### ISSUE TITLE
(GSDX) Timesplitters 1 (broken in both DX and GL)

### ISSUE THREAD

**Issue by LasagnaPie** [PCSX2/pcsx2#45] opened 2014-05-12 00:19 UTC
In OpenGL 2D is broken, you can't navigate through the options and the hud is invisible
in Direct3D11 lights bleed though the walls and is totally unplayable like that. 

![t2-gl](https://cloud.githubusercontent.com/assets/7449866/2940082/6169b1b6-d96d-11e3-9dca-330f6fd89d49.jpg)
![t2-dx](https://cloud.githubusercontent.com/assets/7449866/2940083/69998550-d96d-11e3-97c7-d84c87d64d9d.jpg)

PCSX2 1.3.0.5927
Radeon 5770HD / Phenom 955 X4 3.5ghz
- [x] Broken GUI issue on Opengl (hardware mode) seems to be fixed on the latest development builds ( was already fixed on D3D backends )
- [x] light bleed bugs are still present at all the hardware renderers. here I'll give a even more simpler comparison of the bug. (Tried pretty much all the settings and didn't get anywhere )

**Comment by gregory38** [comment] 2015-06-30 10:14
Could you test the build of this thread http://forums.pcsx2.net/Thread-GSdx-2-0 ?
Note: OpenGL only

**Comment by ssakash** [comment] 2015-11-08 04:35
@gregory38 

- [x] Broken GUI issue on Opengl (hardware mode) seems to be fixed on the latest development builds ( was already fixed on D3D backends )

- [ ] light bleed bugs are still present at all the hardware renderers. here I'll give a even more simpler comparison of the bug. (Tried pretty much all the settings and didn't get anywhere )

#### Hardware mode (OpenGL)
![hardware-mode] (http://ultraimg.com/images/gsdx_20151108021911.png)

#### Software mode (OpenGL)
![software-mode] (http://ultraimg.com/images/gsdx_20151108021930.png)

D3D9 and D3D11 hardware renderers also seems to share the same issues, doesn't seem to be a regression. older versions like 0.9.8 , 1.0.0 , 1.2.1 have way more light bleed issues than the current master branch.

**Comment by gregory38** [comment] 2016-09-07 20:53
A test on latest build will be nice. Several depth issue were fixed, hopefully it would be good for this game.

**Comment by Filipianosol** [comment] 2016-09-08 09:29
The problem now only occurs on hardware D3D renderers, OGL is fixed.
<img width="960" alt="no light bleed" src="https://cloud.githubusercontent.com/assets/12639838/18344360/36195d66-75b7-11e6-9270-781471f456c9.png">
Something minor is that light flares fade when the crosshair overlays them, but I suppose it's the game's fault, since it's like that in software, too.

**Comment by AmbientMalice** [comment] 2016-09-08 12:31
>Something minor is that light flares fade when the crosshair overlays them, but I suppose it's the game's fault, since it's like that in software, too.

Last time I checked, TimeSplitters 2 had some rendering errors with the handheld computer in software mode, so beware of writing off visual issues as game bugs just because the SW renderer has them.

**Comment by MrCK1** [comment] 2016-09-08 15:35
Anybody able to check #1128 - it has the same depth issue with sprites shown here

**Comment by gregory38** [comment] 2016-09-08 15:37
Yes I know there are some remaining bug in the SW renderer. I pushed a new GSdx hack to avoid another SW/HW renderer limitation. Could you test latest git with the following hack
```
UserHacks_AutoFlush = 1
```
There is a huge probability that it won't have any impact but you know.

**Comment by FlatOutPS2** [comment] 2016-09-12 21:12
> Anybody able to check #1128 (Russia with Love) - it has the same issue shown here

That hasn't been solved. The lights in that game also cause massive slowdown. The game runs at over 100 fps when facing away from the lights, and in single digits when looking towards the lights. The slowdown also affects Software mode, but is less severe.

**Comment by MrCK1** [comment] 2018-02-24 19:34
@FlatOutPS2 Can you restest this game as well?

**Comment by FlatOutPS2** [comment] 2018-02-24 19:51
@MrCK1 I don't have the game.

**Comment by MrCK1** [comment] 2019-01-20 23:07
Issue is resolved on DX11.

**Closed by MrCK1** 2019-01-20 23:07 UTC
Labels: Bug, Fixed in OpenGL, GSdx: Hardware, Plugin: GSdx
