### ISSUE TITLE
Tekken 5, upscale issue with certain stages.

### ISSUE THREAD

**Issue by LuismaSP89** [PCSX2/pcsx2#1865] opened 2017-03-16 14:09 UTC
***PCSX2 version:***
PCSX2 v1.50-dev-1934-ga3efc77 (March-16th-2017)

 ***Plugins used:***
AVX2, Using OpenGL
 
***Description of the issue:***
Transparent lines over all the screen. Only when you use upscale option. In native resolution works ok. Maybe an issue with the texture filtering.

***How to reproduce the issue:***
Start tekken 5 with a IR 2x or higher, then go to "for example" moonlit wilderness stage.

***Last known version to work:***

I think this is a very old issue, never tested a version that solves this. And i don´t know if even is possible to solve.

GS Dump Attached:

https://we.tl/GwlFLRl0xS

Maybe related to this? 

https://github.com/PCSX2/pcsx2/issues/1413

**Comment by gregory38** [comment] 2017-03-16 16:42
Depends on the version `UserHacks_merge_pp_sprite = 1` could fix the issue but create others regression.

**Comment by FlatOutPS2** [comment] 2017-03-16 16:59
Duplicate of: https://github.com/PCSX2/pcsx2/issues/638

**Closed by FlatOutPS2** 2017-03-16 16:59 UTC
Labels: Duplicate
