### ISSUE TITLE
[BUG]: GamePad Quick Setup dont work properly.

### ISSUE THREAD

**Issue by Softernet** [PCSX2/pcsx2#5241] opened 2021-12-31 16:25 UTC
### Describe the Bug

When the DirectInput checkbox is checked, Quick Setup captures mouse input when the Mouse API is disabled and without mouse movement, along with a keyboard button press. After that, the next keystrokes are not registered. 

### Reproduction Steps

1. Launch PCSX2 with default settings or enable DirectInput in Gamepad settings.
2. Start quick setup on the PadX tab and try to finish it. 

### Expected Behavior

The Quick Setup procedure should succeed. 

### PCSX2 Revision

v1.7.2183

### Operating System

Windows 10 (64bit)

**Comment by dezraj** [comment] 2022-01-02 11:20
I'm having this exact experience when trying to quick setup my PS4 controller with native Direct Input drivers.

**Comment by exalented** [comment] 2022-01-26 06:04
v1.7.2261
Arch Linux kernel v5.16.2
DS4v1 and Wired XBone controller are both detected and rumble, but niether work when attempting to set inputs.

**Comment by F0bes** [comment] 2022-01-26 06:05
You don't set inputs traditionally on Linux. It should be plug and play.

**Comment by Mrlinkwii** [comment] 2022-08-15 10:15
is this still an issue on latest master ?

**Comment by dezraj** [comment] 2022-08-15 12:29
> is this still an issue on latest master ?

You mean in the Wx version only, right? It's been some months since I don't use it. I'll test it and report it here as soon as I can.

**Comment by Mrlinkwii** [comment] 2022-08-15 12:29
@dezraj  try QT /WX

**Comment by Softernet** [comment] 2022-08-15 18:33
> is this still an issue on latest master ?

Yes.



> try QT /WX

QT version don`t implement the function Quick Setup.

**Comment by dezraj** [comment] 2022-08-16 07:22
I also confirm that the issue is still present in latest master (pcsx2-v1.7.3212-windows-64bit-AVX2-wxWidgets). When I click on "Quick setup", as soon as I hit the Select button in the DS4 controller, L3 is immediately registered without me doing anything with the controller nor with the mouse.

In Qt we have Automatic binding, but when we click there Qt already offers the option "SDL PS4 Controller" and when we select it everything is automatically mapped accordingly based on the SDL database, and I think it is fine the way it is.

**Comment by Mrlinkwii** [comment] 2022-12-11 13:11
sorry for not getting back , if the only issue is WX , WX is deprecated and nearly dead ,  so i think this issue may be  closable , Please use QT

**Comment by lightningterror** [comment] 2022-12-12 04:29
Closing as it is an wx only issue.

**Closed by lightningterror** 2022-12-12 04:29 UTC
Labels: Bug, GUI/WX, PAD: Windows
