### ISSUE TITLE
[BUG]: memory cards can't be selected in the per-game properties settings window

### ISSUE THREAD

**Issue by checktext00** [PCSX2/pcsx2#11213] opened 2024-05-08 14:49 UTC
### Describe the Bug

Memory cards can't be selected in the per-game properties settings window if you already loaded it in a slot it in the main global memory cards setting

### Reproduction Steps

1. Load a memory card into a slot in the global memory cards settings window (that card now becomes "locked" and unavailable to click and drag from the list below)
2. Right-click on a game title and click Properties for the game-specific settings window, go to Memory Cards section
3. That memory card can't be interacted with, and the slot is locked as well (can't swap cards)

### Expected Behavior

It should be possible to override any memory card global setting, you might for example want to change game-specific settings like
- change the slot of that memory card
- make sure that memory card is always loaded
- swap another card to use for that game in that slot
- etc...

### PCSX2 Revision

1.7.5788

### Operating System

macOS 11 (Big Sur)

**Comment by Mrlinkwii** [comment] 2024-05-08 14:52
looks like a duplicate of #10723

**Closed** 2024-05-08 15:10 UTC
Labels: Bug
