### ISSUE TITLE
Warship Gunner 2 sorting problems are back

### ISSUE THREAD

**Issue by disastranagant** [PCSX2/pcsx2#1723] opened 2016-12-27 22:50 UTC
***PCSX2 version:***
Latest dev build v1.5.0-dev-1744-g8fecd35

***PCSX2 options:***
Default settings
***Plugins used:***
default gsdx ogl hardware settings
***Description of the issue:***
The most obvious symptom is a thick greyish band in the middle of the screen that is supposed to be the distance fog.  Also shows up with submerged explosions showing on top of the water.

***How to reproduce the issue:***
Play any level with land, center land on screen, look at the grey band over everything.
Screenshot from one of the tutorial missions http://i.imgur.com/O4MZPcm.png

***Last known version to work:***
Last tested in v1.5.0-dev-1511-gbc7aa1a

***PC specifications:***
i5-4570, 8gb ram, geforce 760, windows 8.1 x64.

**Comment by willkuer** [comment] 2016-12-27 23:13
Can you please check whether [the latest build](https://github.com/PCSX2/pcsx2/commit/8fecd3512ccc86bcc4c23f5f8431a01c61b0b34f) works? If not can you please give [this build](http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.5.0-dev-744-g24a673c&platform=windows-x86) a try? It is around the time were the other issue was closed.

**Comment by disastranagant** [comment] 2016-12-27 23:20
You mean the build mentioned first thing in the post and a build from long before the last known working build?

**Comment by willkuer** [comment] 2016-12-27 23:22
Sorry I misread your comment. I shouldn't comment here while being tired.

**Comment by disastranagant** [comment] 2016-12-27 23:30
new last working: pcsx2-v1.5.0-dev-1714-gc2587ab
Touch VIF, break game with VIF issues :V

**Comment by disastranagant** [comment] 2016-12-27 23:40
1737 works, so it's not the VIF stuff

**Comment by disastranagant** [comment] 2016-12-27 23:51
Looks like the problem starts in the latest build.

**Comment by FlatOutPS2** [comment] 2016-12-28 01:23
It's caused by this commit (1380): https://github.com/PCSX2/pcsx2/commit/f77c1900faf2baa3ffd1ca538f3b444c743b2444

**Comment by disastranagant** [comment] 2016-12-28 01:36
Can't be, the build for that works, and so do many subsequent builds https://github.com/PCSX2/pcsx2/commit/f77c1900faf2baa3ffd1ca538f3b444c743b2444

**Comment by disastranagant** [comment] 2016-12-28 01:47
a relevant screenshot http://i.imgur.com/6ZGqCx1.png

**Comment by gregory38** [comment] 2016-12-28 08:06
Several games seem to suffer on a depth regression. My guess was texture change for Jak II. And based on flatout's feedback, it seems to be the case.

**Comment by FlatOutPS2** [comment] 2016-12-28 10:43
> Can't be, the build for that works, and so do many subsequent builds
I've tested 8 builds today, so far only the latest doesn't work. 1714, 1720, 1737, 1740, 1742, 1744 (the problem), 1511 (the control), and now 1380.

You might want to check if you're using the same (GSdx)settings/Renderer in all those builds. Direct3D (Hardware) renderers don't show the issue anymore.

**Comment by disastranagant** [comment] 2016-12-28 20:39
OpenGL hardware is default on all tested builds.  The only one that might have altered gpu settings is 1511 since I don't think I changed it back from whatever I was last using to make one of the Armored Core games work.

**Comment by FlatOutPS2** [comment] 2017-01-09 11:32
The issue has been resolved in the latest master.

**Closed by FlatOutPS2** 2017-01-09 11:32 UTC
Labels: Plugin: GSdx, Regression
