### ISSUE TITLE
[BUG]: Bleach Blade Battlers 2nd needs "Disable Depth Emulation" for HW mode else it displays artifacts

### ISSUE THREAD

**Issue by AkiyoSSJ** [PCSX2/pcsx2#7285] opened 2022-10-27 10:57 UTC
### Describe the Bug

The game shows huge graphical artifacts and distortions in HW mode if played without the hardware fix "Disable Depth Emulation".

### Reproduction Steps

Play the game normally in HW mode with any render and without any hardware fix.

### Expected Behavior

No artifacts, graphic is displayed normally.

### PCSX2 Revision

v1.7.3490

### Operating System

Windows 10 (64bit)

### CPU

Xeon E3-1271 v3

### GPU

RX 580

**Comment by stenzek** [comment] 2022-10-27 10:59
Sounds like a duplicate of #5299. Also no GS dump provided.

**Closed by stenzek** 2022-10-27 10:59 UTC
Labels: Bug
