### ISSUE TITLE
[BUG]: Broken Fog in Burnout 3

### ISSUE THREAD

**Issue by ElTioRata** [PCSX2/pcsx2#5529] opened 2022-02-15 00:52 UTC
### Describe the Bug

This is a known issue (already quoted in the wiki), I made this issue thread to track any progress on fixing it and hopefully be marked as solved.

- **Description:** Fog in this game is not properly emulated and barely renders as a result.
- **Workaround:** Use Software mode.

### Reproduction Steps

Start any track of the game with fog in Hardware mode.

### PCSX2 Revision

v1.7.2373

### Operating System

Windows 10 (64bit)

### CPU

AMD FX-8350

### GPU

NVIDIA GeForce GTX 1060

**Comment by MrCK1** [comment] 2022-02-15 01:20
Can you provide steps to reproduce (what track/event) and some pictures?

**Comment by ElTioRata** [comment] 2022-02-18 22:13
The issue is present in all tracks with fog, I'm providing screenshots from two tracks.

Alpine Expressway (up is HW and down is SW)
![hardware](https://user-images.githubusercontent.com/19964653/154768197-7d4001bb-ea65-47e4-8d44-5935990a7485.png)
![software](https://user-images.githubusercontent.com/19964653/154768216-f2925b30-7c8a-463c-a2c9-b8bde5b5ec7e.png)
Silver Lake (up is HW and down is SW)
![hardware2](https://user-images.githubusercontent.com/19964653/154768238-81d23048-ca75-416c-9cea-4c6e7
![software2](https://user-images.githubusercontent.com/19964653/154768249-c356fdf2-404d-4bbf-8451-ac7d86d84885.png)
bbd16e1.png)

**Comment by MrCK1** [comment] 2022-02-18 22:17
It looks like there's something else going on, please post your GS settings including the hacks tab.

**Comment by ElTioRata** [comment] 2022-02-18 22:29
![hw](https://user-images.githubusercontent.com/19964653/154769433-02a88918-bedd-40b3-a9c0-42bcba2a15f3.png)
![renderer](https://user-images.githubusercontent.com/19964653/154769438-23ab0049-7d2d-4b31-9c6d-04ac0d097e97.png)
Btw, I just found out that unticking the "Disable Depth Emulation" fixes the issue but it introduces some sort of line that follows the game camera, I guess that's where the fog effect fades in.
![line](https://user-images.githubusercontent.com/19964653/154769599-4c323b55-2157-45af-8116-0e1e1f6fa988.png)

**Comment by RedDevilus** [comment] 2022-02-18 22:31
Yeah that's just the depth line that isn't really visible on native resolution. sidenote: None interlacing doesn't mean progressive or no-interlacing.

**Comment by MrCK1** [comment] 2022-02-18 22:31
You shouldn't have Disable Depth Emulation enabled for any reason really, it will cause issues like you are seeing. 

Use half pixel offset to get rid of the line. Closing since  it's confirmed not to be a valid bug.

**Closed by MrCK1** 2022-02-18 22:31 UTC
Labels: Bug
