### ISSUE TITLE
Freekstyle Invisible Walls

### ISSUE THREAD

**Issue by RevengaDevelop** [PCSX2/pcsx2#3754] opened 2020-09-25 13:43 UTC
PCSX2 version
development builds v1.7.0-dev-338

PCSX2 options:
the Safest config, no speedHacks, EE/OIP default config, VUs default config

Plugins used:
       Bound   GS: GSdx32-AVX2.dll [GSdx 20200925002642 (MSVC 19.26 AVX2/AVX2) 1.2.0]
	Bound SPU2: Spu2-X.dll [SPU2-X 20200925002642 2.0.0]
	Bound  USB: USBnull.dll [USBnull Driver 20200925002642 0.7.0]
	Bound DEV9: DEV9null.dll [DEV9null Driver 20200925002642 0.5.0]

Description of the issue:

Into the maps, there's a lot of invisible walls, so, if you are going on your way, and you will do any trick, immediately you will crash.

There are some jumps that require you to go through a ring of fire or over a massive object back onto the road, those seem to vary the most, sometimes you can NOT pass over them or through them, sometimes you can), and some jumps require you to go over it at a weirdly specific location or specific speed or you will crash into a massive invisible wall.

I've tried many other configs and i couldn't fix it.

Here's 2 videos displaying the bug (I don't own the videos)
Player Crashing:
https://www.youtube.com/watch?v=pIIbQumfXyU
NPC's Crashing:
https://www.youtube.com/watch?v=mjGg0Da37iU

How to reproduce the issue:
select any track (preferably, the second track) and try to do any trick on the jumps. in any moment, you just going to crash, appearly without explanation.

Last known version to work:
the bug it's present in:
stable build v1.6.0
stable build v1.4.0
stable build v1.0.0

Operating System =  Microsoft Windows 10 Pro (build 19041), 64-bit
Physical RAM     =  32720 MB
CPU name         =  Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Graphic Card     =  Nvidia GeForge GTX 645

**Comment by atomic83GitHub** [comment] 2020-09-25 14:10
Yeah this is a real bug, I have the game too and I was looking into this funny enough, unfortunately it is very hard to track and debug, I will stick the core issue label.

**Comment by refractionpcsx2** [comment] 2020-10-27 09:39
Is it any better if you use a build from #3816 ?

**Comment by kozarovv** [comment] 2021-06-29 20:00
While this bug was hard to reproduce, almost random. I can't get it to occur in latest master at all. Some more test should be done before closing this issue, but it seems to be fixed now.

**Comment by refractionpcsx2** [comment] 2021-06-29 20:01
That's good to hear! I wonder what fixed it 🤔

**Comment by Crash2240** [comment] 2022-02-08 21:35
I know these posts are old, but did anyone find a fix? I've searched up this issue and found posts on the pcsx2 forums and reddit but nothing I found had an answer. As stated here and elsewhere it's an issue with the "rounding" which I've tried changing and none of the options seem to do anything. I've even downloaded a build from the time of these posts (v1.7.2312) as it's stated here that fixed it. I've been using the, at the time of posting, latest build (v1.7.2350) and it's still an issue. If anyone has a fix or knows a workaround, I'd appreciate it. Thaks in advance.

**Comment by refractionpcsx2** [comment] 2022-02-08 21:38
No fix yet, sorry.

**Comment by metalstyle-user** [comment] 2022-02-09 01:58
I just play the GameCube one on dolphin.. it works great, just takes a
minute to get the controls in position.

**Comment by anarcopossum** [comment] 2022-07-20 06:08
are there any other games that use the same engine? maybe there is a way to fix it via that?

**Comment by Mrlinkwii** [comment] 2023-04-12 11:06
I assume still an issue  on latest nightly ?

**Comment by AmyRoxwell** [comment] 2023-06-14 07:50
I had actually tried to recreate the bug showcase on the video, same map and even the zone, It doesn't seem to happen anymore  and we can finally closed this and be happy :)
Video Solo: https://www.youtube.com/watch?v=zF10FPbyjMc
Video AI: https://www.youtube.com/watch?v=EiHhQz6fF7Q

**Comment by anarchopossum** [comment] 2023-06-21 23:00
I can try it out sometime soon. The issue I commonly find is in the first map in the campaign. The mega jump near the end of the [first map](https://youtu.be/T8xT-D0jg_s?t=628) of the Campaign. I wonder if it's an issue with just campaign or what.

**Comment by AmyRoxwell** [comment] 2023-06-27 08:28
> I can try it out sometime soon. The issue I commonly find is in the first map in the campaign. The mega jump near the end of the [first map](https://youtu.be/T8xT-D0jg_s?t=628) of the Campaign. I wonder if it's an issue with just campaign or what.
> 
> I do wonder though what engine this game runs on, because if there are other games that use a similar engine I think it would help out to debug

I tried to see if it happened on that map but I wasn't able to make it work in there tho, So I'm pretty sure it is fixed or just so rare than it will be almost impossible to encounter unless someone invest hours recording :b

**Comment by anarchopossum** [comment] 2023-06-27 23:47
> > I can try it out sometime soon. The issue I commonly find is in the first map in the campaign. The mega jump near the end of the [first map](https://youtu.be/T8xT-D0jg_s?t=628) of the Campaign. I wonder if it's an issue with just campaign or what.
> > I do wonder though what engine this game runs on, because if there are other games that use a similar engine I think it would help out to debug
> 
> I tried to see if it happened on that map but I wasn't able to make it work in there tho, So I'm pretty sure it is fixed or just so rare than it will be almost impossible to encounter unless someone invest hundreds of hours recording :b

Yeah I tried it out too and Have no issues on the Mac Version. I think we can close this now

**Comment by refractionpcsx2** [comment] 2023-06-28 08:04
Just to point out, you need to jump near the edges of the ramps in order to trigger the problem

**Comment by anarchopossum** [comment] 2023-06-28 08:48
> Just to point out, you need to jump near the edges of the ramps in order to trigger the problem

I see well i can try that out again soon

**Comment by AmyRoxwell** [comment] 2023-07-02 03:13
> Just to point out, you need to jump near the edges of the ramps in order to trigger the problem

I tried for an whole hour on the map that the video takes place, couldn't trigger it, I tried like 20 minutes on the first map and neither that, the only time I saw me or the bots crashing was when we run against each other but thats normal for the game lol.

If @anarchopossum can't trigger it then we maybe its a good idea to close as solved by witchcraft or something smh

**Comment by anarchopossum** [comment] 2023-07-02 04:34
> > Just to point out, you need to jump near the edges of the ramps in order to trigger the problem
> 
> I tried for an whole hour on the map that the video takes place, couldn't trigger it, I tried like 20 minutes on the first map and neither that, the only time I saw me or the bots crashing was when we run against each other but thats normal for the game lol.
> 
> If @anarchopossum can't trigger it then we maybe its a good idea to close as solved by witchcraft or something smh

Yeah I tried again and nothing. I think we are golden on this oddly lol

**Comment by AmyRoxwell** [comment] 2023-07-02 04:48
@refractionpcsx2 well, what do you think? should we try more testing or just close it and wait if someone that plays has this issue?

**Comment by refractionpcsx2** [comment] 2023-07-02 11:40
I guess close it for now if nobody can reproduce it.  If they come across it again, we can reopen the issue.

**Comment by Pants44** [comment] 2023-08-11 04:24
I've been able to recreate this issue. On the second map, when you do the jump over the coal minecarts. There are infinitely tall invisible walls. I crashed through the first, made it really high for the second and still heard the collision

**Comment by AmyRoxwell** [comment] 2023-08-11 07:20
> I've been able to recreate this issue. On the second map, when you do the jump over the coal minecarts. There are infinitely tall invisible walls. I crashed through the first, made it really high for the second and still heard the collision

Do you have a video about it?
What version of PCSX2 are you using? 
Are you using default settings?

**Comment by anarchopossum** [comment] 2023-08-13 03:54
@Pants44 what lap were you on when the issue occurred?

**Comment by lightningterror** [comment] 2024-04-16 21:42
Re opening as it was stated it's not yet resolved.

**Comment by AmyRoxwell** [comment] 2024-04-17 19:40
> Re opening as it was stated it's not yet resolved.

But the person that said that never answer, neither provided anything that proves he wasnt using an older version, I tried to recreate it multiple times and same goes for @anarchopossum

**Comment by lightningterror** [comment] 2024-04-17 20:36
It was also tested by one of our testers and indeed it can no longer be reproduced.

**Closed by lightningterror** 2024-04-17 20:36 UTC
Labels: Core, Bug - Unknown Source

**Comment by DigitalMajestic** [comment] 2024-04-17 21:00
I tried both on latest and a build from April 10 2023 and was unable to reproduce.

I have a hazy memory of this issue popping up again occasionally so it’s possible this will come up again but for now I’m fairly confident in saying it’s fixed.

**Comment by PS2ZLUT** [comment] 2025-08-02 13:25
“SOLVED” idk wtf version pcsx2 but I can say go to first bikes over others (tested with wife beating Mike) the gnome was cancer I rather dip myself in the mine cart for eternity…. Anyway best tested with invisible wall strategy coming from a PS2 ZLUT drunk for hours smacking existence back into one’s self during the family reunion bc gaming is life FML. SEE YALL IN HEELLLLL GL XD!
