### ISSUE TITLE
[BUG]: Naruto Uzumaki Chronicles 1 (and 2)

### ISSUE THREAD

**Issue by WilliamVaz** [PCSX2/pcsx2#7828] opened 2023-01-09 09:28 UTC
### Describe the Bug

The game crashes when entering the TUTORIAL. last emulator version. 

(Crashes also happen in Naruto Uzumaki Chronicles 2, at times like the fight against Kankuro in Chapter 3.)

### Reproduction Steps

The game crashes when entering the TUTORIAL. last emulator version. 

(Crashes also happen in Naruto Uzumaki Chronicles 2, at times like the fight against Kankuro in Chapter 3.)

### PCSX2 Revision

Any version of the latest

### Operating System

Windows 10 (64bit)

**Comment by RedDevilus** [comment] 2023-01-09 09:33
Last warning, don't make issues and appeal.

**Comment by stenzek** [comment] 2023-01-09 09:35
Duplicate of #7827 which was closed for piracy.

**Closed by stenzek** 2023-01-09 09:35 UTC
Labels: Bug

**Comment by stenzek** [comment] 2023-01-09 09:42
Your video in the previous issue contained pirated content. As per our community rules, we cannot facilitate piracy, as it exposes us to legal risk.

If it's such a "stupid emulator", then why are you even using it?

**Comment by WilliamVaz** [comment] 2023-01-09 09:46
It explains why you are a garbage can

**Comment by RedDevilus** [comment] 2023-01-09 09:47
Okay Mr Nice guy. You can leave now.

**Comment by stenzek** [comment] 2023-01-09 09:48
I'm a bucket, not a garbage can, thank you very much : - )

**Comment by LeoKids** [comment] 2023-05-30 17:07
Boomer!
