### ISSUE TITLE
[BUG]: Time Crisis 2 Visual bugs

### ISSUE THREAD

**Issue by Comfarol** [PCSX2/pcsx2#8835] opened 2023-05-12 22:49 UTC
### Describe the Bug

I noticed this issue again on newer version 1.7.4446 also tried 1.7.4490
last version i tried doesn't seem to have it 1.7.4379

could be related to? https://github.com/PCSX2/pcsx2/issues/5966#issuecomment-1357013225

### Reproduction Steps

play game in vulkan and issue is most observable in level 2.

### Expected Behavior

Shouldn't be any

### PCSX2 Revision

v1.7.4490

### Operating System

Windows 10 (64bit)

### CPU

5800x3D

### GPU

GTX 3070

### GS Settings

vulkan
3x native 1080p
anistropic filtering 16x
anti blue
no interlacing patch

### Emulation Settings

0 frames 
optimal frame pacing

### GS Window Screenshots

![image](https://github.com/PCSX2/pcsx2/assets/27315987/9eff2631-37f1-4ce4-934c-e56684253fb3)

![image](https://github.com/PCSX2/pcsx2/assets/27315987/62dec075-4b9e-47ea-9411-5ef2674370c2)

### Logs & Dumps

https://github.com/PCSX2/pcsx2/files/11363281/Time.Crisis.II_SLUS-20219_20230501132032.gs.zst.zip

**Comment by refractionpcsx2** [comment] 2023-05-12 22:51
could you possibly try a few versions between  1.7.4446 and 1.7.4379 to see if you can narrow it down? A binary search would be a good idea, so try 4400 and see if that's ok, if not try 4390, if it is ok try 4415, and so on :) It would be super helpful.

Thanks!

**Comment by refractionpcsx2** [comment] 2023-05-12 22:56
hmm, if you load the GS dump yourself does it look broken? Because it looks fine here :/

![image](https://github.com/PCSX2/pcsx2/assets/6278726/27059877-315a-4d64-9203-08982f12c2a8)


If it does, it might be your Nvidia drivers are busted. I'm using the 528 drivers because the new ones are kind of terrible :D

**Comment by Comfarol** [comment] 2023-05-12 23:17
My nvidia driver is 516.94.

But the issue flickers in and out. I will try some other versions

**Comment by Comfarol** [comment] 2023-05-13 00:24
so 4400 was fine. 4415 had the glitch. Need more?

**Comment by refractionpcsx2** [comment] 2023-05-13 00:26
Can you first try updating your graphics drivers to one of the 528 versions please? Just to rule that out, because I cannot reproduce it by loading the GS Dump which usually means you have a driver problem (or when you updated you didn't  update the resources folder, but less likely)

**Comment by Comfarol** [comment] 2023-05-13 00:48
strange, even with 528.49 it still happens for me
![image](https://github.com/PCSX2/pcsx2/assets/27315987/4deb00cc-a821-40c0-9987-9274dc1a0577)

[Time Crisis II_SLUS-20219_20230513102538.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/11468514/Time.Crisis.II_SLUS-20219_20230513102538.gs.zst.zip)

**Comment by refractionpcsx2** [comment] 2023-05-13 01:05
Absolutely fine here :/

![image](https://github.com/PCSX2/pcsx2/assets/6278726/234fd0a7-f40f-4c04-b46e-5a69437dd620)

First I would try clearing out your `cache` folder (everything but the gamelist files)

if that doesn't help, try renaming your `inis` and `gamesettings` folders to have `bak` on the end so you can restore them after if it makes no difference, and try running with default settings, nothing custom, see if that works fine.

**Comment by Comfarol** [comment] 2023-05-13 02:07
with fresh 4415 extract, only thing i changed and used was changed to 1080 vulkan and used a savestate i made in 4400.
![image](https://github.com/PCSX2/pcsx2/assets/27315987/720b748b-5a7c-474d-a226-24829b4fd9f2)

:|

**Comment by Comfarol** [comment] 2023-05-13 02:18
ok i tried 4410, 4413, and problem starts in 4414 for me.

**Comment by refractionpcsx2** [comment] 2023-05-13 04:42
just to confirm you can reproduce it by opening the GS Dump you sent me, right? not running the game. Because if it's fine on the GS Dump for you too, then that would explain why it works fine for me but not you, since you seem to be running the game instead.

**Comment by Comfarol** [comment] 2023-05-13 06:42
Yes, it happens when i run the gs dump too.

**Comment by bigol83** [comment] 2023-05-13 09:37
It doesn't happen to me checking that gsdump with latest nightly 1.7.4500 and Nvidia drivers 531.61
![tc2](https://github.com/PCSX2/pcsx2/assets/38129260/5824f63e-9e38-4466-8b29-0df76a328867)

**Comment by coornio** [comment] 2023-05-14 22:18
Tried the dumps out of curiosity but I'm also not getting the issue. If anything, the only problem I see is software being semi-broken because it looks like it's merging interlaced lines, and thus text breaks to a degree and becomes unreadable as a result.

**Comment by Comfarol** [comment] 2023-05-15 00:47
If i enable disable depth emulation in hardware hacks it removes the checker boarding glitch in the gs dump.

**Comment by coornio** [comment] 2023-05-15 09:23
> If i enable disable depth emulation in hardware hacks it removes the checker boarding glitch in the gs dump.

In my case, if I have blending on minimum to produce the effect seen in my last picture, it does indeed remove the checker pattern. If I let the default blending on and use it, it outright removes this light shaft/fog effect from the game.

Ultimately there's still something odd going on at your side which we'd need to figure out :D

**Comment by Comfarol** [comment] 2023-05-16 03:16
yeah something going on. If i change my blending to anything it still there.

**Comment by refractionpcsx2** [comment] 2023-08-14 21:36
Does this still happen?

**Comment by Comfarol** [comment] 2023-08-15 07:18
Haven't had a chance to try any new versions lately. I've been kinda satisfied with enabling 'disable depth emulation' to remove the glitches.

If i get a chance this weekend ill experiment

**Comment by Comfarol** [comment] 2023-09-20 03:09
I played through TC2 today twice on 1.7.5033 and didn't notice any checker boarding on the fog in the distance while playing. I did notice it however in the demo. Minor issue i guess.

**Comment by Comfarol** [comment] 2023-10-03 21:37
I've reformatted my pc to windows 11 fresh. I will retest this soon.

**Comment by Comfarol** [comment] 2023-10-06 06:49
Actually reformtatted w10. But retested those areas and didn't notice any issues.

**Comment by Mrlinkwii** [comment] 2023-10-06 10:57
since you mentioned all is good im going close this issue :)

**Closed by Mrlinkwii** 2023-10-06 10:57 UTC
Labels: Bug, GS: Hardware
