### ISSUE TITLE
Time Crisis 2/3 Timing issues with some BIOS revisions

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2475] opened 2018-06-09 09:58 UTC
***PCSX2 version:***
1.5dev 2400

***PCSX2 options:***
All default, speedhacks off

***Plugins used:***
All defaults

***Description of the issue:***
The games "Time Crisis 2" and "Time Crisis 3" fails to load on some BIOS revisions (Tested on 2 differents PS2 slim BIOS)

- PAL 2.0 (rev 14/06/2004) load them fine
- USA 2.2 (rev 10/02/2006) fails to load them with the following error: sce1394SbEui64(): failed -1

Note: set the EE cyclerate to -3 allow the games to work on the 2.2 BIOS.

***How to reproduce the issue:***
Load Time Crisis 2 or 3 on a 2.2 BIOS (or other than 2.0).

***Not a regression***

***PC specifications:***
AMD fx8350 GTX 1060 Windows 10 64bits

**Comment by Syst3mSh0ck** [comment] 2018-06-10 06:52
Looks like this is caused by a lack of BIOS .nvm section as mentioned here: https://forums.pcsx2.net/archive/index.php/thread-38332.html

sce1394SbEui64 seems to be an IOP function related to I/O likely used during Guncon enumeration.

**Comment by atomic83GitHub** [comment] 2018-06-10 08:18
Humm, maybe it's not related because when I boot the game with EE cyclerate -3, this error still appear but is not fatal.

**Comment by kozarovv** [comment] 2020-08-09 08:53
Can you retest this with latest master by any chance? There were changes to timers since then, maybe it is fixed now.

**Comment by seta-san** [comment] 2020-10-16 23:12
This is a firewire issue, not a timing issue

**Closed** 2020-10-18 17:05 UTC
