### ISSUE TITLE
[Feature Request]: MGS2 blending suggestion

### ISSUE THREAD

**Issue by RaduNastase** [PCSX2/pcsx2#7185] opened 2022-10-13 04:02 UTC
### Description

Moving the blending code for Ocelot/Fatman/Vamp correct skin, from high to medium (or even basic if possible) blending accuracy.

### Reason

It would be a great addition to the overall experience, as some scenes that do not necesarily need high blending (like Olga fight in Tanker) are noticeably slower in high blending, which one would have to set, in order to not be forced to keep switching between settings mid-game.

Thank you so very much for all you efforts!

### Examples

  Some portions take a big hit in high blending, without actually needing that level of blending, so an all around solution would be fantastic.

**Comment by stenzek** [comment] 2022-10-13 04:09
There's no "blending code" for different "correct skin", certain equations and overlap behaviours will trigger sw blend depending on the level.

Making decisions based on one game is also foolish - it might end up worse for the general case and others. But I'll leave this open for others to comment on, maybe LT has some insight here. But considering you didn't even provide a GS dump, I couldn't say which equation it's using and/or why it's slow.

**Comment by RaduNastase** [comment] 2022-10-13 04:37
Hy stenzek

Here is a post regarding the moving of this blending method from full to high.

https://github.com/PCSX2/pcsx2/pull/5196

My proposal is for it to be moved lower to medium, of at all possible.

**Comment by stenzek** [comment] 2022-10-13 04:51
That's not a GS dump.

And moving it from high to medium will likely just make medium as slow as high in everything else, except for the `A==1` case.

So, really, nothing will change? This code is not MGS specific.

**Comment by stenzek** [comment] 2022-10-13 04:55
Actually, this is a duplicate of https://github.com/PCSX2/pcsx2/issues/5242, I completely forgot about it..

**Closed by stenzek** 2022-10-13 04:55 UTC
Labels: Enhancement / Feature Request

**Comment by RaduNastase** [comment] 2022-10-13 07:43
Thank you very much for you explanation.
