### ISSUE TITLE
[Request] using multi custom shader file

### ISSUE THREAD

**Issue by mondaychicken** [PCSX2/pcsx2#2595] opened 2018-09-14 14:20 UTC
Hi.

Pcsx2 has a lot of custom shader files.  ex) gsdx.fx , guest aa 2.0 , etc , ......

But it is impossible to apply both custome shaders like gsdx.fx + guest aa .

If it can be added combining custom shaders  it will be so nice.

Thanks. 
--------------------------------------------------------------------
PS.
Ishiiruka dolphin emulator has  "RG_SSAA.glsl"  scaling shader file.

This shader file is helpful to remove aliasing like pcsx2 built-in fxaa.
So I thought about making RG_SSAA.glsl to built-in shader. 

How do you think about that?

RG_SSAA.glsl file
[RG_SSAA.glsl.txt](https://github.com/PCSX2/pcsx2/files/2383665/RG_SSAA.glsl.txt)

about dolphin shader
https://github.com/Tinob/Ishiiruka/wiki/Post-Processing-Shaders

resident evil4
 before applying
![rb4j08-1](https://user-images.githubusercontent.com/35862336/45555708-1331c980-b829-11e8-919d-6d7602235818.png)

after applying
![rb4j08-2](https://user-images.githubusercontent.com/35862336/45555720-1c229b00-b829-11e8-96fe-05eec7de373a.png)

**Comment by lightningterror** [comment] 2020-04-27 22:55
Duplicate of https://github.com/PCSX2/pcsx2/issues/3045

**Closed by lightningterror** 2020-04-27 22:55 UTC
Labels: Enhancement / Feature Request, Plugin: GSdx
