### ISSUE TITLE
Restore defaults does not set Enable EE cache (slower) to unchecked in the EE/IOP panel

### ISSUE THREAD

**Issue by bositman** [PCSX2/pcsx2#737] opened 2015-08-05 09:02 UTC
@ssakash  This should be easy, you can have it :)

**Comment by ssakash** [comment] 2015-08-05 10:12
the variable might have not been made on the default list group, just pushed a commit.

 could you check whether the issue is fixed on this patch ? https://github.com/ssakash/pcsx2/tree/patch-43

**Comment by karasuhebi** [comment] 2015-08-05 16:25
@ssakash I don't mean to tell you what to do but I think it would make things easier if you were to name your branches more descriptively, specially when working on multiple branches at once like you tend to do.

**Comment by bositman** [comment] 2015-08-05 16:32
Error	2	error C2039: 'SetDefaultItem' : is not a member of 'pxCheckBox'	D:\pcsx2\pcsx2\gui\Panels\CpuPanel.cpp	154

**Comment by avih** [comment] 2015-08-05 17:22
@ssakash are you randomly touching the code? do you test your patches? Can you compile PCSX2?

Both your patches https://github.com/ssakash/pcsx2/tree/patch-43 (in themselves or combined) don't compile successfully, not to mention not getting near fixing the issue...

Please don't reference branches as possible solutions, and don't submit any PRs before you've verified the following:
1. The patch[es] apply cleanly to the current PCSX2 master branch.
2. PCSX2 compiles successfully with your patch[es] applied.
3. The patches actually fix the issue they're supposed to fix.

**Comment by avih** [comment] 2015-08-05 17:39
Specifically, `SetDefaultItem` is only used by `pxRadioPanel` to set the (bold) font of the default radio button. It's not used to restore the default value at a later time, and therefore it'd be meaningless for a checkbox.

On top of that, adding the prototype `pxCheckbox::SetdefaultItem` and then calling it can't ever compile because you didn't add body for that function. And even if you did add a body and called it on init, nothing will make it restore the default value when the user clicks the Restore-defaults button.

PCSX2 unfortunately uses hardcoded values at the CPU panel both at init and when restoring the defaults. Other panels try to restore the defaults more programmatically (like the speed hacks panel).

Your patches look like someone hitting the KB randomly. If you want to be taken seriously, start acting seriously, and follow the checklist at my previous post.

**Comment by ssakash** [comment] 2015-08-05 18:15
@avih 

didn't take a good look at the code (Mobile) , I assumed it's functions based on the variable name, which didn't turn out very well as shown at the branch.

just had a good look and it seems that the radio buttons use "SetSelection" to have the default states on the OnRestoreDefaults [hardcoded], which isn't applicable for the Checkbox functions. will look into it eventually :)

**Comment by avih** [comment] 2015-08-05 18:18
Just follow my checklist and make sure the patch applies, compiles and do what it's supposed to do before you suggest patches in any way.

**Comment by ssakash** [comment] 2015-08-05 18:28
Got it. Just wondering, it would save a lot deal of trouble if I change the EE cache as a radio button rather than a checkbox. Why is checkbox used though ? It's just two states

**Comment by avih** [comment] 2015-08-05 18:37
Don't.

**Closed** 2015-08-05 21:41 UTC
