### ISSUE TITLE
[BUG]: Metal Gear Solid 3: Subsistence (Disc 1) [SLUS-21359] - Game Crashes After Opening Logos

### ISSUE THREAD

**Issue by BakerIsHungry** [PCSX2/pcsx2#8681] opened 2023-04-16 03:35 UTC
### Describe the Bug

After the RAW CD CHD update was implemented, Subsistence appeared to crash every time it goes through the company logos. On OpenGL and DX11 and DX12, it makes it to the fox logo before crashing. On Vulkan, it makes it to the Dolby logo before crashing. (Note: Game was not compressed.)

### Reproduction Steps

Play Subsistence on any version of PCSX2 Nightly between v1.7.4380.0 and v1.7.4391.0

### Expected Behavior

User should be able to make it to the title screen and play the game from start to end without issue.

### PCSX2 Revision

v1.7.4391.0

### Operating System

Windows 10 (64bit)

### CPU

Intel(R) Core(TM) i7-4790K CPU

### GPU

NVIDIA GeForce GTX TITAN X

### GS Settings

I'm trying to use an HD texture pack, but the effect still exists without using the pack at all.

Widescreen patches are enabled, but them being disabled has no effect on the crashing whatsoever.

Shade Boost is on with values 52, 54, 64, though that shouldn't have any effect whatsoever.

### Emulation Settings

Cheats are enabled, but them being disabled has no effect on the crashing whatsoever.

### Logs & Dumps

[crash-2023-04-15-18-16-12-004.txt](https://github.com/PCSX2/pcsx2/files/11241126/crash-2023-04-15-18-16-12-004.txt)

**Comment by refractionpcsx2** [comment] 2023-04-16 03:39
I find it unlikely the CHD update broke your game since your game is not compressed it won't be using that code, plus it was only the third party stuff that changed, none of our internal stuff.

Can you also provide the .dmp file that went with that text file, so we can have a look at why it crashed.

We had a guy on the discord have a crash after the Konami logo and it somehow pointed at some memory not being allocated, somehow, I have no idea how, but I couldn't reproduce it.

**Comment by BakerIsHungry** [comment] 2023-04-16 03:45
Sure thing. Here you go. Idk if it makes a difference, but I somehow didn't get the .dmp for that .txt file, so here's an updated set.
[MGS3 Crash Bug Report.zip](https://github.com/PCSX2/pcsx2/files/11241150/MGS3.Crash.Bug.Report.zip)

**Comment by refractionpcsx2** [comment] 2023-04-16 03:46
awesome, thanks

**Comment by refractionpcsx2** [comment] 2023-04-16 04:01
hmm can you also to go Tools->Enable File logging, then close and restart PCSX2,  get it to crash again, then close it and upload the emulog.txt from the logs folder.

All signs point to it failing to allocate some memory, same as the other, but it shouldn't have a problem with that :/

And I still can't reproduce it.

**Comment by BakerIsHungry** [comment] 2023-04-16 04:02
Sure. Just one moment.

**Comment by refractionpcsx2** [comment] 2023-04-16 04:03
oh and a picture of your graphics settings (the rendering tab, specifically) might be useful

**Comment by BakerIsHungry** [comment] 2023-04-16 04:10
Here you go. sorry that took so long.
![Sneeter Report Part 2](https://user-images.githubusercontent.com/130881357/232265966-1b620cac-6cd2-493f-87f9-b889a8e0596b.png)
[emulog.txt](https://github.com/PCSX2/pcsx2/files/11241197/emulog.txt)

**Comment by refractionpcsx2** [comment] 2023-04-16 04:15
looks like you didn't restart PCSX2, there's a chunk of log missing, it was more the very beginning I was interested in, could you make a new one?

**Comment by BakerIsHungry** [comment] 2023-04-16 04:15
oh yes sorry about that

**Comment by refractionpcsx2** [comment] 2023-04-16 04:17
okay crash reproduced. If you turn Texture Preloading back on it will mitigate it.

**Comment by BakerIsHungry** [comment] 2023-04-16 04:20
That did it. Thanks for the help!

**Comment by refractionpcsx2** [comment] 2023-04-16 05:32
please don't close it, the PR linked will resolve it :)

**Closed** 2023-04-16 05:35 UTC
Labels: Bug

**Comment by BakerIsHungry** [comment] 2023-04-16 05:40
understood. my bad.
