### ISSUE TITLE
Rewind feature

### ISSUE THREAD

**Issue by InfamousKnight** [PCSX2/pcsx2#3698] opened 2020-09-16 22:53 UTC
A rewind feature will work like this:
When enabled, it would make save states every frame with a new one for each frame(maybe 200 frames in it will start deleting old ones before the 200 frames in).

So for instance, advance 200 frames, 200 save states are made,  advance 100 frames, 100 save states are removed from 0 to 100 and so on so forth.

Would benefit tasers who prefer using a game pad.

**Comment by refractionpcsx2** [comment] 2020-09-16 22:55
I have thought about this feature before, however making savestates is very time intensive on PCSX2, it will likely bring your framerate down to about 20% of what it originally was.  I think mainly the problem is that the GS is on a separate thread so we have to wait for the thread to be idle, otherwise it desync's, it's kinda rough.

**Comment by InfamousKnight** [comment] 2020-09-18 14:02
Seeing how my computer already runs pcsx2 slow even without tools enabled, I can only imagine how much slower this would make it. If speed is the main concern, I may as well look into buying a better computer.

**Comment by lightningterror** [comment] 2020-10-12 14:15
I'll close this for the reasons Ref mentioned.

**Closed by lightningterror** 2020-10-12 14:15 UTC
Labels: Invalid

**Comment by mousebutts** [comment] 2021-04-21 18:48
i suppose it could work if you had a good enough PC, and if you saved a state every 10 seconds maybe? 

i think realistically, it'd be closer in resemblance to the rewind feature on Forza games. (if you crash or something, Press Y to Rewind the game about 5 seconds. Then press it again to go another 5 seconds-ish.)

**Comment by RedDevilus** [comment] 2021-04-21 18:51
It's pretty taxing to the emulator, PC in it's whole like the storage, keeping track correctly. Maybe in a limited interval in the future it could be possible.

**Comment by InfamousKnight** [comment] 2022-04-12 21:51
Do you think with this https://github.com/PCSX2/pcsx2/pull/5854)  pr this could work more reasonably? It speeds up save states big time.

**Comment by RedDevilus** [comment] 2022-04-12 22:07
> Do you think with this #5854) pr this could work more reasonably? It speeds up save states big time.

While it does reduce the latencies for loading and saving the states it will still be unusable for rewind feature, the problem is just shifted to the future a bit.

**Comment by devvratmiglani** [comment] 2024-05-04 14:17
This feature is very interesting,I would really like to have this feature if it can be implemented.

Keep it as an experimental feature and it is worth having it, also the hardware will soon become capable of handling it.

Well I agree that it will not be simple to implement it.

You can experience it in nestopia emulator, we can rewind in it.

Thank you to the pcsx2 community.

**Comment by RedDevilus** [comment] 2024-06-26 01:43
I think that only will ever work on Linux if it ever gets implemented. On Windows it might be too slow to spam savestates in series of x amount of seconds.

**Comment by dewxo** [comment] 2024-06-26 01:44
> Playing the new PS2 emulator on PS5, this Rewind feature is amazing. Such a huge QoL improvement when going back to these older games.
> 
> I understand that it significantly decreases performance and on PS4 it's disabled by default because it causes severe slowdown.
> 
> But as an experimental, optional feature it would be amazing.

You mean it has a rewind feature???

**Comment by dewxo** [comment] 2024-06-26 01:47
Idk but Forza Horizon 5 has a rewind feature, well yes the context is quite different here.

**Comment by RedDevilus** [comment] 2024-06-26 07:08
> Idk but Forza Horizon 5 has a rewind feature, well yes the context is quite different here.

Prince of Persia: Sands of Time has that feature as a mechanic which is kinda funny:

https://youtu.be/M5M6VRa7Ac4?t=6

But yeah it's still a kinda niche request still.

**Comment by dewxo** [comment] 2024-06-26 07:25
> > Idk but Forza Horizon 5 has a rewind feature, well yes the context is quite different here.
> 
> Prince of Persia: Sands of Time has that feature as a mechanic which is kinda funny:
> 
> https://youtu.be/M5M6VRa7Ac4?t=6
> 
> But yeah it's still a kinda niche request still.

Never knew it existed this back in games, they must have got some quality developers hard to find in that era.
