### ISSUE TITLE
Regression: Capcom games suffering from lines on right part of screen

### ISSUE THREAD

**Issue by prafullpcsx2** [PCSX2/pcsx2#5851] opened 2022-04-11 16:03 UTC
### Describe the Bug

Although this bug only happens while upscaling but since this is a regression I am posting this bug report.

Capcom games like Onimusha 3, Onimusha 4, Devil may Cry 3 and may be others show graphical artifacts in shape of lines on right side of the screen. These vary from game to game but location is almost same. My testing suggests that this bug started happening after https://github.com/PCSX2/pcsx2/pull/5387 was merged. 

Using round sprite Full reduces the problem but doesn't fix it completely.

### Reproduction Steps

Run these games and they suffer from the mentioned bug during some cutscenes/ingame. I have attached multiframe gsdumps so testing becomes easier.

### Expected Behavior

Game should run without any graphical issues.

### PCSX2 Revision

All versions after v1.7.2300 suffer from this problem

### Operating System

Windows 10 (64bit)

### CPU

i3-9100f

### GPU

750Ti

### GS Settings

Default settings with or without upscaling hacks.

### Logs & Dumps

http://filedropper.com/UvZnto1X

**Comment by Dreadmoth** [comment] 2022-04-12 01:02
Shadow of Rome is also affected by this issue:

[Shadow_of_Rome_right_edge_line.zip](https://github.com/PCSX2/pcsx2/files/8468682/Shadow_of_Rome_right_edge_line.zip)

**Comment by tellowkrinkle** [comment] 2022-04-17 02:22
Okay I looked at Shadow of Rome
Here's a draw **on a build not affected by this problem**: 
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/3315070/163697230-da93c0ce-e8a9-4251-9eb5-6ca1e14f1e34.png">

Game renders a sprite to a 128x56 target from (28664, 30972) to (30712, 31868) with XYOFFSET (28672, 30976).  Convert that to pixel coordinates and you get (-0.5, -0.25) to (127.5, 55.75).  This means that it never touches the rightmost 0.5 of a pixel and the bottommost 0.25 of a pixel, which become whole pixels when upscaling.

So the game has always been broken, but our broken samplers were covering this up by trimming the right and bottom edges off textures.

IMO the proper solution to this is upscaling hacks that affect where the game draws, rather than how we sample textures, but curious of what others think @refractionpcsx2

**Comment by refractionpcsx2** [comment] 2022-04-17 08:46
You might be right in that case, it certainly sounds like an upscaling bother.  It does bug me how we upscale even the fragment part of the integer where in reality it would get rounded/floored beforehand then the pixel coord is decided, rather than a "nearest" kind of thing, since that would screw our upscaling, but I honestly don't have a real solution for what pixels we draw, so upscaling hacks might be the way forward for that, at least for now. 

Maybe @RedDevilus or somebody can play with a concoction of hacks to see if something resolves/reduces it for now.

What's the situation with the capcom games?

**Comment by prafullpcsx2** [comment] 2022-04-20 09:48
After keenly observing games I noticed there are some other regressions caused by 5387 in these games.

![image](https://user-images.githubusercontent.com/12788199/164200990-7fa538e3-c001-494b-b29c-cdfd357ca0e8.png)

**Comment by tellowkrinkle** [comment] 2022-05-06 03:34
Can you test that on #6021?  I can't repro with it, and I can't play the GSdump without it in the Metal renderer.

**Comment by Tzerinas** [comment] 2022-05-06 08:35
Tested. Both Lines and Shadow issue on upscale are still there.

**Comment by prafullpcsx2** [comment] 2022-05-06 17:27
> Can you test that on #6021? I can't repro with it, and I can't play the GSdump without it in the Metal renderer.

All bugs still present on this pr

**Comment by refractionpcsx2** [comment] 2022-10-10 18:22
This is caused by this code right here 

```
        if (m_context->CLAMP.WMS == CLAMP_REGION_CLAMP && MIP_CLAMP.MINU == 0 && MIP_CLAMP.MAXU == tw - 1)
            m_context->CLAMP.WMS = CLAMP_CLAMP;
        else if (m_context->CLAMP.WMS == CLAMP_REGION_REPEAT && MIP_CLAMP.MINU == tw - 1 && MIP_CLAMP.MAXU == 0)
            m_context->CLAMP.WMS = CLAMP_REPEAT;
        else if ((m_context->CLAMP.WMS & 2) && !(tmm.uses_boundary & TextureMinMaxResult::USES_BOUNDARY_U))
            m_context->CLAMP.WMS = CLAMP_CLAMP;
        if (m_context->CLAMP.WMT == CLAMP_REGION_CLAMP && MIP_CLAMP.MINV == 0 && MIP_CLAMP.MAXV == th - 1)
            m_context->CLAMP.WMT = CLAMP_CLAMP;
        else if (m_context->CLAMP.WMT == CLAMP_REGION_REPEAT && MIP_CLAMP.MINV == th - 1 && MIP_CLAMP.MAXV == 0)
            m_context->CLAMP.WMT = CLAMP_REPEAT;
        else if ((m_context->CLAMP.WMT & 2) && !(tmm.uses_boundary & TextureMinMaxResult::USES_BOUNDARY_V))
            m_context->CLAMP.WMT = CLAMP_CLAMP;
```

Namely the first WMS and WMT checks to convert it to CLAMP_CLAMP, get rid of those (or add a check to see if it's m_vt.IsLinear())and you can upscale with Special Texture and you get no leakage or anything, works great.

This also causes problems in GT4 making the sprites for the cars disappear in the score board, same thing fixes it.

**Comment by lightningterror** [comment] 2022-10-14 22:03
Closing as workaround possible.
https://github.com/PCSX2/pcsx2/commit/702aefa43e0a928c3f18ad56187a364747c881f2

**Closed by lightningterror** 2022-10-14 22:03 UTC
Labels: Bug, GS: Hardware, Regression, Workaround Possible
