### ISSUE TITLE
Disc swapping issues (Dynasty Warriors XL-Samurai Warriors XL series)

### ISSUE THREAD

**Issue by bositman** [PCSX2/pcsx2#91] opened 2014-07-04 09:58 UTC
-PCSX2 version: 1.3.0 GIT 25-6-2014

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx, SPU2-X, Lilypad, Linuz ISO/Gigaherz CDVD,rest null plugins

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: The XL games of the series have an 'import from original' feature, which prompts you to eject the XL disc and insert the original disc to load additional content. While the actual disc swap seems to work, the game never imports the data saying 'The wrong disc has been inserted'

-How to replicate: Use any Dynasty Warriors 3/4/5 XL/ Samurai Warriors 1/2 XL game and select 'Import' in the menu, and disc swap to the original disc.

-Last known version to work: Never worked

-PC specifications: 
CPU: Intel Core i5 2500K @ 4.3Ghz
GPU: Gigabyte Geforce GTX660 Windforce OC 2 GB
OS: Windows 7 SP1

-Other comments: Some forum member discovered a way to import the data by merging the 2 discs in one ISO which partially works here: 
http://forums.pcsx2.net/Thread-Dynasty-Warriors-XL-problem-SOLVED
In general it looks like the ELF of the switched disc isn't detected properly.

**Comment by avih** [comment] 2015-01-13 15:10
Swapping DVD is reported to work with Onimusha Dawn of Dreams According to this http://forums.pcsx2.net/Thread-does-the-pcsx2-disc-swap-function-work?pid=426436#pid426436 

Anyone able to confirm this? what region was tested to work/fail? what are the DVDs CRCs?

**Comment by Sarania** [comment] 2015-01-13 21:21
I have a few two disc games I can check, but I'll have to find some saves for those games that are at the end of disc 1(and not saves on the start of disc 2) to check.

**Comment by Sarania** [comment] 2015-01-13 21:52
Just tested Xenosaga Episode 2. Worked fine swapping with internal ISO loader.

SLUS 20892 - Disc 1 - EB39ABEC
SLUS 21133 - Disc 2 - EB39ABEC

**Comment by Sarania** [comment] 2015-01-13 23:25
Xenosaga Episode 3 works.

NTSC - U
SLUS 21389 - DISC 1 - 2088950A
SLUS 21417 - DISC 2 - 2088950A

Same build as above.

**Comment by ramapcsx2** [comment] 2015-01-14 16:07
When I hacked initial swap support together, my games that required swapping all worked.
Xenosaga 2 and 3 were among them.
Later I found out that none of the games I couldn't test worked though :p

**Comment by Sarania** [comment] 2015-01-14 21:46
Lol doh.

**Comment by ArcticHowler** [comment] 2016-03-16 00:21
I probably don't really belong here(just came across this particular github and I use PCSX)  but from my experience ps1 discs(not isos) work fine if it has a disc swap requirement, pretty sure I've tested with isos as well though I can't remember which ones exactly, but I know that FF8 and FF9 work for disc swapping if it's a real disc, Chrono Cross(only other ps1 game I still own other than the other 2, and the isos of each for testing) I don't remember if I tested...

**Comment by bositman** [comment] 2016-03-16 01:52
This is PCSX2, a PS2 emulator -_-

**Comment by ArcticHowler** [comment] 2016-03-16 21:05
PCSX2 works with ps1 games(at least some of them), the swapping works for them even, that's a decent way to reference what is happening for you guys to pinpoint it...

**Comment by willkuer** [comment] 2016-03-16 21:09
What do you mean by psx games work on pcsx2?

**Comment by flameking** [comment] 2016-08-04 20:10
I have looked at this thread and another person just claimed to have made disc swap work for samurai warriors 1 xl

http://forums.pcsx2.net/Thread-Dynasty-Samurai-Warriors-and-Xtreme-Legends-disk-swap-solution

I'd like to see if others can look at this and try for themselves because i cant load games using plugin

**Comment by avih** [comment] 2016-08-04 20:20
> I have looked at this thread and another person just claimed to have made disc swap work for samurai warriors 1 xl
> 
> http://forums.pcsx2.net/Thread-Dynasty-Samurai-Warriors-and-Xtreme-Legends-disk-swap-solution
> 
> I'd like to see if others can look at this and try for themselves because i cant load games using plugin

Thanks, but this is a workaround by editing the DVD image. While useful to know and to have as reference, here too, it's not really about this (seemingly real) bug.

Please take any followup discussions on this method to that forum thread. Thanks.

**Comment by flameking** [comment] 2016-08-05 17:11
I wanted to mention something i found which im not sure may be useful or not:

In samurai warriors xl, you are asked to put in the samurai warriors 1 disc when importing and you get an error saying 'wrong disc has been insterted', and switching to 'no disc' during the import says 'no disc has been insterted'.

When you click 'cancel importation' after however you're asked for the sw xl disc and swapping using disc swap works as the disc is recognised.

How come the xl disc is recognised but not the sw1 disc?

**Comment by avih** [comment] 2016-08-05 19:17
> In samurai warriors xl, you are asked to put in the samurai warriors 1 disc ...

Can you please post the portion of the log from before you swap disk the first time (which fails) until after you insert the XL disk again (which succeeds)? thanks.

**Comment by flameking** [comment] 2016-08-05 19:32
Should i screenshot it or just copy paste the log?

**Comment by avih** [comment] 2016-08-05 19:44
The log would be a good start, thanks. I won't be able to reproduce it, but maybe someone will be able to notice something interesting at the log.

**Comment by flameking** [comment] 2016-08-05 19:45
Closing CDVD
Opening plugins...
Opening CDVD
isoFile open ok: C:\Users\James\Documents\Samurai Warriors 1.iso
Image type  = DVD
CDVD Disk Open: DVD, Single layer or unknown:
 Track 1: Data (Mode 1) (2125440 sectors)
Plugins opened successfully.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_208.78;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC
found 0 symbols
ELF (cdrom0:\SLUS_208.78;1) Game CRC = 0xCF11CD83, EntryPoint = 0x00100008
	HotSwapping to new ISO src image!
	Closing CDVD
Opening plugins...
	Opening CDVD
isoFile open ok: C:\Users\James\Documents\Samurai Warriors Xtreme Legends.iso
	Image type  = DVD
CDVD Disk Open: DVD, Single layer or unknown:
Track 1: Data (Mode 1) (2293888 sectors)
Plugins opened successfully.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_210.80;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC
found 0 symbols
ELF (cdrom0:\SLUS_210.80;1) Game CRC = 0x0442B1BD, EntryPoint = 0x00100008
Closing plugins...

----------------------------------------------------------------------------------------------------

This log is from when i go to import option uptill i cancel the import and reselect the xl disc.

**Comment by flameking** [comment] 2016-08-05 19:50
Forgot to mention a few things:

- I ran the iso using gigahertz plugin and ran it as an ISO
- I disk swapped by changing the iso
- Both my sw1 and xl discs work fine seperately and have no scratches on them
- I have ripped an image with imgburn
- Game is NSTC
- I dont think the log showed anything when the screen said 'wrong disc has been insterted'

**Comment by avih** [comment] 2016-08-05 20:04
Thanks.

> I ran the iso using gigahertz plugin and ran it as an ISO

Out of interest, any reason you use[d] the plugin and not the internal ISO reader? Is there anything the plugin does better?

Back to our subject. Could you please try the following:
- Use the Iso selector (not plugin) and get to the point where the game asks you to swap disc.
- When it prompts you, select "No Disc" at the CDVD menu (and at the dialog choose "Swap Disc")
- Use the Iso selector (not the plugin) to choose the new disc (disc 1).

And then if you can, also try the same only with the plugin instead of the internal iso selector.

I'm not expecting anything exciting to happen on either of those, but just to get a confirmation that they behave the same, and that it doesn't happen only when swapping directly to the other disc.

**Comment by flameking** [comment] 2016-08-05 20:08
Right, i will try that and report back.

Also sorry for the bad wording, i meant i ran it using the internal ISO reader (plugin doesnt work for me) and i used the CDVDgigahertz plugin in 'Plugin/BIOS selector' instead of CDVDnull and the other one.

**Comment by avih** [comment] 2016-08-05 20:11
Ah, so if the plugin doesn't work for you, the internal ISO would be enough :) thanks.

**Comment by flameking** [comment] 2016-08-05 20:17
Ok just tried it now, and i still get the error.

I had to be very quick when changing from No disc to Iso or else i get the 'No disc has been insterted' Message.

However, out of curiosity, i tried what you asked of me but for the part where it says 'cancel importation' (which is after i get the error). Basically i changed to no disc and quickly to samurai war xl iso and it works as the disk is recognised, and cancels the importation.

I hope you are understanding all of this because im very bad at wording :P

**Comment by avih** [comment] 2016-08-05 20:22
I think I did, thanks.

In other words, choosing no disc and then quickly choosing an iso behaved exactly like choosing an iso directly without the "no disc" in the middle, right?

And if it's not done quickly then the game complains.

So no new exciting info, but at least we tried :)

**Comment by flameking** [comment] 2016-08-05 20:30
Yeah exactly.
Hopefully people find a fix to this as most people claim disc swap works for many other games but not samurai warriors.
Some claim they have found a workaround but these arn't working for me and for others (unless im doing something wrong which i dont think i am). Reason for that being the 'plugin' option not working for me because those who claim it works state it must be ran through the plugin not the internal iso reader, but i guess ill discuss that in a forum.

**Comment by avih** [comment] 2016-08-05 20:34
> Reason for that being the 'plugin' option not working for me because those who claim it works state it must be ran through the plugin not the internal iso reader, but i guess ill discuss that in a forum.

If this gets confirmed at the forum (that using the plugins it can swap just fine), please post that info also here afterwards. Thanks.

**Comment by flameking** [comment] 2016-08-05 21:44
I just made a post in a that thread asking to confirm this.


In the meantime, i beleive this information here could be a start to helping us understand more on this issue. 

When i said i was getting a 'wrong disc inserted error' when trying to import from the samurai warriors 1 disc (orginal) but it works when canceling the import (when it asks me for the samurai warriors xl disc), i ran the samurai warriors xl using the internal iso reader. I didn't run the merged iso for 2 reasons, 1: so that i can contribute to this forum about the issue using the original discs and 2: because running the merged iso gives me a black screen with no sound despite getting no errors in the logs (which is confirmed below in this post by another user). This is different from what the OP of that thread suggested as they ran it using the plugin and also ran the merged iso.

As you might know, the workaround according to the thread OP is basically:

-Rip and iso from both sw1 and sw1xl discs using imgburn to create 2 seperate iso
-Extract files from both iso into seperate folders, and then move the files from one folder into another combining them without overwriting anything
-Create a new iso
-Mount iso to a virtual drive and run using plugin instead of internal iso reader
- Then go to import and basically do the 'no disc' and fast switch to 'plugin' as you've described above and the disc will be recognised (which is where many people stop because it isnt recognised).

This is what the OP had said about this in his first post who claims to have made it work: 'Of course you have to do this ''no disc" and "plugin" everytime you want to import the original disc.
And you can't do this if you run the game through the .iso, it works only if you mount the image and you run it through the plugin' - i am running it using the internal iso reader which could be why it's not working for me.

Another user made a reply yesterday and said 'the tutorial of merges of SW original and XL lead to black screens on boots or disk swap, and PCSX2 crashing (when running with the internal iso reader)' - this is exactly what i am experiencing when running the merged iso too. However they said 'with the mounting of the malicious mixed content disk, that which formerly spew black screen, is now working when put into plugin for PCSX2! SWXL boots fine from that disk, and I can make the swaps just like described by the OP with NoDisc to Plugin switches.'

This user claims that running it with the plugin no longer gives them the black screen they used to get running it with the internal iso reader. Unfortunately when i try running it with the plugin, it doesnt work because i get an error and a black screen which is shown here: http://forums.pcsx2.net/Thread-Black-screen-error-when-using-Plugin

I wish i could speak with the OP to double check but this is what we currently know according to them.

I hope this has been helpful. Please feel free to ask me about anything you are unsure of.

**Comment by cau2babj** [comment] 2017-05-30 10:33
https://www.youtube.com/watch?v=WwXYhQm6wDM&t=79s
this my way to load original data from dw3 to dw3xl,also i can do it with dw4xl,smxl,sm2xl too,so if you want i can post it in youtube,like and share a video to everybody wait it,tks.

**Comment by fldef** [comment] 2020-07-23 17:28
Is anyone available to help test a potential fix for this? 

I have a version of v1.6.0 with swaps working in Monster Rancher EVO and SingStar. I could use a hand testing Dynasty Warriors XL games, other Monster Ranchers, and anything else involving disc swaps.

The release can be found here: https://github.com/fldef/pcsx2-fldef/releases/tag/v1.6.0-swapfix-3

**Comment by bositman** [comment] 2020-07-28 12:06
Sure I can help with dynasty warriors. Although I must report it worked fine previously for me, you have to be careful with wide screen patches when doing the swap, PCSX2 will load the swapped disc's patches as well, which can lead to crashes

**Comment by eatitvidboi** [comment] 2020-08-09 04:38
That version of v1.6.0 fldef posted has working disc swaps in Samurai Warriors 2 XL with NoDisc/the regular ISO selector, always hit swap disc and just say no every time the game asks if you want to cancel the procedure. I also tested it in 1.70-dev-147-g9222e93c4 out of curiosity and got the wrong disc inserted error everyone always gets.

**Comment by im1kooldood** [comment] 2020-10-22 04:04
I created an account just to post that I have been trying to get Monster Rancher 3 to work with Disk Swapping for awhile now, and I stumbled across this. I can confirm that fldef's version does work for disk swapping in MR3, When the guy says he's going to eject the tray, just click no disk, then select the rom (I tried to do it quickly as with previous versions the commands would jump quick to close tray), and it read the disk like normal, then ejected and asked for the MR3 disk, again no disk command and select the correct rom. I tried this using Armored Core 2 rom and it worked like a charm. #THANKYOU

**Comment by ikecarmine** [comment] 2021-02-24 05:57
> 
> 
> Is anyone available to help test a potential fix for this?
> 
> I have a version of v1.6.0 with swaps working in Monster Rancher EVO and SingStar. I could use a hand testing Dynasty Warriors XL games, other Monster Ranchers, and anything else involving disc swaps.
> 
> The release can be found here: https://github.com/fldef/pcsx2-fldef/releases/tag/v1.6.0-swapfix-3

I can confirm this working tonight with the ever-elusive Samurai Warriors 2 / Xtreme Legends "Import" issue. Switching the images through the CDVD > ISO Selector dropdown and clicking "Swap" on the confirmation box works just as the console would. Once you've Imported it prompts you to switch back to Xtreme Legends disc and it's the same process.

Previously I'd tried every method of .iso merging and hotswapping techniques one could find with a couple hours of forum crawling to no avail. I was using the Nightly g513f337a8 build for that process.

**Comment by afgks** [comment] 2021-05-21 05:26
> 
> 
> Is anyone available to help test a potential fix for this?
> 
> I have a version of v1.6.0 with swaps working in Monster Rancher EVO and SingStar. I could use a hand testing Dynasty Warriors XL games, other Monster Ranchers, and anything else involving disc swaps.
> 
> The release can be found here: https://github.com/fldef/pcsx2-fldef/releases/tag/v1.6.0-swapfix-3

I tested this with Sengoku Musou 1 + Moushouden (JP version). Disc swap worked but the program crashed about 1 minute into the battle.
Before testing this build, I played the game with the regular build (no disc swap) for few hours without crash.

**Comment by afgks** [comment] 2021-05-24 20:46
@fldef 

I found out the cause - if widescreen patches are enabled, AND you use the Mixjoy function (import from original) in the game, the game will crash whenever the gate-opening cutscene plays.

Some examples of the gate-opening cutscene:
https://i.imgur.com/TECUhUF.png
https://i.imgur.com/KQbxIQJ.png



The log looks something like this before the crash:

```
Overall 0 Widescreen hacks loaded
Loading patch 'DBD2230B.pnach' from archive 'C:\Program Files (x86)\PCSX2\cheats_ws.zip'
comment: Widescreen Hack by ElHecht (Pnach by Little Giant)
(Wide Screen Cheats DB) Patches Loaded: 6
(EE pc:0013FFE0) TLB Miss, addr=0x43280018 [load]
(EE pc:00140000) TLB Miss, addr=0x43280018 [store]
(EE pc:00140000) TLB Miss, addr=0x43280018 [load]
(EE pc:00140000) TLB Miss, addr=0x43280018 [store]
(EE pc:00140000) TLB Miss, addr=0x43280040 [load]
(EE pc:00140000) TLB Miss, addr=0x43280040 [store]
(EE pc:00140000) TLB Miss, addr=0x43280040 [load]
(EE pc:00140000) TLB Miss, addr=0x43280040 [store]

```


If either widescreen patches are not enabled, or you don't use the Mixjoy function, the game will not crash.

**Comment by bositman** [comment] 2021-05-24 21:59
> @fldef
> 
> I found out the cause - if widescreen patches are enabled, AND you use the Mixjoy function (import from original) in the game, the game will crash whenever the gate-opening cutscene plays.
> 
> Some examples of the gate-opening cutscene:
> https://i.imgur.com/TECUhUF.png
> https://i.imgur.com/KQbxIQJ.png
> 
> The log looks something like this before the crash:
> 
> ```
> Overall 0 Widescreen hacks loaded
> Loading patch 'DBD2230B.pnach' from archive 'C:\Program Files (x86)\PCSX2\cheats_ws.zip'
> comment: Widescreen Hack by ElHecht (Pnach by Little Giant)
> (Wide Screen Cheats DB) Patches Loaded: 6
> (EE pc:0013FFE0) TLB Miss, addr=0x43280018 [load]
> (EE pc:00140000) TLB Miss, addr=0x43280018 [store]
> (EE pc:00140000) TLB Miss, addr=0x43280018 [load]
> (EE pc:00140000) TLB Miss, addr=0x43280018 [store]
> (EE pc:00140000) TLB Miss, addr=0x43280040 [load]
> (EE pc:00140000) TLB Miss, addr=0x43280040 [store]
> (EE pc:00140000) TLB Miss, addr=0x43280040 [load]
> (EE pc:00140000) TLB Miss, addr=0x43280040 [store]
> ```
> 
> If either widescreen patches are not enabled, or you don't use the Mixjoy function, the game will not crash.

Yeah i mentioned just that some commends above, it happens because it loads the patches of the switched game and those cause a crash on the original (different addresses and all)

**Comment by ThisNekoGuy** [comment] 2021-09-11 01:41
I've personally had this issue when trying to read any PS2, CD, or DVD disc with Monster Rancher 3 (a PS2 game).

On a normal PS2, Monster Rancher 3 would (via the Saucer Disc game option) prompt the player to hot-swap a disc with _**any disc**_ (it didn't care what kind of disc it was as long as the drive could physically read it - but note this was before BluRays were a thing when I was a kid).
Upon doing so, it would scan the disc then prompt the player to hot-swap back to the game so that it can generate a monster for the player based on the collected data.

I've had this issue where, if I try to read any `iso` file on my system, the game would think it's still a copy of Monster Rancher 3 and ask for confirmation to proceed as though the player did nothing (which would be bad if someone actually proceeded in this state).
If the `iso` file is too big (not an average CD / DVD / PS2 game, etc), PSCX2 can outright crash attempting to read the disc.

If attempting to read a _**physical**_ disc with a disc reader (I used a cheap USB one), sometimes it fails to read the contents at all (with a filesystem error) and half-terminates the game in the process (in a way that forces the user to restart to resume the game process).

Ideally, having this at least work with `.iso` files would be more stable than reading from a disc reader because that would introduce another potential failure point. As it stands, attempting to play this game is difficult because this is a core feature the game depends on in order to progress in the game normally.

For context:
on the initial attempt to do this, the game will accept **_any_** (digital) `iso` file regardless of whether or not it can actually read it and will always generate a Mochi monster. However, putting this monster into hibernation to gain a free slot to do this process again is where the problem lies.

I've had only _**one exception:**_ if you have `Harvest Moon - Save the Homeland`, this game does not produce an `iso`, because it is a `.bin` game; for some reason unbeknownst to me, this is the only PS2 game example I have where Monster Rancher 3 _actually_ recognizes it as a "disc" other than itself and proceeds as it should (although - it does this **very fast** on my machine). I've attempted to use other `.bin` files in attempt to replicate this behavior though, but this causes PCSX2 to crash.

**Closed** 2021-10-03 16:27 UTC
Labels: Bug, Core, Needs Reversing, CDVD
