### ISSUE TITLE
PSX (Cancelled with XMB) BIOS Support?

### ISSUE THREAD

**Issue by DartPower** [PCSX2/pcsx2#4450] opened 2021-05-21 19:43 UTC
Can you implement PSX (NOT PS1, PSX Which cancelled) Bios support?

Currently i tried run with Japan PSX bios but...

```
PCSX2 1.7.0-20210521000616 - compiled on May 21 2021
Savestate version: 0x9a1f0000

Host Machine Init:
	Operating System =  Microsoft Windows 10 Pro (build 19042), 64-bit
	Physical RAM     =  16305 MB
	CPU name         =  Intel(R) Xeon(R) CPU E5-2440 0 @ 2.40GHz
	Vendor/Model     =  GenuineIntel (stepping 07)
	CPU speed        =  2.394 ghz (12 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfcbfbff 9e9ae383
	x86EFlags        =  2c100800

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX

Reserving memory for recompilers...

Loading plugins from J:\EMU\PCSX2\plugins...
	Bound   GS: GSdx32-SSE4.dll [GSdx 20210521000616 (MSVC 19.26 SSE4.1/AVX) 1.2.0]
Plugins loaded successfully.

[GameDB] 10363 games on record (loaded in 633ms)
HLE Notice: ELF does not have a path.

Initializing plugins...
	Init GS
Plugins initialized successfully.

Patches: No CRC found, using 00000000 instead.
Opening plugins...
	Opening GS
Current Renderer: Direct3D 11
GSdx Lookup CRC:00000000
McdSlot 0 [File]: J:\EMU\PCSX2\memcards\CARD64M1.ps2
McdSlot 1 [File]: J:\EMU\PCSX2\memcards\CARD64M2.ps2
GSdx Lookup CRC:00000000
Plugins opened successfully.
48000 SampleRate: 
EE/iR5900-32 Recompiler Reset
	Bios Found: Japan   v01.80(28/10/2003)  Console
	BIOS Warning: Unknown BIOS version. The debugger thread and stack frame views will not be functional.
# Initialize memory (rev:3.69, ctm:196Mhz, cpuclk:147Mhz detected)
Frame buffer size set to  512x512 (1536x1536)

PlayStation 2 ======== Hard reset boot
 ROMGEN=2003-1028, IOP info (CPUID=1f, CACH_CONFIG=0, 8MB, IOP mode)
 <20031028-053521,ROMconf,PS20180JC20031028.bin:12064>
# Total accessable memory size: 64 MB (B:2:8:0) (369:2:7c30)
# TLB spad=0 kernel=1:12 default=13:32 extended=33:41
```

Crashing on this:
```
# Initialize Start.
```

Next log with closing:
```
DEV9: Waiting for RX-net thread to terminate..
DEV9: Done
Closing plugins...
	Closing GS
Plugins closed successfully.
Shutting down plugins...
Plugins shutdown successfully.
```

**Comment by Blackbird88** [comment] 2021-05-23 21:49
Dupe of #1549

**Closed** 2021-05-23 21:53 UTC
Labels: Duplicate
