### ISSUE TITLE
PCSX2 Windows does not remember its position

### ISSUE THREAD

**Issue by QuaiGoner** [PCSX2/pcsx2#2840] opened 2019-02-04 08:36 UTC
OS - Windows 10

So the issue is with other applications and some emulators when you drag its window on the second screen and close it it will remember its last position ( a way to make auto-fullscreen on secondary monitor) but PCSX2 always starts on default screen size and position (primary screen). Is there any way to make it custom setting and choose which screen PCSX2 will use as output? Or just make PCSX2 windows remember which position was last when closing? Thank you.

**Comment by RedPanda4552** [comment] 2019-02-04 15:50
PCSX2 already remembers window dimensions and position. If these are not sticking for you, this probably means PCSX2 is being denied write permissions for its ini files. Is your inis folder in a write protected directory, such as Program Files?

**Comment by QuaiGoner** [comment] 2019-02-04 16:00
No, i have my pcsx2 folder in "Emulators" folder on separate drive. I have portable.ini in my pcsx2 folder, that can cause an issue?

**Comment by willkuer** [comment] 2019-02-04 16:06
Maybe you can look in the pcsx2 ini? There are two and I do not remember which one is the right one. If you find the entry for dimension and position of the window can you try to adjust them manually to see whether loading these values works as intended?

**Comment by RedPanda4552** [comment] 2019-02-04 16:08
No, the portable.ini file is what tells PCSX2 not to write into the user folders, which is fine, perhaps ideal in this case.
Check the pcsx2_ui.ini file and note what the window coordinates are. There's one set for the main window at the top of the file, and one for the GS window a bit lower. You could try moving the window and seeing if the file updates after PCSX2 is closed, and also if editing manually has any effect.

**Comment by QuaiGoner** [comment] 2019-02-04 16:13
Okay, thanks to you i understood my problem. PCSX2 does remember its position, but only on primary monitor. When i drag it to the secondary and close it changes the values in the ini but still opens in the default spot. So PCSX2 cant remember ppsition on the secondary monitor, which was the whole point for me

**Comment by QuaiGoner** [comment] 2019-02-04 16:16
Is that possible to specify which monitor to use? Changing primary to secondary is not an option for me, unfortunately

**Comment by QuaiGoner** [comment] 2019-02-04 16:25
Also my monitor is not both 1080p, one is 720p another - 1080p if that makes any differnce. Can we somehow bring devs attention to this issue? Maybe proper title?

**Comment by RedPanda4552** [comment] 2019-02-04 17:13
I was already planning on checking this myself. Shouldn't need a title change.

**Comment by QuaiGoner** [comment] 2019-02-08 18:44
Any progress?

**Comment by QuaiGoner** [comment] 2019-02-10 18:10
Is it possible to create a bounty for this issue?

**Comment by tadanokojin** [comment] 2019-02-19 02:30
Some notes about this

https://github.com/PCSX2/pcsx2/blob/6905d4d8832505a28b3b2f685e35df6dd821a8b8/common/src/Utilities/wxGuiTools.cpp#L196-L212

`wxGetDisplaySize` returns the size of the display.

So here when we check that the coordinates are valid:
https://github.com/PCSX2/pcsx2/blob/6905d4d8832505a28b3b2f685e35df6dd821a8b8/pcsx2/gui/MainFrame.cpp#L394-L398

We fail because the second monitor falls outside the primary display rectangle.
So we are saving with screen coordinates and validating that against display coordinates.

**Comment by Jordo24** [comment] 2021-07-28 00:41
anyone have a fix for this issue? im using one of the latest 1.7.0 dev builds and im having an issue with pcsx2 not "remembering" my monitors position since im using a secondary one, can anyone help?

**Closed** 2021-08-18 17:40 UTC
Labels: Low Priority, GUI/WX

**Comment by tadanokojin** [comment] 2021-08-18 20:09
This should be fixed now. If there's still an issue just ping me.

**Comment by TeamLinux01** [comment] 2023-08-04 02:03
@tadanokojin I am having an issue with multiple monitors on KDE Plasma.
I have a 1920x1080 HDMI monitor that I have set as primary and a 2560x1440 DP monitor rotated 90 degrees counter-clockwise.

I am using the flatpak version of PCSX2 and it will always open in the center of the DP monitor and when entering BigPicutre, it only fullscreens to the DP monitor.

PCSX2 does remember the dimensions of the window but not the position.

**Comment by MrCK1** [comment] 2023-08-04 02:05
> @tadanokojin I am having an issue with multiple monitors on KDE Plasma. I have a 1920x1080 HDMI monitor that I have set as primary and a 2560x1440 DP monitor rotated 90 degrees counter-clockwise.
> 
> I am using the flatpak version of PCSX2 and it will always open in the center of the DP monitor and when entering BigPicutre, it only fullscreens to the DP monitor.
> 
> PCSX2 does remember the dimensions of the window but not the position.

@TeamLinux01 This issue has already been closed for 2 years. Please use the Discod server if you require further support - https://discord.com/invite/TCz3t9k

**Comment by stenzek** [comment] 2023-08-04 05:12
> it will always open in the center of the DP monitor and when entering BigPicutre, it only fullscreens to the DP monitor.

This is a limitation of lameland (Wayland), not sure if it's WL, Kwin, or Qt specifically.

**Comment by TeamLinux01** [comment] 2023-08-04 13:22
> > it will always open in the center of the DP monitor and when entering BigPicutre, it only fullscreens to the DP monitor.
> 
> This is a limitation of lameland (Wayland), not sure if it's WL, Kwin, or Qt specifically.
> 
> 

Thanks for the response. It makes sense and I just couldn't find any information on it, so having an answer is nice.
