### ISSUE TITLE
Armored Core 2: persistent sound effect loop SPU2-X

### ISSUE THREAD

**Issue by DragonSix** [PCSX2/pcsx2#2917] opened 2019-04-08 06:35 UTC
***PCSX2 version:***
1.4.0 and 1.5.0.2212 and 1.5.0.3026

***PCSX2 options:***
Everything by default, safest preset, no speedhack. Used both software and hardware rendering.

***Plugins used:***
SPU2-X: Tried with Xaudio, DirectSound, Portaudio, Timestretch/Nosync. Bug is present in all cases.

***Description of the issue:***
Oftentimes, after ending a mission, a sound effect will persist and keep looping forever.

***How to reproduce the issue:***
[Mcd001.zip](https://github.com/PCSX2/pcsx2/files/3052911/Mcd001.zip)
Load the save, go to missions, start the mission.
Walk forward with dpad Up and Cross for speed boost, and open the doors with Circle. Ignore enemies. Continue forward up to the locked door, shoot the lock panel with Square and proceed to the lift forward. Activate the lift with Circle then press Start. Leave the mission with Select and confirm.
From the score screen onward, the lift sound effect will remain active.

***PC specifications:***
CPU: I7 4790k GPU: GTX 1070 Soundcard: Motherboard integrated Realtek ALC892 OS: Windows 10 64bit

**Comment by atomic83GitHub** [comment] 2019-04-08 06:42
Yeah this is one of those "SPU problematic" games, this build posted in the forum should do the trick: https://forums.pcsx2.net/Thread-X-Men-Origins-Wolverine-SLUS-21880-Crash?pid=579089#pid579089

**Comment by DragonSix** [comment] 2019-04-08 06:48
Unfortunately, I still encounter the same issues with the SPU2-X refraction plugin you posted.

**Comment by atomic83GitHub** [comment] 2019-04-08 06:51
Put this ini file in the inis folder (replace the old one). 

[spu2 AM2.zip](https://github.com/PCSX2/pcsx2/files/3052974/spu2.AM2.zip)

**Comment by DragonSix** [comment] 2019-04-08 06:55
Hey it works! No more persistent sound loops. Thanks a lot!

**Comment by atomic83GitHub** [comment] 2019-04-08 06:58
Yeah Armored Core 2 (Especially the UBISOFT pal version) are a pure MESS with SPU timings, you need both of these fixes to make the sound right. (the special build avoid sound conflicts and the second avoid sound looping in various places).

**Comment by orbea** [comment] 2019-04-10 13:17
@atomic83GitHub Is there an issue with merging these fixes upstream?

**Comment by atomic83GitHub** [comment] 2019-04-10 13:29
Yes, booth of those are causing regression with some games such as ONI.

**Comment by MrCK1** [comment] 2019-04-10 18:56
Modifying `DelayCycles` is considered a hack, hence the reason why we don't merge it.

You can track all the games that require an alternate value here: https://github.com/PCSX2/pcsx2/issues/2371

**Comment by orbea** [comment] 2019-04-11 14:46
Maybe this game should be added to the meta issue and this one closed?

**Comment by MrCK1** [comment] 2020-12-02 20:00
Fixed in https://github.com/PCSX2/pcsx2/pull/3959

**Closed by MrCK1** 2020-12-02 20:00 UTC
Labels: SPU2
