### ISSUE TITLE
[BUG]: Anti Blur doesn't seem to work in Charlie's Angels (Europe)

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6845] opened 2022-08-15 05:14 UTC
### Describe the Bug

The game is very blurry and turning the anti blur hack on or off doesn't seem to do anything.

![Charlie_s Angels_SLES-51750_20220815145354](https://user-images.githubusercontent.com/96800307/184579872-91b5fb6d-e0f5-4e3e-b7cb-6e1f61f760f1.png)

### Reproduction Steps

Play the game with any renderer or resolution. I tried Software and Vulkan at native and x4.

### Expected Behavior

The anti blur hack should work.

### PCSX2 Revision

pcsx2-v1.7.3208-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

### CPU

Intel i5

### GPU

GTX 1070

### GS Settings

All default

### Emulation Settings

All default

### GS Window Screenshots

![Charlie_s Angels_SLES-51750_20220815145354](https://user-images.githubusercontent.com/96800307/184579981-9361e52f-86b4-4ce8-9890-e8c11d3e7b8b.png)

![Capture](https://user-images.githubusercontent.com/96800307/184580005-b91b9b29-9272-4d6f-aca2-a6e16bf83600.PNG)

### Logs & Dumps

[Charlie_s Angels_SLES-51750_20220815151247.zip](https://github.com/PCSX2/pcsx2/files/9335215/Charlie_s.Angels_SLES-51750_20220815151247.zip)

**Comment by refractionpcsx2** [comment] 2022-08-15 07:28
Yeah that's not the same thing, the game is drawing that blur, the anti-blur is to deal with when the developer has slightly offset the 2 output circuits, which is not happening in this case.

The only way you can improve this (by hacking it), is by using Skipdraw 4,4. if you don't and you're upscaling, be sure to use Half Pixel Offset - Normal (Vertex) to align the blue effect.

We will do the latter in the GameDB, but as for the blur, you can either set the skipdraw per game, or live with it :P

**Comment by drachenschanze** [comment] 2022-08-15 07:59
@refractionpcsx2 Thanks for the info. While I'm here I'll mention a few other bugs that I'm not sure about. Whether they're emulator bugs or a problem with the game itself. The game's terrible so it could be either. 

First when the opening logo fades out it seems to get screwed up.

![Capture](https://user-images.githubusercontent.com/96800307/184597944-fc545d0a-d024-4128-92ff-88d39300a817.PNG)


Second during screen transitions there's a garbage line in the middle.

![Capture2](https://user-images.githubusercontent.com/96800307/184598008-f3117052-4fa6-45e6-92d5-6382da6bee25.PNG)

**Comment by refractionpcsx2** [comment] 2022-08-15 08:01
is it there in software mode too? if not, can you provide a GS Dump of the garbage line? thanks

**Comment by drachenschanze** [comment] 2022-08-15 08:17
@refractionpcsx2 It is there in software mode.

[Charlie_s Angels_SLES-51750_20220815181641.zip](https://github.com/PCSX2/pcsx2/files/9335938/Charlie_s.Angels_SLES-51750_20220815181641.zip)

**Comment by refractionpcsx2** [comment] 2022-08-15 08:18
OK thanks

**Comment by refractionpcsx2** [comment] 2022-08-15 08:36
Either it's a core issue, or the game just does that, would need to run the game on the actual PS2 to check, but here's a GS dump from PCSX2 running on an actual PS2, and the line is there.

![image](https://user-images.githubusercontent.com/6278726/184603449-8f31b49d-eb61-4159-ab79-b3c40f082574.png)

**Comment by drachenschanze** [comment] 2022-08-15 08:44
@refractionpcsx2 Here's the game being played on a real PS2.

https://youtu.be/r6Wd1jMNFyE?t=102

![Capture](https://user-images.githubusercontent.com/96800307/184604685-2f92cf1a-fd09-488d-9e41-c11a756e221b.PNG)

**Comment by refractionpcsx2** [comment] 2022-08-15 08:45
So reproduced in real hw then

![image](https://user-images.githubusercontent.com/6278726/184604815-2885abdc-0415-4d84-b59a-250f443b0a89.png)

**Comment by refractionpcsx2** [comment] 2022-08-15 08:46
![image](https://user-images.githubusercontent.com/6278726/184605035-dbdadb4f-46a6-4310-9c64-352a424aa85f.png)

**Comment by refractionpcsx2** [comment] 2022-08-15 08:47
Anyway, the blur misalignment on upscaling has been fixed on maaster, and since this line happens on real hardware, I think we're done here :)

Thanks for the report.

**Closed by refractionpcsx2** 2022-08-15 08:47 UTC
Labels: Bug, Replicated on Real HW
