### ISSUE TITLE
[BUG]: Just Cause, Memorycard not working properly.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#4957] opened 2021-10-29 13:02 UTC
### Describe the Bug

In the game "Just Cause", creating a memorycard save lead to plenty of various bugs which changes a bit with different sorts of timings behaviours.

At stock settings the game will fail to read the memorycard multiples times and "eventually" complete the saving process after almost 10 minutes.

With instantVU1 disabled the game will read the memorycard and do a few operations but the result is mostly the same, very very slow saving process.

The only way to make it work fine is to reset the EE recompiler while the game is saving, which will instantly make the saving process to complete fine. Nota: this is a horrible thing to do, this will corrupt the save.

### Reproduction Steps

Load the blockdump and savestate, put an empty memorycard (and disable the savestate auto-eject option) and create a save file.

### Expected Behavior

The game should definitely not take this long to do a save.

### PCSX2 Revision

v1.7.0-dev-1980-g52eab49359

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### Logs & Dumps

Blockdump + savestate: https://drive.google.com/file/d/1XdzSAi7HWM2trSOYTs1_Mw8-ncp9hsGP/view?usp=sharing

**Comment by gilderoylockhart01** [comment] 2021-11-11 12:31
It turns out the problem is even worse than anticipated, relaoding the EE recompiler while saving will in fact, make the save corrupted and the game somehow think it's right.

**Comment by TheTechnician27** [comment] 2022-03-05 00:22
Tested the game myself. I created a memory card save and experienced no issues. Creating the save file took around 10 seconds, and subsequent saves took less than two. Given the PS2's propensity for weird save glitches (see, for example: _Jak X_), I would be entirely unsurprised if the OP experienced an actual memory card glitch present on original hardware. I tested creating a save twice just to be sure this wasn't a fluke. However, this game does have noticeable graphical issues in HW rendering.

**Comment by RedPanda4552** [comment] 2022-03-05 17:32
I was already skeptical of this since the original post suggested that speedhack manipulation was affecting the outcome, which suggests this was more of a DMA/SIF issue than anything else. I'd assert the developers likely wrote a relatively sensitive interrupt handler and/or wait loop on the EE, and speedhacks likely disrupt that. Those times seem reasonable, exact numbers would vary depending on what exactly the file structure looks like but that's completely within reason.

I would like to get another testimony on this before closing, so I will keep this alive for now.

**Comment by Mrlinkwii** [comment] 2022-11-19 21:43
can this be double checked on lastest nightly ?

**Comment by refractionpcsx2** [comment] 2023-02-18 15:09
I just ready the instructions, which are frankly ridiculous, I'm not surprised it doesn't work.

Multiple people (including link) have been unable to reproduce, so closing.

**Closed by refractionpcsx2** 2023-02-18 15:09 UTC
Labels: Bug, Waiting feedback, Memory Card

**Comment by TheTechnician27** [comment] 2023-02-18 15:13
@refractionpcsx2 I can actually confirm having just tested Just Cause that it did seem to take the memory card a few times to be written to initially. When creating the initial save, a prompt appeared three times in a row that said Memory Card 1 had been saved to, only for it to appear for a fourth time and actually save the game and let me go back to playing. I couldn't tell you if this is behavior is supposed to happen on original hardware, but it did seem a bit odd.

I couldn't say if this happens with subsequent saves once the initial one has been created, it only took maybe 30 seconds as opposed to "10 minutes", and it definitely didn't lead to any weird behavior for me. It just kind of happened and that was it.

**Comment by refractionpcsx2** [comment] 2023-02-18 15:15
That's probably quite normal after loading a savestate, our ejection stuff isn't great.

**Comment by TheTechnician27** [comment] 2023-02-18 15:22
> That's probably quite normal after loading a savestate, our ejection stuff isn't great.

The thing is in this case that I actually hadn't used savestates at all. I booted the game from a memory card without any Just Cause save data, and then I saved when prompted for the first time. As for the OP's issue of this happening after savestate loading, though, I don't have a clue.
