### ISSUE TITLE
[BUG]: Neo Atlas III (Japan)

### ISSUE THREAD

**Issue by spacemul** [PCSX2/pcsx2#5143] opened 2021-12-12 13:50 UTC
### Describe the Bug

graphics glitch in intro, 2 screens in height
then ingame no background and no texts

![gs_20211212144153](https://user-images.githubusercontent.com/7451522/145714994-d6b7b9d0-fcda-4c3a-88b8-798d8b8c0a56.png)

![gs_20211212144119](https://user-images.githubusercontent.com/7451522/145714995-89264490-f285-4b62-ac46-0650e8b150f9.png)

[Neo Atlas III (Japan) (2021-11-12 14-46-57).zip](https://github.com/PCSX2/pcsx2/files/7698852/Neo.Atlas.III.Japan.2021-11-12.14-46-57.zip)

### Reproduction Steps

Just launch the game

### PCSX2 Revision

1.7.2103

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 3070

**Comment by HeroponRikiBestest** [comment] 2021-12-12 15:07
The game will display text correctly if you enter it in Software mode, but then it will crash. although its basically impossible to progress due to the missing graphics.
![image](https://user-images.githubusercontent.com/50224630/145717250-b51d7baa-5ac8-43b6-bc02-7e1af8edb87d.png)
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/7698948/emuLog.txt)
In HW mode, while even more bugged, it takes longer to crash.
![image](https://user-images.githubusercontent.com/50224630/145717488-d7faf41e-b5e1-4533-9ef0-48ab6d6e8374.png)
(Unfortunately, I lost the logs from PCSX2 outright crashing from the page fault, so I can only provide logs from a freeze in the same place.)
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/7698963/emuLog.txt)


SW GSdumps:
![gs_20211212095117](https://user-images.githubusercontent.com/50224630/145717372-7354f351-eed2-4f27-a40f-682b9e39c830.png)
[gs_20211212095117.gs.zip](https://github.com/PCSX2/pcsx2/files/7698950/gs_20211212095117.gs.zip)
![gs_20211212095424](https://user-images.githubusercontent.com/50224630/145717413-0a598c58-e491-4549-ab2b-70fc7e5193c8.png)
[gs_20211212095424.gs.zip](https://github.com/PCSX2/pcsx2/files/7698952/gs_20211212095424.gs.zip)

HW GSdumps:
![gs_20211212095756](https://user-images.githubusercontent.com/50224630/145717509-de794a7d-8673-456d-920c-74228956475a.png)
[gs_20211212095756.gs.zip](https://github.com/PCSX2/pcsx2/files/7698956/gs_20211212095756.gs.zip)

One time I actually managed to get past the crashes, here are GSdumps from that point. Unfortunately I havent been able to get that far since.
[snaps.zip](https://github.com/PCSX2/pcsx2/files/7698974/snaps.zip)



From what I remember testing, the game actually worked almost entirely perfect on Dobiestation; I think it still had the opening FMV issue, but other than that, all the graphics were displayed correctly. LMK if dumps/logs are needed from Dobie, or if I need a backtrace of the SW crash in PCSX2.

**Comment by HeroponRikiBestest** [comment] 2021-12-12 15:34
The game doesn't seem to suffer from crashes on 1.6.0, and so I was able to get much farther. It seems that the game, provided it doesn't crash, works mostly fine on SW. 
1.6 SW GSdumps:
[dumps.zip](https://github.com/PCSX2/pcsx2/files/7699017/dumps.zip)
Longer blockdump:
[Neo Atlas III (Japan) (2021-11-12 14-46-57).dump.zip](https://github.com/PCSX2/pcsx2/files/7699019/Neo.Atlas.III.Japan.2021-11-12.14-46-57.dump.zip)

**Comment by gilderoylockhart01** [comment] 2021-12-13 22:04
Okay so, this game have 3 different problems so far that I can confirm.

The 1st being the FMVs which are not rendered properly (double height). Not sure what can be causing this but this isn't the only game to still do this (arctic thunder being one).

The 2nd is a very sneaky and very... unique problem. If you load the game in hardware (and by loading I mean, starting), the whole rendering will be a complete mess despite switching to software later on. You must load it in software in order for it to be fine (game storing in cache textures at boot?).

The final bug is one which is quite problematic and I found no solution for it so far. In the map, there will be quite some z-fighting bug in the edges despite the GS mode you are running at.

**Comment by tellowkrinkle** [comment] 2021-12-17 23:41
Looks like the game is defining a texture with TW=10 TH=10 TBW=63, which is such a massive stride that the texture loops over the entirety of GS memory 4 times.  Can't say I was expecting that when coding the new GSOffset.  The current looper assumes that a monotonically increasing page number will not overlap itself after a `% MAX_PAGES`, which isn't true with massive strides like this.  Will fix soon™

**Comment by HeroponRikiBestest** [comment] 2021-12-24 02:17
@tellowkrinkle why was this issue closed? The looping texture was only one of the three issues

**Comment by refractionpcsx2** [comment] 2021-12-24 02:26
It auto closed because it mentioned fixing an issue with this game in the PR which was merged.

**Comment by HeroponRikiBestest** [comment] 2021-12-24 02:34
Oh, ok, my bad. TIL 😅

**Comment by RedDevilus** [comment] 2021-12-24 02:39
If the first comment mentions a keyword and an issue number it will trigger.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

![Screenshot_20211224-033831383 (1)](https://user-images.githubusercontent.com/24227051/147309074-e8b48a51-637c-49b4-82e6-11061bf07d37.jpg)

**Comment by Mrlinkwii** [comment] 2023-02-06 16:07
how is this game on master ?

**Comment by refractionpcsx2** [comment] 2023-02-06 16:13
I think it's working with preload frame (which would need a DB entry.

But I only have a GS Dump, so if somebody else could try that.

**Comment by refractionpcsx2** [comment] 2023-02-28 21:03
Not sure when the FMV was fixed, but the missing text was fixed by #8107

**Closed by refractionpcsx2** 2023-02-28 21:03 UTC
Labels: Bug, GS: Software, GS: Hardware
