### ISSUE TITLE
[BUG]: Flashing Black Screen Bug in Jak 2

### ISSUE THREAD

**Issue by Posey999** [PCSX2/pcsx2#8320] opened 2023-03-03 09:14 UTC
### Describe the Bug

Not Sure whats Causing this Bug But i had no issues with this game in a Previous Version of the emulator it happens mostly outside of the Bar right around the Beginning of the Race to the Hoverboard Tryoutss

### Reproduction Steps

Stand outside the Bar in Haven City and Turn the Cameras
![Screenshot (754)](https://user-images.githubusercontent.com/54924151/222679863-3ab31a6b-e06b-43c2-a55b-ee91ad61b174.png)

### Expected Behavior

its Expected to Not Bug out and look like this
![Screenshot (755)](https://user-images.githubusercontent.com/54924151/222680056-8f393006-a55f-4b90-86df-924f5d45a182.png)

### PCSX2 Revision

1.7.4179

### Operating System

Windows 11

### CPU

Ryzen 5 2600X

### GPU

GTX 1070 TI

**Comment by Posey999** [comment] 2023-03-03 09:16
So Stand in this Area and turn the Camera Directly to the Right to cause the Issue
![Screenshot (756)](https://user-images.githubusercontent.com/54924151/222680859-ae1ad816-b4d7-4fc8-bd21-8c91aa52e435.png)

**Comment by Posey999** [comment] 2023-03-03 09:17
![Screenshot (757)](https://user-images.githubusercontent.com/54924151/222681085-51726e37-6871-44d2-908f-c60bcb59a902.png)

**Comment by refractionpcsx2** [comment] 2023-03-03 09:17
Do you know when it started happening? of if there's a save point nearby, if it's easy to reproduce (we'd need a memcard)

**Comment by Posey999** [comment] 2023-03-03 09:17
okay will send

**Comment by Posey999** [comment] 2023-03-03 09:21
Graphics settings are all on default as well
using the vulkan backend but it happens even in software mode

**Comment by refractionpcsx2** [comment] 2023-03-03 09:21
can you provide instructions on how to get there from your memcard please?

**Comment by Posey999** [comment] 2023-03-03 09:21
just walk outside the Bar then turn the camera

**Comment by refractionpcsx2** [comment] 2023-03-03 09:22
Cool, thanks :) I'll check it out later.

**Comment by Posey999** [comment] 2023-03-03 09:24
got banned from the Discord for a Moderator assuming i was Pirating Bios but i showed them my Fat PS2 and Even Carved my Initials in it and they still Didn't believe me they just Banned me outright so i had to post the Issue here as i can't ask for help at the discord though this was Years ago

**Comment by Posey999** [comment] 2023-03-03 09:25
i mean the Banning thing

**Comment by Posey999** [comment] 2023-03-03 09:28
i'm going to attempt Testing Older Versions Till i find the one i was using with no issues
should be Somewhere within the Last Month or So

**Comment by refractionpcsx2** [comment] 2023-03-03 09:30
I doubt my moderator was incorrect, but sure. Nobody would willingly carve their initials in to a PS2.

**Comment by Posey999** [comment] 2023-03-03 09:34
welp went as Far Back as the February 1st Revision and Black Screen is No Longer Happening

**Comment by Posey999** [comment] 2023-03-03 09:35
will need to slowly Backtrack through Versions to Find the One that Last had it working to Figure out what Went Wrong

**Comment by refractionpcsx2** [comment] 2023-03-03 09:41
Thanks, appreciated.

**Comment by Posey999** [comment] 2023-03-03 09:42
February 20th Release is fine

**Comment by Posey999** [comment] 2023-03-03 09:43
Going to Jump by 5 or So Versions at a Time to see if theres an issue and if there is then i can Quickly Narrow down which version it is

**Comment by Posey999** [comment] 2023-03-03 09:48
Wish there was a Way this could go Faster Possibly via a Separate Updater for Troubleshooters to Quickly Switch out Versions
its just a Suggestion

**Comment by Posey999** [comment] 2023-03-03 09:52
Currently happening Somewhere Between February 26 and February 20th

**Comment by refractionpcsx2** [comment] 2023-03-03 09:53
Well I have a set of preconfigured ini files where all the important things like bios, game list etc point to a central location, then I can extract a new folder and just copy in the cache folder and inis and it just works.

I suggest binary searching when doing regression testing, if you have a lot to test. So pick a midpoint between the broken version and the working version and see if that works, then pick the midpoint either side depending on if it works or not.

**Comment by Posey999** [comment] 2023-03-03 09:57
Found it

**Comment by Posey999** [comment] 2023-03-03 09:58
PCSX2 Nightly - v1.7.4146

**Comment by Posey999** [comment] 2023-03-03 09:58
that was the Last Working version

**Comment by Posey999** [comment] 2023-03-03 09:58
PCSX2 Nightly - v1.7.4147
is where the Issue Started

**Comment by refractionpcsx2** [comment] 2023-03-03 09:58
might be one for @TellowKrinkle to check then, if 4147 broke it

**Comment by Posey999** [comment] 2023-03-03 09:59
v1.7.4147

    [GS-HW: Invert rounding when shader result will get subtracted](https://github.com/PCSX2/pcsx2/pull/8250)

**Comment by Posey999** [comment] 2023-03-03 10:02
also is this light Supposed to be Flashing like this?
![image](https://user-images.githubusercontent.com/54924151/222691358-47269948-bbf6-45c9-8359-a1d5fc78924c.png)

**Comment by refractionpcsx2** [comment] 2023-03-03 10:03
That's a still picture.

**Comment by Posey999** [comment] 2023-03-03 10:03
well it Flashes Overbright when you get to this point
![image](https://user-images.githubusercontent.com/54924151/222691597-f6a5e492-cdfe-45b3-ae15-79dbf659c7d7.png)

**Comment by Posey999** [comment] 2023-03-03 10:04
it just goes back and forth between the two states

**Comment by refractionpcsx2** [comment] 2023-03-03 10:04
Probably not.  Please use the edit button, you're spamming a lot of messages on this issue, this isn't a chat program, you're just making it difficult to navigate this issue for anybody who wants to deal with it.

**Comment by Posey999** [comment] 2023-03-03 10:08
Welp? Its Happening Again
![image](https://user-images.githubusercontent.com/54924151/222692653-5aaf8dcc-346d-447d-a847-2f650d778fe4.png)

**Comment by refractionpcsx2** [comment] 2023-03-03 10:18
dude, it's not going to magically stop. We get it, it's an issue, we'll look in to it.

**Comment by Posey999** [comment] 2023-03-03 10:34
Narrowed it down to specifically 1,7.4137
![image](https://user-images.githubusercontent.com/54924151/222698303-cffb2b80-6c45-41b0-991f-d6fa5fa0d30b.png)

**Comment by refractionpcsx2** [comment] 2023-03-03 10:35
I thought you said 4146 was fine?

**Comment by Posey999** [comment] 2023-03-03 10:45
Take a look again

**Comment by refractionpcsx2** [comment] 2023-03-03 10:50
![image](https://user-images.githubusercontent.com/6278726/222701601-574cd958-492b-46bb-87a5-fce0fc496253.png)

Can you please make sure you're 100% sure it's 4137 where it broke. Thanks.

**Comment by Posey999** [comment] 2023-03-03 11:12
yeah i am
i am playing on 4136 with no issues and 4137 still has the Black screen bug when you go outside of the bar and get close the camera close to the player model

**Comment by refractionpcsx2** [comment] 2023-03-03 11:13
alright thanks

**Comment by refractionpcsx2** [comment] 2023-03-03 11:22
What would be handy as well, if you could make the back screen happen, then press F9 to change to software mode, then make a GS dump, that would be handy.

**Comment by Posey999** [comment] 2023-03-03 11:30
alright will do it in a moment

**Comment by Posey999** [comment] 2023-03-03 11:39
how do i do a GS Dump?

**Comment by refractionpcsx2** [comment] 2023-03-03 11:39
Tools -> Single frame GS Dump, it'll then put the file in your `snaps` folder, you might need to zip it up

**Comment by Posey999** [comment] 2023-03-03 11:43
Hardware GS Dump
[Jak II_SCUS-97265_20230303034214.gs.zip](https://github.com/PCSX2/pcsx2/files/10881534/Jak.II_SCUS-97265_20230303034214.gs.zip)
![Jak II_SCUS-97265_20230303034214](https://user-images.githubusercontent.com/54924151/222711964-35567a1e-f7c0-40d9-b5f1-7c3e91dec688.png)

**Comment by Posey999** [comment] 2023-03-03 11:45
Software GS Dump
[Jak II_SCUS-97265_20230303034405.gs.zip](https://github.com/PCSX2/pcsx2/files/10881544/Jak.II_SCUS-97265_20230303034405.gs.zip)
![Jak II_SCUS-97265_20230303034405](https://user-images.githubusercontent.com/54924151/222712279-8edcc2c8-6c5d-4885-821e-19743367265b.png)

**Comment by refractionpcsx2** [comment] 2023-03-03 11:48
Thanks, it seems to be fixed by #8289, but we're going to investigate why, in case it's by luck.

**Comment by Posey999** [comment] 2023-03-03 11:50
CPU Sprite Render Size Seems to Have an effect

**Comment by Posey999** [comment] 2023-03-03 11:50
![image](https://user-images.githubusercontent.com/54924151/222713335-6b0d857e-7ef8-4fd3-be58-3da6c224ae86.png)

**Comment by Posey999** [comment] 2023-03-03 11:50
![image](https://user-images.githubusercontent.com/54924151/222713402-b8d8397e-2ff5-4728-9509-315b5e3a3a1a.png)

**Comment by Posey999** [comment] 2023-03-03 12:05
hmm? It Seems to have an Effect on the Water in the Distance though
![image](https://user-images.githubusercontent.com/54924151/222716022-0a210007-d6e2-43d3-a566-d1883fc87a12.png)

**Closed** 2023-03-03 14:04 UTC
Labels: Bug
