### ISSUE TITLE
Changing references in the UI from 'CRC' to 'Hash'

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#446] opened 2015-02-02 22:06 UTC
Since it was recently unearthed in the dev channel that the value PCSX2 calculates using a game's .elf file is not actually a CRC-32 hash, I propose we change any references to the word 'CRC' in the UI to something like 'Hash'. This is much less time-consuming than fixing the code to have it calculate actual CRC hashes and then subsequently having to go through all of the lists that rely on the current values (GameIndex, GSdx's GSCrc.cpp, .pnach files, the forum's compatibility posts, the wiki, etc.) and change them to the correct values.

I believe this to be an issue with some merit to it because there's already been an instance where a user (me) thought that his image for a game was corrupt in some way because the CRC that he get for the .elf file using 7-Zip did not match the one given by the wiki or referenced in the forums.

Thanks for reading!

**Comment by ramapcsx2** [comment] 2015-02-03 11:54
It's fine by me. Syntactic tweaks can indeed help avoid confusion.

**Comment by avih** [comment] 2015-02-03 12:14
While I understand that the term CRC might not be accurate, I think the confusion from changing terminology everywhere has greater weight than the inaccuracy of using the term CRC.

The fact that after more than 10 years of PCSX2 only one user got confused by this (and managed to understand by himself what was the cause for the confusion) tells me that we should probably keep things as they are.

**Comment by karasuhebi** [comment] 2015-02-03 19:53
I understand that changing terminologies is a big deal in general but how is changing 'CRC' to 'Hash' carry that much weight? If people know what CRCs are they should know what a hash is, seeing as how the numbers they're used to calling CRCs were supposed to be CRC hashes in the first place. Let's just look at it as being less specific about the kind of hash we're using as opposed to changing terminologies entirely.

And for what it's worth, I can't recall anywhere on PCSX2 itself where the word 'CRC' is used other than the console so I don't think it'd be that jarring of a change for people. The people that most use these hashes are .pnach makers and compatibility reporters, both of which should (hopefully) be tech-savvy enough to understand that changing the name won't affect them in any way. They're still using the same number.

That's just my two cents. I do see @avih's point about no one noticing for 10 years though.

**Comment by ramapcsx2** [comment] 2015-02-15 20:23
Well, we've heard some thoughts on this and I suppose the result is to leave it like it is. Closing then.

**Closed by ramapcsx2** 2015-02-15 20:23 UTC
Labels: GUI/WX
