### ISSUE TITLE
[Feature Request]: Support for DualShock 4 controller rumble effects with native drivers

### ISSUE THREAD

**Issue by dezraj** [PCSX2/pcsx2#5251] opened 2022-01-02 12:25 UTC
### Description

Currently PCSX2 does not seem to support the vibration motors of the PS4 controller with native Windows Direct Input drivers. A work-around for this would be using X Input emulation programs such as DS4Windows, but it would be more user-friendly to have this feature working without the need of additional software.

### Reason

It would be more user-friendly to have the PS4 controller fully working on PCSX2 "out of the box" when using it on Windows.

### Examples

DuckStation emulator has native support for the DS4 rumble on Windows, so perhaps it's also possible for PCSX2?

When I check the options for inputs configuration on DuckStation, I notice that the controller back-end is set to SDL, so maybe this had to be implemented first on PCSX2 in order to have the PS4 controller vibration working on Windows?

Anyway, I'll wait someone more knowledgeable to comment on this.

Thank you in advance for your time and work.

**Comment by F0bes** [comment] 2022-01-02 17:30
Duplicate of #2970

**Closed** 2022-01-02 17:30 UTC
Labels: Duplicate
