### ISSUE TITLE
Devil May Cry: Upper-third of screen is blurred (regression)

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1725] opened 2016-12-29 18:33 UTC
***PCSX2 version:***
v1.5.0-dev-1744-g8fecd35

#1613 (gsdx tc: miss a set scaling call) introduced the regression

***PCSX2 options:***
Defaults

***Plugins used:***
Defaults, GSdx OGL, 4x Native

***Description of the issue:***
During 3D portions of the game, the upper-third of the screen is blurry. You can see the separation in screenshot. The issue is only visible in resolutions above Native.

***How to reproduce the issue:***
Boot the game, start a level and look at the top of the screen.

***Last known version to work:***
v1.5.0-dev-1426-g3b73393

***PC specifications:***
i5-6600k@4.7Ghz, GTX 1070 SC, Windows 10 64-bit Insider Build 14986

![dmcregression](https://cloud.githubusercontent.com/assets/16314399/21550810/d70b6b68-cdca-11e6-82cf-2c983131fcef.png)

**Comment by FlatOutPS2** [comment] 2016-12-29 20:50
This is probably not a PCSX2 issue, but purely the result of the small box now being stretched to screen width as it should and upscaling(something it was never meant to do) makes the difference in resolution noticeable.

**Comment by Hirato** [comment] 2016-12-31 02:51
It looks like that area is used for the healthbar and stuff.
I guess the game takes a copy of the top part of the screen, renders the UI on top of that copy, then paints that buffer back over the original image.

**Comment by DPersonalized** [comment] 2016-12-31 04:17
Oddly enough, something very similar happens in SpongeBob: BFBB (GC) in Dolphin, where there will be a 256x256 box in the top-left corner of the screen that will appear blurrier than the rest of the screen. While it doesn't make the box go away, setting Scaled EFB Copies will make the stuff in the box just as sharp as the rest of the screen. I would guess that having this kind of an option would be a workaround to this issue, as well as an enhancement for any games that might do this kind of stuff over the entire screen and not just a small part of it, but with the GS being the whiny, nagging, illogical nightmare that it is, I'm not sure it could even be done, but I would love to be surprised in this context.

**Comment by MrCK1** [comment] 2016-12-31 22:18
I forgot to mention that the screen is blurred even when the HUD isn't present on-screen if that means anything.

**Comment by FlatOutPS2** [comment] 2017-01-01 11:25
> I forgot to mention that the screen is blurred even when the HUD isn't present on-screen (but not on the pause menu) if that means anything.

That's because the box also used for drawing subtitles during FMV's and cutscenes.

**Comment by MrCK1** [comment] 2017-02-15 17:55
@FlatOutPS2 Should I close this if we know nothing can be done, or leave it open for further testing?

**Comment by ssakash** [comment] 2017-02-15 18:35
Just to be sure, does this issue also happen in custom internal resolutions? I was wondering about it as the scale factor for custom resolution is calculated with respect to the size of output circuit instead of just multiplying by the integral scaling value (which is done by 2x,3x... Native resolutions),

**Comment by FlatOutPS2** [comment] 2017-02-15 18:39
> Just to be sure, does this issue also happen in custom internal resolutions? 

Yes it does. 

@MrCK1 It shouldn't be closed as it could be fixable. As long as it has nog been confirmed either way, it should stay open.

**Comment by washingleavesandthensome23-434** [comment] 2020-01-31 08:32
hows the progress on this issue coming along ive noticed the same as well , a fix for this issue would be appreciated

**Comment by MrCK1** [comment] 2020-01-31 19:59
Well the "blur" is a result of us scaling the HUD so it will work properly when upscaling. In that sense, a fix might not be easy

**Comment by washingleavesandthensome23-434** [comment] 2020-02-01 09:34
well , ive just noticed it happens at the bottom of the screen in the first ingame cutscene or like for example it appears to be happening on any ingame hud element , popup text as well , even the very first intro level you select the statue and you get the popup text when selected it blurrs the font due to the problematic scaling you mentioned, yeah i hope this can be fixed

**Comment by washingleavesandthensome23-434** [comment] 2020-04-22 17:56
any update on this , would love this issue to be taken care of

**Comment by lightningterror** [comment] 2020-05-19 17:53
A gsdump of the issue would be nice.

**Comment by washingleavesandthensome23-434** [comment] 2020-08-19 12:59
heres a fresh gsdx dump with screenshot of the issue 

https://www3.zippyshare.com/v/zJ2j7Q5W/file.html

**Comment by washingleavesandthensome23-434** [comment] 2021-02-11 17:19
as said an update on this issue would be neato

**Comment by washingleavesandthensome23-434** [comment] 2021-04-01 03:31
sup, so hows progress would really appreciate this fixed , its REALLY annoying as all fuck , thanks a bunch in advance

**Comment by washingleavesandthensome23-434** [comment] 2022-04-11 18:15
any fix as of yet ? would appreciate alot

**Comment by refractionpcsx2** [comment] 2022-04-11 18:17
There's been a lot of things touching that within the last few months, idk if it's made any difference, I hadn't paid attention to it tbh

**Comment by washingleavesandthensome23-434** [comment] 2022-04-12 08:18
sadly no ,  actually gotten worse ....using vulkan ...getting flickering vfx/shadows as well  during DT

heres a current build dump>

https://www.mediafire.com/file/h585qrdaed4oo5o/snaps_%2528dmc1%2529.zip/file

**Closed** 2022-05-01 10:40 UTC
Labels: GS: Hardware, Regression
