### ISSUE TITLE
It seems the nvidia hack(another attempt)it's not completely problems free

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#1180] opened 2016-02-14 07:06 UTC
Starting the game in D3D11 mode result it a grid on certain screens or fade out effects it it can't be fixed until you restart the game with another mode already selected(switching modes while the problem is visible,does nothing)
![2016-02-14_080727](https://cloud.githubusercontent.com/assets/5032540/13032406/e25ce28e-d2f9-11e5-94bc-732d306ce11e.jpg)

Works fine with v1.3.1-1016-gd2e4dac and not with v1.3.1-1017-g60a90aa
http://forums.pcsx2.net/Thread-Ar-Tonelico-2-Black-Lines-Across-Screen

**Comment by refractionpcsx2** [comment] 2016-02-14 11:14
I guess I didn't cover all bases :( such a pain! 

I hate nvidia lol

**Comment by ssakash** [comment] 2016-02-14 11:24
I think the best solution would be to create a testcase and report the issue to Nvidia, that would prevent a lots of mess at code.

**Comment by willkuer** [comment] 2016-02-14 11:26
I think it was reported several times bow to nvidia.



Did i understood correctly that booting in ogl and switching to dx10 afterwards fixes the problem? How to explain that?

**Comment by ssakash** [comment] 2016-02-14 11:53
> Did i understood correctly that booting in ogl and switching to dx10 afterwards fixes the problem? How to explain that?

I don't think anything like that was stated on the thread. vsub mentioned that changing the renderer (when D3D11) via GSDX plugin settings without a core restart doesn't resolve the issue.

> I think it was reported several times now to nvidia.

IIRC previous reports were having testcases which were only possible to be reproduced on the emulator, I'm suggesting to create a different testcase where you could reproduce the issue. also does anyone know which Nvidia driver introduced this issue ?

**Comment by refractionpcsx2** [comment] 2016-02-14 12:14
> I think the best solution would be to create a testcase and report the issue to Nvidia, that would prevent a lots of mess at code.

That would be idea yes, problem is, I don't know "how" to reproduce it

**Comment by ssakash** [comment] 2016-02-14 12:54
send them a GS dump ?

**Comment by willkuer** [comment] 2016-02-14 13:13
Don't you need again the emulator to replay the gsdump?

**Comment by refractionpcsx2** [comment] 2016-02-14 13:16
they won't take a GS dump because it takes the game code (even though it's indirect), also the gs plugin isn't very specific to replicate the problem, so they would probably ignore it.

Other problem, I don't think it happens with a gsdump.

**Comment by willkuer** [comment] 2016-02-14 13:19
Therefore it could be indeed some error/undefined behaviour in the emu and amd/intel driver, or? Maybe we are barking the wrong tree?

**Comment by refractionpcsx2** [comment] 2016-02-14 13:20
It was fine on nvidia drivers until the late 200 drivers or early 300 drivers, i forget where it went wrong.

**Comment by ssakash** [comment] 2016-02-14 13:59
> Don't you need again the emulator to replay the gsdump?

GSDump can only be replayed through the GSdumpGUI. unless I'm wrong ?

Hmm, either way the issue should really be addressed on the Nvidia side. even if you can find an alternative, changes involving the viewport will still influence other games (https://github.com/PCSX2/pcsx2/issues/1026)

maybe they might be interested if you could find the exact version of driver which caused the issue ?

**Comment by refractionpcsx2** [comment] 2016-02-14 14:12
tsunamin2311 on the forums tried a bit further and said 320.49 was the last driver before it all went wrong.

**Comment by gregory38** [comment] 2016-02-14 15:21
Maybe you can ask them a changelog. But yes, it would be better to understand where the issue comes from. Is it 100% reproducible on games?

**Comment by refractionpcsx2** [comment] 2016-02-14 15:32
It is 100% reproducible without the hack in there as long as you are upscaling. 

In regards to the game this issue is for, enabling the sprite hack before loading the game will resolve it.  The game needs the sprite hack anyway

**Comment by gregory38** [comment] 2016-02-14 15:39
Did you try with a long gs dump (100+ frames) ?

**Comment by refractionpcsx2** [comment] 2016-02-14 15:42
I can't say I have, but sometimes it doesn't happen for over 10 seconds,  I'm not sure what causes it. 

I'm slightly suspecting some rounding issue when upscaling

**Comment by refractionpcsx2** [comment] 2016-02-15 21:47
Should be fixed in native now?

**Comment by vsub** [comment] 2016-02-16 16:21
Yes it works fine in native and in above native I need to use sprite hack

**Comment by refractionpcsx2** [comment] 2016-02-16 16:49
Cool, that's what I expected, as the games need the sprite hack anyway for some issues, so it should be enabled anyway :)

**Comment by tsunami2311** [comment] 2016-02-17 01:52
I have reported this and i countless times and i believe refraction created a account on nvidia forums and tried to contact manualg about finding a way to fixes, nvidia didnt want to have anything to do with it. last checked it should all be in the topic refraction linked

**Closed** 2016-02-18 18:45 UTC
