### ISSUE TITLE
[BUG] God of War 1 - FMV bug after 1.4.0

### ISSUE THREAD

**Issue by morsyfadl** [PCSX2/pcsx2#4485] opened 2021-06-08 01:13 UTC
God of War's FMV PSS and PSW files are rednered with a black bar at the bottom, which is handeled by naturally the game engine somehow.

When running the game on the 1.6.0 release this bar is present and I cant get rid of it at all.
I tried the 1.4.0 release and it worked correctly on the default settings without changing anything

this issue exists in 1.7.0 latest dev build as well

Describe the bug
Black bar at the bottom of FMVs. 

To Reproduce
Run God of War 1 with a version of pcsx2 later than 1.4.0

Expected behavior
It shouldnt appear

GS Settings
Default settings

Emulation Settings
Default settings

GS Window Screenshots

System Info (please complete the following information):

PCSX2 Revision: 1.6.0 / 1.7.0 dev rev 1284
OS:  Win 10
CPU: Ryze 3600
GPU: RX470
Logs and Dumps

**Comment by F0bes** [comment] 2021-06-08 01:15
There is a provided issue template when you create an issue, please follow it.
Does this issue happen in software mode? (Pressing F9 or changing the renderer in gsdx)

Issue template:

**Describe the bug**


**To Reproduce**


**Expected behavior**


**GS Settings**



**Emulation Settings**






**GS Window Screenshots**


**System Info (please complete the following information):**
 -   PCSX2 Revision: 
 -   OS: 
 -   CPU: 
 -   GPU: 

**Logs and Dumps**

**Comment by morsyfadl** [comment] 2021-06-08 01:32
Software mode doesnt change a thing. I tried pressing F9 and tried turning on the option to switch to SW automatically during FMV, doesnt solve it.

Also I did my best with the template. Sorry I rarely post to github.

**Comment by xuru-thor** [comment] 2021-06-08 04:34
Experiencing the exact same thing, works perfectly on version 1.4.0 and 1.5.0.

**Comment by kenshen112** [comment] 2021-06-08 04:36
Do you know which version of 1.5 it doesn't work on?

**Comment by xuru-thor** [comment] 2021-06-08 04:38
> Do you know which version of 1.5 it doesn't work on?

Sorry, I don't. I'm using v1.5.0-dev-2143-g1d983a681.

**Comment by refractionpcsx2** [comment] 2021-06-08 08:15
Looks fine in software mode for me.  That black bar at the bottom, there doesn't happen to be one at the top too, is there?

**Comment by morsyfadl** [comment] 2021-06-08 13:55
> Looks fine in software mode for me. That black bar at the bottom, there doesn't happen to be one at the top too, is there?

What version are you using? And can you share your settings?

This is how the game looks.
![gsdx_20210608154847](https://user-images.githubusercontent.com/35445029/121196928-2c002a00-c871-11eb-8103-3c10dfeedf16.png)

This is how FMV's are supposed to look and how they actually do look like using 1.4.0
![gsdx_20210608155307](https://user-images.githubusercontent.com/35445029/121197774-e132e200-c871-11eb-9eba-5f93918139b2.png)

This is the black bar when using 1.6.0
![gsdx_20210608154917](https://user-images.githubusercontent.com/35445029/121197111-54882400-c871-11eb-9d04-d3bb946f4e9f.png)

**Comment by refractionpcsx2** [comment] 2021-06-08 13:59
I'm just using 1.7 build 1286, the bars I get are because my window isn't exactly 4:3, but if I correct it I get the below.

![image](https://user-images.githubusercontent.com/6278726/121198460-0e7b9200-c86a-11eb-81f2-89fb54835f72.png)

**Comment by morsyfadl** [comment] 2021-06-08 20:46
> I'm just using 1.7 build 1286, the bars I get are because my window isn't exactly 4:3, but if I correct it I get the below.
> 
> ![image](https://user-images.githubusercontent.com/6278726/121198659-366af580-c86a-11eb-96be-be2fc05d6163.png)
> 
> Just to note, mine is the PAL version

@refractionpcsx2 
I have only the NTSC version of both GoW1 and 2.  And from your screenshot I can see the internal resolution is different. 
iirc Sony Santa Monica rendered the FMV's in ddifferent resolutions for each region, 480 for NTSC and 576i for PAL. Which is why I believe you dont get the same bug I get.

This is what observed so far: on the my NTSC version
1.6.0 / 1.7.0 r1286:

GoW1 Has the Black border bug
GoW1 game runs at 512x448 inerlaced and 640x448 w/ progressive scan on
GoW1 FMV's run at 640x480 regardless
GoW1 FMV files are PSS files rendered at 640x480

on 1.4.0 the resolutions are the same, except that the bug happenes when I enable progressive scan.

GoW2 doesnt have this issue at all because the FMVs are at 640x448

Ibelieve thats the reason you dont experience the same bug because PAL FMV files are rendered at a higher res than NTSC

I extracted the files and examined them for both games to exmine them

**Comment by RedPanda4552** [comment] 2021-06-09 22:16
Check your Zoom setting. Config > Emulation Settings > GS Window. If it is not 100%, set it to 100% exactly and see if the issue persists. I have seen before that starting the emu with zoom enabled and certain combinations of either full screen or windowed modes can result in this jarring offset in other games.

**Comment by morsyfadl** [comment] 2021-06-10 22:28
> Check your Zoom setting. Config > Emulation Settings > GS Window. If it is not 100%, set it to 100% exactly and see if the issue persists. I have seen before that starting the emu with zoom enabled and certain combinations of either full screen or windowed modes can result in this jarring offset in other games.

zomm is 100%
As I said, I'm using defualt settings and fresh installs of every version of the emulator.
And rhis is an *FMV* issue not a game issue. Meaning it only happenes when prerendered cutscenes are played, not during gameplay..

And the previous comments the resolutions I mentiond are internal resolutions.

**Comment by lightningterror** [comment] 2021-06-27 11:21
Here is the list of all 1.5 builds, see if you can track down which build introduced the issue.
https://gist.github.com/turtleli/a7de466bdf0aac4d028be5fa82a31de2

**Comment by xuru-thor** [comment] 2021-06-28 06:23
> Here is the list of all 1.5 builds, see if you can track down which build introduced the issue.
> https://gist.github.com/turtleli/a7de466bdf0aac4d028be5fa82a31de2

I did some testing and I believe it was introduced on build 1729 (v1.5.0-dev-102-g5bf12519d).

**Comment by refractionpcsx2** [comment] 2021-06-28 08:11
https://github.com/PCSX2/pcsx2/commit/5bf12519dae05a5adf0bbd69ecc3671ce54a7b0c

Just to link directly to the commit which you say broke it, it also makes sense that this changed the behaviour. Maybe Greg meant <= 640

**Comment by Bakugan455** [comment] 2021-07-10 02:58
For see discord 1.4.0 useing Hacks for fmv so best way fix it for 1.6.0 load up GSdx plugin that is avx or ssse3 because not use anymore so use 1.4.0 pugins fix bug but need real fix because 1.7.0 does not have fixed yet and needs one

**Comment by Yoshi9800** [comment] 2021-07-20 14:28
@AniLeo when close issues on Rpcs3 github when bug in Rpcs3 it self just like one in this pcsx2 bug.

**Comment by Yoshi20004** [comment] 2021-12-20 08:31
@refractionpcsx2 why is pcsx2 wiki saying this is fixed when it is not because still dev build of pcsx2 1.7.0 so can find a real fix to this bug because been broken mouths now.

**Comment by refractionpcsx2** [comment] 2021-12-20 08:36
> @refractionpcsx2 why is pcsx2 wiki saying this is fixed when it is not because still dev build of pcsx2 1.7.0 so can find a real fix to this bug because been broken mouths now.

I don't see that on the wiki? But we don't maintain the Wiki we just host it, it's for users to update, it's a wiki.

we need to think about what to do with this. We could remove the NTSC Saturation modification that's in there, but then people would bitch there's huge black lines either side,  so need to see if there's anything based on the clock settings we can detect to use the saturation instead of arbitrarily basing it on the set width/height

**Comment by Yoshi20004** [comment] 2021-12-20 08:51
@refractionpcsx2 then Add a gamedb hack for gow1 to fix black bars in fmv movies. Gamedb hacks are magic blutts that will fixed this bug without adding more bugs to outher games into pcsx2.

**Comment by refractionpcsx2** [comment] 2021-12-20 08:53
the GS isn't rigged up to the GameDB at the moment, though doing so is something we're considering (more of a pain in the ass because it's over a thread).  But we'll get around to it.

Anyway, it's not the end of the world, you aren't missing anything, there's just some extra black pixels at the bottom, the whole FMV is there, you'll survive.  If it's so much of a problem, you're welcome to play GoW on 1.4.

**Comment by Yoshi20004** [comment] 2021-12-20 08:56
Thier other problems besides this like green and problems line bug no one report yet thier is fixed need a lot of settings changed for it to work.

**Comment by refractionpcsx2** [comment] 2021-12-20 08:59
Which upscaling bug? It isn't related to this issue, but instead of complaining about bugs which haven't been reported yet, maybe consider reporting them, then we can look in to them.

However the only upscaling bug I know is the green/purple fringing, which we probably can't do a lot about easily, it's due to how the PS2 renders effects and it expects the original resolution, so upscaling it causes problems.

**Comment by Yoshi20004** [comment] 2021-12-20 09:03
Yeah for green and purple fringing here is fixed for it in God of war 1.
turn off conservative buffer allocation in render tab and enable HW hacks, turn fast texture invalidation, align Sprite merge and have half pixel offset to special (Texture - aggressive) and round Sprite to half.

**Comment by refractionpcsx2** [comment] 2021-12-20 09:07
Well, that's just the nature of upscaling PS2 games, I'm afraid.  The console kinda sucks for that and our life is a lot harder than say the Gamecube (and most definitely the PS3)

**Comment by Yoshi20004** [comment] 2021-12-20 09:07
With this and  interlacing mode off in pcsx2 settings progress scan mode off in game and dx11 mode the game runs perfect besides the black bars in fmv movie. Also settings fog fix need to so yeah need settings gow close to perfect

**Comment by Yoshi20004** [comment] 2021-12-20 09:08
So yeah need this black fmv movie bug fix because once it is they game can moved to perfect.

**Comment by prafullpcsx2** [comment] 2021-12-20 13:21
We are still discussing this? Wasn't tgis fixed with memory wrapping?

**Comment by refractionpcsx2** [comment] 2021-12-21 01:07
I'm sorry but you're absolutely clueless... Your arm to think we can just magic a fix for these things or if thin air.

**Comment by Yoshi20004** [comment] 2021-12-21 01:08
Mean guys trying to get this bug fixed unlike rpcs3 team so just close problem up and mark invalid even bug happened on Rpcs3 god of war hd so hope guys do get bug fixed soon.

**Comment by RedPanda4552** [comment] 2021-12-21 01:10
> Mean guys trying to get this bug fixed unlike rpcs3 team so just close problem up and mark invalid even bug happened on Rpcs3 god of war hd so hope guys do get bug fixed soon.

If it's so easy to fix why haven't you done it yet? Or are you just so brain dead that all you can do is clutter up our GitHub with incoherent garbage?

Please, either have something meaningful to contribute, or go away.

**Closed** 2022-04-15 10:07 UTC
Labels: Regression, GS: PCRTC
