### ISSUE TITLE
[BUG]: Wrestle Kingdom - health gages break

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#9132] opened 2023-06-30 20:49 UTC
### Describe the Bug

the health gages break in game
does it in hardware
![Wrestle Kingdom_SLPM-66401_20230630154343](https://github.com/PCSX2/pcsx2/assets/8851653/10c46d86-4c4d-41e7-8de3-24e8ebaf089d)

### Reproduction Steps

start game
choose FREE FIGHT
play and lose
rematch (first option)
the health bars are screwd up

### Expected Behavior

![Wrestle Kingdom_SLPM-66401_20230630154844](https://github.com/PCSX2/pcsx2/assets/8851653/523b587d-64d5-4154-a857-2f6260a8cba6)

### PCSX2 Revision

1.7.4666

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### Logs & Dumps

[Wrestle Kingdom_SLPM-66401_20230630154343.gs.zip](https://github.com/PCSX2/pcsx2/files/11923165/Wrestle.Kingdom_SLPM-66401_20230630154343.gs.zip)

**Comment by refractionpcsx2** [comment] 2023-06-30 20:50
can you boot the game in software and see if it's fine, please :)

**Comment by seta-san** [comment] 2023-06-30 20:57
Already tried.  It was broken slightly different

**Comment by refractionpcsx2** [comment] 2023-06-30 20:58
can you show it please?

**Comment by seta-san** [comment] 2023-06-30 20:59
When I get home. Picking up my son.

**Comment by refractionpcsx2** [comment] 2023-06-30 21:02
alright, thanks

**Comment by seta-san** [comment] 2023-07-01 00:03
never mind it's not showing in software. from boot

**Comment by refractionpcsx2** [comment] 2023-07-01 16:43
do you mean the UI isn't showing or the bug isn't showing?

**Comment by seta-san** [comment] 2023-07-01 16:48
The bug doesn’t show when booting into software.

**Comment by refractionpcsx2** [comment] 2023-07-01 16:51
ok thanks

**Comment by refractionpcsx2** [comment] 2023-08-14 21:23
Can't reproduce this, what's the easiest way to make this happen? I went through "Drama" mode and I had health bars.

**Comment by seta-san** [comment] 2023-08-15 16:35
start game
choose FREE FIGHT
play and lose match
rematch (first option)
the health bars are screwd up

**Comment by refractionpcsx2** [comment] 2023-08-15 18:35
Cool, seems fixed on #9315

**Comment by seta-san** [comment] 2023-08-15 18:57
so it is~! excellent work

**Closed** 2023-08-24 14:42 UTC
Labels: Bug, GS, GS: Hardware
