### ISSUE TITLE
[BUG]: Honda Demo (SLED-53951) TOCA Race Driver 3

### ISSUE THREAD

**Issue by StillPlay2** [PCSX2/pcsx2#9325] opened 2023-07-23 13:51 UTC
### Describe the Bug

A big black box covers the vehicle. When you turn right, it follows you. When you turn left, it follows you.
This happens on all hardware renderers except Software Mode where it is fine.

GS Dump provided below:

### Reproduction Steps

Press Start, go into a race.

### Expected Behavior

No big black box.

### PCSX2 Revision

V1.7.4781

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 7 3800x

### GPU

AMD RX 6500XT

### GS Settings

Native Settings

### Emulation Settings

Default Settings

### GS Window Screenshots

Hardware Renderer:
![Honda Demo  Demo _SLED-53951_20230723143237](https://github.com/PCSX2/pcsx2/assets/116039192/47132d0c-e299-4cdd-87d1-c5600b87b3ff)
![Honda Demo  Demo _SLED-53951_20230723143243](https://github.com/PCSX2/pcsx2/assets/116039192/de1375a1-d305-4987-807d-cb5107896f1c)
![Honda Demo  Demo _SLED-53951_20230723143244](https://github.com/PCSX2/pcsx2/assets/116039192/ec5c5a93-b29f-4962-827c-bedce48eb19e)
![Honda Demo  Demo _SLED-53951_20230723143246](https://github.com/PCSX2/pcsx2/assets/116039192/10105754-5d88-4251-9dd0-1ca73bff6974)
![Honda Demo  Demo _SLED-53951_20230723143248](https://github.com/PCSX2/pcsx2/assets/116039192/980c17f5-043c-4680-ab35-edb0d027743e)

Software Renderer:
![Honda Demo  Demo _SLED-53951_20230723143912](https://github.com/PCSX2/pcsx2/assets/116039192/907f5a9b-de55-4f64-8999-8dd88588aa0a)
![Honda Demo  Demo _SLED-53951_20230723143916](https://github.com/PCSX2/pcsx2/assets/116039192/84afe5ee-a8a3-45a6-b449-c3462fac0f37)

### Logs & Dumps

[Honda Demo [Demo]_SLED-53951_20230723143301.zip](https://github.com/PCSX2/pcsx2/files/12138864/Honda.Demo.Demo._SLED-53951_20230723143301.zip)

**Comment by refractionpcsx2** [comment] 2023-07-23 14:01
Updated your title so it's easier to find. We did know about this but apparently there wasn't an issue.

**Comment by lightningterror** [comment] 2023-10-28 19:02
Duplicate of https://github.com/PCSX2/pcsx2/issues/913

**Closed by lightningterror** 2023-10-28 19:02 UTC
Labels: Bug, GS: Hardware
