### ISSUE TITLE
beatmania IIDX 16 - unusual delay between backing track and key audio

### ISSUE THREAD

**Issue by lain-2p** [PCSX2/pcsx2#2977] opened 2019-05-31 21:20 UTC
***PCSX2 version:***
v1.5.0-dev-3135

- **Notes**:
VSync toggling did not seem to remedy the issue, nor did changing the refresh rate in pcsx2_vm.ini to 59.82 as if it were potentially time-based from NTSC-I video modes like the earlier games.

Adjusted various EE/VU settings to no avail, and none of the speed hacks seem to impact it either.

Internal resolution/deinterlacing method did not seem to impact the problem, nor did fullscreen/windowed or using OpenGL (however OpenGL HW seems to suffer from a seperate frame pacing issue every 10 seconds or so, which is why I am opting to use DX11)

The in-game display offset function does not make up for this issue, as it equally offsets the already out of sync key and backing audio.

Tried multiple settings in SPU2-X, also to no avail.

***PCSX2 options:***
Preset 2 (safe), speedhacks enabled, VSync on, aspect 4:3

***Plugins used:***
GSdx 1.1.0 SSE4 DirectX11 HW, bob tff deinterlace
everything else default

***Description of the issue:***
  Once in a song, there is a set backing track, on top of which the key samples play to form the whole song. Currently in the emulator, this backing track is roughly one beat off from where it should be, as if it started playing ever so slightly late.
Unlike the issue with the non interlaced IIDX games, the speed at which the tracks play or the delay between the two doesn't seem to change.

This may be hard to demonstrate to someone not familiar with the series, as the issue is somewhat subtle if you aren't able to play along to the beat, but if needed I can try to demonstrate the problem in a video.

***How to reproduce the issue:***
Boot the game up, select your controller and default name, go in to FREE mode, and play Quasar in the Alphabetical folder Q. Try to line up your input to the backing track independent of the note crossing over the red line. if replicated, it will show as POOR or GOOD (and generally be audibly wrong).
The input for the first key in Quasar (1) is the square face button
(quasar was chosen as the first few notes are simple and distinct)

***Last known version to work:***
Others have seemingly had more success in the past, but I don't know the details of their PCSX2 setups.
https://youtu.be/sPCEMPIC2xE for example

***PC specifications:***
Intel i5 4670k @4.2GHz, AMD Radeon R9 290, 12GB 1600MHz DDR3 RAM, SSD, Windows 10

**Comment by kevhensen** [comment] 2019-09-03 20:35
Hi,
As per my understanding, you experience a lag between the visual and the sound of your game. Is that correct?

If so, can you take a screen capture of your sound settings (_SPU2-X Settings_ window) by going to _Config->Sound (SPU2)_?

You might want to try all the different synchronizing modes and other sound settings to see if it amplifies, reduce or fix the problem and give us insight about what happens.

Here are 2 configurations to reduce lag to a minimum you could try as an example:
![image](https://user-images.githubusercontent.com/50850536/64206474-723c8400-ce68-11e9-991e-18bdc2c90e01.png)
![image](https://user-images.githubusercontent.com/50850536/64206500-7f597300-ce68-11e9-83d3-1e5ff0d75c6d.png)
![image](https://user-images.githubusercontent.com/50850536/64206579-b16ad500-ce68-11e9-8d60-398148c03329.png)

Hope it helps,

Kevin

**Comment by Prism019** [comment] 2019-12-03 06:57
**_PCSX2 Version:_**
aa03c83126225f92ec98569646b0d2aeffc45360

This issue should affect all beatmania IIDX games (I've tested 6th style and 12 HAPPY SKY). The issue also seems to be present in at least one GuitarFreaks/DrumMania game (I tested GFDM V2).

**_PCSX2 Options:_**
Aspect Ratio: 16:9
All other settings default.

**_Plugin settings:_**
Everything default.

**_APU Settings:_**
Interpolation: 0 - Nearest
Disable Effects Processing: enabled
Module: PortAudio
PortAudio API: 2 - JACK
Synchronizing Mode: None (Audio can skip.)
Latency: 3ms
(I also tried it with Synchronizing Mode set to TimeStretch with 15ms latency. Still present.
Also tried it with Module set to SDL with the SDL API set to JACK, but that just crackled a lot.)

**_PC Specification:_**
AMD FX-8350 @ 3.6GHz, AMD Radeon R9 280X, 16GB 1333MHz DDR3 RAM, 7200 RPM HDD, Arch Linux
JACK server set to 48000Hz, 256 buffer size (5.3ms latency)

**Comment by refractionpcsx2** [comment] 2020-12-02 21:55
Is this still an issue?

**Comment by tjbautista01** [comment] 2021-01-06 18:07
Maybe late but just want to chime in on this issue.

Tried out with PCSX2 1.6.0 and I don't think it's an SPU issue. Although setting the framerate to ~59.83 for 3rd-8th style fixed the eventual early drifting issue around halfway into the track as discussed in a separate issue. Autoplaying tracks confirms that.

For this one though, it seems more like a separate issue related to the GPU/PAD (?) as the game registers the inputs very late like some good chunk of milliseconds between the keypress and when the game in the emu registers a hit, to the point that I have to hit quite early just to get a Flashing Great/Just Great in the game. Probably leaning more towards GPU as how early I would have to hit before the notes hit the red line will depend on the HI-SPEED settings in the game (very early for higher speeds, less early for slower speeds). 

Using HIDDEN+ on versions with the feature and hitting just above the lane cover can help with replicating this. For speeds around 2.5, set the lane cover up to just below where the judgements are (~200ish white number?)

It happens using either the keyboard or a IIDX controller passed thru a PS-USB converter, in which I don't think input latency is an issue as I can get Perfects just fine in DDR with a PS1 dance pad passed thru the converter.

**Comment by refractionpcsx2** [comment] 2021-01-06 18:18
have you tried the latest development build for this? we know 1.6.0 is wrong, but we changed the framerates recently.

**Comment by tjbautista01** [comment] 2021-01-07 15:58
> 
> 
> have you tried the latest development build for this using the normal framerates? we know 1.6.0 is wrong, but we changed the framerates recently.

Tried the latest dev build (v1.7.0-dev-842-g95e7045db) and it seemed to have fixed the issue with the older IIDX style without me even having to manually input the refresh rate so kudos to that.

With regards to gameplay timing though, it's really leaning towards being a GPU issue than a PAD issue, though it might be a combination of both. Like said previously, I had to press very early to get a Just Great and how early varied with the HISPEED settings. This was with IIDX 6th style. 

To confirm, I loaded up IIDX GOLD and set the Timing Adjustment to -5 and lo and behold, I could time my inputs right. This will work with versions DistorteD and above. For IIDX HAPPY SKY, I set the adjustment to -3 as this version was particularly notorious for having very late timing. 

To make sure if PAD wasn't lagging, I loaded up DDR Supernova2 as given DDR's timing was more msec-based than frame-based like IIDX so any display lag shouldn't affect it much. Confirmed also with DDR Extreme that yeah inputs were on time.

**Comment by refractionpcsx2** [comment] 2021-01-07 16:01
Okay there's a couple of things you can try

Set your output module in the SPU2 settings to Portaudio, click configure under it and make sure the latency is the lowest it can go.  Also in your PCSX2_vm.ini in the inis folder there is an option for VsyncQueueSize, set that to 0.

after that, see what the timing is like without adjustment.

**Comment by tjbautista01** [comment] 2021-01-07 16:44
> 
> 
> Okay there's a couple of things you can try
> 
> Set your output module in the SPU2 settings to Portaudio, click configure under it and make sure the latency is the lowest it can go. Also in your PCSX2_vm.ini in the inis folder there is an option for VsyncQueueSize, set that to 0.
> 
> after that, see what the timing is like without adjustment.

Tried it. Still have to press early.

For reference, here is how early illustrated by the HIDDEN+ lane cover. The red line is where I'm supposed to press once the notes are close to it but instead I have to press as the notes approach the top of the lane cover.

![image](https://user-images.githubusercontent.com/63538745/103918865-52972900-514a-11eb-81ce-624aa2ca8452.png)

**Comment by refractionpcsx2** [comment] 2021-01-07 16:46
Are you not supposed to press it when it reaches that line just above where it says poor? 🤔 I didn't realise it was so low...

okay can you try this build too? https://github.com/PCSX2/pcsx2/files/5767008/pcsx2-inputlag2.zip

**Comment by tjbautista01** [comment] 2021-01-07 16:49
> 
> 
> Are you not supposed to press it when it reaches that line just above where it says poor? 🤔 I didn't realise it was so low...
> 
> okay can you try this build too? https://github.com/PCSX2/pcsx2/files/5767008/pcsx2-inputlag2.zip

That line just above POOR is a measure indicator aka which measure are you in the track now. If you play 100% minimooG in HAPPY SKY those measure indicators are gone as said track has no known time signature.

That aside i'll try that build

**Comment by tjbautista01** [comment] 2021-01-07 17:33
> 
> 
> Are you not supposed to press it when it reaches that line just above where it says poor? 🤔 I didn't realise it was so low...
> 
> okay can you try this build too? https://github.com/PCSX2/pcsx2/files/5767008/pcsx2-inputlag2.zip

Update: Tried the build. Timing definitely improved. I can do -3 on GOLD and -1 on HAPPY SKY. for 6th Style I still have to press somewhat early but it's more on par with a PS2 plugged into a laggy HDTV using composite/AV out albeit a value higher.

Tried DDR as well and timing was also better.

So it really was a combination of input lag and GPU lag but at least one's covered now.

**Comment by Prism019** [comment] 2021-01-07 17:37
I wish I could test, but my computer isn't able to be set up right now, and I don't trust my laptop to be able to keep up with pcsx2. When my computer is set up, I will definitely be able to test changes on linux.

**Comment by refractionpcsx2** [comment] 2021-01-07 17:40
> > Are you not supposed to press it when it reaches that line just above where it says poor? 🤔 I didn't realise it was so low...
> > okay can you try this build too? https://github.com/PCSX2/pcsx2/files/5767008/pcsx2-inputlag2.zip
> 
> Update: Tried the build. Timing definitely improved. I can do -3 on GOLD and -1 on HAPPY SKY. for 6th Style I still have to press somewhat early but it's more on par with a PS2 plugged into a laggy HDTV using composite/AV out albeit a value higher (regarding GOLD and HS in which I use -2 and +1 respectively).
> 
> Tried DDR as well and timing was also better.
> 
> So it really was a combination of input lag and GPU lag but at least one's covered now.

Interesting, i mean that build is basically VsyncQueueSize = 0, but there is a small change to how often the pad updates to, though i don't suspect we can get it any better than what is in that build.

**Comment by refractionpcsx2** [comment] 2021-01-07 18:49
Okay one last try, can you try again with this build and included plugins found here: https://github.com/PCSX2/pcsx2/issues/3008#issuecomment-756307822

please follow the instructions on that post to get the benefit.

**Comment by tjbautista01** [comment] 2021-01-07 19:17
> 
> 
> Okay one last try, can you try again with this build and included plugins found here: [#3008 (comment)](https://github.com/PCSX2/pcsx2/issues/3008#issuecomment-756307822)
> 
> please follow the instructions on that post to get the benefit.

Done as instructed. Same results as earlier.

**Comment by refractionpcsx2** [comment] 2021-01-07 19:19
Okay thanks for testing :)

**Comment by refractionpcsx2** [comment] 2021-01-07 19:21
Out of curiosity, do you need to adjust it all on a PS2 to achieve correct timing?

**Comment by tjbautista01** [comment] 2021-01-07 19:29
> 
> 
> Out of curiosity, do you need to adjust it all on a PS2 to achieve correct timing?

when my ps2 is connected to an hdtv, yes for HAPPY SKY and above (all games below HS don't have the adjust option so i'm the one adjusting)

On my current setup, no. Current setup is PS2 outputting component video to a component to HDMI converter and then connected to the HDMI port of a ViewSonic VA2359-SMH monitor. When playing IIDX the monitor's set to Game mode and response time to Ultra Fast and IIDX plays as if I was playing on a CRT. Although the response time thing might not be so relevant as I can still get good results on Standard response time but eh better safe than sorry.

**Comment by refractionpcsx2** [comment] 2021-01-07 19:31
I'm just trying to establish how different it is, that's all, although I don't know if it can be improved much more and the guys who seem to be sensitive to input lag seem to be pretty happy with some of the builds I've posted related to it.  I just don't want to be chasing unicorns if it needs adjusting on the actual console too.

**Comment by tjbautista01** [comment] 2021-01-08 10:53
> 
> 
> I'm just trying to establish how different it is, that's all, although I don't know if it can be improved much more and the guys who seem to be sensitive to input lag seem to be pretty happy with some of the builds I've posted related to it. I just don't want to be chasing unicorns if it needs adjusting on the actual console too.

So I just tested it again with VSync disabled and the aspect ratio set to fit to screen (in this case, 16:9) and the timing of input got better than last time. It's now at the level you'd expect plugging the PS2 into an HDTV via composite aka better than using the PS3.

**Comment by refractionpcsx2** [comment] 2021-01-08 10:56
yeah well generally I would suggest using VSync off and the framelimiter enabled and let that do the sync, that generally has better timing as your monitors vsync rate is unlikely to fit nicely with the games running speed.  But that's good to hear!

**Comment by tjbautista01** [comment] 2021-01-08 11:40
> 
> 
> yeah well generally I would suggest using VSync off and the framelimiter enabled and let that do the sync, that generally has better timing as your monitors vsync rate is unlikely to fit nicely with the games running speed. But that's good to hear!

Yeah it seems that with versions lower than Happy Sky, players would just have to adjust themselves to compensate (Thanks Konami for using frame-based timing)

**Comment by refractionpcsx2** [comment] 2021-01-08 11:46
I guess so ;)

**Comment by limyz** [comment] 2021-02-10 05:38
@tjbautista01 I will test IIDX sometime, I have several misfires despite having the correct input on GuitarFreaks

**Comment by tjbautista01** [comment] 2021-02-10 07:27
Am using PortAudio with lowest latency settings and vsync disabled (input lag is worse with it on) but yeah input lag still remains, even when using a keyboard.

**Comment by tjbautista01** [comment] 2021-02-10 07:54
Tested with latest nightly build and recommended settings. Still has the "need to hit real early" issue like playing on a laggy HDTV. Either it's because of the engine (frame-based timing and makes use of display's refresh rate rather than internal clock like most rhythm games), input lag (present even if playing on a keyboard, but this seems to have been fixed in previous nightlys?), or maybe something else entirely.

**Comment by limyz** [comment] 2021-02-10 08:17
I know this sounds dumb, have you tried setting your display to 59Hz? Also, input lag is subjective and unavoidable. I need to test on IIDX - somehow this was magically solved in the forums (https://forums.pcsx2.net/Thread-Input-lag-on-PS2-Music-games).

![image](https://user-images.githubusercontent.com/8562888/107482673-fac16700-6bba-11eb-8994-c80fa8132f66.png)

**Comment by tjbautista01** [comment] 2021-02-10 08:24
Not possible. Monitor only can do 60Hz. Would it matter though as vsync is disabled?

**Comment by avih** [comment] 2021-02-10 08:34
> Not possible. Monitor only can do 60Hz. Would it matter though as vsync is disabled?

It's possible. Most Displays (TVs and monitors) support both 60 (PC) and 59.94 Hz (NTSC), the latter is usually chosen when you set the display rate to 59 (because the dialog only supports integer values, 59 is a known "code" for 59.94).

So the windows compositor can still introduce lag of its own, which will be smaller if the display is at 59.94.

**Comment by tjbautista01** [comment] 2021-02-10 08:35
59Hz not in selectable modes
![image](https://user-images.githubusercontent.com/63538745/107484852-f5b1e700-6bbd-11eb-98e0-0d8dced68319.png)

**Comment by limyz** [comment] 2021-02-10 08:36
Use CRU (https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU) to add 59.94Hz.

**Comment by avih** [comment] 2021-02-10 08:38
Also, depending on driver, in fullscreen it might switch to exclusive mode, which will bypass the windows compositor and remove the lag it adds.

However, there will always be some lag. The goal here is to minimize it - not to eliminate it.

**Comment by tjbautista01** [comment] 2021-02-10 08:52
Connected to a display that can do 59Hz (which is also where my PS2 is connected when playing console IIDX) and even with response time set to Ultra Fast the latency persists, even on 9th style which bumped the resolution from 240p to 480i

**Comment by limyz** [comment] 2021-02-10 09:07
The Acer KA220HQ is a TN monitor and has a rather lacklustre response time of 5ms. Your best bet is to use a 1ms MPRT display.

**Comment by tjbautista01** [comment] 2021-02-10 09:22
> 
> 
> The Acer KA220HQ is a TN monitor and has a rather lacklustre response time of 5ms. Your best bet is to use a 1ms MPRT display.

As said above, I tried it again this time connected to a display that can do 59Hz (ViewSonic VA2359-smh) which I also use for playing IIDX on PS2 (via Component->HDMI, plays well almost like playing on CRT) and yeah even on that display the latency is present.

**Comment by limyz** [comment] 2021-02-10 09:31
If you are using a playstation controller usb adapter, that significantly adds input lag and should be generally avoided

**Comment by tjbautista01** [comment] 2021-02-10 09:50
> 
> 
> If you are using a playstation controller usb adapter, that significantly adds input lag and should be generally avoided

Fpr PCSX2, am using keyboard because fully aware of the latency USB adapters have

**Comment by refractionpcsx2** [comment] 2021-02-10 09:58
Just to rule it out, can you try this build https://github.com/PCSX2/pcsx2/files/5783396/pcsx2inputlag3.zip
This changes Direct3D to use the flip model where as you kinda noted earlier windows uses 3 potential frames of latency by default, this should get around that (but may introduce tearing)

You will need to set your renderer in GSDX to D3D11 in order for it to have any effect.  The MTGS Queue option will be missing but it should be forced to 0 in this build.

That's the last thing I think we can do for input lag.

**Comment by tjbautista01** [comment] 2021-02-10 10:58
> 
> 
> Just to rule it out, can you try this build https://github.com/PCSX2/pcsx2/files/5783396/pcsx2inputlag3.zip
> This changes Direct3D to use the flip model where as you kinda noted earlier windows uses 3 potential frames of latency by default, this should get around that (but may introduce tearing)
> 
> You will need to set your renderer in GSDX to D3D11 in order for it to have any effect. The MTGS Queue option will be missing but it should be forced to 0 in this build. (of course make sure you use one of the included plugins)
> 
> That's the last thing I think we can do for input lag.

Tested the build linked on the ViewSonic screen as well as the previous build you sent me (the inputlag2 one) and although tearing is evident on keyboard the timing is close to spot-on
Will test with the Japanese IIDX controller this time with the Super Joy Box Pro adapter I have here (said combination was touted by many players back in the day to be the virtually lagless option when using the controller for PC)

**Comment by refractionpcsx2** [comment] 2021-02-10 10:59
okay well you can use the most recent dev build, the main thing is using that GSDX plugin.

Out of curiosity, if you use that GSDX with VSync enabled, what is the lag like?

**Comment by limyz** [comment] 2021-02-10 11:06
I forgot to mention I was using software rendering in my gameplay. With GSDX with Vsync enabled, I keep hitting into the next timing window (>33ms in GuitarFreaks or >22ms in IIDX). However, these games have adjustable timing in its options if the perceived delay is incorrect.

**Comment by refractionpcsx2** [comment] 2021-02-10 11:07
Thanks limyz, but I'm only interested in the D3D results in the test plugin with vsync right now.

**Comment by tjbautista01** [comment] 2021-02-10 11:16
All tests done on inputlag3 build:
Using controller with USB adapter - has lag but I think it's just the adapter (I did say virtually lagless not completely lagless)
Enabled vsync - very laggy
Using controller with USB adapter - laggier than playing on actual PS2 connected to an HDTV via composite

**Comment by refractionpcsx2** [comment] 2021-02-10 11:32
Cool, thanks for testing.

Anyway, as we came to the conclusion before, if it's "PS2-like" I'm happy, if we do better with that plugin, great, because that will get merged at some point.  But I'm not going to rush to try and improve things over the original hardware.

**Comment by tjbautista01** [comment] 2021-02-25 18:51
So just an update: tried it again this time using a USB IIDX controller and yeah timing is pretty much ok. Usin a controller thru a PS2-USB really did introduce a good amount of input lag. Can't score as well as on PS2 but it's pretty close.
![image](https://user-images.githubusercontent.com/63538745/109201985-6f142100-77dd-11eb-9020-d9cfc08e9acd.png)

**Comment by limyz** [comment] 2021-02-25 19:03
Can you try a much dense chart (any black another will work)

**Comment by tjbautista01** [comment] 2021-02-26 05:45
> 
> 
> Can you try a much dense chart (any black another will work)

My current skill level is only up to 8s-9s so for things like Another/Black Another you might need someone else to test

**Comment by refractionpcsx2** [comment] 2022-05-09 18:35
Is this still an issue when keeping the latency down (Cubeb API) and doing things in order to reduce input lag (like VRR and reducing the MTGS queue size)

**Comment by tjbautista01** [comment] 2022-05-17 18:29
the original problem in this thread (backing audio and keysounds desyncing) is no longer an issue as established a few posts ago. the remaining issue is latency from multiple parts (input, display, audio) which i'll touch in here.

input doesnt seem to be an issue as long as vsync is disabled and mtgs queue is 0 so that's crossed out. i have yet to try this on stenzek's qt build with the 'sync to host refresh option' though.

on audio re: cubeb the reported audio latency is a bit too high even on wasapi. compared it with playing iidx on mame and in the latter you hear the sound the moment you press a key (mame's 3.33ms on portaudio wasapi exclusive compared to 10ms on cubeb wasapi even when set to 'use smallest value possible'). not significant for other games but def an issue for rhythm ones.

display latency as i said earlier is kinda similar to plugging an actual ps2 in a laggy hdtv in that i have to set the in-game timing offset to -2 to achieve better results, which would be difficult for older styles that don't have the offset adjust option but unless there's a way to improve display latency i think this is as 'ps2-like' as it's gonna get?

**Comment by Prism019** [comment] 2022-05-17 18:37
> the original problem in this thread (backing audio and keysounds desyncing) is no longer an issue

The original problem in this thread *is* the latency. The audio and keysounds desyncing issue was only ever for IIDX 3rd through 8th styles, as [this post](https://github.com/PCSX2/pcsx2/issues/450#issuecomment-192802877) stated.

**Comment by tjbautista01** [comment] 2022-05-17 19:20
oh it seems i might have misunderstood. 

but on the display latency thing, it seems switching from d3d11 to opengl drastically improved the timing (can actually hit notes on the line and get a flashing great). to confirm i played the same song and chart in both iidx 5th style and iidx empress (sync LIGHT7) and also switched renderers, not changing any timing offset options in the latter. 

the 10ms audio latency isn't too bothersome but to keep timing consistent i listen to my keypresses

confirmed again with a song I can consistently AAA on empress. tried with vsync on and off but mtgs queue still at 0. timing is still ok but it seems i got better results with vsync on. either way it seems opengl might be the better renderer of choice for these games.

vulkan is def a no-no. with vsync on display latency is more horrible than d3d11 and vsync off it performs just about as good as d3d11 with vsync off.

**Comment by Prism019** [comment] 2022-11-08 11:32
It's finally playable for me, albeit having to modify the PCSX2 source to allow me to set the Audio Output Latency to "0 ms (avg)".

![image](https://user-images.githubusercontent.com/7096478/200552739-0d1df57d-0e6a-4801-872b-b28697851e5c.png)

This doesn't seem to be an issue at all, considering Cubeb reports a 40μs minimum buffer on my system with the `jack` backend.
```
[  255.4613] Opening SPU2...
[  255.4625] Initializing SndBuffer at sample rate of 48000...
[  255.4733] (Cubeb) Using normal 2 speaker stereo output.
[  255.4733] (Cubeb) Minimum latency: 0.04 ms (2 audio frames)
```

There's barely any noticeable crackling unless my GPU starts to struggle rendering any visuals, which is only during menuing and is expected with the settings I have selected.

**Comment by hoholee12** [comment] 2023-02-04 07:39
Just my 2 cents, audio in these games do have some latency, but that is not the primary issue for the gameplay.
The real issue is the video lag. video lag is massive in this emulator, so it is impossible to play the pre-12th style games with no in-game monitor timing settings.

**Comment by hoholee12** [comment] 2023-02-04 08:23
just my 2 cents, 10ms audio latency is pretty good enough.. although video lag is still an issue.

**Comment by stenzek** [comment] 2023-02-04 08:30
There's no issues with "video lag". At most, pcsx2 is adding less than one frame of video latency (due to the previous frame's buffer getting scanned out at vblank start time). That meme's been untrue for some time, if you still have input delays, it's because of other stuff (e.g. compositors, so use exclusive fullscreen, etc).

**Comment by hoholee12** [comment] 2023-02-04 08:43
if thats the case, then i might be having issues with the input lag

**Comment by hoholee12** [comment] 2023-02-04 09:03
> There's no issues with "video lag". At most, pcsx2 is adding less than one frame of video latency (due to the previous frame's buffer getting scanned out at vblank start time). That meme's been untrue for some time, if you still have input delays, it's because of other stuff (e.g. compositors, so use exclusive fullscreen, etc).

yup. exclusive fullscreen def fixed it. thanks man 👍

**Comment by refractionpcsx2** [comment] 2023-02-04 14:21
Okay well this issue is done, the original problem is fixed, and the rest of the thread is people falling over themselves trying to sort out their own issues.

**Closed by refractionpcsx2** 2023-02-04 14:21 UTC
Labels: Bug, SPU2, Waiting feedback
