### ISSUE TITLE
Gsdx-ogl not compatible with Intel MS driver (glsl compilation error)

### ISSUE THREAD

**Issue by pal1000** [PCSX2/pcsx2#345] opened 2014-11-11 11:45 UTC
-PCSX2 version used: 1.3.0-20141110154305
-Plugins used: GSdx, SPU2-X, Lilypad, Gigaherz CDVD,rest null plugins
-PCSX2 options: no settings modifications affect the issue except for switching GSDX to an OpenGL mode (hardware or software)
-Plugin settings: Tested GSdx DX9/11 hardware and software renderers. The issue doesn't happen with  DX9/11 hardware or software renderer of GSdx.
-Description: The bios or games graphics appear either black or white and they alternate depending what the game / bios does. Sound is playing normally.
-How to replicate: Boot any game or just the bios
-Last known version to work: Unknown, probably never worked
PC specifications: CPU: Intel Core i3-3220 @ 3.3Ghz GPU: Intel HD Graphics 2500, RAM: 4 GB OS: Windows 7 SP1 x64
Other comments: 
Issue in action: https://www.youtube.com/watch?v=VN3v_g67juc
This issue affects all driver releases for Intel HD Graphics 2500 that I ever used since got this PC which were in chronological order:
r2867 - it was crashing PCSX2 on game / bios boot when using OpenGL hardware or software;
r3071 -  it was crashing PCSX2 on game / bios boot when using OpenGL hardware or software;
r3347 - it was causing the same white and black alternation that affects GSDX OpenGL hardware and software modes now;
r3621 - it was causing the same white and black alternation that affects GSDX OpenGL hardware and software modes now;
r3945  - it was causing the same white and black alternation that affects GSDX OpenGL hardware and software modes now;
r3958 - this is the current driver.
Driver updates for Intel HD Graphics 2500 are published here: https://downloadcenter.intel.com/SearchResult.aspx?lang=eng&ProdId=3711
I also reported a similar problem with PPSSPP when usage of dual source alpha blending was added to it. See: https://github.com/hrydgard/ppsspp/issues/4848#issuecomment-30673657 .
I also opened a thread on Intel community forums regarding dual source alpha blending: https://communities.intel.com/thread/55691

**Comment by gregory38** [comment] 2015-08-24 09:41
I added a hack to compile shader on Intel Window driver. Could you test it ?

**Comment by maximu** [comment] 2015-08-24 15:13
OGL HW working load now under windows.

- Some issues  Stopped crash driver and freeze screen because lost signal and only heart sound -> Load screen for example (FFX-2) and some others games will be crash always or sometimes (Aleatory crash) i think based only tested on Final fantasy games , Shadow of colossus 

Crash after that this screen

![screenshot_89](https://cloud.githubusercontent.com/assets/1274014/9442913/80782fa0-4a7e-11e5-8406-8d0b083e0636.png)

 
OGL SOFT Working fine no crash detected here  .

![screenshot_90](https://cloud.githubusercontent.com/assets/1274014/9442977/d5800860-4a7e-11e5-9f15-e50c5d72add7.png)

Some photos running with OGL render

![screenshot_87](https://cloud.githubusercontent.com/assets/1274014/9443225/31b91e2c-4a80-11e5-994c-acf66cd5ddac.png)
![screenshot_88](https://cloud.githubusercontent.com/assets/1274014/9443226/31be2372-4a80-11e5-9106-606433b97f60.png)

Shadow of colossus Only work OGL Software 

![screenshot_91](https://cloud.githubusercontent.com/assets/1274014/9443725/f9358e3e-4a82-11e5-9828-7381d57e534c.png)


How debug GSDX stop error? The file GSdx_opengl_debug are 0bytes  

Nice progress :+1:

**Comment by gregory38** [comment] 2015-08-24 15:18
Open the GUI, disable accurate blending / accurate date. Try with and without depth support.

To enable extra debugging you need an extra option in the ini file
```
debug_opengl = 1
```
You might also need a dev build.

**Comment by maximu** [comment] 2015-08-24 16:49
GSDX I use this configuration Disable Acurate blending unit Depth  to "none" (Fastest) and disable Acurrate date 

![screenshot_92](https://cloud.githubusercontent.com/assets/1274014/9444395/bc118496-4a86-11e5-914b-31140949102b.png)

If use Debug_opengl=1 in GSDX.ini crash always OGL HW or Software mode.

http://paste.ofcode.org/443rdwRSGVW6WwAZfSUa4X (OGL HW) Log by Visual studios 2015

http://paste.ofcode.org/dS5rsGUpYfxFMLJz9GpqcH (OGL Soft) Log By Visual studios 2015

Excepción no controlada en 0x51F0C5DC (ig7icd32.dll) en pcsx2-dev.exe: 0xC0000005: Infracción de acceso al leer la ubicación 0x00008D6E.

No Debug_opengl=0 will run

**Comment by gregory38** [comment] 2015-08-24 16:56
What openGL version does your driver support?

**Comment by maximu** [comment] 2015-08-24 17:12
Opengl 4.0 for ivybridge HD2500 or HD4000 With some extensions opengl 4.x 

3.x GL context successfully created
Failed to find glCopyImageSubData
Failed to find glInvalidateTexImage
Failed to find glClearTexImage
Failed to find glCreateTextures
Failed to find glTextureStorage2D
Failed to find glTextureSubImage2D
Failed to find glCopyTextureSubImage2D
Failed to find glBindTextureUnit
Failed to find glGetTextureImage
Failed to find glTextureParameteri
Failed to find glCreateFramebuffers
Failed to find glClearNamedFramebufferfv
Failed to find glClearNamedFramebufferuiv
Failed to find glClearNamedFramebufferiv
Failed to find glNamedFramebufferTexture
Failed to find glNamedFramebufferDrawBuffers
Failed to find glNamedFramebufferReadBuffer
Failed to find glCheckNamedFramebufferStatus
Failed to find glCreateBuffers
Failed to find glNamedBufferStorage
Failed to find glNamedBufferData
Failed to find glNamedBufferSubData
Failed to find glMapNamedBuffer
Failed to find glMapNamedBufferRange
Failed to find glUnmapNamedBuffer
Failed to find glFlushMappedNamedBufferRange
Failed to find glCreateSamplers
Failed to find glCreateProgramPipelines
Failed to find glClipControl
Failed to find glTextureBarrier
DSA is not supported. Replacing the GL function pointer to emulate it
OpenGL information. GPU: Intel(R) HD Graphics 4000. Vendor: Intel. Driver: - Build 10.18.10.4252
Buggy driver detected, GL_ARB_separate_shader_objects will be disabled

INFO: GL_EXT_texture_filter_anisotropic is available
INFO: GL_ARB_gpu_shader5 is available
INFO: GL_ARB_draw_buffers_blend is available
INFO: GL_ARB_separate_shader_objects is NOT SUPPORTED
INFO: GL_ARB_shader_image_load_store is NOT SUPPORTED
INFO: GL_ARB_copy_image is NOT SUPPORTED
INFO: GL_ARB_buffer_storage is available
INFO: GL_ARB_clear_texture is NOT SUPPORTED
INFO: GL_ARB_clip_control is NOT SUPPORTED
INFO: GL_ARB_direct_state_access is NOT SUPPORTED
INFO: GL_ARB_texture_barrier is NOT SUPPORTED
DSA is not supported. Replacing the GL function pointer to emulate it
Error GL_ARB_texture_barrier is not supported by your driver. You can't emulate

Also I see Missing finding on Hasswell too .report to Intel .no change to much 

https://communities.intel.com/message/321997

**Comment by gregory38** [comment] 2015-08-24 18:03
Implementation of extension is nice, follwing the standard is better....
Seriously can someone say to them that the team next door implemented a free test suite (and also a free driver....)

**Comment by gregory38** [comment] 2015-08-25 12:05
I would like a test on HW with latest GIT (without accurate blending).

**Comment by avih** [comment] 2015-08-25 12:27
@gregory38 describe the exact config you want tested. Or is it just OpenGL Hardware with  any combination of checkboxes/dropdowns except that blending accuracy is set to None?

**Comment by maximu** [comment] 2015-08-25 13:05
Well after some test and buils dev/release with latest GIT are is for me without none blending and acurracy date using the latest driver for Ivy bridge  10.18.10.4252 on windows 10 x64

* With Debug GSDX build and debug_opengl=1 always crash no debug_txt 0bytes error in  ig7icd32.dll exception .

* With Release mode working OGL HW aleatory stopped driver lost signal need reset for working again 

* With OGL Soft always run no crash driver detected excepted on debug opengl mode not working crash always to run debug_opengl=1

I report to Intel these information too https://communities.intel.com/message/321997

**Comment by gregory38** [comment] 2015-08-25 16:10
Debug is only enabled in dev or debug build. It really feels Intel doesn't support the debug context correctly. Debug is only useful if GSdx manage to finish the initialization which isn't the case here (from your above post)

@avih Potentially IB driver is out-dated and might misses some extensions. (hum HW wasn't hardware). So I would like some tests on Haswell or later. Accurate blend must be disabled as I'm sure Intel doesn't support it yet (On the free driver, there is a patch of 5 lines to enable it ...).

**Comment by avih** [comment] 2015-08-25 16:22
I can test on haswell and broadwell, if you tell me exactly what you want tested, and what should I be looking at in those test.

Also, What do you mean by "The free driver" ? we're talking about Windows, aren't we? there are no "free" (OSS) Intel GPU drivers on Windows, there are only closed source drivers... (and all of them are freely available).

**Comment by gregory38** [comment] 2015-08-25 16:46
Yes by free driver I mean the linux driver. It was just an example of the basic feature that I request for gsdx.

Anyway, just test that you can start/play a game without any crash. Test first release build. If you manage to find the source of the crash for the dev build it would help a lots.

**Comment by avih** [comment] 2015-08-25 16:53
With recent 42xx Intel driver, I can run games with GSdx in OGL mode on both Haswell (win8) and broadwell (win10), with latest git master.

I don't recall any recent crash with GSdx OGL.

**Comment by gregory38** [comment] 2015-08-25 16:54
Ok. Is dev build working also?

**Comment by gregory38** [comment] 2015-08-25 16:59
I just pushed a small change to glsl to remove the Intel hack with a correct syntax. If you can test that it is still working.

**Comment by avih** [comment] 2015-08-25 17:32
Both before and after the "correct syntax" patch, on both broadwell and haswell, both in `Devel` configuration and `Release AVX2` --> GSdx OGL didn't crash neither in SW or HW renderer.

**Comment by gregory38** [comment] 2015-08-25 17:35
Ok. Great. Thanks you very much for the test. So issue is likely in IvyBridge (or previous) driver

**Comment by maximu** [comment] 2015-09-22 13:27
Hey Bad news i can confirm now is likely ivy bridge driver because tried with new version released some days ago  and same problem with HW mode Stopped driver/Freeze aleatory 

Unless new news intel ivy bridge can say that only works well in Software OGL mode :P

**Comment by pal1000** [comment] 2015-09-23 12:54
I tested OpenGL software and it works just fine. I didn't risk using the hardware mode and experience that potential driver crash.

**Comment by maximu** [comment] 2015-09-27 18:35
New information with latest commit 
GLDeviceOGL.cpp:line 1503 assertion failed OGL HW with debug build  Expresion:sev_counter < 5
![screenshot_132](https://cloud.githubusercontent.com/assets/1274014/10124514/f621595a-6556-11e5-9e7a-b3fe61fdf74d.png)

**Comment by gregory38** [comment] 2015-09-27 19:05
Sigh...
Could you post somewhere the content of the file ``` GSdx_opengl_debug.txt ```

**Comment by maximu** [comment] 2015-09-28 01:43
@gregory38 I do not see much more in the log but here error Message:ERROR: Update DepthStencil dummy??

https://gist.githubusercontent.com/maximu/cc2a684348f756543b47/raw/6b5da307091e30593ee4fabf2046e9f8eaac9faa/gistfile1.txt

**Comment by gregory38** [comment] 2015-09-28 07:38
Hum, I need to flush the file when assertion are hit otherwise it misses the interesting part... Unlikely to be the issue

**Comment by maximu** [comment] 2015-09-28 07:58
ah I see, unfortunately no line here containing Severity: High

**Comment by gregory38** [comment] 2015-09-28 13:01
Assert will only be hit if several "high severity" errors are spotted. Could you check the main emulog. Otherwise, run in dev mode (not debug). It will remove the assert but error will still be stored in the txt file. Wait did you add the gsdx ini option to enable error reporting? ``` debug_opengl = 1 ```

**Comment by maximu** [comment] 2015-09-28 13:56
I use always Debug_opengl=1 and debug_glsl_shader=1 report .

In the emulog.txt  just shows information. loop's ERROR: Update DepthStencil dummy and Severity:High	Message:GL error GL_INVALID_VALUE

https://gist.github.com/maximu/376af73be435064f0981

**Comment by gregory38** [comment] 2015-09-28 13:58
Could you just post here the ``` Severity:High ``` message. However if the message is really limited to GL_INVALID_VALUE, I won't be able to debug it.

**Comment by maximu** [comment] 2015-09-28 14:24
Yes, unfortunately it appears only that.
It is as if the driver loses the context in which it works and won't gives information to pcsx2.
Because If I tried to resume sometimes have this error OpenGL 2.x tries to load instead of OpenGL 4.x when the driver is crashed.

It is a heavy mistake intel painful debugging anyway thanks for your effort

Failed to create a 2.0 context
Error: GLLoader failed to get GL version
GSopen Failed: return code: 0xffffffff

**Comment by gregory38** [comment] 2015-09-28 14:52
Could you add a breakpoint on the ASSERT(0) line (or better in line ```case GL_DEBUG_SEVERITY_HIGH_ARB : severity = "High"; sev_counter++; break;```)

Normally it will stop the execution at the first severity error. Post the stack frame trace so we can see the bad GL function. Bonus point if you can dump the argument value of the GL function.

**Comment by Bigpet** [comment] 2015-09-28 14:56
@gregory38 also, he should make a call to "glEnable(DEBUG_OUTPUT_SYNCHRONOUS_ARB);" otherwise the callstack might not be very useful for some driver implementations.

**Comment by gregory38** [comment] 2015-09-28 15:05
No worry
```
#ifdef ENABLE_OGL_DEBUG
	if (theApp.GetConfig("debug_opengl", 0) && gl_DebugMessageCallback) {
		gl_DebugMessageCallback((GLDEBUGPROC)DebugOutputToFile, NULL);
		glEnable(GL_DEBUG_OUTPUT_SYNCHRONOUS_ARB);
	}
#endif
```

**Comment by Bigpet** [comment] 2015-09-28 15:26
alright then. Github search failed me there

**Comment by maximu** [comment] 2015-10-24 08:45
https://communities.intel.com/thread/88052

See if for once and for all get the intel driver windows update their fingers pray haha

Now on linux we can play with ivy bridge enable  blending and accurate data are supported. on mesa 11.x 
- GL_ARB_texture_barrier support
- GL_ARB_shader_image_load_store 

Nice alternative to play on PCSX2 thanks mesa driver :+1:

**Comment by gregory38** [comment] 2015-10-24 08:59
Intel doesn't support hardware more than 2 years. AMD got very bad press when they stop supporting dx10 card. Intel is much worst. In my opinion they don't want to bother. On linux, Mesa on Sandy got more feature than proprietary on Haswell....
The drama is that the biggest GPU market share is Intel (go figure why Dx is ahead).

**Comment by pal1000** [comment] 2016-06-02 08:28
OpenGL backend completely stopped working on IvyBridge after various extensions were made mandatory 1-2 months ago, but everything returned to normal yesterday with those buggy driver related workarounds being pushed.

**Comment by gregory38** [comment] 2016-06-02 08:34
It would be nice to open a bug report at Intel saying that separate shader object + dual source blending == completely broken. There is a test program here https://community.amd.com/thread/194895
I don't know if it can reproduce the Intel's bug. Otherwise you won't have any guarantee that PCSX2 will still work next week !

**Comment by pal1000** [comment] 2016-06-02 18:14
That testcase shows green screen as intended so it must be something else.

**Comment by Evolution0** [comment] 2016-06-29 00:57
Hello,

I've been looking for some  stuff on the web and suddenly came across that! You should see that, I swear you'll love it! More info here <http://tyspitigu.barceloscoffeecompany.com/ueuscc>

forsberganthony@yahoo.com

**Comment by Evolution0** [comment] 2016-07-15 19:06
Hi,

We are planning a short trip this summer and wanted to share some routes with you, what do you think? More info here <http://welcome.nichesolutionsllc.info/ueoodyc>

My Best, forsberganthony@yahoo.com

**Comment by gregory38** [comment] 2017-04-08 12:38
Let's close this issue
* Haswell got both HW&SW GL renderer
* Ivy Bridge got SW GL renderer
* Sandy Bridge is just too old

Hopefully one day we could enable SSO on Intel too. But so far we can't do more with this bad driver.

**Closed by gregory38** 2017-04-08 12:38 UTC
Labels: OS: Windows, Upstream | External, Waiting feedback
