### ISSUE TITLE
[BUG]: Bratz - Girlz Really Rock BUG

### ISSUE THREAD

**Issue by Ollyenigena** [PCSX2/pcsx2#10924] opened 2024-03-13 06:48 UTC
### Describe the Bug

In this specific stage of the game, whenever it finishes and the loading screen appears, the game crashes, closing both the game and the program. 

### Reproduction Steps

Play the game normally until you complete the mission "Find Anna." After the parachute phase, the loading will happen automatically, and it's at this moment that it closes, including the program.

### Expected Behavior

Normal loading and next stage.

### PCSX2 Revision

v1.7.5611

### Operating System

Windows 10 (64bit)

### CPU

AMD Athlon 3000G

### GPU

Radeon Vega Graphics

### GS Settings

![Bratz - Girlz Really Rock_SLUS-21791_20240313032823](https://github.com/PCSX2/pcsx2/assets/163235287/478c6733-ca4f-4817-ba7e-429f6209a1b5)
[Bratz - Girlz Really Rock_SLUS-21791_20240313032823.zip](https://github.com/PCSX2/pcsx2/files/14583301/Bratz.-.Girlz.Really.Rock_SLUS-21791_20240313032823.zip)

### Emulation Settings

standard

**Comment by refractionpcsx2** [comment] 2024-03-13 08:21
If pcsx2 closed it should have hopefully created a crash dump file in your pcsx2 folder (possibly in documents/pcsx2 if in non portable mode), can you upload that here?

**Comment by Ollyenigena** [comment] 2024-03-16 18:32
> If pcsx2 closed it should have hopefully created a crash dump file in your pcsx2 folder (possibly in documents/pcsx2 if in non portable mode), can you upload that here?

Okaay, I'm not sure if this is the right file.
[crash-2024-03-14-00-38-35-363.dmp](https://github.com/PCSX2/pcsx2/files/14624867/crash-2024-03-14-00-38-35-363.dmp)
[crash-2024-03-14-00-38-35-362.txt](https://github.com/PCSX2/pcsx2/files/14624868/crash-2024-03-14-00-38-35-362.txt)

**Comment by Mrlinkwii** [comment] 2024-03-16 20:16
can i have a memcard if not already posted

**Comment by Ollyenigena** [comment] 2024-03-16 23:26
> can i have a memcard if not already posted

Just enter the Drop Zone, there will be a cutscene, and then they will parachute down, it's after that when the crash happens.

[Mcd001.zip](https://github.com/PCSX2/pcsx2/files/14625530/Mcd001.zip)

[Mcd002.zip](https://github.com/PCSX2/pcsx2/files/14625529/Mcd002.zip)

**Comment by Mrlinkwii** [comment] 2024-03-17 00:10
![image](https://github.com/PCSX2/pcsx2/assets/17685135/6f3dfa82-33b8-4038-8a50-d0abeea882b0)
 can not reproduce the issue   , make your game is verified

**Comment by Ollyenigena** [comment] 2024-03-17 02:43
Okay, well '-' ... after countless attempts, the game simply worked, I feel kinda stupid now, but anyway thanks for the help :)

~ screenshots to prove that the game crashed several times and now it worked ._.
![c757b055-917e-4539-94ee-840b779994a5](https://github.com/PCSX2/pcsx2/assets/163235287/fc4fcc7f-edee-42b2-8ccf-1e05bda5d6ae)

![Bratz - Girlz Really Rock_SLUS-21791_20240316233733](https://github.com/PCSX2/pcsx2/assets/163235287/7f93f144-3076-4c61-b6fc-761783e21cf0)

**Comment by Mrlinkwii** [comment] 2024-03-17 09:23
Since everything is working for you I'm gonna closed the issue :)

**Closed** 2024-03-17 09:22 UTC
Labels: Bug
