### ISSUE TITLE
Jackie Chan Adventures (SCES-52412): Half of the screen graphical issue 

### ISSUE THREAD

**Issue by TheGITofTeo997** [PCSX2/pcsx2#1962] opened 2017-06-02 20:50 UTC
***PCSX2 version:***
This happens on the last development build as of 02-06-2017, which is 1.5.0-dev-2104-g49840bb-windows-x86

- **Note**: This always happened on all version of PCSX2, i always update my development build everyday but this graphical glitch always happens. The right part of the screen (divided by a vertical central line) has graphical issues, things such as animations, objects or other particulars of the game don't get loaded or don't show at all. However the left part of the screen works perfectly as expected in the original game. Though, the game is playable till the end. 

***PCSX2 options:***
Not so much to say in this part, but just one important thing: the game looks better if you use OpenGL (Hardware), if you use such option you'll get less graphical bugs, even though the left part of the screen is still glitchy. Speedhacks and other emulation settings do not seem to affect the gameplay.

- **Note**: Tried all the Speedhacks and, as said in the section before, the result doesn't change.

***Plugins used:***
Used all the default plugins and GSd OpenGL, in Hardware Mode.

- **Note**: I prefer to use the GSd OpenGL plugin in Hardware mode, i have Bilinear texture filtering and an internal resolution of 4x Native. I also put the Anisotropic FIltering on 16x and CRC Hacks on automatic, however such settings do not seem to affect the gameplay problems.

***Description of the issue:***
The right part (screen vertically divided) of the screen shows several graphic glitches: since you start the game you'll immediately notice that the game menu (language selection) keeps flashing on the right part of the screen (and yes, that's quite disturbing O.o). Once you get in the game (which, i repeat, is fully playable despite of these issues), you can notice there are many problems in the right part, such as: animations not working (or totally absent), things not working correctly or things get loaded later than the left part, and this creates a really annoying game experience since it's like the game is cut in half.
Though, you can play the game until the end and reach the credits without any crashes 

***How to reproduce the issue:***
The issue always happens and has always happened in EVERY version of PCSX2 (i always update my dev-build). Yes, it got better in the time but it still persists unfortunately. You can notice that just by booting the game as you would do normally.

***Last known version to work:***
I am sorry to say that this graphical glitches always happened in every version of PCSX2.

***PC specifications:***
Here's my PC Hardware:
CPU: Intel Core i7 6700K 4.00 GHz 
RAM: Corsair Vengeance LPX DDR4 3200 MHz 32 GB 
GPU: MSI GTX 1070 GAMING X 
Audio Card: Sound Blaster ZxR 
SSD: Samsung SSD 950 PRO NVMe V-NAND 256GB 
HDD: Western Digital Caviar Black 1 TB 
Motherboard: ASUS Z170 PRO GAMING/AURA 
Power Supply: Corsair HX850i

***Special Note for the Development Team:***
FIrst i would like to thank you personally for your awesome work on this emulator. It's really a shame that game like the one i am mentioning doesn't work correctly. Just wanted to tell you this is really a great game and it is one of my favourites and it would be awesome to play it on PCSX2 in high resolution :-).
Hope you guys will fix this soon and i hope my report has been usefull too, Keep up your work!

**Comment by MrCK1** [comment] 2017-06-02 21:55
Thanks for the report, but this is a duplicate of #1838.

**Comment by lightningterror** [comment] 2017-06-02 22:23
Before this gets closed as a duplicate can you test this build ? 
https://ci.appveyor.com/project/gregory38/pcsx2/build/1.2732-master/artifacts

You can report your test at https://github.com/PCSX2/pcsx2/pull/1868

**Closed** 2017-06-03 03:49 UTC
Labels: Duplicate

**Comment by TheGITofTeo997** [comment] 2017-06-06 12:56
@lightningterror i have tested it and it looks better in the menu (since it works as expected) but worse in-game, because in the right part of the screen you can see "through walls" and see like the borders and the shadows of other buildings (i am testing in the mexican village), so on this side it is worse than the more recent build

**Comment by lightningterror** [comment] 2017-06-13 01:14
Can you test the latest git ? @turtleli pushed a new commit.

**Comment by ramfattah** [comment] 2019-04-20 09:05
for this ... i changed the video config render to Direct3D 11 rather than Open GL

**Comment by TheGITofTeo997** [comment] 2019-04-20 09:26
@ramfattah i don't know man, i have just given up on this game in this years. I have tried every configuration i could try, openGL, Direct3D but this is still not fixed. I check the PCSX2 website everyday and i always try new dev builds just for this game but this is still not fixed and i started thinking it will never be at this point.

**Comment by ramfattah** [comment] 2019-04-20 19:42
@TheGITofTeo997  i may have found a solution for you ... have you tried messing around with Aspect Ration in the actual game? im referring to the game settings and not PCSX2 . Trying changing aspect ratio to 4:3 and save changes ...

**Comment by TheGITofTeo997** [comment] 2019-04-20 20:27
@ramfattah yeah man... unluckly i have tried everything i could try :/ anyway thanks for your help! at least something else is interested into make this game working ;-) if you have any suggestion just let me know

**Comment by SimonGhostRiley** [comment] 2020-04-19 10:09
@TheGITofTeo997 Hey mate! I had the same problem...but I tried switching the renderer from Direct3D9(hardware) to Direct3D11(software) in the video(GS) >plugin settings
The game works fine..hope this helped you fix it. Have a nice day!

**Comment by Taha-Yaseen** [comment] 2025-05-16 11:43
Here is my settings and it works like a gem

<img width="429" alt="Image" src="https://github.com/user-attachments/assets/69e5f62a-0ee5-44ff-af4d-9ecba8157a96" />

**Comment by JordanTheToaster** [comment] 2025-05-16 11:48
> Here is my settings and it works like a gem

The game already works on latest PCSX2 you don't need to change anything.

**Comment by TheGITofTeo997** [comment] 2025-05-18 12:22
Yes, it has now been fixed
