### ISSUE TITLE
[BUG]: Silent Hill 2 - black screen during FMVs

### ISSUE THREAD

**Issue by Watkinsjo2** [PCSX2/pcsx2#7195] opened 2022-10-15 06:25 UTC
### Describe the Bug

FMVs will display a black screen while in-game. The audio plays correctly and the game will still continue as normal once they're over/skipped. I tracked down when this first began and it started on Nightly v1.7.3247.

I tested across D3D11, OpenGL, and Vulkan using both AMD and Nvidia GPUS at default settings.

### Reproduction Steps

Start a new game and the intro FMV will be black. The second FMV when meeting Angela has the same issue. It also happens with the title screen opening FMV after leaving the game idle for 1 minute.

### Expected Behavior

The FMVs should display correctly.

### PCSX2 Revision

v1.7.3419

### Operating System

Windows 10 (64bit)

### CPU

i7-12700KF

### GPU

RTX 3080; Radeon HD 7700

### Logs & Dumps

[emulog.zip](https://github.com/PCSX2/pcsx2/files/9791297/emulog.zip)

**Comment by kenshen112** [comment] 2022-10-15 06:32
Duplicate of #6976

**Comment by stenzek** [comment] 2022-10-15 06:47
Indeed. I have a fix for this, it just needs more double-checking to make sure it's correct...

**Closed by stenzek** 2022-10-15 06:47 UTC
Labels: Bug
