### ISSUE TITLE
[GSdx hardware bug] Jackie Chan Adventures flickering and improper cel shading effect

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#1824] opened 2017-02-14 08:05 UTC
**_Description of the issue_**:

* The black lines in the wall seem to flicker frequently in the hardware renderers, the issue isn't reproducible in the software renderer. (**_GS Dump_**: [**download link**](https://www.dropbox.com/s/w2g9tazwb2bi0nn/JackieChanTextureIssue.7z?dl=0))

  - _D3D11 hardware renderer_
![D3D11](http://i.imgur.com/1fUDrMc.png)

  - _OpenGL hardware renderer_
![OpenGL](http://i.imgur.com/pHIIOIq.png)

  - _OpenGL software renderer_
![SW](http://i.imgur.com/EllfolW.png)

* The cel shading effect on the trees will turn out a bit weird on the hardware renderer when you're running around controlling the player. ``( Also note the missing shadows, OpenGL doesn't seem to render the shadows properly at certain scenarios like this one )``

  - _OpenGL hardware renderer_
![HW_OGL](http://i.imgur.com/itmS7ns.png)

  - _OpenGL software renderer_
![OGL_SW](http://i.imgur.com/2fIZOJn.png)

**_Note_**: 

 * The D3D renderers have way more issues! D3D9 doesn't even render half of the screen and D3D11 has tons of issues along with no rendering of shadows due to lack of depth read support. I'm just highlighting the OpenGL exclusive bugs in this report.
 
 * Test was done with all accuracy options enabled and tried various combinations of hardware hacks to try and fix the issue  but all the efforts turned out to be futile.

**Comment by gregory38** [comment] 2017-02-14 09:41
Of course, you tested on the native resolution. Could be rounding issue or maybe alpha test issue. If you're motivated you can dump all the states (save and dump option) to find a wrong draw call and see what happen exactly.

**Comment by FlatOutPS2** [comment] 2017-02-14 10:35
> D3D9 doesn't even render half of the screen.

This issue also affects D3D11 and OpenGL at upscaled resolutions if you go the the Plugin Settings, and then resume the emulation.

**Comment by gregory38** [comment] 2017-03-11 10:03
@ssakash  Could it be related to #1838 ? Picking the wrong depth buffer can cause missing shadow.

**Comment by MrCK1** [comment] 2017-10-14 04:15
@ssakash I suppose the Unscale Point Line hack could be useful for the flickering? Not sure about the cel shading in general. I own Cartoon Network Racing which also uses cel shading and IIRC, the effect isn't reproduced properly in HW renderer as well.

**Comment by AmbientMalice** [comment] 2017-10-14 12:48
Worth noting XIII's cel shading isn't correct in HW renderer, either.

**Comment by Scalerize** [comment] 2022-06-25 17:44
Preload frame data Fixes Upscaling issues in this game

**Comment by Scalerize** [comment] 2022-11-24 23:07
the right side of the trees is really messed up.
![image](https://user-images.githubusercontent.com/98698811/203872682-451a35c4-a811-4211-af9f-ec1ca8fbe603.png)

Both the ps3 and the ps4 Emulate the gs correctly in this game, i wonder what the reason might be on pcsx2

**Comment by Scalerize** [comment] 2022-11-24 23:22
Seems that EE Cycle skipping also reduces artifacts slightly

Normal Cycle:
![image](https://user-images.githubusercontent.com/98698811/203873661-3ae3beaf-b3b5-4faf-9c17-fda3638c51ad.png)

Cycle skipping set to 2:
![image](https://user-images.githubusercontent.com/98698811/203873703-0abb2195-6326-4c7f-9cec-51cc384fbab9.png)

**Comment by kakashi314** [comment] 2022-12-28 16:37
002425BC
lui	v1,0x002C

Nopping the instruction seems to improve the image

**Comment by stenzek** [comment] 2023-04-08 13:52
Fixed in #8606. For the record, it was nothing to do with anything on the EE or alpha testing. Game renders the main at 1280x448, then downsamples it to 640x448, the depth is done in two halves, offsetting TBP0 for the second (same as 10 Oin and Miami Vice).

The shadows were broken because it re-uses a previous C32 target pointer as a Z16S depth buffer, but it does clear it inbetween. So we need to remove the 32-bit flag on the clear.

**Closed** 2023-04-09 16:56 UTC
Labels: Bug, GS: Hardware
