### ISSUE TITLE
Closed bugs marked as Fixed / or without feedback in a while

### ISSUE THREAD

**Issue by rcaridade145** [PCSX2/pcsx2#2317] opened 2018-02-20 14:32 UTC
https://github.com/PCSX2/pcsx2/issues?q=label%3AFixed+is%3Aopen

Some are from 2016, most recent some months old.
I think they should be ok to close, if the user does give feedback in that long.

Edit1: #777 #267 #1101

**Comment by FlatOutPS2** [comment] 2018-02-20 15:34
Some of those are valid issues that might still be active. We shouldn't change the status of those until someone has confirmed it either way. The ones that are marked fixed but are still open, waiting for feedback, might be worth closing if they have been waiting for many months.

**Comment by rcaridade145** [comment] 2018-02-20 15:41
True @FlatOutPS2 . I did take care in trying to find those that at first seemed as they were active or part of a bigger bug but not being referenced.  I am trying to group most of those as i can in a single place so its easier to take a look/take notice of.

**Comment by refractionpcsx2** [comment] 2018-02-20 19:27
What we used to do at one point was with old issues, we'd post in them asking for an update, if none was given within an amount of time (say a month) then we close it.

**Comment by lightningterror** [comment] 2018-02-23 17:00
I took care most of the stuff you mentioned, and we usually go back to older issues to check up on them if anything has changed.

**Comment by rcaridade145** [comment] 2018-02-26 12:10
Looked a bit around #32 #1578

**Comment by lightningterror** [comment] 2018-02-26 12:54
Those are still valid.

**Comment by lightningterror** [comment] 2018-03-10 15:22
Gonna close this since it's not really an active issue. Plus we track older issues like I said.

If you find anything new you can still post here.

**Closed by lightningterror** 2018-03-10 15:22 UTC
Labels: Question / Discussion
