### ISSUE TITLE
Tales of Legendia - Half Screen bug in the new GSdx

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#2692] opened 2018-11-18 22:07 UTC
***PCSX2 version:***
https://github.com/PCSX2/pcsx2/commit/c6abc08b5ffb9d4f77a7bc923ffa05d77281509f

***PCSX2 options:***
`Renderer: OpenGL (Hardware)`

I tested various combinations of options and hacks and only `OpenGL (Software)` avoids the issue, but this is not a good workaround due to significant performance problems and issue https://github.com/PCSX2/pcsx2/issues/1421.

***Plugins used:***
`GSdx (GCC 8.2.0 SSE2/AVX) 1.1.0 [libGSdx]`

Note:

The legacy GSdx is not affected.
`GSdx (GCC 8.2.0, SSE2) 1.0.0 [libGSdx-legacy-1.0.0]`

***Description of the issue:***
In `Tales of Legendia` during battles the half screen bug still exists in the new GSdx only.

GSDump - http://0x0.st/sUVG.xz

Hardware
![1](https://i.imgur.com/cW5mjQo.png)

Software
![2](https://i.imgur.com/3lYFQqB.png)
(The blurriness is a byproduct of changing the images resolution.)

***How to reproduce the issue:***

1. Start `Tales of Legendia` OpenGL (Hardware) and the new GSdx.
2. Start any battle.

***Last known version to work:***

This works with the legacy GSdx plugin.
```
GSdx (GCC 8.2.0, SSE2) 1.0.0 [libGSdx-legacy-1.0.0]
```
However building old commits is pretty difficult due to newer gcc and cmake. I was able to test back to commit 7d75a7310 without finding a good commit.

I suspect that this never worked in the new GSdx and only does in the legacy GSdx.

These are potentially relevant links.

https://github.com/PCSX2/pcsx2/issues/1339
https://github.com/PCSX2/pcsx2/issues/1574
https://github.com/PCSX2/pcsx2/pull/1579

***PC specifications:***
OS: `Slackware64-current`
Compiler: `gcc-8.2.0`
mesa: https://github.com/mesa3d/mesa/commit/9367514524f70faad99c721bac92339c8ff8bad9

**Comment by orbea** [comment] 2018-11-18 23:05
Apitrace - http://0x0.st/sU4P.xz

I am not sure if this is the first bad call, but the first call which clearly shows the issue in the framebuffer is `43550` in `Frame 4`.
```
43550 @0 glDrawArrays(mode = GL_TRIANGLE_STRIP, first = 55942, count = 4)
```
![1](https://i.imgur.com/Xg0qMH9.png)

**Comment by lightningterror** [comment] 2018-11-18 23:10
Regression build
4 commits in total so that narrows things down
1cc696ab31f51da331ea755e6cd45f1bdb02fbc6 v1.5.0-dev-1407-g1cc696ab3 https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.5.0-dev-1407-g1cc696ab3&platform=windows-x86

Working build
1b8d6a38e7abd4521d83e2d333450d7995f9718e v1.5.0-dev-1403-g1b8d6a38e https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.5.0-dev-1403-g1b8d6a38e&platform=windows-x86

**Comment by orbea** [comment] 2018-11-18 23:20
So bad commit has to be one of the following?

61333ecb407984dc658b9d5015d529f8aba87ca3
677f890c5c574dc84da9076c847e4e07b5b3f905
3653a7746ad935666f6ab2528b148ad5887395f0
1cc696ab31f51da331ea755e6cd45f1bdb02fbc6

**Comment by orbea** [comment] 2018-11-19 00:00
Are you sure about that commit range? I managed to build both 677f890 and 1cc696a where they both appear to be good commits.

**Comment by lightningterror** [comment] 2018-11-19 00:10
I believe so.

**Comment by lightningterror** [comment] 2018-11-19 02:31
Can you upload another gsdump, multiframe this time ?

**Comment by orbea** [comment] 2018-11-19 02:45
Here is a multiframe gsdump.

http://0x0.st/sUJ4.xz

Reverting this change from the above commit makes the issue go away.
```
diff --git a/plugins/GSdx/Renderers/HW/GSRendererHW.cpp b/plugins/GSdx/Renderers/HW/GSRendererHW.cpp
index 83d8256e0..05385562d 100644
--- a/plugins/GSdx/Renderers/HW/GSRendererHW.cpp
+++ b/plugins/GSdx/Renderers/HW/GSRendererHW.cpp
@@ -1146,11 +1146,11 @@ GSRendererHW::Hacks::Hacks()
 	m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::RozenMaidenGebetGarden, CRC::RegionCount, &GSRendererHW::OI_RozenMaidenGebetGarden));
 	m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::StarWarsForceUnleashed, CRC::RegionCount, &GSRendererHW::OI_StarWarsForceUnleashed));
 	m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::SuperManReturns, CRC::RegionCount, &GSRendererHW::OI_SuperManReturns));
-	m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::TalesOfLegendia, CRC::RegionCount, &GSRendererHW::OI_TalesOfLegendia));
 	m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::ArTonelico2, CRC::RegionCount, &GSRendererHW::OI_ArTonelico2));
 	m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::ItadakiStreet, CRC::RegionCount, &GSRendererHW::OI_ItadakiStreet));
 
 	if (!can_handle_depth) {
+		m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::TalesOfLegendia, CRC::RegionCount, &GSRendererHW::OI_TalesOfLegendia));
 		m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::SMTNocturne, CRC::RegionCount, &GSRendererHW::OI_SMTNocturne));
 		m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::GodOfWar2, CRC::RegionCount, &GSRendererHW::OI_GodOfWar2));
 	}
```

**Comment by lightningterror** [comment] 2018-11-19 16:46
Yea, so far all of the linked stuff is connected.**v1.5.0-dev-1407** might've fixed something that affected how the hack in GSRendererHW works. Can you confirm that the above change didn't cause any other regressions ?

**Comment by lightningterror** [comment] 2018-11-19 18:05
Opengl with depth is able to render the ui/text without the need of the OI hack, there are still problems with shadows tho.
The hack itself needs to be updated to accommodate for the changes in https://github.com/PCSX2/pcsx2/commit/1cc696ab31f51da331ea755e6cd45f1bdb02fbc6 that possibly fixed the ui/text issue.

**Comment by lightningterror** [comment] 2018-11-19 18:38
![gsdumpgui 2018-11-19 19-37-40-23](https://user-images.githubusercontent.com/18107717/48727510-b096e880-ec32-11e8-86a9-af169b8c1088.png)
![gsdumpgui 2018-11-19 19-37-07-10](https://user-images.githubusercontent.com/18107717/48727512-b096e880-ec32-11e8-997b-b694032c5d7f.png)

**Comment by orbea** [comment] 2018-11-19 19:02
Shadows look fine here.
![1](https://i.imgur.com/wJjxSjq.png)

**Comment by orbea** [comment] 2018-11-19 19:10
How do I turn depth on/off?

**Comment by lightningterror** [comment] 2018-11-19 19:11
Should be in Advanced options on linux. **Disable Depth Emulation**

**Comment by orbea** [comment] 2018-11-19 19:14
Thanks, I was staring right at it and just didn't see it, but shadows still look fine with it on or off, maybe this is specific to certain drivers?

**Comment by orbea** [comment] 2018-11-19 20:32
I think the hack is just not needed on my system, I went back to the build where I moved the hack instead of removing it and I can reproduce the issue again when depth emulation is turned off. When the hack is removed altogether this issue is entirely absent with or without depth emulation. Perhaps the shadows should be discussed in a separate issue?

Are there any platforms/drivers where this is not safe?
```
diff --git a/plugins/GSdx/Renderers/HW/GSRendererHW.cpp b/plugins/GSdx/Renderers/HW/GSRendererHW.cpp
index 83d8256e0..509c74cc0 100644
--- a/plugins/GSdx/Renderers/HW/GSRendererHW.cpp
+++ b/plugins/GSdx/Renderers/HW/GSRendererHW.cpp
@@ -1146,7 +1146,6 @@ GSRendererHW::Hacks::Hacks()
 	m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::RozenMaidenGebetGarden, CRC::RegionCount, &GSRendererHW::OI_RozenMaidenGebetGarden));
 	m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::StarWarsForceUnleashed, CRC::RegionCount, &GSRendererHW::OI_StarWarsForceUnleashed));
 	m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::SuperManReturns, CRC::RegionCount, &GSRendererHW::OI_SuperManReturns));
-	m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::TalesOfLegendia, CRC::RegionCount, &GSRendererHW::OI_TalesOfLegendia));
 	m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::ArTonelico2, CRC::RegionCount, &GSRendererHW::OI_ArTonelico2));
 	m_oi_list.push_back(HackEntry<OI_Ptr>(CRC::ItadakiStreet, CRC::RegionCount, &GSRendererHW::OI_ItadakiStreet));
 
@@ -1584,20 +1583,6 @@ bool GSRendererHW::OI_StarWarsForceUnleashed(GSTexture* rt, GSTexture* ds, GSTex
 	return true;
 }
 
-bool GSRendererHW::OI_TalesOfLegendia(GSTexture* rt, GSTexture* ds, GSTextureCache::Source* t)
-{
-	uint32 FBP = m_context->FRAME.Block();
-	uint32 FPSM = m_context->FRAME.PSM;
-
-	if (FPSM == PSM_PSMCT32 && FBP == 0x01c00 && !m_context->TEST.ATE && m_vt.m_eq.z)
-	{
-		m_context->TEST.ZTST = ZTST_ALWAYS;
-		//m_dev->ClearDepth(ds);
-	}
-
-	return true;
-}
-
 bool GSRendererHW::OI_SMTNocturne(GSTexture* rt, GSTexture* ds, GSTextureCache::Source* t)
 {
 	uint32 FBMSK = m_context->FRAME.FBMSK;
```

**Comment by orbea** [comment] 2018-11-20 15:34
@lightningterror Does the above change look at all acceptable? Given that it fixes the half screen issue and I can't reproduce the shadows issue I am not sure there is anything else I can do here.

**Comment by lightningterror** [comment] 2018-11-20 18:09
I'll need to do a bit more testing.

**Comment by orbea** [comment] 2018-11-20 18:17
Okay, thanks!

**Comment by orbea** [comment] 2018-11-21 15:42
Actually I can reproduce the shadows issue, but only with a CRC level of `debug` or `minimal` including with the above hack removed. This is reproducible with the legacy GSdx as well.

Additionally lower CRC levels introduce several other issues, an extreme performance drop, completely wrongly colored menus and frequent crashes.

Neither the crashes or wrongly colored menus are reproducible in the legacy GSdx, but instead there are depth issues in the battles and a half screen bug for the menu screen.

**Comment by orbea** [comment] 2018-11-21 15:48
I went back to commit 61333ecb4 and found with a CRC level of `none`:

* The shadows during battle are still wrong.
* Its still really slow.
* The menus are the correct color.
* It doesn't seem to crash anymore.

I'll make new issues for the latter two.

**Comment by orbea** [comment] 2018-11-21 18:56
The latter two are recent regressions, see issue https://github.com/PCSX2/pcsx2/issues/2702.

**Comment by lightningterror** [comment] 2018-11-24 12:44
If DX had depth support we could've purged this hack probably, anyway I'll close this since we already have a meta issue open for depth on dx https://github.com/PCSX2/pcsx2/issues/2458

Opengl should be fine, (at least for now) if depth is enabled and crc hacks are enabled.

**Closed by lightningterror** 2018-11-24 12:44 UTC
Labels: Fixed in OpenGL, GSdx: Hardware, Plugin: GSdx, Regression

**Comment by orbea** [comment] 2018-11-24 15:01
@lightningterror Just to make it clear this just masks the issue with opengl and it will still occur with depth off.

At the very least it would be better if this was purged for at least Linux where I think users will only use GL.

**Comment by lightningterror** [comment] 2018-11-24 16:49
I know, I'm leaving it for the sake of dx. Anyway gl users don't need to disable depth most of the time.

**Comment by orbea** [comment] 2018-11-24 17:14
Understood, it might be useful to track all the hacks which aren't needed on GL or vica versa.

**Comment by lightningterror** [comment] 2018-12-10 15:21
It looks like the hack is no longer needed on dx11 as well with the depth conversion being ported.

It can be purged now it seems.

**Comment by orbea** [comment] 2018-12-10 16:19
Cool to hear!
