### ISSUE TITLE
[BUG] severe graphic corrupt in Jak2 when playing Onin's symbols minigame

### ISSUE THREAD

**Issue by Sgtbomber91** [PCSX2/pcsx2#4142] opened 2021-01-14 17:16 UTC
**Describe the bug**

severe graphic corruption in Jak 2 (SCUS-97265), when playing Onin's minigame.
Symbols still appear during minigame, but background and textures goes nuts.
![jak2_minigame_corrupted](https://user-images.githubusercontent.com/40438332/104622736-eceaf580-5691-11eb-8da9-19ebd6d34907.jpg)

**To Reproduce**

Start play Onin's symbol popping minigame. After some time, severe graphic corruption will happen (visual garbage, missing textures, flickering stuff)
Switching from DirectX11 to OpenGL doesn't resolve the issue.
Software mode works fine.

**Expected behavior**

No graphic corruption, as the minigame plays on
![jak2_minigame_ok](https://user-images.githubusercontent.com/40438332/104622742-ef4d4f80-5691-11eb-8f1c-5f10dfbd3150.jpg)

**GS Settings**

**Emulation Settings**

none, since even the safest GS preset possibile and/or everything at Default for the Graphic plugin causes the issue

**GS Window Screenshots**

**System Info (please complete the following information):**
 - PCSX2 Revision: 1.7.0-dev-869
 - OS: Win10
 - CPU: Amd Ryzen 1700
 - GPU: AMD radeon RX Vega56

**Logs and Dumps**
https://www.dropbox.com/s/ei78bm00iwb8n8p/jak2_minigame_corrupted.gs.7z?dl=0

**Comment by MrCK1** [comment] 2021-01-14 17:18
@Sgtbomber91 Can you please provide us a blockdump using the System-> Create Blockdump option. You'll have to load as normal and play the minigame for a while so we have some data to work with. Thanks.

**Comment by refractionpcsx2** [comment] 2021-01-14 17:19
software mode and hardware mode look the same in that GS Dump, they both look like the top picture.

**Comment by Sgtbomber91** [comment] 2021-01-14 17:27
> 
> 
> software mode and hardware mode look the same in that GS Dump, they both look like the top picture. Can you remake the GS Dump using software mode please?

here it is.
https://www.dropbox.com/s/f4b03dki1l3svqj/jak2_minigame_sw_safest_ok.gs.7z?dl=0

**Comment by MrCK1** [comment] 2021-01-14 17:28
Thanks, do you have widescreen patches enabled by any chance? One of our testers thinks that might be the cause of your issue

**Comment by Sgtbomber91** [comment] 2021-01-14 17:47
> 
> 
> @Sgtbomber91 Can you please provide us a blockdump using the System-> Create Blockdump option. You'll have to load as normal and play the minigame for a while so we have some data to work with. Thanks.

Doing a fresh boot of the game, loading the memory card save, and playing the minigame two times doesn't show the corruption. Weird.
https://www.dropbox.com/s/ptdh0zej86fbukm/SCUS-97265%20%282.01%29.iso%20%282021-00-14%2018-31-17%29.dump?dl=0
**my Hacks **: 
EE cycle: 0
EE Steam: 0
MTVU ON
InstantVU ON
MicroVU Flag Hack
Fast texture invalidation
Skipdraw range 1:1
Wild arms offset
Merge sprites

Uhm, thinking on it, it seems that the corruption happens after a variegated playthrough (roaming around, level loading, deaths, missions), along with some save-state scumming.
It may be "emulator fatigue"?

**Comment by Sgtbomber91** [comment] 2021-01-14 17:49
> 
> 
> Thanks, do you have widescreen patches enabled by any chance? One of our testers thinks that might be the cause of your issue

I do have widescreen patched enabled, but while creating the blockdump i got no texture corruptions during the test case.

**Comment by MrCK1** [comment] 2021-01-14 18:42
By chance, do these issues go away if you set skipdraw back to 0?

**Comment by Sgtbomber91** [comment] 2021-01-14 19:26
Resetting Skipdraw range to 0/0 actually causes characters shadows to become "solid", which is quite undesirable.

I made another try, messing up with the quick-state saves, and it seems to progressively cause some internal garbage, which ultimately seems to increase the chances of graphic corruption.

Triggering the texture corruption in the minigame isn't exactly easy, since you also need to progress a bit into it, and becomes quite hard after reaching 300+ points.

**Comment by refractionpcsx2** [comment] 2022-03-05 14:36
Is this still an issue? It must be noted that this game requires Auto Flush (not on by default in HW mode) to render effects correctly, and may be further improved by #5580 (if by nothing but performance with Auto Flush enabled)

**Comment by coornio** [comment] 2022-05-11 11:06
Can we get a new dump here? All 3 links are dead.

**Comment by Technostrophe** [comment] 2023-04-20 20:54
[Jak II SCUS-97265 (Save File + GS Dump).zip](https://github.com/PCSX2/pcsx2/files/11290378/Jak.II.SCUS-97265.Save.File.%2B.GS.Dump.zip)
![Jak II (Hardware)](https://user-images.githubusercontent.com/124680696/233485182-a150d79a-e419-46cb-a49e-caf3ef543c07.png)
![Jak II (Software)](https://user-images.githubusercontent.com/124680696/233485192-2c81e1f5-b61e-47b5-9077-65c1da9a3784.png)

Checked out the issue, attached pictures as well as a zip containing a save file for the NTSC-U version as well as a GS Dump with an icon on the screen, preliminary findings show no corruption, mini-game has been tested 5x on each renderer.

**Comment by refractionpcsx2** [comment] 2023-08-15 11:22
Got @Technostrophe to recheck just to be sure and it seems this is fine now, so closing :)

**Closed by refractionpcsx2** 2023-08-15 11:22 UTC
Labels: Bug, GS: Hardware
