### ISSUE TITLE
[BUG] (Qt): ALT+RETURN full screen hotkey conflicts with the RETURN key bound to a button after switching to a different window

### ISSUE THREAD

**Issue by ElTioRata** [PCSX2/pcsx2#6930] opened 2022-08-27 18:55 UTC
### Describe the Bug

After switching to different window, pressing RETURN key (when bound to a controller button) will make the game full screen (even though the hotkey for that is ALT+RETURN), workaround for this binding the full screen hotkey to a different key or key combination (for example: CTRL+RETURN)

### Reproduction Steps

1. Make sure to have ALT+RETURN full screen hotkey configured (default settings).
2. Also make sure to have RETURN key bound to a controller bound (like X).
3. Play any ISO.
4. Switch to another window.
5. Switch to PCSX2.
6. Press RETURN key.
7. PCSX2 will switch to full screen.

### Expected Behavior

NOT FULL SCREENIZE WHEN PRESSING RETURN EVEN AFTER SWITCHING TO A DIFFERENT WINDOW.

### PCSX2 Revision

v1.7.3256

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment] 2023-08-31 12:24
This is by design. If one bind triggering blocked others, you wouldn't be able to have multiple binds activate on a single keypress.

I special cased hotkeys, so that if e.g. you had save bound to CTRL+F1, and load bound to F1, it won't activate both when you release F1 after pressing it with CTRL, but other than that, this is a won't fix, sorry.

**Closed by stenzek** 2023-08-31 12:24 UTC
Labels: Bug
