### ISSUE TITLE
[BUG]:  increase/decrease hotkey doesn't function properly.

### ISSUE THREAD

**Issue by Fujosej** [PCSX2/pcsx2#8059] opened 2023-02-06 15:23 UTC
### Describe the Bug

When I use hotkeys to increase or decrease the target speed, 
<details>
  <summary>Spoiler</summary>

![image](https://user-images.githubusercontent.com/37980944/217009974-635c82ab-30d5-4357-80d6-12edf152d80a.png)

</details>

it doesn't update the emulation speed after each consecutive press of the bind. To make it work, I need to press the turbo/fast forward bind (in my case, 'tab'), and then it will register the target speed increase or decrease. I have to repeat this process each time I want to change the target speed.

### Reproduction Steps

In any game press the binds for increase or decrease the target speed
<details>
  <summary>Spoiler</summary>

![image](https://user-images.githubusercontent.com/37980944/217009974-635c82ab-30d5-4357-80d6-12edf152d80a.png)

</details>
You will be stuck at one speed until you press the TAB and then it will register the change for target speed again

### Expected Behavior

It should update the emulation speed after each consecutive press of the bind.

### PCSX2 Revision

PCSX2 Nightly - v1.7.4013

### Operating System

Windows 10 (64bit)

**Comment by guidodi** [comment] 2023-05-02 06:37
Any help with this devs? It is broken since last year, it broke around v3800. Thanks.

**Comment by Mrlinkwii** [comment] 2023-05-09 13:24
@Fujosej  can you find when exactly it broke

**Comment by Mrlinkwii** [comment] 2023-05-28 11:35
> > @Fujosej can you find when exactly it broke
> 
> It was v1.7.3828


 Thanks for letting me know:)

**Comment by Fafner1000** [comment] 2023-06-20 20:44
I can confirm it has been fixed with one the latest updates. Thanks.

**Comment by Mrlinkwii** [comment] 2023-06-20 22:00
cool , ill close as completed then

**Closed as completed by Mrlinkwii** 2023-06-20 22:00 UTC
Labels: Bug
