### ISSUE TITLE
[BUG]: The King Of Fighters 94 polygon background disappears

### ISSUE THREAD

**Issue by tee4341** [PCSX2/pcsx2#5413] opened 2022-01-26 08:51 UTC
### Describe the Bug

The King Of Fighters 94 polygon background disappear
![screenshot 9](https://user-images.githubusercontent.com/48321898/151131767-dfc32ebd-6777-42de-a956-189b80af5115.jpg)
![screenshot 10](https://user-images.githubusercontent.com/48321898/151131774-b4e20c8b-1ff3-4288-9262-3b20c7db2390.jpg)
![screenshot 11](https://user-images.githubusercontent.com/48321898/151131779-cd747f3e-12d2-44e2-bfa1-c6dac458d023.jpg)
![screenshot 2](https://user-images.githubusercontent.com/48321898/151131783-d5061fc0-9953-4817-8a77-405e5886816a.jpg)
![screenshot 3](https://user-images.githubusercontent.com/48321898/151131789-da10b22e-6c9f-4f76-8ed1-ae185c2ab3bd.jpg)
![screenshot 4](https://user-images.githubusercontent.com/48321898/151131792-19c78682-e352-4cda-90dd-f3dd263d22f7.jpg)
![screenshot 5](https://user-images.githubusercontent.com/48321898/151131795-85c68bcc-c929-4617-93e7-08b363074e9e.jpg)
![screenshot 6](https://user-images.githubusercontent.com/48321898/151131799-2fbaf195-8ede-4379-b809-d46fd00ee5ea.jpg)
![screenshot 7](https://user-images.githubusercontent.com/48321898/151131802-9e8a9aba-84c7-47d8-a910-0753b5f9038b.jpg)
![screenshot 8](https://user-images.githubusercontent.com/48321898/151131804-b435c7ee-c23b-4f21-809f-99b5fb98035b.jpg)
s

### Reproduction Steps

polygon background disappear

### Expected Behavior

polygon background ok

### PCSX2 Revision

1.7.2271

### Operating System

Windows 11

### CPU

i7

### GPU

gtx 950m

**Comment by refractionpcsx2** [comment] 2022-01-26 14:36
Duplicate of #3496

Please search before making new issues.

**Closed by refractionpcsx2** 2022-01-26 14:36 UTC
Labels: Bug
