### ISSUE TITLE
007 Nightfire's crosshair is useless in hardware renderer

### ISSUE THREAD

**Issue by divinity76** [PCSX2/pcsx2#2074] opened 2017-09-15 20:29 UTC
***PCSX2 version:***
``PCSX2 1.5.0-20170907181526 - compiled on Sep  7 2017`` [(but some googling shows that this issue has been present since at least 2013)](http://forums.pcsx2.net/Thread-Graphical-Issues-with-007-Nightfire)

***PCSX2 options:***
i have been been shuffling options for over 2 hours, unable to make this go away except by using software renderer (which doesn't have the problem at all... but doesn't look pretty. at that point i may as well play with my real ps2), so its safe to say that the exact options doesn't really matter, but for a specific setup that showcase the error: no speedhacks, OpenGL Hardware renderer, and everything at default settings (or, Interlacing: None. Texture Filtering: Nearest. 8-bit Textures disabled. Internal Resolution: Native. Mipmapping: Off. CRC Hack Level: None. HW Hacks disabled. Accurate Date disabled. Blending Unit Accuracy: None.)
![img](https://image.prntscr.com/image/oFoKVNxSSTOJMkhz6qU3ZA.png)

***Plugins used:***
only the default plugins. 
![img](https://image.prntscr.com/image/z3oyaGH3T_ujPshfVQsbog.png)

***Description of the issue:***
the crosshair is a big red square, making it near impossible to precision-aim at enemies far away, and it's very annoying to play with.

![gsdx_20170915220533](https://user-images.githubusercontent.com/1874996/30501372-82e251ea-9a62-11e7-95aa-fd251bb92e70.jpg)
[gsdx_20170915220533.gs.zip](https://github.com/PCSX2/pcsx2/files/1307647/gsdx_20170915220533.gs.zip)
![gsdx_20170915220533](https://user-images.githubusercontent.com/1874996/30501397-99c72700-9a62-11e7-909c-6258cd4a8176.jpg)

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
start any mission where you need a gun (not a sniper, which is the only weapon you can use in the very first mission)

***Last known version to work:***
probably never worked. i found a forum thread from 2013 complaining about the same.

***PC specifications:***
laptop: AORUS X5 v6 15.6" 120Hz
CPU: i7-6820HK (4 cores, 2.7->3.6GHz turbo, 8Mb L3 cache, overclockable)
RAM: 32GB (DDR4 2400 MHz SO-DIMM, 2x16GB, 2 free sockets, upgradable to 64GB, made by G.Skill)
GPU: GTX 1070 (8GB GDDR5, made by Gigabyte, overclockable)
Display: 15.6" Full HD 1920x1080 Wide Viewing Angle 120Hz & 5ms Anti-Glare LCD with G-SYNC (by Aorus)
Chipset: Mobile Intel HM170 Express
disk: 1x500GB SSD (Samsung SM951, by specs 1550 MB/s write, 2150MB/s read, 300,000IOPS, but i'm not even capable of reaching half of those speeds when testing...)

**Comment by MrCK1** [comment] 2017-09-15 20:42
Duplicate of #258

**Closed** 2017-09-15 21:49 UTC
