### ISSUE TITLE
GTA Liberty city stories hud transparency bug in directx mode

### ISSUE THREAD

**Issue by moonbeam00** [PCSX2/pcsx2#2063] opened 2017-09-04 04:01 UTC
https://i.imgur.com/fYr1u.jpg
This is the same issue as https://github.com/PCSX2/PCSX2/issues/378
It was partially fixed in OpenGL mode here https://github.com/PCSX2/pcsx2/pull/1306
but it stil remains in directx mode. Unfortunelly liberty city stories in OpenGL mode works really poorly for me. It's unplayable both in hardware and software, both on experimental and stable versions. It's possible to port this fix to directx mode?

**Comment by lightningterror** [comment] 2017-09-04 15:43
Hardware Depth needs to be ported from OpenGL to Direct3D.

**Comment by FlatOutPS2** [comment] 2018-02-28 15:51
Duplicate of #378

**Closed** 2018-02-28 16:00 UTC
Labels: Duplicate, GSdx: Direct3D, GSdx: Hardware
