### ISSUE TITLE
Frame limiter change has no effect

### ISSUE THREAD

**Issue by XXXBold** [PCSX2/pcsx2#2952] opened 2019-05-03 19:44 UTC
***PCSX2 version:***
``PCSX2 1.5.0-0 - compiled on May  2 2019 (Linux Version, from PPA)
on Linux Mint 19.1, 64-bit (see below for more infos)``

***PCSX2 options:***
- Preset: Balanced, Multithreaded VU enabled
- Apect Ratio/Aspect Ratio Overwrite: Widescreen 16:9
- Wait for Vsync is disabled

***Plugins used:***
GS: 
![gs_window](https://user-images.githubusercontent.com/30773753/57161709-c01e7e00-6ddb-11e9-8f0c-4df8a48b4dbd.png)

***Description of the issue:***
If I enable/disable the frame limiter, the Emulator always stays at 100% of its speed.
I've tested this in a menu, where the Usage is pretty low, so it should go up to probably 400% when the frame limiter is disabled.

I've tried this with 2 different games, both are affected (I guess the game doesn't matter for this issue).

On the same machine, but on Windows, the frame limiter does work as expected.

***How to reproduce the issue:***
For me, it's 100% reproducible:
- 1. Start any game, e.g. open a menu where Resource usage is low.
- 2. Enable/Disable the Frame limiter with the hotkey, see no difference in runspeed (always ~100%).

***Last known version to work:***
`Unknown, stable seems to have the same issue`

***PC specifications:***
https://gist.github.com/XXXBold/007546b9d2e8020dec84795f09e63a30

***Log Output while running:***
https://gist.github.com/XXXBold/d0a9277c0ee9e6819d94c355fb47788b

**Comment by DonelBueno** [comment] 2019-05-04 11:21
Try running the emulator as admin.

**Comment by XXXBold** [comment] 2019-05-04 11:25
Well, there's no "admin" on Linux, but I've just tested as root. 
The problem persists.

**Comment by pixelherodev** [comment] 2019-05-04 18:28
Now that you mention it, I've  had the same problem.

Works fine on Windows, but compiled from source under Devuan the frame limiter does nothing.

**Comment by gregory38** [comment] 2019-05-04 18:35
Is turbo mode working ?

**Comment by KrossX** [comment] 2019-05-04 18:38
Maybe the compositor is forcing vsync? Try a PAL game and see if it locks at 60 fps as well.

**Comment by XXXBold** [comment] 2019-05-04 18:39
You mean the frame skipping I guess? Just enabled it (Turbo with TAB), and yes, this works.

**Comment by avih** [comment] 2019-05-04 18:39
Does it work when you disable framelimit via the config dialog? (config -> GS) Do you have vsync enabled?

**Comment by XXXBold** [comment] 2019-05-04 18:39
> Maybe the compositor is forcing vsync? Try a PAL game and see if it locks at 60 fps as well.

I have an EU BIOS, sorry :/

**Comment by XXXBold** [comment] 2019-05-04 18:42
> Does it work when you disable framelimit via the config dialog? (config -> GS) Do you have vsync enabled?

Doesn't make a difference if enable in the Dialog or toggle with F4

**Comment by mirh** [comment] 2019-05-18 12:09
[Try this](https://stackoverflow.com/a/18062444/5994170)

**Comment by XXXBold** [comment] 2019-05-18 18:21
> [Try this](https://stackoverflow.com/a/18062444/5994170)

Ahh, that solves it, cool, thanks!

I need to start PCSX2 with `vblank_mode=0 /usr/games/PCSX2-linux.sh`

However, not sure if I should close this issue (Probably PCSX2 should take care of this by itself?)

**Comment by mirh** [comment] 2019-05-18 20:28
Indeed. There must be some problem between pcsx2 and mesa driver.

**Comment by XXXBold** [comment] 2019-06-08 12:12
I'm not sure if that's a proper solution, but if I add the line "export vblank_mode=0" at the beginning of the file /usr/games/PCSX2-linux.sh (Which is created by default anyway if you install pcsx2-unstable), the Frame limiter is working if you start it over this script, without need to set it up in the terminal manually.

However, the entry from the startmenu (which is created by default, aswell) is not starting using this script (Why is it created then?), it's launching the command "env GDK_BACKEND=x11 __GL_THREADED_OPTIMIZATIONS=1 mesa_glthread=true MESA_NO_ERROR=1 PCSX2".

IMHO it would make sense to add all these Parameters to the .sh script and just launch "/usr/games/PCSX2-linux.sh" in the start menu, or what do you think?

**Comment by mirh** [comment] 2019-06-08 12:18
That "externally" forcing the driver is no solution.

**Comment by BlackLotus** [comment] 2019-07-07 20:08
Which GPU and which driver?
I have the same problem since I updated my system a week ago with my RX 570 since I upgraded to mesa 19.1.1
Didn't yet check if a mesa downgrade solves the problem, but llvmpipe (LIBGL_ALWAYS_SOFTWARE) didn't have the problematic.
Will eventually check later on what the exact source of the problem is.

**Comment by XXXBold** [comment] 2019-07-08 16:24
GPU: R9 290X
Driver: most recent 19.2-git mesa from oibaf ppa: https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

I don't really want to perform a downgrade if not necessary, might break my system xD

**Comment by mirh** [comment] 2019-07-08 19:25
https://gitlab.freedesktop.org/xorg/xserver/issues/629
https://bugs.freedesktop.org/show_bug.cgi?id=105412
:thinking: 
Are you sure compositor, DE, or whatever might not have some kind of override in place?
"Vsync always on, but if I force it, it works off" doesn't seem a bug floating around.

**Comment by XXXBold** [comment] 2019-07-09 18:54
Hm, I don't really know if it's affected in general, in Half Life 1 (OpenGL aswell), I can enable/disable VSYNC ingame, and it works (50->100FPS).

The first issue you refer to doesn't apply for me, because for me setting vblank_mode=0 DOES have an effect, as mentioned above.

The VSYNC value for me is 50 FPS/Hz, because I have connected a TV on HDMI, which is its max. refresh rate, and it can't vary between different Monitors (Guess that's a driver issue/limitation, but that's another story).

For your 2nd link, the suggested command in a response ("LIBGL_DEBUG=verbose vblank_mode=0 glxgears -info") prints out this for me:
`libGL: Can't open configuration file /home/simon/.drirc: No such file or directory.
libGL: Can't open configuration file /home/simon/.drirc: No such file or directory.
libGL: pci id for fd 4: 1002:67b0, driver radeonsi
libGL: MESA-LOADER: dlopen(/usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so)
ATTENTION: default value of option vblank_mode overridden by environment.
libGL: Can't open configuration file /home/simon/.drirc: No such file or directory.
libGL: Can't open configuration file /home/simon/.drirc: No such file or directory.
libGL: Can't open configuration file /home/simon/.drirc: No such file or directory.
/usr/share/libdrm/amdgpu.ids version: 1.0.0
libGL: Using DRI3 for screen 0
GL_RENDERER   = AMD Radeon R9 200 Series (HAWAII, DRM 3.26.0, 4.18.0-25-generic, LLVM 8.0.1)
GL_VERSION    = 4.5 (Compatibility Profile) Mesa 19.2.0-devel (git-4271430 2019-07-07 bionic-oibaf-ppa)
GL_VENDOR     = X.Org
GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_depth_bounds_test GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_EXT_texture_buffer_object GL_AMD_texture_texture4 GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_buffer_object GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_compatibility GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_ATI_meminfo GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_draw_indirect GL_ARB_get_program_binary GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_shader_subroutine GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_viewport_array GL_EXT_vertex_attrib_64bit GL_NV_vdpau_interop GL_AMD_multi_draw_indirect GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_query_buffer_object GL_AMD_shader_trinary_minmax GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_fragment_layer_viewport GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_buffer_range GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_AMD_pinned_memory GL_ARB_bindless_texture GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_compute_variable_group_size GL_ARB_enhanced_layouts GL_ARB_indirect_parameters GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_NVX_gpu_memory_info GL_ARB_ES3_1_compatibility GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_sparse_buffer GL_ARB_texture_barrier GL_ARB_transform_feedback_overflow_query GL_EXT_polygon_offset_clamp GL_EXT_shader_image_load_formatted GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_parallel_shader_compile GL_ARB_shader_atomic_counter_ops GL_ARB_shader_ballot GL_ARB_shader_clock GL_ARB_shader_viewport_layer_array GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_EXT_window_rectangles GL_MESA_shader_integer_functions GL_ARB_polygon_offset_clamp GL_ARB_texture_filter_anisotropic GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_semaphore GL_EXT_semaphore_fd GL_KHR_parallel_shader_compile GL_AMD_framebuffer_multisample_advanced GL_EXT_texture_sRGB_R8 
VisualID 1432, 0x598
14729 frames in 5.0 seconds = 2935.626 FPS
23882 frames in 5.0 seconds = 4776.359 FPS`

**Comment by mirh** [comment] 2019-07-09 19:49
> Hm, I don't really know if it's affected in general, in Half Life 1 (OpenGL aswell), I can enable/disable VSYNC ingame, and it works (50->100FPS).

NVM, then **we** are broken.

**Comment by F0bes** [comment] 2021-11-26 03:35
Is this problem solved on the latest master?

**Comment by XXXBold** [comment] 2021-11-29 17:25
@F0bes 
I've just tested it with latest master, self-built for Ubuntu 20.04 (as described in the wiki).
This time, it worked as intended (FPS could exceed monitor refresh rate when limiter was disabled). However, I'm currently running on a NVIDIA GPU, so I'm not sure if the original problem is solved, because I'm using the proprietary driver.

**Comment by F0bes** [comment] 2021-11-29 17:37
Thanks for testing. This issue is quite old and no one has reported this issue for some time so I'll close this.
In the case that this is an issue It'll just be reopened.

**Closed by F0bes** 2021-11-29 17:37 UTC
Labels: OS: Linux, Waiting feedback

**Comment by manioo8** [comment] 2022-12-28 23:35
For any poor soul that ends up here from a google search after having problems with the pcsx2 frame limiter not reaching above 60fps no matter the setting on steam deck, there's a built in option for limiting frames to 60 that also affects pcsx2. Before diving into more debugging, make sure to press the quick menu button while the game is running (the three dots button . . . ) and change the cap from 60 fps to off. Sorry that I'm re-opening this issue, but if that helps somebody in the future then it was worth it as this is one of the first results for this issue on the steam deck.
