### ISSUE TITLE
Midnight Club 3 Dub Edition Remix - transparant layers covering (part of) the screen

### ISSUE THREAD

**Issue by KyofuRex** [PCSX2/pcsx2#2327] opened 2018-02-27 17:44 UTC
Game: Midnight Club 3: Dub Edition Remix USA
PCSX2 version
Present since 1.5 dev build, since the opengl, d3d11 improvement. (I think)

My PCSX2 Plugin settings: GSDX: SSE4.1/AVX everything else is default. (I couldn't test it in AVX2 mode because I have Ivy Bridge CPU). 
GSDX settings: Present In d3d11/opengl hardware mode. sub settings of this isnt relevant, no matter what I change (I really tried everything), the issue is still there.

Dump file of issue: (archived in zip)
[issue.zip](https://github.com/PCSX2/pcsx2/files/1763933/issue.zip)

Description of problem:
First i want to say this is constantly present. The bottom half of the screen have some kind of lighting bug. The car headlights are invisible, sometimes it appears for less than a second and disappearing in the next leaving a burned like mark on its place. In 99% of times the main menu of the game's burned mark is visible when i start cruising.

I have some videos to demonstrate it.

https://www.youtube.com/watch?v=M6gKNCqIivA
https://www.youtube.com/watch?v=HGQc2wBamSA

Most of the times, for example when it seems the game is stressed (lots of cars, scripts or rain) the entire bottom half goes crazy, leaving transparent textures. Sometimes i have to wait minutes until it disappears, just to appear again in the next race. Interesting thing i noticed, that my car is still visible when it happens. only the surroundings affected. 
I tried to fix it by changing EE and VU in game hacks tab too. My final thoughts was the bug is the least aggressive when everything is on 0

Issue was present in 1.4.0 but the area of the effect was on the left side on the screen and much thinner.
A video: https://www.youtube.com/watch?v=h1pRdaul3dY

My PC settings:
CPU: i5 3570k
VGA: EVGA GTX 1070 FTW
RAM: Crucial Ballistix DDR3 CL8 1600Mhz
MOBO: MSI Z77 MPower
OS: Windows 10 Pro 64bit

I hope I wrote everything. This is my first issue submission.

**Comment by MrCK1** [comment] 2018-02-27 17:46
The half-screen bug is a known issue, that's what causes the issue with the headlights. If you use DX11, the CRC hack will remove them or you can play with the SW renderer.

**Comment by FlatOutPS2** [comment] 2018-02-27 17:53
The CRC hack isn't bulletproof. This is an active issue.

**Comment by yakovlev999** [comment] 2018-02-27 18:08
Thank you guys for the answers and the CRC hack tip. I give it a try. I hope it can be fixed, because other than that. the game runs flawlessy :)

**Comment by ghost-101** [comment] 2019-01-18 04:07
Issue still persists on 1.5.0-20190117095859, OpenGL HW (Linux).
Using the native PS2 resolution happened to make these overlay artifacts go away quickly after occurance, apart from the headlights always being cut off.
https://pomf.pyonpyon.moe/nsdtgb.png

**Comment by czr1210** [comment] 2019-08-30 22:40
Issue is present in the current dev build (3265-g03133bc53), however you can mitigate the problem and improve performance greatly. The game is fully playable but when there's a full overlay it is difficult to drive at high speed.

Spending hours on various configs I hope the below findings can help others to workaround this bug.

I'm running an Intel i7-4790 / Nvidia GTX 970

- Midnight Club seems _very_ susceptible to audio latency. I found this affects input lag but may also trigger the bug raised. ASIO4ALL can help, when installed I could run with much lower latency + DirectSound works better.
[https://i.imgur.com/9UV00ZF.png](url)

*Disabled audio sync greatly helps to smooth performance, with VSync set to Standard I experienced no dropouts
**Useful test - At the start of a race if the counter is laggy, I generally found this to be audio settings misconfigured (or pushing graphics too high).

- OpenGL Renderer seems less prone to causing bug. I ran with the below config: [https://i.imgur.com/oZzTVq2.png](url)

- Emulator settings set to standard, with all speed hacks but no change to Cyclerate/Skipping. This _definitely_ throws things off and can trigger full screen glitches. I found some success pushing EE settings up, but only with necessary tweaks to audio config / ASIO buffer

Some artefacts still show but mostly this is the worst seen during races:
https://i.imgur.com/kmTvdL7.jpg

**Comment by tadanokojin** [comment] 2019-12-20 20:01
After some debugging (which was hard to do) I found the cause of the issue. It is a halfscreen TS for the headlights. Actually, I wrote a fix for this but detection is bad. Here is a build where I force GSdx to run the halfscreen path:
https://youtu.be/PFvhzGqYFrc

Will need to understand full effect and research a good solution but for now I understand the problem.

**Comment by czr1210** [comment] 2019-12-22 22:29
Nice, good to see this is being looked into

**Comment by Wakadooey** [comment] 2020-07-13 12:33
@KyofuRex 
Was holding off on playing Midnight Club 3 because of headlight issue, decided to play it and mess around with settings. 
Turns out all I needed to do was set "half screen fix" to force enable. Probably would have taken longer to figure out if it weren't for @tadanokojin. Hopefully this also works for anyone who reads this. 
![image](https://user-images.githubusercontent.com/68230690/87304433-ced5ea00-c4e2-11ea-9de9-41fe28b1ca0c.png)

**Comment by czr1210** [comment] 2020-07-14 11:22
> @KyofuRex
> Was holding off on playing Midnight Club 3 because of headlight issue, decided to play it and mess around with settings.
> Turns out all I needed to do was set "half screen fix" to force enable. Probably would have taken longer to figure out if it weren't for @tadanokojin. Hopefully this also works for anyone who reads this.
> ![image](https://user-images.githubusercontent.com/68230690/87304433-ced5ea00-c4e2-11ea-9de9-41fe28b1ca0c.png)

I've started to replay this only the other day after seeing the half screen fix. Works great now! 
The game is pretty intensive and seems to have some internal lag, running @ 180% cycle rate seems to help

**Comment by Wakadooey** [comment] 2020-07-14 11:31
@czr1210 I'm glad to see you got your game running well. I get frame drops here and there, going to try increasing cycle rate, thanks for the advice!

**Comment by czr1210** [comment] 2020-07-14 22:53
> @czr1210 I'm glad to see you got your game running well. I get frame drops here and there, going to try increasing cycle rate, thanks for the advice!
> 
> Edit: This reduced the lag by a lot within races and on the race finish screens
> ![image](https://user-images.githubusercontent.com/68230690/87422335-749e5d00-c5a6-11ea-8524-144310e6ff11.png)
> Refraction over at the pcsx2 forums is a legend!

Just tried those and didn't have much joy after turning cyclerate back down. Running @ 180% has been solid though, much better speed and no stability issues.

Had some decent success using ReShade on this game. The below thread discusses issues with DX11 but RibShark's workaround works if you amend the script slightly: https://github.com/PCSX2/pcsx2/issues/2106

Below screenshots show both on and off, there's tons of parameters to mess with but it's looking a lot nicer

https://i.ibb.co/P1tJRcz/Off.png

https://i.ibb.co/ckSrGBJ/On.png

**Comment by Wakadooey** [comment] 2020-07-15 12:56
@czr1210 Whoa, I just tried that, got some pretty nice results.
Went from:
![regular](https://user-images.githubusercontent.com/68230690/87547342-f52d8e00-c678-11ea-94e6-57b7fee52d8c.png)
To:
![reshaded](https://user-images.githubusercontent.com/68230690/87547394-07a7c780-c679-11ea-9dba-a43f7f88436b.png)

Didn't even know about Reshader, thanks for letting me know. 
Midnight Club 3 is a lot more enjoyable like this!

**Comment by czr1210** [comment] 2020-07-15 20:25
> @czr1210 Whoa, I just tried that, got some pretty nice results.
> Went from:
> ![regular](https://user-images.githubusercontent.com/68230690/87547342-f52d8e00-c678-11ea-94e6-57b7fee52d8c.png)
> To:
> ![reshaded](https://user-images.githubusercontent.com/68230690/87547394-07a7c780-c679-11ea-9dba-a43f7f88436b.png)
> 
> Didn't even know about Reshader, thanks for letting me know.
> Midnight Club 3 is a lot more enjoyable like this!

Nice, looks great with the extra contrast / haze removed!

**Closed** 2022-03-12 12:28 UTC
Labels: GS, GS: Hardware
