### ISSUE TITLE
BF2 only smal part of the screen is visable hardware mode

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#2992] opened 2019-06-13 18:16 UTC
PCSX2 1.5.0-20190613145203 - compiled on Jun 13 2019

Every setting is default default speed etc.

In game on software mode the game is actually playable but if i select hardware dx 11 or opengp the screen only shows a small part.

software mod
![pcsx2 2019-06-13 22-07-25-142](https://user-images.githubusercontent.com/5770076/59457124-dd0d8e80-8e28-11e9-8644-c2460dac61e6.jpg)

hardware mod 

![pcsx2 2019-06-13 22-07-44-431](https://user-images.githubusercontent.com/5770076/59457145-ea2a7d80-8e28-11e9-87e8-e2b518e2aa71.jpg)

[emuLog.txt](https://github.com/PCSX2/pcsx2/files/3287540/emuLog.txt)

[snaps.zip](https://github.com/PCSX2/pcsx2/files/3287541/snaps.zip)

**Comment by MrCK1** [comment] 2019-06-13 18:19
Dupe of #1565

**Closed by MrCK1** 2019-06-13 18:19 UTC
