### ISSUE TITLE
[BUG]: Steambot Chronicles [SLUS-21344] | Game Textures Incorrect on Vulkan Native Res & Texture Dumps Corrupted

### ISSUE THREAD

**Issue by HarryTheTurtle** [PCSX2/pcsx2#10857] opened 2024-02-24 16:05 UTC
### Describe the Bug

When using the Vulkan renderer on native resolution the textures are displayed incorrectly. The ocean is green and a cone under each actor is displayed. The fog effect is also missing.

When dumping textures the texture are corrupted and unusable. Also when dumping textures the setting will dump gigs of data in only minutes.

### Reproduction Steps

Set the renderer to Vulkan Native resolution and start the game. This is the very first scene in the game. Please see attached pictures, savestate, and GS Dump.

### Expected Behavior

Vulkan should render the scene the same as software when in native resolution. Texture dumps are unusable.

### PCSX2 Revision

v1.7.5577

### Operating System

Windows 10

### CPU

i9-10850K CPU @ 3.60GHz

### GPU

NVIDIA GeForce RTX 3090

### GS Settings

Although the issue stated occurs on native, I did some testing and enabled some HW Hacks to see if the problem persists. The only setting that effected the issue is Disable Render Fixes but that will put an artifact in the upper left corner of the display.

Vulkan Native with Disable Render Fixes Enabled:
![Steambot Chronicles_SLUS-21344_20240224091044](https://github.com/PCSX2/pcsx2/assets/47069190/14bcfaf7-69ef-48af-833d-d8a5b6a1b602)

### Emulation Settings

All settings are [Default]

### GS Window Screenshots

Vulkan Renderer on Native:
![Steambot Chronicles_SLUS-21344_20240224090242](https://github.com/PCSX2/pcsx2/assets/47069190/696b3d60-6428-4187-a8e7-f7ccacf742ad)

Software Renderer:
![Steambot Chronicles_SLUS-21344_20240224090230](https://github.com/PCSX2/pcsx2/assets/47069190/55f899ff-f87a-4e6f-9910-4b17e2a37ce5)

Vulkan Renderer on Native:
![Steambot Chronicles_SLUS-21344_20240224090322](https://github.com/PCSX2/pcsx2/assets/47069190/a394903a-1139-4a74-a56d-2f03440a8eff)

Software Renderer:
![Steambot Chronicles_SLUS-21344_20240224090611](https://github.com/PCSX2/pcsx2/assets/47069190/ed0a005e-ed8f-421a-b000-54f8a03fab29)

------------------------------------------------------------------------------------------------------------------------------------------

Corrupted Texture Dumps:
![Screenshot (30)](https://github.com/PCSX2/pcsx2/assets/47069190/93bc9007-3531-479c-9556-376b23707000)

Corrupted Texture Dump Example:
![1bd566fee833a47d-00005dc0](https://github.com/PCSX2/pcsx2/assets/47069190/86dfd47f-70c2-47f4-b916-13005fe741c8)

### Logs & Dumps

Save State Standing in Ocean:
[SLUS-21344 (9F391882).01.p2s.zip](https://github.com/PCSX2/pcsx2/files/14393438/SLUS-21344.9F391882.01.p2s.zip)

GS Dump Single Frame from Exact Location in Save State:
[Steambot Chronicles_SLUS-21344_20240224100237.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/14393446/Steambot.Chronicles_SLUS-21344_20240224100237.gs.zst.zip)

**Comment by Mrlinkwii** [comment] 2024-02-24 16:16
re: hardware mode  issue i think the  GSC maybe broken 

re: texture dumping that's kinda expected , some games may  not dump correctly due to how a game is made

**Comment by HarryTheTurtle** [comment] 2024-02-24 16:20
> re: texture dumping that's kinda expected , some games may not dump correctly due to how a game is made

I suppose making HD Texture Packs for this game is out of the question for now. It does dump some usable textures but I'd say 3/1000 isn't a good ratio. I would settle for just upscaling it in the Vulkan Renderer but since it is broken on Native that also isn't viable at this time.

**Comment by stenzek** [comment] 2024-02-25 04:32
It's a nutty page-at-a-time interleaved channel+texture shuffle. I HLE'ed this ages ago, hoping for something that worked for all games on this engine, but it seems to be game specific.

Duplicate of #1318.

**Closed by stenzek** 2024-02-25 04:32 UTC
Labels: Bug
