### ISSUE TITLE
Merging DEV9 into core

### ISSUE THREAD

**Issue by AmFobes** [PCSX2/pcsx2#3764] opened 2020-09-28 19:01 UTC
Pinging @TheLastRar for the sake of discussion.

I also created an issue on the CLR-DEV9 repo [here](https://github.com/TheLastRar/CLR-DEV9/issues/31#issue-710503019)

**Comment by TheLastRar** [comment] 2020-09-29 09:57
To summerise the plan so far;

1. dev9drkghz will have the winPcap/Npcap dependency removed and it's TAP backend updated (https://github.com/PCSX2/pcsx2/pull/3740)
2. dev9drkghz will be merged into core, as it's code is compatable with the core codebase, while CLR_DEV9's code isn't
3. HDD support will be ported in sometime afterwards

Note that you will be unable to use CLR_DEV9 afterwards as DEV9 plugin loading will be removed when dev9grkghz is merged. 

The winsock backed will not be ported, due to its poor support for LAN games.

**Comment by GovanifY** [comment] 2020-09-29 10:32
Yup! That's in line with what I have planned

**Comment by Tellilum** [comment] 2020-09-29 13:02
There are a few communities, like the .hack//frägment community that rely on winsock due to quick and easy setup. Would it be possible to add it as a secondary option for those who actively use it?

**Comment by GovanifY** [comment] 2020-09-29 13:08
How much effort would it take to port your existing tutorials to tap? You need to install openvpn and then bridge the tap interface it automatically created. This takes about 30seconds if done correctly on windows.

**Comment by TheLastRar** [comment] 2020-09-29 13:52
To clarify, it's largely only LAN games that would need per game setup for the most part with winsock, games that talk to a central server work without issue (Except when connecting to localhost, where an extra checkbox needs to be unchecked).
TAP however would provide a more consistant experance across the two)

Regarding TAP (and I guess pcap on linux) at some point, I may try and go though dev9ghzdrk and attempt to orginise its file structure to more closely match CLR_DEV9. I'm sure there are small changes and such that I did that I never ported back (Xlink compatability changes, possibly others?) and I'll pick these up when I do this.

**Closed** 2020-10-31 16:35 UTC

**Comment by vico93** [comment] 2020-11-01 18:05
Great choice. /s

The only plugin which works for me (CLR_DEV9) can't be selected anymore because devs decided to merge an incomplete solution instead.

**Comment by refractionpcsx2** [comment] 2020-11-01 18:08
@vico93 have you used it since it was merged? it's not using the same components as the plugin was.

Anyway, we're going to work with TheLastRar to get missing functionality across, so stop your bitching.

**Comment by vico93** [comment] 2020-11-01 18:10
> @vico93 have you used it since it was merged? it's not using the same components as the plugin was.
> 
> Anyway, we're going to work with TheLastRar to get missing functionality across, so stop your bitching.

Try to interpret my statement before bitching.

The menu in newest build **doesn't work**. The adapter list is empty (i have Win10pcap installed) and the HD section says "not yet implemented".

Why merge an incomplete plugin barring choice feature-complete competitors? And i am bitching? Cmon

**Comment by AmFobes** [comment] 2020-11-01 18:15
> How much effort would it take to port your existing tutorials to tap? You need to install openvpn and then bridge the tap interface it automatically created. This takes about 30seconds if done correctly on windows.
> 
> Just so you know winsock has to be done per game and even then is not guaranteed to work, hence why we don't necessarily intend on supporting it out of the box

Please read the dicussions regarding your issues. The comment qouted above tells you what you need.

**Comment by refractionpcsx2** [comment] 2020-11-01 18:17
I did interpret your statement, your first line was sarcasm (as you willingly showed) then you complained about an "incomplete" solution, instead of nicely asking why your adapters don't show up.

You do NOT need WinPCap anymore, you need some VPN software to create the adapter, then you can use it.  TheLastRar recommends OpenVPN, here is what he said: 

> There used to be a direct link on the site that had just the needed driver, instead seems to be bundled with OpenVPN here 
> https://openvpn.net/community-downloads/, There is however this, which does provide a download for just the driver 
> https://build.openvpn.net/downloads/releases/latest/

As for the HDD, if you read what I said, we're working with the CLRDEV9 developer to get the missing functionality implemented.

Maybe in future, instead of just coming to our github to complain that the dev9 plugin doesn't work for you, you could ask for help in getting it to work? you would get a much more favourable response.

**Comment by tadanokojin** [comment] 2020-11-01 18:20
The nightlies are subject to change/break/etc anyway. So if you're expecting everything that we merge into it to be perfect right out of the gate then you just have unrealistic expectations. Stick to stable release if that is what you want or just use a version of the nightlies that supports dev9 as a plugin.

**Comment by vico93** [comment] 2020-11-01 18:23
> Maybe in future, instead of just coming to our github to complain that the dev9 plugin doesn't work for you, you could ask for help in getting it to work? you would get a much more favourable response.

The problem is: it **works** under CLR_DEV9, but after that genious change, not only it doesn't work but also users cant choose anymore.

This emulator, like PSX-based ones, are based on plugins and the choice users can have depending of their hardware.

The only explainations to take away this feature are or a desperate feature to get libretro support or the devs feel threatened by DobbieStation rising compatibility.

**Comment by tadanokojin** [comment] 2020-11-01 18:24
Wow, Ref and I are both Dobie devs lol

**Comment by refractionpcsx2** [comment] 2020-11-01 18:28
@vico93 congratulations for ignoring everything important I (and the CLRDEV9 dev) had to say. Further proves my point you're just here to complain and cause problems.

And as Kojin says, both myself and Kojin are Dobiestation developers, so we don't feel "threatened" by it. Plugins are just not a popular thing to have anymore and at this stage it's kind of pointless.  If you don't like its current state, use 1.6, development builds are a work in progress, so things will suck from time to time.
