### ISSUE TITLE
[BUG]: Gran Turismo 4 Race Start Text is Persistent

### ISSUE THREAD

**Issue by DanielBielak** [PCSX2/pcsx2#8387] opened 2023-03-13 02:51 UTC
### Describe the Bug

When in driving mode, the text "GET READY TO DRIVE" or "FULL THROTTLE" remains on the screen throughout the whole driving session or until the car is driven in reverse.

### Reproduction Steps

In Gran Turismo 4, from the home screen in Gran Turismo mode:

- Select City Courses
- Select any course
- Select Practice
- Select A-Spec=Driver's mode
- Drive

Text, "GET READY TO DRIVE" or "FULL THROTTLE"  remains on the screen indefinitely or until the car is driven in reverse.

### Expected Behavior

I expected the text "GET READY TO DRIVE" or "FULL THROTTLE" to disappear once I started driving.

### PCSX2 Revision

v1.7.4224

### Operating System

macOS 10.14 (Mojave)

### CPU

2.2 GHz Intel Core i7

### GPU

Intel Iris Pro 1536 MB

### GS Window Screenshots

<img width="1440" alt="Screen Shot 2023-03-12 at 2 54 17 PM" src="https://user-images.githubusercontent.com/101737437/224597230-97caa36f-0e41-45a6-91cf-cfe06bb3e1db.png">
<img width="1440" alt="Screen Shot 2023-03-12 at 10 26 16 PM" src="https://user-images.githubusercontent.com/101737437/224597234-28bb3924-88f6-41c9-9409-d7d6f38652d9.png">

**Comment by RedDevilus** [comment] 2023-03-13 03:07
Need to enable Tools > Advanced Settings and then:

![image](https://user-images.githubusercontent.com/24227051/224599162-66c021aa-5f47-406a-987a-e526cbbfb27e.png)

**Comment by stenzek** [comment] 2023-03-13 03:21
Known issue, full fpu breaks license tests. Duplicate of #2245.

**Closed by stenzek** 2023-03-13 03:21 UTC
Labels: Bug
