### ISSUE TITLE
[BUG]: Debugger: Spamming B key or spacebar in R5900 disassembly view adds a random R3000 breakpoint

### ISSUE THREAD

**Issue by Berylskid** [PCSX2/pcsx2#10392] opened 2023-12-12 01:34 UTC
### Describe the Bug

In R5900 disassembly view, pressing B key or spacebar adds Execute-type breakpoint for selected instruction.
But spamming those keys immediately adds a random Execute-type breakpoint to R3000 view.
And it often stops program.

### Reproduction Steps

1. Open PCSX2
2. Run a game
3. Open Debugger
4. Spam B key or spacebar in R5900 Disassembly view while game is running
5. See breakpoints tab in R3000 view

### Expected Behavior

Any inputs in R5900 view should not affect R3000 view. Vice versa.

### PCSX2 Revision

v1.7.5281

### Operating System

Windows 11

**Comment by F0bes** [comment] 2023-12-12 01:53
🥲

**Comment by Daniel-McCarthy** [comment] 2023-12-12 01:53
I'm trying to reproduce this, and haven't found this behavior. (I am on the same OS and version.) Below I have attached what I am experiencing when following these steps (no breakpoints are generated on my side for R3000 view and continues operating as expected).

Do you have any suggestions/tips for reproducing this? Are these the correct steps?
![PCSX2-ReproducingBreakpointBug1](https://github.com/PCSX2/pcsx2/assets/4957200/5dbfd204-615c-44a5-9ddd-17bc0baae672)

**Comment by Berylskid** [comment] 2023-12-12 01:59
I'm sorry, my reproduction step lacks some infos then. I'd correct it later.

How about doing it while running game?

**Comment by Daniel-McCarthy** [comment] 2023-12-12 02:04
> I'm sorry, my reproduction step lacks some infos then. I'd correct it later.
> 
> How about doing it while running game?

That did the trick, thanks! Happened as described immediately when testing while the game is running (on assembly that won't cause it to immediately pause).

**Comment by F0bes** [comment] 2023-12-14 18:54
Okay, I can reproduce it. The IOP tab is receiving key presses even though it's not active.
(No, it's not related to automatically swapping to the breaking CPUs tab, that happens after)
I'm going to have to further investigate how to mitigate this Qt (I assume) issue.

**Comment by F0bes** [comment] 2023-12-14 19:43
After some hair pulling, I figured out what the issue is. It should be resolved in #10406.

**Closed** 2023-12-15 20:35 UTC
Labels: Bug, Debugger
