### ISSUE TITLE
[UI] Speed hacks panel visually not disabled after applying settings

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#543] opened 2015-05-15 04:56 UTC
**UI Issue**:

Issue title: The Speed hacks options are visually not disabled after applying settings using the Apply option in the bottom right of the speedhacks window.

- PCSX2 version: PCSX2 1.3.1-20150508095434 - compiled on May  8 2015

- PCSX2 options: Defaults, no settings modifications affect the issue

- Plugins used: GSdx, SPU2-X, Lilypad, Linuz ISO/Gigaherz CDVD,rest null plugins

- Plugin settings: Defaults, no settings modifications affect the issue

- Description: The Speed hacks options are visually not disabled (greyed out) after applying settings using the Apply option in the bottom right of the speedhacks window. The Issue was not present in r5186, The problem was Introduced from r5196 onwards and is still present on the latest development builds.

 How to replicate: 
 1) Open the Emulation Settings window and open the Speed Hacks panel.
 2a) If unchecked, check the enable speed hacks checkbox.
 2b) Uncheck the Enable speed hacks checkbox.
 3) Click the apply button.
 4) Result as seen in the screenshot. [http://forums.pcsx2.net/attachment.php?aid=38473]

- Last known version to work: PCSX2 r5186

**Comment by avih** [comment] 2015-05-15 05:01
So what's the bug? It looks like it should to me.

In a bug report, the most important thing together with Steps To Reproduce (STR), is to say what you expected to see, and what you see instead.

In your report you have the STR and what you get at the end, but you didn't say how you think it should be instead.

And as far as I can tell, it looks the way it should, so if you think something should look differently, please describe this different thing clearly.

**Comment by avih** [comment] 2015-05-15 05:03
Sorry, I now see what you mean.

**Comment by ssakash** [comment] 2015-05-15 05:08
just for reference, The Issue was Triggered from this commit. https://code.google.com/p/pcsx2/source/detail?r=5196

**Comment by avih** [comment] 2015-05-16 16:55
I think it's possibly a `wxWidgets` bug (not necessarily, but worth a check), since while it's not grayed out, it's actually locked (i.e. you can't modify any of the values which are not grayed out), and since both graying out the locked sections and locking the individual widgets happens in one `wxWidgets` command, I think it could be `wxWidgets` itself. I.e., there appears to be a contradiction between how it looks (unlocked) and how it behaves (locked), which might be a wx bug.

Anyone on Linux with wxWidgets 3.x or @gregory38, would you be able to try the following with wxWidgets 3.x and tell me what you get?

- Make sure Presets are disabled. Close the Settings dialog if it's open.
- Open the Emulation options panel, go to the speed hacks tab.
- Enable/Check the main speed hacks checkbox, then uncheck it.
- --> result: all individual items on that panel (except the main checkbox) are grayed out and locked.
- Click Apply

Expected results: nothing should change on the panel - all the individual speed hack widgets remain grayed out and locked (cannot be modified).

Actual result on windows: the two sliders and the MTVU checkbox are grayed out and locked as expected, but the 4 remaining checkboxes are not grayed out - though they're still locked.

Is the actual result different with wx 3.x ?

**Comment by Shoegzer** [comment] 2015-05-16 17:25
I don't observe any problem following your test procedure, avih.  Options remain greyed out here.  

Tested with Linux Mint 17.1 x64, with wx-common (etc.) 3.0.0-2, and the latest 1.3.1-0 snapshot available from gregory's PPA.

**Comment by avih** [comment] 2015-05-16 17:39
Thanks @Shoegzer.

So this appears to confirm that it's a wxWidgets issue. While it's probably possible to work around this issue with some code, I think it's not worth it. The relation between the presets and the speed hacks panel is complicated already, and adding a workaround for a wxWidgets bug would be both hard and likely to start a whack-a-mole of more use cases which need handling.

Since this appears to be an external bug where a good workaround is likely not trivial, and it's not critical in any way, and while it _looks_ incorrect, it actually _behaves_ correctly, I'm declaring this as WONTFIX.

Thanks for the report though.

**Closed by avih** 2015-05-16 17:39 UTC

**Comment by avih** [comment] 2015-05-16 19:42
I gave it a go anyway - bbf7153acd1101678c208ab86c87d65d5ce11bef .

Hopefully I didn't mess up other stuff (though I think it ended up fairly safe). Thanks again for the report.

**Comment by ssakash** [comment] 2015-05-17 04:47
Awesome , Thanks for the fast fix. I'll move this to the resolved subforums on the new bug reporting system.
