### ISSUE TITLE
too much was reverted

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#745] opened 2015-08-07 09:29 UTC
The  commit 72b828ef0de764aeb35a213eb3067b7041ef19e7 did a big revert of code. But it seems that it drops a valid commit 5287de930bf34acc135e922681eb75b0ec7a87d4

It looks like a bad git command.

**Comment by mirhl** [comment] 2015-08-07 11:31
You mentioned two times the same commit

**Comment by refractionpcsx2** [comment] 2015-08-07 12:16
Yeah git hated me,  thought I'd sorted it out :(

**Comment by gregory38** [comment] 2015-08-07 12:17
You just need to revert your revert commit and add back the math.h file. Good luck ;)

**Comment by micove** [comment] 2015-08-08 20:03
This should revert the revert + add the file with 1 command. 
```
git cherry-pick 5287de9
```

I don't know if what was intended to be reverted was actually reverted or not.

**Comment by gregory38** [comment] 2015-08-09 11:21
Well the purpose was to train Ref with GIT ;) If you give it the solution, it is too easy.

**Comment by refractionpcsx2** [comment] 2015-08-09 13:15
I'd rather have a solution, I hate git,  I don't want to use it ;)

**Comment by micove** [comment] 2015-08-09 13:24
I just wanted brownie points for my PR that he is assigned to. ;)

More realistically, fixing this will break that PR for the 7th or so time therefore I want to get it over with so I can redo it again. I'm not sure how pistachioman has managed to keep fixing his PR for almost a year w/o going nuts.

**Comment by refractionpcsx2** [comment] 2015-08-09 13:53
You are welcome to fix it for me :p

**Comment by micove** [comment] 2015-08-09 14:05
There #753

**Comment by refractionpcsx2** [comment] 2015-08-09 14:35
Thanks,  merged :)

**Closed by refractionpcsx2** 2015-08-09 14:35 UTC
