### ISSUE TITLE
error when disabling pcsx2 sound

### ISSUE THREAD

**Issue by xXthecatXx** [PCSX2/pcsx2#9861] opened 2023-08-26 16:01 UTC
### Describe the Bug

https://github.com/PCSX2/pcsx2/assets/127200899/1b673384-e22d-4754-9d58-ea54b84ddae3

### Reproduction Steps

start any game in properties leave the volume to 0 both in global settings and then you can check any box inside pcsx2 and the volume will turn on again.

### PCSX2 Revision

PCSX2 Nightly - v1.7.4951

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment] 2023-08-27 03:22
I couldn't reproduce the issue when toggling a setting, but the global slider taking precedence over the per-game setting is fixed in #9864.

**Comment by xXthecatXx** [comment] 2023-08-27 04:23
thanks for solving the problem

**Closed** 2023-08-27 05:33 UTC
Labels: Bug
