### ISSUE TITLE
GitHub releases are outdated

### ISSUE THREAD

**Issue by VelocityRa** [PCSX2/pcsx2#3191] opened 2019-12-29 22:50 UTC
The latest development build in your Releases page (https://github.com/PCSX2/pcsx2/releases) is from 2016.

I was pointed to https://pcsx2.net/download/development/dev-windows.html which is the correct place to get them, but having those on GitHub is misleading, perhaps they should be removed.

**Comment by MrCK1** [comment] 2019-12-29 22:53
The tags you see on Github are "breadcrumbs" - they are there for developers to know when the start of a branch was and view commits from before/after them for regression testing. We don't have them setup to continuously log every commit under that specific tag.

Unrelated here, but also keep in mind that odd numbered builds are not considered stable releases, which is why it's not on the main page. The next stable release will be numbered 1.6.0 (which will be due out in the coming months). When that happens, you will see a new tag there on Github (in addition to our main site)

**Comment by lightningterror** [comment] 2020-02-07 20:43
1.5 release tag is the same as 1.4 release (commit wise). To me it looks like the tag was mostly added as a milestone.
It can be safely removed.

**Comment by lightningterror** [comment] 2020-02-11 09:43
I looked in to it and it looks like we label appveyor and maybe buildbot too based on latest release tag so it is intended so I will close this.

**Closed by lightningterror** 2020-02-11 09:43 UTC
Labels: Quality & Assurance

**Comment by tadanokojin** [comment] 2020-02-11 10:49
Some additional info. Apparently when a tag is created a "release" is automatically created. I use scare quotes here because they aren't really releases. Those actually appear a little differently:

![004175](https://user-images.githubusercontent.com/26046960/74230158-ceb29380-4c91-11ea-9b26-dcdd656affaf.png)

There is an open issue with Github about this and the confusion it causes on other projects:
https://github.community/t5/How-to-use-Git-and-GitHub/Tag-without-release/td-p/6255

There is apparently no way to override this functionality at this time.
