### ISSUE TITLE
Accessing Plugins Menu Causes Temporary Freeze on "Enumerating Available Plugins"

### ISSUE THREAD

**Issue by DPersonalized** [PCSX2/pcsx2#999] opened 2015-11-26 18:25 UTC
Whenever I go to the Plugins menu, PCSX2 temporarily freezes (for as long as 5 minutes at one point - I had to close PCSX2 because it never started responding again.) It appears to freeze when looking for the AVX2 GSdx plugin, but **it is there.** I'm guessing the problem is that my CPU doesn't support the AVX2 extension (it's an Athlon X4 750K and I know for a fact that it doesn't.) The freeze is completely consistent.

CPU: AMD Athlon X4 750K @ 4.1GHz
GPU: AMD Radeon HD 7770
OS: Windows 8.1 x64
RAM: 4GB DDR3

**Comment by willkuer** [comment] 2015-11-26 19:02
Temporary fix would be to remove the plugin? Can you please post the emulog after you observed the problen?

**Comment by yorkiesandskittles** [comment] 2015-11-26 19:58
Loading plugins...
	Binding   GS: C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\GSdx32-SSE4.dll 
Windows 6.3.9600
	Binding  PAD: C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\LilyPad.dll 
	Binding SPU2: C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\SPU2-X.dll 
	Binding CDVD: C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\cdvdGigaherz.dll 
	Binding  USB: C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\USBnull.dll 
	Binding   FW: C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\FWnull.dll 
	Binding DEV9: C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\DEV9null.dll 
Plugins loaded successfully.

(GameDB) 9692 games on record (loaded in 280ms)
Bios Found: Europe  v02.00(14/06/2004)  Console
Path: C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\DEV9ghzdrk.dll
File is not a valid dynamic library.
[wx] Failed to load shared library 'C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\DEV9ghzdrk.dll' (error 0: the operation completed successfully.)
Some kinda plugin failure: C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\DEV9ghzdrk.dll
Path: C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\GSdx32-AVX2.dll
File is not a valid dynamic library.
[wx] Failed to load shared library 'C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\GSdx32-AVX2.dll' (error 0: the operation completed successfully.)
Some kinda plugin failure: C:\Users\Adam\Downloads\pcsx2-v1.3.1-1478-g9f2fa79-windows-x86\plugins\GSdx32-AVX2.dll

**Comment by ssakash** [comment] 2015-11-27 12:17
I can confirm the momentary pause at plugin selector menu on my Core2Duo which doesn't support AVX instructions. I'll try to look into it If I get some time. :)

**Comment by gregory38** [comment] 2015-12-04 14:57
Is it a wx3.0 regression? Otherwise, I guess there is no progress?

**Comment by ssakash** [comment] 2015-12-04 16:27
Not really, I tested this last week. WX 2.8 also had this issue. Initially I had suspected that this momentary lag will be caused when trying to load any unsupported instruction sets / respective libraries. but that doesn't seem to be the case .... 

test case was my old core2duo which only supported SSE2, SSSE3. It didn't receive any momentary lag when enumerating the SSE4.1 version of GSDX which is still unsupported by my processor. but the issue was caused when enumerating the AVX and AVX2 version of the plugin. ( not really a big issue , it just causes a bit of delay for 8-10 seconds and resumes again.). the last time I checked this it seemed to be a issue with WX Dynamic Library functions. (I might be wrong)

@gregory38 , did you check this on Linux ? curious since you have marked it as an issue specific to Windows.

**Comment by gregory38** [comment] 2015-12-04 16:31
Linux doesn't bundle N plugins so it isn't an issue for us. Not sure of the behavior. Maybe it just doing the relocation of the lib symbols. 10s is quite slow.

**Comment by gregory38** [comment] 2015-12-04 16:32
Hum if you have a debugger maybe stop it in the middle of the lag and check where you are in the code.

**Comment by turtleli** [comment] 2015-12-04 16:45
@ssakash The AVX and AVX2 GSdx plugins are compiled with the /arch:AVX flag on Windows. It might be worth checking whether that has anything to do with it.

**Comment by ssakash** [comment] 2015-12-04 21:16
> The AVX and AVX2 GSdx plugins are compiled with the /arch:AVX flag on Windows. It might be worth checking whether that has anything to do with it.

Lag is still present when /arch:AVX flag is not set.

> Hum if you have a debugger maybe stop it in the middle of the lag and check where you are in the code.

PXThread hits an unhandled exception over here during the enumeration of the Plugin (AKA momentary lag) :  https://github.com/PCSX2/pcsx2/blob/master/plugins/GSdx/GSVector.h#L5233

related by any chance ?

**Comment by turtleli** [comment] 2015-12-04 21:57
Maybe it's attempting to initialise the AVX/AVX2 dlls, but it reaches an unknown instruction and throws an exception. Do the call stacks for any of the threads show anything useful?

**Comment by gregory38** [comment] 2015-12-05 07:49
How many exception do you have? 1 or a lots for each avx line of codes.

**Comment by turtleli** [comment] 2015-12-10 18:32
I think it really is an unsupported instruction issue. For SSE4.1, most of the GSVector4 initialisation probably uses SSE2 instructions anyway, so it won't hit unsupported instructions often. But for AVX/AVX2, all of the GSVector8 initialisation uses AVX/AVX2 instructions.

**Comment by gregory38** [comment] 2015-12-10 18:41
Yes it is also my hypothesis. And you're right 4.1 is only a few instructions. AVX/AVX2 extends all previous SSE instructions.

**Comment by gregory38** [comment] 2016-01-28 09:48
I think I have found at least one issue. Someone got a crash (illegal instruction) on linux.
There are some AVX2 code in global initializer. We need it to fix it.

This array must be moved inside the class and generated when the object is created
```
const GSVector4i GPUDrawScanlineCodeGenerator::m_test[8] =
{
	GSVector4i(0xffff0000, 0xffffffff, 0xffffffff, 0xffffffff),
	GSVector4i(0x00000000, 0xffffffff, 0xffffffff, 0xffffffff),
	GSVector4i(0x00000000, 0xffff0000, 0xffffffff, 0xffffffff),
	GSVector4i(0x00000000, 0x00000000, 0xffffffff, 0xffffffff),
	GSVector4i(0x00000000, 0x00000000, 0xffff0000, 0xffffffff),
	GSVector4i(0x00000000, 0x00000000, 0x00000000, 0xffffffff),
	GSVector4i(0x00000000, 0x00000000, 0x00000000, 0xffff0000),
	GSVector4i::zero(),
};
```

Code is for PS1. I can't test it on linux. So who want to fix it ?

**Comment by turtleli** [comment] 2016-06-21 00:03
A list of globals that can cause issues (there may be omissions).
```
GSBlock.cpp:26:const GSVector8i GSBlock::m_r16mask(0, 1, 4, 5, 2, 3, 6, 7, 8, 9, 12, 13, 10, 11, 14, 15, 0, 1, 4, 5, 2, 3, 6, 7, 8, 9, 12, 13, 10, 11, 14, 15);
GSBlock.cpp:28:const GSVector4i GSBlock::m_r16mask(0, 1, 4, 5, 2, 3, 6, 7, 8, 9, 12, 13, 10, 11, 14, 15);
GSBlock.cpp:30:const GSVector4i GSBlock::m_r8mask(0, 4, 2, 6, 8, 12, 10, 14, 1, 5, 3, 7, 9, 13, 11, 15);
GSBlock.cpp:31:const GSVector4i GSBlock::m_r4mask(0, 1, 4, 5, 8, 9, 12, 13, 2, 3, 6, 7, 10, 11, 14, 15);
GSBlock.cpp:34:const GSVector8i GSBlock::m_xxxa(0x00008000);
GSBlock.cpp:35:const GSVector8i GSBlock::m_xxbx(0x00007c00);
GSBlock.cpp:36:const GSVector8i GSBlock::m_xgxx(0x000003e0);
GSBlock.cpp:37:const GSVector8i GSBlock::m_rxxx(0x0000001f);
GSBlock.cpp:39:const GSVector4i GSBlock::m_xxxa(0x00008000);
GSBlock.cpp:40:const GSVector4i GSBlock::m_xxbx(0x00007c00);
GSBlock.cpp:41:const GSVector4i GSBlock::m_xgxx(0x000003e0);
GSBlock.cpp:42:const GSVector4i GSBlock::m_rxxx(0x0000001f);
GSBlock.cpp:45:const GSVector4i GSBlock::m_uw8hmask0(0, 0, 0, 0, 1, 1, 1, 1, 8, 8, 8, 8, 9, 9, 9, 9);
GSBlock.cpp:46:const GSVector4i GSBlock::m_uw8hmask1(2, 2, 2, 2, 3, 3, 3, 3, 10, 10, 10, 10, 11, 11, 11, 11);
GSBlock.cpp:47:const GSVector4i GSBlock::m_uw8hmask2(4, 4, 4, 4, 5, 5, 5, 5, 12, 12, 12, 12, 13, 13, 13, 13);
GSBlock.cpp:48:const GSVector4i GSBlock::m_uw8hmask3(6, 6, 6, 6, 7, 7, 7, 7, 14, 14, 14, 14, 15, 15, 15, 15);
GSClut.cpp:685:static const GSVector4i s_bm(0x00007c00);
GSClut.cpp:686:static const GSVector4i s_gm(0x000003e0);
GSClut.cpp:687:static const GSVector4i s_rm(0x0000001f);
GSDrawScanlineCodeGenerator.cpp:47:const GSVector8 GSDrawScanlineCodeGenerator::m_log2_coef[4] = 
GSDrawScanlineCodeGenerator.cpp:57:const GSVector4i GSDrawScanlineCodeGenerator::m_test[8] =
GSDrawScanlineCodeGenerator.cpp:69:const GSVector4 GSDrawScanlineCodeGenerator::m_log2_coef[4] = 
GSRendererCL.cpp:203:const GSVector4 g_pos_scale(1.0f / 16, 1.0f / 16, 1.0f, 1.0f);
GSSetupPrimCodeGenerator.cpp:27:const GSVector8 GSSetupPrimCodeGenerator::m_shift[9] =
GSSetupPrimCodeGenerator.cpp:42:const GSVector4 GSSetupPrimCodeGenerator::m_shift[5] =
GSVector.cpp:25:const GSVector4i GSVector4i::m_xff[17] = 
GSVector.cpp:46:const GSVector4i GSVector4i::m_x0f[17] =
GSVector.cpp:67:const GSVector4 GSVector4::m_ps0123(0.0f, 1.0f, 2.0f, 3.0f);
GSVector.cpp:68:const GSVector4 GSVector4::m_ps4567(4.0f, 5.0f, 6.0f, 7.0f);
GSVector.cpp:69:const GSVector4 GSVector4::m_half(0.5f);
GSVector.cpp:70:const GSVector4 GSVector4::m_one(1.0f);
GSVector.cpp:71:const GSVector4 GSVector4::m_two(2.0f);
GSVector.cpp:72:const GSVector4 GSVector4::m_four(4.0f);
GSVector.cpp:73:const GSVector4 GSVector4::m_x4b000000(_mm_castsi128_ps(_mm_set1_epi32(0x4b000000)));
GSVector.cpp:74:const GSVector4 GSVector4::m_x4f800000(_mm_castsi128_ps(_mm_set1_epi32(0x4f800000)));
GSVector.cpp:75:const GSVector4 GSVector4::m_max(FLT_MAX);
GSVector.cpp:76:const GSVector4 GSVector4::m_min(FLT_MIN);
GSVector.cpp:80:const GSVector8 GSVector8::m_half(0.5f);
GSVector.cpp:81:const GSVector8 GSVector8::m_one(1.0f);
GSVector.cpp:82:const GSVector8 GSVector8::m_x7fffffff(_mm256_castsi256_ps(_mm256_set1_epi32(0x7fffffff)));
GSVector.cpp:83:const GSVector8 GSVector8::m_x80000000(_mm256_castsi256_ps(_mm256_set1_epi32(0x80000000)));
GSVector.cpp:84:const GSVector8 GSVector8::m_x4b000000(_mm256_castsi256_ps(_mm256_set1_epi32(0x4b000000)));
GSVector.cpp:85:const GSVector8 GSVector8::m_x4f800000(_mm256_castsi256_ps(_mm256_set1_epi32(0x4f800000)));
GSVector.cpp:86:const GSVector8 GSVector8::m_max(FLT_MAX);
GSVector.cpp:87:const GSVector8 GSVector8::m_min(FLT_MIN);
GSVector.cpp:93:const GSVector8i GSVector8i::m_xff[33] = 
GSVector.cpp:130:const GSVector8i GSVector8i::m_x0f[33] =
GSVertexTrace.cpp:27:const GSVector4 GSVertexTrace::s_minmax(FLT_MAX, -FLT_MAX);
PSX/GPUDrawScanlineCodeGenerator.cpp:1013:const GSVector4i GPUDrawScanlineCodeGenerator::m_test[8] =
PSX/GPULocalMemory.cpp:26:const GSVector4i GPULocalMemory::m_xxxa(0x00008000);
PSX/GPULocalMemory.cpp:27:const GSVector4i GPULocalMemory::m_xxbx(0x00007c00);
PSX/GPULocalMemory.cpp:28:const GSVector4i GPULocalMemory::m_xgxx(0x000003e0);
PSX/GPULocalMemory.cpp:29:const GSVector4i GPULocalMemory::m_rxxx(0x0000001f);
PSX/GPUSetupPrimCodeGenerator.cpp:223:const GSVector4 GPUSetupPrimCodeGenerator::m_shift[3] =
```

**Closed** 2016-08-02 22:00 UTC
Labels: Plugin: GSdx
