### ISSUE TITLE
[BUG]: Okami - Celestial Brush of Restoring bug

### ISSUE THREAD

**Issue by VladimirVSC** [PCSX2/pcsx2#6392] opened 2022-06-10 16:54 UTC
### Describe the Bug

After using the Celestial Brush of Restoring on the key objects (River of Heavens on screenshots) the picture suddenly become too dim. The bug doesn't occure with software renderer if using it from the beginning of emulation, but switching to it after the bug occured in Vulkan or Direct3D is no use. The bug is true for both Windows and Linux versions of emulator. It is presenting in stable 1.6.0 version too.

### Reproduction Steps

Using the Celestial Brush of Restoring to repair the River of Heaven in the beginning of the game. 

### Expected Behavior

The picture after using of Celestial Brush must be as bright as on the "Normal" screenshot.

### PCSX2 Revision

v1.7.2889

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

LMDE 5

### CPU

Intel Core i5-4430 3GHz (4 cores)

### GPU

GTX 760

### GS Settings

Adapter = NVIDIA GeForce GTX 760
CaptureHeight = 480
CaptureWidth = 640
DisableDualSourceBlend = 0
DisableFramebufferFetch = 0
DumpDirectTextures = 1
DumpPaletteTextures = 1
DumpReplaceableMipmaps = 0
DumpReplaceableTextures = 0
DumpTexturesWithFMVActive = 0
GSDumpCompression = 0
HWDisableReadbacks = 0
IntegerScaling = 0
LoadTextureReplacements = 0
LoadTextureReplacementsAsync = 0
MaxAnisotropy = 0
OsdScale = 100
OsdShowCPU = 0
OsdShowFPS = 0
OsdShowGPU = 0
OsdShowGSStats = 0
OsdShowIndicators = 0
OsdShowMessages = 0
OsdShowResolution = 0
OsdShowSpeed = 0
OverrideGeometryShaders = -1
OverrideTextureBarriers = -1
PrecacheTextureReplacements = 0
Renderer = 14
ShadeBoost = 0
ShadeBoost_Brightness = 50
ShadeBoost_Contrast = 50
ShadeBoost_Saturation = 50
SkipDuplicateFrames = 0
TVShader = 1
ThreadedPresentation = 0
UseBlitSwapChain = 0
UseDebugDevice = 0
UserHacks = 0
UserHacks_AutoFlush = 0
UserHacks_CPU_FB_Conversion = 0
UserHacks_DisableDepthSupport = 0
UserHacks_DisablePartialInvalidation = 0
UserHacks_Disable_Safe_Features = 0
UserHacks_HalfPixelOffset = 0
UserHacks_Half_Bottom_Override = -1
UserHacks_SkipDraw_End = 0
UserHacks_SkipDraw_Start = 0
UserHacks_TCOffsetX = 0
UserHacks_TCOffsetY = 0
UserHacks_TextureInsideRt = 0
UserHacks_TriFilter = -1
UserHacks_WildHack = 0
UserHacks_align_sprite_X = 0
UserHacks_merge_pp_sprite = 0
UserHacks_round_sprite_offset = 0
aa1 = 1
accurate_blending_unit = 1
accurate_date = 1
autoflush_sw = 1
capture_enabled = 0
capture_out_dir = /tmp/GS_Capture
capture_threads = 4
conservative_framebuffer = 1
crc_hack_level = -1
deinterlace = 7
disable_interlace_offset = 0
disable_shader_cache = 0
dithering_ps2 = 2
dump = 0
extrathreads = 3
extrathreads_height = 4
filter = 2
fxaa = 0
linear_present = 1
mipmap = 1
mipmap_hw = -1
override_GL_ARB_shader_image_load_store = -1
override_GL_ARB_sparse_texture = -1
paltex = 0
pcrtc_offsets = 0
png_compression_level = 1
preload_frame_with_gs_data = 0
save = 0
savef = 0
savel = 5000
saven = 0
savet = 0
savez = 0
shaderfx = 0
shaderfx_conf = shaders/GS_FX_Settings.ini
shaderfx_glsl = shaders/GS.fx
texture_preloading = 0
upscale_multiplier = 1
wrap_gs_mem = 0

### Emulation Settings

[EmuCore]
CdvdVerboseReads=disabled
CdvdDumpBlocks=disabled
CdvdShareWrite=disabled
EnablePatches=enabled
EnableCheats=disabled
EnablePINE=disabled
EnableWideScreenPatches=disabled
EnableNoInterlacingPatches=disabled
EnableRecordingTools=enabled
ConsoleToStdio=disabled
HostFs=disabled
PatchBios=disabled
PatchRegion=
BackupSavestate=enabled
SavestateZstdCompression=enabled
McdEnableEjection=enabled
McdFolderAutoManage=enabled
MultitapPort0_Enabled=disabled
MultitapPort1_Enabled=disabled
GzipIsoIndexTemplate=$(f).pindex.tmp
[EmuCore/Speedhacks]
EECycleRate=0
EECycleSkip=0
fastCDVD=disabled
IntcStat=enabled
WaitLoop=enabled
vuFlagHack=enabled
vuThread=disabled
vu1Instant=enabled
[EmuCore/CPU]
FPU.DenormalsAreZero=enabled
FPU.FlushToZero=enabled
FPU.Roundmode=3
VU.DenormalsAreZero=enabled
VU.FlushToZero=enabled
VU.Roundmode=3
[EmuCore/CPU/Recompiler]
EnableEE=enabled
EnableIOP=enabled
EnableEECache=disabled
EnableVU0=enabled
EnableVU1=enabled
vuOverflow=enabled
vuExtraOverflow=disabled
vuSignOverflow=disabled
vuUnderflow=disabled
fpuOverflow=enabled
fpuExtraOverflow=disabled
fpuFullMode=disabled
StackFrameChecks=disabled
PreBlockCheckEE=disabled
PreBlockCheckIOP=disabled
[EmuCore/GS]
VsyncQueueSize=2
FrameLimitEnable=enabled
FrameSkipEnable=disabled
VsyncEnable=0
FramerateNTSC=59.94
FrameratePAL=50
FramesToDraw=2
FramesToSkip=2
[EmuCore/Gamefixes]
VuAddSubHack=disabled
FpuMulHack=disabled
FpuNegDivHack=disabled
XgKickHack=disabled
EETimingHack=disabled
SoftwareRendererFMVHack=disabled
SkipMPEGHack=disabled
OPHFlagHack=disabled
DMABusyHack=disabled
VIFFIFOHack=disabled
VIF1StallHack=disabled
GIFFIFOHack=disabled
GoemonTlbHack=disabled
IbitHack=disabled
VUSyncHack=disabled
VUOverflowHack=disabled
[EmuCore/Profiler]
Enabled=disabled
RecBlocks_EE=enabled
RecBlocks_IOP=enabled
RecBlocks_VU0=enabled
RecBlocks_VU1=enabled
[EmuCore/Debugger]
ShowDebuggerOnStart=disabled
AlignMemoryWindowStart=enabled
FontWidth=8
FontHeight=12
WindowWidth=1000
WindowHeight=728
MemoryViewBytesPerRow=16
[EmuCore/TraceLog]
Enabled=disabled
EE.bitset=0
IOP.bitset=0
[DEV9]
[DEV9/Eth]
EthEnable=disabled
EthApi=Unset
EthDevice=
EthLogDNS=disabled
InterceptDHCP=disabled
PS2IP=0.0.0.0
Mask=0.0.0.0
Gateway=0.0.0.0
DNS1=0.0.0.0
DNS2=0.0.0.0
AutoMask=enabled
AutoGateway=enabled
ModeDNS1=Auto
ModeDNS2=Auto
[DEV9/Hdd]
HddEnable=disabled
HddFile=DEV9hdd.raw
HddSizeSectors=83886080

### GS Window Screenshots

![Normal](https://user-images.githubusercontent.com/96921167/173114128-9d50350b-2e31-4363-a77f-9c7566319f6f.png)

![After using celestial brush](https://user-images.githubusercontent.com/96921167/173114140-20d1893d-5dae-4d59-95f4-8aad424228c2.png)

### Logs & Dumps

[Okami - Celestial brush bug.gs.zip](https://github.com/PCSX2/pcsx2/files/8880617/Okami.-.Celestial.brush.bug.gs.zip)

[emuLog.txt.zip](https://github.com/PCSX2/pcsx2/files/8880623/emuLog.txt.zip)

**Comment by coornio** [comment] 2022-06-10 21:07
Can't reproduce this sort of brightness loss on my end no matter what I try. It does show in the GS dump, but all that tells me is that you've done something that has carried over into the dump itself. Are you able to restart the whole sequence and grab a savestate prior to using the celestial brush to fill the river?

**Comment by VladimirVSC** [comment] 2022-06-13 14:50
> Can't reproduce this sort of brightness loss on my end no matter what I try. It does show in the GS dump, but all that tells me is that you've done something that has carried over into the dump itself. Are you able to restart the whole sequence and grab a savestate prior to using the celestial brush to fill the river?

Strange... It can't be on my side either. I didn't make anything with settings (all by default) or code. The same problem was on Windows 7. Nothing unusual was done with Windows or Linux. Video drivers are NVIDIA officials - 456.xx for Windows and 470.xx for Linux. Here is a gs dump before the bug (is that  what you meant by "savestate"?

[GS dump before and after the bug.zip] 
(https://github.com/PCSX2/pcsx2/files/8892095/GS.dump.before.and.after.the.bug.zip)
)

**Comment by VladimirVSC** [comment] 2022-06-13 15:08
> Can't reproduce this sort of brightness loss on my end no matter what I try. It does show in the GS dump, but all that tells me is that you've done something that has carried over into the dump itself. Are you able to restart the whole sequence and grab a savestate prior to using the celestial brush to fill the river?

Just in case..

[Savestate before the bug.zip](https://github.com/PCSX2/pcsx2/files/8892249/Savestate.before.the.bug.zip)
.

**Comment by coornio** [comment] 2022-06-13 17:08
Don't know what to tell you then. I wasn't able to reproduce this bug from a fresh boot of the game up to these scenes of using the Celestial Brush myself :/

**Comment by kakashi314** [comment] 2023-01-06 14:16
The issue still exists in v1.7.3859

Software hardware vulkan, it doesn't matter. it's always there

the only thing that reduces graphical corruption is setting the crc hack level to aggressive, therefore i believe it's a GS related bug.

Hardware: 
![image](https://user-images.githubusercontent.com/121500889/211028775-a529c7c5-4575-4c63-8736-72bd8831fcce.png)
Software:
![image](https://user-images.githubusercontent.com/121500889/211028815-c3d2ff99-e3c1-47e5-874c-487a451757f8.png)
Hardware with crc set to aggressive:
![image](https://user-images.githubusercontent.com/121500889/211028917-3330c658-16d8-4966-b236-0e8c66b50185.png)
Gs dump:
https://anonfiles.com/Ve0cweQaye/Okami_SLUS-21115_20230106171159.gs_zst

**Comment by Mrlinkwii** [comment] 2023-01-06 14:21
[Okami_.zip](https://github.com/PCSX2/pcsx2/files/10360696/Okami_.zip)
incase link get deleted

**Comment by kakashi314** [comment] 2023-01-07 13:25
After looking more into it. i have no reason to believe it's a GS bug. will try and see what's causing it

**Comment by kakashi314** [comment] 2023-01-07 13:40
VU0 regs during the bug:
![untitled](https://user-images.githubusercontent.com/121500889/211153615-fa8275ae-01cc-400c-bdc4-f3f27bfd79a9.PNG)
VU0 regs before the bug:
![untitled](https://user-images.githubusercontent.com/121500889/211153633-00a4206b-6bac-4d91-b09b-15bc3daf8cb0.PNG)

**Comment by kakashi314** [comment] 2023-01-07 14:10
Doesn't exist in 1.4.0. will try and see which version is responsible

**Comment by kakashi314** [comment] 2023-01-07 15:33
Are there any versions previous than v1.5.1899 but newer than v1.5.1894

Because #1804 being the cause doesn't make sense to me

**Comment by Mrlinkwii** [comment] 2023-01-07 16:07
@kakashi314 https://github.com/PCSX2/archive/blob/master/RELEASES-1.5.md try that

**Comment by kakashi314** [comment] 2023-01-07 16:09
> @kakashi314 https://github.com/PCSX2/archive/blob/master/RELEASES-1.5.md try that

this one's even better https://web.archive.org/web/20170324200142/http://buildbot.orphis.net/pcsx2/index.php?m=fulllist

**Comment by kakashi314** [comment] 2023-01-07 16:12
Changes between these versions:
#1808
#1821
This one is unrelated:
#1835

**Comment by kakashi314** [comment] 2023-01-07 16:24
I think i found the one that's behind this bug:
#1808

**Comment by kakashi314** [comment] 2023-01-07 20:45
But this bug affect every renderer

**Comment by kakashi314** [comment] 2023-01-07 20:46
Switching to software doesn't fix it though .

**Comment by RedDevilus** [comment] 2023-01-07 20:52
Refraction is just clarifying that what you linked is not the breaking commit(s).

**Comment by kakashi314** [comment] 2023-01-07 21:00
> Refraction is just clarifying that what you linked is not the breaking commit(s).

Well, it's one of these. i'll just link all of them
https://github.com/PCSX2/pcsx2/commit/500d2e076db1b7d7d526008250b8244e84d0ef0f
https://github.com/PCSX2/pcsx2/commit/17b33afd64cc3ff95921fba5856db46bd68b8fda
https://github.com/PCSX2/pcsx2/commit/319b3dabdf67b1d1ee273ce4dcf79d60705a2ad3
https://github.com/PCSX2/pcsx2/commit/ff89619b09e7db4a87da1739cc02e054099e5828

**Comment by refractionpcsx2** [comment] 2023-01-07 21:28
The only thing I can see which may have mattered, is the default CRC level changed.

**Comment by kakashi314** [comment] 2023-01-07 21:45
Adding my save since the original poster didn't give his. and any dev wishing to replicate it is gonna have to watch very long fmvs.
[SLUS-21115 OKAMI 30 0_00_00 _ (A49B6AF8).zip](https://github.com/PCSX2/pcsx2/files/10367241/SLUS-21115.OKAMI.30.0_00_00._.A49B6AF8.zip)

**Comment by refractionpcsx2** [comment] 2023-01-07 22:21
I'm just trying this and the first thing I can see that you pointed out was the brush in the stars, but it looks fine to me?

**Comment by kakashi314** [comment] 2023-01-07 22:24
I meant that they were fixed in starting in 1.899

**Comment by refractionpcsx2** [comment] 2023-01-07 22:44
okay so is this is Issue completely fixed then? 

I'm just a bit confused with what the conversation is here and all the linking to commits, posting pictures of the game rendering wrong, then posting a save game to the bug point.

**Comment by kakashi314** [comment] 2023-01-07 22:46
> okay so is this is Issue completely fixed then?
> 
> I'm just a bit confused with what the conversation is here and all the linking to commits, posting pictures of the game rendering wrong, then posting a save game to the bug point.

that was to assist the devs in knowing what was fixed in the pr

**Comment by kakashi314** [comment] 2023-01-07 23:16
The pictures were added to show what v1.5.1899 Fixed in this game.

As for the memory card. i added it because it's related to #6392 . as the river is 3 mins away from the save.

sorry for any confusion :) it's all on me

**Comment by Buzzardsoul** [comment] 2023-03-29 14:04
Ok, this may sound weird, but it seems that this was fixed by #8142

**Comment by refractionpcsx2** [comment] 2023-03-29 14:06
Is that including the brightness bug?

**Comment by Buzzardsoul** [comment] 2023-03-29 14:08
> Is that including the brightness bug?

The bug that I am referring to is in @VladimirVSC 's GS Window Screenshots in his post.

**Comment by refractionpcsx2** [comment] 2023-03-29 14:17
So yes then? :P

**Comment by Buzzardsoul** [comment] 2023-03-29 14:38
> So yes then? :P

Yes, the bug where the image loses its brightness right after the river is repaired is fixed.

**Comment by refractionpcsx2** [comment] 2023-03-29 14:39
awesome, thanks! I'll close this then unless it crops up again, then we can reopen.

**Closed by refractionpcsx2** 2023-03-29 14:39 UTC
Labels: Bug, GS: Hardware, Regression
