### ISSUE TITLE
[BUG]: Lighting Bug in Beyond Good and Evil

### ISSUE THREAD

**Issue by Zulthar** [PCSX2/pcsx2#11675] opened 2024-08-06 17:46 UTC
### Describe the Bug

The the shadows coming from characters are erratic, and flashing

### Reproduction Steps

go into an outside area in Beyond Good and Evil, I use the recommended settings

### Expected Behavior

For the lighting to be generally static with a few dynamic shadows coming from characters

### PCSX2 Revision

v2.1.68

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Mint

### CPU

AMD Ryzen 5 3600 6-Core Processor

### GPU

GeForce GTX 1650

### GS Window Screenshots

![Beyond Good and Evil_SLUS-20763_20240806103722](https://github.com/user-attachments/assets/f4790d04-d47c-48b7-b6a8-60b8caa031ad)

### Logs & Dumps

[beyond good and evil_shadows.zip](https://github.com/user-attachments/files/16513951/beyond.good.and.evil_shadows.zip)

**Comment by lightningterror** [comment] 2024-08-06 17:48
Duplicate of https://github.com/PCSX2/pcsx2/issues/1986

**Closed by lightningterror** 2024-08-06 17:48 UTC
Labels: Bug
