### ISSUE TITLE
Ace Combat 5 Invincible Enemy Issue

### ISSUE THREAD

**Issue by jupiterbjy** [PCSX2/pcsx2#1842] opened 2017-02-26 13:58 UTC
***PCSX2 version:***
``1.5.1902``

***PCSX2 options:***
``None``

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset along with MTVU speed hack disabled. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``All default``

- **Note**: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``Ace Combat 5 - Unable to Kill enemy Nimrods and Freights in Mission 3 after cut-scene. Lost all memcard data after this update, so I'm starting 100 hours save file from ash. Thanks for that.``

***How to reproduce the issue:***
``Bios-USA 2.20 / Ace Combat 5 / Normal / Mission 3. Deal all incoming planes and skip cut-scene,``

***Last known version to work:***
``PCSX2 1.5.1744/1899 works great with little graphical glitches.``

***PC specifications:***
``Win10 64bit i5-3570 GTX960 OC 16GB ram``

**Comment by FlatOutPS2** [comment] 2017-02-26 14:12
As you describe it doesn't have the issue with dev-1899 this has to be a regression caused by https://github.com/PCSX2/pcsx2/pull/1835

**Comment by volodymyrkutsenko** [comment] 2017-02-27 01:23
Sorry to hear about your memcard.
I suppose you're talking about the Mission 3 where you have to protect the Kestrel carrier. Unfortunately, I cannot reproduce the issue as all the enemies are killable after the cut-scene including Nimrods for me.
In any case I don't think the game could have a regression caused by the mentioned PR because the game never uses CFC2 for reading the TPC register. It must have been something else.

**Comment by mirh** [comment] 2017-02-27 12:47
Do you have automatic fixes enabled?
Because that was the behaviour before sudonim brought 35da3319dfb3f82f12135e9956b186a5f6f3e385

**Comment by jupiterbjy** [comment] 2017-02-27 13:18
Automatic fix? Is that kind of speedhack?

And one more, compared to 1744 version, game is very laggy. Same configure with this: https://youtu.be/7ayr1W6RIa8 gives me only 70% speed.

I'll try clean install at march 1st and see if problem is still happening. Thanks for replies!

**Comment by FlatOutPS2** [comment] 2017-02-27 13:42
> Automatic fix? Is that kind of speedhack?

No, it's automatic gamefixes(it includes a hack for Ace Combat 5). You can enable or disable it on the System tab of PCSX2.
If Preset is enabled in Config > Emulation Settings, Automatic Gamefixes is always enabled.

**Comment by jupiterbjy** [comment] 2017-02-27 15:03
Since I never touch emulation settings, It won't be a problem. I wonder if this serious perfomance drop and invincible bug has something to do. I can't use computer currently, can't check it. I kept OpenGL with Blending unit acc. as high, and possible to use 200% turbo mode. but currently just 70% even in main menu..

**Comment by mirh** [comment] 2017-02-27 19:38
Ace combat doesn't require anything special. 
You can disable accurate date, blending and I think CRC hacks too. 

I currently can't check either, otherwise I'd try newest builds.

**Comment by jupiterbjy** [comment] 2017-02-28 09:39
Well, It CRC hack's half pixel offset/round sprite fixes texture issues, and blending unit accuracy fix missle's gradation. And OpenGL fixes lost shadow, engine heat effect, Hrimpaxi burst missle.

**Comment by mirh** [comment] 2017-02-28 10:39
Mhh.. I had never noticed last 4 things. 
But half pixel offset is the [wrong](https://www.reddit.com/r/emulation/comments/56wj30/mipmapping_makes_the_ace_combat_games_run_way/d8osrry/) hack though.

**Comment by jupiterbjy** [comment] 2017-03-01 04:55
how do you play then? exhaust heat effect never appears on direct X, nor shadow and lens flare..
but half pixel do fix separated plane sprite back into one in direct X. 
After half pixel offset: http://imgur.com/tvsdIvf
Before: http://imgur.com/Qpp9WOM
Direct X hanger: http://imgur.com/gzbb1BH
OpenGL hanger: http://imgur.com/CNJvDOC

**Comment by jupiterbjy** [comment] 2017-03-01 06:28
Checked. Invincible enemies are fixed on lastest revision 1909 But not seeing Ace pilot at mission 1, even after killing all 12 planes solo. was 1909 a revert?

**Comment by mirh** [comment] 2017-03-01 08:14
> Before

Half-pixel hack is an old "brute force" hack. I'm not saying that it might not help but afaik it presents issues here or there. 
The actual proper one [is](http://forums.pcsx2.net/Thread-Align-sprite-doesn-t-work-in-latest-PCSX2?page=3#pid536980)

```
UserHacks_round_sprite_offset=2
Userhacks_align_sprite_X=1
UserHacks_unscale_point_line=1
```
>  Direct X hanger

Wtf? I don't remember a similar mess since.. 2013 I guess?

When I get home I'll really have to check.

**Comment by FlatOutPS2** [comment] 2017-03-01 10:55
> Wtf? I don't remember a similar mess since.. 2013 I guess?

The hanger issue is due to the lack of hardware depth in DX, so you must not have played the game in Hardware mode between 2013 and 2015(when hardware depth was introduced for OGL). :P

> Checked. Invincible enemies are fixed on lastest revision 1909 But not seeing Ace pilot at mission 1, even after killing all 12 planes solo. was 1909 a revert?

No change has been made that should be able to alter the issue. It must've been something on your side.

**Comment by jupiterbjy** [comment] 2017-03-01 21:48
I see.. no changes, huh. Actually I fresh started game in 1744 and transfered to 1909, I'll check if new game in 1901/1909 still cause problem or not.

And about round sprite, is 2 means half or full?
Setting it full makes missle trail less gradiant, and those settings had no effect on my side last time.. I'll try it anyway, thanks for that ;)

**Comment by mirh** [comment] 2017-03-01 22:52
Ok so..... I had never noticed that thing in the hangar.. Because I had never starred at planes there in the first place. Depth emulation is indeed it. 

Then, when in-game, other shortcomings of DX seem to be the scaling of some lines in both radar and menu map, and the odd shadowing on the plane/engine (related to #1547 perhaps?). But then it seems to actually **beat** opengl by not making "green" the radar zone. 

Blending unit accuracy set from high onward also slightly change the right bottom of the screen
http://www5.zippyshare.com/v/0ra4VNzL/file.html

Last but not least, in anything but software mode, half of the clouds are missing and "squadron commands d-pad" is amiss. 

> And about round sprite, is 2 means half or full?

You should notice I provided plenty of links to further read. 

Also, I wouldn't know where to look for lens flare or "shadows". After burner can be seen fiy.

**Comment by jupiterbjy** [comment] 2017-03-02 09:50
Well, I can confirm you that there  indeed a layer of shadow not seen in direct X, and heat induced light refraction effect is rarely seen in direct X. I'll make comparsion video at sunday. And about green zone of radar, you mean border of map in 5 or ECM of zero? I get both shown in Opengl..

And one thing I want to tell you guys is, I'm really not trying to be offensive. My mothertougue is not english, so I'm not pretty good at expressing my thoughts, sorry about that;;

**Comment by FlatOutPS2** [comment] 2017-03-02 12:26
You can tell the shadows are missing in DX by watching the shadow of the body of the plane on the wings, it's missing in DX Harware, but it is there in Software mode and OGL Hardware. This again is due to the lack of hardware depth.

You can see the smoke effect of the engines in DX, but the heat effect is missing/very faint. This is due the lack of blending unit accuracy(needs basic on OGL).

**Comment by mirh** [comment] 2017-03-02 13:30
Links are blue and underlined even in Swahili 💋 
Anyway, np

> And about green zone of radar, you mean border of map in 5 or ECM of zero?

I mean the actual radar is green instead of transparent. 

....

...

Jesus christ amd?

**Comment by gregory38** [comment] 2017-03-02 15:27
Note that due to missing depth emulation, DX will skip some draw calls. Obviously it will miss some effects. Less obvious it can (sometimes) also fix effects.

**Comment by FlatOutPS2** [comment] 2017-03-02 15:34
I've never noticed the radar issue @mirh mentioned, so it might be a driver bug issue in OGL rather than something that is fixed in DX.

**Comment by gregory38** [comment] 2017-03-02 15:38
gsdump are often interesting to compare the rendering in 2 different drivers ;) If it is AMD again, and it could be, I don't know what to do....

**Comment by mirh** [comment] 2017-03-02 23:43
So.. radar is fine in ogl in nov1 build.. Tomorrow I'll try to dissect. 

In other news gregory, there seems to be an UI misalignment problem and missing clouds in OGL hw for you to check.

**Comment by FlatOutPS2** [comment] 2017-03-03 00:17
The UI misalignment problem is another I can't reproduce.

The two main problems in this game(which also affect the other AC games) are the missing clouds and the sun shining through solid objects in Hardware mode.

**Comment by jupiterbjy** [comment] 2017-03-03 09:49
Hmm, about soild object, you mean plane or terrain? At least terrain is out of that problem, shown in 'Final Option'.
And, about missaligned UI, again, check my video, from 4:00
https://youtu.be/7ayr1W6RIa8

And mirh, watch that from 4:30, see heat effect from jet without afterburner. That effect is the only reason I moved into openGL, at cost of performance ;)

**Comment by FlatOutPS2** [comment] 2017-03-03 10:13
> Hmm, about soild object, you mean plane or terrain? At least terrain is out of that problem, shown in 'Final Option'.

Plane. It affects both third person and cockpit view.

> And, about missaligned UI, again, check my video, from 4:00

That's a different issue. You just didn't enable the HW hacks @mirh suggested earlier, which would've fixed the UI issues visible in the video.

**Comment by jupiterbjy** [comment] 2017-03-03 13:28
Still, I cannot use my pc due to daily routine. Therefore, that video is not updated. I'll test right away tomorrow, 7 p.m. GMT +9

And one more thing I want to ask: half pixel offset do fix fogs misalignned in mission like 'LIT FUSE', but cause so many issues, especially trees. I've tried for 3 hours to replace it, but no luck. Is there any recommended settings for that?

**Comment by mirh** [comment] 2017-03-03 21:41
You should learn to distinguish between upscaling issue, which are a thing, and renderer bugs. It's just confusing otherwise. 

Said this... It seems like I was getting green radar.. Due to me loading from a savestate?
Does it even make sense?

**Comment by jupiterbjy** [comment] 2017-03-04 09:51
Well, sorry for confusing you. You know, I lack knowledge, just signed up github for bug report ;)
About green radar, I also had green border in DX too,. And disappears if I apply hacks. Isn't it normal?

**Comment by jupiterbjy** [comment] 2017-03-04 11:47
Checked all versions, cannot reproduce invincible bug. Tried 3 versions but no effect. Shall we close thread or change topic?

Btw, round sprite full fixed sprite issue(fog), which I never succeed in DX mode. Seems like Unscale Point line is not needed.. I'll check Hrimpaxi if it's burst missle is fixed. Both Zero and 5 had same issue on that.

**Comment by mirh** [comment] 2017-03-04 12:24
> Well, sorry for confusing you. You know, I lack knowledge, just signed up github for bug report ;)

Yes, but notice that even NOW in the last post you continued to talk about sprites hacks like normal. 
They (including unscale) are only needed for upscaling, and you never ever specified that nevertheless. 

...anyway, TL;DR bugs we might still keep this bug report: 
* D3D depth emulation (even though a meta-issue also covering cases like #1685 could be better)
* missing clouds
* objects are transparent to the sun?
* my wtf issue with the save-state bringing-in broken graphics (which also reproduces in gs dump)
* the tiny misalignment I noticed in the squadron d-pad (but this could have something to do with above)
* your whatever problem with burst missiles (which I had never noticed too tbh) provided it's not about non-native res

**Comment by FlatOutPS2** [comment] 2017-03-04 13:07
This issue can be closed soon as far as I'm concerned. Another issue can be opened for Hardware mode issues (clouds and sun issues). The depth emulation doesn't need an issue, it's just a lack of hardware depth in D3D. We know it isn't there. If we open new issues for every game that needs an option which is available in OGL and not in D3D, we'd have several hundred more open issues. If it wasn't for the OGL performance issues with AMD GPU's, no one would care anyway.

Does the save state issue also happen when you create a new save state or was just a one-time fluke(did you make the savestate with an older PCSX2/GSdx version)?

**Comment by jupiterbjy** [comment] 2017-03-04 13:12
I'm not getting savestate issue. But moving savestates of 18XX on 1902 did broke it.
And, I got issue for Round Sprite=Full, which makes effect(Afterburner, Shadow) misaligned at center.
I'm currently uploading video for demonstration

**Comment by jupiterbjy** [comment] 2017-03-04 14:04
https://youtu.be/DL_tSblFtgA?t=600
check this out, sinematics and engine exhaust is splited. Take a look from 10:00 for just 1 min.
And you will see half pixel offset fix engine exhaust in 10:55

Btw, really thanks you guys for helping me out, although we didn't fix nor found cause of main issue, I think I've learned many parts of PCSX2, and limit of each rendering options ;)

**Comment by mirh** [comment] 2017-03-04 16:44
For the love of everything lovable (and for the.. like third time?), can you first try on NATIVE resolution?
Said this, I have never seen the game all that broken, if you ask me. 
~~And indeed, I guess part of the problem is because you hadn't sprit~~ I must be writing posts on drugs or something. First of all, I had totally forgot about `UserHacks_merge_pp_sprite=1`. 
Secondly, just now I realize **half-pixel** *offset* is not the same of **wild arms** *offset*. 

And my goodness the clarity this brings on. Thank you so much. 
To sum-up my best recommended settings now
```
UserHacks_round_sprite_offset=2
Userhacks_align_sprite_X=1
UserHacks_merge_pp_sprite=1
UserHacks_unscale_point_line=1
UserHacks_HalfPixelOffset=3
```
In other news, your gsdx looks strange. Mine is like [this](https://cloud.githubusercontent.com/assets/9366725/23580386/2bcbe84e-0101-11e7-937d-a853b514aa5a.PNG). 

> If we open new issues for every game that needs an option which is available in OGL and not in D3D, we'd have several hundred more open issues. 

Then let's open a meta-meta issues for all features missing in d3d 😛 

> If it wasn't for the OGL performance issues with AMD GPU's, no one would care anyway.

Oh right, lol, sometimes my mind is off the world. 
..
Albeit, if it's between API's capabilities.. I mean, why not*?
*[have at least an issue for tracking what's missing]
And besides, older intel/amd users are pretty much condemned too. 

> Does the save state issue also happen when you create a new save state or was just a one-time fluke(did you make the savestate with an older PCSX2/GSdx version)?

I was almost going to tell you it's a one-time fluke. But then I had this problem even in another one (albeit I still cannot figure out what's the trigger).

**Comment by FlatOutPS2** [comment] 2017-03-04 17:32
> have at least an issue for tracking what's missing

I know what's missing, and I also know that list might significantly reduce soon, so let's wait a while.
We could also consider opening a feature request issue for a multi-threaded OpenGL Hardware renderer. :P

> I was almost going to tell you it's a one-time fluke. But then I had this problem even in another one (albeit I still cannot figure out what's the trigger).
And it was made with same pcsx2 version, yes.

I'll try to reproduce it.

> EDIT: I was also thinking that the COP2 patches for AC5 and zero were just made for the NTSC-U and PAL-E releases. Perhaps japanese ones are still bugged? Shouldn't we point that out somehow?

Many patches don't have a NTSC-J equivalent. It might be a good a idea of to make an issue with a collection of all gameindex patches. That makes it easier to track which versions have the patches and might help with eventually resolving the issues they solve too.

**Comment by mirh** [comment] 2017-03-04 18:53
> I know what's missing, and I also know that list might significantly reduce soon, so let's wait a while.

Uh, looking forward to it then. For as much, I hope you realize that of course nobody outside you and 2-3 people really knows that list 😝 

>  We could also consider opening a feature request issue for a multi-threaded OpenGL Hardware renderer. :P

Developer might want to attempt to our lives. 

> I'll try to reproduce it.

I can attach them if you want. 

> Many patches don't have a NTSC-J equivalent. It might be a good a idea to make an issue with a collection of all gameindex patches.

I was actually thinking more \*bigger\*. 
For example: if it wasn't for me [providing the log to sudonim] back then, I'm not sure how much time PAL versions could have stayed unfixed. 
Of course you can't tell user to get the game into another game region.. But if they are actually affected, why not telling them to come back to us because the issue is trivial and the fix is stupid but we need them?

Some method to link/merge similar games in GameIndex.dbf would be required though. 
In turn this made me remember we had a quite long debate over reforming regions in #825.

**Comment by jupiterbjy** [comment] 2017-03-05 08:16
Wow, mirh, your settings are quite different, is that same 1909?
and, can you check if half-sprite=3 cause tree glitch? Since I dont have that option..

**Comment by mirh** [comment] 2017-03-05 10:59
>  I was using AVX 1, thanks

AVX 1 is no more since some weeks. What have your hands on?

> just add this line in inis?

Yes. Trees seem ok then.

**Comment by jupiterbjy** [comment] 2017-03-08 07:03
https://youtu.be/lFR2gHaBRt4
Check around 11:20, this is the last problem I'm currently facing. Resolution is 3x native.
Any recommendation for this?

**Comment by mirh** [comment] 2017-03-08 18:50
If you can share a [gs dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) I could take a look (unfortunately I have controller unavailable to reach there). 

Besides, you still haven't explained where that AVX1 comes from.

**Comment by jupiterbjy** [comment] 2017-03-09 09:21
I'll try, so you get clean burst missle explosion, right?
I'll make dump at..saturday. And about AVX1, It's date was around 2016/12/26, which means it's from dev ver 1744. I just perfomed overwriting.

**Comment by mirh** [comment] 2017-03-09 10:37
Lol, then. 
@anybodyelse do you think printing build/rev version/date in emulog might help to avoid this kind of problems?
Or do you think the "hassle" is not worth the (*ideally*) one-time-only benefit?

**Comment by FlatOutPS2** [comment] 2017-03-09 10:49
> @anybodyelse do you think printing build/rev version/date in emulog might help to avoid this kind of problems?

We could get rid of the full path of a plugin and add the plugin revision date intead.

**Comment by jupiterbjy** [comment] 2017-03-09 14:03
So AVX1 is updated to AVX2 and I was using it after year changed.. lol
I'll dump right away at saterday, around 8~9PM. I have to clear game again, since my memcard is gonner ;)
Currently paused from mission 21. Man, I hate 8492.

**Comment by mirh** [comment] 2017-03-12 12:52
Try setting `UserHacks_SpriteHack` to 0 or 2. I found half creates like bubbles in supersonic shock waves.

**Comment by jupiterbjy** [comment] 2017-03-12 15:20
I was doing MMD port into gmod, and did lots of retry at 23 24 25, so I couldn't reach end in time, couldn't make dump. Sorry for that..

And, I've seen shockwave a little bit acting similar with burst missle too, I'll try that setting next sunday, thanks!

**Comment by oldmud0** [comment] 2017-03-13 22:09
I read through the posts and could not find a resolution that had to do with the original issue (invincible enemies). Are you sure this is a regression? I do remember this issue was in 1.2.1-r5875 - it was very well documented and there were some attempts to fix but don't have links right now.

**Comment by mirh** [comment] 2017-03-13 22:27
I mentioned that in third comment. 
Now the whole thread is a dump on: 
* whatever upscaling issue we'll be able to identify in @jupiterbjy wanderings
* sun/clouds problems
* my crazy ogl affair

TODO (but in other tickets): 
* think about that GameIndex.dbf revamp
* remember FlatOut to implement his idea :*

Good night

**Comment by sudonim1** [comment] 2017-03-14 12:31
This has become a bit of a mess of different issues, hasn't it? I'll quickly explain what the invincible enemies fixing patch is about.

The game uses VU macro code which expects reads flags while instructions are in the pipeline which will write new flags.  Full pipeline emulation for VU macro code is even more complicated than for VU micro code and we aren't even close to being able to do that, so the patch and several like it for other games reorder the instructions to implement the same logic without pipeline emulation.

**Comment by sudonim1** [comment] 2017-03-14 12:32
re. why VU macro code pipeline emulation is so hard, it means emulating the full superscalar R5900 pipeline correctly.  I'm interested in doing this at some point for single blocks, but we'll never have correct R5900 pipeline emulation in the recompiler across branches.

**Comment by jupiterbjy** [comment] 2017-03-14 15:09
I see, so what we see from PCSX2 is actually mostly patched onto games itself, instead of emulating Emotion engine perfectly. Then I got that bug because PCSX2 did not patched game at that momment? PCSX2 was somewhat acting weird as I overwrite 1901 it on 18XX, even saying translation is not available yet.

**Comment by mirh** [comment] 2017-03-14 17:42
As I said, it might have been as well you had automatic gamefixes disabled. 

Anyway, yes I know this is a bit of a messy ticket, but we are trying to confirm problems in the first place. I got defined #1860. 
For the reminders, I don't think to be the best one to lead the way.

**Comment by jupiterbjy** [comment] 2017-03-15 09:15
Hardware hack section was completely greyed out and every settings, translations, memcard was not loaded in process, so I guess PCSX2 was gone mad that that point.

Although it's too late, I just remebered one thing:
When I experienced invincible bug and signed up github for report, I found that if I use that savestate on other versions, like 1744, it also acted same way. Can savestate or memcard cause issue to emulation like this?

**Comment by mirh** [comment] 2017-03-15 09:42
Gamefixes (or at least these COP2 patches specifically) are "carried" by savestates (which afaik you should think as "full RAM images"). So, yes. 
Memory cards have nothing to do with this then.

**Comment by FlatOutPS2** [comment] 2017-03-16 23:18
Let's close this issue, and move the other unconfirmed issues to a new issue once they've been confirmed/reproduced.

**Closed** 2017-03-16 23:18 UTC
Labels: Invalid

**Comment by mirh** [comment] 2017-03-17 00:04
Is there some "issues closing rage" these days?
I mean, OP might not be the fastest one, but this thing about sprites didn't seem stale. 

Besides, there's nothing else to confirm in my last two exoteric points for *somebody* to open a ticket. 😝

**Comment by FlatOutPS2** [comment] 2017-03-17 00:18
> Is there some "issues closing rage" these days?

Don't worry, this one is also invalid for Direct3D. ;)

**Comment by mirh** [comment] 2017-03-17 00:28
I only talked about d3d when that could be and was an improvement over ogl?
If any, it's stupid that readers had to guess we were always talking about an upscaled scenario, but still.

**Comment by jupiterbjy** [comment] 2017-03-17 14:16
Finally closed, sorry for giving you guys troubles haha;;
So the main issue is gone in vane, but causing no problem. I'm glad issue ended just on me ;)

mirh, thanks for all your settings, and for FlatOutPS2, thanks for letting me know about what's on basis of DX11 renderer's problems. I never expected 'forum' could be this friendly and helpful, compared to RPI forums :)

**Comment by mirh** [comment] 2017-03-17 16:37
> So the main issue is gone in vane, but causing no problem

Oh right lol, the whole thing started from this. 

> I never expected 'forum' could be this friendly and helpful, compared to RPI forums :)

Tbh issues tracker isn't really supposed to be one, but whatever.

**Comment by mirh** [comment] 2017-03-24 20:41
> Edit: Currently userhacks_spritehack is 0, wonder if 2 fixes it. I'll test it tomorrow

👀

**Comment by jupiterbjy** [comment] 2017-03-25 00:58
https://youtu.be/oVsFwKAy8Mw
Sprite 2 fixed SOLG and shockwave, but couldn't test Hrimpaxi yet, sorry.

By the way, widescreen hack seems to extend view of game, pretty cool

**Comment by jupiterbjy** [comment] 2017-03-25 11:58
No good, it didn't fix burst missile.
I somehow managed to fix it other days, in Zero, but that miracle is not happening again.

https://youtu.be/qAVOr0D_xJU

**Comment by mirh** [comment] 2017-03-25 12:55
Savestate plauce?

**Comment by FlatOutPS2** [comment] 2017-03-25 15:17
Enable the "Auto Flush" hack. That will resolve the square borders issue. It is still missing some of the extra/smoke effects of the blast visible in Software mode though

**Comment by jupiterbjy** [comment] 2017-03-26 02:55
Well, but nearly got it with OGL, with higher Resolution. I'm so happy of that ;)
And, result: http://imgur.com/l5ulX7p
Nearly fixed, thanks!

Seems like now Align Sprite is making issue here, since it's pretty clean if I disable it.
http://imgur.com/yaPmhwW

**Comment by FlatOutPS2** [comment] 2017-03-26 06:53
I didn't have Align Sprite enabled. I just used `merge_pp_sprite` to remove the vertical lines.

**Comment by jupiterbjy** [comment] 2017-04-08 15:55
Pretty late for commenting, merge_pp_sprite only seems to fix in-game vertical lines, not ones on menu screen and plane selection, same goes for burst missile broke again. This happened after disabling Widescreen patch. Any recommendations?

**Comment by jupiterbjy** [comment] 2017-04-08 16:14
Current settings:
https://i.gyazo.com/453ded9b42becc2ccfa9151ad470eea1.png
I don't think there's something to do with WS patch, while it seems to increase performance request a lot..

**Comment by mirh** [comment] 2017-04-08 16:15
`Align sprite`, `round sprite` and `sprite` are 3 different hacks. 
Flatout lovely noted merge_pp can replace the first one. 

I don't know why you posted a screen that misses where most of the juicy stuff happens.

**Comment by jupiterbjy** [comment] 2017-04-09 07:25
I know they are all different, and I lost savestate of Hrimpaxi so I couldn't get burst missle. But since it's showing same as before, I thought I don't need it. And, that image I posted clearly shows you Merge option is not fixing lines in menu

**Comment by jupiterbjy** [comment] 2017-04-09 07:45
https://youtu.be/8y6wbQhteo8?t=299
Menu/hanger Lines(not black lines) - 0:00 ~ 0:24
Settings - 0:38
Burst missle - 5:00

**Comment by mirh** [comment] 2017-04-09 13:08
Ok, seems like you are right. 
Merge_pp does nothing for *non*-in-game menus. 

Said this, guess like we could sum up last problem standing from this issue as: burst missiles are blocky? Doesn't auto flush help?

**Comment by jupiterbjy** [comment] 2017-04-11 14:41
Well, I guess you're right.
Sorry for troubling you again, I thought I fixed it when I applied auto flush and disabled align_sprite. Weird bug

**Comment by mirh** [comment] 2017-04-11 17:27
Something that I still have to understand: does it at least work at native resolution?

**Comment by jupiterbjy** [comment] 2017-04-13 08:05
I'll check it in hour, I bet it will

**Comment by jupiterbjy** [comment] 2017-04-15 11:31
https://youtu.be/su-oLU3uPcU
Sorry for delay, I was too sick, I had no time to use PC after returning home at 11 PM
And yes, it works well on native.

**Comment by mirh** [comment] 2017-04-15 14:04
Uf, good. 
And with this information I guess you could finally fill out a nice bug report. 

I guess you'd just need a gs dump for gregory.

**Comment by jupiterbjy** [comment] 2017-04-18 09:45
I tested unscale point line that day, no luck. I'll dump GS memory today, thanks for help ;)

**Comment by jupiterbjy** [comment] 2017-04-18 14:22
https://drive.google.com/open?id=0BxWgr9SSY0qtYXVGN3JoNUt3Njg
Here's dump, have no idea why screenshot looks like this

**Comment by mirh** [comment] 2017-04-18 15:06
Try round sprite half?

**Comment by jupiterbjy** [comment] 2017-04-22 10:37
Wait...it fixed it??
Didn't we fixed this issue with UserHacks_round_sprite_offset=2 at first place?
How could this happen??

**Comment by mirh** [comment] 2017-04-22 12:55
>  How could this happen??

I dunno. Seems like there are some communication problems between us. 
My only wonder now is whether AutoFlush and "Sprite" makes even any difference or not.

**Comment by jupiterbjy** [comment] 2017-04-22 14:46
When we fixed step-by-step, it all worked so greatly, especialy autoflush fixing Burst missle. But why not now - mysterious..

**Comment by mirh** [comment] 2017-04-22 18:05
Just tested in your superb gs dump. 
Auto-flush does make a difference. It just address blockiness of explosions on another "level".

**Comment by jupiterbjy** [comment] 2017-04-25 13:30
I wonder what superb mean in this context.. Anyway, in the end, auto flush did nothing but using up my performance on newer versions, I see.. 

I'll check if it has no effect on SOLG too, thanks for testing!

**Comment by mirh** [comment] 2017-04-26 08:15
It should mean that it shows off a lot of meat. 
Anyway, I'll repeat it does make a difference, at least in opengl.
