### ISSUE TITLE
[BUG]: Colin McRae Rally 2005 Broken graphics | Framerate/In-game timer

### ISSUE THREAD

**Issue by ShephardB3** [PCSX2/pcsx2#8877] opened 2023-05-18 23:48 UTC
### Describe the Bug

The game is really buggy and has been for years now.
1) menus runs fine
2) a\ going in-race is where all gets messed up, first graphics are broken if playing on a clear weather (at the exception of Rain weather where rendering is fine) (software mode renders the graphics with no problem but the others issues are still present)
b\ In-game timer is broken because it counts very slow
c\ the ghost car is not properly sync as it starts driving before the 5 second startup countdown has finished (around 3 second and it already starts driving)
d\ the speed of the game is very fast and desynced and the framerate is low
BONUS: Playing Online is where something gets interresting, since the game is capped 25fps Online, races runs perfectly and stable but the graphics are still broken unless playing with Rain and it becomes playable.

All default settings used on PCSX2,

### Reproduction Steps

.

### Expected Behavior

The ps2 version is my all times favourite

### PCSX2 Revision

v1.7.4518

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3550h

### GPU

GTX 1650

### GS Settings

![image](https://github.com/PCSX2/pcsx2/assets/126799811/15933c49-444c-4ffd-91ee-48d2ceaea14a)

### GS Window Screenshots

![image](https://github.com/PCSX2/pcsx2/assets/126799811/83a648a0-f35b-49e6-8a98-c4c197a101ce)

### Logs & Dumps

![Colin McRae Rally 2005_SLES-52636_20230519004436](https://github.com/PCSX2/pcsx2/assets/126799811/035a24a5-7e2d-4685-96e2-446d00950d23)
![Colin McRae Rally 2005_SLES-52636_20230519004504](https://github.com/PCSX2/pcsx2/assets/126799811/6419e07b-978f-4cf2-b170-893748a45d84)

**Comment by lightningterror** [comment] 2023-05-18 23:51
Duplicate of #1546

**Closed by lightningterror** 2023-05-18 23:51 UTC
Labels: Bug
