### ISSUE TITLE
Echo Night Beyond: Abnormal performance drops using the HW renderer

### ISSUE THREAD

**Issue by Helium-4** [PCSX2/pcsx2#2355] opened 2018-03-28 11:57 UTC
***PCSX2 version:***
  v1.5.0-dev-2334-gefc1274b2

***PCSX2 options:***
  see below

***Plugins used:***
  GSdx OpenGL

***Description of the issue:***
Performance is extremely poor when the flashlight is turned on while using the hardware renderer (25fps instead of 120fps uncapped with the same scene).
No setting affects the performance in any meaningful way nothing makes it faster and nearly nothing makes it any slower.
That includes speedhacks, manual gamefixes, rounding and clamping modes on both EE and VUs, rendering resolution, accurate date, blending accuracy (none breaks some things but is otherwise just as slow as ultra), CRC Hack Level, all the options in the Advanced Settings and Hacks menu.
Using DX is not an option as it does not work properly with this game although it doesn't have the performance issues OGL has (blending related since OGL with blending accuracy set to none has the same graphical issues as DX)
Here is a GS dump of the worst example of that drop I could get and another one in the same place with the flashlight off as a comparison.
[Echo Night Flashlight on.zip](https://github.com/PCSX2/pcsx2/files/1855826/Echo.Night.Flashlight.on.zip)
[Echo Night flashlight off.zip](https://github.com/PCSX2/pcsx2/files/1855827/Echo.Night.flashlight.off.zip)

***How to reproduce the issue:***
1.Start a new game
2.Skip to gameplay
3.Look right
4.Turn flashlight off and on

***Last known version to work:***
 None

***PC specifications:***
  Intel i7 4770K
  Nvidia GTX 1070 (390.77)
  Windows 7.

**Comment by gregory38** [comment] 2018-03-28 17:40
Do you have the speed issue if you disable blending and/or depth emulation

**Comment by Helium-4** [comment] 2018-03-28 17:45
Yes, disabling blending only causes graphical issues but does not impact speed, disabling depth emulation doesn't have any effect at all.

**Comment by MrCK1** [comment] 2018-04-03 19:37
Do you have "Enable 8-bit textures" checked or unchecked? It may be causing performance drops.

**Comment by Helium-4** [comment] 2018-04-03 23:41
There is basically no difference with it checked or unchecked.

**Comment by MrCK1** [comment] 2018-04-05 16:10
@Helium-4 Can you post your GSdx settings? A picture of the dialog itself would be ideal.

**Comment by Helium-4** [comment] 2018-04-05 16:54
If you wish but like I explained earlier no setting seems to really affect the speed in any real positive way and most don't seem to make it run any worse either. 
For example those settings
![image](https://user-images.githubusercontent.com/16150597/38379507-365e673a-3901-11e8-9577-36689e911468.png)
Results in pretty much the same performance as those settings
![image](https://user-images.githubusercontent.com/16150597/38379597-7cf79842-3901-11e8-9e65-4b5db81bdb35.png)
And for reference this is what I used at first (which runs the same as the above two)
![image](https://user-images.githubusercontent.com/30066566/38379914-8060b864-3902-11e8-97c8-b948befe1a58.png)

**Comment by Helium-4** [comment] 2018-04-20 20:37
Can I do anything to help you check that or are the info I provided enough?

**Comment by AlessandroVetere** [comment] 2018-05-09 18:08
If some lighting effect is achieved via the usage of palettes (using clut), maybe #2344 should improve performances.
Instead if it is mostly via uniform updates, that is still open problem with OGL (same issue of ZoE2 Anubis fight, which have both many palettes and uniform updates).

Ideally fixing DX11 blending may be the easy solution, but increasing OGL uniform buffer performances could be better because of the better overall compatibility of the OGL renderer.

**Comment by lightningterror** [comment] 2018-05-10 14:35
> Ideally fixing DX11 blending may be the easy solution.

If only someone was up to the task to do that that knows how to :)

**Comment by AlessandroVetere** [comment] 2018-05-10 20:58
Well, you are right. Maybe making separate issues just to talk about each of the two problems (DX11 blending, OGL uniform buffers) in a specific way may ease tackling those, constituing also a clear reference for future works.

**Comment by lightningterror** [comment] 2018-05-10 21:11
You should join us on discord, we talk a lot about dev stuff there, among other things :)

**Comment by Helium-4** [comment] 2019-05-10 14:44
The issue seems fixed in DX11 right now with blending on, although I haven't tested much further than the initial starting point so I can't confirm that there's no blending related issues latter on.
There's still a big impact to just having the flashlight on even in DX11 but it's merely a ~30% decrease in framerate instead of ~80% with OGL

**Comment by lightningterror** [comment] 2019-05-10 16:20
> The issue seems fixed in DX11 right now with blending on, although I haven't tested much further than the initial starting point so I can't confirm that there's no blending related issues latter on.

Cool, looks like the game hits unsafe fbmask on 32bit format to render those effects, note I can't see anything on the provided dumps, will need a multiframe dump.

**Comment by gregory38** [comment] 2019-05-10 16:39
Unsafe alpha ?

**Comment by lightningterror** [comment] 2019-05-10 17:24
Yes

**Comment by Helium-4** [comment] 2019-05-10 19:38
>I can't see anything on the provided dumps, will need a multiframe dump.

[gsdx_20190510212754.7z.zip](https://github.com/PCSX2/pcsx2/files/3167876/gsdx_20190510212754.7z.zip)

**Comment by lightningterror** [comment] 2019-05-10 22:01
Now I see, yes that is a nice improvement for dx now.

**Comment by lightningterror** [comment] 2020-03-04 08:25
I investigated this a bit further, the issue isn't fbmask but that we have 4073 colclip draw in one frame (every second frame I think), all of the cases (accumulation, free, fast hdr, sw, hdr only) are being hit depending on the draw.

A possible optimization would be to use sw colclip instead of hdr for the last case when accurate blending is enabled as it does offer a speed improvement.
https://github.com/PCSX2/pcsx2/blob/f2a9b59aae417be940abd5d61e92635fb63a60f3/plugins/GSdx/Renderers/OpenGL/GSRendererOGL.cpp#L542

**Comment by lightningterror** [comment] 2022-01-11 14:27
With Vulkan it's the best we can do, with some upscaling even so I will close this now.

**Closed by lightningterror** 2022-01-11 14:27 UTC
Labels: GS: Hardware, Performance impact, GS: Blending, GS: Fixed in Vulkan

**Comment by TransparentBlue** [comment] 2022-01-11 15:04
Considering it's about 3-4 times faster with Vulkan compared to OGL and Vulkan is even faster than DX11 with blending that's more than good enough.
