### ISSUE TITLE
Gradius V grid graphical and other glitches

### ISSUE THREAD

**Issue by TeddBb** [PCSX2/pcsx2#2070] opened 2017-09-12 15:26 UTC
Gradius V has graphical glitches spefically when bosses are entering/leaving the gameplay field of view, there's also glitches when in game cut-scenes are played.

Note the glitches happen across all versions and are easy to reproduce since I've reproduced it on other hardware with radically different specs all around.

See here for in game cutscene graphical glitch.

https://www.youtube.com/watch?v=ftr0fVPDp_k

Gridlines on entry and exit of bosses, probably do to large animations taking place.

https://www.youtube.com/watch?v=3-sUaSewbUM

PCSX2 version: build v1.4.0
PC specifications: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 780 OS: Windows 7 64 Bit

**Comment by lightningterror** [comment] 2017-09-12 16:34
Is the issue present present on v1.5.0 ?

**Comment by atomic83GitHub** [comment] 2017-09-12 16:34
Go to hardware hack section and try half pixel offset to special texture (agressive), these gridline are also in guitar hero if a remember.

**Comment by TeddBb** [comment] 2017-09-12 18:09
@atomic83GitHub 

Setting it to aggressive got rid of the grid lines on the first boss, haven't tested it all the way through the game it seemed to have helped.

The glitch for parts where control is taken away during in game cutscenes still exists however.

This glitch still exists, even with aggressive set to on:

https://www.youtube.com/watch?v=ftr0fVPDp_k

**Comment by atomic83GitHub** [comment] 2017-09-12 18:34
Can you try the EETimingHack and round/clamping mode?
A similar issue was in mgs3 subsistence in the past.

**Comment by TeddBb** [comment] 2017-09-12 21:55
@atomic83GitHub 

Tried all combinations of settings, no results.  Graphics still are corrupted.

**Comment by atomic83GitHub** [comment] 2017-09-14 20:04
The issue is in software mode?

**Comment by TeddBb** [comment] 2017-09-17 23:46
Graphical glitch goes away during in game event when set to open GL software, I haven't tested it through the whole game but it seems to help.

**Comment by lightningterror** [comment] 2020-03-22 15:15
Can you upload a gsdump of the issue?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by lightningterror** [comment] 2020-04-30 17:05
I will close this as user never provided additional details and was using an older version.

**Closed by lightningterror** 2020-04-30 17:05 UTC
Labels: GSdx: Hardware, Plugin: GSdx

**Comment by gottfired** [comment] 2022-04-16 15:27
Just tested with newest version of PCSX core in RetroArch. Cut scene glitches still happening randomly in the future Vic Viper scene.

**Comment by RedPanda4552** [comment] 2022-04-16 16:44
@gottfired We do not accept bug reports from third party builds. Use an official, up-to-date nightly build before reporting issues.

**Comment by gottfired** [comment] 2022-04-16 18:36
@RedPanda4552 Ok. I've now tested with the nightly v1.7.2621 SSE4 build. Still same glitches during the first in game cutscene. Look the same as in the OP linked video, looks like some random flashes of some broken buffer data. Grid lines are fixed though. Renderer was set to automatic.
