### ISSUE TITLE
[BUG]:  Tenchu - Fatal shadows. Buttons remain pressed after you load save state even if you press nothing. 

### ISSUE THREAD

**Issue by draccfacc** [PCSX2/pcsx2#9857] opened 2023-08-26 11:29 UTC
### Describe the Bug

Tenchu - Fatal shadows, latest nightly build. Buttons remain pressed after you load save state even if you press nothing.   Tested: 1.latest nightly - doesn't work 2.pcsx2-v1.7.4885-windows-x64-Qt - doesn't work 3.pcsx2-v1.7.3946-windows-64bit-AVX2-Qt - works fine  4.1.6.0. - works fine. 

### Reproduction Steps

1.Press e.g. "duck" button 2.save state with "duck" button pressed 3.release "duck" button 4.load state.

### Expected Behavior

Buttons not pressed after you load state

### PCSX2 Revision

1.7.4950

### Operating System

Windows 11

### CPU

R5 1600 AF

### GPU

R9 370X

### Logs & Dumps

![Tenchu 4 - Fatal Shadows_SLUS-21129_20230826142432](https://github.com/PCSX2/pcsx2/assets/141240645/0d49305b-5887-4d01-99f6-39b83b54be8f)

**Comment by stenzek** [comment] 2023-08-26 11:39
Enable the controller OSD. Check what it is saying.

**Comment by draccfacc** [comment] 2023-08-26 11:47
![Tenchu 4 - Fatal Shadows_SLUS-21129_20230826144530](https://github.com/PCSX2/pcsx2/assets/141240645/03328319-0a94-445a-acba-27bc549950e1)

**Comment by draccfacc** [comment] 2023-08-26 11:47
![1](https://github.com/PCSX2/pcsx2/assets/141240645/dd83f6e7-5468-49b1-8b13-87d4f6f3b319)

**Comment by stenzek** [comment] 2023-08-26 11:50
R1 is duck?

**Comment by draccfacc** [comment] 2023-08-26 11:50
Yes

**Comment by stenzek** [comment] 2023-08-26 13:30
Duplicate of #9716, fixed by #9858.

**Closed by stenzek** 2023-08-26 13:30 UTC
Labels: Bug, Duplicate
