### ISSUE TITLE
Burnout 3 (USA) - Crackling Engine Sounds

### ISSUE THREAD

**Issue by escape209** [PCSX2/pcsx2#2341] opened 2018-03-13 19:33 UTC
***PCSX2 version:***
1.5.0-dev-2237

***PCSX2 options:***
***Plugins used:***
All default, no speedhacks, following GSdx settings:
![image](https://user-images.githubusercontent.com/8225831/37364544-bfb5fa00-26f2-11e8-9d2d-b8a7a22435f1.png)

***Description of the issue:***
Frequently, your car's engine will have this annoying crackling to it. It seems to happen most often when I go into a race with software mode.
https://www.youtube.com/watch?v=LiTBlEJnd94

The mods aren't the cause of the issue. I get the problem with an unmodified copy, I just happened to have the modded copy selected when I was recording the video.

***How to reproduce the issue:***
Go into a race with software mode enabled.

***Last known version to work:***
Issue has always been present.

***PC specifications:***
CPU: i7-7700K
GPU: GTX 1050
OS: Windows 10 x64
RAM: 8GB

**Comment by MrCK1** [comment] 2018-03-14 00:07
What about your SPU2-X settings?

**Comment by euroze** [comment] 2018-03-14 08:13
![image](https://user-images.githubusercontent.com/8225831/37390303-6769fde8-275f-11e8-9aa1-b191806c2283.png)

**Comment by MrCK1** [comment] 2018-03-15 18:18
DirectSound is obsolete now, a lower latency with XAudio2 and ASync Mix or None would probably work better.

**Comment by atomic83GitHub** [comment] 2018-03-17 21:16
Use Directsound only if you have a very old sound card wich does not support Xaudio2 (the directsound succesor).

**Comment by mirh** [comment] 2018-03-17 21:56
I'm not sure to which windows version you have been left, but sound card has nothing to do to be made to support windows's apis.

**Comment by MrCK1** [comment] 2018-03-26 02:40
I can't reproduce this on my NTSC copy, disable the de-alias filter that you were using in the video and/or check your sound card's drivers.

**Comment by Eurose209** [comment] 2018-03-26 14:00
I found now it's definitely because of DirectSound. I think the "nice" tag beside the DirectSound option is misleading as it implies it's better in some way than XAudio, which is only "recommended", which is the reason I was using DSound (I'm not really an audio guy.)

**Comment by MrCK1** [comment] 2018-03-26 14:05
Ok I'll close this then.

**Comment by MrCK1** [comment] 2020-05-21 19:11
Reopening since I am able to reproduce on certain events using XAudio or PortAudio. Settings don't seem to affect the issue.

**Closed** 2021-01-27 00:03 UTC
Labels: SPU2

**Comment by Xerxes3rd** [comment] 2021-06-30 13:05
I can reproduce this by enabling Widescreen Patches for a USA/NTSC copy of Burnout 3 (via archive.org), and the issue doesn't seem to be present with Widescreen Patches disabled.  Happens with the Internal Resolution set to either Native or 3x (1080p).  Tried adjusting audio latency from 96 to 50 and 150, and the issue still occurs.

Best way to observe the crackling sound is to start a "Crash" event in the game and listen to the idle sound of your vehicle.

Version: PCSX2 1.6.0
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU: Nvidia GeForce GTX 1650
OS: Windows 10 x64 20H2
RAM: 16GB

**Comment by refractionpcsx2** [comment] 2021-06-30 13:08
It's been fixed in more recent builds, 1.6 will never be fixed, please test with the latest version before reporting problems, thanks.

**Comment by Xerxes3rd** [comment] 2021-06-30 13:18
Apologies!  The website shows 1.6 as the latest stable build; I’ll grab one of the development builds instead.  Thank you!

**Comment by refractionpcsx2** [comment] 2021-06-30 13:23
No problem, yes 1.6 is the latest stable, we've fixed a bunch of stuff since :)
