### ISSUE TITLE
Metal gear solid 3 pal graphical problem in hardware mode OpenGL

### ISSUE THREAD

**Issue by Nabokov86** [PCSX2/pcsx2#1848] opened 2017-03-08 19:37 UTC
***PCSX2 version:***
development builds v1.5.0-dev-1912-g91f8056

***PCSX2 options:***
Default settings. No speedhacks

***Plugins used:***
GS: GSdx32-SSE2 - default or any other settings

***Description of the issue:***
Graphic problems in hardware mode. Incorrect imaging of a thermal googles/night vision device and codec. This problem is only in the PAL version game. NTSC version works perfectly.
![fin](https://cloud.githubusercontent.com/assets/26260168/23720072/adf77856-044e-11e7-819b-7a6fd166a9fd.png)

***How to reproduce the issue:***
Run metal gear solid 3 PAL, use openGL (hardware);
Use thermal goggles or codec.

***Last known version to work:***
Unknow

***PC specifications:***
CPU: AMD Athlon II X3 460 overclocked: GeForce GTS 450 OS: Windows 7 64 Bit

p.s. I do not know much English. I'm sorry if the phrases can look stupid :p

**Comment by gregory38** [comment] 2017-03-08 19:46
Thanks you for your detailled report.

I will close it as a duplicate of #1339

**Closed** 2017-03-08 19:46 UTC
Labels: Duplicate
