### ISSUE TITLE
Enemies and characters in Final Fantasy X will sometimes face away from eachother in battle

### ISSUE THREAD

**Issue by myownfriend** [PCSX2/pcsx2#760] opened 2015-08-13 12:57 UTC
In the fight that Tidus has with the large underwater monster at the beginning of the game, he and the monster will be facing away from each other and they will turn around to attack. The same thing happens in the fight with the creature he fights near the campfire, though in that case, it's only the monster and only the portion of the fight with Rikku in it.

**Comment by karasuhebi** [comment] 2015-08-13 13:08
Known issue:
http://wiki.pcsx2.net/index.php/Final_Fantasy_X#Characters_face_the_wrong_direction_during_battles

**Comment by refractionpcsx2** [comment] 2015-08-13 13:48
This is a well known issue which requires clamping to fix, this isn't really something we can deal with. I guess we could change the rounding by default in the gamedb, however some users might complain about the speed drop.

**Comment by myownfriend** [comment] 2015-08-13 18:08
Ah, sorry about that. Should I close this issue or no?

**Comment by refractionpcsx2** [comment] 2015-08-13 19:04
Leave it open for now, i've marked it as a potential change to the game database, but ill leave this open for discussion about pro's and con's of doing it.

**Comment by willkuer** [comment] 2015-08-13 19:39
Default options should almost every time be accurate. Users can specify speedhacks if wanted.

Also is rounding really changing performance? Clamping is clear but rounding?

**Comment by refractionpcsx2** [comment] 2015-08-13 19:50
Sorry, I meant clamping, I wil edit my post

**Comment by willkuer** [comment] 2015-08-13 19:54
Well ee round to negative works as well.

**Comment by refractionpcsx2** [comment] 2015-08-13 20:29
probably because it rounds weird and avoids the need for the clamp, but i prefer changing clamping than rounding as rounding tends to have more unintended behaviour

**Closed** 2018-02-20 19:25 UTC
Labels: GameDB, Maybe?
