### ISSUE TITLE
[Feature Request]: 64MB/128MB Ram Toggle

### ISSUE THREAD

**Issue by StillPlay2** [PCSX2/pcsx2#9909] opened 2023-09-05 17:59 UTC
### Description

A option/toggle for upgrading the default 32MB Ram on PS2 to 64MB/128MB. A feature particularly useful for homebrew games, game-hacks, development PS2's, The PSX, prototypes, unreleased software (possibly retail games that can benefit from the extra ram but I can test rigourously 🙂

One example is "Ultimate Mortal Kombat Deception" that requires double the ram to which is a modification on the original version of Mortal Kombat Deception which vastly improves on the vanilla version that features extra characters, extra stages etc
https://github.com/ermaccer/ultimate-mkd

Thank you 🙂

### Reason

Improvements, upgrades

### Examples

Duckstation, Dolphin, xemu, RPSC3 ("Debug Console Mode" I believe in "Advanced Configuration")
Linux on PS2 (PBPX-95509) for improved & better experience.
Others maybe.

**Comment by Mrlinkwii** [comment] 2023-09-05 18:01
duplicate of #5803

**Comment by Mrlinkwii** [comment] 2023-09-05 18:02
and duplicate of #1549

**Closed by Mrlinkwii** 2023-09-05 18:01 UTC
Labels: Enhancement / Feature Request
