### ISSUE TITLE
[BUG]: Onimusha 2 left side of screen , fog effects and fmv borders issue etc.

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [PCSX2/pcsx2#7563] opened 2022-12-09 10:14 UTC
### Describe the Bug

Left side of screen has alignment issue, fog effects only show in software mode aka an upscale issue no matter the API used and FMVs got images on borders and flickering 

### Reproduction Steps

Load up game and play mountain level and for fmv just play a fmv,  for alignment issue,  I'll elaborate:
On the first level only, press f9 twice to cycle to and from software renderer. After that, HW renderer will display the first area correctly with no black on left side.

Rest of the game will only display correctly in Software mode.

### Expected Behavior

Left side of screen should be aligned , fog should be rendering proper and fmvs shouldn't flicker or have images overplayed on borders

### PCSX2 Revision

PCSX2 1.7.3693

### Operating System

Windows 11

### CPU

Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz   3.60 GHz

### GPU

ASUS STRIX RTX2070 Super

### GS Window Screenshots

https://cdn.discordapp.com/attachments/309643527816609793/1050708698495995924/image.png            https://cdn.discordapp.com/attachments/309643527816609793/1050710246869434419/image.png

### Logs & Dumps
[Onimusha_2_-_Samurais_Destiny_SLUS-20393_20221209105800.zip](https://github.com/PCSX2/pcsx2/files/10193852/Onimusha_2_-_Samurais_Destiny_SLUS-20393_20221209105800.zip)

**Comment by Mrlinkwii** [comment] 2023-02-02 18:27
can this be check on latest mater ?

**Comment by washingleavesandthensome23-434** [comment] 2023-02-18 21:50
> can this be check on latest mater ?

Yup still an issue as of today, latest nightly

**Comment by Murad58** [comment] 2023-02-18 21:51
Checked, and confirmed to be present on 1.7.4110 :)

**Comment by kevin98761234** [comment] 2023-03-21 05:41
Fog is displayed whether the renderer is software or any hardware.
The left border is present with the renderer in hardware, but the blinking is not confirmed.
No FMV problems can be confirmed.

v1.7.4262
![Onimusha 2_SLPM-65101_20230321143118](https://user-images.githubusercontent.com/88806005/226526376-a4891404-6b77-4878-a108-653c328aefab.png)

**Comment by washingleavesandthensome23-434** [comment] 2023-06-22 21:37
Any progress on this one?🙂

**Comment by washingleavesandthensome23-434** [comment] 2023-07-05 16:31
OK noticed one more issue, 
![Screenshot_20230218_075542](https://github.com/PCSX2/pcsx2/assets/60486562/1b436b8e-ff69-4b8f-ae8b-37ec34744ca9)


Getting these weird black lines on subs

**Comment by washingleavesandthensome23-434** [comment] 2023-07-05 20:25
OK one more bug noticed for today

**Comment by washingleavesandthensome23-434** [comment] 2023-07-06 10:57
One more thing I've noticed,  is it possible too add the ability for adding texture injection support for 2d prerendered backgrounds like oni2 has a ton of? Would really be appreciated a ton

**Comment by washingleavesandthensome23-434** [comment] 2023-08-15 11:48
Any progress on oni2 issues?🙂

**Comment by stein3x** [comment] 2023-09-27 05:59
The bug with the misaligned left side is still present in the latest revision, unfortunately the only way to play the game bug-free is to use software mode. The subtitles black lines is a common issue when you change the internal resolution higher than native in games that use a mix of 3D and 2D assets even in some psone games, you will get black lines or missing corners in the subtitles. The only way to properly play is to use software mode with Lottes CRT to blend everything nicely till maybe it will get fixed in some future revision.

**Comment by washingleavesandthensome23-434** [comment] 2023-10-16 07:18
> OK one more bug noticed for today , iffy shadows looks like lines
> 
> <img alt="image_7-5-23_22-28-47" width="261" src="https://user-images.githubusercontent.com/60486562/251274539-71699be9-513b-442c-b92d-4a07f8127c86.png">
> ![Onimusha_2_-_Samurais_Destiny_SLUS-20393_20230705221651](https://user-images.githubusercontent.com/60486562/251273944-91eec3f3-a983-4c8f-8a96-704f72597aeb.png) [Onimusha_2_-_Samurais_Destiny_SLUS-20393_20230705221651.zip](https://github.com/PCSX2/pcsx2/files/11961740/Onimusha_2_-_Samurais_Destiny_SLUS-20393_20230705221651.zip)

Btw Just loaded Oni 2 up in software mode, the shadow lines are still present.

Version: v1.7.5116

**Comment by stein3x** [comment] 2023-10-17 12:44
I recently replayed Onimusha 2 in Software mode and i didn't experience or notice any rendering issues, i checked again on the latest version v1.7.5125 and it looks fine.

Software:
<a href="https://ibb.co/18CD39f"><img src="https://i.ibb.co/18CD39f/software.png" alt="software" border="0"></a>

DX11 native resolution:
<a href="https://ibb.co/r4tbKBs"><img src="https://i.ibb.co/r4tbKBs/dx11-default.png" alt="dx11-default" border="0"></a>

DX11 1440p internal resolution:
<a href="https://ibb.co/cNhQDHg"><img src="https://i.ibb.co/cNhQDHg/dx11-1440p.png" alt="dx11-1440p" border="0"></a>

In DX11 you can still notice the black bar on the left side which is still present no matter the settings.

**Comment by stenzek** [comment] 2023-10-17 13:05
The SPS-like issue on the shadows might be because the rounding/clamping has been messed with. It's baked into the GS dump, and broken even in software. OP should upload a save instead.

**Closed** 2023-10-17 15:08 UTC
Labels: Bug

**Comment by washingleavesandthensome23-434** [comment] 2023-10-29 07:36
Appreciated alot stenzek🫡
