### ISSUE TITLE
Many games crash with custom resolution.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#1972] opened 2017-06-15 17:02 UTC
***PCSX2 version:***
v1.5.0-dev-2117-g4a56240

***PCSX2 options:***
EE-IOP
Round Mode : chop zero 
Clamping mode : Normal

VUs
Micro-vu
Same as th EE-IOP

Hack:
None used

***Plugins used:***
GSDX dx9 (OpenGL have the same issue)

***Description of the issue:***
Many games randomly crash with custom resolution , native resolution (x3 for exemple) works.

***How to reproduce the issue:***
In Silent hill 3, Load the first level of the game and walk to the librairy (where we see Claudia the first time) and you will see crash (before sometimes).
In Top Spin, just load the game and it will never past the FMV.

***Last known version to work:***
1.5dev 1435

***PC specifications:***
Amd Phenom 2 x4 955 be
Nvidia gtx 560ti

**Comment by ssakash** [comment] 2017-06-15 17:45
Interesting. By the way, I need more information regarding the bug,

* Does the issue occur when Large Framebuffer is enabled/disabled?
* Does it occur on all custom resolution values (or) is it limited to only a specific value?
* Region of the game? USA/Europe?

I'm afraid I can't look into the issue in detail if you don't provide a block dump/[GS dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue, do you think you could provide either one of them? If not, I'd be resorted to get the game on my own. 😢

**Comment by atomic83GitHub** [comment] 2017-06-15 18:19
The frame buffer don't change the issue , I had tested with some resolution (1820x720,568x789 and many other),but not change, the region of the game is Japan but I suspect the Pal version and NTSC are also affected. Aanother thing , TOP SPIN is also affected but only in the dx9 mode.

**Comment by atomic83GitHub** [comment] 2017-06-15 18:21
I will create a gs dump please wait

**Comment by atomic83GitHub** [comment] 2017-06-15 18:43
![image](https://user-images.githubusercontent.com/26351275/27196344-5bbad89e-520a-11e7-8dcc-e99e7c3e68d7.png)
It seems to be more intensive on dx9 and OpenGL.
But I cant put them in github please help me.

**Comment by atomic83GitHub** [comment] 2017-06-15 18:56
I you have a mail respository i can send you the gs dump

**Comment by lightningterror** [comment] 2017-06-15 22:33
I managed to reproduce the issue on build 1.5. - 1274 so it's not a regression.

Hope these are enough.
GS dump at the area before the crash happens.
Application crash dump.
Block dump.
Large Framebuffer makes no difference.
Resolution 1080p 
DX9 seems to be the worst case scenario followed by OpenGL(note amd gpu , don't quote me on it)
https://drive.google.com/open?id=0B8cQAq-Ko9-uc3ZURXIwYUExblU

**Comment by ssakash** [comment] 2017-06-16 06:19
> I you have a mail respository i can send you the gs dump

You could probably just host it in an external file hosting site (Like Dropbox) and share the link of the file.

>  managed to reproduce the issue on build 1.5. - 1274 so it's not a regression.

Did you manage to reproduce the issue at ``1.5.0-dev-2113``? Just wondering as @atomic83GitHub has marked it as the last working version.

**Comment by lightningterror** [comment] 2017-06-16 12:16
2112 actually. 2113 doesn't have a download link and too lazy to compile it.

Yes the crash is present.

**Comment by gregory38** [comment] 2017-06-29 08:52
A Visual Studio backtrace/stacktrace of the crash will be nice too.

**Comment by atomic83GitHub** [comment] 2017-07-22 18:25
There is an error in my topic , the last version to work is not the 2113 , but I can't download the correct version due to a build orphis issue (404 error) , the 1.6 and the regression label must be reintroduced (and maybe the hight priority label because its a huge regression)
Note: Some game are not able to pass the loading screen with custom resolution !

**Comment by ssakash** [comment] 2017-07-22 18:36
> There is an error in my topic , the last version to work is **not** the 2113 , but I can't download the correct version due to a build orphis issue (404 error),  the 1.6 and the regression label must be reintroduced (and maybe the hight priority label because its a huge regression)

I'm confused. You're saying that the issue was **not** introduced by 2113 and you haven't tested older versions yet due to an error in the buildbot then how are you sure it's a regression in the first place? I assume you tested an older version of PCSX2 and it didn't have the issue? If that's the case, could you mention the version number of that specific old build?

**Comment by atomic83GitHub** [comment] 2017-07-22 18:38
I had before found the version that introduced the issue and must refind it to remember , so when the Buildbot issue is fixed , I will update the topic.

**Comment by lightningterror** [comment] 2017-07-22 18:41
> when the Buildbot issue is fixed , I will update the topic.

Buildbot has been fixed.

**Comment by atomic83GitHub** [comment] 2017-07-22 20:15
#lightningterror not for me , anyway , I will update it tomorrow.

**Comment by atomic83GitHub** [comment] 2017-07-27 15:49
Buildbot not fixed yet , what's going on here.

**Comment by atomic83GitHub** [comment] 2017-08-30 20:22
I have test many games on the 1.4 version and they don't have crash with custom resolution.
It's a regression.
I can't download the version that introduced the issue (buildbot don't work with older version: 404 error).

**Comment by lightningterror** [comment] 2017-09-07 01:15
Yeah buildbot doesn't work.

Try going through Appveyor history , it should work the same.
https://ci.appveyor.com/project/gregory38/pcsx2/history

**Comment by atomic83GitHub** [comment] 2017-09-07 04:50
Thanks for the info.
I will try to find the build that introduced the issue.

**Comment by lightningterror** [comment] 2017-09-07 20:15
Found it.

Regression  PR https://github.com/PCSX2/pcsx2/pull/1435

GS Dump
https://drive.google.com/open?id=0B8cQAq-Ko9-uRWpBaWEwU1VFYzA

Block Dump
https://drive.google.com/open?id=0B8cQAq-Ko9-ucmZpTmU3UThDUEk

**Comment by MrCK1** [comment] 2017-10-24 17:25
What's the ststus on this?

**Comment by lightningterror** [comment] 2017-10-24 17:39
@ssakash is working on it. Gonna take a while.

**Comment by ssakash** [comment] 2017-10-24 21:24
I'm not working on this at the moment, don't have to because there's nothing left to work on. I actually fixed this issue internally last month, I just didn't get free time to push it to remote. (I'm sure you guys are aware of the patch I'm talking about? I mentioned about it in the discord group channel)

I'll probably open the pull request for it when I get free time, plus there are some conflicting bugs already present in the texture cache which needs to be dealt with before applying my patch.

**Closed** 2018-03-03 03:31 UTC
Labels: GSdx: Hardware, GSdx: Upscaling, Plugin: GSdx, Regression
