### ISSUE TITLE
Slowdown when certain objects are drawn (Gran Turismo 3)

### ISSUE THREAD

**Issue by RAZORXKHARA33** [PCSX2/pcsx2#2043] opened 2017-08-15 21:42 UTC
When I drive on sunset and/or night tracks, emulation will pause for a split second when taking certain corners. Sound cuts out and the image freezes and then resumes. One way to trigger it is at Laguna Seca. It happens whenever the sun comes into and out of view. After the pause, the emulation speed immediately returns to 100%. It's just a form of lag, but I'm running a GTX 1080 and not really pushing the internal resolution that far, so I wouldn't tend to expect performance like that, even with how resource-intensive PCSX2 can be at times. This has been happening ever since I started using PCSX2, but I'm currently using build v1.5.0-dev-2155-g41bfb6e80.

***PCSX2 version:***
v1.5.0-dev-2155-g41bfb6e80, but also happens on stable 1.4.0 and earlier.

- **Notes**:
Not urgent, nor game-breaking, but would be nice to have fixed before next stable release.

***PCSX2 options:***
EE Round: Chop/Zero
EE Clamping: Full
VU Round: Chop/Zero
VU Clamping: Extra + Preserve Sign
Frame limiting and Frame skipping disabled
Vsync setting: Forced on thru Nvidia Control Panel, set to Adaptive in PCSX2
EE Cyclerate: +1 (issue persists with EE Cyclerate set to default)
VU Cycle Stealing: None
INTC Spin Detection: Enabled
Wait Loop Detection: Enabled
Fast CDVD: Enabled
mVU Flag Hack: Enabled
MTVU: Enabled
Manual Game Fixes: Disabled

***Plugins used:***

GSdx Settings:
Adapter: NVIDIA GeForce GTX 1080
Renderer: OpenGL (Hardware)
Interlacing: Bob tff
Texture Filtering: Bilinear (PS2)
Allow 8-bit textures: Enabled
Large Framebuffer: Enabled (issue persists regardless of setting)
Internal Resolution: 3x Native
Mipmapping (Ins): Full (disabling or setting to basic does not help)
CRC Hack Level: Partial (OpenGL Recommended)
HW Hacks: Disabled
Accurate Date: Enabled
Blending Unit Accuracy (High)

SPU-2X Settings:
Interpolation: Catmull-Rom
Disable Effects Processing: Disabled
Use de-alias filter: Disabled
Debug Options: Disabled
Module: XAudio2
Volume: 100%
Latency: 30ms
Synchronizing Mode: Async Mix
Audio Expansion Mode: Stereo (none, default)
Use a Winamp DSP Plugin: Disabled

***Description of the issue:***
Emulation pauses for a split second when certain objects are drawn and becomes rather irritating over time.

***How to reproduce the issue:***
At Laguna Seca, when the sun comes into and out of view, the issue will occasionally occur. It's worse at Seattle Circuit and will sometimes happen at Special Stage Route 11, even though there is no sun there. I've even seen it happen at non-sunset tracks like Grand Valley Speedway I and Rome Circuit I.

***Last known version to work:***
It's been present in every version of PCSX2 I've used since 1.2.1 stable.

***PC specifications:***
CPU: Intel Core i7 4790K (4.4 GHz)
RAM: 32 GB DDR3 1600 MHz
GPU: Nvidia GeForce GTX 1080
Boot SSD: Samsung 950 Pro 256 GB (PCSX2 loads off of this drive)
Mass Storage 1: WD Blue 1 TB 7200 RPM (games, inis, and memory cards load off of this, moving games to an SSD does not help).
Windows 10 Pro 64-bit, Creators Update

**Comment by mirh** [comment] 2017-08-15 22:46
Take a gs dump and post it.

**Comment by RAZORXKHARA33** [comment] 2017-08-15 23:18
Does it have to be at the exact moment the sun draws into view, or just when it is on screen at any given point?

**Comment by mirh** [comment] 2017-08-16 07:13
If the problem is spanned in time you can take a some-seconds-long dump.

**Comment by RAZORXKHARA33** [comment] 2017-08-16 13:32
It only happens the instant the sun comes into view (and sometimes the instant it moves out of view). The GSDump I took is from Monaco, where the issue doesn't occur as often, but still occurs nonetheless.

If there are other cars in view while the sun is in view, then the game slows down. I've also experienced this since I started using PCSX2, but the split-second pause when it first enters view is far more annoying.

GS Dump: https://www.dropbox.com/s/ze7geg4qpd3jtis/gt3_sun_lag.zip?dl=0

**Comment by atomic83GitHub** [comment] 2017-08-16 14:15
Same issue on the game "Beyond good and evil".

**Comment by gregory38** [comment] 2017-08-16 15:13
What happen if you disable depth emulation (by the way mipmapping full isn't a good idea)

**Comment by RAZORXKHARA33** [comment] 2017-08-16 15:33
@gregory38 If I disable depth emulation, the issue isn't fixed, and smoke and dust is visible through the car body when it shouldn't be (looks the same regardless on DX11). I use full mipmapping because I get no performance increase from turning it to basic or off.

**Comment by MrCK1** [comment] 2017-09-30 03:21
@RAZORXKHARA33 Turn Blending Accuracy to Medium and see if the performance drops are still present. 

For instance, even for my 1070 gets performance drops in GT4 when viewing cars, ect. This is resolved by reducing Blending Accuracy to Medium.

**Comment by RAZORXKHARA33** [comment] 2017-09-30 04:44
@MrCK1 I get the same results as you, no slowdown. This has been the case since PCSX2 had a blending unit accuracy option. At the time, I had a 780 Ti, whereas now, I have a 1080. The slowdown was even worse before, but it seems like there's something happening that's stealing GPU cycles and causing a crazy slowdown when blending unit accuracy is set to high. It just doesn't seem right for even a high-end system to be brought to its knees just by looking at a car in its full detail (which, for GT3 and GT4, pales in comparison to what we see in Project Cars and Assetto Corsa). I know the resource intensiveness is down to the fact that it's an emulator, so PC hardware wasn't meant to render it in the first place, but it still doesn't sit 100% right with me...

**Comment by gregory38** [comment] 2017-09-30 05:05
No it is normal and expected. BA high is for lighter games which have blending issue in the first place.
No ba == 1 draw of 1000 triangles
ba == 1000 draws of 1 triangle + 1000 gpu cache flushes
So yes it is slow (cpu wise mostly)
Besides ba bypass the ROPs of your gpu. ROPs are emulated with shader so it also increases the gpu load.

**Comment by MrCK1** [comment] 2017-09-30 05:08
Well you can't compare PC games and emulation to be fair. Blending accuracy is emulated by a shader, which is why it's slow even on high end systems. GT4 is very heavy when it comes to shaders. 

Another thing to note is that blending performance doesn't scale equally across PCSX2. Other games such as The Suffering even require Full Blending for all effects to be produced on-screen. 

I don't know how much more wiggle room there is in the future, but hopefully we can make a more efficient blending operation in the future or add another step between medium and high for games like this.

Since the slowdown issue is resolved, I'm going to close this for now. Thanks for the quick reply!

**Closed** 2017-09-30 05:09 UTC
Labels: GSdx: Hardware, Plugin: GSdx
