### ISSUE TITLE
Hype the Time Quest: missing polygons

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#2944] opened 2019-04-28 16:06 UTC
***PCSX2 version:***
1.5dev 3108

***PCSX2 options:***
All default, speedhacks disable, tested with interpreter.

***Plugins used:***
All defaults, GSDX software mode

***Description of the issue:***
The game "Hype the Time Quest misses a lot of polygons with all GSDX renders (likely a core problem).

![Capture](https://user-images.githubusercontent.com/26351275/56866978-2cfed600-69e0-11e9-99c6-aacf4f36c284.PNG)

***How to reproduce the issue:***
Load the game "Hype the Time Quest".

***Not a regression***

***PC specifications:***
AMD fx8350, GTX 1060, 16 gb Gskill ram

**Comment by RhythmLady** [comment] 2019-05-30 12:31
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ
https://discord.gg/bFCfZte
https://discord.gg/N24gCZJ

**Comment by MarvinKlein1508** [comment] 2019-08-29 19:56
I have just tested it again with PCSX2 v1.5.0-dev-3272. Unfortunately nothing as changed yet. I will check again regulary. If you need any data related to this issue, dont hestitate to contact me.

Best,
Marvin

**Comment by Sleora** [comment] 2019-09-26 01:54
Unfortunately, I too have suffered these graphic bugs. No matter how hard I tried all the possible configurations, nothing works. I find this unfortunate because these bugs make the game experience extremely difficult (or even unplayable). I pray that a solution will appear very quickly.

**Comment by Sleora** [comment] 2019-11-24 16:59
Hello there, after playing a bit, I noticed that not only polygons/textures are missing, but mechanics too. I managed to cross Gogoud's bridge and selecting the key. But no matter how many times I try, the gate won't open. I have the unlocking animation, but nothing happens. Some sounds won't play too by the way.

**Comment by MarvinKlein1508** [comment] 2019-11-26 21:33
> 
> 
> I managed to cross Gogoud's bridge and selecting the key but no matter how many times I try, the gate won't open.

I can't confirm this behaviour. I was able to reach Torras. But once reached, everthing was cut afterwards the mid of the screen. 

I tried it on PAL Version German.

**Comment by kozarovv** [comment] 2019-11-28 16:33
Missing textures and sounds can be similar issue to Shadowman 2, probably caused by SNDDRVGR.IRX or SNDDRV.IRX. Will be good to find person that own modded PS2, and that game, to test it using OPL and SMB. There is small chance that missing texturing will be reproduced that way on PS2, and will partially confirm that iop is problem here. 

Why SMB + OPL? Because this scenario is getting most of IOP memory, and for example allow to reproduce Shadowman 2 issue on real hardware. I know is more like assumption than anything else, but really worth to give it a shot. Is not first time when custom sounds modules produce issues, vide DOA2, Shadowman 2.

**Comment by PSI-Rockin** [comment] 2019-11-28 16:47
Can't comment on Shadowman 2, but in the case of DOA2, the dcache bug is on the EE side. DOA2 does two nonblocking RPC calls in a row, Because the game, for some reason, reuses the same buffer for sending and receiving, without dcache emulation the IOP will overwrite the second RPC call, which leads to the crash.

The tl;dr is that the issue with DOA2 has nothing to do with the IOP and is completely caused by EE bugs.

If this game has a custom CDVD streaming module, then it could be a likely candidate for the problem. Otherwise, I'm not sure how broken sound would also affect missing polygons. More often than not, I've found that "IOP bugs" are actually caused by improper usage of the modules on the EE side.

**Comment by Sleora** [comment] 2019-12-07 17:59
I realized something! The textures/polygons are not missing, they are all there. It is the order of the textures that are bugger, those normally in the background appear in the foreground and therefore hide the others.

**Comment by seta-san** [comment] 2020-12-10 21:16
[gsdx_20201210151303.gs.zip](https://github.com/PCSX2/pcsx2/files/5675650/gsdx_20201210151303.gs.zip)

**Comment by refractionpcsx2** [comment] 2020-12-10 21:19
A GS dump won't help, this is a VU issue.

**Comment by Sleora** [comment] 2020-12-10 22:40
Is it possible to fix the issue or the game is made in a particular way that makes the launcher unable read VU correctly?

**Comment by refractionpcsx2** [comment] 2020-12-10 22:42
I'm not sure if it's fixable without causing performance problems, it's something I'm going to have to look in to and see if I can come up with an adequate solution.

**Comment by Sleora** [comment] 2020-12-10 23:09
Thanks

**Comment by Sleora** [comment] 2021-04-19 22:18
Any news ?

**Comment by KevinEca** [comment] 2021-07-29 18:26
Hello everyone,
Hype the Time Quest is a game from my childhood. So I test it sometimes with PCSX2 in the hope that there can be completely playable. Lately the game is much better, apart from all the dialog boxes (are they behind what is displayed?) Everything else seems to match.
The bug like listed here have the same result  with the 1.7-1526 build, but the 1.7-1554, the result is more accurate. I will search for the exact build that gives the magic ^^
![hype time quest 1-6-1554](https://user-images.githubusercontent.com/22177436/127545801-6c8f2c52-4f3e-4ee9-8341-3e0cf6fd5798.png)

**Comment by MarvinKlein1508** [comment] 2021-07-29 18:42
@KevinEca there are still textures missing within the tree

**Comment by refractionpcsx2** [comment] 2021-07-29 18:46
okay this is weird, the rounding thing isn't quite straight forward.. You need to go to the menu with Chop/Zero rounding, then swap to Positive in the menu.  Booting with Positive rounding means it won't work, so weird!

**Comment by KevinEca** [comment] 2021-07-29 18:47
After some research, the 1.7-1526 (https://github.com/PCSX2/pcsx2/commit/c1232136c22d6e4d5f6f2e75e949cb7aee26783a) has the problem, and the 1.7-1528 (https://github.com/PCSX2/pcsx2/commit/cd33a17584fadb7aed29262dc7a1a1109c6ff4de) have the adjusted graphics.
it hasn't a 1.7-1527 build, so maybe ?

For the tree, it's true (and piece of wall also)
For the EE Rounding to Positive, i can't reproduce that
Thanks you for all your work

**Comment by refractionpcsx2** [comment] 2021-07-29 18:48
@KevinEca sorry you must have been replying when I did, try the sequence that I used to do it, booting with Positive doesn't seem to work on its own, which is a bit irriitating

**Comment by seta-san** [comment] 2021-07-29 18:49
Ipu color conversion did this?

**Comment by refractionpcsx2** [comment] 2021-07-29 18:51
I guess so, could avoid some accidental hiding of stuff...

**Comment by KevinEca** [comment] 2021-07-29 19:10
I don't know if this can help, but the result is know very similar to the other PS2 emulator Play! (0.42-56 with default settings), same bug with the HUD/Menu.
Before the 1.7-1528, Plays! had a better result, but now this is no longer the case (issue in the head of playmobil)
![hype time quest 1-6-1554 2](https://user-images.githubusercontent.com/22177436/127551584-3bbc0d8c-928e-41bf-ae70-103887572792.png)
![play 0 42-56](https://user-images.githubusercontent.com/22177436/127550735-78841a8f-6936-41d3-83df-cc6a59afc843.jpg)

**Comment by refractionpcsx2** [comment] 2021-07-29 19:18
Did you try swapping the rounding on the menu like I said +

**Comment by KevinEca** [comment] 2021-07-29 19:27
Yes I changed it, and it's work. The EE Rounding to positive must be done after the loading screen (with the Ubisoft's logo) and during the main menu
![hype time quest 1-6-1554 3](https://user-images.githubusercontent.com/22177436/127553136-ee961580-b612-4ed2-8883-45554da8685e.png)

**Comment by Sleora** [comment] 2021-07-29 22:33
Great ! It's all doing great ! It's been so long since improvements (since any improvements at all...). I hope the game will be fully playable soon.

**Comment by refractionpcsx2** [comment] 2021-08-10 17:50
That tree is not a rendering glitch, that's entirely different geometry for the tree and the background, that's not the same area. My guess if that is the same area, is there's multiple versions of this game with different geometry, because I can't see the emulator making that much of a mistake without it being complete nonsense, which it isn't.

**Comment by KevinEca** [comment] 2021-08-10 18:26
For the sky, the defects seems to appear in console too, the video with pause at 5:37
Somebody with Hype time quest and a YUC cable for check this with a good quality?

Two images by pcsx2, with internal resolution x1 and x3
![hype time quest x3](https://user-images.githubusercontent.com/22177436/128912984-6ea8450c-0dd6-4cec-94e5-797860788c7a.png)
![hype time quest natif](https://user-images.githubusercontent.com/22177436/128912989-a36b4156-8370-47bc-b142-702b9ec79436.png)
Surely a false problem

**Comment by refractionpcsx2** [comment] 2021-08-10 18:34
I mean, to me the sky looks fine.

**Comment by KevinEca** [comment] 2021-08-10 18:52
So only  HUD/Menus remains then, good
Note : 
After change the rounding mode at main menu (rounding mode to "Chop / Zero" and assign it to "Positive") and load a game.
When you change zone, loading screen, you have to redo it  to keep the fix (→ "Chop / Zero" → "Positive")

**Comment by refractionpcsx2** [comment] 2021-08-10 18:54
hmm, then there must be a calculation/value being computed during loading screens, it might be patchable, but I don't know where to start.

**Comment by refractionpcsx2** [comment] 2021-09-12 22:47
I have devised a patch for the PAL M4 version in PR #4762

If you have the German or French versions, please send me a blockdump up to the main menu, you can skip the videos (just be sure to allow a second or 2 for me to press the button)

**Comment by seta-san** [comment] 2021-09-13 02:50
M4 works quite well so far.

**Comment by MarvinKlein1508** [comment] 2021-09-13 06:42
I can provide you a blockdump for the German version. How do I get one? @refractionpcsx2

**Comment by refractionpcsx2** [comment] 2021-09-13 07:32
> I can provide you a blockdump for the German version. How do I get one? @refractionpcsx2

in 1.7 you can go to the debug menu then "Create blockdump" then run your game normally up to the menu, exit the emulator gracefully and it should put a .dump file in your PCSX2 folder :)

Oh and don't forget to turn blockdumps back off again once you're done.

Thanks :)

**Comment by refractionpcsx2** [comment] 2021-09-13 08:34
I've added the French release which happened to be the same address, just waiting on the German one now, though I suspect the address is going to be the same again lol

**Comment by MarvinKlein1508** [comment] 2021-09-13 21:11
I've downloaded the latest build now. Here is the dump

```
PCSX2 1.7.0-20210913205553 - compiled on Sep 13 2021
Savestate version: 0x9a240000

Host Machine Init:
	Operating System =  Microsoft Windows 10, 64-bit
	Physical RAM     =  32704 MB
	CPU name         =  Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Vendor/Model     =  GenuineIntel (stepping 09)
	CPU speed        =  4.199 ghz (8 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff fedaf387
	x86EFlags        =  2c100800

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA

The current power profile is 'Ausbalanciert'.
The current min / max processor states
AC: 5% / 100%
Battery: 5% / 100%

Reserving memory for recompilers...
[GameDB] 10627 games on record (loaded in 388ms)
	HotSwapping to new ISO src image!
HLE Host: Set 'host:' root path to: \

Patches: No CRC found, using 00000000 instead.
isoFile open ok: D:\ROMS\PS2\Hype The Time Quest PS2.ISO
	Image type  = CD
 * CDVD Disk Open: CD, 1 tracks (1 to 1):
 * * Track 1: Data (Mode 1) (319386 sectors)
isoFile create ok: D 
blockoffset = 0
blocksize   = 2448
blocks	     = 319386
3.x GL context successfully created
OpenGL information. GPU: NVIDIA GeForce RTX 2070/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver: NVIDIA 466.47
INFO: GL_ARB_sparse_texture is available
INFO: GL_ARB_sparse_texture2 is available
INFO: GL_ARB_gpu_shader5 is available
INFO: GL_ARB_shader_image_load_store is available
INFO: GL_ARB_compute_shader is available
INFO: GL_ARB_shader_storage_buffer_object is available
INFO: GL_ARB_texture_view is available
INFO: GL_ARB_vertex_attrib_binding is available
INFO: GL_ARB_clear_texture is available
INFO: GL_ARB_multi_bind is available
INFO: GL_ARB_direct_state_access is available
INFO: GL_ARB_texture_barrier is available
INFO: GL_ARB_get_texture_sub_image is available

Current Renderer: OpenGL
Available VRAM/RAM:3840MB for textures
GS Lookup CRC:00000000
48000 SampleRate: 
GS Lookup CRC:00000000
McdSlot 0 [File]: D:\Downloads\pcsx2-v1.7.0-dev-1741-g154ed5763-windows-x86\memcards\Mcd001.ps2
(FileMcd) Creating new 8MB memory card: D:\Downloads\pcsx2-v1.7.0-dev-1741-g154ed5763-windows-x86\memcards\Mcd001.ps2
McdSlot 1 [File]: D:\Downloads\pcsx2-v1.7.0-dev-1741-g154ed5763-windows-x86\memcards\Mcd002.ps2
(FileMcd) Creating new 8MB memory card: D:\Downloads\pcsx2-v1.7.0-dev-1741-g154ed5763-windows-x86\memcards\Mcd002.ps2
EE/iR5900-32 Recompiler Reset
	Bios Found: Europe  v02.00(14/06/2004)  Console
# Initialize memory (rev:3.70, ctm:196Mhz, cpuclk:147Mhz detected)

PlayStation 2 ======== Hard reset boot
 ROMGEN=2004-0614, IOP info (CPUID=1f, CACH_CONFIG=0, 2MB, IOP mode)
 <20040614-100914,ROMconf,PS20200EC20040614.bin:11696>
# Total accessable memory size: 32 MB (B:2:8:0) (370:2:7c30)
# TLB spad=0 kernel=1:12 default=13:30 extended=31:38
# Initialize Start.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize User Memory ...
# Initialize Scratch Pad ...
# Initialize Done.

EE DECI2 Manager version 0.06 Feb  6 2003 08:38:48
  CPUID=2e20, BoardID=0, ROMGEN=2004-0614, 32M

Patches: No CRC found, using 00000000 instead.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLES_502.65;1
(SYSTEM.CNF) Software version = 1.01
(SYSTEM.CNF) Disc region type = PAL
PAD: Warning! No controls are bound to a currently attached device!
Please attach a controller that has been setup for use with PAD or go to GamePad Settings and setup new controls.

found 13585 symbols
ELF (cdrom0:\SLES_502.65;1) Game CRC = 0x3D2A2448, EntryPoint = 0x00100008
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLES_502.65;1
(SYSTEM.CNF) Software version = 1.01
(SYSTEM.CNF) Disc region type = PAL


IOP Realtime Kernel Ver.0.9.1

    Copyright 1999 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadelf: fname cdrom0:¥SLES_502.65;1 secname all
loadelf version 3.30
Input ELF format filename = cdrom0:¥SLES_502.65;1
0 00100000 0020dc80 .................................
Loaded, cdrom0:¥SLES_502.65;1
start address 0x100008
gp address 00000000
# Restart Without Memory Clear.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize Scratch Pad ...
# Restart Without Memory Clear Done.
Elf entry point @ 0x00100008 about to get recompiled. Load patches first.
[GameDB] Searching for 'sles-50265' in GameDB
[GameDB] Found 'sles-50265' in GameDB
[GameDB] Searching for patch with CRC '3d2a2448'
[GameDB] No CRC-specific patch or default patch found
[GameDB] Searching for 'sles-50265' in GameDB
[GameDB] Found 'sles-50265' in GameDB
[GameDB] Searching for patch with CRC '3d2a2448'
[GameDB] No CRC-specific patch or default patch found
GS Lookup CRC:3D2A2448
GS Lookup CRC:3D2A2448
Get Reboot Request From EE

PlayStation 2 ======== Update rebooting..

PlayStation 2 ======== Update reboot complete
cdvdman Init


IOP Realtime Kernel Ver. 2.1

    Copyright 1999-2001 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
MEC File Not Found, creating substitute...
loadmodule: fname cdrom0:¥MODS¥LIBSD.IRX;1 args 0 arg 
loadmodule: id 25, ret 0
loadmodule: fname cdrom0:¥MODS¥SIO2MAN.IRX;1 args 0 arg 
loadmodule: id 26, ret 0
loadmodule: fname cdrom0:¥MODS¥PADMAN.IRX;1 args 0 arg 
loadmodule: id 27, ret 0
loadmodule: fname cdrom0:¥MODS¥MCMAN.IRX;1 args 0 arg 
loadmodule: id 28, ret 0
loadmodule: fname cdrom0:¥MODS¥MCSERV.IRX;1 args 0 arg 
loadmodule: id 29, ret 0
loadmodule: fname cdrom0:¥MODS¥SDRDRV.IRX;1 args 0 arg 
SDR driver version 2.0.0 (C)SCEI
 Exit rsd_main 
loadmodule: id 30, ret 0
Get Reboot Request From EE

PlayStation 2 ======== Update rebooting..

PlayStation 2 ======== Update reboot complete
cdvdman Init


IOP Realtime Kernel Ver. 2.1

    Copyright 1999-2001 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadmodule: fname cdrom0:¥MODS¥LIBSD.IRX;1 args 0 arg 
loadmodule: id 25, ret 0
loadmodule: fname cdrom0:¥MODS¥SIO2MAN.IRX;1 args 0 arg 
loadmodule: id 26, ret 0
loadmodule: fname cdrom0:¥MODS¥PADMAN.IRX;1 args 0 arg 
loadmodule: id 27, ret 0
loadmodule: fname cdrom0:¥MODS¥MCMAN.IRX;1 args 0 arg 
loadmodule: id 28, ret 0
loadmodule: fname cdrom0:¥MODS¥MCSERV.IRX;1 args 0 arg 
loadmodule: id 29, ret 0
loadmodule: fname cdrom0:¥MODS¥SDRDRV.IRX;1 args 0 arg 
SDR driver version 2.0.0 (C)SCEI
 Exit rsd_main 
loadmodule: id 30, ret 0
(UpdateVSyncRate) Mode Changed to PAL.
Stream Buffer 1Bank 32768byte 5banks 163840byte used
Stream Buffer 1Bank 32768byte 5banks 163840byte used
Stream Buffer 1Bank 32768byte 5banks 163840byte used
Stream Buffer 1Bank 32768byte 5banks 163840byte used
[GameDB] Searching for 'sles-50265' in GameDB
[GameDB] Found 'sles-50265' in GameDB
[GameDB] Searching for patch with CRC '3d2a2448'
[GameDB] No CRC-specific patch or default patch found
Unknown device 'GameData¥World¥Sound¥;1'
Unknown device 'GameData¥World¥Sound¥;1'
Unknown device 'GameData¥World¥Sound¥German¥;1'
Unknown device 'GameData¥World¥Sound¥German¥;1'
Unknown device ';1'
Unknown device ';1'
Unknown device 'German¥;1'
Unknown device 'German¥;1'
open fail name ¥SOUND¥SOUND0¥LIBSD.IRX;1
open fail name ¥SOUND¥SOUND1¥LIBSD.IRX;1
open fail name ¥SOUND¥SOUND2¥LIBSD.IRX;1
open fail name ¥SOUND¥SOUND3¥LIBSD.IRX;1
Unknown device 'host'
Known devices are  tty:(CONSOLE)  rom:(ROM/Flash)  cdrom:(CD-ROM )  mc:(Memory Card) 
loadmodule: fname cdrom0:¥MODS¥LIBSD.IRX;1 args 0 arg 
loadmodule: id 31, ret 1
open fail name ¥SOUND¥SOUND0¥SNDDRVGR.IRX;1
open fail name ¥SOUND¥SOUND1¥SNDDRVGR.IRX;1
open fail name ¥SOUND¥SOUND2¥SNDDRVGR.IRX;1
open fail name ¥SOUND¥SOUND3¥SNDDRVGR.IRX;1
Unknown device 'host'
loadmodule: fname cdrom0:¥MODS¥SNDDRVGR.IRX;1 args 0 arg 

-----------------------Begin IOP init--------------------------
The block RAM 666064
-----------------------End   IOP init--------------------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!IRX exit  point!!!!!!!!!!!!!!!!!!!!!!!!!!!
loadmodule: id 32, ret 0
Welcome to fn_iInitItClassObjectEnv
Welcome to fn_iInitSpuEnv
Welcome to fn_iInitVagEnv
Welcome to fn_iInitMemEnv
Welcome to fn_iInitCdEnv
Disk Type= PlayStation2 CD
Initialised in CD mode
Welcome to fn_iInitRoundEnv
Welcome to fn_iInitChMemEnv
Welcome to fn_iInitChCdEnv
Welcome to fn_iInitChRoundEnv
Welcome to fn_iInitSTRMEnv
fn_iInitLoadIop2Spu init
open fail name ¥SOUND¥SOUND0¥BNK_0.VSC;1
Unknown device 'host'
[GameDB] Searching for 'sles-50265' in GameDB
[GameDB] Found 'sles-50265' in GameDB
[GameDB] Searching for patch with CRC '3d2a2448'
[GameDB] No CRC-specific patch or default patch found
```


I don't see any buttons within the main menu on PAL German version.

**Comment by refractionpcsx2** [comment] 2021-09-13 21:15
That's not the instructions I gave you...

I haven't done the german version yet, I'm waiting for your blockdump

**Comment by RedDevilus** [comment] 2021-09-13 21:16
A blockdump can be seen as an interactive video or a snippet of an ISO. The purposes are for debugging even when other people such as a dev that don't own the games. Combined with savestates it's a very handy tool.

Enabling Blockdumps
Follow the menu path below which matches your PCSX2 version:
- 1.6.0: Debug > Create Blockdump
- 1.7.0: Debug > Create Blockdump

Creating and Uploading Blockdumps
- Start buggy game with fast or full boot (don't use savestate)
- Run till you see the issue + let it run for 5 seconds extra.
- Fully Close PCSX2.
- Find the blockdump where pcsx2.exe is.
- Upload here with a working savestate

Also you should enable high performance plan for your computer.

**Comment by MarvinKlein1508** [comment] 2021-09-13 21:19
Oh my bad. Here you go: http://www.filedropper.com/hypethetimequestps22021-08-1323-17-21

As mentioned previously: 3D models work, 2D UI doesn't

**Comment by refractionpcsx2** [comment] 2021-09-13 21:21
Thanks. Yes, I know, give me a minute :P

**Comment by refractionpcsx2** [comment] 2021-09-13 21:23
Did you load the game normally? because that blockdump doesn't work, it fails to boot.

**Comment by MarvinKlein1508** [comment] 2021-09-13 21:23
Yes. I choose ISO and clicked on System and then on boot.

**Comment by refractionpcsx2** [comment] 2021-09-13 21:29
You didn't press F3 or load a savestate?

**Comment by MarvinKlein1508** [comment] 2021-09-13 21:29
No. I only chose the ISO booted it up, skipped the videos and then closed the application.

**Comment by refractionpcsx2** [comment] 2021-09-13 21:31
and you had "create blockdump" ticked before you started the game, yes? cos this is very strange, it's not booting at all... It's failing to open a file

**Comment by MarvinKlein1508** [comment] 2021-09-13 21:33
I don't know how to read the file. I created another dump:
http://www.filedropper.com/hypethetimequestps22021-08-1323-30-14
or as 7z http://www.filedropper.com/hypethetimequestps22021-08-1323-30-14_1

**Comment by refractionpcsx2** [comment] 2021-09-13 22:38
You just mount the blockdump as an ISO (make sure you disable "create blockdump", though)

hmm that's still failing to load a file

> open fail name ¥MODS¥LIBSD.IRX;1
> loadmodule: id -203, ret 0
> loadmodule: fname cdrom0:¥MODS¥LIBSD.IRX;1 args 0 arg 
> CdRead: Reading Sector 0000016 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000048 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000032 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000016 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000048 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000032 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000016 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000048 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000032 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000016 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000048 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000032 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000016 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000048 (001 Blocks of Size 2340) at Speed=24x
> open fail name ¥MODS¥LIBSD.IRX;1
> loadmodule: id -203, ret 0
> loadmodule: fname cdrom0:¥MODS¥LIBSD.IRX;1 args 0 arg 
> CdRead: Reading Sector 0000016 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000048 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000032 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000016 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000048 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000032 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000016 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000048 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000032 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000016 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000048 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000032 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000016 (001 Blocks of Size 2340) at Speed=24x
> CdRead: Reading Sector 0000048 (001 Blocks of Size 2340) at Speed=24x
> open fail name ¥MODS¥LIBSD.IRX;1
> loadmodule: id -203, ret 0
> loadmodule: fname cdrom0:¥MODS¥LIBSD.IRX;1 args 0 arg 
> 

It just loops doing that for me. :/  have you got any special settings? what BIOS are you using?

**Comment by RedDevilus** [comment] 2021-09-13 22:51
Not sure what is happening:
![image](https://user-images.githubusercontent.com/24227051/133167056-6980e9e2-501f-44c1-999d-3dcea80c53d9.png)

Seems broken, can you even see anything even without doing blockdumps aka just running the game?

**Comment by refractionpcsx2** [comment] 2021-09-14 08:25
okay, alternative solution, just send me the ELF file off the disc, it'll be called SLES_502.65

**Comment by MarvinKlein1508** [comment] 2021-09-14 15:16
@refractionpcsx2 I created a small video which shows how I get the blockdump for you. Tell me if I did anything wrong.
https://www.youtube.com/watch?v=3w4AwDJaSSA

**Comment by MarvinKlein1508** [comment] 2021-09-14 15:19
Also here is the SLE_502.65 file
https://www.file-upload.net/download-14691238/SLES_502.65.html

**Comment by refractionpcsx2** [comment] 2021-09-14 15:22
looks like the right procedure :/ does it work when you play it back?

Thanks for the ELF, I can make the patch from that

**Comment by refractionpcsx2** [comment] 2021-09-14 15:28
Okay I've added the German patch to the PR, to nobodies surprise, it was at the same address again.

**Comment by MarvinKlein1508** [comment] 2021-09-14 16:25
> looks like the right procedure :/ does it work when you play it back?

No it doesn't. It just crashes. Not sure why. 

> Can you confirm it works, then I'll merge it and close this issue, finally!
I am not this much into C++ development. Could you provide an updated .exe so I can check it out? The current downloadable executable is 8 hours old

**Comment by refractionpcsx2** [comment] 2021-09-14 16:28
Here, this is all you need, no need for a new exe. just extract this to your pcsx2 folder
[GameIndex.zip](https://github.com/PCSX2/pcsx2/files/7163630/GameIndex.zip)

**Comment by MarvinKlein1508** [comment] 2021-09-14 16:42
It works fine for me.

**Comment by refractionpcsx2** [comment] 2021-09-14 16:45
awesome :) I'll merge then

**Closed** 2021-09-14 16:45 UTC
Labels: Core, Recompiler, Interpreter, Bug - Unknown Source

**Comment by Neroagin** [comment] 2022-07-22 19:26
hey, so i wanted to start playing the game on my ps2 since i played the original and rly liked it but had the missing pol's. how did you manage to fix it?

**Comment by refractionpcsx2** [comment] 2022-07-22 19:33
The poly issue was a bug with the IPU (used for videos normally but can be used for graphics, as in this case).  The missing font's I had to patch because there was a rounding error.

**Comment by Neroagin** [comment] 2022-07-22 21:55
Can you tell me how to fix it or give me like a piece of software i need to use? Would really appreciate it

**Comment by refractionpcsx2** [comment] 2022-07-22 21:56
download the latest version.

**Comment by Neroagin** [comment] 2022-07-22 22:05
Of what?

**Comment by refractionpcsx2** [comment] 2022-07-22 22:06
PCSX2....

**Comment by Neroagin** [comment] 2022-07-22 22:11
Indeed, but im pretty sure i d downloaded nightly, ima just reinstall it. Thanks for the advise

**Comment by refractionpcsx2** [comment] 2022-07-22 22:12
well if your 3d is still broken, you're not on the latest nightly.

**Comment by Neroagin** [comment] 2022-07-22 22:17
how do i know it is nightly? it doesnt give an option

**Comment by refractionpcsx2** [comment] 2022-07-22 22:18
what is the version at the top of the window?

**Comment by Neroagin** [comment] 2022-07-22 22:24
1.6.0

**Comment by Neroagin** [comment] 2022-07-22 22:24
downloaded the newest

**Comment by Neroagin** [comment] 2022-07-22 22:24
still has the bugs

**Comment by refractionpcsx2** [comment] 2022-07-22 22:25
1.6 is the last stable, it's not the nightly.

the nightly's are under the "nightly" section of the downloads on the website.

**Comment by Neroagin** [comment] 2022-07-22 22:26
aaah ok thx ima download them now

**Comment by Neroagin** [comment] 2022-07-22 22:32
YAAAAAY it worked, thx man u saved my weekend
