### ISSUE TITLE
[BUG]: SOCOM 3 [SCES-53300] flickering and invisible characters

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#5944] opened 2022-04-23 23:19 UTC
### Describe the Bug

Flickering and disappearing characters including main character. Happens in Hardware and Software renderers.

### Reproduction Steps

Easiest to reproduce but multiple locations
- Quick Deploy
- Run straight and a bit left (Delta Location)
- Stand at the edge of the crater

### Expected Behavior

Not flicker dead bodies or other characters.

### PCSX2 Revision

v1.7.2648

### Operating System

Windows 10 (64bit)

### CPU

i7-9750H

### GPU

RTX 2060M

### GS Settings

/

### Emulation Settings

/

### GS Window Screenshots

/

### Logs & Dumps

[gs_20220423142355_SOCOM_3_-_U.S._Navy_SEALs__PAL-M5__SCES-53300.zip](https://github.com/PCSX2/pcsx2/files/8548766/gs_20220423142355_SOCOM_3_-_U.S._Navy_SEALs__PAL-M5__SCES-53300.zip)

Broken:
![image](https://user-images.githubusercontent.com/24227051/164949142-a541f592-54af-43a3-bacc-dda7cf7d7c58.png)

Working:
![image](https://user-images.githubusercontent.com/24227051/164949157-12c486e7-accb-49cf-899c-6c1d4222fcee.png)

**Comment by prafullpcsx2** [comment] 2022-04-24 00:41
Isn't there an automatic entry in the gamedb for this? Something like Round mode to negative/nearest and clamping mode to None used to work in the past?

**Comment by RedDevilus** [comment] 2022-04-24 00:43
There is one for the SPS but no rounding or clamping (EE or VU) works for it.

**Comment by RedDevilus** [comment] 2022-04-24 00:53
Ok None VuClamp fixes SPS but hides the character and makes dead bodies flicker.

However higher VuClamp fixes the flickering introduces the SPS again.

**Comment by RedDevilus** [comment] 2022-04-24 00:56
All default:
![image](https://user-images.githubusercontent.com/24227051/164951081-62e54a5c-f9a0-4276-b26e-f382ad109e89.png)

Gamefix with None VuClamping:
![image](https://user-images.githubusercontent.com/24227051/164951086-d0a806d9-c3b9-45ae-869b-ab96d3c96173.png)

VuClamp Extra+ Preserve sign and Full (seems the same):
![image](https://user-images.githubusercontent.com/24227051/164951104-89c6340b-6862-46d4-9d36-b66f697b8e68.png)

**Comment by xCENTx** [comment] 2022-04-25 07:10
include this in your game patches
```
Serial = SCUS-97474
Name   = SOCOM 3 - U.S. Navy SEALs
Region = NTSC-U
Compat = 6
eeRoundMode = 0	// Fixes Screen Tearing
vuRoundMode = 0	// Fixes Screen Tearing
eeClampMode = 3	// Fixes Invisible Characters
vuClampMode = 3	// Fixes Invisible Characters
[patches = 75ED4282]
	author=Prafull
	// fix slowdown when looking at sun
	patch=1,EE,2019EB40,word,00000000
[/patches]
```

**Comment by refractionpcsx2** [comment] 2022-04-25 10:41
I'm not convinced that the EE needs any clamping/rounding setting.  The VU certainly does.

**Comment by xCENTx** [comment] 2022-04-25 15:40
These are recommended settings that the SOCOM Community has been running for about 2 years now. If you don't use those settings you will get screen tearing and objects not rendering on screen.

**Comment by refractionpcsx2** [comment] 2022-04-25 15:41
I know the vu settings affect that stuff, but I've not been shown any evidence that the EE settings affect it.

So to be clear, I completely agree on the VU settings.

**Comment by RedDevilus** [comment] 2022-04-25 15:51
Still occasional SPS
![image](https://user-images.githubusercontent.com/24227051/165125456-acb0d2d8-17d3-480d-91cc-446a6e8d655d.png)

[v1.7.2641-64bit-Qt-SOCOM3PALsstate.zip](https://github.com/PCSX2/pcsx2/files/8556108/v1.7.2641-64bit-Qt-SOCOM3PALsstate.zip)

**Comment by refractionpcsx2** [comment] 2022-04-25 15:53
@RedDevilus you have to restart the game, otherwise it doesn't take effect properly, so safestates break it.

**Comment by RedDevilus** [comment] 2022-04-25 16:00
![image](https://user-images.githubusercontent.com/24227051/165127653-c9f80f3d-d1fc-491a-84f8-21a08d7ba4fe.png)
Works fine now if restarted and using this.

**Comment by xCENTx** [comment] 2022-04-25 17:33
> okay cool, what about the rounding to nearest on the VU? Does that affect anything?

I have been testing this for the last hour or so and could not see any  positive differences with rounding setting changed from the default preset. It seems the issue is resolved by changing the VU Clamping

**Comment by refractionpcsx2** [comment] 2022-04-25 17:34
OK Cool, that confirms we don't need to add anything else then. Thanks for testing.

**Closed** 2022-04-25 22:28 UTC
Labels: Bug
