### ISSUE TITLE
Marvel vs Capcom 2: 2D Issue

### ISSUE THREAD

**Issue by Kidboy17** [PCSX2/pcsx2#2637] opened 2018-10-13 18:41 UTC
***PCSX2 version:***
Build v1.5.0-dev-2616-g70033020a

***PCSX2 options:***
All Default settings, DirectX 11 hardware

***Description of the issue:***
All 2D images of this game are "fuzzy". Changing any of the texture filtering options does not help any. Im using Direct3D 11 Hardware, SSE4.1. OpenGL has the same issue, plus the screen bounces up and down slightly.
![gsdx_20181013112537](https://user-images.githubusercontent.com/37382324/46908778-b9322b80-cedc-11e8-86ab-1464c2157d02.png)

***PC specifications:***
Intel i5-4670k, Nvidia 780Ti, Windows 7 Ultimate

**Comment by KrossX** [comment] 2018-10-15 02:17
That's why it's called saw-tooth, and the deinterlacing method that gives you up and down movement, called bob. Blend will give you a more stable image, although there'll be ghosting. Also, all deinterlacing methods work best in native resolution.

**Comment by Kidboy17** [comment] 2018-10-15 02:29
Im using native resolution. Default everything

**Comment by Kidboy17** [comment] 2018-10-17 20:04
That makes sense. I always use Native Resolution as I find it is the most accurate with the least amount of errors.

So is my problem worth fixing with a commit?

**Comment by KrossX** [comment] 2018-10-18 02:39
I don't know if there's anything to fix here. It seems to be just the usual problem with interlaced video. Some games look fine with setting **Interlacing** to **None** but otherwise, pick the method you can tolerate the most.

**Comment by MrCK1** [comment] 2019-03-11 04:11
Based on the images provided, this issue is not a bug in the core but rather dependent on the interlacing setting. Therefore, I will be closing this.

**Closed by MrCK1** 2019-03-11 04:11 UTC
