### ISSUE TITLE
Can't map PS3 right joystick

### ISSUE THREAD

**Issue by johnny-mac** [PCSX2/pcsx2#2491] opened 2018-07-02 04:10 UTC
***PCSX2 version:***
1.4 and 1.5

***Plugins used:***

lillypad, onepad-legacy, onepad

***Description of the issue:***

I can't map the right joystick on my PS3 controllers!

***How to reproduce the issue:***

trying to map PS3 right joystick

***PC specifications:***
AMD FX-6300 3.5ghz 6-core 16GB RAM Nvidia GT 1030, Artix(Arch derivative) Linux
HP EliteBook 8440p 2.4ghz 4-core i5 8GB RAM intel i915, Void Linux

**Comment by ledufff** [comment] 2018-11-14 23:12
I have a similar issue on Debian Stretch, PCSX2 from debian repos. 
I can reproduce something similar with kernel 4.18.6 from backports. In my case nor R_Up nor R_down is recognized.
![captura de pantalla de 2018-11-14 17-52-54](https://user-images.githubusercontent.com/10855368/48518054-582ca900-e836-11e8-9c2c-9018ec85168b.png)


If I use the default, stable kernel which is 4.9 the bug is gone
![captura de pantalla de 2018-11-14 16-06-00](https://user-images.githubusercontent.com/10855368/48517060-1fd79b80-e833-11e8-9288-8f52dd55a551.png)

I mapped my DualShock 3 successfully using kernel 4.9, but when using kernel 4.18.6 the controller won't work unless you remap the controller again, but like the pics tell, axes seems to be in the wrong places/missing.

I can use the controller just fine with any other emulator under any kernel, precision, vibration and so. 
Wonder if this an issue related to OnePad or to the distro, since as you may see kernel seems to be related to how DS3 behaves. 
(I don't have anything else backported only kernel/firmware. 
Anything else like, udev, systemd, mesa, etc is all from stable)

**Comment by ptkato** [comment] 2019-04-01 00:13
I have a similar problem, but I can't map the dpad, R3, R_Up, R_Down, L3, start, select; and for some reason the L2 maps as JAxis 2 Full and the R2 maps as JBut 7, as can be seen in the image.

![image](https://user-images.githubusercontent.com/10677806/55297127-26893880-53f9-11e9-84f9-0266e48c36cb.png)

**Comment by ptkato** [comment] 2019-04-20 23:37
@ledufff I don't believe it's distro specific, I installed the PCSX2 git version in Arch Linux (kernel 5.0.8) and I got the same problem as you when using OnePad Legacy (1.3.0), R_Down and R_Up doesn't map. Now with OnePad (1.5.0) things are even worse, as I stated in my previous post.

**Comment by gregory38** [comment] 2019-04-21 05:52
Need Sdl version too. Onepad (not legacy) should work without any mapping

**Comment by ptkato** [comment] 2019-04-24 21:40
Yeah, OnePad 1.5.0 works without any bindings. It's a bit misleading though, because the controller doesn't bind anything in the config window, even though it works fine in-game.

**Comment by arcum42** [comment] 2019-04-25 05:59
With the non-legacy version, the config window is mostly there for if you want to use a keyboard as your controller, so you can map keys.

That dialog box is also one I find rather painful to make changes to, between wxwidgets, and all the hard-coded positions on things. One of these days, I'll get back to the branch where I was fiddling with it...

**Comment by johnny-mac** [comment] 2019-07-10 01:27
Any fixes come up? I still don't understand how to fix this issue q_q
still can't program the right joystick. Have to use antimicro with the arrow keys mapped to the joystick... not ideal. Would be great to get it working straight.

**Comment by SeanyMCP** [comment] 2020-04-07 19:23
Hello, I have exactly the same problem, cannot map start, select, L3, R3, Ry, Rx.
For info I had a mapping problem with the right analog stick systemwide before I corrected the mapping with js-test. Ry, Rx and R2 were meddled up. I'm not sure if it is related because now

**Comment by lightningterror** [comment] 2020-12-18 14:21
Closing in favour of #4016

**Closed by lightningterror** 2020-12-18 14:21 UTC
Labels: PAD: Linux/Mac
