### ISSUE TITLE
Bios ps2 Logo off center 

### ISSUE THREAD

**Issue by WizLizard** [PCSX2/pcsx2#1054] opened 2015-12-23 00:32 UTC
On the latest dev builds the Playstation 2 logo you see before a game starts is vertically off center.

**Comment by Depersonalized** [comment] 2015-12-23 09:37
Screenshot?

**Comment by WizLizard** [comment] 2015-12-23 09:42
@Depersonalized Here it's slightly lower. Look at it in full screen it's easier to notice.

![screenshot 4](https://cloud.githubusercontent.com/assets/12180630/11974138/6d900844-a92f-11e5-9403-e097c2d00f59.png)

**Comment by WizLizard** [comment] 2015-12-23 09:46
@Depersonalized All settings at default.

![screenshot 5](https://cloud.githubusercontent.com/assets/12180630/11974219/0a2945c6-a930-11e5-9daa-1fc3e3e49bbc.png)

**Comment by ssakash** [comment] 2015-12-23 11:54
@WizLizard 

can you provide your emulog while using a debug build during the reproduction of this issue ?

**Comment by WizLizard** [comment] 2015-12-23 12:03
@ssakash Here is a log.

[log2.txt](https://github.com/PCSX2/pcsx2/files/70734/log2.txt)

**Comment by ssakash** [comment] 2015-12-23 12:07
@WizLizard 

one from the debug builds please not the release build,

**Comment by WizLizard** [comment] 2015-12-23 12:08
Hmm where do i get the debug build?

**Comment by Depersonalized** [comment] 2015-12-23 12:11
http://buildbot.orphis.net/pcsx2/index.php?m=get&rev=v1.3.1-1568-gf4dcb35&platform=windows-x86

**Comment by ssakash** [comment] 2015-12-23 12:14
No, you have to compile the debug build yourself. @Depersonalized  has provided the development version.

If you don't have resources to compile then I'll upload the debug build and give you the link.

**Comment by ssakash** [comment] 2015-12-23 12:19
here's one of my upload of the debug build: https://www.dropbox.com/s/vg70leofffucbj0/bin.rar?dl=0

provide the emulog after the reproduction of this issue. do note that debug builds are slower than the release builds.

**Comment by WizLizard** [comment] 2015-12-23 12:27
Can't run it seems i'm missing a few dependencies?

**Comment by ssakash** [comment] 2015-12-23 12:39
I think you need windows SDK : https://dev.windows.com/en-us/downloads/windows-10-sdk

**Comment by turtleli** [comment] 2015-12-23 12:45
@ssakash Console Log -> Sources -> Dev/Verbose - is it not enough to just enable that on a release build?

**Comment by WizLizard** [comment] 2015-12-23 12:48
@ssakash Ok i will try again after installing SDK when i have a chance.

**Comment by ssakash** [comment] 2015-12-23 12:49
@WizLizard 

I think you can follow @turtleli  instructions, that's way better, partially my fault since I didn't think of that :p

**Comment by WizLizard** [comment] 2015-12-23 12:57
So i went ahead and just left it in d39 mode as it seems to effect all renders that iv'e tested.

[log.txt](https://github.com/PCSX2/pcsx2/files/70779/log.txt)

**Comment by ssakash** [comment] 2015-12-23 13:11
Thanks, can you do one more test on the 1.2.1 version reproducing the issue with  Console Log -> Sources -> Dev/Verbose  and provide the emulog ? 

here's the build download link: http://pcsx2.net/download/releases/windows.html

**Comment by WizLizard** [comment] 2015-12-23 13:20
I'm pretty sure this doesn't issue doesn't occur in 1.2.1

**Comment by ssakash** [comment] 2015-12-23 13:38
I see, then it's likely that when it gets a request for 0x72 it sets NTSC video mode and then hence the height modification. I'll look into it when I have some time, Thanks for reporting.

**Comment by WizLizard** [comment] 2015-12-23 13:39
Np

**Comment by ssakash** [comment] 2015-12-24 09:56
@WizLizard 

here's a build download link of #1057 : https://ci.appveyor.com/api/buildjobs/qebcaldojbjplb4c/artifacts/pcsx2-v1.3.1-1577-g75680d7-master-64-vs2015-Win32-ReleaseAll.7z

can you confirm that the issue is resolved ?

**Comment by ssakash** [comment] 2015-12-24 16:19
oh. nevermind delaying this till a proper fix gets committed. the one I had done caused black border regression on three other games :(

**Comment by WizLizard** [comment] 2015-12-24 19:27
Ok

**Closed** 2016-01-17 15:38 UTC
Labels: Plugin: GSdx, Regression

**Comment by BParks21** [comment] 2022-04-21 20:56
@ssakash This issue has returned in nightly v1.7.2645. Not sure exactly when it started.

**Comment by refractionpcsx2** [comment] 2022-04-21 21:01
You have 2 choices @BParks21 

1. Live with it
2. Use the screen offsets option, but this might look weird in some games.
3. 
![image](https://user-images.githubusercontent.com/6278726/164551624-0125ede7-12a5-43ab-91bf-fcfd4fd8408d.png)
