### ISSUE TITLE
[BUG]: NTSC-J games don't have Japanese names in fullscreen menu.

### ISSUE THREAD

**Issue by TailsGuy** [PCSX2/pcsx2#10124] opened 2023-10-16 20:17 UTC
### Describe the Bug

Recently, there's been a change where Japanese games have their Japanese names displayed instead of the English names.
I like this change, but I realized that it actually isn't reflected in the fullscreen menu. [Press ESC when you're in full screen]

### Reproduction Steps

Go into any Japanese game, in my example I did Final Fantasy X International, and go full screen, and then press ESC. Look at the bottom right, be sure not to focus on the actual file name, but the GameDB title.

### Expected Behavior

I'd assume it would be Japanese too since it was changed recently.

### PCSX2 Revision

1.7.5122

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment] 2023-10-16 20:25
Was this not fixed by #10119 ?
I would have assumed it would be the same fix.

**Comment by TailsGuy** [comment] 2023-10-16 21:30
![Screenshot 2023-10-16 172956](https://github.com/PCSX2/pcsx2/assets/70661792/111e4af3-0dfc-4ccb-b7b4-fd307d4c9d1d)
Nada

**Comment by TailsGuy** [comment] 2023-10-16 21:31
![Screenshot 2023-10-16 173101](https://github.com/PCSX2/pcsx2/assets/70661792/49bb0604-48f9-4635-b1bc-6b96da6c1ad0)

**Comment by refractionpcsx2** [comment] 2023-10-16 21:49
oh english may be forced in the full screen/pause/osd, because we use imgui for it.

What we probably need to do is link the glyph updater to also check the gamedb so we can display them. As long as we don't have any arabic game titles, because imgui can't do RTL :)

**Comment by stenzek** [comment] 2023-10-17 02:48
This is working as intended, and a "won't fix" for now.

There's two main problems with adding all the gamedb glyphs:
1. It has to be added to every locale, which means resizing the window and startup becomes slower, because they have to all be re-rasterized again.
2. The code points may not be supported in other CJK fonts.

The "solution" is to refactor ImGui's font rasterizer to rasterize multiple fonts, on demand, depending on the code point. But that's a pretty mammoth task, and kinda out of scope for us. Unless someone wants to take it on, in which case, I'm sure ImGui would be appreciative - it's a well established issue there.

**Closed by stenzek** 2023-10-17 02:48 UTC
Labels: Bug, GUI/Qt
