### ISSUE TITLE
Dog's Life (PAL) - Dog gets black after a few seconds

### ISSUE THREAD

**Issue by SimplyLiz** [PCSX2/pcsx2#1004] opened 2015-11-28 10:18 UTC
![2015-11-28 1](https://cloud.githubusercontent.com/assets/7029836/11451291/46ba46ac-95c1-11e5-94be-4a5b8cb99f67.png)

Latest rev from today (1.3.1 - 1487)

Just start a new game and walk around for a fews seconds, Jake get's all black, a lot of texture bugs on him.

Btw, he also has a "colored stripe" on his head. This happens right from the beginning. This seems not to be related to the "getting black" issue.

Happens in both OpenGL and DirectX. (though directx has a lot more texture issues.) Doesn't happen in Software Mode though.

**Comment by willkuer** [comment] 2015-11-28 14:54
Have you tried higher accuracy in opengl? E.g.something like blending mode or accurate date?

**Comment by Talantyyr** [comment] 2015-11-28 15:29
I've tried "Accurate Date", "Hardware Deth" and Blending Unit Accuracy set to Ultra with no difference, jake still turns black.

**Comment by willkuer** [comment] 2015-11-28 22:04
Thanks. What about crc hack level : none vs partial vs full?

**Comment by Talantyyr** [comment] 2015-11-29 08:22
CRC None -> it's even worse. The Textures looks greenish (moldy Oo) like in DirectX. So the crc hack level seems to make it better in openGL :)

i've now tested all combinations of CRC Level / Blending accuracy (and both checkboxes accurate date / hardware depth) and jake always turns black.

8 bit textures also make no difference.
Same goes for Resolution (tried native, 1x, 2x, 3x, 4x)

I've now also disable the HW Hacks (skipdraw set to 1). Still turns black.

I've prepared a savestate. Press X  to leave smellovision, run forward and watch jake turn black. when you load the savestate in software mode this doesn't happen.
http://workupload.com/file/wezuzcAl

**Comment by willkuer** [comment] 2015-11-29 17:30
I think it would help more if you create a GS dump. The devs do not necessarily have the game and savestates get invalid from time to time. So please create a gs dump.

**Comment by Talantyyr** [comment] 2015-11-29 18:39
Here you go:
http://workupload.com/file/4y4qA2Pr

I've started the game, loaded the savestate, Hold Shift + F8, ran forward until jake was all black and released the button. Hope that helps!

**Comment by FlatOutPS2** [comment] 2018-02-25 14:44
This still happens with latest git build. Jake the dog turns black when moving the character with Direct3D11 and OpenGL hardware renderers, Direct3D9 hardware renderer turns the skin blue-green-ish and it seems to change slower than with the other HW renderers. Switching to Software will not fix the issue, but not playing in hardware renderer at all will prevent it.

**Comment by jpovixwm** [comment] 2020-10-03 20:47
This issue still occurs as of 3231e7956. All versions of the game are affected: SLUS-21018, SCES-51248 and SLPM-65995.
I did some investigation with SLUS-21018, and here's what I've got to share:

The visual glitch is caused by the dog gradually getting dirtier the further it travels. This is why the issue doesn't occur when the dog stands in place.
The game constantly checks the distance traveled by the dog, and once it goes over 500.0 units, the value is reset to 0, and the dog is made very slightly more dirty.
The subroutine responsible for making the dog dirtier is the one at `001f99c8` (this also handles the dog cleaning process if you go to the dog wash), while the one for checking the distance traveled is at `001f59e0`. By modifying the instructions at `001f60b0` and `001f60f8`, it is possible to alter the required distance and the amount by which the dog gets dirtier, respectively.
For example, when the distance condition is set to 1000.0, the rate at which the dog gets dirtier will be 50% of the original game. And if the instruction responsible for the incrementation is altered so that it increments by 2 rather than by 1, the dog will get dirtier in larger steps at a time. Setting it to 0 will cause the dog to never get dirty, avoiding this graphical bug altogether. Because of how useful it is, I've created this PNACH, which lets you enjoy the game with a HW renderer: `patch=0,EE,001F60F8,byte,00`.

Given the above, I was able to gain control over how the dog is made dirtier, which allowed me to easily reproduce this issue with the dog standing still, which I hope will make the GS dumps I captured easier to work with and analyze.
The issue manifests itself only if a HW renderer is used while the dog gets dirtier.
A GS dump I captured with the SW renderer, where the glitch doesn't occur, can be replayed with GSdx's HW renderers and the glitch cannot be reproduced.
In the opposite case, when the dump was captured in HW mode, the glitch now *will* reproduce when the dump is replayed in SW mode.
I'm also including a third GS dump, captured using HW mode in 2x resolution. This has interesting effects, because you can see the textures from the ground located behind the dog, get applied to the dog itself. And once again, this dump shows the same problem if replayed in SW mode.
I've also included a save state which makes it trivial to reproduce this issue. After loading the state, just move the dog a bit and that's it. Or, if you want the dog to stay in place, then just write a float greater than ~4000 to `0x20aca5b4`, 5000.0 will do. This save state has the incrementing instruction altered so that it increments by `0x100`, and the distance threshold is at around 4000, so writing 5000.0 to the memory at that address will instantly make the dog visibly dirty.

Download: https://workupload.com/file/CBTEWWG2S9M

**Comment by tadanokojin** [comment] 2020-10-04 09:31
Thanks for patch, debug and dumps. I'll take a look when I get a moment.

**Comment by Dogmander** [comment] 2021-01-04 14:20
@jpovixwm Could you give me a quick explanation on how to fix this issue with the vanilla game or whatever, as I'm not really sure how to use cheats or patches in PCSX2 that much.

**Comment by RedDevilus** [comment] 2021-01-04 14:25
Is MTVU disabled?

**Comment by Dogmander** [comment] 2021-01-04 14:30
I have it disabled, yes. As if I have it enabled it seems to hang after the main cutscenes I think.

**Comment by RedDevilus** [comment] 2021-01-04 14:36
MTVU is fixed in 1.7 but it seems to be a CLUT issue from what i hear.

**Comment by Dogmander** [comment] 2021-01-04 14:41
Okay, but all I'm trying to do is just fix the black jake issue

**Comment by refractionpcsx2** [comment] 2021-01-04 14:42
[GSdx32-AVX2clutoffset3.zip](https://github.com/PCSX2/pcsx2/files/5765218/GSdx32-AVX2clutoffset3.zip)
it's a long shot but you could give this version of GSDX a try

**Comment by Dogmander** [comment] 2021-01-04 14:44
What will that version do?

**Comment by refractionpcsx2** [comment] 2021-01-04 15:06
Well, that fixes some CLUT issues, so if it's a CLUT problem, it might stop him turning black. No guarantees though

**Comment by Dogmander** [comment] 2021-01-04 15:30
Okay, I'll try it

**Comment by Dogmander** [comment] 2021-01-05 01:21
Nope, Jake still turns black? Any way I can fix this? 
![image](https://user-images.githubusercontent.com/34490166/103595816-6e8c9780-4eca-11eb-967b-80697ae274d3.png)

**Comment by tadanokojin** [comment] 2021-01-05 01:22
Play in SW until it's fixed or mess about with patches. It's not a clut issue.

**Comment by Dogmander** [comment] 2021-01-05 01:28
How can I use the patches? Is it a cheat code or something?

**Comment by Dogmander** [comment] 2021-01-05 01:30
> Play in SW until it's fixed or mess about with patches. It's not a clut issue.

I'm using the NTSC-U version of the game btw

**Comment by tadanokojin** [comment] 2021-01-05 01:31
This is an issue tracker, it's not really the purview of this issue to explain how the patch system works. Go ask the forums how to use it. This is for tracking the issue and for providing debugging and other information that helps debug it not for asking how to use the emulator.

**Comment by Dogmander** [comment] 2021-01-05 01:36
Okay, sorry. Also, there is another issue that makes Jake have a stripe on his forehead for some reason. You might also want to check this issue out too. 
![image](https://user-images.githubusercontent.com/34490166/103596674-74837800-4ecc-11eb-9bba-8114d57adf4b.png)

One more issue, when loading into the game. The book turns partly black. ![image](https://user-images.githubusercontent.com/34490166/103596582-3c7c3500-4ecc-11eb-90ad-cfe985a88d45.png)

**Comment by tadanokojin** [comment] 2021-01-05 01:38
Thanks I'll keep it in mind. I suspect it's all related.

**Comment by Dogmander** [comment] 2021-01-05 01:39
Yeah, this game has a lot of graphical issues, which is a shame since this is one of my favorite games and these graphical issues are pretty annoying.

**Comment by Dogmander** [comment] 2021-01-19 18:57
Has anyone had any progress resolving this issue?

**Comment by refractionpcsx2** [comment] 2022-02-14 15:52
With the latest master, if you enable Preload Frame and Texture in RT, we're nearly there, but I think the remaining issue is because preload frame is pretty janky

![image](https://user-images.githubusercontent.com/6278726/153898143-f017e0fa-8e3c-4f6d-ac7b-0389d1603e88.png)

**Comment by Dogmander** [comment] 2022-02-14 20:24
> With the latest master, if you enable Preload Frame and Texture in RT, we're nearly there, but I think the remaining issue is because preload frame is pretty janky
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/6278726/153898143-f017e0fa-8e3c-4f6d-ac7b-0389d1603e88.png)
> 
> 
> 
> Edit: Here's a higher resolution screenshot
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/6278726/153898490-802ae46d-0297-41a5-b07d-04d66572cbce.png)
> 
> 

That's definite an improvement, but still not perfect, but it's good to see progress nonetheless

**Comment by refractionpcsx2** [comment] 2022-02-17 23:23
okay, did some messing around, and the mud and Jakes body texture are fine if you set blending accuracy to "Ultra", so there must be a type of blend which is being done on hardware which isn't working so great.

**Comment by refractionpcsx2** [comment] 2022-02-18 12:37
If anybody wants to go ahead and try #5540 it will now work there with basic blending (which is the most ideal).  Of course you still need Preload Frame and Texture in RT, but it looks much better

![image](https://user-images.githubusercontent.com/6278726/154684151-4c36050f-bcb1-4096-ae21-6c6f08efc3c9.png)

Last remaining issue is the texture seam on his head.

**Closed** 2022-02-18 18:00 UTC
Labels: GS, GS: Hardware

**Comment by Levan7** [comment] 2022-03-11 16:30
Still getting this issue on v1.7.2431 build

**Comment by Levan7** [comment] 2022-03-11 18:20
@refractionpcsx2 
It worked thank you and sorry if this information was in the thread and missed.

**Comment by RedDevilus** [comment] 2022-03-11 20:25
When the GS HW fixes gets added, then it will be possible for the GameDB. But a lot of games will need to be reviewed.

**Comment by refractionpcsx2** [comment] 2022-03-11 20:26
yes, wait for #5593 to be merged

**Comment by Dogmander** [comment] 2022-03-11 20:29
👍

**Comment by MiwooTheBroz** [comment] 2022-06-23 15:52
No news about a fix with upscaling?
Texture replacement is possible for the main character?

How to fix this?

**Comment by refractionpcsx2** [comment] 2022-06-23 15:53
Upscaling works, though I think some scales are still problematic, not much we can do about that, just pick another one

**Comment by MiwooTheBroz** [comment] 2022-06-23 15:57
Ok, but this is a hardware mode issue with upscaling. The dog become darker. It's not linked with the sun effect?

Do you have errors concerning this in the console?

**Comment by refractionpcsx2** [comment] 2022-06-23 16:03
No? As long as you don't have manual hw fixes enabled in the GS settings, it should be dealt with.

**Comment by MiwooTheBroz** [comment] 2022-06-23 22:31
> No? As long as you don't have manual hw fixes enabled in the GS settings, it should be dealt with.

Which hw fixes do you use for this game with the last version of PCSX2?

**Comment by refractionpcsx2** [comment] 2022-06-23 22:32
clampModes:
    vuClampMode: 3 # Fixes minor SPS on characters.
  gsHWFixes:
    preloadFrameData: 1 # Fixes bad textures on Jake.
    halfPixelOffset: 1 # Fixes double image.

**Comment by MiwooTheBroz** [comment] 2022-06-24 13:38
![3](https://user-images.githubusercontent.com/87132960/175547290-29e49a1e-4917-49e8-aa4e-db86fe4539ae.png)
![1](https://user-images.githubusercontent.com/87132960/175547298-ddabfd5f-824f-4901-bfac-3475ed635fda.png)
![2](https://user-images.githubusercontent.com/87132960/175547301-b61f4cf9-df0d-4d9b-8773-768cc0eea279.png)



> 

I don't have the numbers but this is my captures. Is this correct?

**Comment by MiwooTheBroz** [comment] 2022-06-24 13:46
Because I search the best configuration .. thank you for your help
![image](https://user-images.githubusercontent.com/87132960/175548965-5185c4a9-3ab8-4e1c-9055-f10c47114627.png)

**Comment by refractionpcsx2** [comment] 2022-10-27 09:26
Just a quick note to say the going black in Smell-o-vision seems to be fixed with #7267

**Comment by MiwooTheBroz** [comment] 2022-11-01 11:11
> Just a quick note to say the going black in Smell-o-vision seems to be fixed with #7267

Hey, thank you, this fix is in the last main branch ? Everything is fixed?

**Comment by refractionpcsx2** [comment] 2022-11-01 11:12
I think so, yep!

**Comment by MiwooTheBroz** [comment] 2022-11-01 11:21
> I think so, yep!
> 
> It's possible certain upscales might still make it explode, I don't know, I didn't test that, but other than that, it should be fine!

Thank you :D
