### ISSUE TITLE
PCSX2 process does not always terminate properly

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1044] opened 2015-12-16 03:12 UTC
PCSX2 1.3.1-20151207111040 - compiled on Dec  7 2015

-"Safest" preset used.

-Plugins used: GSdx, SPU2-X, Lilypad, Linuz ISO/Gigaherz CDVD,rest null plugins

-Plugin settings: Defaults, no settings modifications affect the issue

I've noticed this issue for a few months now, but sometimes the PCSX2 process will remain in Process Hacker/Task Manager after the application is closed. Opening a new PCSX2 window after the fact would not terminate the old one either.

The bug only occurs if the application is closed after a game is opened (if the app is opened and closed WITHOUT loading a game; I was unable to reproduce) After a few trials; I was able to reproduce it easier if the game was running for at least 10-15 sec. Any game ripped to my HDD as an ISO or physical copies were both able to reproduce this issue.

PC Specs: CPU: Intel Core i5-4460@ 3.2Ghz, 4GB Ram
GPU: EVGA Geforce 750 1GB SC
HDD: Western Digital Blue 1TB 7200RPM
OS: Windows 7 64-bit SP1

The game running in the log was Wipeout Fusion - emulog.txt: http://pastebin.com/Ap0sJeDV

Old process - no icon in taskbar
![missingprocess](https://cloud.githubusercontent.com/assets/16314399/11830893/628de7a8-a377-11e5-9f9d-2d4270d96713.png)

Remaining Threads
![remainingthreads](https://cloud.githubusercontent.com/assets/16314399/11830899/87c7073e-a377-11e5-8030-3740fb06a78f.png)

After Restarting (top process is OLD, below that is newer instance)
![dupe2](https://cloud.githubusercontent.com/assets/16314399/11830991/6568881a-a378-11e5-854d-df8f078243fd.png)

**Comment by gregory38** [comment] 2015-12-16 11:23
Could be related to mtvu ? Did you enable it ?

**Comment by MrCK1** [comment] 2015-12-16 22:44
Ah you're right I think the mtvu hack was causing this.

**Comment by willkuer** [comment] 2015-12-17 00:09
Still i dont think this should happen. Hack doesnt mean that potentially the program crashes or locks on shutdown.

The only problem is that you seem to be the first one noticing/getting this issue. And mtvu is used for many years now. Maybe it is on your side...

**Comment by MrCK1** [comment] 2015-12-17 03:06
It probably is something I did. When I tried Win 10 for a few days (absolutely hated it - went back to Win7) I remember having this problem then as well.

**Comment by ramapcsx2** [comment] 2015-12-17 09:57
The problem is known, there should be an issue on it already somewhere.
It's entirely a MTVU issue and yea, we need to fix it asap.

**Comment by gregory38** [comment] 2015-12-17 10:00
Ideally someone shoud attach a debuger and post the stack frame of the remaining threads.

**Comment by willkuer** [comment] 2015-12-17 10:18
Do you know how to reproduce it @ramapcsx2?

I dont think that I ever saw zombie pcsx2 processes...

**Comment by gregory38** [comment] 2015-12-17 10:39
@refractionpcsx2 hit this issue couple of months ago.

**Comment by gregory38** [comment] 2015-12-17 10:40
By the way, I added a lock/wait somewhere in mvu to avoid a crash on linux. Maybe it doesn't play nicely on windows.

**Comment by refractionpcsx2** [comment] 2015-12-17 10:44
I doubt it was that, this hasn't been right for a very long time.

**Comment by vsub** [comment] 2015-12-17 16:25
It usually happens on ZoE2 when the vram usgage becomes too high or when I use very high scaling mode...which actually also increases the vram usage

**Comment by refractionpcsx2** [comment] 2015-12-17 16:28
It can happen if you run FFX and as soon as it recompiles the VU program as well. It's just something in the thread control isn't working right.

**Comment by ramapcsx2** [comment] 2015-12-19 11:38
The problem should be resolved now. Can someone verify?

**Comment by MrCK1** [comment] 2015-12-21 14:31
I tried it a few days ago and had no problems.

**Comment by ramapcsx2** [comment] 2015-12-21 21:30
Seems fixed for me as well :)

**Comment by MrCK1** [comment] 2015-12-29 23:33
So it turns out this issue might be back. I'm getting multiple processes in Task Manager again.  I'm not sure what brought it back; but right now I'm on build v1.3.1-1588-g191453d

**Comment by ramapcsx2** [comment] 2015-12-30 15:23
Still only with MTVU?

**Comment by vsub** [comment] 2016-05-02 09:03
I just found 100% reproducible method...and no mtvu is not enabled(in fact,all speedhacks are disabled)

I'm using the latest beta(v1.5.0-dev-698)
1.Use fast/full booth while CDVD=>Plugin is selected(gigahertz with no game in the dvd drive...this will go to the browser)
2.Switch to iso and use Swap not reset

When you try to close pcsx2 after that(it doesn't have to be immediately,you can close it at any time),the process will stay in the task manager

**Comment by refractionpcsx2** [comment] 2016-05-02 10:26
Without mtvu?? I don't think I've ever seen that happen.  Will reopen this for now then

**Comment by FlatOutPS2** [comment] 2016-05-02 10:38
You don't need to use swap. Just boot any game from DVD without having a DVD on the drive and afterwards it won't kill the process.

**Comment by MrCK1** [comment] 2016-05-02 12:59
I remember seeing in Process Hacker that when Gigaherz can't read a disk (fails to set spindle speed) that was causing PCSX2 not to terminate as well (the plugin was still using CPU cycles)

**Comment by turtleli** [comment] 2016-06-20 23:15
I took a brief look at this, using the CDVD plugin with no disc method to reproduce it. Thread stack trace:
```
ptw32_mcs_lock_release(ptw32_mcs_node_t_ * node) Line 213
pthread_key_delete(pthread_key_t_ * key) Line 106
Threading::BaseTlsVariable<FastFormatBuffers>::KillKey() Line 165
GlobalBufferManager<Threading::BaseTlsVariable<FastFormatBuffers>>::~GlobalBufferManager<Threading::BaseTlsVariable<FastFormatBuffers>>() Line 137
```
Basically it ends up stuck at `WaitForSingleObject(e, INFINITE);` when the TLS buffers are being cleaned up. Investigating further I did
```
diff --git a/common/src/Utilities/FastFormatString.cpp b/common/src/Utilities/FastFormatString.cpp
index 863fb9b..68a1a8b 100644
--- a/common/src/Utilities/FastFormatString.cpp
+++ b/common/src/Utilities/FastFormatString.cpp
@@ -232,13 +232,14 @@ uint format_that_unicode_mess( CharBufferType& buffer, uint writepos, const wxCh
 
 CharBufferType* GetFormatBuffer( bool& deleteDest )
 {
+#if 0
 	deleteDest = false;
 	if (buffer_is_avail)
 	{
 		if (m_buffer_tls.Get()->HasFreeBuffer())
 			return &m_buffer_tls.Get()->GrabBuffer();
 	}
-
+#endif
 	deleteDest = true;
 
 	return new CharBufferType(2048);
```
and the problem disappeared. I even removed the code to fix the MTVU issue and PCSX2 still cleans up properly. So it seems the usage of the TLS buffers in the FastFormat* stuff is the root cause (but don't ask me why it causes an issue, I don't know).

**Comment by ramapcsx2** [comment] 2016-06-21 14:33
Nice find!
So can we do without TLS buffers?

**Comment by turtleli** [comment] 2016-06-21 15:24
Maybe. It's there to avoid memory allocation overhead. I'll open a PR for it at some point and we can see if there's any noticeable difference in performance.

**Closed** 2016-06-29 12:13 UTC
Labels: Core, Voodoo
