### ISSUE TITLE
[Feature Request]: Add M3U Support

### ISSUE THREAD

**Issue by gabrieljtaylor** [PCSX2/pcsx2#7640] opened 2022-12-20 23:54 UTC
### Description

Add support for M3U playlists for multi-disc games, including the ability to load discs via an M3U playlist and the ability to swap discs between those listed in the M3U playlist.

### Reason

1. The use of M3U files for multi-disc games is essentially a standard among emulators for disc-based systems, which this emulator currently doesn't support, causing user confusion and usability issues.
2. While the Big Picture mode may make it "[arguably less useful](https://github.com/PCSX2/pcsx2/issues/6696#issuecomment-1269621970)" for users who use the native PCSX2 interface, anyone who uses a frontend like EmulationStation or Steam (via Steam ROM Manager) won't be using Big Picture mode and thus need a better solution for changing discs without breaking out a keyboard & mouse (or in the case of Steam Deck usage, modifying or switching controller settings) _just_ to change discs.

I realize this isn't the top of your priority list, but I'm submitting this request in hopes that it at least stays on the priority list and that others who are interested in the feature have a place to express their support.

### Examples

Duckstation, PCSX ReArmed, Dolphin, Beetle, and more all support M3U files.

**Comment by F0bes** [comment] 2022-12-20 23:56
Duplicate of #6696

**Closed** 2022-12-20 23:56 UTC
Labels: Enhancement / Feature Request
