### ISSUE TITLE
King of Colosseum Green - hangs on opening

### ISSUE THREAD

**Issue by mostdaysarebaddays** [PCSX2/pcsx2#3448] opened 2020-06-07 17:10 UTC
***PCSX2 version:***
``(For example, stable build v1.6.0 (or) development builds v1.7.0-dev-xxx)``

1.6.0. Works fine 1.4.0.

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSdx plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

Default plugins, no changes.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``

Game hangs on opening white screen

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``

Boot game, watch hang

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

Works in 1.4.0

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``

**Comment by lightningterror** [comment] 2020-06-07 17:19
See if you can track down which 1.5 build introduced the regression, it will help a lot.
https://buildbot.orphis.net/pcsx2/index.php?m=fulllist

**Comment by someother1n** [comment] 2020-06-07 20:47
Tested this real quick, seems like EE Timing hack should fix this. May need to be added as an autofix.

SLPM_65206.  crc DBDE0864    Tested on 1.6 and 1.7.

**Comment by MrCK1** [comment] 2020-06-07 20:52
We'd prefer to find the broken build first rather then add a game fix. Would you be able to make a blockdump using the Debug menu for us?

**Comment by someother1n** [comment] 2020-06-08 00:25
Sure I can do that, when I get access to my regular PC hopefully later. In the meantime, earlier I found the build that regressed the game. Obviously tested without using the EE hack:

![builds](https://user-images.githubusercontent.com/60489087/83983488-e0810c00-a8fc-11ea-927f-3d840a37d7f4.jpg)

**Comment by MrCK1** [comment] 2020-06-08 00:47
Sorry on second thought we won't need the blockdump because another tester has it. Can you run the game again with the GIF FIFO hack enabled?

**Comment by mostdaysarebaddays** [comment] 2020-06-08 10:43
Can confirm EE Timing Fix fixes it, GIF FIFO does not fix it.

**Comment by RedDevilus** [comment] 2020-06-25 18:42
Should be fixed if it only needs EE Timing.

**Closed** 2020-06-27 14:44 UTC
Labels: GameDB, Regression
