### ISSUE TITLE
[BUG]: FFX FMV Flickering

### ISSUE THREAD

**Issue by larwood** [PCSX2/pcsx2#5244] opened 2022-01-01 11:17 UTC
### Describe the Bug

Most but not all FMVs in Final Fantasy X flicker when the Renderer configured is OpenGL.  When the Renderer configured is Software there is no issue.

Once the FMV flicker begins if I quickly toggle the Renderer with F9 from OpenGL -> Software -> OpenGL the issue no longer occurs.

I have not yet watched all 50 FMVs in the The Sphere Theater (Luca Sphere Theater) but the issue does not appear to trigger there.  Perhaps becuase I have to press X to begin the FMV so the transition is different?

I have tested on my Notebook and Desktop with different hardware and the issue is present on both.

There is no difference in behaviour if I load from a Memory Card save or from a Save State.

I have shared logs and a GS dump.

A short 17 second video
https://www.youtube.com/watch?v=11W2vXuybwU

Forum discussion
https://forums.pcsx2.net/Thread-Final-Fantasy-X-Internal-Resolution-Scaling-Incorrect-During-Gameplay-Cutscenes?page=2

### Reproduction Steps

Load the game from either Memory Card save or Save State and wait for transition from in game play to FMV.

The majority but not all FMVs will exhibit the flickering behaviour.

### Expected Behavior

Game play to FMV transition occurs with no flickering.

### PCSX2 Revision

v1.7.2184

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i7 8750H

### GPU

NVIDIA GeForce GTX 1060

### GS Settings

Fresh install no changes from defaults

### Emulation Settings

Fresh install no changes from defaults

### Logs & Dumps

GS dump
https://drive.google.com/file/d/1VsfQnN5RrWuSIebTjE_q79dTrFtGblBz/view?usp=sharing

Logs
https://drive.google.com/file/d/1Jm_py7zY8s99x44UNyBKtvx0GgrNoPws/view?usp=sharing

**Comment by refractionpcsx2** [comment] 2022-01-01 14:03
I think this has been around for at least a while, but I suspect it will happen randomly depending on what's in VRAM.  Any chance you could check back to when it started happening, if it used to not be an issue?

Of course don't check every build in turn, jump back to 1.7.2000 or something, see if that works, if not, try 1000, then narrow it down etc.

**Comment by prafullpcsx2** [comment] 2022-01-01 19:10
Looks like you forgot to upload the savestate and memory card save you were talking about in first post.

**Comment by larwood** [comment] 2022-01-02 04:12
@prafullpcsx2 here is a link to a memory card and save state.  The memory card has two saves.  The first is at Lake Macalania where you can walk to the lake to chat with Yuna.  It takes a while to get to the FMV so that is what the Save State is for.  The second save I have purchased all the Movie Spheres so you can visit Luca Theatre to view them all but so far I have not triggered the issue here.

https://drive.google.com/file/d/1f2sU6EAJsgeCaXW6C_n6aFVQjKmxm6hg/view?usp=sharing

**Comment by larwood** [comment] 2022-01-02 04:18
@refractionpcsx2 I did test v1.7.2003 back in late November 2021 as part of the discussion in the PCSX2 Forums and the issue was occurring there as well.

Looking at the Releases page I can't view any v1.7.x versions older than v1.7.2003.  I'm happy to test if you can direct me to a location to download older versions of the v1.7.x branch.
https://github.com/PCSX2/pcsx2/releases?page=19

**Comment by prafullpcsx2** [comment] 2022-01-02 07:08
I tested this today and it seems to be a problem with using savestates. If I do a fresh boot then the problem doesn't occur. If I load the savestate first time the problem doesn't occur. The flickering starts when you use the savestate the second time.

**Comment by larwood** [comment] 2022-01-02 09:48
100% not a problem with using savestates. If you load up the memory card save from Lake Macalania and don't use the Save State it will flicker but you will have to wait 5 minutes or so for the scene with Yuna to play out.

**Comment by prafullpcsx2** [comment] 2022-01-02 09:57
Load it 4 times. Didn't flicker even once

**Comment by larwood** [comment] 2022-01-02 11:02
Interesting. I had multiple instances throughout the game of FMVs flickering with OpenGL. There were some that didn't but the majority did. I can reproduce the flickering 100% of the time with the lake scene both from the Save State and from the Memory Card save. With the software renderer no problems ever.

To clarify regards the save state. I didn't use save states at all through this game. I only created the one I uploaded to save the Devs some time as that lake scene is quite long before the FMV plays.

**Comment by prafullpcsx2** [comment] 2022-01-02 14:24
On further testing this seems to be a strange bug.

Native- bug happens everytime.
2x Native + Conservative buffer - bug happens everytime.
Rest all - bug happens only on using savestate twice.

I assume you were using one of the first two options?

Also if you go into graphics settings the flickering stops automatically (even if you don't change any option).

**Comment by larwood** [comment] 2022-01-02 23:24
My testing was using Native. A clean install of PCSX2 with no modifications.  I just dropped in the bios, memcards and iso files.

I can confirm your discovery that just entering the Graphics settings and exiting with no actual changes stops the flickering.

Additionally I found an easier way to test.  Load the 'Luca Stadium - Main Gate' save.  Walk up to the Save Sphere and select 'Board airship'.  Once on the airship talk to the Captain and select Sin from the destination list.  This loads a short FMV which exhibits the flickering behaviour for me 100% of the time.  Once you arrive at Sin you can walk up to the Save Sphere and board the airship again then repeat this loop as many times as you like.

**Comment by larwood** [comment] 2022-01-03 00:28
I tested using AetherSX2 and the FMV flickering occurs in that app as well. This is expected as I believe the code is shared between the two projects.

**Comment by F0bes** [comment] 2022-01-03 00:38
> I believe the code is shared between the two projects.


Yup

**Comment by larwood** [comment] 2022-01-10 10:21
Testing the new option 'Use Software Renderer for FMVs' in AetherSX2 allows both the Lake Macalania and Sin FMVs to play with no flickering.

**Comment by refractionpcsx2** [comment] 2022-01-10 10:21
We have that option back too..

**Comment by larwood** [comment] 2022-01-10 12:13
OK yes I see that option now. I must have missed that commit notes email.

I tested out v1.7.2218 with both FMVs by enabling the option 'Use Software Renderer for FMVs' under Games Fixes.  The FMVs still flicker if I have configured 'Graphics Settings > Renderer > Automatic'.  The renderer being used in this case is 'OpenGL HW' according to the Window Title.  However if I specifically set the renderer 'Graphics Settings > Renderer > OpenGL' the FMVs run with no flickering.

**Comment by RedDevilus** [comment] 2022-01-15 01:22
I wonder if Enabling Large Framebuffer / Disable Conservative Framebuffer Allocation also helps with the issue.

**Comment by gamerk2** [comment] 2022-02-11 04:38
I did some testing during my recent FFX-2 playthrough, since I ran into the same issue.  Looking back at my notes from my testing using v1.7.2003 (I forgot to report the issue since IRL stuff happened):

-)All FMVs are affected; problem most easily replicated by watching the opening cutscene, so it's not a savestate related issue
-)Reproduced on both DX11/OGL backends
-)Not affected by ANY graphical settings I tested with in either graphics mode
-)Software Renderer not affected

Also, this is a possible seizure risk* so it should probably get looked at ASAP.  I didn't bisect when the problem started (IRL stuff) but I can do so this weekend if no ones looked at this yet.

*Not a doctor, but I have to imagine this is a problem.

**Comment by AhayriSG** [comment] 2022-07-14 00:10
Rocky: Legends (SLUS-20890): same FMV flickering problem with HW renderer.

**Comment by refractionpcsx2** [comment] 2022-07-24 09:59
@AhayriSG did you even try it on this PR before posting that? cos two of us have tested it now and it works fine.

**Comment by refractionpcsx2** [comment] 2022-07-24 10:20
why do you have Deinterlacing set to "none"?

**Comment by AhayriSG** [comment] 2022-07-24 10:54
> why do you have Deinterlacing set to "none"?

bc testing with "Samsung SyncMaster 1100MB"

**Comment by refractionpcsx2** [comment] 2022-07-24 11:06
> > why do you have Deinterlacing set to "none"?
> 
> bc testing with "Samsung SyncMaster 1100MB"

That has nothing to do with it? Your monitor might not be interlaced, but the PS2 is. Turning that off tells the game that it's not interlaced and causes it to try and allocated too much height for the picture and it gets confused.

**Comment by AhayriSG** [comment] 2022-07-24 11:30
> > > why do you have Deinterlacing set to "none"?
> > 
> > 
> > bc testing with "Samsung SyncMaster 1100MB"
> 
> That has nothing to do with it? Your monitor might not be interlaced, but the PS2 is. Turning that off tells the game that it's not interlaced and causes it to try and allocated too much height for the picture and it gets confused.

Oh okay my bad. Thanks.

**Comment by refractionpcsx2** [comment] 2022-10-20 14:35
This is already fixed in master in https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2800 , so closing

**Closed by refractionpcsx2** 2022-10-20 14:35 UTC
Labels: Bug, Workaround Possible
