### ISSUE TITLE
[BUG]: Qt applying wrong value for fullscreen mode

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#7320] opened 2022-11-03 06:56 UTC
### Describe the Bug

The global PCSX2.ini is giving the wrong value than what's on the GUI.
Global is at Borderless but the ini is saying `FullscreenMode = 2560 x 1080 @ 60.000000 hz`

### Reproduction Steps

- Change to Direct3D11 or 12 (Global)
- Change from Borderless to any other value (Global)
- Launch random game
- Set it back to Borderless (Global)
- Open Per-game setting and look at Borderless seeing it has wrong value (Per-game)
- Restarting PCSX2 doesn't fix it
- Change renderer to Automatic (Optional)
- Check per-game settings

Example:
![image](https://user-images.githubusercontent.com/24227051/199662276-d7cfb8c2-585a-4ecd-9aeb-2bb0c622bc6e.png)

### Expected Behavior

Give the correct value. Keep in mind his is a non-existing value in OpenGL and Vulkan, so it will default correctly to borderless so it's a visual GUI error.

### PCSX2 Revision

v1.7.3514

### Operating System

Windows 10 (64bit)

**Comment by JordanTheToaster** [comment] 2023-03-16 14:03
Looks fine here.

![image](https://user-images.githubusercontent.com/80843560/225641635-fab7f170-06a4-41db-a430-81eefe6943fc.png)

**Comment by refractionpcsx2** [comment] 2023-03-16 14:08
Can't reproduce here either, can you check again?

**Comment by RedDevilus** [comment] 2023-08-17 01:56
Still an issue.
Step 1: Change global renderer to D3D11 or D3D12
Step 2: Change borderless to any random exclusive fullscreen value
Step 3: Launch random game
Step 4: Reset global settings back to Automatic/Default values (Undoing Step 1, Don't undo Step 2) while game is running
Step 5:
![image](https://github.com/PCSX2/pcsx2/assets/24227051/20ce045a-aae1-4412-aa37-ae9174364af2)
Step 6: Restart PCSX2 doesn't fix it.

(Similar to how if you enable multitap ports and OSD still sees those specific enabled ports even after closing multitap 1 and 2)

**Comment by kamfretoz** [comment] 2024-03-06 13:56
Can't reproduce, v1.7.5596

![image](https://github.com/PCSX2/pcsx2/assets/14798312/1d7008cc-048e-48ea-a0a5-71461a26e90b)

**Comment by kamfretoz** [comment] 2024-10-26 13:59
Still can't repro, PCSX2 v2.1.227

![Image](https://github.com/user-attachments/assets/7ca1d567-01e6-420b-a488-2bd3bab9ff61)

**Comment by Mrlinkwii** [comment] 2024-10-26 14:04
Since this hasn't been able to be reproduced, I'm going to go ahead Ans close this issue :)

**Closed** 2024-10-26 14:04 UTC
Labels: Bug, GUI/Qt
