### ISSUE TITLE
[BUG]: Valkyrie Profile Audio Issue

### ISSUE THREAD

**Issue by knight-ryu12** [PCSX2/pcsx2#6545] opened 2022-06-29 22:37 UTC
### Describe the Bug

Intro animation will desync from voiceover if user enables 1080i D3 mode.
This will never happen on all other mode.

### Reproduction Steps

1. Enable D3 mode using secret commands.
2. Watch FMV cutscene.

### Expected Behavior

Audio should not desync.

### PCSX2 Revision

v1.7.3033

### Operating System

Windows 11

### CPU

Ryzen 7 5800H

### GPU

RTX 3060Ti

### GS Settings

SW Mode Used. Happens both HW and SW.

### Logs & Dumps
[video.7z](https://drive.google.com/file/d/1qwb9kp9iBI22ZIxgWIcVFFd8P7Lxf_IA/view?usp=sharing) 
Containing three MP4s recorded.

**Comment by refractionpcsx2** [comment] 2022-06-29 22:38
Yes, this is known, happens quite badly in the PAL version as well. Usually lowering the EE cycle rate by a couple of notches will keep it in sync.

**Comment by knight-ryu12** [comment] 2022-06-29 22:40
Better to leave a note, ~~I think 1080i is meme anyway, but~~ and fix it

**Comment by trostboot** [comment] 2022-07-01 17:56
Related/duplicate of?: https://github.com/PCSX2/pcsx2/issues/1634

**Comment by refractionpcsx2** [comment] 2022-07-01 17:58
Yes and no, the other is PAL but we can mention it there.

**Closed by refractionpcsx2** 2022-07-01 17:58 UTC
Labels: Bug, SPU2, Timing
