### ISSUE TITLE
Request: Remember CRC hack for OpenGL and Direct3D separately

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#1815] opened 2017-02-12 04:47 UTC
Okay another request , this time to remember the value for crc hack for each render (Direct3D and OpenGL precisely) , this will come in handy when switching between Direct3D and OpenGL render , you won't need to go through the trouble of changing them as well when switching Hardware renders.

It's not a huge issue but I find it troubling that we need to switch to Full for Direct3D or Partial for OpenGL each time we switch renders.

**Comment by FlatOutPS2** [comment] 2017-02-12 11:01
Duplicate of https://github.com/PCSX2/pcsx2/issues/1722

Also see the active Pull Request; https://github.com/PCSX2/pcsx2/pull/1686

**Closed by FlatOutPS2** 2017-02-12 11:01 UTC

**Comment by ssakash** [comment] 2017-02-13 12:16
@FlatOutPS2 : This isn't a duplicate of #1722. The request made in #1722 was to default to ``Partial`` level when the best renderer is detected as OpenGL at the initial fresh startup of the GSdx plugin settings. This issue seems to request for something totally different, like having two multiple variables for storing CRC hack level state based on renderers.

**Comment by FlatOutPS2** [comment] 2017-02-13 12:26
They use different words, but they basically ask for the same thing.
