### ISSUE TITLE
Dark Cloud and more not working on openGL with git pcsx2

### ISSUE THREAD

**Issue by twitchplayskh** [PCSX2/pcsx2#1460] opened 2016-07-13 12:12 UTC
i love Dark Cloud 1 so i had a go at playing it on pcsx2 and yes it is on ps4 but i make twitch plays streams with ps2 games so i need it on pc,
the problem is with opengl all i have is a white screen with game sound http://imgur.com/a/qQsGV
my pc hardware specs not the best but work ok for a lot of ps2 games http://imgur.com/a/t2cAD
pcsx2 settings are set to default  i am on Revision a37cd40 for the git on the website http://imgur.com/a/Xl0PH

yes my card is old but it all work on the stable build

**Comment by mirh** [comment] 2016-07-13 12:31
Git pcsx2, not dev, that's another thing. 
Said this, it's a known problem with AMD driver (and basically the reason you should use DX11 there)
It never hurts to be sure of where the regression happened though. 
So.. could you [bissect](http://buildbot.orphis.net/pcsx2/index.php?m=fulllist) the issue?
I'd try to check if this change was between dev-707 and 708 for starters if I were you.

**Comment by twitchplayskh** [comment] 2016-07-13 12:44
well when i run games on v1.40 i have no white screen and it all work but if i go and run it on pcsx2 from the git page on the website i have this bug is there a thing i can send like a log or do you need my settings

**Comment by mirh** [comment] 2016-07-13 12:49
Usually it's just about taking a gs dump (ctrl+shift+f8) and waiting for gregory magician to check it. 
But as I said, the problem is probably with how stupid gpu driver work. 
Sooo, go to git page and try to check between which builds this regression happened.

**Comment by twitchplayskh** [comment] 2016-07-13 13:27
did a lot of testing and v1.5.0-dev-848-g5672d2b	 works ok but all the builds after that  have the  white screen on opengl hope this helps

**Comment by FlatOutPS2** [comment] 2016-07-13 15:44
What's your GPU driver version?

**Comment by twitchplayskh** [comment] 2016-07-13 17:02
all my GPU info http://imgur.com/a/SU2wy

**Comment by mirh** [comment] 2016-07-13 17:11
Mhh... That looks like system provided W10 driver. 
Try [16.2.1](http://support.amd.com/it-it/download/desktop/legacy?product=legacy3&os=Windows+10+-+64)

**Comment by twitchplayskh** [comment] 2016-07-13 17:12
ok let me give that a go

**Comment by twitchplayskh** [comment] 2016-07-13 17:51
wow it works thank you a lot i hope this will give me a bit of a fps boost as well Kappa

**Comment by mirh** [comment] 2016-07-13 23:36
@gregory38 Is this just 179681ef18eb9734585817eab1a6ce04cdb350cd kicking in then?

**Comment by twitchplayskh** [comment] 2016-07-14 07:35
i bet its to hard to code in but is there not a way to tell people if there drivers are out of date like a pop up message

**Comment by gregory38** [comment] 2016-07-14 07:46
Don't you have some kinds of auto-update in Steam?/ Driver?/ Windows update? already.

**Comment by twitchplayskh** [comment] 2016-07-14 07:59
yes but it makes you dl the update checking software from like amd and nvidia no link to the dl you need xd

**Comment by mirh** [comment] 2016-07-14 08:08
There won't ever be a newer driver for that, peace. 
If any, somebody in some forum may tinker/make a mushup. 

Still, I'm wondering if this is just the workaround kicking in, or actual driver having fixed something.

**Comment by gregory38** [comment] 2016-07-14 08:13
I disabled SSO on recent enough driver.

**Comment by gregory38** [comment] 2016-07-14 09:32
shall we close the issue if it was only an old driver issue.

**Comment by mirh** [comment] 2016-07-14 09:46
I'm still wondering why if "broken" version should be anything before 16.5, stil you get an improvement with 16.2 :p

**Closed** 2016-07-16 07:54 UTC
Labels: GSdx: Hardware, Upstream | External
