### ISSUE TITLE
[GSdx HW] Fatal Frame - Invisible Ghosts / General camera issues

### ISSUE THREAD

**Issue by Ryudo300** [PCSX2/pcsx2#1024] opened 2015-12-07 13:26 UTC
- **PCSX2 version:** GIT 1.3.1-1474 (And pretty much any PCSX2 version)
- **PCSX2 options:** Defaults, no settings modifications affect the issue
- **Plugins used:** GSdx, SPU2-X, Lilypad, Gigaherz CDVD,rest null plugins
- **Plugin settings:** Defaults, no settings modifications affect the issue
- **Description:** Fatal Frame makes use of a camera to target and attack ghosts, or capture random ghosts on camera appearing throughout the game. This works perfectly fine in software mode, but when you go into GSdx hardware mode, the ghosts become invisible. This is a very old bug that has been around since pretty much the beginning of PCSX2 and still isn't correctly fixed. 
  
  There was a point where the ghosts were visible again during camera mode, but they were unable to be targeted. Even if you were spot on aiming at the ghost, the game would not register it as being targeted. It seems in recent revisions that this was fixed again, and you can target the ghosts again, but this results in the ghosts being invisible again when you try to attack.
- **How to replicate:** Just use your camera during any ghost interaction and you'll see that the ghosts are invisible. (Remember to also note the other bug I described of when there were revisions where the ghosts were visible, but just couldn't be targeted. So it's quite honestly two bugs at once that seem to coincide with each other.)
- **Last known version to work:** Camera mode never worked correctly. It was always one bug or the other.
- **PC specifications:**
  - **CPU**: Intel Core i5-4670K @ 3.4Ghz 
  - **GPU:** ATI Sapphire Radeon R9 280 3GB 
  - **OS:** Windows 7 Ultimate x64 (SP1)
- **Other comments:** If necessary I can dig up some revisions which had the ghosts visible, but with the other bug where you are unable to actually target and hit the ghosts. I think if we can just make the ghosts visible though from the current revision it should all-around fix hardware mode hopefully. There's still some other minor bugs with the camera in hardware mode, but these ones that I reported here truly stand out due to the fact that they essentially completely break the game in hardware mode.

**Comment by gregory38** [comment] 2015-12-08 09:38
I'm a bit lost. Could you confirm me that current behavior is the same as 1.2.
Did you try the accurate date & depth option in the openGL hw renderer? What is the status when those options are enabled?

**Comment by Ryudo300** [comment] 2015-12-09 02:57
Yeah it's the same behavior in 1.2.

And I never tried OGL before, which I did just now, and it actually works fine in OGL.. the ghosts show up. And I didn't even need to set Accurate Date or Depths. Using Basic Blending Accuracy.

So it seems to be completely restricted to D3D Hardware. (Software mode is obviously fine as well)

**D3D Hardware Mode - No ghost visible 1**
![fatal frame - hardware mode no ghost 01](https://cloud.githubusercontent.com/assets/10039778/11675266/93564398-9e28-11e5-96c1-b0bdbfa0bed6.png)

**D3D Hardware Mode - No ghost visible 2.**
![fatal frame - hardware mode no ghost 02](https://cloud.githubusercontent.com/assets/10039778/11675264/9355c9d6-9e28-11e5-9cd4-3720c0b9c426.png)

**D3D Software Mode - Ghost is visible**
![fatal frame - software mode ghost 01](https://cloud.githubusercontent.com/assets/10039778/11675263/93557fee-9e28-11e5-93cf-4dea983477ca.png)

**OGL Mode - Ghost is visible**
![fatal frame - ogl mode ghost 01](https://cloud.githubusercontent.com/assets/10039778/11675265/9355d732-9e28-11e5-8fc5-f36fafa5e739.png)

**Comment by gregory38** [comment] 2015-12-10 10:00
```
Using Basic Blending Accuracy.
```
Oh interesting, which level exactly? the first one. Very high probability that it is related to color bit masking (aka fbmask)

**Comment by Ryudo300** [comment] 2015-12-12 19:00
These were the settings used during the OGL screenshots.

![bandicam 2015-12-12 19-58-55-559](https://cloud.githubusercontent.com/assets/10039778/11763437/d5581b10-a10a-11e5-80f5-3f6b434aac59.png)

**Comment by gregory38** [comment] 2015-12-12 19:53
Ok. So it is likely related to bitmasking.

**Comment by Ryudo300** [comment] 2015-12-15 22:17
Not sure what is up with this. Decided to play again today, and now I apparently can't target ghosts. They show up, but they can't be targeted. So it seems it only works randomly from time to time in OGL.

**Comment by gregory38** [comment] 2015-12-28 10:36
Ok. Potentially the remaining issue is related to depth support. Current options don't emulate the depth at 100%. Typically the reading of depth from the EE isn't yet implemented.

**Comment by FlatOutPS2** [comment] 2016-04-20 15:17
This bug is still active in latest git version.
Though I've had no targeting issues in the PAL version. Switching to software mode and back to hardware shows the ghosts in D3D and OGL modes.

**Comment by Ryudo300** [comment] 2016-04-27 12:23
Targeting is still an issue in the NTSC version. I played the game again for a bit last a few days ago.

Same goes for invisible ghosts. Temporary fix is still switching between software and HW modes, but this only lasts a very short time before it breaks again during playing.

**Comment by gregory38** [comment] 2016-04-27 12:45
Was the preload hack tested? Which level of CRC, dunno if GSdx have some for this game?

**Comment by FlatOutPS2** [comment] 2016-04-27 13:38
Does targeting fail on invisible ghosts too, or only when the temporary fix is used?

**Comment by refractionpcsx2** [comment] 2016-04-27 16:02
The targeting has never worked in HW mode properly I don't think. It basically bitmaps the screen and uploads if (via reversed VIF FIFO) to the PS2 and it then checks if you've hit the ghost.

software mode was fixed to make this work  but hw mode has always been screwed.

**Comment by gregory38** [comment] 2016-04-27 16:03
What does the game read the depth buffer or the color buffer?

**Comment by refractionpcsx2** [comment] 2016-04-27 16:04
I'd presume from the fact it worked in software and not hw, it will be the depth, as that was the only thing that wasn't available in hw mode.

**Comment by gregory38** [comment] 2016-04-27 16:06
But depth reading is working on openGL now. So maybe there is a bug on some depth format reading. Or it fails to understand which texture is read. For example depth could be located at 0x1000 but game does the read with a small offset at 0x1200.

**Comment by FlatOutPS2** [comment] 2016-04-27 16:06
> The targeting has never worked in HW mode properly I don't think. 

It did work when I tried the PAL version(for the freezing at the final boss bug).

**Comment by refractionpcsx2** [comment] 2016-04-27 16:08
I don't think it "really" worked, I think you could aim anywhere and it pretended to hit the ghost.

**Comment by gregory38** [comment] 2016-04-27 16:12
I think it would be easier to debug the invisible ghost issue first. It really feel like a wrong depth buffer somewhere.

**Comment by gregory38** [comment] 2016-04-27 16:40
The gs dump request
* First one with the invisible ghost
* The same after toggling F9

This way I could compare the diff. Let's first fix the rendering issue. If game is badly rendered, the reading by the EE will be wrong.

**Comment by FlatOutPS2** [comment] 2016-04-27 16:46
> I don't think it "really" worked, I think you could aim anywhere and it pretended to hit the ghost.

No, that definitely wasn't the case for the PAL version. Aimed next to a ghost didn't damage it, and hitting in the center got more damage.

I just retested the game(last attempt was just before 1306 PR was created), and ghosts are now visible. And still no issue with targeting.

**Comment by gregory38** [comment] 2016-04-27 17:15
So it seems invisible ghost was due to a bad depth format. @Ryudo300 could you confirm the behavior on latest git. It ough to work on both PAL/NTSC version.

@FlatOutPS2 
Hum, could you post your GSdx.ini. Maybe it depends on a special option.

**Comment by FlatOutPS2** [comment] 2016-04-27 17:21
I didn't use a special option. I used a fresh PCSX2, with both OpenGL and D3D11 and scaling set to 3x.

**Comment by gregory38** [comment] 2016-04-27 17:35
So maybe @Ryudo300 uses a bad one ;)

**Comment by refractionpcsx2** [comment] 2016-04-27 17:40
Hmm, are you sure it works with scaling?

**Comment by FlatOutPS2** [comment] 2016-04-27 17:49
I used scaling and it worked, so yes?

**Comment by gregory38** [comment] 2016-04-27 17:56
Ref which version do you have? If it works now on pal, we can conclude the bug is likely related to depth.

**Comment by Ryudo300** [comment] 2016-04-27 17:59
I'll fetch the latest pcsx2 and give that a try in a bit. Currently not in front of my computer so can't test it yet

**Comment by Ryudo300** [comment] 2016-04-27 18:54
![pcsx2 2016-04-27 20-53-38-513](https://cloud.githubusercontent.com/assets/10039778/14864433/29f34a6c-0cba-11e6-9cf7-9082a109cddd.png)
Not exactly a major improvement..... this is what OGL looks like now. Is there some specific settings I need to use for this game in OGL?

**Comment by FlatOutPS2** [comment] 2016-04-27 18:58
Welcome to the world of AMD driver bugs. :p 
You need to set Blending Unit Accuracy to Ultra to avoid. It is not a PZ/FF issue.

**Comment by Ryudo300** [comment] 2016-04-27 19:03
Ok the ghosts were visible this time, and I was able to target. But I honestly can't play long enough in this setup. I'm getting 15~20 FPS running it on Ultra. This is near impossible to play in.

**Comment by FlatOutPS2** [comment] 2016-04-27 19:10
Really? I'm pretty sure I had double that fps, but my GPU is inferior to yours. I thought it was pretty playable for being on ultra.

You can use DX11 to test it as well.

**Comment by Ryudo300** [comment] 2016-04-27 19:12
Maybe different drivers? I might have a crappier driver version. I'm running on Crimson 16.3.2 atm

**Comment by gregory38** [comment] 2016-04-27 19:14
It depends mostly on the cpu perf. I'm sorry for you but it is a good news for me. One more game checked ;)

**Comment by Ryudo300** [comment] 2016-04-27 19:15
Just tested DX11.

Ghosts were invisible, but can be targeted at least so far.

**Comment by FlatOutPS2** [comment] 2016-04-27 19:22
> Ghosts were invisible, but can be targeted at least so far.
Were all ghosts invisble? Cause I only tested to the first ghost battle from the start with DX11, and they were all visible(without ever switching renderer).

**Comment by Ryudo300** [comment] 2016-04-27 19:24
Two ghost encounters so far, what's weird is that a 'friendly' ghost did show up after switching maps. (The ones where you only have a few seconds to take a photo of).

**Comment by FlatOutPS2** [comment] 2016-04-27 19:32
Just tried again and now battle ghosts were invisible again in both DX11 and OpenGL, so it's not completely resolved. All the 'friendly' ghosts were still visible as you described as well.

Performance is 30-40fps with some dips to low-mid 20s(which might be because I'm playing from DVD).

**Comment by gregory38** [comment] 2016-04-27 20:01
Dx11 still doesn't support depth read/write so it is likely still broken.

**Comment by refractionpcsx2** [comment] 2016-04-27 20:16
> Ref which version do you have?

I don't, I have Fatal Frame 3 (J), oh and Project Zero 3 (which is the PAL version)

**Comment by FlatOutPS2** [comment] 2016-04-27 20:25
> I don't, I have Fatal Frame 3 (J), oh and Project Zero 3 (which is the PAL version)

Fatal Frame is the US version, Zero is the Japanese version.

Do the other two games in the series have the same issues?

> Dx11 still doesn't support depth read/write so it is likely still broken.

It worked when OpenGL also worked, and both were broken when the were broken. So it's probably just a depth issue

**Comment by gregory38** [comment] 2016-04-27 20:29
If both dx11 and openGL share the same issue, it isn't a depth issue. But either a texture cache issue or maybe the crtc read feedback. Depth ought to work on openGL now but not in dx11.

**Comment by FlatOutPS2** [comment] 2016-04-27 20:30
Oops, I meant "So it's probably NOT just a depth issue" :P

**Comment by FlatOutPS2** [comment] 2016-04-27 20:47
I did find another temporary way to get the ghost to show up, just be pauzing and resuming the game.
I tested a GSdx version with texture cache turned off, it didn't change anything.

**Comment by gregory38** [comment] 2016-04-27 20:51
You might need both the depth and the texture cache. Anyway, you need to find a way to generate a gs dump that reproduce the issue. This way, I could analyze draw call by draw call the rendering. And I need to add some code to dump texture that are read by the EE.

**Comment by gregory38** [comment] 2016-04-28 08:31
OoO maybe I found a subtile bug. I'm searching depth texture into depth buffer. But the depth texture could be in the color buffer too (and conversion won't be the same...).

In the mean time, you could also try a dev build (mean dev target) with gl trace enabled
```
debug_opengl = 1
```

See if you see this kind of message
```
ERROR: InvalidateLocalMem depth format isn't supported.........
```
```
ERROR: InvalidateLocalMem target is a depth format
```

**Comment by FlatOutPS2** [comment] 2016-04-28 10:01
I used a dev build of the master and put `debug_opengl = 1` in GSDX.ini, but got not error messages or other special log entries. Do I need any other option on?

**Comment by gregory38** [comment] 2016-04-28 10:05
Let's me guess, Visual Studio doesn't set the `_DEVEL` macro.

Edit `config.h` to always define ENABLE_OGL_DEBUG

**Comment by refractionpcsx2** [comment] 2016-04-28 10:09
Nope, only this

<PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>

**Comment by gregory38** [comment] 2016-04-28 10:13
Actually it is better this way, it will crash on dx otherwise.

**Comment by FlatOutPS2** [comment] 2016-04-28 11:31
> Edit config.h to always define ENABLE_OGL_DEBUG

Did that, no change.

**Comment by gregory38** [comment] 2016-04-28 11:38
Hum, could you check if the file `GSdx_opengl_debug.txt` was created?

**Comment by FlatOutPS2** [comment] 2016-04-28 11:53
Yes it was. Wasn't it supposed to be posted in the pcsx2 log?

There wasn't a InvalidateLocalMem in the log, but when I just tried again there were several of the following:
T:Error	ID:371612	S:Mid	=> ERROR: InvalidateLocalMem depth format isn't supported (500,16 to 504,17)

**Comment by gregory38** [comment] 2016-04-28 12:00
The printf is only done when _debug is enabled.

https://github.com/PCSX2/pcsx2/blob/master/plugins/GSdx/GSDeviceOGL.cpp#L1655

Just remove the ifdef/endif macro. It will print it on the emulog.

Could you post the log somewhere? Size of the read is really small (And strange), just a 4x2 pixels.

**Comment by FlatOutPS2** [comment] 2016-04-28 12:12
Here's the completely log:
[GSdx_opengl_debug.txt](https://github.com/PCSX2/pcsx2/files/240464/GSdx_opengl_debug.txt)

**Comment by gregory38** [comment] 2016-04-28 13:39
Thanks. I will look at it more closely when I back to home.

I need to fix a couple of limitation to handle the depth read (won't impact this game but might impact others). I need to reduce the size of the read, reading the full depth for 4 pixels is not efficient.

Then I'm worried about buffer size. As you can see we have a buffer of 640x1344 at address 0. It means the buffer overlap the buffer at 0x8C0 and 0x1180. So potentially we miss some rendering. Rendering done in buffer 0 must be done in 0x8c0 and/or 0x1180
```
T:Perf	ID:371152	S:Info	=> TC: Read Back Target: 52 (0x0)[fmt: 0x0]. Size 640x1344
T:Perf	ID:371585	S:Info	=> TC: Read Back Target: 1 (0x8c0)[fmt: 0x0]. Size 640x224
T:Perf	ID:371612	S:Info	=> TC: Read Back Target: 5 (0x1180)[fmt: 0x31]. Size 640x224
```

**Comment by gregory38** [comment] 2016-05-16 16:23
Could someone give a quick shot to #1316 I don't think it will help but you know.

**Comment by gregory38** [comment] 2016-05-16 16:41
Wait maybe I found an important bug due to latest addition. I need to debug it first.

**Comment by FlatOutPS2** [comment] 2016-05-16 17:10
Actually, I think I did try it back when you created the PR, but it didn't help. I suspect I accidentally deleted the build afterwards, so I forgot about it. :D

I'll make sure and try again after you've dealt with the bug.

**Comment by gregory38** [comment] 2016-05-16 17:25
For the bug, I was using the texture size instead of the real transfer size. But it seems we always transfer the full texture, so no impact.

Ok. Don't bother then. However you could still try to generate me nice big gs dump.

**Comment by FlatOutPS2** [comment] 2016-12-18 12:08
@Ryudo300 The invisible ghosts issue seems fixed with "Fast Texture Invalidation" HW hack. Can you confirm this?

**Comment by Ryudo300** [comment] 2016-12-19 08:52
I'll give it a whirl later when I get home from work.

**Comment by FlatOutPS2** [comment] 2017-01-01 23:53
@Ryudo300 Home from work yet? :p

**Comment by refractionpcsx2** [comment] 2017-01-02 00:35
> @Ryudo300 Home from work yet? :p

maybe he's taking the long route :P

**Closed** 2017-01-08 21:21 UTC
Labels: GSdx: Hardware

**Comment by gregory38** [comment] 2017-01-08 21:32
If it fixed by the hack, it is likely due to partial read back

**Comment by DudeStudienarbeitLMAO** [comment] 2017-11-05 15:49
For what it's worth, this wasn't fixed by the hack.
