### ISSUE TITLE
[BUG]:Colin Mcrae Rally 2005 

### ISSUE THREAD

**Issue by TheBoxGamePL** [PCSX2/pcsx2#7141] opened 2022-10-06 09:40 UTC
### Describe the Bug

in the game Colin Mcrae Rally 2005 there is a graphics problem that during the game there is a purple screen with fps stripes in the game drops to 10 instead of 30/60 and there are also problems with the sound during the game

### Reproduction Steps

![1](https://user-images.githubusercontent.com/101580091/194279690-4c9576a4-9cf5-4dab-b5e8-1ff0fa90b519.PNG)
![3](https://user-images.githubusercontent.com/101580091/194280130-13cf0318-6dac-4f45-905a-6e88aaf39c11.PNG)

### Expected Behavior

![obraz_2022-10-06_112738754](https://user-images.githubusercontent.com/101580091/194277625-17c4d9ba-675c-4a7f-882e-cc7c8d50e404.png)

### PCSX2 Revision

v1.7.1337

### Operating System

Windows 10 (64bit)

### CPU

i5-7300HQ

### GPU

GTX 1050

### GS Settings

![1](https://user-images.githubusercontent.com/101580091/194278428-c984653a-ff7a-433b-9cf6-e8379d1d0660.PNG)

### Emulation Settings

![1](https://user-images.githubusercontent.com/101580091/194278560-1a40e42b-36fd-4371-b4ae-50aa1a0e6816.PNG)

### GS Window Screenshots

![obraz_2022-10-06_114002719](https://user-images.githubusercontent.com/101580091/194280455-c21614bd-2c0e-4d50-b0a4-35fe69168b45.png)

### Logs & Dumps

![1](https://user-images.githubusercontent.com/101580091/194278876-314ff49c-537a-4c2d-b359-27171f8822d2.PNG)
![2](https://user-images.githubusercontent.com/101580091/194278878-53d1fe13-b80b-47b1-adce-2f712c4b0646.PNG)
![3](https://user-images.githubusercontent.com/101580091/194278880-fb8c0bc3-ab01-4fcb-8431-ec46ca400ef2.PNG)
![4](https://user-images.githubusercontent.com/101580091/194278884-c5e1eae2-8f31-40e4-97f7-95b4d4b53871.PNG)
![5](https://user-images.githubusercontent.com/101580091/194278887-9ecc9ee8-5942-4681-bab9-de0a8df84ecb.PNG)
![7](https://user-images.githubusercontent.com/101580091/194278890-dfccd619-7ff9-4f81-bf23-23d0b7d46022.PNG)
![8](https://user-images.githubusercontent.com/101580091/194278892-a568ad31-34c8-49a0-b78b-c35a8e8dcf0f.PNG)

**Comment by refractionpcsx2** [comment] 2022-10-06 09:44
Duplicate of #1546

**Closed by refractionpcsx2** 2022-10-06 09:44 UTC
Labels: Bug
