### ISSUE TITLE
[BUG]: Running games with Vulkan or OpenGL renderer in Fullscreen disables Windows HDR settings

### ISSUE THREAD

**Issue by Cyber-Snake** [PCSX2/pcsx2#6145] opened 2022-05-23 11:21 UTC
### Describe the Bug

PCSX2 disables Windows HDR settings when fullscreen is toggled with Vulkan or OpenGL rendered. Issue seems to be new for Qt release as it didn't happen with previous versions. This issue may not be caused by PCSX2 directly but by Nvidia drivers since it can also happen with other OpenGL and Vulkan applications but only when using Exclusive Fullscreen, as far as I know PCSX2 uses Borderless Windows which should not cause this behavior and again issues was not present in previous releases.

### Reproduction Steps

Launch any game with Vulkan or OpenGL renderer and toggle fullscreen with HDR enabled in Windows settings.

### Expected Behavior

PCSX2 should not disable HDR settings and instead continue to use HDR color space.

### PCSX2 Revision

v1.7.2775

### Operating System

Windows 11

**Comment by Licmi007** [comment] 2022-06-01 18:09
same problem,pls try to fix this :)

**Comment by jmarucha** [comment] 2022-11-25 19:30
So I did run in the same problem and I can say at 1.7.3626 it is still occurs. Borderless windowed mode is in fact full screen, and it switches my monitor mode.
However there is one other weird thing
After I alt-tab from game, or close it, HDR settings are not disabled. What changes is SDR to HDR brightness behaves like it was set to lowest possible (but system shows it's not). Touching the slider sets it to correct position.

Display adapter: Nvidia 3080
System: Windows 11
Renderers tested: OGL & Vulcan
I can provide other details if needed, but i'm all new to the color gamut stuff.

**Comment by velosotiago** [comment] 2022-11-30 17:54
Running into the same problem. I believe the HDR "resetting" to be a problem with Windows, since it can be reproduced in any game running on OpenGL or Vulkan in Exclusive Fullscreen mode.

As @jmarucha described above, the real issue is that with both OpenGL and Vulkan renderers in PCSX2, Exclusive Fullscreen is being used instead of Borderless Fullscreen, despite the Fullscreen Mode dropdown saying otherwise.

PCSX2 Version: 1.7.3661 AVX2 QT
Display Adapter: Nvidia 3080 10GB
System: Windows 11
Renderers Tested: All (only reproducible on OGL and VK - SW, DX11 and DX12 use Borderless Fullscreen as expected)

**Comment by jmarucha** [comment] 2022-12-04 17:31
I can confirm the issue of SDR brightness settings not reverting is related to windows, as it's not unique for PCSX2, and occurs in Stumble Guys (no idea about api or anything).

**Comment by Cyber-Snake** [comment] 2022-12-06 15:41
The bug is not related to PCSX2 specifically, as people said it's normal behavior in Exclusive Fullscreen with Vulkan or OpenGL caused by Windows or graphics drivers. But it can be fixed on PCSX2 by introducing proper Borderless Fullscreen.

**Comment by 13xforever** [comment] 2023-01-23 13:25
Wanted to create a feature request, but it would duplicate this issue.
It's an nvidia bug that affects pretty much every vulkan app/game. You can workaround it by explicitly requesting non-exclusive full screen mode.
Here's an example of advanced settings from rpcs3:
![image](https://user-images.githubusercontent.com/36445/214050649-c51800b4-33b0-4d87-b639-657c8e59ea50.png)

**Comment by stenzek** [comment] 2023-01-23 14:45
Adding such an option to fix an nvidia bug seems kinda silly.. has it been reported to nvidia?

**Comment by mparley** [comment] 2023-04-16 12:57
Just want to point out it isn't an nvidia bug as it breaks just the same as on my amd gpu. More likely a windows issue as others pointed out. I've had the same thing happen with other opengl applications but personally haven't run into any other vulkan ones that do it

**Comment by Cyber-Snake** [comment] 2023-04-24 17:15
I can confirm it's possible to disable Exclusive Fullscreen promotion via Nvidia Inspector by modifying OGL_DX_PRESENT_DEBUG and in bit value editor enabling bits # 00 and # 19 .
Could it be possible to make PCSX2 request desired fullscreen mode from drivers? That's how it's implemented in RPCS3. It offers you option to either prefer Borderless or Exclusive Fullscreen as well as Automatic. And it solves the issue with HDR and even enables DXGI promotion.
![RPCS3 0 0 27-14924-5870dad6 Alpha _ master 24_04_2023 19_09_091](https://user-images.githubusercontent.com/48720219/234068584-aabe9e34-99ed-4cef-91f1-e6afe1a564dd.png)

**Comment by stenzek** [comment] 2023-04-25 03:30
Quoting what I said in January

> Adding such an option to fix an nvidia bug seems kinda silly.. has it been reported to nvidia?

> And it solves the issue with HDR and even enables DXGI promotion.

I don't see how the exclusive fullscreen extension for Vulkan would have anything to do with "DXGI promotion".

Both AMD and NV automatically scan out the swap chain directly, similar to exclusive fullscreen, in Vulkan and OpenGL.

**Comment by Cyber-Snake** [comment] 2023-04-25 15:16
Trying to get it resolved on Nvidia side is unlikely to produce any results. As far as we know it's the intended behavior. The DXGI layer is a recent addition but they still didn't bother changing how Exclusive Fullscreen functions despite it conflicting with that feature, it's possible it will change in the future but right now there's no indication of that. So workaround on emulators side is the only option here. And even HDR aside something should be changed in how PCSX2 handles fullscreen. I expect many people simply want to have Borderless Windowed for various reasons but right now it just forces you into Exclusive Fullscreen and as I said I don't expect Nvidia to do anything about it.

**Closed** 2023-04-25 15:24 UTC
Labels: Bug, OS: Windows

**Comment by Cyber-Snake** [comment] 2023-04-25 15:57
All right, if anyone is browsing this in the future [here's a workaround](https://performance.moddinglinked.com/#DXVK). Ignore the fact that it's a Fallow New Vegas guide, there's a "Enabling Flip Model (DXVK with DXGI)" section which describes which flags to modify in Nvidia Profile Inspector to disable forced promotion to FSE. This works on PCSX2 and any other application that doesn't play well with HDR. Nvidia may fix things on their end eventually but right now that's the best solution to the problem.

**Comment by mparley** [comment] 2023-04-27 23:54
I guess I'll just wait for NVIDIA to fix their "driver issue" for my AMD gpu.

**Comment by tompatomp** [comment] 2024-04-08 10:04
> All right, if anyone is browsing this in the future [here's a workaround](https://performance.moddinglinked.com/#DXVK). Ignore the fact that it's a Fallow New Vegas guide, there's a "Enabling Flip Model (DXVK with DXGI)" section which describes which flags to modify in Nvidia Profile Inspector to disable forced promotion to FSE. This works on PCSX2 and any other application that doesn't play well with HDR. Nvidia may fix things on their end eventually but right now that's the best solution to the problem.

Very late response but I found a much easier solution to the problem.

Go to Nvidia control panel > Manage 3d settings and scroll down to the last setting which says "Vulkan/OpenGL present method" and change that to "Prefer layered on DXGI Swapchain. 

This completely fixed the problem with HDR turning off when exiting a vulkan/openGL game.

**Comment by 13xforever** [comment] 2024-04-08 11:04
why even necropost; pcsx2 had the setting to disable fso for months at this point
![image](https://github.com/PCSX2/pcsx2/assets/36445/2de8dabd-9398-4a25-a166-db0fa385b20e)

**Comment by BaraoDoPequi** [comment] 2024-04-14 06:42
> > All right, if anyone is browsing this in the future [here's a workaround](https://performance.moddinglinked.com/#DXVK). Ignore the fact that it's a Fallow New Vegas guide, there's a "Enabling Flip Model (DXVK with DXGI)" section which describes which flags to modify in Nvidia Profile Inspector to disable forced promotion to FSE. This works on PCSX2 and any other application that doesn't play well with HDR. Nvidia may fix things on their end eventually but right now that's the best solution to the problem.
> 
> Very late response but I found a much easier solution to the problem.
> 
> Go to Nvidia control panel > Manage 3d settings and scroll down to the last setting which says "Vulkan/OpenGL present method" and change that to "Prefer layered on DXGI Swapchain.
> 
> This completely fixed the problem with HDR turning off when exiting a vulkan/openGL game.

I updated the emulator and I was having this problem, I spent 3 hours trying to solve it and I couldn't. If you were standing in front of me right now, I'd give you a kiss!

**Comment by vmnt** [comment] 2026-06-15 15:03
> > All right, if anyone is browsing this in the future [here's a workaround](https://performance.moddinglinked.com/#DXVK). Ignore the fact that it's a Fallow New Vegas guide, there's a "Enabling Flip Model (DXVK with DXGI)" section which describes which flags to modify in Nvidia Profile Inspector to disable forced promotion to FSE. This works on PCSX2 and any other application that doesn't play well with HDR. Nvidia may fix things on their end eventually but right now that's the best solution to the problem.
> 
> Very late response but I found a much easier solution to the problem.
> 
> Go to Nvidia control panel > Manage 3d settings and scroll down to the last setting which says "Vulkan/OpenGL present method" and change that to "Prefer layered on DXGI Swapchain.
> 
> This completely fixed the problem with HDR turning off when exiting a vulkan/openGL game.

Thank you so much for posting this. As you probably suspected, this bug/behaviour occurs across an array of openGL games (not just this engine) - for example Beyond All Reason and Avorion. I found this thread years ago (before you posted that workaround) but didn't revisit it and missed your message. Your reply is probably the source of an LLM finally suggesting this to me as the workaround while game developers work on the proper handling.
