### ISSUE TITLE
[BUG]: Pac-Man World Rally: Missing shadows and geometry

### ISSUE THREAD

**Issue by Hemporus01** [PCSX2/pcsx2#5384] opened 2022-01-23 03:28 UTC
### Describe the Bug

The shadows and geometry on certain objects and racers appear to be missing in the latest dev build.

### Reproduction Steps

Just get to the character select screen and you'll notice it right away.

### Expected Behavior

I expected the shadows and geometry to be present.

### PCSX2 Revision

v1.7.2260

### Operating System

Windows 10 (64bit)

### CPU

i5-11600

### GPU

GTX 1080 Ti

### GS Settings

<img width="265" alt="Capture" src="https://user-images.githubusercontent.com/97992262/150663154-c8ab8c56-0d57-4d6d-a79c-d59be9ceb34e.PNG">
<img width="266" alt="Capture 2" src="https://user-images.githubusercontent.com/97992262/150663155-7d558ef1-2aec-45f8-b820-1cdd4bbf1d2b.PNG">

### Emulation Settings

Defaults were used.

### GS Window Screenshots

![InkedCapture_LI](https://user-images.githubusercontent.com/97992262/150663593-7dc0763e-a5e6-4a9a-9212-c344415f6797.jpg)
![Inkedgs_20220122211721_LI](https://user-images.githubusercontent.com/97992262/150663602-83177413-8b84-45d1-9195-dc98db5b1a0c.png)

### Logs & Dumps

[PMWR Missing shadows and geometry GS dump.zip](https://github.com/PCSX2/pcsx2/files/7919665/PMWR.Missing.shadows.and.geometry.GS.dump.zip)

**Comment by refractionpcsx2** [comment] 2022-01-23 11:02
The vehicle looks to have shadows to me.

**Comment by refractionpcsx2** [comment] 2022-01-23 11:17
![image](https://user-images.githubusercontent.com/6278726/150675783-e688f2bc-e905-4eb9-b7d6-c7e018cc66b2.png)

looks fine to me, I can't reproduce your issue.

**Comment by refractionpcsx2** [comment] 2022-01-23 11:22
Okay I see the menu graphics that are missing, I'll look in to it

**Comment by gilderoylockhart01** [comment] 2022-01-23 12:13
Just a note about branch,branch,branch, those are normal logs which indicates the game is doing a triple branch, this is loged in red but perhaps should more be marron like the other logs because it's not an error at all.

**Comment by refractionpcsx2** [comment] 2022-01-23 12:35
I think that is where the error lies, my previous fix was incorrect, but I'm looking in to it now, having to deep dive back in to the behaviour so I can work out what was going on >.<

**Comment by gilderoylockhart01** [comment] 2022-01-23 13:00
Mmm, so I guess that's the reason I had some weird problems with MGS2 since you updated evil branch.

**Comment by refractionpcsx2** [comment] 2022-01-23 16:32
Should be fixed with my PR (linked above)

**Comment by Hemporus01** [comment] 2022-01-23 19:46
Its all fixed now.
<img width="1008" alt="Capture" src="https://user-images.githubusercontent.com/97992262/150695374-d19e65e1-b388-4401-acc6-5af51551adf7.PNG">
.

**Closed** 2022-01-23 20:31 UTC
Labels: Bug
