### ISSUE TITLE
Devil May Cry graphic glitch

### ISSUE THREAD

**Issue by ReyVGM** [PCSX2/pcsx2#1740] opened 2017-01-04 03:24 UTC
***PCSX2 version:***
pcsx2-v1.5.0-dev-1711-g29d2292-windows-x86

***PCSX2 options:***
***Plugins used:***
Default

***Description of the issue:***
During the ending cutscene (ingame graphics), after you shoot the boss, Dante is the only one that should be glowing purple, but instead the whole room glows too.

![screen3551](https://cloud.githubusercontent.com/assets/7338867/21630854/821b4aac-d20b-11e6-9626-faeb4ffa4a57.png)

Save state right before the scene:
[devil may cry ending save.zip](https://github.com/PCSX2/pcsx2/files/683857/devil.may.cry.ending.save.zip)

***PC specifications:***
CPU: Intel i5 3rd gen GPU: none OS: Windows 764 Bit

**Comment by refractionpcsx2** [comment] 2017-01-04 09:57
Does that happen on all renderers? If you use OpenGL and put the Blending Accuracy up to Ultra does it still happen?

**Comment by gregory38** [comment] 2017-01-04 11:33
First test the SW renderer.

**Comment by FlatOutPS2** [comment] 2017-01-04 11:38
If it works in Software mode, and refractionpcsx2's suggestion doesn't help, upload a GS dump of the issue: http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by ReyVGM** [comment] 2017-01-04 16:40
Sorry, yes I tested all the renderers. But I can't test OpenGl one because I don't have a GPU and the emu says I can't use it.

I used D3D11 SW by default.

HOWEVER, I tested the different renderenders by just loading the save state before the issue happened. Do I need to get to the ending from scratch to test that or is loading a state work fine?

**Comment by refractionpcsx2** [comment] 2017-01-04 17:09
Can somebody with a GPU confirm this please? I don't trust intel drivers :P

A GS Dump as requested by FlatOutPS2 above would be good, please make it in software mode.

**Comment by FlatOutPS2** [comment] 2017-01-04 18:05
It definitely looks like something's wrong there in all renderers. Did you also try disabling speedhacks and changing the VU Clamping/Rounding mode settings?

**Comment by prafullpcsx2** [comment] 2017-01-04 18:15
I can confirm the bug but I think it will be better to check zerogs also.

**Comment by ReyVGM** [comment] 2017-01-04 18:15
I always have Preset 2 enabled, so I disabled it and disabled the speedhacks too (and also messed around with it too enabling/disabling stuff) and the same issue happened.

But bear in mind I'm using a save state, I don't know if the issue is "embedded" in the save state now.

**Comment by refractionpcsx2** [comment] 2017-01-04 18:41
> It definitely looks like something's wrong there in all renderers. 

The screenshot in the GS dump looked okay?

**Comment by FlatOutPS2** [comment] 2017-01-07 14:04
> The screenshot in the GS dump looked okay?

It doesn't. But without a screenshot of how it's supposed to look you might think it is. The dump itself shows a clearer example of the issue.

This is how the scene is supposed to look(about the same moment as the snapshot in the first post):
![dante](https://cloud.githubusercontent.com/assets/15942346/21742001/ec2f7c4c-d4e5-11e6-9429-3b7205de17ec.jpg)

Once the issue is triggered, all renderers show the issue, so the GS dump won't help much.

**Comment by ReyVGM** [comment] 2017-01-08 00:29
Man, how did you ever find that out?

**Comment by MrCK1** [comment] 2017-12-03 00:04
If I get to this point, I'll retest it. I happened to notice that this game requires Full Blending to render blood transparently (and probably some other stuff) so we'll see.

**Comment by coornio** [comment] 2022-05-11 08:38
Activity poke -- can someone with the game confirm whether this bug is still present in the latest devel? 

The game has "Disable Partial Invalidation" enabled as an automatic GS fix, with the note "fixes corrupt textures" which ref believes is related to this very bug.

If someone could get back to me here, we can close this issue if it's truly resolved, and also adjust the wiki accordingly.

**Comment by refractionpcsx2** [comment] 2022-07-10 11:49
No response so assuming resolved, we can reopen if it is still an issue.

**Closed by refractionpcsx2** 2022-07-10 11:49 UTC
Labels: Workaround Possible, Bug - Unknown Source
