### ISSUE TITLE
Tekken 5 - Sun rays through character

### ISSUE THREAD

**Issue by Krusher97** [PCSX2/pcsx2#2766] opened 2018-12-21 11:54 UTC
***PCSX2 version:***
 1.5.0 dev 2818

***PCSX2 options:***
OpenGL HW with Default settings

***Plugins used:***
Default

***Description of the issue:***
The sun "rays" render through the character in hardware mode. More noticeable at native resolution.
![gsdx_20181221171845](https://user-images.githubusercontent.com/25664221/50341506-036f0300-0545-11e9-8eaa-9dbfcf7cee9e.png)
![gsdx_20181221171904](https://user-images.githubusercontent.com/25664221/50341511-07028a00-0545-11e9-86a2-e4d8fd52af5d.png)
First screenshot is from OpenGL HW at native resolution, second is from SW.
[gsdx_20181221171845.gs.zip](https://github.com/PCSX2/pcsx2/files/2702644/gsdx_20181221171845.gs.zip)

***How to reproduce the issue:***
Start practice mode and select the City at Sunset stage

***Last known version to work:***
None

**Comment by mirh** [comment] 2018-12-21 17:14
Smells very similar to #1860

**Comment by MrCK1** [comment] 2019-01-04 19:54
Maybe it's a half-screen issue? Can't tell

**Comment by lightningterror** [comment] 2019-06-27 23:21
Is sw render fine?

**Comment by Krusher97** [comment] 2019-06-28 04:15
Yes, second screenshot is from SW renderer.

**Comment by refractionpcsx2** [comment] 2022-03-05 15:36
This is caused by a bad CRC hack, which I don't think is required anymore

turning CRC hacks to "none" produces this

![image](https://user-images.githubusercontent.com/6278726/156890060-ada5b0e1-1813-4e51-883a-ab30131dba77.png)

**Comment by refractionpcsx2** [comment] 2022-03-05 15:56
Yeah the CRC hack was bad, needed to be more specific, fixed now.

**Closed** 2022-03-05 15:55 UTC
Labels: GS, Needs Research
