### ISSUE TITLE
Auto update 

### ISSUE THREAD

**Issue by Siraj1993** [PCSX2/pcsx2#3807] opened 2020-10-08 19:35 UTC
It will very good to have auto update in PCSX2. I hope the developer can add it to emulator. Thanks...

**Comment by gtgamer468** [comment] 2020-10-08 19:58
That is a duplicate of this issue: [https://github.com/PCSX2/pcsx2/issues/3054](url)

**Comment by RedPanda4552** [comment] 2020-10-08 19:58
#3054

**Closed by RedPanda4552** 2020-10-08 19:58 UTC
Labels: Duplicate
