### ISSUE TITLE
Grand Theft Auto Vice City Stories - Gsdx regression

### ISSUE THREAD

**Issue by Blackbird88** [PCSX2/pcsx2#1013] opened 2015-12-01 19:09 UTC
Caused by @d67ba01
Original
![image](https://cloud.githubusercontent.com/assets/4414625/11511104/68923a02-9867-11e5-9196-c74c7a3ae728.png)
General regression (Bottom of the screen is cut-off)
![image](https://cloud.githubusercontent.com/assets/4414625/11511117/7b1d26a0-9867-11e5-972a-eaf3924561c2.png)

(This way annoying to pinpoint)

**Comment by ssakash** [comment] 2015-12-02 05:37
Ouch ! I'll have to try looking into this game.

**Comment by ssakash** [comment] 2015-12-02 07:15
@Blackbird88 

could you give me a memory card save file near the issue ? I can't reproduce it on my side.

**Comment by Blackbird88** [comment] 2015-12-02 07:19
Just to make sure. Do you have in-game Widescreen set to on? Maybe it's related to that.
As for memory card I'll post it when I'll get home.

**Comment by ssakash** [comment] 2015-12-02 07:36
Never mind. I was looking into GTA: Vice city instead. I'll check this game later

**Comment by Blackbird88** [comment] 2015-12-02 07:38
Oh that didn't cross my mind. The names can be confusing hehe

**Comment by gregory38** [comment] 2015-12-02 08:22
Did you try to toggle F7 toggle several time to disable tv shader, please check also interlacing.

**Comment by ssakash** [comment] 2015-12-02 08:32
@Blackbird88 

I tried checking the near save point and still no luck on reproducing this issue, does this happen on all places (or) only on this certain save spot ? 

![gta](http://ultraimg.com/images/gsdx_20151202055940.png)

**Comment by willkuer** [comment] 2015-12-02 11:11
To answer the small question before it got lost: yes you should disable widescreen hacks. They can affect cropping.

**Comment by Blackbird88** [comment] 2015-12-02 12:54
That's the literally first thing I did and nothing. This game doesn't even need one. It has native WS support.

**Comment by ssakash** [comment] 2015-12-02 13:24
> Do you have AMD GPU? Maybe that Nvidia scaling issue is back? IDK what else. And yes it happens everywhere.

I have a GTX-750 Ti and if the mentioned commit was really the one which did cause the issue then it's unlikely to be a driver issue.

please try this [GSDX plugin](https://www.dropbox.com/s/o4xb7n2z1fo6a1s/GSdx32-SSE2.dll?dl=0) and post back the emulog. a little run at where the issue was present should be enough ;) 

The log will likely be a bit large so feel free to attach at any hosting sites.

**Comment by Blackbird88** [comment] 2015-12-02 13:34
This it?
https://gist.github.com/Blackbird88/e337a8d9535e43f48c01

**Comment by ssakash** [comment] 2015-12-02 13:53
weird, the log messages didn't get triggered. could you provide the memory card save file ?

> And yes it happens everywhere.

I didn't encounter any such instances though, did the issue occur when starting a new game and entering free roam ? what about the menus and into logos ?

**Comment by Blackbird88** [comment] 2015-12-02 13:54
Sure If I can get through BIOS since it has no text for some reason.

**Comment by ssakash** [comment] 2015-12-02 15:44
I still can't reproduce the issue. debugging is pretty much impossible if the issue doesn't even appear. Tried both the NTSC and PAL versions of the game and everything looks fine. 

![image](http://ultraimg.com/images/gsdx_20151202210646.png)


Try getting the latest development version from [here](http://buildbot.orphis.net/pcsx2/index.php) with the default settings ( everything left unchanged, don't import INI files ) and check whether you could reproduce the issue. (sorry, just to get things straight since you seemed to have some issues with BIOS as well)

**Comment by Blackbird88** [comment] 2015-12-02 15:55
Still happens with clean PCSX2 :(
Anything else I can do? GS Dump or Debug version of PCSX2/GSdx?

**Comment by ssakash** [comment] 2015-12-02 15:57
please give emulog from debug build. CRTC scaling info should be there

**Comment by Blackbird88** [comment] 2015-12-02 16:10
Got it here
https://gist.github.com/Blackbird88/0e3050e4cbf1c06bb47b

**Comment by refractionpcsx2** [comment] 2015-12-02 16:15
Looks like you are using a custom debug version. Can you download the latest git build, put it in to a new folder, copy over your bios and memorycards and try that one please.

**Comment by Blackbird88** [comment] 2015-12-02 16:16
But I did that already lol

**Comment by ssakash** [comment] 2015-12-02 16:21
What the heck O_0 , according to the log the PAL game is using NTSC video mode. For correct behavior it should have ``Set GS CRTC configuration. Interlace Interlaced. Field Type FRAME. Mode PAL  640x512 @ 50.000 (49.76)``

That's how it does for me, give me a dev emulog of the last version which worked well please.

**Comment by Blackbird88** [comment] 2015-12-02 16:34
This is from build that doesn't have this issue
https://gist.github.com/Blackbird88/5266d9564cca986915d0

**Comment by ssakash** [comment] 2015-12-02 16:35
CRTC configuration is still wrong... by any chance did you patch your ISO (or) something ?

**Comment by Blackbird88** [comment] 2015-12-02 16:35
No. Definitely not.

**Comment by ssakash** [comment] 2015-12-02 16:52
@gregory38 

Here's a summary of the issue, The issues is with a PAL game which seems to use NTSC video mode for some reasons. since the original height of the game is 512 and it seems to run in NTSC video mode my older commit saturates the value to 448 and the lower part of the screen gets cropped. which shouldn't happen since the game should run in PAL video mode where the conditional check doesn't get applied.

Also it seems to run at NTSC video mode for @Blackbird88  PAL version of the game where it correctly runs at PAL video mode on my friends PAL version of this game. so the obvious conclusion would be that either the internal detection for PAL/NTSC video mode is wrong (or) the ISO dumpc is a bit weird. any opinions ? 


@Blackbird88 

could you try remaking the ISO once again ? (just to be on the safe side)

**Comment by Blackbird88** [comment] 2015-12-02 16:58
Sorry, but that I'll do tomorrow since that is too time consuming.
Meanwhile you can have this. MD5 of the executable.
SLES_546.22 - 965E3D460C8B85D347EA195D4CAA9665

**Comment by gregory38** [comment] 2015-12-02 16:59
Is there any configuration in the game/bios? Which is the region of the game?

@Blackbird88 it is fine. It isn't an ISO issue anyway. That the standard GS behavior (aka undefined ;) )

**Comment by Blackbird88** [comment] 2015-12-02 17:03
Well I have **Screen Size** set to Full since 4:3/16:9 option creates black bars. Otherwise all looks normal.
Also I thought PCSX2 ignores this stuff?

**Comment by gregory38** [comment] 2015-12-02 17:10
```
Also I thought PCSX2 ignores this stuff?
```
Well I don't know, some stuffs are black magic ;)

**Comment by ssakash** [comment] 2015-12-02 17:21
Hmm, either detection is partially wrong : https://github.com/PCSX2/pcsx2/blob/b7c51922e82ab0d107bf3923191bc304555289e3/pcsx2/R5900OpcodeImpl.cpp#L888
(or) ISO has some problems. since it works fine on my PAL version of this game. block dump might help ( probably )

**Comment by Blackbird88** [comment] 2015-12-02 17:22
Block dump?

**Comment by gregory38** [comment] 2015-12-02 17:25
code misses some info (such as global variables). Besides it is only a limited view, you can set the register manually without relying on the syscall.

@ssakash which version do you have exactly?

**Comment by ssakash** [comment] 2015-12-02 17:35
> which version do you have exactly?

PAL region disk of the same game. (SLES-54622) only with a different CRC. you can see further information on the dev logs which @Blackbird88 posted (it gives a clear idea of the issue) also see my explanation [here](https://github.com/PCSX2/pcsx2/issues/1013#issuecomment-161362378) and you'll figure out the cause of the issue. :) 

> Block dump?

search the forums, a little busy. gotta go to sleep ...

**Comment by rz5** [comment] 2015-12-02 20:34
I cannot reproduce this bug with the memory card file provided @Blackbird88.

Here's what pcsx2 says about my copy:
```
ELF (cdrom0:\SLES_546.22;1) Game CRC = 0xB3AD1EA4, EntryPoint = 0x001DD680
(IsoFS) Block 0x10: Primary partition info.
(IsoFS) Filesystem is ISO9660
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLES_546.22;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = PAL
```
The last CRTC message I got was:
```
Set GS CRTC configuration. Interlace Interlaced. Field Type FIELD. Mode PAL  640x512 @ 50.000 (49.76)
```
Also worth noting is that I never got a CRTC message where the mode was NTSC.
Here's the state of some relevant GS registers while I'm in-game:
```
SMODE1
    CMOD = 3 // This implies PAL mode, it's concordant with the CRTC message
SMODE2
    INT = 1
    FFMD = 0
DISPLAY
    DX = 656
    DY = 72
    MAGH = 3
    MAGY = 0
    DW = 2559
    DH = 509
```

Here's what I get when I make a GS dump:
https://www.sendspace.com/file/gx29sz

Some observations are that my copy and @ssakash's are the same (same CRC). @Blackbird88's copy has a different CRC and it's setting video mode to NTSC, which on mine it never happens.
@Blackbird88, could you post a GS dump? I can already tell what's happening is that, because CMOD is set to 2 (NTSC mode), that triggers the height being limited to 448 when the "framebuffer" is actually 510.

**Comment by refractionpcsx2** [comment] 2015-12-02 20:49
It sounds to me like that ISO has been patched to NTSC. Did you "definitely" rip that ISO from your retail disc? I can't understand why the CRC would be different and the game would be saying it is an NTSC game when it is quite definitely a PAL region game.

I'm pretty confident the issue is with your ISO and not the emulator.

**Comment by Blackbird88** [comment] 2015-12-02 21:18
Yes. And it has been working fine for years.

**Comment by refractionpcsx2** [comment] 2015-12-02 21:20
But there was no proper handling before and your ELF File is obviously not the standard one for this release, this is what I don't understand.

The game shouldn't be marking itself as NTSC as it is a PAL game, but your copy is, that is the only way that commit can affect your game

**Comment by Blackbird88** [comment] 2015-12-02 21:20
Actually this is in ELF
>BOOT2 = cdrom0:\SLES_546.22;1
VER = 1.00
VMODE = PAL

**Comment by refractionpcsx2** [comment] 2015-12-02 21:23
Yes, but your ELF file (the SLES_546.22) is telling the hardware to run in and NTSC mode (the CMOD register flag) which is usually something which has been done by a region patch.

**Comment by Blackbird88** [comment] 2015-12-02 21:25
I don't suppose there is a tool to view those flags like you can with Windows .EXEs?

**Comment by refractionpcsx2** [comment] 2015-12-02 21:26
unfortunately not, it's something which will need to be manually put in to the program as these are set in code, not a header like with windows.

**Comment by gregory38** [comment] 2015-12-02 21:31
maybe we can compare both binary (or the dissassembled version)
binary comparison on linux
```
cmp -l
```
binary to asm
```
objdump -d -mmips file.elf
```

**Comment by ramapcsx2** [comment] 2015-12-03 11:33
I believe this is a useless effort. He may have bought a pirate copy without realizing it. It happened a lot in certain markets. His .elf has certainly been tampered with. There's no way a PAL release would boot into an NTSC mode by default. At most, some games might allow changing the video mode in their menus.

**Comment by slx7R4GDZM** [comment] 2015-12-03 12:21
@Blackbird88, have you tried your ISO on a real PS2 to check the behavior?

**Comment by Blackbird88** [comment] 2015-12-03 13:43
Yeah it works fine on it. My PS3 too. Guess it was bootleg copy without me knowing :/

**Comment by gregory38** [comment] 2015-12-03 14:28
OoO autodetection is doomed IMO.

(by the way, what does bootleg mean?)

**Comment by ssakash** [comment] 2015-12-03 14:32
> (by the way, what does bootleg mean?)

Pirated copy of a product.

**Comment by Blackbird88** [comment] 2015-12-03 14:53
Okaya so I got arr copy to test your theory guys (pls no bully) and the issue is gone. It even loads my saves. The red flag should've been the fact that my PAL copy runs at 60 FPS while this one runs at 50 FPS liek it should. Probably why it was tampered with in teh first place. To get NTSC 60 FPS :D
I forgot about the FPS differences.

**Comment by mirhl** [comment] 2015-12-03 18:26
Mhh.. we could call this the final test for resolution detection I guess. 
If it works on ps2.. then shouldn't we technically expect the same (one day)?

**Comment by ramapcsx2** [comment] 2015-12-05 10:35
It's often extra hard to emulate glitchy hardware behaviour correctly.
In this case it's unknown what the pirates did to get full screen in 60Hz.
Possibly they only offset the video a bit and because reasons GSdx doesn't support that yet.
Good thing this was resolved though, closing :)

**Closed by ramapcsx2** 2015-12-05 10:35 UTC
Labels: Plugin: GSdx, Regression
