### ISSUE TITLE
CDVD plugin merge causing issues with Input Recording's pausing/frame-advancing

### ISSUE THREAD

**Issue by InfamousKnight** [PCSX2/pcsx2#3721] opened 2020-09-20 04:27 UTC
In latest commit fe10f23
There's a major recording bug on linux

I copied PCSX2_keys.ini.default to the ini folder on linux and tried to change the frame advance key to F instead of Space(I also changed the control pad so that itb doesn't conflict with F key already set there) and it didn't apply. Space is still required like its reading the wrong file.

Next major problem, when trying to tas midnight club 2, I start new recording with game open, from power on, advance frame up to the point where I can pass the flaming rockstar animation(you can do this once its about halfway done), and it freezes the game. I can still advance frames though. And this happens once I press start(n key) on frame advance. I would press n and space at the same time. And once I did that, it froze. I'm sure it would also freeze if you simply tried to apply an input on frame advance. I have't tried it.

I haven't tried windows yet either.

**Comment by refractionpcsx2** [comment] 2020-09-20 13:06
Tagging @xTVaser and @sonicfind

**Comment by sonicfind** [comment] 2020-09-20 13:58
Right away, I can answer the first issue.
You have to remove the “.default” extension for it to register. It says this at the top of the file.
In regards to the second part, I’ll have to look into that.

**Comment by InfamousKnight** [comment] 2020-09-20 14:33
I tried to find a consistent way to reproduce the second problem: just enter frame advance mode and try to skip that rockstar logo animation by mashing start key. Eventually this will freeze the game but not the movie file.

**Comment by sonicfind** [comment] 2020-09-20 14:47
If the movie file is still able to proceed, then that means that behind the scenes the emulation is too - just that the game itself isn’t.
The internal recording frame counter will only increment itself if the interface that controls pausing, frame advancing, etc. registers that emulation itself has processed another frame.
I assume you’ve already tested just letting the game proceed as normal without frame advancing right? Need to know whether it is truly frame advancing causing some sort of internal issue or just the PCSX2 in general. Would make testing on Linux for Vaser a bit easier.

**Comment by sonicfind** [comment] 2020-09-20 15:01
Also, can you confirm if there is an older build where this doesn’t happen?

**Comment by InfamousKnight** [comment] 2020-09-20 15:16
It seems to be an issue with frame advancing. If you don't touch frame
advance, things should be fine.

I could try and look into older builds.

**Comment by xTVaser** [comment] 2020-09-20 16:22
> I tried to find a consistent way to reproduce the second problem: just enter frame advance mode and try to skip that rockstar logo animation by mashing start key. Eventually this will freeze the game but not the movie file.

Just for clarification, you're holding the start key and advancing frames?

Can you try doing the same thing in a different game?  I'd be surprised if this issue is linux specific, but also I havn't seen any issues with frame-advancing myself since the recent revamp.

And yeah, a good older commit to try is prior to the recent overhaul - https://github.com/PCSX2/pcsx2/commit/fa894d9d4876ac779f8209af7164f38baf952211 though you may see other more glaring issues that that PR resolved.

**Comment by InfamousKnight** [comment] 2020-09-20 16:40
I tested holdin the start key and advancing frames, and this reproduces the
problem. So yeah, just hold start and advance frames. And eventually the
game will freeze but the movie will keep going. If you play back, it plays
like no inputs were made.

**Comment by xTVaser** [comment] 2020-09-20 17:29
I think I've repro'd the issue.  Not linux specific and doesn't seem to be specific to your game either.

The issue appears to be if you frame-advance while the DVD is still doing it's boot process, it's unable to continue.  I'm seeing a lot of logs like the following while frame-advancing which I don't remember seeing before:
```
isoFile open ok: E:\ISOs\Jak\Jak 2.iso
	Image type  = DVD
```

I'm worried this isn't related to _just booting_ and also might effect things whenever the disc is accessed.  Given the new odd logging behaviour, and it seeming to be related to the DVD booting, I'm wondering if it's related to the recent CDVD plugin merge into core - https://github.com/PCSX2/pcsx2/pull/3518

Historically we've seen frame-advancing cause things like cheats/settings to be reloaded, which we knew would need to be fixed eventually.  Perhaps the CDVD merge added something to that process which is actually a problem (the worst that happened with reloading cheats was just log spam).

Thanks for bringing this to our attention so soon, hopefully it's an easy fix.

**Comment by xTVaser** [comment] 2020-09-20 17:47
Yup just tested it, seems to be caused by the CDVD plugin merge / the plugin merge has highlighted an issue.  Using the following commit should allow you to workaround this until we resolve it. https://github.com/PCSX2/pcsx2/commit/11fe2619eb9299730a63e338d78959dff4754e4c

**Comment by refractionpcsx2** [comment] 2020-09-20 21:28
Can you try this again on the most recent CDVD commit I just made?

**Comment by xTVaser** [comment] 2020-09-20 21:51
On my end, latest commit on master (https://github.com/PCSX2/pcsx2/commit/551847411f99a98c94777176472c61b99b76549c) has resolved the issue.  🤞 @InfamousKnight reports the same.

**Comment by refractionpcsx2** [comment] 2020-09-20 21:52
Lovely job, I shall close this then :)

**Closed by refractionpcsx2** 2020-09-20 21:52 UTC
Labels: Bug, CDVD, High Priority, Regression, TAS Functionality
