### ISSUE TITLE
The Legend of Spyro: A New Beginning/Eternal Night Issues

### ISSUE THREAD

**Issue by KinDeDu** [PCSX2/pcsx2#1490] opened 2016-07-29 15:59 UTC
PCSX2 version: Official v1.4.0 release
CPU options: EE/IOP defaults, VUs defaults
Plugins used: GSdx 20160105132032 (MSVC 19.00, SSE41) 1.0.0 (gsdx32-sse4) (hardware and software, dx11), SPU2-X v2.0.0
Description: 
Missing HUD and Menu.
The game menu flashes. I tried to change to redering software but the menu disappears completely. Even the texts of the dialogues in the game are missing. I have some screenshots of my configuration. Does anyone have a solution to this?

This is a video showing the problem of the game menu:

https://youtu.be/492htE4V-tM
![pcsx2_coresettings_ee-iop](https://cloud.githubusercontent.com/assets/20727674/17254556/98897eee-55b5-11e6-9ca2-1a40ef6240f6.png)
![pcsx2_coresettings_gs window](https://cloud.githubusercontent.com/assets/20727674/17254557/988c0380-55b5-11e6-87f1-d555e32aa935.png)
![pcsx2_coresettings_gs](https://cloud.githubusercontent.com/assets/20727674/17254558/9892f410-55b5-11e6-9945-19b7dcac0e4b.png)
![pcsx2_coresettings_speedhacks](https://cloud.githubusercontent.com/assets/20727674/17254560/989de488-55b5-11e6-9d25-0a3665031917.png)
![pcsx2_coresettings_vus](https://cloud.githubusercontent.com/assets/20727674/17254561/989ead28-55b5-11e6-9f85-c8cee0374b0b.png)
![plugin](https://cloud.githubusercontent.com/assets/20727674/17254562/98a404bc-55b5-11e6-8285-fad52d64a9a5.PNG)
![configuration](https://cloud.githubusercontent.com/assets/20727674/17254563/98aa63ac-55b5-11e6-95e5-3b9889b66b15.PNG)
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/390911/emuLog.txt)
![missing menu](https://cloud.githubusercontent.com/assets/20727674/17254564/98ba1f72-55b5-11e6-8fe4-8d4455d27993.PNG)

**Comment by Nobbs66** [comment] 2016-07-30 03:43
would be nice to see what hardware hacks you're using.

**Comment by KinDeDu** [comment] 2016-07-30 07:02
In the graphics settings I enabled "enable HW Hacks" but I have not turned anything.

![hwhack](https://cloud.githubusercontent.com/assets/20727674/17268747/576ab19c-5634-11e6-8394-d79a893e06c3.PNG)

**Comment by MrCK1** [comment] 2016-07-30 13:52
Please close this. This user has illegally downloaded an .iso (Found in emulog.txt)

`D:\Nuova cartella (5)\ps2\Legend of Spyro, The - A New Beginning (Europe) (En,Fr,De,Es,It,Nl).iso`

**Comment by Mori-S** [comment] 2016-07-31 17:40
Well if he can't verify the dump is good then that's a problem. However I don't see how the file name proves he has an illegal backup. There's plenty of tools out there that will rename dumped IOS's like that

**Comment by Mori-S** [comment] 2016-08-01 03:47
Okay so the bug report is still valid though because I checked it against a verified dump by redump.org. The title screen flashes like he said.

**Comment by ssakash** [comment] 2016-08-01 12:55
> Please close this. This user has illegally downloaded an .iso (Found in emulog.txt)

Please explain, it's not immediately obvious to everyone on how it's a pirated content. Does ``Nuova cartella`` mean ``Downloads`` (or) something ?

Either way, making accusations isn't really nice without conclusive evidence.

**Comment by MrCK1** [comment] 2016-08-01 14:22
"Nuova cartella" means new folder in Spanish 😋

Anyways I pasted the .iso filename in Google, and it's a duplicate of the same file hosted on Emuparadise

**Comment by zuzma** [comment] 2016-08-01 15:28
That's how romcenter names files. If you dump the game from a real disc and use the redump.org database and fix the file name it'll be that

**Comment by FlatOutPS2** [comment] 2016-08-01 16:44
@MrCK1: I removed the website name from your post. Better not to inadvertently advertise those websites.

I doubt many people who legally own all their games would use an app like romcenter, but it's no proof of illegal downloading.

**Comment by jcdenton2k** [comment] 2016-08-04 03:05
Try to disable all speedhacks, widescreen hacks (if any) and cheats (if any) and see if the issues still persist.

**Comment by KinDeDu** [comment] 2016-08-04 09:37
I tried, but always graphical problems. With the NTSC version of the game the problem had been solved but for the PAL version the problem persists.

**Comment by jcdenton2k** [comment] 2016-08-05 01:24
Curious, this thread in the forums is from 2009:
http://forums.pcsx2.net/Thread-Bug-Report-The-Legend-of-Spyro-A-New-Beginning-PAL

And this is what the wiki shows:
http://wiki.pcsx2.net/index.php/The_Legend_of_Spyro:_A_New_Beginning

It seems that the NTSC version works without issues but the testing report is pretty sparse.
You should try to first use preset 1 (safest) and then uncheck it and make sure you do the following:

-Disable Cheats and Widescreen Patches.
-Try with DirectX 9, DirectX 11, and OpenGL renderers in both software and hardware modes.
-Uncheck the Enable Hardware Hacks.  Don't use any hacks at all.
-Finally, do all this with both the stable version and the latest Git version.

If none of this improves or changes the situation then feel free to post an update here.  There are far too many variables at the moment to properly diagnose the cause of this issue.

**Comment by KinDeDu** [comment] 2016-08-05 10:23
I tested it with the latest dev build, and I followed all your steps but the situation does not change. I tested with DirectX 9, DirectX 11, and OpenGL renderer In both hardware and software modes. I disabled Hardware Hacks but the menu and HUD flickers.

**Comment by jcdenton2k** [comment] 2016-08-05 14:59
That's a shame.  Hopefully you have your emulogs from your testing and you can send it to the devs so they can look into it.

**Comment by MrCK1** [comment] 2016-10-28 17:54
@KinDeDu any status update on this?

**Comment by KinDeDu** [comment] 2016-11-25 19:13
With the latest updates have not yet solved the problem. I hope you can solve.

**Comment by gregory38** [comment] 2016-11-26 11:08
And without any speedhack on the core level ?

**Comment by Dreadmoth** [comment] 2016-11-26 15:39
Can also confirm this issue: [Menu flicker gif](http://i.imgur.com/TSUCJEq.gif)
Occurs without speedhacks.

The only GSdx settings that have any effect are the renderer and CRC hack level:
Software: no HUD / main menu / subtitles
Hardware (any): flickering HUD / main menu / subtitles
CRC None: no HUD / main menu / subtitles (even on hardware renderers)

Subtitles over FMVs are partially visible (SW) / don't flicker (HW) if they are drawn on the letterbox area:

![Spyro_FMV_subtitles](https://cloud.githubusercontent.com/assets/8492684/20641233/78f413c6-b43f-11e6-9224-891352f17c85.png)

**Comment by KinDeDu** [comment] 2016-12-19 12:28
Has anyone found a solution for this problem?

**Comment by BlackHawk2306** [comment] 2017-04-18 01:09
Tested it today, the problem is still there. The main menu and subtitles are flickering, subtitles sometimes missing. It seems to have something to do with wether there is animated background behind it or not. That part of the subitltles, that is on the black border doesn't flicker, same for the next in the pause menu, wich has an image as background.I tried slowing the game down and lowering the framerate, by bumping up the resolution, it looks like the flicker rate is 50% of frame rate, probably apperaring/dissappearing with every full frame (it's the count of interlaced frames what you see in the counter, right?)

**Comment by MrCK1** [comment] 2017-04-18 01:23
@BlackHawk2306 There's no 1.6.0 stable yet. Not sure what version you're referencing.

**Comment by BlackHawk2306** [comment] 2017-04-18 01:52
oops, my bad, I meant version 1.4.0, I think it might be too late...

**Comment by arturdiez** [comment] 2017-06-29 10:12
any solution found guys?

**Comment by seanwee** [comment] 2017-09-15 15:05
Guys im running pcsx2 1.2.1 and it runs perfectly. No bugs no flashing, perfect.

**Comment by Dreadmoth** [comment] 2017-09-15 18:25
@seanwee 
Tried 1.2.1 - issues are still present for me on default settings (and all renderers).
Did you have to change any settings?

Maybe there is more than one PAL version of the game?

Detected PS2 Disc = cdrom0:\SLES_543.59;1
Software version = 1.01
Disc region type = PAL
Game CRC = 0x0EE5646B, EntryPoint = 0x00100008

Does yours match? It can be found in [PCSX2 install folder]\Logs\emuLog.txt after running the game.

**Comment by seanwee** [comment] 2017-09-16 02:22
I see the problem. Im using the SLUS version.

**Comment by seanwee** [comment] 2017-09-16 02:41
Isnt the EU and US version of the game the same?

**Comment by seanwee** [comment] 2017-09-16 02:41
I got my iso from EMUparadise

**Comment by seanwee** [comment] 2017-09-16 08:36
Anyways, does it have to be pal? Why not use an NTSC version?

**Comment by Papermanzero** [comment] 2017-09-16 13:22
yes. because of language selection.

**Comment by willkuer** [comment] 2017-09-16 14:11
And try to buy an ntsc game in europe. (Which wouldn't even run on your real console because of region lock IIRC)

**Comment by seanwee** [comment] 2017-09-16 16:08
But we arent running a real console are we now?

Any if you can read and type english here you'll do fine with the ntsc version of the game.

**Comment by seanwee** [comment] 2017-09-16 16:11
Good luck buying a real game cd for an 11 year old game short of buying a 2nd hand one.

**Comment by seanwee** [comment] 2017-09-16 16:11
Which DOES NOT GIVE ANY PROFIT TO THE DEVELOPERS.

**Comment by willkuer** [comment] 2017-09-16 19:15
The point is

1. We don't support piracy to avoid getting trouble with sony. There is no moral discussion piracy vs no piracy of 20 y/o games and strange copyright laws.
2. Thus we need to buy hard copies in local 2nd hand stores or abroad with large fees for transport
3. There was basically no exchange of ntsc games to pal regions and vice versa because they were not running on other consoles because of the region lock
4. Thus today there are basically no hard copies of ntsc games in pal regions and vice versa

So it is really hard to get a hard copy of an ntsc version in pal countries and vice versa.

------

Additionally the pcsx2 userbase is larger than the people posting at git. Your argument can be used to call the pcsx2 UI and guide translations useless. I actually like to play in English and use the gui in English although English is not my native language. Other people however prefer their native tounge.

**Comment by seanwee** [comment] 2017-09-17 05:43
So i guess dreadmoth got the answer he was looking for

**Comment by jcdenton2k** [comment] 2017-09-23 23:22
Just a thought:

Much of the last ~dozen comments or so is stuff that would've fit better on a forum or Discord server discussion.  Of course this is what happens when the hyperactive forum mods make people feel unwelcome to voice their concerns in a public fashion and resort to cluttering issues on Github with it instead.

I don't agree with what @seanwee posted but I understand why they'd choose to do so here rather than the forums.

If PCSX2 doesn't yet have a Discord server then it may be the time to get one and get some different people (not the current forum mods) who can look over that server instead.  Have the devs hang out there as well and occasionally deign to respond to us poor little peasants who complain loudly and often about something provided for free, hmm?

**Comment by MrCK1** [comment] 2017-09-24 01:00
@jcdenton2k We do have a discord and even though it's "unofficial" most of us hang out around there as well.

**Comment by seanwee** [comment] 2017-09-24 07:40
Eh, im kind of used to it already, this isnt the only place mods do that. Its kinda their responsibility after all ;)

Actually i usually just download variations of the same iso until one works. Havent had the need to upgrade from pcsx2 1.2.1 to whatever is the newest one. Its usually just the iso's fault.

**Comment by willkuer** [comment] 2017-09-24 07:57
So let's add some more off topic stuff? I posted 5k posts on the forum and got a single warning which vanished after one month or so. I got the warning in the beginning and I got it rightfully. So, with a sample size of 1 I counter your sample-size-of-1-bad-experience.

The people at forums.pcsx2.net are extremely helpful and friendly helping in their free time. There is basically just one rule you need to follow: Don't openly show that you download games from the web.

**Comment by seanwee** [comment] 2017-09-24 11:31
Are you adressing me?

**Comment by seanwee** [comment] 2017-09-24 11:42
Assuming you are addressing me, i wouldn't consider this a bad experience. The post edit(?) was rightly warranted.

Being a member of over 20+ forums from computers to cars, music, games and audiophile equipment i have gotten a lot of bad experiences before. So my sample size is about 60-70.

Look, I just saw this problem in github and thought i might be able to help. I just did it too insensitively(?). Given , ive seen takedowns of links to pirated game sites in a forum before but i didnt think it would still matter when you cant really get an original copy of the game anymore. As in a method that would actually support the developers and not a 2nd hand copy.

**Comment by MrCK1** [comment] 2017-09-24 14:22
It doesn't matter what your opinion on the matter is, the policies in place are there to protect the Integrity of the project. End of story.

**Comment by seanwee** [comment] 2017-09-24 15:21
Wow man , ouch.

**Comment by gregory38** [comment] 2017-09-24 16:21
Seriously guys, this is a working tool, a bug tracker exactly. It isn't the place for this kind of talk. 

Besides, the copyright law doesn't allow copy even if it isn't sold. 2nd hand market is allowed. It isn't about money for game developpers, it is about the Law. For example a game developper still get the right to port his game on android. Maybe you find the law silly, but it isn't us that make the Law ;)

**Comment by seanwee** [comment] 2017-09-26 00:35
Bottom line : If you want to play without issues, get a NTSC iso and play using PCSX2 v1.2.1

**Comment by Kyogre** [comment] 2017-12-04 14:23
I had the same "no HUD" problem on the Russian NTSC version. The cause of that bug was game's multiloader (it is menu with language selection that launches right after you open the game). To fix the problem I just applied patch that deletes all language except one and thus deletes multiloader. It is named SLUS-21372_ER-R.7z if you would like to keep only Russian language, SLUS-21372_ER-E if you want only English, SLUS-21372_E-ER if you want to reverse the changes back, but I am not sure about the third one. After applying the patch my game runs with HUD even if I choose default settings.

**Comment by lightningterror** [comment] 2017-12-04 15:02
This will be hard to fix. Thing is the PAL version, CRC 7ACF7E03 to be precise shares an id with ICO which is another games and has it's own set of CRC hacks, and other texture cache fixes.

I need the following:
gs dump or block dump with a savestate so I can run some tests.

**Comment by Kyogre** [comment] 2017-12-04 15:26
@lightningterror Am I right that you need dumps of exactly NTSC patched english working version?

**Comment by lightningterror** [comment] 2017-12-04 15:29
I actually need dumps from the PAL version, but NTSC can help as well. If I can reproduce the issue then I'll know if it's an easy fix or not ( well for me at least ).

**Comment by Kyogre** [comment] 2017-12-04 16:21
1. here is GSdumps for menu and ingame https://www.mediafire.com/file/a8m5z62deyqarra/SLUS_21372%20GSdumps.zip
2. I have file named SLUS_213.72(Eng) (2017-11-04 19-10-49).dump that weighs 130 MB. Do you need it?
3. I still don't understand what savestate you need. Tell me, please
4. I have only NTSC version, so I can't provide dumps for PAL

**Comment by lightningterror** [comment] 2017-12-04 16:30
Yea that's the block dump, you can compress it in a zip btw.
As for savestate = sstates, when you press F1 to save your progress.

You should create the block dump from booting the emulator and playing a little in the game, saving the progress and exiting after.

**Comment by Kyogre** [comment] 2017-12-04 18:08
So you need dumps when I am using ISO with working HUD. Am I right? Or you need dumps when I am using ISO with broken HUD?
When I need to make savestate: in game's main menu or in game?

**Comment by lightningterror** [comment] 2017-12-04 18:11
I need a savestate in game where the hud works/is broken with a block dump.

**Comment by Kyogre** [comment] 2017-12-04 18:28
Created block dump for "HUD works" conditions and it weighs 3.6 GB. Of course, I will upload it to Mega, but haven't I done something wrong? Because, I still can't believe that it is so big.

**Comment by Kyogre** [comment] 2017-12-04 18:50
I created block dumps for both conditions and they weigh 3.6 and 2.4 GB. Haven't I done something wrong? Because, I still can't believe that they are so big. Here they are: https://mega.nz/#F!Ik8EUaAZ!I1U_aONIx5UjIbbdZl--9w

**Comment by Kyogre** [comment] 2017-12-04 19:20
contact me after you download all the dumps, because I don't want to keep these dumps on my Mega for too long time

**Comment by lightningterror** [comment] 2017-12-04 19:50
Oh you didn't compress them in rar or zip before uploading them. Add them in an archive before uploading and make sure you select Best compression. They should be reduced to around 50MB in size.

**Comment by Kyogre** [comment] 2017-12-05 10:42
@lightningterror I updated the link

**Comment by lightningterror** [comment] 2018-01-09 03:31
Well this is weird. Hardware mode the HUD keeps blinking.
Software mode the HUD doesn't appear at all. So HW mode is a bit better in that regard. HW misses the dragon logo in the game startup sequence tho.

**Comment by Dreadmoth** [comment] 2018-01-09 13:32
@lightningterror If [this](https://i.imgur.com/qYdi7Xw.png) is the logo you're referring to, it appears if the Preload Frame Data hack is enabled.

Blockdump + GS dump + Save State from PAL version: https://drive.google.com/open?id=1AQ5vQ25qz7wmisKKYCBB7QY1xrqFtTZ2

**Comment by lightningterror** [comment] 2018-01-09 13:34
Ah yea, guess I forgot to test that with hacks.

**Comment by lightningterror** [comment] 2018-01-13 22:28
Small update. The crc hack is what actually causes the menu to flicker if enabled. If crc hacks are disabled then software and hardware mode behave the same.

**Comment by lightningterror** [comment] 2018-01-13 23:01
Well the flickering is related to this code here. Clearing depth. Without it hardware behaves the same like software on the menu.

https://github.com/PCSX2/pcsx2/blob/4aa25c497137c0167b43473ffa7b97d50ddb52e0/plugins/GSdx/GSRendererHW.cpp#L1566

**Comment by Maedoster** [comment] 2018-04-07 20:08
@lightningterror some news? I'm actually interested in this game and wanna find out what's the problem with flickering ;D

**Comment by lightningterror** [comment] 2018-05-20 14:41
Hardware mode should be good now on the PAL version.
Software mode still has issues.

**Comment by lightningterror** [comment] 2018-05-21 02:27
@Kyogre can you retest latest dev build ?

**Comment by Kyogre** [comment] 2018-05-25 16:37
@lightningterror Even if I don't have PAL version? And with which settings I need to test?

**Comment by lightningterror** [comment] 2018-06-02 01:46
Please test #2467
Both hardware and software should be fine now.

**Closed** 2018-06-02 10:38 UTC
Labels: Bug, Core, Workaround Possible
