### ISSUE TITLE
Git Version - Text Cut Off In Intro GUI

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#1032] opened 2015-12-11 05:01 UTC
I just compiled the latest git version from source in Slackware.

I compiled wxWidgets-3.0.2 against GTK2, and when I start PCSX2 for the first time and get the introduction GUI, I noticed text is being cut off. Please see the screen shots...

![pcsx2_1](https://cloud.githubusercontent.com/assets/13072581/11736278/f6ce80ba-9fc3-11e5-97c4-f6dd3265e422.png)

Next screen

![pcsx2_2](https://cloud.githubusercontent.com/assets/13072581/11736311/4dc42ed8-9fc4-11e5-984b-87eb6c706f46.jpg)

**Comment by turtleli** [comment] 2015-12-11 09:01
What GTK2 theme are you using?

Btw, you need to specify the actual git revision - "latest" is useless once new commits are pushed.

**Comment by Geyup** [comment] 2015-12-11 10:03
Sorry;  ```PCSX2 1.3.1-20151207111040```

This text cutting off happens with any GTK2 theme I'm using...

**Comment by gregory38** [comment] 2015-12-11 11:43
Are you sure that PCSX2 is linked with WX3? Could you do a `ldd path_to/PCSX2`
Could you test GTK3. There is an option to enable it at build time (like GTK3_API)

**Comment by Geyup** [comment] 2015-12-12 07:39
Ok I'll try with gtk3 and below is ldd.

ldd /usr/bin/32/PCSX2

```


	linux-gate.so.1 (0xf7755000)
	libwx_baseu-3.0.so.0 => /usr/lib/libwx_baseu-3.0.so.0 (0xf74a6000)
	libwx_gtk2u_core-3.0.so.0 => /usr/lib/libwx_gtk2u_core-3.0.so.0 (0xf6fde000)
	libwx_gtk2u_adv-3.0.so.0 => /usr/lib/libwx_gtk2u_adv-3.0.so.0 (0xf6e58000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0xf6dc8000)
	libgtk-x11-2.0.so.0 => /usr/lib/libgtk-x11-2.0.so.0 (0xf695e000)
	libgdk-x11-2.0.so.0 => /usr/lib/libgdk-x11-2.0.so.0 (0xf68af000)
	libcairo.so.2 => /usr/lib/libcairo.so.2 (0xf6775000)
	libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0xf672b000)
	libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0xf671f000)
	libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0xf670a000)
	libpangoxft-1.0.so.0 => /usr/lib/libpangoxft-1.0.so.0 (0xf6702000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0xf66e0000)
	libgthread-2.0.so.0 => /usr/lib/libgthread-2.0.so.0 (0xf66de000)
	libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0xf66da000)
	libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0xf6572000)
	libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0xf6551000)
	libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0xf6503000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0xf63d5000)
	libz.so.1 => /lib/libz.so.1 (0xf63bf000)
	libaio.so.1 => /lib/libaio.so.1 (0xf63bc000)
	librt.so.1 => /lib/librt.so.1 (0xf63b3000)
	libdl.so.2 => /lib/libdl.so.2 (0xf63ae000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xf62c6000)
	libm.so.6 => /lib/libm.so.6 (0xf6284000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xf626a000)
	libpthread.so.0 => /lib/libpthread.so.0 (0xf6250000)
	libc.so.6 => /lib/libc.so.6 (0xf60c3000)
	/lib/ld-linux.so.2 (0x565b2000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0xf608a000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0xf5f53000)
	libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0xf5f4e000)
	libSM.so.6 => /usr/lib/libSM.so.6 (0xf5f46000)
	libnotify.so.4 => /usr/lib/libnotify.so.4 (0xf5f3e000)
	libpng14.so.14 => /usr/lib/libpng14.so.14 (0xf5f13000)
	libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0xf5edb000)
	libtiff.so.3 => /usr/lib/libtiff.so.3 (0xf5e78000)
	libbz2.so.1 => /lib/libbz2.so.1 (0xf5e67000)
	libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0xf5e63000)
	libXi.so.6 => /usr/lib/libXi.so.6 (0xf5e54000)
	libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0xf5e4a000)
	libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0xf5e40000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0xf5dae000)
	libicule.so.51 => /usr/lib/libicule.so.51 (0xf5d5b000)
	libicuuc.so.51 => /usr/lib/libicuuc.so.51 (0xf5c0a000)
	libicudata.so.51 => /usr/lib/libicudata.so.51 (0xf46bf000)
	libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0xf46bc000)
	libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0xf46b9000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0xf46b4000)
	libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0xf462c000)
	libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0xf4629000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0xf4627000)
	libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0xf461e000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0xf4614000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0xf4601000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0xf45e1000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0xf45de000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0xf45d8000)
	libresolv.so.2 => /lib/libresolv.so.2 (0xf45be000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0xf4597000)
	libffi.so.6 => /usr/lib/libffi.so.6 (0xf4590000)
	libEGL.so.1 => /usr/lib/libEGL.so.1 (0xf44f7000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0xf43f3000)
	libXft.so.2 => /usr/lib/libXft.so.2 (0xf43dd000)
	libICE.so.6 => /usr/lib/libICE.so.6 (0xf43c4000)
	libuuid.so.1 => /lib/libuuid.so.1 (0xf43c0000)
	libnvidia-glsi.so.352.41 => /usr/lib/libnvidia-glsi.so.352.41 (0xf433c000)
	libnvidia-tls.so.352.41 => /usr/lib/tls/libnvidia-tls.so.352.41 (0xf4337000)
	libnvidia-glcore.so.352.41 => /usr/lib/libnvidia-glcore.so.352.41 (0xf2168000)
```

**Comment by Geyup** [comment] 2015-12-12 09:08
Compiling against wxgtk3 it fails to compile.

This is my wxGTK3 compile flags;

```
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --enable-shared \
  --enable-mediactrl \
  --with-opengl \
  --enable-graphics_ctx \
  --with-gtk=3 \
  --enable-unicode \
  --enable-plugins \
  --enable-ipv6 \
  $stl \
  --build=$ARCH-slackware-linux
```

This is the output from the terminal trying to compile pcsx2;

```
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/32/gcc
-- Check for working C compiler: /usr/bin/32/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/32/g++
-- Check for working CXX compiler: /usr/bin/32/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Cross compilation is disabled.
-- Compiling a i386 build on a x86_64 host.
-- Enable the building of po files by default in Release build !!!
CMake Error at cmake/BuildParameters.cmake:351 (message):
  GTK3 is highly experimental besides it requires a wxWidget built with
  __WXGTK3__ support !!!
Call Stack (most recent call first):
  CMakeLists.txt:59 (include)


-- Configuring incomplete, errors occurred!
See also "/tmp/sar/pcsx2-12.11.15/build/CMakeFiles/CMakeOutput.log".
```

This is the output from CMakeOutput.log;

http://dpaste.com/2SBY0MC

**Comment by turtleli** [comment] 2015-12-12 11:23
Hmm. I just noticed that your font size seems much larger than mine - that's probably what's causing the problem.

**Comment by Geyup** [comment] 2015-12-12 23:37
@turtleli font size might be the problem, but the application should adjust to any size, or type....

I use Openbox, and this is my obconf settings.

![obconf](https://cloud.githubusercontent.com/assets/13072581/11764467/5b268588-a129-11e5-9aa9-812f0664f160.jpg)

**Comment by Geyup** [comment] 2015-12-12 23:39
But for now I'd like to be able to test out GTK3 but it's not compiling against it...

hmm

**Comment by turtleli** [comment] 2015-12-12 23:57
Two different methods to compile against WXGTK3 built against GTK3:
 - Compile a devel release (`-DCMAKE_BUILD_TYPE=Devel`)
 - Comment/remove the last 5 lines in cmake/BuildParameters.cmake

**Comment by Geyup** [comment] 2015-12-13 00:24
Comment or remove these?

```
if(CMAKE_BUILD_TYPE MATCHES "Release" OR PACKAGE_MODE)
    if (GTK3_API)
        message(FATAL_ERROR "GTK3 is highly experimental besides it requires a wxWidget built with __WXGTK3__ support !!!")
    endif()
```

thank you

**Comment by turtleli** [comment] 2015-12-13 00:27
Yes

**Comment by Geyup** [comment] 2015-12-13 00:29
Ok I'll make a little patch then and brb...

thanks

**Comment by Geyup** [comment] 2015-12-13 00:35
Ok a patch for the masses! LOL

https://gist.github.com/Geyup/fda6af2c5c4cb999d225

**Comment by Geyup** [comment] 2015-12-13 01:09
Ok it compiled, does the package contents look ok?

```
./
install/
install/doinst.sh
install/slack-desc
usr/
usr/bin/
usr/bin/32/
usr/bin/32/PCSX2-linux.sh
usr/bin/32/PCSX2
usr/lib/
usr/lib/pcsx2/
usr/lib/pcsx2/libspu2x-2.0.0.so
usr/lib/pcsx2/libFWnull-0.7.0.so
usr/lib/pcsx2/libonepad-1.1.0.so
usr/lib/pcsx2/libUSBnull-0.7.0.so
usr/lib/pcsx2/libGSdx-1.0.0.so
usr/lib/pcsx2/libCDVDnull.so
usr/lib/pcsx2/libdev9null-0.5.0.so
usr/man/
usr/man/man1/
usr/man/man1/PCSX2.1.gz
usr/share/
usr/share/pixmaps/
usr/share/pixmaps/PCSX2.xpm
usr/share/doc/
usr/share/doc/PCSX2/
usr/share/doc/PCSX2/PCSX2_Readme.pdf
usr/share/doc/PCSX2/PCSX2_FAQ.pdf
usr/share/pcsx2/
usr/share/pcsx2/cheats_ws.zip
usr/share/pcsx2/GameIndex.dbf
usr/share/applications/
usr/share/applications/PCSX2.desktop
usr/doc/
usr/doc/pcsx2-12.12.15/
usr/doc/pcsx2-12.12.15/License.txt
usr/doc/pcsx2-12.12.15/pcsx2.SlackBuild
usr/doc/pcsx2-12.12.15/readme-Docs.txt
usr/doc/pcsx2-12.12.15/PCSX2_Readme.doc
usr/doc/pcsx2-12.12.15/PCSX2_FAQ.doc
usr/doc/pcsx2-12.12.15/GPL.txt
```

**Comment by Geyup** [comment] 2015-12-13 01:17
I'm using ```wxGTK3-3.0.2``` & ```gtk+3-3.8.2``` Slackware 14.1 still uses an older version of GTK3.

Compiled against wx3 with gtk3 support, the gui still looks the same.

![p1](https://cloud.githubusercontent.com/assets/13072581/11764825/30ca7796-a137-11e5-93f8-9df4340bde0a.jpg)


![p2](https://cloud.githubusercontent.com/assets/13072581/11764826/379fca8a-a137-11e5-8e5e-1ee56219d464.jpg)

**Comment by i30817** [comment] 2015-12-13 07:45
I think pcsx2 has some windows that are fixed size. For example i can't resize the graphics gdsx plugin options (and i'd really really like to make them smaller (smaller text or the introduction of a scrollbar depending on coding)  since not all options are visible on gnome-shell at 768 height.

**Comment by turtleli** [comment] 2015-12-13 12:03
Well, I don't know where the issue is. The GTK3 one looks especially weird. Here's how it looks for me with GTK3, Adwaita theme with Fluxbox, Slackware64-current with 32-bit chroot:

![wawa](https://cloud.githubusercontent.com/assets/10976277/11766822/372249da-a190-11e5-8469-c8ad2deb2ab2.png)
![wawa2](https://cloud.githubusercontent.com/assets/10976277/11766823/3d3490f8-a190-11e5-9483-2c4c064cbd8b.png)

**Comment by Geyup** [comment] 2015-12-13 22:45
@turtleli sorry where's this weird you are talking about? I don't see anything wrong with the gui...

hmm

**Comment by turtleli** [comment] 2015-12-13 22:47
I mean your screenshots - the font is small in some areas for no apparent reason.

**Comment by Geyup** [comment] 2015-12-13 22:58
Oh I thought you were talking about yours looking weird LOL...

I bet it's the difference in GTK versions, because I just tried it with Adwaita.

Slack current uses gtk 3.18.5 and 14.1 uses 3.8.2

**Comment by turtleli** [comment] 2015-12-13 23:08
I don't think I had those problems with GTK3 when I was still using 14.1.

Does Openbox override the GTK theme settings? Does it look correct using other Window managers or desktop environments?

**Comment by Geyup** [comment] 2015-12-13 23:30
For themes in Openbox, obconf only changes the Openbox menu. For GTK theming I use LXAppearance to theme applications.

I don't have any other Window Mangers or DE to test this out in.

Also here's something I finally realize after looking at your GUI screen shots, that cut off text on mine, the ```style``` ```font``` look of the text for me does not change. But in your screen shots it's taking on the same looking fonts as the rest of the GUI... Hmm

**Comment by Geyup** [comment] 2015-12-13 23:33
This is how my ~.config/gtk-3.0/settings.ini looks;

```
[Settings]
gtk-theme-name=Numix Flatstudio
gtk-icon-theme-name=NouveGnomeGray
gtk-font-name=Aller 9
gtk-cursor-theme-name=Ecliz-orange
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=0
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb
```

**Comment by willkuer** [comment] 2015-12-13 23:46
I'd rather sa the label width is the issue here. For some reason your labels are too small. Thats why you get additional linebreaks. And as the labels hight doesnt autoscale with content your text gets clipped.

**Comment by Geyup** [comment] 2015-12-13 23:50
Please take a screen shot of the first window.

I get the feeling my text is not changing to the fonts I'm using, so I want to see yours.

Here is mine;

![1](https://cloud.githubusercontent.com/assets/13072581/11770374/4e542b32-a1f4-11e5-84a8-e04dccbdaf09.jpg)

**Comment by Geyup** [comment] 2015-12-13 23:53
By the way, looking backup at my GTK2 screen shots, the small text does change, but it's still cut off.

What lables are you referring too, I don't understand?

**Comment by turtleli** [comment] 2015-12-14 00:35
willkuer means the areas of text you are having issues with.
My GTK3 theme settings only has
```
[Settings]
gtk-theme-name = Adwaita
```
(well, customising is a pain)

I won't provide a screenshot since it doesn't add any new information - the font differences are already clearly visible in the previous screenshots.

**Comment by Geyup** [comment] 2015-12-14 00:48
Where is this label adjustment suppose to come from GTK or wxwidget?

Your  ~.config/gtk-3.0/settings.ini only has in it?

```
[Settings]
gtk-theme-name = Adwaita
```

In my last screen shot, what I was trying to point out is the smallest text you are seeing in that screen shot, does not change to the font I'm using, but I'm assuming it does for you, that is why I was asking for a screen shot to see, because it appears to be changing for you in the other windows, and this is what I'm  trying to figure out why it changes for you with GTK3 and not for me.

But as I mentioned it changes in GTK2 but still the font is cut off.

**Comment by turtleli** [comment] 2015-12-14 17:18
> Where is this label adjustment suppose to come from GTK or wxwidget?

Probably PCSX2. I need to analyse the code.

> Your ~.config/gtk-3.0/settings.ini only has in it?

Yes.

**Comment by Geyup** [comment] 2015-12-14 23:13
label ok, seems strange that it would work different in different WMs and DEs... I personally didn't think a WM or DE controlled this...  hmm

Hmm your settings.ini, that's odd, I thought they would all have about the same amount of info, ok...

**Comment by gregory38** [comment] 2016-11-08 23:51
Not sure it is relevant but I just found this code in wx
```
void wxControl::PostCreation(const wxSize& size)
{
    wxWindow::PostCreation();

#ifndef __WXGTK3__
    // NB: GetBestSize needs to know the style, otherwise it will assume
    //     default font and if the user uses a different font, determined
    //     best size will be different (typically, smaller) than the desired
    //     size. This call ensure that a style is available at the time
    //     GetBestSize is called.
    gtk_widget_ensure_style(m_widget);
#endif

    SetInitialSize(size);
}
```

**Comment by Geyup** [comment] 2016-11-11 03:41
@gregory38 HI!

Since the post Slackware has FINALLY come out with a new version; 14.2

I have since moved to 14.2 and I'm not doing multilib at present.

Not sure if I'm going to bother with multilib in Slackware anymore, and I REALLY WISH PCSX2 was 64 bit capable...

**Comment by gregory38** [comment] 2016-11-11 10:29
You know, at least multilib is enough to run the app. For dev it is cumbersome. I hack/recompile the full gtk stack of my distribution...

Anyway, I think I foumd the issue. I will do a pr later.

**Comment by Geyup** [comment] 2016-11-12 02:17
I know multilib is enough to run the app, I just don't feel like messing with it any more in my box...

**Comment by gregory38** [comment] 2016-11-12 12:15
Yeah, Yeah I understand. That being said, you can run PCSX2 on 64 bits. Gui is fine, and you can even boot game if you use the HW renderer and all interpreters.

```
32bit just needs to die IMHO!
```
Why ? Any technical reason ? To save 1GB of HDD ?
Because distribution never managed to move a couple of lib from `/usr/lib` to something more clever ? Removing 32 bits might help here, but problem appear again if you want to cross-compile (ARM, ARMV8...).

**Comment by Geyup** [comment] 2016-11-13 00:55
You can run  PCSX2 on 64 bits but it can't be compiled on x64?

32bit vs 64bit, why? One simple reason, better processors on the 64bit ARCH over 32bit for one reason, of course I'm talking Intel platform.

Why anyone would game on ARM is beyond me, it's not a gaming platform...

Anyhow...

**Comment by gregory38** [comment] 2016-11-14 12:04
No, you can either
* compile a 32 bits PCSX2 and run it with 32 bits (multiarch) libs. As all CPU supports 32 bits instructions at full speed.
* compile a 64 bits PCSX2 and run it with 64 bits libs. Perf will suck because recompiler won't be supported. And you need GSdx HW (but hopefully SW will work too soon).

```
32bit vs 64bit, why? One simple reason, better processors on the 64bit ARCH over 32bit
```
I'm currently looking to port GSdx SW renderer on 64 bits. So far, 64 bits seem to save a couple of move but I doubt it will provide any real boost on the performance. But at least, we could benchmark on the GS side.

**Comment by Geyup** [comment] 2016-11-16 01:44
Thanks...

**Comment by jcdenton2k** [comment] 2016-11-16 06:09
Some relevant reading @gregory38 
http://www.geoffchappell.com/notes/windows/license/memory.htm

**Comment by gregory38** [comment] 2016-11-17 09:50
64 bits topic => http://forums.pcsx2.net/Thread-GSDX-Software-mode-Wanna-bet-on-64-bits-performance

On the font topic, I need to split my wx font pr to integrate some fixes in git. Stay tuned.

**Comment by gregory38** [comment] 2016-11-19 10:30
@Geyup could you test latest version of PCSX2 ? 
If you want a 64 bits build:
```
./build.sh --prof --clean --no-cross-multilib 
```

**Comment by Geyup** [comment] 2016-11-20 06:23
I'm compiling from a build script and these are my compile flags below, so how would I add in these changes you are showing?


mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DWX28_API=TRUE \
    -DBIN_DIR=/usr/bin/32 \
    -DDOC_DIR=/usr/doc/$PRGNAM-$VERSION \
    -DCMAKE_LIBRARY_PATH=/usr/lib \
    -DGAMEINDEX_DIR=/usr/share/pcsx2 \
    -DPLUGIN_DIR=/usr/lib/pcsx2 \
    -DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/32/wx-config \
    -DwxWidgets_wxrc_EXECUTABLE=/usr/bin/32/wxrc-2.8 \
    -DDISABLE_PCSX2_WRAPPER=TRUE \
    -D{PACKAGE_MODE,XDG_STD}=ON \
    -DCMAKE_BUILD_TYPE=Release ..
        
  make
  make install DESTDIR=$PKG
cd ..

**Comment by seta-san** [comment] 2022-02-11 17:49
This isn’t a problem anymore in qt is it?

**Comment by F0bes** [comment] 2022-02-11 17:52
That's why the GUI/Qt label is added here. We aren't closing Wx issues as Wx is still used by default in dev builds.

**Comment by lightningterror** [comment] 2022-05-10 14:27
Shouldn't be a problem on Qt, won't be addressed on wx.

**Closed by lightningterror** 2022-05-10 14:27 UTC
Labels: OS: Linux, GUI/WX, GUI/Qt
