### ISSUE TITLE
OpenGL=>Full Screen=>Esc=>the window is not closed

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#820] opened 2015-09-13 08:20 UTC
If you go full screen while using OpenGL,if you try to directly close the window(Esc)rather than first exiting full screen,few seconds after pressing Esc,the music will stop and the game screen will stay.

The only way to exit is by using any of the mouse buttons,Alt+Tab or the windows key
Works fine with Direct3D 9\\11

**Comment by yorkiesandskittles** [comment] 2015-09-13 10:45
Does using Alt+Enter work?

**Comment by vsub** [comment] 2015-09-13 11:54
Alt+Enter allows me to go full screen(the same as double click which I use)but I'm talking about pressing Esc while in full screen.
In OGL mode,the game screen freeze when you press Esc while in full screen.
Pressing Alt+Enter after the game window freeze does nothing

**Comment by hellbringer616** [comment] 2015-09-16 15:25
i can confirm this happens to me as well.
I don't think this was always the case, I'll check once I'm home and see if one of my older builds doesn't have this issue.

**Comment by turtleli** [comment] 2015-09-16 16:33
I'm wondering whether it's wxWidgets 3.0 related. I know that sounds strange since only OpenGL has symptoms, but shinra358 reported this problem on the GSdx 1.0 thread quite a while back (7/30/2015), just after the wxWidgets 3.0 transition.

Does the problem exist in pcsx2.exe from the v1.3.1-807-g5c58bd2 build?

And could you provide PC specs (including GPU driver version)? I think you are both using Windows 7 64-bit, NVIDIA GPU of some sort.

**Comment by vsub** [comment] 2015-09-16 17:15
Hmm,yes it's wxWidgets 3.0 related
 v1.3.1-807-g5c58bd2 - works fine
v1.3.1-813-g7aa3613 - problem exist

i7 4771,GTX750TI\HD4600(happens on both cards so it can't be drivers related),Win7 x64

**Comment by hellbringer616** [comment] 2015-10-01 19:31
Just realized i never gave you my specs, sorry about that.
OS: Win7 64-bit
CPU: 4590k
GPU: GTX 680
Driver: 353.52

Did some testing and found the issue does not happen with Lilypad, however it does happen with Pokopom v2 (r127)

**Comment by avih** [comment] 2015-10-01 19:57
> Did some testing and found the issue does not happen with Lilypad, however it does happen with Pokopom v2 (r127)

Interesting. Do you have the "Safe fullscreen exit on escape" checked at the Lylipad config?

/me thinks we should maybe move this functionality into PCSX2 itself, and hide it in Lylipad.

**Comment by ramapcsx2** [comment] 2015-10-06 15:05
@hellbringer616 Could you verify if Lilipad works for you because of its "Safe fullscreen exit on escape" hack? Once we know that, we can fix it.

**Comment by avih** [comment] 2015-10-06 15:08
@vsub could you please confirm if it's related to LilyPad's "Safe fullscreen exit on escape"? I.e. does it cause the issue or fix the issue?

I want to remove this hack from LilyPad and fix it in PCSX2 itself, but so far whatever I try it always exits "safely" from full screen also without this hack enabled and also in OpenGL HW rendering. So I won't remove the hack before I can see what actual issue it fixes, so maybe you could help here.

**Comment by hellbringer616** [comment] 2015-10-06 15:12
Sorry guys, i've been sick, Yes "Safe fullscreen exit on escape" was enabled and if i disable it i get the same result as Pokopom

**Comment by ramapcsx2** [comment] 2015-10-06 15:32
Thanks :)
Could you paste the last couple of lines of your emulog when it happens?

**Comment by hellbringer616** [comment] 2015-10-06 15:40
not sure if you;ll find anything of use with this, says the same if Lilypad has the safe fullscreen exit on escape checked

>Closing plugins...
	Closing DEV9
	Closing FW
	Closing USB
	Closing CDVD
	Closing SPU2
	Closing PAD
	Closing GS
Plugins closed successfully.

**Comment by avih** [comment] 2015-10-06 16:22
@vsub @hellbringer616 I just tried to fix this within PCSX2 itself such that the LilyPad hack is not required anymore, which also hopefully make ESC on fullscreen work with other input plugins.

I'd appreciate if you can confirm once the buildbot has the new build ready, or if you can build yourself directly from master.

If this is successful, then I'll either remove this hack from LilyPad, or just make it not enabled by default.

**Comment by vsub** [comment] 2015-10-06 16:34
Ok I will when the buildbot compile it but in the mean time,I have one question(since I can't try it yet)
Did you tried pressing Esc while in full screen while using the command line --noguiprompt.

At least here on v1.3.1-1208-g9eadf35,the dialog is created behind the game window while I'm in full screen.
I can't do anything except Enter to choose ok or Esc again to close the dialog which I don't see

**Comment by avih** [comment] 2015-10-06 16:48
> At least here on v1.3.1-1208-g9eadf35,the dialog is created behind the game window while I'm in full screen.

It doesn't happen for me (neither with the Intel GPU nor with the AMD GPU), but it's probably related to specific drivers, or driver bugs, so maybe I'm just lucky with it.

This revision doesn't suspend emulation when you press ESC during fullscreen, so depending on how the driver handles PCSX2's fullscreen (it might make it exclusive even if PCSX2 doesn't ask it to), it might happen indeed. I'd ask you to also try e4d8af0c97875526a325aa941c6d9acf7152e183 which suspends emulation for this confirmation, but I think the buildbot is broken, since it doesn't have builds for few hours old revisions.

Gimme few mins though, I'll make test builds for both e4d8af0c97875526a325aa941c6d9acf7152e183 which suspends during the --noguiprompt confirmation, and also the currently latest which tries to emulate the Lilypad hack internally.

Stay tuned.

**Comment by avih** [comment] 2015-10-06 17:11
Please try this: https://0x0.st/zhv.7z (it includes two pcsx2.exe files only, so put it where your PCSX2 folder is, and rename it to `pcsx2.exe` if your GPU driver picks the GPU according to the exe name).

It includes 1215 and 1218.
1215 suspends emulation for `--noguiprompt`
1218 also has the internal fullscreen ESC hack.

Let me know how each of them behaves when the LilyPad "Safe fullscreen exit on escape" hack is _disabled_. Thanks.

**Comment by vsub** [comment] 2015-10-06 17:24
1215 - the main problem in this issue is not fixed but the weird thing is that only when I use --nogui --noguiprompt,the full screen freeze happens only once.
If I press Esc while in full screen,the dialog will appear behind but if I press Esc to close that dialog and press Esc again,from now one,pcsx2 will always correctly exit full screen and display the prompt

1218 - everything works correctly but it looks like the lilypad option must be removed.If the option is enabled,I still get the same results(works fine)but there is some 1 or 2 seconds delay before pcsx2 react to the ESC

**Comment by avih** [comment] 2015-10-06 17:29
Thanks for testing. So it sounds like it does manage to fix the issue without the help of external hacks, correct?

> 1218 - everything works correctly but it looks like the lilypad option must be removed.If the option is enabled,I still get the same results(works fine)but there is some 1 or 2 seconds delay before pcsx2 react to the ESC

Not sure I understand this comment though. Why "must" it be removed? Does it now behave worse than before when the LilyPad hack is enabled?

**Comment by vsub** [comment] 2015-10-06 17:34
Actually,no...the hack works the same way(I just tried with DX11)when it's enabled and when it's disabled but with the latest change,I can exit full screen by just pressing Esc while using OGL

Maybe the hack wait for something before closing the window and because of that "something",there is a delay.
If I disable the hack,it exit full screen instantly(no delay)

**Comment by avih** [comment] 2015-10-06 17:37
So are these correct?
- When the LilyPad hack is enabled in 1218 - it behaves the same as before when the LilyPad hack was enabled.
- When the LilyPad hack is disabled in 1218 - it behaves correctly, and better than before when the LilyPad hack was enabled (because now it doesn't have the lag).

**Comment by vsub** [comment] 2015-10-06 17:45
Before:
DX9\11 with the hack - 1 second delay
DX9\11 without the hack - instant exit from full screen
OGL with the hack - 1 second delay and then freeze(kinda)
OGL without the hack - instant freeze(kinda)

With the latest change everything is the same(about the hack)but this time,the game window don't freeze  when you press Esc while using OGL.

So yes,problem solved

**Comment by avih** [comment] 2015-10-06 17:55
Hmm.. then I don't think I get it.

You say that with older releases - even with the LilyPad hack there was an issue (with OGL)? I had the impression the LilyPad hack was fixing this issue. Didn't it?

It seems to me that at least @hellbringer616 says that the LilyPad hack fixed it, so it did for him but didn't for you? (it's possible, I'm just trying to make sure all the scenarios are coveres).

> OGL with the hack - 1 second delay and then freeze(kinda)
> OGL without the hack - instant freeze(kinda)

So this is before. After it's the same only without the freeze (i.e. exits correctly), yes?

**Comment by vsub** [comment] 2015-10-06 18:03
> So this is before. After it's the same only without the freeze (i.e. exits correctly), yes?

The hack behaves the same way as before and at least here,it doesn't help fixing the problem(which is actually fixed now with your last update).
Enabling\Disabling it now,behaves the same way if OGL mode as when I use DX...delay when its enabled and instant exit when it's not...no freezing anymore

**Comment by avih** [comment] 2015-10-06 18:20
Thanks, then I can only conclude that you (vsub) and hellbringer616 are having a different issue, but with similar symptoms.

For vsub the issue only happened with OGL and was _not_ fixed by the LilyPad hack. We now know 1218 fixes this issue for vsub, and also doesn't make it worse when enabling the LilyPad hack in 1218. So vsub's bug is fixed.

For @hellbringer616 , he says he has "the same issue", but we know that for him the LilyPad hack does fix it, so it's probably a different issue.

What we still don't know is:
- Whether or not 1218 works correctly for @hellbringer616 and doesn't have any issue when the LilyPad hack is disabled or when using Pokopom v2 (r127).
- Whether or not 1218 with the LilyPad hack enabled behaves worse (in whatever way) than older builds with the LiliPad hack enabled.

@hellbringer616, could you please answer the above questions? (only for 1218 compared to a recent build you already have which has the bug).

Take 1218 from here https://0x0.st/zhv.7z , extract it to your existing pcsx2 folder and rename `pcsx2-test-v1.3.1-1218-g9c1688a~internal-hack-fullscreen-esc.exe` to `pcsx2.exe` (to replace your existing pcsx2.exe) before you test. Thanks.

**Comment by avih** [comment] 2015-10-06 18:38
On somewhat related news, the buildbot is operational again (thanks Orphis), and 1218 is now available for download also from the buildbot.

**Comment by avih** [comment] 2015-10-06 18:45
@vsub did you by any chance configur the KB shortcut to toggle fullscreen?

The LilyPad hack works by "injecting" alt+enter just after you press escape (only if it's fullscreen), and then another alt+enter when pcsx2 resumes (if it's not fullscreen). alt+enter is the default pcsx2 shortcut to toggle fullscreen, so if you have a different one, then it will explain why the hack doesn't work for you, and maybe it is the same issue afteral.

**Comment by vsub** [comment] 2015-10-06 18:54
I enter full screen by double click and no keys are changed

**Comment by avih** [comment] 2015-10-06 22:36
Note that I also just pushed a change to LilyPad where some options which PCSX2 doesn't need are disabled (including the "safe exit on esc" hack) , so if you want to test new PCSX2 builds with this hack enabled, use an older LilyPad dll.

**Comment by hellbringer616** [comment] 2015-10-07 02:22
Your latest updates fixed the issue for me, So maybe this is a different issue than i had originally, this is with the latest GIT builds, curious enough the issue may be driver related, my workstation (nvidia GPU) is running driver 355.82 and i cannot get the issue to replicate even on builds i have had issues with in the past

**Comment by avih** [comment] 2015-10-07 02:30
Thanks for testing, and glad to hear it's fixed. And yes, as I noted earlier and at the comment at the code, this is highly likely to be driver related or possibly driver bug[s].

**Closed by avih** 2015-10-07 02:30 UTC
Labels: Bug, GUI/WX, OS: Windows

**Comment by mirh** [comment] 2017-11-13 16:35
Fixed in 9c1688a39a3523418d7780be0452557a0170eedb and fa04f0970e2435f0bf4077a696b795729f1da07b ftr
