### ISSUE TITLE
The Legend of Spyro Graphical Glitch (SW/HW/ALL)

### ISSUE THREAD

**Issue by LorenzoConte97** [PCSX2/pcsx2#1781] opened 2017-01-17 17:04 UTC
***PCSX2 version:***
v1.5.0-dev-1801-g8fe94ec

***PCSX2 options:***
Emulator Settings: 1 (Safe+)
GSdx Settings:
Adapter: Nvidia GTX 970
Render: OpenGL (Hardware)
Interlacing: Auto
Resolution: Native
Texture Filtering: Bilinear (PS2)
Anisotropic Filtering: off
Mipmapping: off
CRC level: Partial
Blending Unit: Basic

***Plugins used:***
GS: GSdx 1.1.0 AVX2
PAD: LilyPad 0.12.0
SPU2: SPU2-X 2.0.0
CDVD: cdvdGigaherz 0.11.0

***Description of the issue:***
Start the game and when you must click "start" the Spyro logo is missing.

screen: http://oi68.tinypic.com/20iu9zc.jpg

***How to reproduce the issue:***
Start the game

***PC specifications:***
CPU: Intel Core i5 4690k @ 3.5GHz
GPU: Nvidia GTX 970 G1 GAMING (last driver)
OS: Windows 7 Professional 64bit (last update)

**Comment by FlatOutPS2** [comment] 2017-01-17 18:26
Duplicate of https://github.com/PCSX2/pcsx2/issues/1490

**Closed by FlatOutPS2** 2017-01-17 18:26 UTC
Labels: Duplicate
