### ISSUE TITLE
[BUG]: PCSX2 will crash if ROMs filename was including "%" in the name when make gamelist.

### ISSUE THREAD

**Issue by nassau-tk** [PCSX2/pcsx2#12011] opened 2024-11-16 02:32 UTC
### Describe the Bug

PCSX2 will crash if ROMs filename was including "%" in the name when make gamelist.

If not refresh the romlist then it will not happen crash.
So, Maybe, The issue will not happen older ver.

It may occur with other symbols, but % definitely occurs.

This seems to be the cause of some of the crashing issues seen here and there on the forums.

### Reproduction Steps

The error condition is that there is a % immediately after the number in the rom name.

Like below...

abcd 100% xyz .chd  <== Crash
abcd 1%00 xyz .chd  <== Crash
abcd 100 % xyz .chd <== Crash (include a space)

abc %100 xyz .chd    <== Not Crash

### Expected Behavior

Correct the file name rules to avoid errors.

At the same time, if possible, I would be happy if the file format of gamelist.cache became UTF-8.
Because 2-byte characters become garbled.

### PCSX2 Revision

v2.3.17

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 7 5800X

### GPU

RTX3060

**Comment by nassau-tk** [comment] 2024-11-16 02:37
And, This crash will logged below.

ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFF6FA06F80)
00007FFF6FA06F80 (ucrtbase): (filename not available): wcsnlen
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFF6F9F245A)
00007FFF6F9F245A (ucrtbase): (filename not available): strtol
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFF6F9F114A)
00007FFF6F9F114A (ucrtbase): (filename not available): wcstol
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFF6F9F0D9E)
00007FFF6F9F0D9E (ucrtbase): (filename not available): wcstol
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFF6F9F0BFB)
00007FFF6F9F0BFB (ucrtbase): (filename not available): wcstol
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF633F9FCD5)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF633F9FCD5)
00007FF633F9FCD5 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF633F8B382)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF633F8B382)
00007FF633F8B382 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6336B7706)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6336B7706)
00007FF6336B7706 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6336B579F)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6336B579F)
00007FF6336B579F (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF633CC266A)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF633CC266A)
00007FF633CC266A (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFED2FFF8B0)
00007FFED2FFF8B0 (Qt6Core): (filename not available): QThread::start
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFF70307374)
00007FFF70307374 (KERNEL32): (filename not available): BaseThreadInitThunk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFF7217CC91)
00007FFF7217CC91 (ntdll): (filename not available): RtlUserThreadStart

**Comment by F0bes** [comment] 2024-11-16 18:18
I'm unable to reproduce this.
Can you provide me the .dmp file generated either with the pcsx2 executable or in the data directory? The data directory is usually in `C:\Users\%USERPROFILE%\Documents\PCSX2`.

**Comment by nassau-tk** [comment] 2024-11-20 00:39
> I'm unable to reproduce this. Can you provide me the .dmp file generated either with the pcsx2 executable or in the data directory? The data directory is usually in `C:\Users\%USERPROFILE%\Documents\PCSX2`.

@F0bes Sorry, My PC has not the Folder.
How can I get the .dmp file?
If PCSX2 crash then crash report dmp file will make on same directory with exe.
Is it not?

[crash-2024-11-20-09-33-03-066.zip](https://github.com/user-attachments/files/17823007/crash-2024-11-20-09-33-03-066.zip)

And, I tested same problem on other PC.
And, It happend on it.

https://github.com/user-attachments/assets/bd904aaf-4807-4d9a-94b4-fbb28bb13cbf

**Comment by F0bes** [comment] 2024-11-20 01:04
> > I'm unable to reproduce this. Can you provide me the .dmp file generated either with the pcsx2 executable or in the data directory? The data directory is usually in `C:\Users\%USERPROFILE%\Documents\PCSX2`.
> 
> @F0bes Sorry, My PC has not the Folder.
> How can I get the .dmp file?
> If PCSX2 crash then crash report dmp file will make on same directory with exe.
> Is it not?
> 
> [crash-2024-11-20-09-33-03-066.zip](https://github.com/user-attachments/files/17823007/crash-2024-11-20-09-33-03-066.zip)
> 
> And, I tested same problem on other PC.
> And, It happend on it.
> 
> https://github.com/user-attachments/assets/bd904aaf-4807-4d9a-94b4-fbb28bb13cbf
> 
> 

Is the .dmp file in the same directory as the exe? It can be in either place.

**Comment by nassau-tk** [comment] 2024-11-20 04:56
I attached it the above. (Zip)
Please, Check it.
Thank you.

**Comment by F0bes** [comment] 2024-11-20 18:14
I have PR #12023 that should fix this. If it's not merged by the time you see this, feel free to test it report back.

**Closed** 2024-11-23 00:28 UTC
Labels: Bug
