### ISSUE TITLE
GSdx compile segfaults

### ISSUE THREAD

**Issue by jefferyrlc** [PCSX2/pcsx2#3043] opened 2019-07-27 20:03 UTC
***PCSX2 version:***
``(For example, stable build v1.4.0 (or) development builds v1.5.xxx)``
1.5.0.r3214.ddb6aac82-1 (I got it via git clone)
- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

- **Note**: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
GSdx segfaults when it tries to compile on GCC/G++ 9.1.0

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
clone git
run build.sh

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
Intel Core i7 860; MSI Nvidia GTX 960 Manjaro Linux 18

[terminal output.txt](https://github.com/PCSX2/pcsx2/files/3438546/terminal.output.txt)

**Comment by arcum42** [comment] 2019-07-27 20:11
From the attached output:
`CMake Warning at cmake/SearchForStuff.cmake:218 (message):
  

      It looks like you are compiling with 9.0.x or 9.1.x. Using these versions is not recommended,
      as there is a bug known to cause the compiler to segfault while compiling. See patch
      https://gitweb.gentoo.org/proj/gcc-patches.git/commit/?id=275ab714637a64672c6630cfd744af2c70957d5a
      Even with that patch, compiling with LTO may still segfault. Use at your own risk!
      This text being in a compile log in an open issue may cause it to be closed.
Call Stack (most recent call first):
  CMakeLists.txt:27 (include)`

Duplicate of #2948.

**Closed by arcum42** 2019-07-27 20:11 UTC
