### ISSUE TITLE
[BUG]: Clock Tower 3 [SLUS-20633] Horizontal lines in FMVs

### ISSUE THREAD

**Issue by wesker265** [PCSX2/pcsx2#9924] opened 2023-09-08 06:39 UTC
### Describe the Bug

When starting Clock Tower 3, most FMVs are glitched, with horizontal lines appearing throughout the video. The video will also glitch out and have ghost images retain from before. This does not happen in Software mode. Toggling between the different renderers and software mode will intermittently fix this issue, but is inconsistent. Software mode is the only mode where this does not occur. I tried starting the game from the beginning with Vulkan, OpenGL, D11 and D12, and all cause this issue.

Sometimes, the Capcom logo FMV will be fine, while the next FMV will be glitched out, and other times the Capcom logo FMV will be glitched out, while the following FMV will be fine.

This happens with and without widescreen patches, and at all resolutions (including native resolution in hardware mode). The resolution seems to affect how thick the horizontal lines are.

All gameplay and engine-rendered cutscenes seem unaffected. This issue did not occur approximately two years ago when I last played this game. MTVU enable/disable does not affect the issue.

### Reproduction Steps

Begin game. Watch all FMVs without skipping them.

### Expected Behavior

Begin Game. FMVs will not display horizontal lines throughout video and no image retention will occur.

### PCSX2 Revision

1.7.4988

### Operating System

Windows 11

### CPU

i7-7700k

### GPU

RTX 3080Ti

### GS Settings

GS Display settings - All default

Rendering - All default except: Internal Resolution 6x (Also present in Native and 4x)
                                                  Anistropic Filtering: 16x (Off-8x also causes issue)
                                                  Blending Accuracy: High (Basic also causes issue)

All other settings default

### Emulation Settings

All Default. MTVU on or off has no change. VU1 on or off has no change either.

### GS Window Screenshots

![Clock Tower 3_SLUS-20633_20230907231447](https://github.com/PCSX2/pcsx2/assets/45540160/5c2250e1-b9f6-4676-bba0-6a99bda1c017)

![Clock Tower 3_SLUS-20633_20230907230927](https://github.com/PCSX2/pcsx2/assets/45540160/66654129-37b5-4856-9568-701da1ee24a5)

![Clock Tower 3_SLUS-20633_20230907230130](https://github.com/PCSX2/pcsx2/assets/45540160/94328e7d-a5cc-48d6-8689-5b918969c05a)

### Logs & Dumps

[Clock Tower 3_SLUS-20633_20230907233816.gs.zip](https://github.com/PCSX2/pcsx2/files/12556310/Clock.Tower.3_SLUS-20633_20230907233816.gs.zip)

**Comment by refractionpcsx2** [comment] 2023-09-08 07:29
Oh god sake, I fixed this once ages ago :(

**Comment by Buzzardsoul** [comment] 2023-10-30 22:13
Seems to be fixed on latest.

**Comment by refractionpcsx2** [comment] 2023-10-30 22:17
Nah it's still broken.

**Comment by Buzzardsoul** [comment] 2023-10-30 22:20
This is a picture from my latest. Not sure why it's working fine with my version.

![untitled](https://github.com/PCSX2/pcsx2/assets/126727903/725e2889-f3af-44cd-ab46-32916b708582)

**Comment by refractionpcsx2** [comment] 2023-10-30 22:23
I don't think the GS dump shows it, running the game manually shows the problem. I expect even running the game, switching renderers will fix it temporarily

**Comment by treacherousfiend** [comment] 2023-10-31 02:20
I'm not particularly familiar with using PCSX2 or debugging it, but I decided i'd play this game today (fun coincidence how recently active this thread is!), and noticed a few things.

Running the game with interlacing completely disabled seems to show that the FMV is skipping frames? every other frame is completely black.
It seems like a lot of settings, from what I can tell basically anything that causes the renderer to reset, seems to also fix the issue temporarily (i.e. mipmapping, trilinear filtering).
Blend de-interlacing doesn't have this issue, but causes the FMV to be darker? I don't really understand how the different de-interlacing modes work, it could be darker because its blending with pure black frames maybe?

**Comment by refractionpcsx2** [comment] 2023-10-31 02:22
Yes, every other frame is black which causes the deinterlacer to freak out, the problem is old targets in the hardware texture cache confusing it on video replay.i had fixed it ages ago but it broke again.

The is some stuff myself and sten are working on which may fix it, but it might be a little while

**Comment by treacherousfiend** [comment] 2023-10-31 02:24
Wow, thanks for the quick response! Glad to hear it'll be fixed soon, but I suppose i'll have to deal with slightly darker cutscenes until then

**Comment by refractionpcsx2** [comment] 2023-10-31 02:25
If you want a temporary solution, you could enable the software fmv switch in the per game - > game fixes

**Comment by treacherousfiend** [comment] 2023-10-31 02:30
Yep, that works, thanks!

**Closed** 2023-11-24 10:34 UTC
Labels: Bug, GS: Hardware

**Comment by Oberworld** [comment] 2024-03-21 06:43
I have this problem. I use v1.7.5624, all settings by default.
I can't find the software fmv switch in the per game - > game fixes.

Is there any option to fix it? 
Thank you.
