### ISSUE TITLE
[BUG]: Opening Properties Menu (from right clicking on a game) Frequently Closes PCSX2

### ISSUE THREAD

**Issue by Virjoinga** [PCSX2/pcsx2#11846] opened 2024-09-26 02:28 UTC
### Describe the Bug

PCSX2 closes (doesn't crash) frequently when opening the properties window (from right clicking on a game).

### Reproduction Steps

Right click on a game and open the properties window. Close out of that menu and repeat the process.

### Expected Behavior

PCSX2 shouldn't close from opening the properties menu (from right clicking on a game).

### PCSX2 Revision

v2.1.170

### Operating System

Windows 11

**Comment by Jakey757** [comment] 2024-09-26 02:35
Can't reproduce, Windows 10. Rapidly opened and closed properties window on multiple games.

**Comment by Mrlinkwii** [comment] 2024-09-26 09:56
@Virjoinga you need to update your gpu drivers

**Comment by F0bes** [comment] 2024-09-26 21:07
We load the GPU driver stuff when you open the settings. Does the crash also happen when you open the global settings window?

If updating your GPU drivers doesn't fix it, please upload an emulog of when it happens.

I'll close this for now.

**Comment by HayateLaTech** [comment] 2024-09-28 00:58
I have the same Problem here. Sometimes opening Properties work, but more often than not it leads to a Crash.
All Drivers are updated on my end.

I tried leaving the Log-Window open, but it simply closes whenever pcsx2 crashed.
The emuLog.txt contains the following:

> [    7.2831] Applying settings...
[   12.2230] Applying settings...
[   17.8502] isoFile open ok: A:\Roms\Sony PlayStation 2\ROMs\Cel Damage Overdrive\Cel Damage Overdrive.bin
[   17.8512]   Image type  = CD
[   17.8514]  * CDVD Disk Open: CD, 1 tracks (1 to 1):
[   17.8515]  * * Track 1: Data (Mode 1) (166419 sectors)
[   17.9529] D3D11 feature level for autodetection: c000
[   22.1700] isoFile open ok: A:\Roms\Sony PlayStation 2\ROMs\Burnout Revenge.iso
[   22.1703]   Image type  = DVD
[   22.1704]  * CDVD Disk Open: DVD, Single layer or unknown:
[   22.1705]  * * Track 1: Data (Mode 1) (1943328 sectors)
[   25.1128] isoFile open ok: A:\Roms\Sony PlayStation 2\ROMs\DTM Race Driver.iso
[   25.1131]   Image type  = DVD
[   25.1132]  * CDVD Disk Open: DVD, Single layer or unknown:
[   25.1132]  * * Track 1: Data (Mode 1) (1888816 sectors)
[   27.7542] isoFile open ok: A:\Roms\Sony PlayStation 2\ROMs\FINAL_FANTASY_X_2.ISO
[   27.7546]   Image type  = DVD
[   27.7547]  * CDVD Disk Open: DVD, Single layer or unknown:
[   27.7549]  * * Track 1: Data (Mode 1) (1990352 sectors)
[   31.0802] isoFile open ok: A:\Roms\Sony PlayStation 2\ROMs\Shadow of the Colossus.ISO
[   31.0805]   Image type  = DVD
[   31.0806]  * CDVD Disk Open: DVD, Single layer or unknown:
[   31.0806]  * * Track 1: Data (Mode 1) (1315408 sectors)
[   33.9121] isoFile open ok: A:\Roms\Sony PlayStation 2\ROMs\Tony Hawk's American Wasteland.iso
[   33.9126]   Image type  = DVD
[   33.9128]  * CDVD Disk Open: DVD, Single layer or unknown:
[   33.9130]  * * Track 1: Data (Mode 1) (1701568 sectors)
[   37.2089] isoFile open ok: A:\Roms\Sony PlayStation 2\ROMs\DTM Race Driver.iso
[   37.2092]   Image type  = DVD
[   37.2094]  * CDVD Disk Open: DVD, Single layer or unknown:
[   37.2095]  * * Track 1: Data (Mode 1) (1888816 sectors)

Windows 11
RTX4090
i9 13900k

happens on nightly as well as stable

**Comment by HayateLaTech** [comment] 2024-09-28 10:16
After testing it out a bit more, the Main Setting window doesn't seem to trigger the Crashes, it only happens when trying to open Game Properties.

And I got this in the Log Window on a startup after a Crash:

> [    0.4468] isoFile open ok: A:\Roms\Sony PlayStation 2\ROMs\TOMB_RAIDER.ISO
[    0.4472]   Image type  = CD
[    0.4483] isoFile: Invalid layer1 Primary Volume Descriptor
[    0.4492]  * CDVD Disk Open: DVD, Single layer or unknown:
[    0.4503]  * * Track 1: Data (Mode 1) (1980080 sectors)
[    0.4513] Failed to get ELF name: Path component 'SYSTEM.CNF' not found

**Comment by Virjoinga** [comment] 2024-09-28 20:21
> @Virjoinga you need to update your gpu drivers

Mine are already up-to-date (sorry for late reply)

**Comment by Virjoinga** [comment] 2024-09-28 20:25
> We load the GPU driver stuff when you open the settings. Does the crash also happen when you open the global settings window?
> 
> If updating your GPU drivers doesn't fix it, please upload an emulog of when it happens.
> 
> I'll close this for now.

1. No it does not crash when opening the global settings.
2. My GPU drivers are already up-to-date.

[emulog.txt](https://github.com/user-attachments/files/17176196/emulog.txt)

**Comment by F0bes** [comment] 2024-09-28 20:52
> Failed to get ELF name: Path component 'SYSTEM.CNF' not found

This makes me believe that it is a bad game ISO.

**Comment by F0bes** [comment] 2024-09-28 20:53
> > We load the GPU driver stuff when you open the settings. Does the crash also happen when you open the global settings window?
> > If updating your GPU drivers doesn't fix it, please upload an emulog of when it happens.
> > I'll close this for now.
> 
>     1. No it does not crash when opening the global settings.
> 
>     2. My GPU drivers are already up-to-date.
> 
> 
> [emulog.txt](https://github.com/user-attachments/files/17176196/emulog.txt)

> isoFile: Invalid layer1 Primary Volume Descriptor

Same for you. Can you verify that the game checksum matches redump?

**Comment by HayateLaTech** [comment] 2024-09-28 21:08
> Same for you. Can you verify that the game checksum matches redump?

Where do I get the checksum of redump to check against? o:

I remember dumping those games straight from the German Discs that I had. What confuses me is that sometimes the Properties load up correctly and sometimes it just crashes.

If the ISO would be faulty, wouldn't that also mean it cannot be run or opened in the Properties at all?

(All Games run flawlessly)

**Comment by HayateLaTech** [comment] 2024-09-28 21:25
I checked the CRC with this website here:

https://wiki.pcsx2.net/Lara_Croft_Tomb_Raider:_Anniversary

and it's the exact same.

**Comment by F0bes** [comment] 2024-09-28 21:29
Okay, I'll try and replicate the issue sometime. Thanks for reporting you guys!

**Comment by HayateLaTech** [comment] 2024-09-28 21:43
There is a Crash Report that sometimes generates in form of a txt in the root directory of the pcsx2 exe.

I'll strip away all private parts and post the content, maybe it'll help:

> Exception 0xC0000005 at 0x00007FFA304173E4
SymInit: Symbol-SearchPath: '.', symOptions: 530, UserName: 'Noeru'
OS-Version: 10.0.22631 () 0x100-0x1
A:\Roms\Sony PlayStation 2\pcsx2-qt.exe:pcsx2-qt.exe (00007FF6A3BE0000), size: 228786176 (result: 0), SymType: '-exported-', PDB: 'A:\Roms\Sony PlayStation 2\pcsx2-qt.exe', fileVersion: 2.1.174.0
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA304173E4)
00007FFA304173E4 (owclient): (filename not available): base::SRWLock::TryLock
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA30350AB9)
00007FFA30350AB9 (owclient): (filename not available): OW_DestroyInstance
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA72DB4D97)
00007FFA72DB4D97 (nvoglv64): (filename not available): DrvPresentBuffers
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA62A7B0DE)
00007FFA62A7B0DE (vulkan-1): (filename not available): vkResetEvent
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A3F2C096)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A3F2C096)
00007FF6A3F2C096 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A3F5EDC2)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A3F5EDC2)
00007FF6A3F5EDC2 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A3F5EBC6)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A3F5EBC6)
00007FF6A3F5EBC6 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A42CAF85)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A42CAF85)
00007FF6A42CAF85 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A42BA31C)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A42BA31C)
00007FF6A42BA31C (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A42FBDFE)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A42FBDFE)
00007FF6A42FBDFE (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A42FCCC8)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A42FCCC8)
00007FF6A42FCCC8 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A42FFE46)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A42FFE46)
00007FF6A42FFE46 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A41F27B2)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A41F27B2)
00007FF6A41F27B2 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E279531)
00007FFA2E279531 (Qt6Core): (filename not available): QObject::qt_static_metacall
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E27C384)
00007FFA2E27C384 (Qt6Core): (filename not available): QMetaObject::activate
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA300524C1)
00007FFA300524C1 (Qt6Gui): (filename not available): QAction::activate
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E33FF13)
00007FFA3E33FF13 (Qt6Widgets): (filename not available): QMenu::actionGeometry
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E33FCF5)
00007FFA3E33FCF5 (Qt6Widgets): (filename not available): QMenu::actionGeometry
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E3460DA)
00007FFA3E3460DA (Qt6Widgets): (filename not available): QMenu::mouseReleaseEvent
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E1D67B5)
00007FFA3E1D67B5 (Qt6Widgets): (filename not available): QWidget::event
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E1927FE)
00007FFA3E1927FE (Qt6Widgets): (filename not available): QApplicationPrivate::notify_helper
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E190A00)
00007FFA3E190A00 (Qt6Widgets): (filename not available): QApplication::notify
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E23936C)
00007FFA2E23936C (Qt6Core): (filename not available): QCoreApplication::notifyInternal2
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E19682E)
00007FFA3E19682E (Qt6Widgets): (filename not available): QApplicationPrivate::sendMouseEvent
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E1FA129)
00007FFA3E1FA129 (Qt6Widgets): (filename not available): QWidgetRepaintManager::updateStaticContentsSize
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E1F815C)
00007FFA3E1F815C (Qt6Widgets): (filename not available): QWidgetRepaintManager::updateStaticContentsSize
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E1927FE)
00007FFA3E1927FE (Qt6Widgets): (filename not available): QApplicationPrivate::notify_helper
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E19198D)
00007FFA3E19198D (Qt6Widgets): (filename not available): QApplication::notify
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E23936C)
00007FFA2E23936C (Qt6Core): (filename not available): QCoreApplication::notifyInternal2
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2FCF45A5)
00007FFA2FCF45A5 (Qt6Gui): (filename not available): QGuiApplicationPrivate::processMouseEvent
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2FD4FD4C)
00007FFA2FD4FD4C (Qt6Gui): (filename not available): QWindowSystemInterface::sendWindowSystemEvents
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E3C2729)
00007FFA2E3C2729 (Qt6Core): (filename not available): QEventDispatcherWin32::processEvents
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2FFE7D39)
00007FFA2FFE7D39 (Qt6Gui): (filename not available): QWindowsGuiEventDispatcher::processEvents
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E240A64)
00007FFA2E240A64 (Qt6Core): (filename not available): QEventLoop::exec
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E341A9F)
00007FFA3E341A9F (Qt6Widgets): (filename not available): QMenu::exec
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E3418DB)
00007FFA3E3418DB (Qt6Widgets): (filename not available): QMenu::exec
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A41E8ECC)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A41E8ECC)
00007FF6A41E8ECC (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E28562B)
00007FFA2E28562B (Qt6Core): (filename not available): QMetaCallEvent::placeMetaCall
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E283573)
00007FFA2E283573 (Qt6Core): (filename not available): QObject::event
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E1D74A9)
00007FFA3E1D74A9 (Qt6Widgets): (filename not available): QWidget::event
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E1927FE)
00007FFA3E1927FE (Qt6Widgets): (filename not available): QApplicationPrivate::notify_helper
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA3E19198D)
00007FFA3E19198D (Qt6Widgets): (filename not available): QApplication::notify
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E23936C)
00007FFA2E23936C (Qt6Core): (filename not available): QCoreApplication::notifyInternal2
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E23C12E)
00007FFA2E23C12E (Qt6Core): (filename not available): QCoreApplicationPrivate::sendPostedEvents
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2FFE7DBF)
00007FFA2FFE7DBF (Qt6Gui): (filename not available): QWindowsGuiEventDispatcher::sendPostedEvents
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E3C2729)
00007FFA2E3C2729 (Qt6Core): (filename not available): QEventDispatcherWin32::processEvents
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2FFE7D39)
00007FFA2FFE7D39 (Qt6Gui): (filename not available): QWindowsGuiEventDispatcher::processEvents
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E240A64)
00007FFA2E240A64 (Qt6Core): (filename not available): QEventLoop::exec
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFA2E236CBD)
00007FFA2E236CBD (Qt6Core): (filename not available): QCoreApplication::exec
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A420F8E0)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A420F8E0)
00007FF6A420F8E0 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A463C300)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A463C300)
00007FF6A463C300 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6A463C186)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6A463C186)
00007FF6A463C186 (pcsx2-qt): (filename not available): (function-name not available)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFB068E257D)
00007FFB068E257D (KERNEL32): (filename not available): BaseThreadInitThunk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFB07CEAF28)
00007FFB07CEAF28 (ntdll): (filename not available): RtlUserThreadStart

**Comment by F0bes** [comment] 2024-09-28 21:46
Can you upload the corresponding .dmp file? Just the txt doesn't tell us much. Ensure that the crash dump is actually from this even though 😅

**Comment by HayateLaTech** [comment] 2024-09-28 21:48
[crash-2024-09-28-22-55-12-917.dmp](https://github.com/user-attachments/files/17176686/crash-2024-09-28-22-55-12-917.dmp)

The only crashes came from opening the Properties, so I am very certain this contains it.

**Comment by F0bes** [comment] 2024-09-28 22:07
That crash actually happens in `OWClient.dll`
Can you try uninstalling OverWolf, restarting your computer, and see if that stops the crashing?
I don't know if things have changed in the last 6 months but it appears like you **need** to uninstall OverWolf for it to stop injecting its (broken) modules into software. [According to this reddit thread anyways.](https://www.reddit.com/r/Overwolf/comments/1b7yrah/dont_inject_dll_into_every_process/)

This is actually the second crash we've had with OverWolf. The first time they were actually using the OBS graphics hook when they weren't permitted too...

**Comment by HayateLaTech** [comment] 2024-09-28 22:13
This kinda freaks me out because uninstalling Overwolf really fixed the Problem..

The thing is that I deactivated autostart for Overwolf and it wasn't started when those crashes happened.. (no symbol in the taskbar or that arrow menu on the right side)

So.. is this already considered malware? XD

Thanks a lot for helping fix this issue! :D I'll never install Overwolf ever again, wth XD

**Comment by F0bes** [comment] 2024-09-28 22:18
I'm glad that fixed the issue for you.

Unfortunately, there's no reliable way for us to stop Overwolf (and similar software) from injecting into PCSX2. This ends up wasting the time of both our developers and helpers, as well as our users, when the issue isn't even on our end.

@Virjoinga Do you by chance have Overwolf installed? If not, do you see a .dmp file in your PCSX2 directory that you can upload?

**Comment by Virjoinga** [comment] 2024-09-28 22:34
> I'm glad that fixed the issue for you.
> 
> Unfortunately, there's no reliable way for us to stop Overwolf (and similar software) from injecting into PCSX2. This ends up wasting the time of both our developers and helpers, as well as our users, when the issue isn't even on our end.
> 
> @Virjoinga Do you by chance have Overwolf installed? If not, do you see a .dmp file in your PCSX2 directory that you can upload?
It did not fix the issue, never said it did? I do have Overwolf installed yeah, it was for modding Lethal Company a while ago. There is no .dmp created as PCSX2 just closes, not crashes (as stated in the initial post).

**Comment by F0bes** [comment] 2024-09-28 22:36
I'm aware you never said it did. I was wondering if HayateLaTech's issue is the same as yours. Are you able to try and uninstall Overwolf to double check that it is not the cause of the issue?

**Comment by HayateLaTech** [comment] 2024-09-28 22:36
> It did not fix the issue, never said it did? I do have Overwolf installed yeah, it was for modding Lethal Company a while ago. There is no .dmp created as PCSX2 just closes, not crashes (as stated in the initial post).

PCSX2 closing means it's crashing. And try uninstalling Overwolf, that will probably fix the issue for you too.

(F0bes was referring to me fixing the issue on my end)

**Comment by Virjoinga** [comment] 2024-09-28 22:41
> I'm aware you never said it did. I was wondering if HayateLaTech's issue is the same as yours. Are you able to try and uninstall Overwolf to double check that it is not the cause of the issue?

Oh sorry, my mistake. I uninstalled it and Thunderstore and the issue seems to be resolved. I wonder why Overwolf caused an issue with PCSX2?

**Comment by F0bes** [comment] 2024-09-28 22:54
> I wonder why Overwolf caused an issue with PCSX2?

Couldn't tell you. If you want, you can open a support ticket with them.

**Closed by F0bes** 2024-09-28 22:54 UTC
Labels: Bug
