### ISSUE TITLE
[BUG]: Shadow Hearts Covenant - Freezes randomly during screen transitions

### ISSUE THREAD

**Issue by edubenavente** [PCSX2/pcsx2#7823] opened 2023-01-08 14:55 UTC
### Describe the Bug

The game will freeze randomly after fading to black while it's loading a transition, either from a zone change or in-between cutscenes. The music will keep playing, but the screens remains black. It doesn't happen always at a specific transition, it's completely random.
It appears to only happen after having used ~~speedhacks~~ **edit:** fast forward. If loading again from the memory card, the freezing won't occur as long as the ~~speedhacking~~ **edit:** fast forward hasn't been used.

### Reproduction Steps

Its occurrence is completely random, there's no way to trigger it other than to keep playing while using ~~speedhacks~~ **edit:** fast forward. In my case, the game was perfectly fine for a few hours and it didn't start happening until the second dungeon (Paris Subway Tunnels). From that point on, it keeps repeating far more frequently.

### Expected Behavior

The next scene loading normally.

### PCSX2 Revision

Nightly v1.7.3875

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 3800X

### GPU

RTX 3070

**Comment by refractionpcsx2** [comment] 2023-01-08 15:12
yeah we're aware of this one, it's just a pain to reproduce.

**Comment by edubenavente** [comment] 2023-01-08 15:33
Thanks for the fast reply! It's the very first time I've had any issues using the Fast Forward speed, I didn't know it caused issues. I'll stop using it then.
I use it a lot for old RPGs to speed up some animations and I hoped there was some workaround :_)

**Comment by refractionpcsx2** [comment] 2023-01-08 15:42
Fast forward (tab or F4) should be fine, providing you're not using ASync synchronisation for the sound.

**Comment by edubenavente** [comment] 2023-01-08 15:51
Oh, I must have misunderstood what speedhack means, I was referring to fast forward (specifically the Turbo / Fast Forward (Hold) hotkey), I'm very sorry, I'll edit the bug report.
I'm not using ASync, just the recommended TimeStretched. I left all my options as default or recommended, except for the renderer (Vulkan) and cranking up the internal resolution.
As far as I can tell, the game worked fine as long as I didn't use fast forward, but it would freeze randomly if I'd used FF at some point since loading the memcard.

**Comment by refractionpcsx2** [comment] 2023-01-08 15:53
yeah that's strange, not sure that's entirely true, I suspect it will freeze regardless

**Comment by edubenavente** [comment] 2023-01-08 15:59
What made me assume so was that I loaded the save game in the dungeon where the issue happened the first time, and I tried to complete it up to 4 times still using fast forward, and I was never able to finish it because it would freeze at random transitions (every time resetting the game and loading from the memory card, because once the freeze happens, if I reload a save state right before the freeze, it will always keep happening at the same exact spot). Maybe I was just very lucky, but the fourth time when I stopped using fast forward, I could finally finish it with no issues.
I guess I'll try to keep playing without using it to see if it happens regardless.

**Comment by refractionpcsx2** [comment] 2023-01-08 16:00
if you could, please, I do find it very strange though, the emulation shouldn't be any different with or without fast forward.

**Comment by edubenavente** [comment] 2023-01-08 16:02
I'll test it as soon as I can in a few hours and I'll post an update. Thanks for the assistance!

**Comment by edubenavente** [comment] 2023-01-09 16:53
Update: I played for 2.5 hours without fast forward and never encountered any issue, so I tried to force the bug to happen. I tested it in the first map the freezes happened, first using fast forward, and the bug triggered in less than 5 minutes. I did the same thing but with no fast forward, I wandered over and over through the many transitions for 30 minutes, and it never happened.
I'm led to believe the FF is causing it _somehow_ but maybe it's just a case of devilish coincidence. Tbf, I tried the same experiment a second time in another location where the bug happened, and this time it never triggered, both with or without fast forward, but it's weird that it hasn't happened ever once while I refrained from using fast forward.

In any case, since it's a known bug I'm guessing the answer is no, but is there any known workaround to prevent it? Or maybe it doesn't happen in some other versions, or older ones? Thanks!

**Comment by refractionpcsx2** [comment] 2023-01-09 16:56
That's really strange, I wonder why that is....

I mean the hangs were a known bug but I thought maybe it was no longer happening, but all the timing involved there is done in emulation space, so it's transparent to if you're fast forwarding or not, so I don't get it :/

**Comment by refractionpcsx2** [comment] 2023-02-28 20:29
Just noticed this is a duplicate of #7139
Closing in favour of that one (since it was first)

**Closed by refractionpcsx2** 2023-02-28 20:29 UTC
Labels: Bug, CDVD
