### ISSUE TITLE
[BUG]: Castlevania - Curse of Darkness map screen glitched out

### ISSUE THREAD

**Issue by rhobiusvoid** [PCSX2/pcsx2#6156] opened 2022-05-23 19:19 UTC
### Describe the Bug

![image](https://user-images.githubusercontent.com/22803374/169890469-5e946059-3e0f-403c-aed6-efedcd9e3284.png)
Exactly what it says on the tin. Above this line is a picture of the map screen in Software Mode.
![image](https://user-images.githubusercontent.com/22803374/169890525-49bfa020-9837-426e-9380-2e96180fd4dc.png)
And this is what it looks like in Hardware Mode.

Seems to be a regression, considering the fact this wasn't a problem until now.

### Reproduction Steps

Get into the game and just open the map by pressing Select.

### Expected Behavior

The map is to be sharp and readable, considering doors are just simple holes in the white outline surrounding the blue interiors.
![image](https://user-images.githubusercontent.com/22803374/169890735-f17cffc2-7377-4762-8d33-e3be0ee1d74a.png)
Here is what it normally looks like.

### PCSX2 Revision

1.7.2775

### Operating System

Windows 10 (64bit)

### CPU

i5-9400F

### GPU

GTX 1050ti

### GS Settings

![image](https://user-images.githubusercontent.com/22803374/169890865-f378f9dc-c938-4144-898e-2334195430be.png)
![image](https://user-images.githubusercontent.com/22803374/169890878-fd5addcd-8e52-4fc3-b9c7-faed581ad980.png)

### Emulation Settings

Tested on all presets, doesn't seem to change anything.

**Comment by Mrlinkwii** [comment] 2022-05-23 19:20
Can you post a gs dump? :)

**Comment by rhobiusvoid** [comment] 2022-05-23 19:21
How do I go about doing that?

**Comment by MuPendulum** [comment] 2022-06-07 19:11
Regressed with #3940
@tellowkrinkle

**Comment by ichee** [comment] 2022-06-11 19:29
Issue seems to be caused by the texture filter `Bilinear PS2`. Setting any other value, excluding the trilinear option which is worse for this issue, seems to resolve it.

If using the software renderer with QT builds, changing to one of the hardware renderers and setting the filter option to anything other than `Bilinear PS2` then switching back will work around the issue with software as well.

**Comment by coornio** [comment] 2022-06-11 22:49
So it's fixed both by changing the default Texture Filtering and also by having any form of Texture Preloading. I wonder what these two have in common that rectify this.

**Comment by ichee** [comment] 2022-07-17 01:18
This same issue (or at least similar) was also reported in the forums years ago, and subsequently resolved.

Forum link at https://forums.pcsx2.net/Thread-Horizontal-Lines-in-Castlevania-Curse-of-Darkness.

**Comment by ichee** [comment] 2022-07-17 07:05
Latest build looks significantly better on all hardware renderers than they did previously, though edges of map are a bit jagged.
Also, the displayed 'S' on some area maps gets cut off when moving the map vertically.

Software renderer is still broken without using the above workaround.

**Comment by MuPendulum** [comment] 2022-11-14 19:13
Regression is still present in latest master (aa4a9cda) so this was not one of the games fixed by #6757.

Software: Broken
Hardware w/ Texture Preloading set to None: Broken
Hardware w/ Texture Preloading set to Partial: Improved but may still be partially broken according to ichee
Hardware w/ Texture Preloading set to Full (Hash Cache): Same as Partial

**Comment by refractionpcsx2** [comment] 2022-11-14 19:21
It's fixable with #6553 
![image](https://user-images.githubusercontent.com/6278726/201747205-0b54f775-ddb1-42dc-9ebf-b2606a578552.png)

**Comment by MuPendulum** [comment] 2022-11-14 22:46
bd8fcc8f is the culprit although I can confirm the pre-round sprite hack in #6553 works around it in the software renderer.

**Comment by refractionpcsx2** [comment] 2022-11-14 22:48
that's not exactly introducing a bug per-sé, we need that part to be accurate, but the PS2 is not so accurate in its start/end positions of the texture, something the preround PR works to alleviate (but it needs a whole lot more work)

**Closed** 2024-05-15 17:13 UTC
Labels: Bug, GS
