### ISSUE TITLE
[PAL - SCES_509.67]Kingdom Hearts I cutscene slowdowns.

### ISSUE THREAD

**Issue by Tyestor** [PCSX2/pcsx2#951] opened 2015-11-04 14:49 UTC
So I thought I'd play through this game again. Fun idea, right? I dunno what happened, but I'm getting slowdowns in cutscene(s) and on (some) menus. By cutscenes I mean the cutscene directly after you hand in the logs/cloth/rope etc and you tell Kairi you're done for the day. It's Kairi/Riku/Sora all sitting on/by a tree overlooking the water and talking. This never used to happen, I've played through this game before with no slowdowns at all. 

PCSX2 is using default settings pretty much. The slowdowns happen on OGL and D3D11. I was using 6x native res at the time and that was the first thing I changed down. I put it down to 3x and I still got slowdowns. Considering I can play through most games at 5x native (including KH2FM), this doesn't bode well. I increased EE Cyclerate and VU Cyclerate by 1 and no dice. Also turning MTVU on did nothing too. Oh and CRC was at partial for when I had OGL on and full for D3D11. Keep in mind that there are no gameplay slowdowns, at least from what little I have played during Destiny Islands and in the Dive to the Heart sequences.

Info

OS: Windows 10 Pro N 64-bit
PCSX2 version: PCSX2 1.3.1-20151103091731 / v1.3.1-1379-g6e7962e
CPU: Intel i5 2500k @ 3.7ghz
GPU: AMD 6950 @ 840/1325
RAM: 12GB G.Skill Ripjaws 1600mhz

**Comment by Tyestor** [comment] 2015-11-04 14:54
Okay, I did some more testing. This is still on D3D11. I worked my way up through the resolution scaling to see how high I could play it. Native, fine. 2x, fine. 3x, fine. 4x, fine. Less than 30% peak EE/GS/VU at any time, including the problem cutscene/menus on 4x. As soon as I changed it to 5x, the slowdowns happened again, but what is strange is that I'm getting the same EE/GS/VU % as the other res scales, 25%-30%. Still no gameplay slowdown, just slowdown in the menu and cutscene.

**Comment by willkuer** [comment] 2015-11-04 15:04
Sounds like simple gpu bottleneck. The forum would've been a better place to discuss this. Possibly you played with/updated drivers since your last trial.

**Comment by Tyestor** [comment] 2015-11-04 15:10
You mean updating my drivers made the performance worse?

**Comment by willkuer** [comment] 2015-11-04 15:24
Or you recently installed win10 and use default win10 gpu drivers. I dont know.

Still this is highly probably not an issue with the codebase. You can try some older versions if you like. But even if you find version that work better it might be due to the fact that pcsx2 more accurate now.

**Comment by ssakash** [comment] 2015-11-04 15:33
>> I've played through this game before with no slowdowns at all. 

While using the same version of *PCSX2* ? If yes then it's likely to be any driver (or) hardware changes parameters on your side.

else, please mention the previous version of *PCSX2* which doesn't reproduce this slow performance issue. if you could find the exact version of *PCSX2* which introduced this issue it'd make much easier for the developers to look into it if it's a potential issue on the code base.

**Comment by Tyestor** [comment] 2015-11-04 15:52
>While using the same version of PCSX2 ?

No, not this version of PCSX2. 

>else, please mention the previous version of PCSX2 which doesn't reproduce this slow performance issue

Well, that's next to impossible since I played through the game quite a while ago (2+ years ago). All I can tell you is that it wasn't a stable version so it was probably version 1.1. Absolutely no idea what revision. If what willuker said is indeed true, what most likely happened is that PCSX2 got more accurate and my piddling 2500k and 6950 can no longer play KH1 on 5x native. I have no idea what was fixed though and I can't understand why only the cutscenes are slowing down.

**Comment by willkuer** [comment] 2015-11-04 16:11
Please check version 1.0 and 1.2.1 then.

Do you have a 4K monitor? 4x native = ~2k x 2k resolution, 5x native = ~2.5k x 2.5k resolution. If you have a full hd monitor (~1k x 2k resolution) you probably won't see the difference between 4x and 5x native.

**Comment by Tyestor** [comment] 2015-11-04 16:28
I have a 1080p monitor.

You most definitely can tell the difference and I would show you screenshots, however, print screen doesn't work (black screen) and F8 gives terrible screenshots (mangled aspect ratio, low resolution). Rendering at even 4x is noticeably more blurry than 5x. Rendering above monitor resolution supersamples the image, as I'm sure you're well aware. Supersampling is quite simply the best form of AA there is. Obviously, there is rapid diminishing returns but it doesn't start at 4x. Anyway, I'll give 1.0 and 1.2.1 a go. I just tried to play some KH2FM and I can't play that on 5x either and I played through that on 5x native quite recently (I even have some videos of it on YouTube).

**Comment by willkuer** [comment] 2015-11-04 17:00
If you are aware of SSAA you often see the influence. Just because you know where to look. The difference between 2x native and 3x native and 4x native on a fullHD screen on the other side is obvious to everybody. I agree that SSAA is one of the best AA but one might want to note that pcsx2 is using full screen SSAA which is extremely demanding. Adaptive SSAA is considered by devs and if I look at gregory's productivity curve in the last month's I guess it will be implemented at some point.

If you need SSAA I have no problem with that. A different approach would be to check custom resolutions. Either they are at similar range unexpectedly faster or you can find something between 4x and 5x native (considering your 16:9 aspect ratio as well!). If I remember one thread regarding custom resolutions correctly you need to double the height dimension in custom resolution to get the correct resolution (maybe due to interlacing?) 1920x1080 -> 1920x2160 but I might be wrong here.

**Comment by refractionpcsx2** [comment] 2015-11-04 19:32
Sounds strange to get slowdowns in only the cutscenes, i wouldn't say that was a GPU slowdown.

Common reasons for this are

1. Running the game directly from the disc
2. Running the ISO from a slow external drive.

**Comment by Tyestor** [comment] 2015-11-04 20:09
I try to avoid custom resolutions where I can because I've had some bad experiences with it in the past. Plus, I heard that it's getting removed soon (or maybe that's just the UI option).

As for the ISO/HDD...It's not running off the disc, the ISO is not on an external HDD it is on one of my internal drives, specifically, a Western Digital Caviar Black (7200 RPM, IIRC). Thirdly, I just did an analysis with Defraggler and the drive is fragmented 18%. So not very much but I'll defrag it anyway. For the record, the slowdown in KH2FM happened during gameplay. Turning the res down to 4x native fixed it. I have yet to test 1.0 and 1.2.1

**Comment by Tyestor** [comment] 2015-11-04 20:26
I just downloaded PCSX2 1.2.1 (r5875) and I can play KH2FM full speed. Standing around in the Altar of Naught and in combat, no slowdowns. 6x native. INTC, MTVU, Wait Loop an mVU Flag Enabled EE Cyclerate and VU Cycle Stealing at default.

I haven't tested KH1 yet. I will edit this post

GSDX Settings: https://i.imgur.com/wiBclnl.png

**Comment by gregory38** [comment] 2015-11-05 11:21
```
Adaptive SSAA is considered by devs and if I look at gregory's productivity curve in the last month's I guess it will be implemented at some point.
```
Please don't make any hypothesis on my agenda (I'm very busy).

First it would be better to test the speed impact on Native. Then KH reads the GPU memory from the EE threads in video cutscene. I change a bit the sync method to be gl thread compatible (maybe we do too much sync). It was done just before the git moving. However I think it is only done a couple of time so it is unlikely to have a speed impact (but you know).

**Comment by Tyestor** [comment] 2015-11-05 16:34
Sorry gregory, I don't know what you mean. I mean, if 4x native runs fine, native will obviously run fine too, right? I tested it anyway, and yeah, it works fine. I saw GS jump to 45%, otherwise 25-35% at one point. EE 25-35% and VU 15-25%. Same settings as the OP except on native. This is on v1.3.1-1379-g6e7962e.

I don't know if it helps at all but here's a Native log: http://pastebin.com/5a2v6JMq

and a Native x5 log: http://pastebin.com/NFKFgru7

**Comment by willkuer** [comment] 2015-11-05 16:57
I would still say that this is a slowdown due to gpu limitations. If it happens only at higher upscaling and the gs thread doesn't have more cpu time it needs to be outside the cpu somewhere on the way or directly at the gpu. Or it is some special bug in the gs plugin because 5x native is handled differently (forgotten case or scaaler <= 4 or something like that).

Iso load time bottleneck would happen as well on native. I guess the cutscene is just not prerendered.

What happens if you increase the scaler to 6x or 8x native?

**Comment by deadair3210** [comment] 2015-11-05 17:20
The only cut scenes in KH that are pre-rendered are the opening and closing cut scenes to the game, the ones that look drastically different quality wise from the rest of the cut scenes.

**Comment by Tyestor** [comment] 2015-11-06 05:46
Pretty much what deadair said, there's almost no non pre-rendered cutscenes in KH. 8x just slows the cutscene down even further (16 FPS or something). Still no slowdown in actual gameplay though, curiously.

**Comment by gregory38** [comment] 2015-11-08 13:41
Your GPU can't keep it. Normally GPU are severals draw-calls late. I'm nearly sure that we're trying to read the framebuffer. Therefore we must flush all pending drawings. Impact is bigger with upscaling and it also consumes more memory bandwidth (both cpu&gpu).

**Comment by gregory38** [comment] 2015-12-04 15:08
I'm closing the report as I think your question was answered. Slowdowns are only accepted at the native resolution.

**Closed by gregory38** 2015-12-04 15:08 UTC
Labels: Question

**Comment by auwsmit** [comment] 2018-09-26 16:56
What if his specs were slightly worse, such that he could run all his games at native (and even higher) resolution with the exception of the Kingdom Hearts 1 Destiny Island cutscenes? Myself and many others are in this boat, but rather than providing some kind of potential game-specific patch or option to fix this singular issue, we are told to ignore it or to pay for better hardware.

Perhaps it is trivial enough to be a non-issue, or perhaps the effect(s) in the cutscene are just CPU-intensive with no easy workaround possible. Is anyone willing to look into this, or is Moore's law enough that lower/mid-tier hardware simply gets the short end of the stick?

I don't mean to come off as entitled or whiny, I just think that this is a valid issue that deserves to be addressed more directly.

**Comment by willkuer** [comment] 2018-09-26 18:55
Again the forum is a much better place to ask since you want to solve a problem that more than one person observed before. You however asked in the dev section where only a few devs are available and most of them have good specs.

You problem is most probably a different one. I‘d assume your cpu is the issue here and that might be solvable by some speedhacks. However you did not provide enough information to analyze this further. All information we now got is that your pc is slightly worse (whatever that means) and you run at native resolution (without any reference to other settings) and you got lags (without specification how severe and what the performance readings show).
