### ISSUE TITLE
Jackass The Game (NTSC-U) [SLUS-21627] Black Vertical lines only in hardware mode

### ISSUE THREAD

**Issue by shandawgy** [PCSX2/pcsx2#269] opened 2014-08-21 20:18 UTC
On a few missions in game there are black vertical lines that are spaced out over the screen only in hardware mode. Skip 1 draw dose fix the lines. I also get the following appear on the pcsx2:

padman: *** VBLANK OVERLAP ***

The fastest way to see the lines are shown in the beginning missions:

Roof top cart stop
suburban wake boarding
golf rally

My pcsx2 version is:
pcsx2-v1.2.1-511-g02b19b7

Plugins:
GSDx 20140818023333(MSVC 18.00,AVX) 0.1.16 [GSdx32-AVX]
XPad 0.2.0
SPU2-X 2014081802333 2.0.0
cdvdGigaherz (20140818023333ll) 0.9.0

My specs are:
Intel core i5-3470T CPU @ 2.90GHz
2x NVidia 560 GForce graphics card SLI
8gb Ram
Windows 8 64bit

**Comment by ssakash** [comment] 2015-02-19 12:23
looks like the specific problem is fixed on having skip draw hack to 1. is it still a valid gsdx:hardware issue ?

**Comment by gregory38** [comment] 2015-06-30 10:00
Please try the build from this thread http://forums.pcsx2.net/Thread-GSdx-2-0

Note: OpenGL only.

**Comment by gregory38** [comment] 2015-08-05 09:03
Please test the openGL renderer on latest dev release. The issue is likely fixed.

**Comment by gregory38** [comment] 2016-04-25 15:02
Any news on a recent GSdx (openGL)

**Comment by gregory38** [comment] 2016-05-05 17:37
The issue is likely fixed in latest openGL with hardware depth support

I'm closing the issue because original poster is mia.

**Closed** 2016-05-05 17:38 UTC
Labels: GSdx: Hardware, Plugin: GSdx, Waiting feedback
