### ISSUE TITLE
Final Fantasy X crashes when defeating Final Aeon / assertion failed: vpu/vif invalid unpack

### ISSUE THREAD

**Issue by clbr** [PCSX2/pcsx2#1350] opened 2016-05-07 14:08 UTC
When finishing the second form of Braska's Final Aeon, pcsx2 1.4.0 crashes.

![pcsx2bug](https://cloud.githubusercontent.com/assets/790333/15092546/d3ba44d4-145c-11e6-9ef6-e04178d3b0ec.png)

(copying by hand from the image, excuse any typos)
Function: VifUnpackSSE_Dynarec::ModUnpack(int, bool)
Thread: EE core
Condition: false
Message: Vpu/Vif - Invalid unpack! [3]

FFX iso md5sum: cde762d23d647a910a3b392d595f7426

Pressing "no" caused a second assertion to pop up, pressing no to that crashed pcsx2. Would it be useful if I got a save state right before it happens? Using the software mode.

**Comment by clbr** [comment] 2016-05-07 14:26
Here's a cap of the second assert:
![second](https://cloud.githubusercontent.com/assets/790333/15092650/9f271744-145f-11e6-9d17-eb91d3f8137a.png)

**Comment by clbr** [comment] 2016-05-07 14:42
Here's a save state right before. Press X twice, the boss'll die and pcsx2 goes down in flames.
https://u.pomf.is/qzpmku.p2s

The original filename is SLUS-20312 (F0800C1E).01.p2s

**Comment by refractionpcsx2** [comment] 2016-05-07 16:14
Are you using any speedhacks or gamefixes?

**Comment by clbr** [comment] 2016-05-07 17:14
None. My settings are all defaults, except using my forked gsdx graphics plugin. I can post the ini files if needed.

**Comment by refractionpcsx2** [comment] 2016-05-07 18:17
Hmm okay, does it crash consistently? or is it really random? are you able to try some older builds to see if you can find where it started?

**Comment by clbr** [comment] 2016-05-07 19:58
Consistently, every time at the same place, with the same assert.

Can't really try older (or newer) builds as it takes a bit to build and I'm short on time. How do you know it used to work? Even in git I see the 3 codepath in that function asserts.

**Comment by refractionpcsx2** [comment] 2016-05-07 20:54
You can get builds from the buildbot to check older builds, you don't need to build anything :)

http://buildbot.orphis.net/pcsx2/index.php?m=fulllist

**Comment by clbr** [comment] 2016-05-08 07:26
Those are Windows builds, I'm on Linux. I can't use the official ppa packages either, because they don't recognize my controller (bug open).

I don't know what vif is or what 3 means, but here's my thoughts from experience with git and other emulators:
- the unpack mode, 3, is most likely a constant in the original code
- this means it's highly unlikely for pcsx2's translator to mistranslate a different number to 3
- git blame shows the 3 path in this function has never worked

With FFX being a popular game, I guess it's just a rare iso. It's a pre-release, showing "please enjoy this playable demo" on startup, containing some videos in Japanese, some small bugs, etc. With this in mind, someone having completed a final eur/usa ffx release may not mean anything about this iso.

(random note: I still see the turned bosses and inverted controls in some rooms, even though those are marked fixed long time ago in the pcsx2 wiki. Curious)

**Comment by refractionpcsx2** [comment] 2016-05-08 10:03
As far as I'm aware there is no unpack mode 3, at least no official one.  I guess this calls for some testing, but generally it does this if the dma packet is bad

**Comment by jobs-git** [comment] 2016-06-05 09:57
I have finished FFX using PCSX2 v 1.2, its definitely playable, finshable and amazing! Though there are some point at which FPS slows down it just take some simple restart.

**Comment by MrCK1** [comment] 2016-06-07 01:39
@jobs-git I think that you're using an outdated build, as the issue here refers to the latest stable release; which is v1.4.0.

**Comment by jobs-git** [comment] 2016-06-07 04:59
@MrCK1 well the OP himself mentioned that he can't try older version due to time constrain in his part, that means, if he got the luxury he could try it, I am just confirming that it can be finished in older version thus helping us a bit in isolating the problem.

**Comment by clbr** [comment] 2016-06-07 08:36
@jobs-git But was it this specific ISO that you finished on 1.2?

**Comment by jobs-git** [comment] 2016-06-08 01:53
I could not confirm, but I dont have a pre release note during the intro. 

Maybe, it is the reason why your iso is pre-release, some buggy code during porting. It is better to get a new ISO in your part.

**Comment by clbr** [comment] 2016-06-08 07:22
It's possible save files aren't compatible between versions, and with
so much time taken, I already watched the ending on youtube anyway. So
I don't really need to get this working anymore, but it would be good
to find if it's a pcsx2 bug anyway.

**Comment by winapp2** [comment] 2016-08-25 22:50
Please go to the same place without a memcard or savestate. I belive this is the issue.

**Comment by clbr** [comment] 2016-08-26 08:01
Uh, you are aware it takes 40 hours or more to get there?

**Comment by winapp2** [comment] 2016-08-26 10:03
Yeah, you either have to close this Issue or have 40 hours fun. Because, there's no sure way to tell people, if this bug is because of PCSX2 or the old savestates fault. Is this savestate you are linking your own or another one's savestate?

**Comment by FlatOutPS2** [comment] 2016-08-26 10:22
I extremely doubt that's the issue.

@clbr Instead of posting the md5sum, can you share the game CRC(example: BB3D833A) and serial number(example: SLUS-20312)? It should be in the log(top of the log window?).

**Comment by worsety** [comment] 2016-08-26 11:43
Reproducing from the start of the game would be silly, from a save on a memory card is fine.

**Comment by clbr** [comment] 2016-08-26 14:20
The savestate is my own, completely from my own playthrough.

@all: Please don't delete or drastically edit posts. It makes things look very weird. If you make a mistake, mark it like "edit: sorry, blabla", don't erase things out of existence.

**Comment by winapp2** [comment] 2016-08-26 16:36
If it's yours then this problem related to pcsx2.

**Comment by jobs-git** [comment] 2016-08-28 20:42
Do you have the ps2 memcard save near that point?

**Comment by clbr** [comment] 2016-08-29 09:11
I do, but the last save point is about an hour before this. Do you still want it?

**Comment by jobs-git** [comment] 2016-08-29 09:33
Yhea, i could play it thru, and reach that buggy code

**Comment by clbr** [comment] 2016-08-29 09:42
https://u.pomf.is/mkacck.zip

Github's file uploading is broken again, so had to use an external host.

**Comment by jobs-git** [comment] 2016-08-29 11:53
your pcsx2 version is from the site or github?

**Comment by clbr** [comment] 2016-08-29 11:59
It's compiled from the 1.4.0 release tarball.

**Comment by jobs-git** [comment] 2016-09-11 08:11
I get this, Final Fantasy File data not found

**Comment by gregory38** [comment] 2016-09-11 08:59
@refractionpcsx2 we did some fix for vif mode 3 with the help of the testsuite, didn't we?

So I think the initial assertion ought to be fixed in latest git.

**Comment by refractionpcsx2** [comment] 2016-09-12 17:39
I think we did yes, it would be worth testing.

**Comment by refractionpcsx2** [comment] 2016-10-24 09:55
Is there any update on this?

**Comment by jobs-git** [comment] 2016-11-05 20:18
Ok, I tested it, I have reached upto 2nd Jeck Aeon Battle no problem so far. I think if there really is an issue, I should get his error during the first boss battle, but nothing happened.

**Comment by jobs-git** [comment] 2016-11-05 20:20
Ok, I tested it, I have reached midway 2nd Jeck Aeon Battle no problem so far (darn I rushed it its so difficult to beat). I think if there really is an issue, I should get his error during the 2nd boss battle, but nothing happened.

**Comment by refractionpcsx2** [comment] 2016-11-05 22:00
@clbr can you confirm you no longer have a crash?

**Comment by jobs-git** [comment] 2016-11-05 22:09
I think he will keep getting the crash as he uses a pre release iso, btw, I am testing from PCSX 1.4.

**Comment by FlatOutPS2** [comment] 2016-11-05 23:15
> I think he will keep getting the crash as he uses a pre release iso

That's the big hurdle. Until we can rule out this isn't a pre release bug that occurs on PS2 as well, we can't be sure this is actually a PCSX2 issue.

**Comment by sudonim1** [comment] 2016-11-05 23:59
The hell? It's definitely just the pre-release code that's buggy, this is obviously invalid.

**Comment by refractionpcsx2** [comment] 2016-11-06 00:47
If it's pre-release (I hadn't actually read the whole thread) then I don't really care. If it's fixed, it's fixed.

**Closed by refractionpcsx2** 2016-11-06 00:47 UTC
Labels: Vif

**Comment by jobs-git** [comment] 2016-11-06 05:44
found my old old old save file from PCSX 1.3 for ffx loaded it for PCSX 1.4, finished up to the credits without any issue, except slowness, I expect it since there is no AVX plugin there, so sad ending :'( and so great game!

**Comment by jobs-git** [comment] 2016-11-06 05:47
found my old old old save file from PCSX 1.3 for ffx loaded it for PCSX 1.4, finished up past the Super Final Yu Yevon boss without any issue, except slowness, I expect it since there is no AVX plugin there, so sad ending :'( and so great game!
