### ISSUE TITLE
[BUG]: Itadaki Street 3 (Sound Issues & Strange slowdowns)

### ISSUE THREAD

**Issue by Sunken54** [PCSX2/pcsx2#11199] opened 2024-05-05 22:27 UTC
### Describe the Bug

The ingame music stops playing after 10 seconds of gameplay (only SFX remains) and the CPU doesn't play like on original hardware (strange slowdown on CPU's turn and missing dialogues).

First and foremost, I have thousands hours of gameplay on original hardware so I can describe exactly how the game should act. I can provide videos of original game on original hardware to help understanding how it should be.

### Reproduction Steps

I tested on latest build (1.7.5782 actually) but never worked on previous versions too.

Machines used for testing:

-PC with intel Core i7 + RTX 3080 + 32GB RAM
-PC with Ryzen 5800U + 16GB RAM
-Mac mini M2 Pro
-Macbook Pro M2 Pro
-Steam Deck with Flatpak build

Tested with the most compatible configuration (native resolution and no tweaks) and tested with various combinations of EE speed and cycles (took me hours of testing).

The music glitch is easily reproducible in the first select menu (just wait around 10 seconds and the music stops). For those who really know the game, there's a difference in timing when the text appears. There's some strange slowdown).

But the worst occurs ingame. You can easily test it when creating a new game (1st menu). Just keep validating with O to start a new game and select 3 CPU opponents and a random map.

When in game, you can roll the dice and play flawlessly when it's your turn (exept the music glitch) but on CPU's turn, a dialogue box should appear but it doesn't. The game acts like it's seeking for data and you can show the dialogue box like a fraction of second. Game speed should be very quick but this data seeking takes a lot of time comparing to the original. CPU's dice roll is very long too as it should be immediate.

### Expected Behavior

So, the original game plays with ingame music and CPU's turn is really quick with dialogue boxes and no wait time when rolling the dice.

As it's my favorite PS2 game (Yes, I know it's weird), I could never thank you enough if you can solve these issues. Feel free to ask me if you need more details.

Thanks a lot for your help and your awesome work! <3

### PCSX2 Revision

1.7.5782

### Operating System

Windows 11

### If Linux - Specify Distro

Steam OS / KDE

### CPU

Default settings and native resolution without any tweaks

### GPU

RTX 3080

**Comment by Mrlinkwii** [comment] 2024-05-05 22:48
Duplicate of #3500

**Closed** 2024-05-06 02:23 UTC
Labels: Bug
