### ISSUE TITLE
[BUG]: Driver timeouts with RDNA3 GPUs on Windows + Vulkan

### ISSUE THREAD

**Issue by Wolver32** [PCSX2/pcsx2#10720] opened 2024-01-25 21:43 UTC
### Describe the Bug

I already reported this issue on Discord one or two weeks ago but I decided to put it also here as I've seen other people having similar issues. At the time I didn't provide a GS Dump, but now I am doing so. The dump was recorded in VCS while playing in Software mode, when changing to Vulkan the driver timeout occurs between frames 480-500, usually around 490. Here's the link: https://drive.usercontent.google.com/download?id=19zbfSnzsAGUvRRz2T5x2beABn7KF1mxA&export=download
(check comment below in case this link doesn't work anymore)

From what I understand, this seems to be happening only on RDNA3 cards. If you want me to test other stuff with these 2 games and/or post more dumps, feel free to ask.

### Reproduction Steps

In VCS I can always replicate the issue when going above the wooden bridge near the military base, in LCS I haven't found a spot where I can trigger it consistently. I haven't done extensive testing with other APIs, but after around 30 minutes of continuous playtime in VCS with DX12 I didn't notice a single crash.

I also did a few tests on Fedora Silverblue with one of the latest nightly AppImage builds, RADV never crashed so I would mark this as a Windows-only issue.

### PCSX2 Revision

v1.7.5509

### Operating System

Windows 11

### CPU

Intel Core i5-12600KF

### GPU

AMD Radeon RX 7800 XT

### GS Settings

- Aspect Ratio = 16:9
- FVM Aspect Ratio: 16:9
- Internal Resolution = 8x
- Anisotropic Filtering = 16x
(Happens even at default settings)

**Comment by refractionpcsx2** [comment] 2024-01-25 21:54
Okay here's a local copy of the dump, I recompressed it to xz (down from over 600mb to about 200mb), then compressed in to zip volumes.

Because Github sucks and doesn't let you upload anything without a known extension, I had to add `.zip` to the end of all the files, so you will need to remove that before extracting.

This is simply so if the google drive link dies for any reason, we have a copy on github too, I wouldn't recommend putting in the effort unless you need to :P

[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.001.zip](https://github.com/PCSX2/pcsx2/files/14058028/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.001.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.002.zip](https://github.com/PCSX2/pcsx2/files/14058029/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.002.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.003.zip](https://github.com/PCSX2/pcsx2/files/14058030/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.003.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.004.zip](https://github.com/PCSX2/pcsx2/files/14058032/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.004.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.005.zip](https://github.com/PCSX2/pcsx2/files/14058037/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.005.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.006.zip](https://github.com/PCSX2/pcsx2/files/14058039/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.006.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.007.zip](https://github.com/PCSX2/pcsx2/files/14058040/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.007.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.008.zip](https://github.com/PCSX2/pcsx2/files/14058042/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.008.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.009.zip](https://github.com/PCSX2/pcsx2/files/14058043/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.009.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.010.zip](https://github.com/PCSX2/pcsx2/files/14058044/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.010.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.011.zip](https://github.com/PCSX2/pcsx2/files/14058045/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.011.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.012.zip](https://github.com/PCSX2/pcsx2/files/14058046/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.012.zip)
[Grand Theft Auto - Vice City Stories_SLUS-21590_20240125192703.gs.zip.013.zip](https://github.com/PCSX2/pcsx2/files/14058047/Grand.Theft.Auto.-.Vice.City.Stories_SLUS-21590_20240125192703.gs.zip.013.zip)

**Comment by stenzek** [comment] 2024-01-26 12:21
I can't reproduce any GPU crash on my NV GPU, nor are any validation errors showing. So it's either an AMD driver issue, or something the validation layers aren't checking for.

Can't really do much about it, or narrow it down to the exact draw/shader, as I don't have one of these GPUs.

**Comment by Wolver32** [comment] 2024-01-26 13:09
It'd be nice if someone with a non-RDNA3 AMD GPU could do a test. I saw a few people on the Discord server discussing about RNDA3-specific crashes and so I imagined that other AMD GPUs aren't affected. With my old RTX 3060 I never experienced any crashes.

I own 2 other games (Gran Turismo 3 and 4), those don't seem to cause driver timeouts when running under Vulkan... But I should probably test them more to confirm that they're not affected.

I am no expert and I really have no idea on what could cause these timeouts, but if the Mesa driver works just fine in Linux I think there's probably something weird going on with the AMD Windows driver.

**Comment by Wolver32** [comment] 2024-01-31 21:48
Today I had a bit of free time and so I did a few more tests...

Update 1: I played Gran Turismo 3 for around 50 minutes, Windows + Vulkan, 8x resolution, 16x AF and Basic Blending Accuracy. I had zero issues while playing, everything looked normal. I then decided to crank Blending Accuracy all the way up to Maximum, the 7800 XT should have the horsepower to handle it. Result: driver timeouts after around 5-10 minutes of play. While I can't reproduce it consistently (like I managed to do in VCS), I changed the title of this bug report and made it more generic as I'm sure there are other games that trigger driver timeouts in particular conditions. I tried messing around with the Blending Accuracy in VCS, but even with Minimum the crash occurs at the exact same spot.

Update 2: I decided to try older PCSX2 builds with VCS. The first one I chose is v1.7.3722-64bit-AVX2-Qt from December 16th 2022, Vulkan, 8x resolution, 16x AF and Blending Accuracy set to Maximum, result: the crash didn't occur on the usual bridge, but after around 15 minutes in the ferris wheel area. I then picked an even older build, v1.7.2264-64bit-AVX2 from January 23rd 2022 (one of the earliest Vulkan implementations), and ran again VCS with the previous settings... After around 30 minutes of gameplay I didn't have a single crash! Of course I can't be 100% sure that this build will never trigger driver timeouts, but it definitely seems more stable than current ones. Maybe some newer Vulkan extension that doesn't play too well with the AMD Windows driver?

This weekend I should have time to test more stuff.

**Comment by Wolver32** [comment] 2024-02-04 15:48
Here I am with another report, this will be a long one with lots of numbers... I decided to test if resolution and/or blending accuracy have an impact in driver timeouts (spoiler: yes), to do this I used the GS Dump that I posted here and each time I took note of the frame where the driver crashed. I started by checking all resolutions at default settings (including Blending Accuracy, which is set to Basic), I did 3 passes for each resolution:
- Native (PS2): 118 118 118
- 1.25x Native: 118 118 118
- 1.5x Native: 118 118 118
- 1.75x Native: 118 122 118
- 2x Native: 118 120 128
- 2.25x Native: 189 180 188
- 2.5x Native: 248 248 248
- 2.75x Native: 324 324 324
- 3x Native: 378 378 378
- 3.5x Native: 388 388 388
- 4x Native: 390 400 402
- 5x Native: 430 426 424
- 6x Native: 440 440 440
- 7x Native: 444 444 444
- 8x Native: 490 490 490
![image](https://github.com/PCSX2/pcsx2/assets/130566900/b64625fa-d378-43f5-ac01-0e94a911d64c)

With Blending Accuracy set to its default setting (Basic), it's clear that a driver timeout is triggered later at higher internal resolutions. I then decided to take 3 resolutions to test the other Blending Accuracy settings: Native (which gave the worst results), 3x (~1080p, seems to be a good middle ground) and 8x (best results). Let's see the results for the other Blending Accuracy levels...

Minimum Blending Accuracy
- Native (PS2): 118 118 118
- 3x Native: 378 378 330
- 8x Native: 492 490 490

Medium Blending Accuracy
- Native (PS2): 118 118 118
- 3x Native: 378 330 330
- 8x Native: 490 492 490

High Blending Accuracy
- Native (PS2): 118 118 118
- 3x Native: 378 378 330
- 8x Native: 492 490 492

Full Blending Accuracy
- Native (PS2): 118 118 118
- 3x Native: 378 378 330
- 8x Native: 490 490 490

There's really not much to say here, the results seem to be in line with Basic. There's however one more level that I haven't mentioned yet, and it gave weird results...
Maximum Blending Accuracy
- Native (PS2): PASSED PASSED PASSED
- 3x Native: 118 118 118
- 8x Native: 2 CRASH 2

Maximum Blending Accuracy completely changes everything, now Native resolution gives by far the best results by completing the whole GS Dump, while 8x either doesn't load at all or is able to show only 2 frames.
Considering that this is the first time that I see my GS Dump being reproduced in its entirety on Windows + Vulkan, I went in game for a quick test... I managed to play for around 3-4 minutes and then the screen went black, but after around 10 seconds it came back to life and emulation surprisingly continued; this happened 2-3 times, but eventually a driver timeout was triggered. So the combo Native + Maximum Blending Accuracy seems the most "stable", but it will eventually crash.
Feel free to ask me to test particular settings, I can't really interpretate these numbers.

EXTRA
Probably irrelevant, but around 30% of times that a driver timeout is triggered, an assertion error windows appears. Error message is at line 508 in GS/Renderers/Common/GSRenderer.cpp

**Comment by stenzek** [comment] 2024-04-23 04:03
Could you please re-test on the latest release? Apparently the feedback loop extension was causing GPU crashes on RDNA3, which I've now dropped, so with any luck this should be resolved, if it's the same issue.

**Comment by Wolver32** [comment] 2024-04-23 08:15
I don't have much time today, but I still was able to do a quick test with GTA VCS. I used 8x resolution scale, 16x Anisotropic Filtering and Maximum Blending Accuracy, these settings instantly caused driver timeouts.
With the latest release my old GS Dump passes and even during gameplay I was able to go past that bridge. I went around the map for around half an hour and the game behaved and performed just as I expected, but my session was unfortunately ended by another driver timeout:
![image](https://github.com/PCSX2/pcsx2/assets/130566900/ce2527c7-e3fd-4e95-80e4-111d9545eea4)

It happened seemingly at random as I was just trying to land a helicopter, yesterday when I was testing another build posted on the Discord server I experienced it after the "Welcome to Vice City" loading screen (when going to the other island). Still, there's clearly a major improvement.

**Comment by stenzek** [comment] 2024-04-23 10:19
Oh well. Will have to wait until someone with a RDNA3 GPU looks into it then. I'm not going to rush out and buy one just for PCSX2 :P

**Comment by Wolver32** [comment] 2024-05-02 16:04
Recent versions now always pass with my old [GS Dump](https://drive.usercontent.google.com/download?id=19zbfSnzsAGUvRRz2T5x2beABn7KF1mxA&export=download) that I posted here and during gameplay crashes seem random, so I'm not able to trigger a driver timeout reliably. I then used it on build v1.7.5720 (20th April 2024), which is one of the latest ones that has [this behaviour](https://github.com/PCSX2/pcsx2/issues/10720#issuecomment-1925800945) with my old GS Dump in relation to resolution and blending accuracy.

With your suggested settings, I performed 10 tests, 5 with default blending accuracy and the other 5 with maximum blending accuracy. The other settings are Vulkan + 8x Resolution Scale + 16x AF.

Default Blending Accuracy: the last non-vsync file across all 5 tests was 10001_vertex.txt which, without knowing anything, seems rather uninteresting given that number of draws was set to 10000 (and those files start from 1 and not 0).

Maximum Blending Accuracy: the last non-vsync file across all 5 tests was 04755_vertex.txt. I'll upload here the vertex.txt and context.txt files from the last run:
[04755_context.txt](https://github.com/PCSX2/pcsx2/files/15190908/04755_context.txt)
[04755_vertex.txt](https://github.com/PCSX2/pcsx2/files/15190910/04755_vertex.txt)

**Comment by refractionpcsx2** [comment] 2024-05-02 16:11
So Maximum died? confused why it's a lower number :D

**Comment by Wolver32** [comment] 2024-05-02 16:15
Maximum + 8x Res dies almost immediately (around frame 2), while Default + 8x Res dies around frame 490.
I guess that's why I get a lower number with maximum blending accuracy.

**Comment by refractionpcsx2** [comment] 2024-05-02 16:22
okay, when you did each run, did you delete the old files after noting the last one? Just wanna make sure we're looking at the right draw

**Comment by Wolver32** [comment] 2024-05-02 16:23
Yep

**Comment by Wolver32** [comment] 2024-05-02 16:26
Yes, all 5 tests (with max blending accuracy) ended with that exact file.

**Comment by refractionpcsx2** [comment] 2024-05-02 16:27
perfect, thanks! :)

**Comment by Wolver32** [comment] 2024-05-03 10:14
Updated the driver and tried your build, unfortunately it's a regression compared to recent nightly builds.
8x Resolution + Maximum Blending Accuracy now triggers a driver timeout around frame 660, which is a lot better than build v1.7.5720 (crashes at frame 2) but recent nightly builds don't have a problem with my GS Dump at these settings. Even in gameplay I got a crash after like 30 seconds.

**Comment by stenzek** [comment] 2024-05-03 11:13
Oh well. Like I said above, it won't be fixed until someone with the knowledge _and_ hardware looks into it. I'm out of random ideas to try, and there isn't any spec violation going on the current validation layers can detect.

**Comment by Wolver32** [comment] 2024-05-03 11:29
Thank you for trying though, I imagine the struggle if you don't have the hardware. Unfortunately my knowledge here is very limited, all I can do is helping test stuff... And whenever anyone wants me to try things, feel free to ask :)
For me personally it doesn't change that much as I'll continue to use PCSX2 on Linux, RADV works flawlessly and I have yet to encounter an issue there.

**Comment by stenzek** [comment] 2024-05-10 16:57
So like an idiot I went out and bought a GPU to debug this (and other uses too). It is completely random, and not a specific draw. But think I may have found a workaround.

Give #11223 a shot. I can't trigger a crash in any of the games that I could before (Ratchet, VCS).

**Comment by Wolver32** [comment] 2024-05-10 17:05
Oh wow, ok tomorrow I'll give it a shot!

**Comment by Wolver32** [comment] 2024-05-11 13:52
I think you fixed it!
I had around 40+ minutes of uninterrupted gameplay in VCS, yesterday around 20-ish, no driver timeouts to report. I'll still try a bit more in the coming days (especially with other games), but the results I got this time are more than promising. Thank you for investing time and money into this :)

One unrelated and minor thing that I noticed while testing is the water rendering being off... I don't know if this is again a RDNA3 exclusive thing, but this is what I'm seeing on Windows:
![VCS_Windows](https://github.com/PCSX2/pcsx2/assets/130566900/67d18d39-8e4b-43ab-a705-48296dc6b9c6)

While on Linux everything looks normal:
![VCS_Linux](https://github.com/PCSX2/pcsx2/assets/130566900/5d4249cc-ffe0-4702-802c-383d226a92c9)

I initially noticed it while playing on #11223, but then I also tried to see if it's the same on the last nightly build and the answer is yes. Those screenshots were taken from build 1.7.5799, same settings used on both OSes. I decided to post it here for now as it could be another RDNA3 issue, but if needed I can open another bug report.

**Comment by stenzek** [comment] 2024-05-12 01:54
Post a GS dump of it. Can't do much without one.

**Closed** 2024-05-12 01:55 UTC
Labels: Bug, OS: Windows, Needs Research

**Comment by lightningterror** [comment] 2025-01-02 17:45
Reopening as there are still other crashes remaining. Also see https://github.com/PCSX2/pcsx2/pull/12144

**Comment by crashGG** [comment] 2025-01-03 12:18
After a year of driver version iteration, the rdna3 gpu uses the latest 24.12.1 driver and works normally, and rarely loses response.

**Comment by mirh** [comment] 2025-02-02 12:47
Moving from #12144..
I noticed one while looking for differences with RDNA2 cards, and I think it may actually be the culprit of this whole ordeal (being the two architectures otherwise way too functionally identical to matter): *driverInfo* reports a completely [different](https://forums.guru3d.com/threads/amd-radeon-software-preview-drivers-dch-uwp.437511/page-77#post-6140045) compiler is used between RDNA 2 and RDNA 3 cards. First has the good ol' AMD proprietary one, while the second has LLPC (has anybody tested AMDVLK on linux?).
And I'm almost certain there must be some environment variable to switch the two (the compute people argue it's `AMD_ENABLE_LLPC` which I did find inside of *amdvlk64.dll*).. Idk though if only to switch RDNA2 to LLPC, or also to have 3 use the older code path.

p.s. I seem to understand they have some other [internal](https://github.com/GPUOpen-Drivers/xgl/blob/dev/icd/settings/settings.cpp) driver knobs that can be adjusted.. even though I have no clue whatsover about the way you'd do it (even bloody exe renaming wouldn't work, because despite having all kinds of beahviours for StrangeBrigade, Wolfenstein, Dooms, cs2, R6E, sniper elite 5 and whatnot they rely on `VkApplicationInfo` to match programs)

**Comment by Squall-Leonhart** [comment] 2025-03-01 23:14
has nothing to do with the compiler, 

RDNA3 has explicit requirements that a resource is transitioned back into the compressed general layout after having used VK_EXT_attachment_feedback_loop_layout (which itself is required so as not to feed compressed data into the loop and cause visual artifacts), if the resource is not transitioned back a pagefault will occur on present, so thats one factor to be aware of that can cause Device removal.

You also need to ensure you're cleaning up self referenced data so that the driver isn't leaking video memory, which on AMD (and recently nvidia) will also trigger device removal when paging beyond the available physical memory (unless using VK_EXT_pageable_device_local_memory)

VMA (as i noticed is being used) also has fragmentation issues (which contribute to OOM device removal), it now has a defragmentation api, but its left up to the developer to invoke it.
