### ISSUE TITLE
Baldur's Gate: Dark Alliance 2 (EU/PAL) - High pitched whining sound that persists long after combat sequences.

### ISSUE THREAD

**Issue by gannon345** [PCSX2/pcsx2#1721] opened 2016-12-26 01:34 UTC
***PCSX2 version:***
Various. Dev builds 1.5 revision 1351, 1530, 1705, and 1740 (latest build) tested. Issue is persistent through all of them.

***PCSX2 options:***
All defaults for sound options. Also tested with Directsound plugin to same result.

EE and speedhacks at defaults, excepting MTVU is enabled. 

GPU plugin:

Have tested various configurations on the OpenGL and DX11 renderer, issue seems unrelated to GSDX / renderer.

***Plugins used:***
All default plugins.

***Description of the issue:***

I searched the forums but didn't any info on this issue, so I don't think it's been previously reported. Randomly throughout Baldur's Gate: Dark Alliance 2 there is a sustained, high pitched whining sound that plays. I've tested with Directsound and with the default sound plugin, it occurs on both. It primarily seems to occur in combat, but when roaming dungeons, even after combat the sound will continue for a long, but seemingly random interval (could be a few seconds, could go on for several minutes and even persist through cutscenes).

***How to reproduce the issue:***
Just start the game and get into combat with any enemy. Issue occurs seemingly at random, but occurs very often, often enough to reproduce within a few minutes of play or less.

***PC specifications:***
Intel i5 4690k
8GB DDR3 1600
SSD Drive
Nvidia GTX 970 mini
Windows 8.1

**Comment by refractionpcsx2** [comment] 2016-12-26 08:07
As I said on the forum,  can you try setting the output module to "no sound" and see if the noise continues in those places?

**Comment by gannon345** [comment] 2016-12-26 19:23
Will test and see, hopefully later today.

**Comment by gannon345** [comment] 2016-12-26 20:51
Okay, tested, confirmed the sound goes away when we set the output in the SPU2 plugin to "no sound." There's no sound at all when that is set.  It comes back when we switch back to xaudio in the plugin.

Also, to confirm it's not a hardware or configuration issue, I hooked a 3.5" / spdif out from my PC's audio out directly to the soundbar's analog input, instead of running through HDMI ARC. The noise not only persists, but is actually much worse when connected that way.

I have a save state where the issue is occurring, and it's repeatable on reloading the state, but Github won't allow me to attach a zip file here for some reason. [Here's a link to it ](https://drive.google.com/file/d/0B255hrARvK6eVUdjZTh6aFQ2a2c/view?usp=sharing) on Google Drive.

**Comment by refractionpcsx2** [comment] 2016-12-26 21:39
ok thanks, that means there is an issue with SPU2-X :) Is it fine in 1.4.0? also how about if you disable the Effects Processing in SPU2-X?

**Comment by gannon345** [comment] 2016-12-26 21:59
I haven't checked, but will test in a bit. Haven't tried it in 1.4. Will the sstate be compatible?

**Comment by refractionpcsx2** [comment] 2016-12-26 22:33
The sstate won't be, you'll need to make an ingame save, the memorycards will be

**Comment by gannon345** [comment] 2016-12-27 00:45
I was hopeful, as it didn't occur for a while on 1.4, but the issue eventually reoccurred again inside the Red Fang Lair (about 20-30 minutes into gameplay). I tried to capture a save state when it occurred, but the state seems to have corrupted, the emulator crashed when I attempted to reload it. I do have the state file if you can somehow use it.

Also, disabling effects processing on 1.5 did not change it either.

**Comment by refractionpcsx2** [comment] 2016-12-27 00:48
savestates aren't a lot of good due to the nature of how often they change, different versions of the game and how just generally unreliable they can be :P We'd be much better off with a memorycard save and instructions on how to get to the location you experience the issue

**Comment by gannon345** [comment] 2016-12-27 00:49
Also, no memcard saves around anytime the high pitched noise occurs, but as noted above I was able to replicate it on 1.4 after about 20 minutes of gameplay. It seems to occur at random, after observing it a bit. I've had it occur at the start of a cutscene, during combat, and the most recent time it occurred (this time on 1.4) was when accessing the level up screen and inventory. So there doesn't seem to be a particular trigger for it, unless it's one of the in-game sounds causing it to occur.

**Comment by refractionpcsx2** [comment] 2016-12-27 00:53
Hmm, random is even worse :/ although the most likely cause is a voice not keying off like it should do.  Does anything appear in the console window about keys being < 4 cycles or anything when it starts?

**Comment by gannon345** [comment] 2016-12-27 01:04
No errors at all in the console. Everything loads normally. Even the length of the high pitched whine varies. Like if I load it from the save state where I captured it, it will last for 5-6 seconds on one load, and then upon reloading could last for 20 seconds, 30 seconds, or even persist entirely until loading a new area.

The noise doesn't persist beyond loading screens.


Full console text below (note: my saves and the save state are from rev 1705, but I've tested and confirmed the issue is the same on 1740 previously). 

---------------------------------------

PCSX2 1.5.0-20161210223027 - compiled on Dec 11 2016
Savestate version: 0x9a0c0000

Host Machine Init:
	Operating System =  Microsoft Windows 8.1 Pro (build 9600), 64-bit
	Physical RAM     =  8134 MB
	CPU name         =  Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	Vendor/Model     =  GenuineIntel (stepping 03)
	CPU speed        =  3.499 ghz (4 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 7ffafbbf
	x86EFlags        =  2c100000

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA

Reserving memory for recompilers...

Loading plugins...
	Binding   GS: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\GSdx32-AVX2.dll 
	Binding  PAD: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\LilyPad.dll 
	Binding SPU2: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\Spu2-X.dll 
	Binding CDVD: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\cdvdGigaherz.dll 
(GameDB) 9708 games on record (loaded in 140ms)
	Binding  USB: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\USBnull.dll 
	Binding   FW: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\FWnull.dll 
	Binding DEV9: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\DEV9null.dll 
Plugins loaded successfully.

HLE Notice: ELF does not have a path.


Initializing plugins...
	Init GS
	Init PAD
	Init SPU2
	Init CDVD
	Init USB
	Init FW
	Init DEV9
Plugins initialized successfully.

Patches: No CRC found, using 00000000 instead.
Opening plugins...
	Opening GS
	Opening PAD
	Opening SPU2
Current Renderer: OpenGL (Hardware mode)
	Opening CDVD
isoFile open ok: D:\PS2 Games\Baldur's Gate - Dark Alliance II (Europe, Australia) (En,Fr,De)\Baldur's Gate - Dark Alliance II (Europe, Australia) (En,Fr,De).iso
	Image type  = DVD
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (1803776 sectors)
	Opening USB
	Opening FW
	Opening DEV9
3.x GL context successfully created
OpenGL information. GPU: GeForce GTX 970/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver: NVIDIA 376.33
INFO: GL_EXT_texture_filter_anisotropic is available
INFO: GL_ARB_gpu_shader5 is available
INFO: GL_ARB_draw_buffers_blend is available
INFO: GL_ARB_viewport_array is available
INFO: GL_ARB_shader_image_load_store is available
INFO: GL_ARB_clear_texture is available
INFO: GL_ARB_get_texture_sub_image is available

Available VRAM/RAM:3840MB for textures
GSdx Lookup CRC:0
McdSlot 0 [File]: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\memcards\Mcd001.ps2
McdSlot 1 [File]: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\memcards\Mcd002.ps2
Plugins opened successfully.
EE/iR5900-32 Recompiler Reset
	Bios Found: Japan   v01.00(17/01/2000)  Console
	BIOS rom1 module not found, skipping...
	BIOS rom2 module not found, skipping...
	BIOS erom module not found, skipping...
# Initialize memory (rev:3.17, ctm:393Mhz, cpuclk:295Mhz )
Frame buffer size set to  512x1280 (1536x3840)

PlayStation 2 ======== Hard reset boot
 ROMGEN=2000-0117, IOP info (CPUID=1f, CACH_CONFIG=ffffffff, 2MB, IOP mode)
 <20000117-050310,ROMconf,:11232>
# Total accessable memory size: 32 MB (B:2:8:0)
# TLB spad=0 kernel=1:12 default=13:30 extended=31:38
# Initialize Start.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize User Memory ...
# Initialize Scratch Pad ...
# Initialize Done.

EE DECI2 Manager version 0.06 Dec 10 1999 17:48:37
  CPUID=2e20, BoardID=0, ROMGEN=2000-0117, 32M

Patches: No CRC found, using 00000000 instead.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLES_521.87;1
(SYSTEM.CNF) Software version = 1.01
(SYSTEM.CNF) Disc region type = PAL
ELF (cdrom0:\SLES_521.87;1) Game CRC = 0xF59FF56B, EntryPoint = 0x00100008
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLES_521.87;1
(SYSTEM.CNF) Software version = 1.01
(SYSTEM.CNF) Disc region type = PAL


IOP Realtime Kernel Ver.0.9.1

    Copyright 1999 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadelf: fname cdrom0:¥SLES_521.87;1 secname all
loadelf version 3.30
Input ELF format filename = cdrom0:¥SLES_521.87;1
0 00100000 00262a40 .......................................
Loaded, cdrom0:¥SLES_521.87;1
start address 0x100008
gp address 00000000
# Loader 'cdrom0:¥SLES_521.87;1':pc=00100008
Elf entry point @ 0x00100008 about to get recompiled. Load patches first.
Overall 0 Widescreen hacks loaded
Loading patch 'F59FF56B.pnach' from archive 'D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\cheats_ws.zip'
comment: Widescreen Hack by El_Patas
(Wide Screen Cheats DB) Patches Loaded: 16
(UpdateVSyncRate) Mode Changed to PAL.
(UpdateVSyncRate) FPS Limit Changed : 50.00 fps
GSdx Lookup CRC:F59FF56B
end is at 7082a4 or 7373476 for non hex readin idiots
26113372 bytes free
break1
break1b Ptr:7374672 Size:26109276
break2
break2b
break1c
break1d
hihi
Get Reboot Request From EE

PlayStation 2 ======== Update rebooting..

PlayStation 2 ======== Update reboot complete
cdvdman Init


IOP Realtime Kernel Ver. 2.2

    Copyright 1999-2002 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadmodule: fname cdrom0:¥BG¥0MOD¥SIO2MAN.IRX;1 args 0 arg 
loadmodule: id 25, ret 0
loadmodule: fname cdrom0:¥BG¥0MOD¥PADMAN.IRX;1 args 0 arg 
loadmodule: id 26, ret 0
loadmodule: fname cdrom0:¥BG¥0MOD¥LIBSD.IRX;1 args 0 arg 
loadmodule: id 27, ret 0
loadmodule: fname cdrom0:¥BG¥0MOD¥SDRDRV.IRX;1 args 0 arg 
SDR driver version 4.0.1 (C) SCEI
 Exit rsd_main 
loadmodule: id 28, ret 0
loadmodule: fname cdrom0:¥BG¥0MOD¥MCMAN.IRX;1 args 0 arg 
loadmodule: id 29, ret 2
loadmodule: fname cdrom0:¥BG¥0MOD¥MCSERV.IRX;1 args 0 arg 
loadmodule: id 30, ret 2
loadmodule: fname cdrom0:¥BG¥0MOD¥HELLO.IRX;1 args 0 arg 
starto
loadmodule: id 31, ret 0
Stream Buffer 1Bank 32768byte 5banks 163840byte used
Frame buffer size set to  1280x1280 (3840x3840)
Loading savestate from slot 0...
	filename: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\sstates\SLES-52187 (F59FF56B).00.p2s
EE/iR5900-32 Recompiler Reset
	Loading GS
	Loading PAD
	Loading SPU2
MTVU speedhack is enabled, saved states may not be stable
Overall 0 Widescreen hacks loaded
Loading patch 'F59FF56B.pnach' from archive 'D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\cheats_ws.zip'
comment: Widescreen Hack by El_Patas
(Wide Screen Cheats DB) Patches Loaded: 16

**Comment by refractionpcsx2** [comment] 2016-12-27 01:07
Hmm sorry I can't accept this, your BIOS is not officially supported, it has a LOT of hacks in it, some of which are sound related. You were very unlucky to buy a first generation Japanese PS2 console.

**Comment by gannon345** [comment] 2016-12-27 01:10
Really? Which BIOS should I be using? I'll test.

**Comment by gannon345** [comment] 2016-12-27 01:23
Okay, tested with SCPH-39001. Same issue occurs on my save state, but I'm not sure if that's representative after changing the BIOS. I'll keep playing the game and see if the problem persists.

Full console log below:

-------------------------------

PCSX2 1.5.0-20161210223027 - compiled on Dec 11 2016
Savestate version: 0x9a0c0000

Host Machine Init:
	Operating System =  Microsoft Windows 8.1 Pro (build 9600), 64-bit
	Physical RAM     =  8134 MB
	CPU name         =  Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	Vendor/Model     =  GenuineIntel (stepping 03)
	CPU speed        =  3.499 ghz (4 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 7ffafbbf
	x86EFlags        =  2c100000

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA

Reserving memory for recompilers...

Loading plugins...
	Binding   GS: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\GSdx32-AVX2.dll 
	Binding  PAD: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\LilyPad.dll 
	Binding SPU2: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\Spu2-X.dll 
	Binding CDVD: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\cdvdGigaherz.dll 
(GameDB) 9708 games on record (loaded in 138ms)
	Binding  USB: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\USBnull.dll 
	Binding   FW: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\FWnull.dll 
	Binding DEV9: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\DEV9null.dll 
Plugins loaded successfully.

[wx] Failed to load shared library 'D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\plugins\DEV9ghzdrk.dll' (error 126: the specified module could not be found.)
Bios Found: USA     v01.60(07/02/2002)  Console
HLE Notice: ELF does not have a path.


Initializing plugins...
	Init GS
	Init PAD
	Init SPU2
	Init CDVD
	Init USB
	Init FW
	Init DEV9
Plugins initialized successfully.

Patches: No CRC found, using 00000000 instead.
Opening plugins...
	Opening GS
	Opening PAD
	Opening SPU2
Current Renderer: OpenGL (Hardware mode)
	Opening CDVD
isoFile open ok: D:\PS2 Games\Baldur's Gate - Dark Alliance II (Europe, Australia) (En,Fr,De)\Baldur's Gate - Dark Alliance II (Europe, Australia) (En,Fr,De).iso
	Image type  = DVD
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (1803776 sectors)
	Opening USB
	Opening FW
	Opening DEV9
3.x GL context successfully created
OpenGL information. GPU: GeForce GTX 970/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver: NVIDIA 376.33
INFO: GL_EXT_texture_filter_anisotropic is available
INFO: GL_ARB_gpu_shader5 is available
INFO: GL_ARB_draw_buffers_blend is available
INFO: GL_ARB_viewport_array is available
INFO: GL_ARB_shader_image_load_store is available
INFO: GL_ARB_clear_texture is available
INFO: GL_ARB_get_texture_sub_image is available

Available VRAM/RAM:3840MB for textures
GSdx Lookup CRC:0
McdSlot 0 [File]: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\memcards\Mcd001.ps2
McdSlot 1 [File]: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\memcards\Mcd002.ps2
Plugins opened successfully.
EE/iR5900-32 Recompiler Reset
	Bios Found: USA     v01.60(07/02/2002)  Console
	BIOS rom1 module not found, skipping...
	BIOS rom2 module not found, skipping...
	BIOS erom module not found, skipping...
# Initialize memory (rev:3.63, ctm:196Mhz, cpuclk:147Mhz detected)
Frame buffer size set to  512x1280 (1536x3840)

PlayStation 2 ======== Hard reset boot
 ROMGEN=2002-0207, IOP info (CPUID=1f, CACH_CONFIG=0, 2MB, IOP mode)
 <20020207-164243,ROMconf,PS20160AC20020207.bin:11552>
# Total accessable memory size: 32 MB (B:2:8:0) (363:2:7c30)
# TLB spad=0 kernel=1:12 default=13:30 extended=31:38
# Initialize Start.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize User Memory ...
# Initialize Scratch Pad ...
# Initialize Done.

EE DECI2 Manager version 0.06 Feb  7 2002 16:41:20
  CPUID=2e20, BoardID=0, ROMGEN=2002-0207, 32M

Patches: No CRC found, using 00000000 instead.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLES_521.87;1
(SYSTEM.CNF) Software version = 1.01
(SYSTEM.CNF) Disc region type = PAL
ELF (cdrom0:\SLES_521.87;1) Game CRC = 0xF59FF56B, EntryPoint = 0x00100008
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLES_521.87;1
(SYSTEM.CNF) Software version = 1.01
(SYSTEM.CNF) Disc region type = PAL


IOP Realtime Kernel Ver.0.9.1

    Copyright 1999 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadelf: fname cdrom0:¥SLES_521.87;1 secname all
loadelf version 3.30
Input ELF format filename = cdrom0:¥SLES_521.87;1
0 00100000 00262a40 .......................................
Loaded, cdrom0:¥SLES_521.87;1
start address 0x100008
gp address 00000000
# Restart Without Memory Clear.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize Scratch Pad ...
# Restart Without Memory Clear Done.
Elf entry point @ 0x00100008 about to get recompiled. Load patches first.
Overall 0 Widescreen hacks loaded
Loading patch 'F59FF56B.pnach' from archive 'D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\cheats_ws.zip'
comment: Widescreen Hack by El_Patas
(Wide Screen Cheats DB) Patches Loaded: 16
(UpdateVSyncRate) Mode Changed to PAL.
(UpdateVSyncRate) FPS Limit Changed : 50.00 fps
GSdx Lookup CRC:F59FF56B
end is at 7082a4 or 7373476 for non hex readin idiots
26113372 bytes free
break1
break1b Ptr:7374672 Size:26109276
break2
break2b
break1c
break1d
hihi
Get Reboot Request From EE
ROM directory not found

PlayStation 2 ======== Update rebooting..

PlayStation 2 ======== Update reboot complete
cdvdman Init


IOP Realtime Kernel Ver. 2.2

    Copyright 1999-2002 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadmodule: fname cdrom0:¥BG¥0MOD¥SIO2MAN.IRX;1 args 0 arg 
loadmodule: id 25, ret 0
loadmodule: fname cdrom0:¥BG¥0MOD¥PADMAN.IRX;1 args 0 arg 
loadmodule: id 26, ret 0
loadmodule: fname cdrom0:¥BG¥0MOD¥LIBSD.IRX;1 args 0 arg 
loadmodule: id 27, ret 0
loadmodule: fname cdrom0:¥BG¥0MOD¥SDRDRV.IRX;1 args 0 arg 
SDR driver version 4.0.1 (C) SCEI
 Exit rsd_main 
loadmodule: id 28, ret 0
loadmodule: fname cdrom0:¥BG¥0MOD¥MCMAN.IRX;1 args 0 arg 
loadmodule: id 29, ret 2
loadmodule: fname cdrom0:¥BG¥0MOD¥MCSERV.IRX;1 args 0 arg 
loadmodule: id 30, ret 2
loadmodule: fname cdrom0:¥BG¥0MOD¥HELLO.IRX;1 args 0 arg 
starto
loadmodule: id 31, ret 0
Stream Buffer 1Bank 32768byte 5banks 163840byte used
Frame buffer size set to  1280x1280 (3840x3840)
Loading savestate from slot 0...
	filename: D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\sstates\SLES-52187 (F59FF56B).00.p2s
EE/iR5900-32 Recompiler Reset
	Loading GS
	Loading PAD
	Loading SPU2

	Warning: BIOS Version Mismatch, savestate may be unstable!
		Current BIOS:   USA     v01.60(07/02/2002)  Console (crc=0x3a75b059)
		Savestate BIOS: Japan   v01.00(17/01/2000)  Console (crc=0x22b99c77)
		
MTVU speedhack is enabled, saved states may not be stable
Overall 0 Widescreen hacks loaded
Loading patch 'F59FF56B.pnach' from archive 'D:\pcsx2-v1.5.0-dev-1705-g415090d-windows-x86\cheats_ws.zip'
comment: Widescreen Hack by El_Patas
(Wide Screen Cheats DB) Patches Loaded: 16
Closing plugins...
	Closing DEV9
	Closing FW
	Closing USB
	Closing CDVD
	Closing SPU2
	Closing PAD
	Closing GS
Delete 0 Shaders, 62 Programs, 28 Pipelines
Plugins closed successfully.

**Comment by refractionpcsx2** [comment] 2016-12-27 01:25
Yeah please don't use savestates, if there are any faults they will carry them with them

**Comment by gannon345** [comment] 2016-12-27 01:27
Yep, I understand. I only created that save state to begin with as a means of directly accessing the sound issue one of the times it occurred; I initially thought it might help with troubleshooting. But I'm playing from a memory card save.

Not sure if I'll have more time to play and/or test tonight, but I'll keep an eye out for the issue and let you know if it persists.

**Comment by refractionpcsx2** [comment] 2016-12-27 01:45
I didn't think it used mipmapping because it has it's one special techniques for making things look fancy, you can probably disable mipmaps.

**Comment by gannon345** [comment] 2016-12-27 02:51
Okay, changing to SCPH-39001 BIOS has not fixed the issue, and has introduced new issues. Now there is a rapid, intermittent tapping or clicking noise in the background. And some sounds cutting in and out (spell effects, predominantly). The sound was actually running better on the Japanese BIOS. 0_o

I have found an area where the high pitched whine is repeatable every time with a specific enemy. When you fight the large blue bug enemies in the Earth Plane (Earth I zone), when you fight and kill them the whine happens.

[Here is a video of it happening](https://youtu.be/V9OCIN2Wyzc?t=8m41s), I believe also on an emulator but I'm not 100% certain. You can hear the sound in this video when the player fights those large blue monsters, but the sound goes away after what seems like a set interval. In my case, the high pitched sound lingers for a long time, varying. Sometimes it lasts 5-10 seconds, other times over a minute, and sometimes not going away until a zone change.

Github still won't let me attach ZIP files, but [here's a link to my memcard save ](https://drive.google.com/file/d/0B255hrARvK6eRHNhazQwVmR1Rlk/view?usp=sharing)in the area mentioned above in that video

**Comment by gannon345** [comment] 2016-12-27 03:29
Minor update: I didn't know about the Fast Texture Invalidation hack. I'm going to test that tomorrow (or next time I play in general) to make sure what's going on (specifically the new clicking/tapping sound) is not any sort of slowdown or engine speed issue.

**Comment by Dreadmoth** [comment] 2016-12-27 09:57
Not 100% sure, but I think I remember hearing a similar high pitched whine in a few places throughout the game last time I played Dark Alliance 2 on my PS2. Might check if I have any saves near that area

**Comment by gannon345** [comment] 2016-12-27 13:27
Yeah, I'm beginning to realize the whine is part of the game, as I've seen it in some videos too. The part where it lasts varying intervals and sometimes never stops until changing zones is the issue, it's supposed to end. But this seems like one of those issues that might be too random to immediately fix, there's no rhyme or reason I can tell for when it happens.

Also, I don't think it's supposed to be sounding in inventory menus or cutscenes, but can't say that with 100% certainty.

**Comment by MrCK1** [comment] 2018-03-26 03:00
@Dreadmoth @gannon345 Were either of you ever able to verify if this is an emulation bug or does it exist on real hardware? 

In addition, a test on latest git would be nice - unlikely anything has changed however.

**Comment by Dreadmoth** [comment] 2020-01-05 17:52
I found what seems to be a reproducible occurrence: [Memcard save](https://drive.google.com/file/d/1dJcn5tPsYsg2xe0sKqJCDIymBbB73O75/view)

Load save.
Go north, enter the door to Argesh the Gouger's Hold.
Watch cutscene. Buzzing sound starts after Argesh kills the orc, and persists through the rest of the cutscene and the boss battle, until the area is departed.
If the cutscene is skipped, the buzzing sound occurs anyway (maybe it emanates from the orc corpse?).

**The buzzing sound occurs on my real PS2** in this scene.
On PCSX2, it seems a bit louder relative to other sounds, but that may just be due to differences in audio setup / processing on my TV compared to PC.

**Comment by seta-san** [comment] 2021-10-02 01:54
Refraction did a ton of audio improvements around the last time this was commented on. And others say that the sound of present on ps2 hardware. Is this an issue?

**Comment by MrCK1** [comment] 2021-10-02 01:57
If this is the same issue that exists on the forum, I had ref test the other day and he did not hear any issues with audio. Possibly it has been resolved.

**Comment by seta-san** [comment] 2021-10-02 02:11
If the sound exists on hardware then he should hear it and this might never have been an issue to begin with

**Comment by MrCK1** [comment] 2022-06-12 01:33
Closing since it was replicated on HW.

**Closed by MrCK1** 2022-06-12 01:33 UTC
Labels: Bug, SPU2, Replicated on Real HW
