### ISSUE TITLE
Remove dependency DX Sdk

### ISSUE THREAD

**Issue by Zangetsu38** [PCSX2/pcsx2#1133] opened 2016-01-19 14:45 UTC
Please remove dependency with very old sdk (June 2010) and use Windows Kits include with Visual Studio 2015

**Comment by ssakash** [comment] 2016-01-19 15:07
duplicate of #564

**Comment by Zangetsu38** [comment] 2016-01-19 15:09
hmm why this issue clossed ?

**Comment by ssakash** [comment] 2016-01-19 15:17
> I think this can be closed. DirectX SDK will be required forever, at least for XAudio2 and XInput

**Closed** 2016-01-19 15:29 UTC

**Comment by Zangetsu38** [comment] 2016-01-19 17:03
hu Why ? xaudio 2 and xinput perfectly works with windows kit

**Comment by refractionpcsx2** [comment] 2016-01-19 17:06
It does, but only for windows 8 and above. We need to still support Windows 7 and to an extent XP support would be nice to keep, at least for the moment, using the windows sdk gets rid of older OS support completely, so we're not going to swap to it yet.

**Comment by Zangetsu38** [comment] 2016-01-19 17:09
What is the interest to continue to support XP and 7?
There are both dead!
It would be better to go ahead and passed a full support of Windows 10 with these new APIs (DX12 etc. ..)

**Comment by Zangetsu38** [comment] 2016-01-19 17:11
@refractionpcsx2 You tried to do a poll on your site or fb to see what OS people have had to pcsx2?

**Comment by deadair3210** [comment] 2016-01-19 17:15
Many people still use Windows 7 simply because they dislike the design of 8 and 10. I repair computers and out of the 25 computers i saw, 15 of them were running windows 7. Just because you think a OS is dead doesnt mean everybody else does.

**Comment by refractionpcsx2** [comment] 2016-01-19 17:15
We've seen users come for support who still use older OS's.

A large majority use windows 7, this week alone I've seen 2 or 3 people using XP.

**Comment by Zangetsu38** [comment] 2016-01-19 17:20
hmm I see, yet Windows XP really is death for drivers and the Microsoft Support.
For Windows 7, it's still good but it will not take long for him too.

**Comment by refractionpcsx2** [comment] 2016-01-19 17:25
Windows 7 isn't slow, no slower than windows 10.  A lot of people don't like the new start menu or the spying that goes on in the background and all the forced updating, plus people have reasons such as software not running under windows 10.

while you may think it's old because microsoft say it is, many people still love it. And so we cannot drop support for those operating systems.

If you check this graph of general internet users, there are more people on XP than Windows 10
https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0

**Comment by Zangetsu38** [comment] 2016-01-19 17:27
oh i see ^^

**Comment by willkuer** [comment] 2016-01-19 17:29
> Windows 7 isn't slow, no slower than windows 10. A lot of people don't like the new start menu or the spying that goes on in the background and all the forced updating, plus people have reasons such as software not running under windows 10.

Exactly my reasoning. I actually don't know why I should install a new windows version if everything works just perfectly. Sure Win10 is probably not bad. Neither is Win7.

**Comment by Zangetsu38** [comment] 2016-01-19 17:30
I did not say that Windows 7 was bad, just that Windows 10 was far better ^^

**Comment by deadair3210** [comment] 2016-01-19 17:40
Windows 7 is only slow on your ssd because it doesnt do a lot of the things windows 8 and 10 do automatically like use TRIM or allign partitions to the start of flash pages. With the right tools, I have even gotten Windows 7 to be faster than 10

**Comment by refractionpcsx2** [comment] 2016-01-19 18:10
Windows 7 fix do trim as soon as you put service pack 1 on. I can't vouch for the other thing though

**Comment by deadair3210** [comment] 2016-01-19 18:18
I did not know this, I thought the native drivers that 7 uses didn't support TRIM. Learn something everyday, I guess

**Comment by Zangetsu38** [comment] 2018-08-26 01:33
Any news for this ? tested compilled on VS 2017 15.8.1 and get same probleme before :( 
why just not bump on SDK 8.1 ? 
old sdk is just totaly dead now, june 2010 hm ^^

**Comment by MrCK1** [comment] 2018-08-26 01:36
We still use DirectSound in SPU2-X, so I believe that's part of the issue iirc.

**Comment by Zangetsu38** [comment] 2018-08-26 01:37
sdk for 8.1 no have that ?

**Comment by lightningterror** [comment] 2018-08-26 01:38
You can pretty much skip the sdk if you don't plan on compiling spu2-x.

**Comment by Zangetsu38** [comment] 2018-08-26 01:43
rpcs3 have code for use xaudio 2.7 in windows 7 and 2.8 or 2.9 in Windows 8/10, because juste, Windows is not compatibnle by defaut on xaudio 2.7 get buig on sound etc, 2.9 is perfect for it

**Comment by Zangetsu38** [comment] 2018-08-26 01:56
I have fixed my compilation issue and works good without installing old sdk, with just add few file in 3rdparty folder and add little code for it
![image](https://user-images.githubusercontent.com/5261759/44624097-ea7e7a00-a8e3-11e8-8830-d1c8981b0d85.png)
![image](https://user-images.githubusercontent.com/5261759/44624100-f5d1a580-a8e3-11e8-8bf1-8a89245e5b25.png)
you think that is good for can create pr ?

**Comment by MrCK1** [comment] 2018-08-26 01:57
No, it means you're doing something wrong. Everyone else can compile the peoject fine, so there's an issue on your end somewhere.

**Comment by Zangetsu38** [comment] 2018-08-26 01:59
yes  problem is need install old sdk, and so for that i no want, i using only sdk instamlmed with Visual studio 2017

**Comment by MrCK1** [comment] 2018-08-26 02:05
The SDK dependency isn't going anywhere soon, so you'll just have to install it if you want to compile PCSX2.

Besides it's just that - a dependency, what's the harm in installing the SDK on your PC?

**Comment by Zangetsu38** [comment] 2018-08-26 02:07
i don't want install it, it too old, i have already sdk needed, just need bump this on more recently sdk that all, i don't see any probleme for that, and my code your see in screen full works, i can compile it and it works good :)

**Comment by RedPanda4552** [comment] 2018-08-26 02:11
I think you're completely missing the point. The DX9 SDK doesn't exist for XAudio, it exists for the D3D9 renderer. There has already been plenty of discussion on removing it for the 1.6 stable release, but there is no ETA on when that will be right now. That said, you can compile everything except GSdx without the DX9 SDK just fine.

**Comment by Zangetsu38** [comment] 2018-08-26 02:12
eu ? i have never speek GSDX, it compile fine and good works, here i speak only for SPU2-X, but i have show, with add my folder and my small code, and can compile it and works fine

**Comment by RedPanda4552** [comment] 2018-08-26 02:14
Right... That's my point. SPU2-X compiles without the DX9 SDK. We have it, _for GSdx, not SPU2-X_.

**Comment by Zangetsu38** [comment] 2018-08-26 02:15
hmm not me, i have VS 2017 15.8 with windows kit 8.1 + windows kit 16.299

**Comment by RedPanda4552** [comment] 2018-08-26 02:16
You just said SPU2-X compiles.

**Comment by RedPanda4552** [comment] 2018-08-26 02:17
Regardless, I don't see why adding the SDK is a problem either, unsubbing thread.
