### ISSUE TITLE
Ratchet & Clank 2 - Megaturret Doesn't Work Correctly

### ISSUE THREAD

**Issue by erwark** [PCSX2/pcsx2#354] opened 2014-11-19 11:41 UTC
Core issue?

Issue title: Ratchet & Clank 2 (PAL/Australia) Megaturret Not Working

-PCSX2 version: 1.2.1 Stable

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx (SW or HW), SPU2-X, Lilypad, Linuz or Gigaherz CDVD,rest null plugins. Same issue under ZeroGS - ruling out Graphics.

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: The turrets from the Megaturret Glove (the upgraded Miniturrent Glove) just bounce up and down with their starting sound and animation looping. They don't work (shoot anything).

-How to replicate: Upgrade the Miniturret Glove to the Megaturret glove and use it.

-Last known version to work: Never worked (checked back to 0.9.7). Also checked most recent testing build.

-PC specifications: 
CPU: Intel Core i5 2500K @ 4.3Ghz 
GPU: Gigabyte Radeon 6950 1GB
OS: Windows 7 x64 SP1

-Other comments: Aside from this issue, the game runs fine under Software Mode. No settings/gamefixes seem to make a difference. 2 other people have posted the issue in the past with no resolution (but they stopped following up the issue pretty quickly). These people seemed to have 64-bit Windows and PAL-Region games, like me. I have not tried the NTSC release.

I've filled out the required info as I understand it and welcome any ideas or requests for more information.

Thanks.

**Comment by Hirato** [comment] 2015-11-13 09:21
This did happen on the consoles as well, but only occasionally.
The R&C wiki also suggests the issue plagues the NTSC version.

Something in PCSX2's operation seems to trigger the issue for every single turret, so they all end up stuck in an initialising state.
I've tried all the semi-relevant manual game hacks, as well as numerous combinations of the EE/VU precision options to no avail.
Is there anything I can do to help debug this?

**Comment by Nobbs66** [comment] 2016-04-26 14:49
I'll look into this sometime tonight.

**Comment by FlatOutPS2** [comment] 2016-04-26 15:11
There's also bug report on the forum about this:
http://forums.pcsx2.net/Thread-Bug-Report-Ratchet-and-Clank-2-Megaturrets-PAL-Australia

**Comment by atomic83GitHub** [comment] 2017-11-04 15:27
Still here with last 1.5 dev build, blockdump is comming.

**Comment by atomic83GitHub** [comment] 2018-01-02 14:09
Here is a blockdump of the issue:
https://drive.google.com/file/d/1LIlXu6o3_66aVH5M_-MZbaJwvW7zIDLt/view?usp=sharing

**Comment by RagnarokerXIII** [comment] 2018-04-08 19:39
Has this bug been fixed yet?

**Comment by MrCK1** [comment] 2018-04-08 19:43
Nobody knows what causes it yet...

**Comment by NoShotz** [comment] 2019-09-26 04:53
This seems to no longer be an issue.

**Comment by Dreadmoth** [comment] 2019-09-26 20:51
Issue persists for me (PAL version) on current master: [**loud** video](https://i.imgur.com/YCakCpp.mp4)

**Comment by NoShotz** [comment] 2019-09-26 21:05
I was playing on the NTSC version

**Comment by Legion495** [comment] 2021-01-08 21:21
Can confirm on 1.6.0 the PAL version of the game still got the issue.

**Comment by dualmacops** [comment] 2021-03-29 01:07
Tried with: v1.7.0-dev-1163-ga6fac1e00
The problem still persists...

**Comment by kozarovv** [comment] 2021-04-04 21:52
This seems to have nothing to do with VU, game get incorrect data for FPU compare. Function that load $f0 also not take data from VU. 

```
0x308140 move    $a0, $s4
0x308144 li.s    $f1, 6.5
0x30814C nop
0x308150 c.le.s  $f1, $f0 ($f0 at this point is 1.6 (0x3FCCCCCD))
0x308154 nop
0x308158 bc1f    def_307D34
```
Patching $f1 to 1.5 (0x3fc00000) make things work correctly. that what i was able to figure out. Real cause of bad data is still unknown. Also that can't be patched by pnach due to insane overlay system, and due to even more insane overlay loading system.. 
Only working way to hackfix it is patching iso with ppf, because every single game level have this function on different offset. And hooking loader not worked for me.

**Comment by Kwakoxium** [comment] 2021-09-14 18:33
I was hoping to find a solution, but I see that the problem is still mysterious. :')

Surprisingly, while trying to finish the last objective on a planet, the weapon evolved in Megaturret and time to got to the end, it was working, but it didn't last long, I didn't escape it. The problem unfortunately appeared when I changed planet. :(

**Comment by Vogtinator** [comment] 2021-09-23 18:07
> Patching $f1 to 1.5 (0x3fc00000) make things work correctly. that what i was able to figure out. Real cause of bad data is still unknown. Also that can't be patched by pnach due to insane overlay system, and due to even more insane overlay loading system..
> Only working way to hackfix it is patching iso with ppf, because every single game level have this function on different offset. And hooking loader not worked for me.

Great info, thanks a lot!

I used your disassembly to create a patch based on the mechanism used by https://github.com/PCSX2/pcsx2/pull/4541 (merged but got reverted later again):

```
           if (cpuRegs.code == 0x0280202d)
           {
                   if (*(int*)PSM(pc + 0x4) == 0x3c0140d0 && *(int*)PSM(pc + 0x8) == 0x44810800 && *(int*)PSM(pc + 0x10) == 0x46000836)
                   {
                           DevCon.Warning("Patching Ratchet and Clank bad COP2 sequence at PC %x", cpuRegs.pc);
                           memWrite32(pc + 0x4, 0x3c013f80);
                   }
           }
```

Appears to work fine here with the PAL version (sces-51607, CRC 2f486e6f).

**Comment by Kwakoxium** [comment] 2021-09-25 13:56
Could this fix the famous problem?  :D

**Comment by Helicosaurus** [comment] 2021-09-28 14:13
@Vogtinator Nice! If you have the time, I'd need some help so I can know how to apply the patch, so then I can help testing it.

**Comment by Vogtinator** [comment] 2021-09-28 14:20
> @Vogtinator Nice! If you have the time, I'd need some help so I can know how to apply the patch, so then I can help testing it.

I pushed the hack into a repo here: https://github.com/Vogtinator/pcsx2/tree/rc2hack. You can build from that branch to test it.

**Comment by Helicosaurus** [comment] 2021-09-28 15:34
I've successfully build from your repo, but I don't see anything in the logs about the fix (which doesn't appear to be enabled at all). I tried switching planets in-game without success. I have "Automatic Gamefixes", "Enable Cheats" and "Enable Widescreen Patches", on Release build x64 (Win10). [Here are the logs](https://pastebin.com/nKBm6TE2) (default + dev/verbose).

**Comment by Vogtinator** [comment] 2021-09-28 18:14
> EDIT: pinpointed it, having more than 5 turrets makes the first ones bug; there can only be 5 turrets coexisting properly.

That matches my experience on console, that generous use of turrets breaks new ones at some point.

**Comment by evjm** [comment] 2021-09-30 17:51
> > @Vogtinator Nice! If you have the time, I'd need some help so I can know how to apply the patch, so then I can help testing it.
> 
> I pushed the hack into a repo here: https://github.com/Vogtinator/pcsx2/tree/rc2hack. You can build from that branch to test it.

Well done in fixing the patch! For an absolute noob like myself, what is the easiest way to attach this patch or recode it? A step by step process if not too hard would be awesome thank you!

**Comment by Vogtinator** [comment] 2021-09-30 19:31
> > > @Vogtinator Nice! If you have the time, I'd need some help so I can know how to apply the patch, so then I can help testing it.
> > 
> > 
> > I pushed the hack into a repo here: https://github.com/Vogtinator/pcsx2/tree/rc2hack. You can build from that branch to test it.
> 
> Well done in fixing the patch! For an absolute noob like myself, what is the easiest way to attach this patch or recode it? A step by step process if not too hard would be awesome thank you!

I enabled builds in my fork, so you can download windows binaries from here: https://github.com/Vogtinator/pcsx2/actions/runs/1292303171

**Comment by evjm** [comment] 2021-09-30 20:59
> > > > @Vogtinator Nice! If you have the time, I'd need some help so I can know how to apply the patch, so then I can help testing it.
> > > 
> > > 
> > > I pushed the hack into a repo here: https://github.com/Vogtinator/pcsx2/tree/rc2hack. You can build from that branch to test it.
> > 
> > 
> > Well done in fixing the patch! For an absolute noob like myself, what is the easiest way to attach this patch or recode it? A step by step process if not too hard would be awesome thank you!
> 
> I enabled builds in my fork, so you can download windows binaries from here: https://github.com/Vogtinator/pcsx2/actions/runs/1292303171

Thank you! I will replace the files in the original with these.

**Comment by Sunnyweeb** [comment] 2021-10-24 01:11
hey sorry for being an absolute absolute noob, but is there a "guide" or "how to" i can follow to get the thing working x_x?

**Comment by Kwakoxium** [comment] 2021-11-06 21:50
It seems to work!

**Comment by Vogtinator** [comment] 2021-12-07 13:58
> the download links for the binaries all say expired are you able to repost them.

I triggered another build: https://github.com/Vogtinator/pcsx2/actions/runs/1549681004

**Comment by frogdude129** [comment] 2021-12-09 11:08
much appreciated thank you.

**Comment by GreyXor** [comment] 2021-12-30 13:06
@Vogtinator Thanks, it's works for me, maybe now we should open a PR for this patch ?

**Comment by Vogtinator** [comment] 2021-12-30 13:11
> @Vogtinator Thanks, it works for me, maybe now we should open a PR for this patch ?

Could be done, but the way the patch is applied is quite a hack. OTOH, #4541 did get merged temporarily...

**Comment by refractionpcsx2** [comment] 2021-12-30 13:14
I kinda want a better solution, I didn't like the hardcodedness of it, I kinda want a gamedb solution, but other stuff has gotten in the way.

**Comment by Vogtinator** [comment] 2021-12-30 15:10
I cleaned it up a bit and opened https://github.com/PCSX2/pcsx2/pull/5235. I noticed that for some reason my patch changed 6.5 to 1.0 instead of 1.5, so I changed it to 1.5 in the PR. It appears to work fine still.

Maybe this could be patched better if there was a mechanism to patch content read from disk? That would only work well if it's uncompressed though.

**Comment by rushbushnocap** [comment] 2022-02-19 16:02
hi, found this useful guide on how to solve the problem with megaturrets but the files are expired; can someone repost them?
(don't know if they work on 1.6.0 though)

**Comment by LingKuja** [comment] 2022-04-04 19:51
What's funny is that this issue is still happening. Sad, because on real hardware the Megaturret is a pretty neat weapon.

**Comment by RedPanda4552** [comment] 2022-04-10 17:11
In the interest of making the workaround more portable, I made an application using PINE to implement the workaround. Should work on any nightly builds which have PINE: https://github.com/RedPanda4552/RatchetTurretServer

**Comment by Karlthulu** [comment] 2022-05-16 09:57
To further simplify the patch, i have made an application, that directly patches the game code permanently.
https://github.com/Karlthulu/RC2TurretPatch

**Comment by LingKuja** [comment] 2022-05-16 21:23
> To further simplify the patch, i have made an application, that directly patches the game code permanently. https://github.com/Karlthulu/RC2TurretPatch

Just tried it and it solved the megaturrets popping. Great job

**Comment by TheDiggster13** [comment] 2022-09-06 11:18
> To further simplify the patch, i have made an application, that directly patches the game code permanently. https://github.com/Karlthulu/RC2TurretPatch

Also worked for me!

**Comment by Oskichi** [comment] 2022-10-16 14:38
It worked perfectly. Thank you very much!! :)

**Comment by kurokochee** [comment] 2022-11-19 16:55
I patched it from 29/29 to 0/29 and then it closed automatically but I dont see the patched rom. Where is the directory or is the rom that I choosed became the patched rom?

**Comment by Karlthulu** [comment] 2022-11-20 01:26
> I patched it from 29/29 to 0/29 and then it closed automatically but I dont see the patched rom. Where is the directory or is the rom that I choosed became the patched rom?

It should apply the patch to the rom that you chose, and change that file. There will not be any new file created

**Comment by kurokochee** [comment] 2022-11-20 04:09
> > I patched it from 29/29 to 0/29 and then it closed automatically but I dont see the patched rom. Where is the directory or is the rom that I choosed became the patched rom?
> 
> It should apply the patch to the rom that you chose, and change that file. There will not be any new file created

Is the name of the file the same? and is this for pcsx2 only?

**Comment by Karlthulu** [comment] 2022-11-20 07:10
> > > I patched it from 29/29 to 0/29 and then it closed automatically but I dont see the patched rom. Where is the directory or is the rom that I choosed became the patched rom?
> > 
> > 
> > It should apply the patch to the rom that you chose, and change that file. There will not be any new file created
> 
> Is the name of the file the same? and is this for pcsx2 only?

The patch fixes the rom you pick, so the file has the same name, and will be the same place that it was before patching. I only used pcsx2, so i do not know if the problem is even present while using other tools, but i see no reason, that it would be exclusive to one tool, as it only patches the rom, and does nothing with the emulator itself

**Comment by kurokochee** [comment] 2022-11-20 07:27
Is there a different version of RC 2 Pal or any RC2 Pal rom can use this?

**Comment by Karlthulu** [comment] 2022-11-20 09:52
> Is there a different version of RC 2 Pal or any RC2 Pal rom can use this?

As is also written on the project page, i have only done a small amount of testing. I downloaded a rom from somewhere, and used pcsx2 as my emulator. Others have indicated that it worked for them, if it doesn't work for you, i am not sure what the reason is, but I think it should work just fine.

**Comment by stenzek** [comment] 2022-11-20 10:04
@Karlthulu Please refrain from discussing piracy on our issue tracker.

**Comment by refractionpcsx2** [comment] 2022-12-27 23:19
dunno if any of you are still around, but if you could try #7708 on an unpatched disc and see if the dynamic patch works for the mega turret.

I've basically implemented the original dynapatch idea but better and editable in the gamedb, so hopefully that works better for you.

**Comment by Vogtinator** [comment] 2022-12-27 23:55
> dunno if any of you are still around, but if you could try #7708 on an unpatched disc and see if the dynamic patch works for the mega turret.

Works! Not sure where the patch log lines end up (I don't see them in the terminal), but the miniturrets work fine.

> I've basically implemented the original dynapatch idea but better and editable in the gamedb, so hopefully that works better for you.

I'm happy if something finally gets merged.

**Comment by refractionpcsx2** [comment] 2022-12-28 00:03
The patch line appears in the console log window at the moment the patching happens, probably as you throw a turret

**Comment by Vogtinator** [comment] 2022-12-28 00:09
Works: `[  234,2560] Applying Dynamic Patch to address 0x003863E0`

I had to find the option to enable the system console first - first time using the Qt GUI here.

**Closed** 2022-12-28 13:55 UTC
Labels: Core, Floating Point Accuracy

**Comment by xXCpF01Xx** [comment] 2024-09-08 10:33
is it possible to make a patch for aethersx2? Im playing the game in my s24 ultra and I would like to use megaturrets peepoSad

**Comment by LingKuja** [comment] 2024-09-08 15:07
> is it possible to make a patch for aethersx2? Im playing the game in my s24 ultra and I would like to use megaturrets peepoSad

It would be best to either ask in the [aethersx2 github](https://github.com/AetherSX2/AetherSX2), or some other arm related community.

**Comment by F0bes** [comment] 2024-09-08 15:51
> It would be best to either ask in the [redacted], or some other arm related community.

Please do not link to unofficial repositories. There are no known safe forks or redistributions of AetherSX2.

> is it possible to make a patch for aethersx2? Im playing the game in my s24 ultra and I would like to use megaturrets peepoSad

AetherSX2 is not managed by us and is no longer under active development.
