### ISSUE TITLE
Scroll bar doesn't work in debugger

### ISSUE THREAD

**Issue by Nobbs66** [PCSX2/pcsx2#864] opened 2015-10-01 17:34 UTC
*Build Tested PCSX2 1.3.1-0 - compiled on Sep 28 2015. 
*Issue: None of the scroll bars in the debugger work, but using the scroll wheel on your mouse does work.
*How to reproduce: 
   1)Open PCSX2 and start the debugger.
   2)Have an ISO selected in the ISO browser
   3)Hit run in the debugger
   4Instructions should fill the debugger, but you can't use the scroll bar to go through them. This forces the use of a scroll wheel and makes searching incredibly slow.

**Comment by avih** [comment] 2015-10-01 17:35
Is it a regression? if yes, what's the last build where it worked?

**Comment by willkuer** [comment] 2015-10-01 21:25
PageUp and PageDown keys are probably relevant solutions until the scrollbar is fixed.

**Comment by gregory38** [comment] 2015-10-12 20:10
related to #885 ?

**Comment by ssakash** [comment] 2015-10-13 15:08
@gregory38 

Nope, the current issue is based on the slider for ```CtrlDisassemblyview``` whereas the referenced PR adds a new slider to ```CtrlRegisterList```.

**Comment by gregory38** [comment] 2015-11-08 14:40
Assigned to wx expert

**Comment by turtleli** [comment] 2015-11-12 19:05
s/wx expert/person who fixed some wx bugs/ ;)

I don't think the scrollbar was designed to fully work - the disassembly can be a few 100k lines long, so proper scrollbar behaviour would probably be a bad idea.

**Comment by turtleli** [comment] 2015-12-02 20:46
Closing since making it work fully is a bad idea.

Page up/down, clicking and holding on the scrollbar (the non tracking bits, whatever they're called), and/or using the functions are probably the best ways to navigate the disassembly.

**Closed by turtleli** 2015-12-02 20:46 UTC
Labels: Bug, Core, GUI/WX

**Comment by ramapcsx2** [comment] 2015-12-03 12:10
Yes, the scrollbar wasn't intended to be usable. It's there to allow some other gui interaction.
