### ISSUE TITLE
GTA Stories - broken Radar and Subtitles Alpha layers

### ISSUE THREAD

**Issue by Mega1500** [PCSX2/pcsx2#1138] opened 2016-01-21 23:55 UTC
Hey so, I posted about this on the subreddit and I was told by karasuhebi to file an issue here.
Basically, when you play GTA Liberty City Stories and Vice City Stories using hardware renderer (OpenGL, DX9 and 11) the alpha layer of the subtitles and radar display incorrectly. However, when using software renderer (again, any of them) they display correctly. 

Here's images to showcase the problem (using DX11, but it also happens on others).

Grand Theft Auto Liberty City Stories:
Hardware Renderer: http://i.imgur.com/vcFKqxa.jpg http://i.imgur.com/fLVqHhd.jpg
Software Renderer: http://i.imgur.com/Ohozita.jpg http://i.imgur.com/1o2wcyt.jpg

Grand Theft Auto Vice City Stories:
Hardware Renderer: http://i.imgur.com/nwpQn5s.jpg http://i.imgur.com/54D1d47.jpg
Software Renderer: http://i.imgur.com/jNRsZer.jpg http://i.imgur.com/ghpr5GN.jpg

**Comment by karasuhebi** [comment] 2016-01-22 00:44
Thanks for the report! Do you know how far back this has been going on? I believe you mentioned in [the thread](https://www.reddit.com/r/PCSX2/comments/41mr1v/gta_stories_games_hudsubtitles_alpha_issue/) that it's been around for years? You can check by downloading old versions here:
http://pcsx2.net/download/releases/archive-download.html

**Comment by Mega1500** [comment] 2016-01-22 01:31
From what I remember, it happened when I tried the game a looong time ago. Only thing I can say for sure is that in 2014 this already happened, that was when I played through the whole LCS using PCSX2. I'll try to download some old versions to see if it did not happen at some point.

**Comment by gregory38** [comment] 2016-01-22 06:52
generate me a gs dump. And did you check the `preload` hack?

**Comment by Blackbird88** [comment] 2016-01-22 10:56
Dupe of #378 :P

**Comment by refractionpcsx2** [comment] 2016-01-22 11:54
Please continue the issue there.

**Closed by refractionpcsx2** 2016-01-22 11:54 UTC
