### ISSUE TITLE
Unable to get multiple controllers working correctly

### ISSUE THREAD

**Issue by Sarteck** [PCSX2/pcsx2#1139] opened 2016-01-22 12:16 UTC
On Ubuntu 14.04, I am having an issue getting multiple controllers working at the same time.

I have two gamepads; a generic $10 USB Playstation controller and a friend's old XBox360 (wired) controller.

After installing xboxdrv, I am able to configure both controllers without issue.  (See screenshots.)  However, only Pad 1 seems to be recognized by my games.

I have tried both controllers for Pad1, and I have tried both controllers AND my keyboard for Pad2, but only Pad1 ever seems to work.

![pad1](https://cloud.githubusercontent.com/assets/2689481/12510380/7f710044-c0d7-11e5-82a9-56b926ba3f1d.png)
![pad2](https://cloud.githubusercontent.com/assets/2689481/12510378/7f70b3d2-c0d7-11e5-9bac-3987c1d5dff3.png)
![pad-available](https://cloud.githubusercontent.com/assets/2689481/12510379/7f70b56c-c0d7-11e5-996e-09f61f95d52c.png)

You will note that the XBox controller says it's wireless; I'm not really sure what that's all about.

**Comment by Sarteck** [comment] 2016-01-22 12:20
Um, to clarify, the problem is that input from Pad2 is not recognized while the game is running.

**Comment by gregory38** [comment] 2016-01-22 12:32
Which version?

Could you post the content of onepad.ini file (likely in $HOME/.config/PCSX2/inis)

Potentially some updates broke the code...

**Comment by Sarteck** [comment] 2016-01-22 13:12
Sure, but it's probably more likely something I'm doing wrong, probably, hah.

Version is 1.4.0.

OnePAD.ini:

$ cat .config/PCSX2/inis_1.4.0/OnePAD.ini 
log = 0
options = 0
mouse_sensibility = 500
joy_pad_map = 65280
ff_intensity = 32767
[0][0] = 0x10006
[0][1] = 0x10007
[0][2] = 0x10004
[0][3] = 0x10005
[0][4] = 0x10000
[0][5] = 0x10001
[0][6] = 0x10002
[0][7] = 0x10003
[0][8] = 0x10008
[0][9] = 0x1000a
[0][10] = 0x1000b
[0][11] = 0x10009
[0][12] = 0x30100
[0][13] = 0x30200
[0][14] = 0x30400
[0][15] = 0x30800
[0][16] = 0x20101
[0][17] = 0x20000
[0][18] = 0x20001
[0][19] = 0x20100
[0][20] = 0x20103
[0][21] = 0x20002
[0][22] = 0x20003
[0][23] = 0x20102
[1][0] = 0x0
[1][1] = 0x0
[1][2] = 0x0
[1][3] = 0x0
[1][4] = 0x0
[1][5] = 0x0
[1][6] = 0x0
[1][7] = 0x0
[1][8] = 0x0
[1][9] = 0x0
[1][10] = 0x0
[1][11] = 0x0
[1][12] = 0x0
[1][13] = 0x0
[1][14] = 0x0
[1][15] = 0x0
[1][16] = 0x0
[1][17] = 0x0
[1][18] = 0x0
[1][19] = 0x0
[1][20] = 0x0
[1][21] = 0x0
[1][22] = 0x0
[1][23] = 0x0
PAD 0:KEYSYM 0x3b = 1
PAD 0:KEYSYM 0x61 = 0
PAD 0:KEYSYM 0x64 = 14
PAD 0:KEYSYM 0x65 = 12
PAD 0:KEYSYM 0x66 = 13
PAD 0:KEYSYM 0x69 = 4
PAD 0:KEYSYM 0x6a = 7
PAD 0:KEYSYM 0x6b = 6
PAD 0:KEYSYM 0x6c = 5
PAD 0:KEYSYM 0x6e = 11
PAD 0:KEYSYM 0x70 = 3
PAD 0:KEYSYM 0x73 = 15
PAD 0:KEYSYM 0x76 = 8
PAD 0:KEYSYM 0x77 = 2
PAD 1:KEYSYM 0x20 = 11
PAD 1:KEYSYM 0xff51 = 15
PAD 1:KEYSYM 0xff52 = 12
PAD 1:KEYSYM 0xff53 = 13
PAD 1:KEYSYM 0xff54 = 14
PAD 1:KEYSYM 0xffb2 = 6
PAD 1:KEYSYM 0xffb4 = 7
PAD 1:KEYSYM 0xffb6 = 5
PAD 1:KEYSYM 0xffb8 = 4

**Comment by gregory38** [comment] 2016-01-22 13:18
Hum yes code is completely broken. As you can see all lines that start with `[1]` (the 2nd pad) are null. :cry:

**Comment by Sarteck** [comment] 2016-01-22 13:53
WOuld you suggest trying an earlier version?

**Comment by gregory38** [comment] 2016-01-22 14:22
Unfortunately due to dependency you can't use older version. There is a pending PR to rewrite completely the onepad gui. It will be merged soon. 

What you can do is 
* Configure the pad1 like it was the pad2. 
* Copy the onepad.ini as onepad_pad2.ini
* Configure everything correctly the pad1 as pad1 and pad2 as pad2
* Edit manually the ini file and copy the `[0]....` line from the onepad_pad2.ini to onepad.ini. You need to rename them to `[1]...` line.
* Then put the file in read only `chmod -w OnePAD.ini ` You can restore write access with `chmod +w OnePAD.ini `

**Comment by outlier314** [comment] 2016-02-06 22:42
Facing a similar issue here.  Also running ubuntu 14.04 though I have two identical controllers.  The input on pad1 controls both players and the second controller is ignored.

Is this something that can be fixed by manually editing the onepad config file?

**Comment by willkuer** [comment] 2016-02-07 00:23
The manual fix is described in the post directly before yours.

I guess the mentioned pr will be merged soon. However if you are searching for a fast solution try as it was written.

**Comment by outlier314** [comment] 2016-02-07 19:06
Well, I did try that.  Also tried configuring each controller individually, swapping them around, etc.  In each case I get the same results in the .ini file (and the same in-game behavior).

I guess I don't know what the config file needs to look like when I'm done.  Sarteck's file posted above apparently had a lot of null values for the second controller (now editted?), but I'm not getting that.

For reference here is my current OnePad.ini in case somebody can spot a problem with it.

log = 0
options = 0
mouse_sensibility = 500
joy_pad_map = 0
ff_intensity = 32767
[0][0] = 0x20302
[0][1] = 0x20305
[0][2] = 0x10004
[0][3] = 0x10005
[0][4] = 0x10003
[0][5] = 0x10001
[0][6] = 0x10000
[0][7] = 0x10002
[0][8] = 0x10006
[0][9] = 0x0
[0][10] = 0x0
[0][11] = 0x10007
[0][12] = 0x30100
[0][13] = 0x30200
[0][14] = 0x30400
[0][15] = 0x30800
[0][16] = 0x20101
[0][17] = 0x20000
[0][18] = 0x20001
[0][19] = 0x20100
[0][20] = 0x20104
[0][21] = 0x20003
[0][22] = 0x20004
[0][23] = 0x20103
[1][0] = 0x20302
[1][1] = 0x20305                                                                                                    
[1][2] = 0x10004                                                                                                    
[1][3] = 0x10005                                                                                                    
[1][4] = 0x10003                                                                                                    
[1][5] = 0x10001                                                                                                    
[1][6] = 0x10000                                                                                                    
[1][7] = 0x10002                                                                                                    
[1][8] = 0x10006                                                                                                    
[1][9] = 0x0                                                                                                        
[1][10] = 0x0                                                                                                       
[1][11] = 0x10007                                                                                                   
[1][12] = 0x30100                                                                                                   
[1][13] = 0x30200                                                                                                   
[1][14] = 0x30400                                                                                                   
[1][15] = 0x30800                                                                                                   
[1][16] = 0x20101                                                                                                   
[1][17] = 0x20000                                                                                                   
[1][18] = 0x20001                                                                                                   
[1][19] = 0x20100                                                                                                   
[1][20] = 0x20104                                                                                                   
[1][21] = 0x20003                                                                                                   
[1][22] = 0x20004                                                                                                   
[1][23] = 0x20103

**Comment by willkuer** [comment] 2016-02-07 19:16
Are the additional linebreaks as well in the ini file? Possibly ini read requires strict ordering of input and that is your issue.  Please try to remove the linebreaks and keep the same order for the second controller as for the first.

However i can not check how everythibg works and how it is supposed to be.

**Comment by outlier314** [comment] 2016-02-07 21:54
Ugh, no extra lines are not in the original.  Redid the configuration paying attention to button ordering and got the same result still.  Here is the revised file:

log = 0
options = 0
mouse_sensibility = 500
joy_pad_map = 0
ff_intensity = 32767
[0][0] = 0x20302
[0][1] = 0x20305
[0][2] = 0x10004
[0][3] = 0x10005
[0][4] = 0x10003
[0][5] = 0x10001
[0][6] = 0x10000
[0][7] = 0x10002
[0][8] = 0x10006
[0][9] = 0x0
[0][10] = 0x0
[0][11] = 0x10007
[0][12] = 0x30100
[0][13] = 0x30200
[0][14] = 0x30400
[0][15] = 0x30800
[0][16] = 0x20101
[0][17] = 0x20000
[0][18] = 0x20001
[0][19] = 0x20100
[0][20] = 0x20104
[0][21] = 0x20003
[0][22] = 0x20004
[0][23] = 0x20103
[1][0] = 0x20302
[1][1] = 0x20305
[1][2] = 0x10004
[1][3] = 0x10005
[1][4] = 0x10003
[1][5] = 0x10001
[1][6] = 0x10000
[1][7] = 0x10002
[1][8] = 0x10006
[1][9] = 0x0
[1][10] = 0x0
[1][11] = 0x10007
[1][12] = 0x30100
[1][13] = 0x30200
[1][14] = 0x30400
[1][15] = 0x30800
[1][16] = 0x20101
[1][17] = 0x20000
[1][18] = 0x20001
[1][19] = 0x20100
[1][20] = 0x20104
[1][21] = 0x20003
[1][22] = 0x20004
[1][23] = 0x20103

**Comment by Sarteck** [comment] 2016-02-07 22:47
FWIW, I was never able to get it working, either.

I did as instructed, swapping out an alternate Pad2 config into the original, and replacing the array index "[0]" with "[1]" and then stripping it of write permission.  Even afterwards, I was unable to use a second controller.

Figured it was something to do with my own incompetence, though.  (And it probably is.)  When my friends are over, I just boot into Windows for gaming, which isn't a "solution" per se, but close enough for me.

**Comment by outlier314** [comment] 2016-02-08 04:04
Ah, thanks for the update.  I'll look for another alternative then until the UI rewrite happens.

**Comment by gregory38** [comment] 2016-04-26 16:52
Sorry for the delay, I was busy
The issue is likely related to this variable. This one set the SDL joy id to PS joy. If you have 2 joy (try 65536 or 1)
```
joy_pad_map = 0
```

As a side note, the new GUI was merged.

**Comment by outlier314** [comment] 2016-04-27 02:52
That did the trick!  Set joy_pad_map = 1 manually and now both controllers function as expected and two players can play.  Will have to try out the new GUI, but for now I'm a happy camper.

Thanks!

**Comment by gregory38** [comment] 2016-07-18 15:53
Latest git must work. If everything is ok, shall we close this issue?

**Comment by Shoegzer** [comment] 2016-12-30 21:11
I've recently discovered that when connecting two DS4 pads via bluetooth, and configuring them through OnePAD, the OnePAD.ini file will show both configuration sets but uses the line: joy_pad_map = 65280 (65280 is 0xFF00).  Because of this, the second DS4 pad is not recognized.  Only when I assign joy_pad_map = 1 by manually editing the OnePAD.ini file will OnePAD recognize the second DS4 pad.

**Closed** 2017-01-07 15:39 UTC
Labels: OS: Linux, Plugin: OnePad
