### ISSUE TITLE
[BUG]: --nogui launch command is broken in newer builds of pcsx2 wxWidgets

### ISSUE THREAD

**Issue by Gagert** [PCSX2/pcsx2#6380] opened 2022-06-09 00:11 UTC
### Describe the Bug

It seems that the --nogui option is broken with the newer releases of pcsx2 wxWidgets releases. I tried the nightly build "pcsx2-v1.7.2804-windows-64bit-AVX2-wxWidgets" and the newer "pcsx2-v1.7.2916-windows-64bit-AVX2-wxWidgets". Neither build can launch a ps2 game with the --nogui launch command.

It seems however that the --nogui launch command works in the few months older nightly build "pcsx2-v1.7.2355-windows-64bit-SSE4", I haven't tested the versions between this build and the newer ones to find the build that broke --nogui.

### Reproduction Steps

Launching a game with the --nogui command line argument with the newest release of pcsx2 wxWidgets for Windows 64 bit (I'm using Windows 10 64 bit). The ps2 game doesn't start, there's only a log window that lasts for a couple of seconds before pcsx2 closes again.

### Expected Behavior

When launching a game with --nogui on the wxWidgets builds of pcsx2 (I have to use those builds when playing Guitar Hero), the selected game is supposed to start via a launcher or shortcut with no issues launching the game.

### PCSX2 Revision

pcsx2-v1.7.2916-windows-64bit-AVX2-wxWidgets

### Operating System

Windows 10 (64bit)

### CPU

i7-12700KF

### GPU

GTX 1080

**Comment by larwood** [comment] 2022-06-22 10:42
I can confirm the -nogui option was working as of pcsx2-v1.7.2645-windows-64bit-AVX2.

I updated today to pcsx2-v1.7.2988-windows-64bit-AVX2-wxWidgets an encountered this issue.

**Comment by MKG4CRT** [comment] 2022-06-25 06:06
El problema descrito es el mismo en Linux, el comando --nogui no funciona en las últimas compilaciones

**Comment by FriendlyTroll** [comment] 2022-06-26 09:01
I can confirm that launching with --nogui option crashes the programm.

Running Ubuntu 20.04.3,

**Comment by lastblade** [comment] 2022-07-01 22:20
QT version doesn't work either. This is bad specially because steamlink still has that weird bug that makes the game lags if the app has two windows. The only workaround was launching pcsx2 with the nogui argument.

https://steamcommunity.com/app/353380/discussions/0/405692758710320173

**Comment by Daisouji** [comment] 2022-07-01 22:53
> QT version doesn't work either. This is bad specially because steamlink still has that weird bug that makes the game lags if the app has two windows. The only workaround was launching pcsx2 with the nogui argument.
> 
> https://steamcommunity.com/app/353380/discussions/0/405692758710320173

<img width="403" alt="Win1" src="https://user-images.githubusercontent.com/82060898/176975702-cf51ce2f-28af-4fb0-9108-a1cfb5592e6a.PNG">

These 2 settings, and just run a shortcut

**Comment by acparker18** [comment] 2022-07-26 18:13
Steam Deck/Linux user on the Flatpak nightly version 1.7.3115 chiming in here. Also seeing this issue for the past week or so, updating every day to the latest nightly build.

Default EmulationStation config launches PCSX2 with the nogui option, which crashes without obvious error, and requires a manual override of the system. This then requires a custom bash script to launch the game without that option. Performance is already limited on the Steam Deck, so launching with the gui hurts a bit in some titles, and the workaround is simple, but not obvious to novice users.

Can't find any errors in any logs as part of the launch process (ES, bash script calls some Python for logging, PCSX2 itself, nothing). I will try to provide any information or logs after more testing.

FWIW, the nogui option was still working for me until about 1 week ago from today. I attempted updates daily, so I was certainly on a similar or later build than the OP, and it was still working. Probably differences in the Linux build, may not be helpful, but I hope it is.

**Comment by stenzek** [comment] 2022-07-27 03:20
We could probably close this, unless someone is interested in working on it specifically, since wx is deprecated, and qt has a nogui mode now.

**Comment by refractionpcsx2** [comment] 2022-07-27 09:21
Since Qt now has a -nogui switch and WX is deprecated (essentaly) gonna go ahead and close this one.

**Closed by refractionpcsx2** 2022-07-27 09:21 UTC
Labels: Bug

**Comment by acparker18** [comment] 2022-07-28 00:06
@refractionpcsx2 Should I open a separate issue for the flatpak version? Still seeing this on all nightly builds.

**Comment by refractionpcsx2** [comment] 2022-07-28 00:11
We're not responsible for flatpack, but the Qt builds work fine if you use single hyphens and not double ones.

**Comment by acparker18** [comment] 2022-07-28 00:14
@refractionpcsx2 Gotcha. Thanks for the info!

**Comment by ribolovac510** [comment] 2022-08-08 13:11
This regression got introduced with #5816 where Input Recording is turned on by default. The --nogui command can be used even in latest wxWidgets builds but only if "Enable Input Recording" is turned off in Game Settings.

**Comment by refractionpcsx2** [comment] 2022-08-08 13:14
We're not fixing wxwidgets, it's basically legacy at this point.

**Comment by ribolovac510** [comment] 2022-08-08 19:42
Yup, I know. Just wanted to leave a comment for anyone still using the wx builds (e.g. for Guitar Hero games) and searching for a workaround.

**Comment by albmm74** [comment] 2022-08-17 10:58
> This regression got introduced with #5816 where Input Recording is turned on by default. The --nogui command can be used even in latest wxWidgets builds but only if "Enable Input Recording" is turned off in Game Settings.

Hello. Input recording is dissabled in my pcsx2 options and --nogui isn't still working.

> We're not fixing wxwidgets, it's basically legacy at this point.

Due I'm not able to use Qt in my Ubuntu distribution, it is possible to know what were the last nightly build where this feature was working?

Many thanks in advice.

**Comment by refractionpcsx2** [comment] 2022-08-17 10:59
Then I suggest you upgrade your ubuntu installation :)

**Comment by albmm74** [comment] 2022-08-17 12:29
> Then I suggest you upgrade your ubuntu installation :)

Thanks. Can't understand that people who despises all his previous work in favor of the most recent.
