### ISSUE TITLE
Kingdom Hearts cutscene garbage

### ISSUE THREAD

**Issue by deadair3210** [PCSX2/pcsx2#768] opened 2015-08-16 08:00 UTC
In Kingdom Hearts, no matter the setting, the normally black bars on the top and bottom of FMV's are filled with garbage remains, almost like a cache is being reused without being cleaned.
![untitled](https://cloud.githubusercontent.com/assets/1053504/9292507/f1b9aa6c-43c2-11e5-9e0b-0bc16db890d7.png)

**Comment by gregory38** [comment] 2015-08-16 10:20
GL or DX?

**Comment by refractionpcsx2** [comment] 2015-08-16 11:17
It has always done this with DX, but only in HW mode, i think it was a texture cache issue.

**Comment by gregory38** [comment] 2015-08-16 13:26
Try a dev build with gl renderer.

**Comment by refractionpcsx2** [comment] 2015-08-16 17:17
Does it to me regardless of renderer. As i say, I think it's a HW TC issue, reusing an old RT.

**Comment by gregory38** [comment] 2015-08-16 17:26
On dev build too? I vaguely remember that I add an extra target clear in dev (or maybe debug build)

**Comment by refractionpcsx2** [comment] 2015-08-16 17:31
oh you did mean that, nobbs assumed you meant the git builds :P Ill rebuild a debug build of gsdx

**Comment by deadair3210** [comment] 2015-08-16 17:34
Still does it to me on OGL HW.
Specs:
Intel Core i5 2500k @ 4.2GHz
nvidia GTX 660 3GB Superclocked
5GB DDR3
![capture](https://cloud.githubusercontent.com/assets/1053504/9294438/20b6194a-4413-11e5-9eef-59c26f59deeb.png)

**Comment by refractionpcsx2** [comment] 2015-08-16 17:35
yep still does it in a dbg build

**Comment by deadair3210** [comment] 2015-08-16 17:36
Im on pcsx2-v1.3.1-963-gc32f1df-windows-x86. Sorry, meant to post that earlier

**Comment by NormalSpeed** [comment] 2015-08-17 01:45
Well, idiots (PCSX2 devs) are known to suck at coding. They are behind an emulator in some ways that's been developed entirely by one person in less than 10 years, counting breaks ("Play!").

It says a lot about PCSX2 when a single human being is catching up to a whole team in less time.

**Comment by ssakash** [comment] 2015-08-17 03:46
@NormalSpeed

No one here is obliged to satisfy your requirements, please leave this place if you have nothing constructive to add.

from my perspective you're just a user who is dependent on other open source projects to satisfy his own personal interests  , you really have no rights to criticize the developers who have spared a portion of their busy schedule just to contribute here.

Damn,, I just wasted another 20 seconds of my life on arguing with a typical ungrateful discourtesy user.

**Comment by Nobbs66** [comment] 2015-08-17 03:47
Yeah, don't bother with the trolls.

**Comment by refractionpcsx2** [comment] 2015-08-17 08:25
Indeed, please don't respond to trolls, just report them to github, they're pretty good about that kind of thing.

**Comment by bositman** [comment] 2015-08-17 10:21
This has been around forever and it affects too many games to mention. You'll notice if you switch renderers it goes away so it's some leftover stuff.

**Comment by gregory38** [comment] 2015-08-17 12:20
Still on a debug build. Could someone test this option:
```
preload_frame_with_gs_data = 1
```

**Comment by deadair3210** [comment] 2015-08-17 18:17
How would i go about testing that?

**Comment by refractionpcsx2** [comment] 2015-08-17 18:22
It still does it with that in the gsdx.ini, if that's what you needed to know

**Comment by gregory38** [comment] 2015-08-18 12:27
ok it was to be sure that it wasn't an already fixed issue. It is likely related to texture cache. It could be a target that it isn't cleared or cleared by the GS with a special trick.

**Comment by refractionpcsx2** [comment] 2015-08-18 12:31
It's possible.  I can't remember if KH1 does it, but in KH2 they clear a bunch of VU memory by sending fake packets to it which just end up zeroing it out, instead of doing a reset or anything.  Wonder if they are doing similar freaky tricks with the GS.

Pretty sure the SW Renderer is fine though.

**Comment by deadair3210** [comment] 2015-08-19 22:01
So just stick with the software renderer? wont that make the game run slower?

**Comment by refractionpcsx2** [comment] 2015-08-19 22:05
@deadair3210 this only happens in FMV's, we have a gamefix to automatically switch renderers when an FMV starts or finishes. FMV's are generally quick in software mode as there is little processing required (except possibly in FFX-2 which does point sampled video)

**Comment by karasuhebi** [comment] 2015-08-19 22:06
There's a gamefix that makes it so that the game switches to a software renderer during FMVs. Just use that. The game itself should work fine.

And yes, software renderers can be more demanding than hardware renderers because all the work is being done by the CPU without any help from the GPU.

**Comment by refractionpcsx2** [comment] 2015-08-19 22:08
Ninja'd :P

**Comment by deadair3210** [comment] 2015-08-19 22:09
Ok, thanks. Didnt figure cutscenes would stress the renderer that much, but wanted to make sure.
I have another issue related to the same game, I suppose i need to make another issue, right?

**Comment by refractionpcsx2** [comment] 2015-08-19 22:11
correct, but it's best to discuss it on the forum first, once we have ruled out that it isn't an errornous setting we can create an issue for it :)

I know other people do anyway, but it would be good to keep it as clean of support issues as possible, i  hope you understand.

**Comment by deadair3210** [comment] 2015-08-19 22:12
Ok. Was actually unaware of an official forum existing actually. Should probably pay more attention

**Comment by refractionpcsx2** [comment] 2015-08-19 22:13
No problems, you can find it at http://forums.pcsx2.net   naturally the official site is pcsx2.net, if you didn't guess xD

**Comment by deadair3210** [comment] 2015-08-19 22:14
Thanks. Under which section should i make a post?

**Comment by refractionpcsx2** [comment] 2015-08-19 22:15
General Discussion and Support please :)

**Comment by deadair3210** [comment] 2015-08-19 22:16
ok, thanks

**Comment by chane2k1** [comment] 2015-10-09 20:41
FMV software switch does not work with Kingdom Hearts unfortunately, It works on many other games, but not this one. I reported this in the forums back in August, with a video to demonstrate http://forums.pcsx2.net/Thread-GSdx?pid=477782#pid477782

**Comment by deadair3210** [comment] 2015-10-13 03:21
I noticed that as well

**Comment by gregory38** [comment] 2016-03-12 10:41
A potential explanation of the bug could be found in #1222

**Comment by gregory38** [comment] 2016-03-12 12:30
Ok Boys. I need a long gsdump to confirm my potential explanation. And potentially fix it.

The dump must start before the video start. And of course, end after the start of the fmv.

**Comment by chane2k1** [comment] 2016-03-12 16:03
Just woke up, here's the GS dump for the Kingdom Hearts 1 fmv garbage, https://drive.google.com/file/d/0B-XoRQUIxD4tS1hla0FnM0JuTHc/view?usp=sharing

**Comment by gregory38** [comment] 2016-03-12 17:26
Here a short explanation of what happen.
* The game will draw a black screen on the RT located at 0x1800.
* The EE will upload the FMV at the same location but only the center not the top/bottom band.
* Due to the write GSdx will trash the RT.
* And will recreate a new source texture

The "bug" is that GSdx doesn't copy back the content from the RT to the GS mem. So it can be merged when the new texture is uploaded. Or we need to upload the new texture into the RT.

**Comment by gregory38** [comment] 2016-03-18 08:32
@bositman 
```
This has been around forever and it affects too many games to mention. You'll notice if you switch renderers it goes away so it's some leftover stuff.
```
That many?

If my understanding of the issue is right, I will need to intercept the GS clean draw call. And then reports it manually (SW) in the GS mem. However I don't know what will be the impact on the perf.

**Comment by Nobbs66** [comment] 2016-03-20 15:59
@gregory38 is the issue supposed to be fixed in the latest build on the buildbot?

**Comment by gregory38** [comment] 2016-03-20 16:15
Not yet merged but soon. You can check appveyor in a couple of hours to have a build

**Comment by Nobbs66** [comment] 2016-03-20 16:27
Ahh, ok. I'd imagine the fix is OGL only?

**Comment by gregory38** [comment] 2016-03-20 17:16
Actually, I'm afraid that I might also fixed DX9/DX11 too.

**Comment by refractionpcsx2** [comment] 2016-03-20 17:19
You have, your fears are to be confirmed :P

**Comment by gregory38** [comment] 2016-03-20 17:31
https://ci.appveyor.com/project/gregory38/pcsx2/build/1.696-gsdx-black-fmv/job/dek5siyusxgyoji3/artifacts

I hope to merge the code soon.

**Closed** 2016-03-21 17:26 UTC

**Comment by gregory38** [comment] 2016-03-21 17:29
I merged the fix in the master tree.
