### ISSUE TITLE
[BUG]: Graphical issues with textures missing in Dark Cloud Using Vulkan Render

### ISSUE THREAD

**Issue by Zyute1991** [PCSX2/pcsx2#5323] opened 2022-01-12 06:12 UTC
### Describe the Bug

While starting a new game file in Dark cloud after intro the ground and wall textures are missing or messed up. Ground shows up as blue in color and wall has a strange look to it.

### Reproduction Steps

Enabling Vulkan once intro has ended the character is placed in the first village and the ground along with the wall textures are corrupted.

### Expected Behavior

Opengl doesn't have these issues and renders the textures fine. I would expect vulkan to do the same.

### PCSX2 Revision

v1.7.2225

### Operating System

Windows 10 (64bit)

### CPU

i9-10850k

### GPU

RTX 3080

### GS Settings

![20220112_003107 1](https://user-images.githubusercontent.com/83191605/149070107-4b0839de-eb05-4dbf-bc7f-fdec55519df6.jpg)

### Emulation Settings

![20220112_003222 1](https://user-images.githubusercontent.com/83191605/149070237-f0678863-333f-4cd9-b1e7-3e16e0d266cd.jpg)

**Comment by lightningterror** [comment] 2022-01-12 06:18
A gsdump would be nice.

**Comment by RedDevilus** [comment] 2022-01-12 06:24
From Discord:
[SnapsDarkCloud1.zip](https://github.com/PCSX2/pcsx2/files/7852179/SnapsDarkCloud1.zip)
[SnapsDarkCloud2.zip](https://github.com/PCSX2/pcsx2/files/7852180/SnapsDarkCloud2.zip)

**Comment by lightningterror** [comment] 2022-01-12 07:20
I'm unable to reproduce the issue.

**Comment by liamharper2453** [comment] 2022-01-12 08:41
> I'm unable to reproduce the issue.

Mipmapping issue I think. Try with mipmapping on full.

https://user-images.githubusercontent.com/25060863/149092922-1a5461ac-ba41-4601-a825-809758b019aa.mp4

[Dark Cloud 12012022.zip](https://github.com/PCSX2/pcsx2/files/7852965/Dark.Cloud.12012022.zip)

**Comment by coornio** [comment] 2022-01-12 11:13
Any chance for a savestate (x64)? I can't find my save, might be among those I've lost and I don't want to start playing the game from scratch just for the test :P

**Comment by coornio** [comment] 2022-01-12 11:26
I can't reproduce as seen in the video, but I can confirm that something's broken about the hills. In SW rendering, the top portion of the hills is green and gradually fades out to the more high-res grass+rock texture seen up close on the hill walls. In HW rendering however, the emulator doesn't fade the grass texture out, it outright removes it and leaves just the high-res one below to show. As a result, there's a fair bit of pop-in. I am unsure if this is actually some form of mipmapping or otherwise, or if it's even related to the issue reported. See video:

Uploading 2022-01-12 13-24-10.mp4…

**Comment by Zyute1991** [comment] 2022-01-12 18:35
The video from liamharper2453 is a better idea of what I was experiencing with the textures.

**Comment by coornio** [comment] 2022-01-16 14:54
@Zyute1991 @liamharper2453 Can you guys confirm whether you're on the latest NVIDIA drivers? IIRC anything below 497 is buggy with Vulkan.

**Comment by Zyute1991** [comment] 2022-01-16 18:28
Yes i can confirm that im using the latest drivers. My version starts as 5xx.xx

**Comment by liamharper2453** [comment] 2022-01-17 08:55
> @Zyute1991 @liamharper2453 Can you guys confirm whether you're on the latest NVIDIA drivers? IIRC anything below 497 is buggy with Vulkan.

I am on latest drivers (497)

**Comment by refractionpcsx2** [comment] 2022-01-17 08:57
> > @Zyute1991 @liamharper2453 Can you guys confirm whether you're on the latest NVIDIA drivers? IIRC anything below 497 is buggy with Vulkan.
> 
> I am on latest drivers (497)

That isn't the latest driver

**Comment by liamharper2453** [comment] 2022-01-17 09:33
> > > @Zyute1991 @liamharper2453 Can you guys confirm whether you're on the latest NVIDIA drivers? IIRC anything below 497 is buggy with Vulkan.
> > 
> > 
> > I am on latest drivers (497)
> 
> That isn't the latest driver

Same issues as described on my video on 511.23 and latest Master.

**Comment by refractionpcsx2** [comment] 2022-01-17 09:34
I presume enabling GPU Palette Conversion makes the issue go away?

**Comment by liamharper2453** [comment] 2022-01-17 09:38
> I presume enabling GPU Palette Conversion makes the issue go away?

Yeah seems to make it go away

**Comment by lightningterror** [comment] 2022-03-15 09:28
Closing in favor of #5660

**Closed by lightningterror** 2022-03-15 09:28 UTC
Labels: Bug, GS: Vulkan
