### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Ds886** [PCSX2/pcsx2#5383] opened 2022-01-23 02:07 UTC
### Description

Couple of things:
1. If you maintain the 3rd party libraries yourself you should put versioning some libraries are not versioned properly and will be as result harder to mange both from your side and from the contributor.( I see they are not maintained upstream so there isn't much traction)

2. there are some case where you have multiple of the same headers on different 3rd parties I saw it in cases like khrplatofrm.h exist in two different folders.
Their origin and version is unclear but I see it . the upstream version in case of arch maintained libglvnd and seems to differ on arch.

3. For linux -  This kind of "assisting"  dependency in case of linux distro is extremely dangerous as base libraries are a moving target and change between distros, I understand that you by default link against the system itself in some cases when possible, but this in practice lead to a code that really hard to isolate and fit to one system and could lead to very hard to debug linking bugs both from the user and the developer( cmake is prone to such issues). a better solution from linux side would be to work with the appropriate maintainers to add the packages. as well as have a more clear instructions how to build against the main distros(fedora, arch, debian, ubuntu)

4. The upstream of the libraries are obscure and hard to track - there is no upstream url, github repository or author that clearly linked with  the 3rd party lib.
 for example libsamplerate, GL, glad, jpgd(upstream it is called [jpeg-compressor](https://github.com/richgel999/jpeg-compressor))
While some are evidently unmaintained for over 5 years(which for me would suggest find a maintained solution) this does reduce visibility and understanding of the project.

5. Examined some of the 3rd party packages and some  of the packages are out of date
    a. libsamplerate 0.2.1->0.2.2
    b. khrplatrform.h I have no idea where it pulled from it exist in two places([GL](https://github.com/PCSX2/pcsx2/blob/master/3rdparty/GL/khrplatform.h), [glad](https://github.com/PCSX2/pcsx2/blob/master/3rdparty/glad/include/khrplatform.h))
    in nvidia(upstream in arch) their seems to be [different version](https://github.com/NVIDIA/libglvnd/commit/b29f99d836048d157e55fc2868b5612e2ab46ac1) It seems like the duplication is due to upstream
    c. fmt 7.13 -> 8.1.1(broke ABI compatibility but fixed a lot of memory safety issues from what it seems in the changelog)
    d. wxwidgets 3.0.2 -> 3.05(?)
    
On a personal note:
I am not sure how scalable such solution and attitude(maintaining the dev environment) would be, I got to work on projects that do it like libreoffice and from my experience it become a nightmare quite fast both from the project maintainers, contributors  and the package maintainers.
rather than help it introduces more overhead and lack of clarity as time goes on and dependencies pile on.

If  the goal is to create a persistent dev env today such issues are solved in far more scalable and repeatable manner in  containers  and defining the development environment setup as code/ repeatable powershell script to setup external libraries on the windows side resolve "build on my machine error" and help in standardize as well as chain testing. 
Not familiar with Visual C++ package management but I recall newer VS are getting more bearable with nuget at least on .net  side and it is more natural to the platform despite it's shortcoming.

On a side-note with all this help to setup the environment compilation itself was extremely hard without direct help in chat on my side due to undocumented packaging and unintuitive tagging "packaging" as  building against the host system and set  the default behavior to compile against the self managed libraries instead of the system libraries.

(sorry in advance if the issue is combined, I see the problems as interlinked and can't be tackled  in seprate)

### Reason

See above

### Examples

As for the library management
1. Update libraries with the needed  testing(most beneficial but probably costly will be libfmt from what it seems).
2. Add more visible linking to the upstream repo, version,license  and the author
3. Probably create a notification bot for new release(fmt is the most affected by it)

As for general build system:
1. Containerize  or have more well defining the build environment in concrete instructions and/or assistant scripts for supported platforms.
   a. Have a clear README how to setup  an environment, explicit prerequisites and how to compile on different supported environments such as windows, debian-based distros, RHEL based distros, Arch (Currently there is different wikis spread around which are not tied to the repo and out of date last I've tried them, ended up figuring it form checking the AUR/Arch build recipes which are not clearly connected to the project and help from the AUR  maintainer)
2. Separately an a opt-in repeatable script to fetch libs that will be localized to the affected environments that can't be updated in such manner(i.e. old linux distros or Windows) 
3. Use more natural  to the platform packaging for devenv if possible (probably nuget can be tested in the case of windows+visual studio, and more strict distro system libraries in case of linux)

**Comment by Ds886** [comment] 2022-01-23 02:22
As example for the instructions adding something like below recipe freebsd and explicit listing of the dependencies with upstream link  will help a lot(not sure about the build instruction fully as I've lost them but it should build, probably some extra flags for "package mode" needed in the current setup)

```
sudo pkg install cmake xorg p5-Alien-wxWidgets sdl2 libsamplerate gtk3 p5-Gtk3
git clone https://github.com/PCSX2/pcsx2.git
mkdir -p pcsx2/bld && cd pcsx2/bld
cmake ../
make 
```

Adding such example in a readme tied in to the repo for other distros or env will help a lot.

 if needed an automated and containerized devenv setup script can also assist in having a persistent development and building environment

**Comment by stenzek** [comment] 2022-01-23 03:09
This is silly. Using system libraries has several problems:

1. On most systems, they're out of date, and missing features we need.
2. This is the big one, using different library versions creates bugs, exponentially increases the number of environments which we have to "support", and makes investigating bugs so much harder. Especially when said bugs are caused by your system packages, modified or not.
3. It makes building a pain. PCSX2 is nice to build, especially on Windows, because you pretty much clone and build, done.
4. It makes it impossible for us to modify said libraries when needed, especially when those changes aren't accepted upstream.

For Qt, we're using our own builds, and **will not** be using system packages. Most distros don't even ship Qt6 yet.

Fact is, the majority of users are on Windows, most of the developers are on Windows, expecting us to make the Windows process worse to cater for a tiny fraction of Linux users is kinda ridiculous.

**Comment by F0bes** [comment] 2022-01-23 03:20
You had a discussion with not only me but a PCSX2 team member on discord. When I asked you about windows package availability you said
```
On windows there are similliar systems if you are using mingw for VC++ I haven't work with as much 
 I do recall they started to add saner packaging
```
1. MinGW isn't even a working platform for PCSX2
2. You can't expect us to start using something like winget (which is still on version 1.0, and more than likely doesn't have our 3rd party) to appease Linux users.

Honestly, I still don't understand your goal with this. This seems like more of an annoyance and I don't know why you've decided to bring it here. If you want to PR something then maybe I'll understand.

**Comment by tellowkrinkle** [comment] 2022-01-23 04:49
> On a side-note with all this help to setup the environment compilation itself was extremely hard without direct help in chat on my side due to undocumented packaging and unintuitive tagging "packaging" as building against the host system and set the default behavior to compile against the self managed libraries instead of the system libraries.

On Linux, we default to system libraries for pretty much everything that's commonly available as a system library, including GTK, wxWidgets, SDL2, soundtouch, libsamplerate, and libpng.  Unless your issue was with fmt or one of the even more obscure libraries we use (rapidyaml? good look finding that in your package manager), I don't think the cause of your problem was us using bundled libraries over system libraries because we don't.

If you are the person who F0bes quoted, I don't think your problem was with 3rd party libraries at all, but instead was with you doing an in-tree build which caused problems due to some duplicate filenames we have.  This should be fixed in #5385.  Also, if that is you, I find your request to add better instructions pretty funny, because you clearly didn't read any of our instructions which all say to make a `build` directory for your build.

**Comment by Ds886** [comment] 2022-01-23 10:38
@tellowkrinkle 
My issue was pretty clear:
1. It is not clear the source of the projects, versions etc. this make it that even with the current setup contibutors will have hard time to validate the dependencies.

2. Undocumented process  - I am the same person and indeed  had an issue with creating 2ndry directory at first(oversight on my part due to the hour and  last time I've asked people said it is not up to date so i didn't trust it to beginwith).
I continued privately and   needed to enable `-DPACKAGE_MODE=ON` in combination with `-DXDG_STD=TRUE` in order to actually produce viable output which are not documented with assistance.
It was confusing as the wording  is opposite of all other projects were "package" option associate either with a portable build or bundling the binaries in a portable format. 


3. Decoupled documentation - the build instructions and prerequisites libraries with version to the repo will assist immensely since right now nobody  have an idea if the instructions  are up to date  or if they will fit older version as there is no tie in explanation to know since the instructions are decoupled.(this will become an apparent issue if you will remove a library, cmake version will deprecate a feature  or change the behavior of the cmake).
On that note currently due to that there is the awkward situation that you have two separate authoritative documentation that don't really agree with each other.
 [github wiki](https://github.com/PCSX2/pcsx2/wiki/Installing-on-Linux#cmake-build-system) and [site wiki](https://wiki.pcsx2.net/PCSX2_Documentation/Compiling_on_Linux))

This step is near zero effort ,lead to easier to maintenance and a lot more streamlined with adding and auditing changes in the build process.(you basically tie in the building instructions as part of the state of the repo and don't need to manage in the wiki version change in the style of "from version X to Version Y do A this and from version Y do B")
Regardless currently as far as I could see there is no clear explanation of the build system, mostly a build recipe that maybe works.

4. platform agnostic, portability and extendability -  
The current solution is prone to edge cases.
for example I believe I resulted in a bad build where I've used the undocumented package mode and it silently completed but used the embedded libraries(i will need to verify but that was my last indication).


4a. thirdparty maintenance - Currently If you want to play with the dependencies it cannot be untied from the state of the repo and it can't be done in predictable manner, meaning the steps done to update are not audited as part of the process.
This will end up being harder with every additional dependency especially if there is inter dependency between different modules.(it is also more prone for dependency dangling)

Improving it can be done in many ways that will not harm the workflow, but will in the end require finding strategies to define the dependency in more code like and systematized manner.

I am not familiar in depth with visual c++ ecosystem nowadays but I saw solutions like vcpkg, CMake, download modules and in other projects wrapper scripts.  I believe there is many more and I am not saying any one solution is the best but it something that will assist both for the windows build and the linux portable builds in terms of play space and hackability. It can be even close to the existing solution of submodules but with more standardized library management to some degree behind the scenes.

**Comment by tellowkrinkle** [comment] 2022-01-23 11:27
If you'd like to request better documentation, please do it in a separate issue because this one is so filled with other stuff that you can't even figure out a good name for the issue

If you think suggesting we use things you've never even tried is going to make our lives easier then you should probably stop right now, the answer is "no it won't"

If you want to request things because you think they'll make *your* life easier then you should stop talking about how much these things would help us and actually say why they'd help you

**Closed** 2022-02-01 11:32 UTC
Labels: Enhancement / Feature Request, Invalid
