### ISSUE TITLE
Ace Combat Games missing cloud textures in Hardware mode.

### ISSUE THREAD

**Issue by MidnightLocke** [PCSX2/pcsx2#3205] opened 2020-01-15 15:31 UTC
***PCSX2 version***
1.5.0 (All versions and I believe all developmental builds)

***Description***
  The clouds simply don't render unless you're in software mode. In hardware mode they're nonexistent. While this isn't a major issue, it's still quite an issue that I'd love to see solved. 

![image](https://imgur.com/kR5ro0y.jpg)
![image](https://imgur.com/PFQZVOg.jpg)

***PCSX2 options:***
Default settings. Any changes don't fix this issue.

***How to reproduce the issue:***
It is reproduced by simply playing the game. No special setting.

***Last known version to work:***
Has never worked from what I know on any build. If there exists one, this will be changed. 

***PC specifications:***
Windows 10
Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (Turbo up to 4.2 I believe) 
32GB RAM
GTX 1080 Max-Q

**Comment by mirh** [comment] 2020-01-15 15:42
Duplicate of #1861
(even though this has pictures)

**Closed** 2020-04-27 22:43 UTC
Labels: Duplicate
