### ISSUE TITLE
[BUG]: [Regression] Xenosaga Episode I displays a past static image at the end of loading screens 

### ISSUE THREAD

**Issue by MetrosexualGarbodor** [PCSX2/pcsx2#6625] opened 2022-07-14 04:54 UTC
### Describe the Bug

The title screen flashes for a second after loading screens for a bit, but later it just grabs another random static image. This did not occur a couple of months ago.

![imagen](https://user-images.githubusercontent.com/79612681/178902165-27b424ca-d305-4f54-a21d-d004e87adb64.png)

### Reproduction Steps

Load into the game from save slot 2, see the title screen flash after loading. Go down and leave the room if you didn't see it the first time.

[memcards.zip](https://github.com/PCSX2/pcsx2/files/9108545/memcards.zip)

### PCSX2 Revision

v1.7.3073

### Operating System

Windows 10 (64bit)

### CPU

i7-10700k

### GPU

RTX 3070

### Logs & Dumps

[gs_20220714055028_Xenosaga - Episode I - Der Wille zur Macht_SLUS-20469.zip](https://github.com/PCSX2/pcsx2/files/9108539/gs_20220714055028_Xenosaga.-.Episode.I.-.Der.Wille.zur.Macht_SLUS-20469.zip)

**Comment by sirfredrick** [comment] 2022-08-01 00:00
I bisected this and found that it was introduced in PR #5955 
Hopefully it can get fixed soon!

**Comment by katz1717** [comment] 2022-12-04 05:06
Has there been any fix for this? I'm using QT 1.7.3671

**Comment by gm1224** [comment] 2023-01-10 22:05
Still present as of v1.7.3881

**Comment by hyperspacejelly** [comment] 2023-01-23 22:19
Just happened to me with the latest nightly (v1.7.3945). Most loading would end with a still from a previous battle or exploration sequence kind of overlayed for a second.

**Comment by MetrosexualGarbodor** [comment] 2023-02-11 13:41
It's not fixed.
![image](https://user-images.githubusercontent.com/79612681/218261037-587a9c5a-a6f0-4ac3-9ebd-48d90b2e8431.png)
![image](https://user-images.githubusercontent.com/79612681/218261130-6f45cadc-23fb-400a-bf55-5b7431059f13.png)

**Comment by refractionpcsx2** [comment] 2023-02-11 16:45
Can confirm following the repro steps, this is still a problem.

**Comment by stenzek** [comment] 2023-02-12 06:35
The underlying issue was fixed, it just still manifests on longer loading screens because the target gets evicted from the cache due to it being too old. PR to work around that coming soon, just needs regression testing..

**Closed** 2023-02-12 08:34 UTC
Labels: Bug, GS: Hardware
