### ISSUE TITLE
Removing Direct3D 9 ?

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#1793] opened 2017-01-26 14:40 UTC
Since 1.4.0 is the last version to support Windows XP I see no need for pcsx2 to continue supporting DX9 as well.

The downside to this is that older gpus before 2006/7 I believe? 
Tho if people want to run pcsx2 they should have better hardware than that to begin with.

Now I also have a question regarding this. Will dropping support for DX9 also make it that pcsx2 doesn't require the "DirectX End-User Runtimes"? That would be great addition if pcsx2 can work without it.

**Comment by ssakash** [comment] 2017-01-26 14:42
Duplicate of #1171, closing this one right now.

**Closed by ssakash** 2017-01-26 14:42 UTC
Labels: Duplicate

**Comment by lightningterror** [comment] 2017-01-26 14:44
Ups , didn't know there was a topic already xD

**Comment by mirh** [comment] 2017-01-26 15:03
Afaik D3D9 renderer's utility is kind of "fuck accuracy be fast". 

As for not needing redist, see #1253
