### ISSUE TITLE
Meta: Games that need a patch to work

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#2331] opened 2018-03-01 14:31 UTC
***Here is a meta to track games that need a patch to work.***

You will find the list in the .txt file (because it's too big for a github issue webpage).

***I hope this will help PCSX2 dev team to solve these issue more easly.***

***Note:***
I only include 1 game serial for each issue. 

[PCSX2.patches.txt](https://github.com/PCSX2/pcsx2/files/2613538/PCSX2.patches.txt)

**Comment by MrCK1** [comment] 2018-03-01 17:27
I don't think there's much point to this issue really, although a good portion of those patches are for the IPU - many of which may not be necessary anymore.

**Comment by lightningterror** [comment] 2018-03-01 19:32
There was a time that I wanted to do this but I kinda changed my mind since it's such a drag. Anyway @atomic83GitHub you can also do it, it's not difficult, since you already did GameDB PRs before :)

**Comment by FlatOutPS2** [comment] 2018-03-01 19:45
Wow, that Drakan patch is terrible. It's a GSdx hardware mode hack in the GameDB. O_o
The a.k.a should also be removed.

**Comment by atomic83GitHub** [comment] 2018-03-02 10:36
I am currently doing a PR to add/remove some hacks, I would have something to ask to all the owners of games in question, can you send me a blockdump of the game without the patch enable?

So far I tested 4 games "ONI" "Ace combat 4" "Ace combat 5" and "Ace combat 0", I can confirm that the "ONI" patch is still needed to fix a black screen when loading the main menu (if someone is interested to fix this game, I can send a Blockdump for this one). I still have to check the "Ace combat series".

**Comment by mirh** [comment] 2018-03-02 10:48
Ace combat patches are needed to fix IOP issues. 
I'm kinda sure at least some months ago they were still totally required.

**Comment by FlatOutPS2** [comment] 2018-03-02 10:57
> I am currently doing a PR to add/remove some hacks

I assumeyou mean adding the changes to your current GameDB PR that is still open, because there's no reason to make another PR for it.

>  can you send me a blockdump of the game without the patch enable?

That's completely unnecessary. We can just tell you what the state of the game is.

Tekken 4 - Currently still necessary. Will be fixed when I release my IPU PR.
WRC 3, WRC Rally Evolved - There's a PR for those too.

Syphon Filter - The Omega Strain - Fixes flashlight, still necessary.
Ace Combat series - Fixes collision detection, still necessary.
Jak X - Combat Racing - Fixes hanging, still necessary.
F1 2002 - Fixes controller detection issue, still necessary.
Disney-Pixar's The Incredibles - Fixes hang, still necessary.
Incredibles, The - Rise of the Underminer - Fixes hang, still necessary.
Spongebob Squarepants - The Movie - Fixes hang, still necessary.

Drakan - GSdx Hardware patch - This should definitely be removed.

The other COP patches should still be necesary.

The other IPU/DMA patches really need testing.

**Comment by atomic83GitHub** [comment] 2018-03-02 13:02
Thanks @FlatOutPS2, I made 2 PR because of the size of each commit (too big just for a single PR in my opinion)

**Comment by lightningterror** [comment] 2018-08-03 17:10
Can you update the issue ? A lot of patches were added since this was opened.

**Comment by atomic83GitHub** [comment] 2018-11-25 21:44
I updated the list. Don't hesitate to ping me if a game is missing.

**Comment by lightningterror** [comment] 2021-12-31 20:15
Plenty of patches were added by link.

**Closed by lightningterror** 2021-12-31 20:15 UTC
Labels: GameDB, Meta Issue
