### ISSUE TITLE
Sonic heroes, texture flickering at distance in Hardware mode

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#2118] opened 2017-11-05 18:08 UTC
***PCSX2 version:***
Last 1.5 dev

***PCSX2 options:***
All default, speedhacks disabled.

***Plugins used:***
GSD , All default

![capture](https://user-images.githubusercontent.com/26351275/32417572-d60bc66e-c25b-11e7-8262-3fab663b1196.PNG)
![capture2](https://user-images.githubusercontent.com/26351275/32417575-da2e1a08-c25b-11e7-86f4-323a2c85c1a6.PNG)

***Description of the issue:***
The game Sonic Heroes have a distant texture flickering in every Hardware mode under GSDX

***How to reproduce the issue:***
Load PCSX2, go ingame with Sonic heroes, the first level is a good exemple to see the issue.

***Not a regression***

***GSDUMP***
https://drive.google.com/file/d/0B0Ph0W1NYxIVTWlhVGh5V0U3SlE/view?usp=sharing

***PC specifications:***
AMD fx8350 Gainward GTX 780Ti Windows 10 64 Bit

***Note***
Every core hacks and Clamp/Round mode don't do anything.

**Comment by MrCK1** [comment] 2017-11-05 18:12
Can you include screenshots?

**Comment by atomic83GitHub** [comment] 2017-11-05 18:36
It's hard to describe the issue with a screenshot but you can see a little exemple (in the red circle)
![capture](https://user-images.githubusercontent.com/26351275/32417902-783c5922-c260-11e7-80a3-a0be5b50593a.PNG)

**Comment by MrCK1** [comment] 2017-11-05 18:38
Disable 8-bit textures and enable 16x Anisotropic Filtering.

**Comment by atomic83GitHub** [comment] 2017-11-05 18:40
This doesn,t help here.

**Comment by MrCK1** [comment] 2017-11-05 18:42
Did you try SW renderer? Post a screenshot from there.

**Comment by atomic83GitHub** [comment] 2017-11-05 18:47
Here is the software render, it is fine:
![capture](https://user-images.githubusercontent.com/26351275/32417986-fcd20e6a-c261-11e7-8f14-de13a9709be8.PNG)
Here is the a second small exemple with 8bit disabled and 16x Anisotropic Filtering.
![capture2](https://user-images.githubusercontent.com/26351275/32417989-17b20834-c262-11e7-984a-251f3aa90859.PNG)

**Comment by MrCK1** [comment] 2017-11-05 18:49
Can you get a little closer in SW (around the same point you captured in HW)

It could be a rounding issue in HW, but I'm not sure.

**Comment by atomic83GitHub** [comment] 2017-11-05 18:52
Here it is, sorry for the bad quality, it's due to the lower resolution:
![capture](https://user-images.githubusercontent.com/26351275/32418039-e4ca0c2c-c262-11e7-9a52-c84ef00183ee.PNG)

**Comment by lightningterror** [comment] 2017-11-05 18:53
Block dump , memcard save , save state. I'd like to try this out myself and confirm.

**Comment by MrCK1** [comment] 2017-11-05 18:54
Block dump won't be necessary, memcard and savestate are fine.

**Comment by atomic83GitHub** [comment] 2017-11-05 19:10
Here is the Blockdump, savestate and a memorycard with the save.

https://drive.google.com/file/d/0B0Ph0W1NYxIVOXByYVgyX2pMblE/view?usp=sharing

**Comment by MrCK1** [comment] 2018-01-07 04:42
@atomic83GitHub Can you try this on your PS2 and see if the issue is visible there?

**Comment by atomic83GitHub** [comment] 2018-01-07 12:23
Here is a picture taken from my phone and as you can see, it doesn't have the issue (looks like the software mode).

![20180107_132004](https://user-images.githubusercontent.com/26351275/34649347-b335eb96-f3ad-11e7-98b8-aa42a23ee5cb.jpg)

**Comment by FlatOutPS2** [comment] 2018-01-07 12:55
This issue used to affect the software renderer too, but it has been resolved between v1.0.0 and v1.2.1.

**Comment by lightningterror** [comment] 2022-12-12 05:37
Closing in favor of meta issue.

**Closed by lightningterror** 2022-12-12 05:37 UTC
Labels: GS, GS: Hardware
