### ISSUE TITLE
Ape Escape 3 poor performance

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#2607] opened 2018-09-27 00:05 UTC
***PCSX2 version:***
1.4 and recent development versions from git.

***PCSX2 options:***
Tried literally everything, nothing helps it.

***Plugins used:***
GSdx SSE4/AVX

***Description of the issue:***
Most areas of the game run slow due to high CPU usage, particularly 1 thread eating 100% of CPU while not utilizing other threads.

I can run other games fine with plenty of CPU resource left to spare. This game is abnormally slow, possibly indicating an area in PCSX2 which could use optimization or a bug fix.

There is a "cinema room" area in stage 4 that causes a particularly severe FPS drop, most likely no matter how powerful your hardware is. This is noted as a "Known issue" on the PCSX2 wiki.

***PC specifications:***
Xeon 1230v2, RX580, have used latest mesa/llvm and stable.

**Comment by mirh** [comment] 2018-09-27 19:51
OpenGL is the king renderer here. And in turn amd is the king supporting opengl (on linux). 
What distro are you using? And could you try to start pcsx2 with `mesa_glthread=true`?

**Comment by z0z0z** [comment] 2018-09-27 20:56
No difference. I can play other games I've tried fine.

Like I said I have very low GPU usage, it is the 100% processor usage preventing me from playing the game.

The only thing I'm not able to test is DX11/DX9 renderer, my hunch is that there is possibly a bug in the OpenGL renderer which causes high CPU usage in this game.

**I just want someone with a Windows PC to test performance in this game between DX11/DX9 and OpenGL.**

**Comment by z0z0z** [comment] 2018-09-27 21:13
https://wiki.pcsx2.net/Ape_Escape_3

It is listed in known issues:

>Games slows down when the black-and-white movie is visible in the cinema room at stage XX

I have experienced this, the FPS drop is severe in this area.

I can run the game at 60fps in certain areas on certain levels, but most areas I cannot.

I am aware my processor is not the most powerful processor on Earth, but I think this abnormally low performance due to a bug.

**Comment by RinMaru** [comment] 2018-09-28 02:37
yep ive had this issue too the cinema room its like the 4th stage in the game

**Comment by mirh** [comment] 2018-09-28 07:59
> The only thing I'm not able to test is DX11/DX9 renderer, my hunch is that there is possibly a bug in the OpenGL renderer which causes abnormally high CPU usage in this game.

Not sure why impossibility to run DX would entail opengl is bugged. 
Did you try different presets in the emulation settings?
And what about software renderer?

**Comment by z0z0z** [comment] 2018-09-28 18:40
> Not sure why impossibility to run DX would entail opengl is bugged.
I am on Linux and don't have a Windows PC. This is why I can't test DX renderers and I want someone with a Windows PC to compare performance.

Perhaps performance is just bad in this game with all renderers. I think it's abnormally bad performance that indicates a bug somewhere in PCSX2 though.

I get better performance in this game with MTVU off, despite having 8 threads on my CPU. This game seems to run up 100% CPU usage on 1 thread while not using other threads enough.

I'd really just like a developer to check out performance in this game in general and see what's going on.

**Comment by mirh** [comment] 2018-09-28 20:42
Can you try "none" renderer?

**Comment by RinMaru** [comment] 2018-09-28 22:01
none renderer is still laggy

**Comment by z0z0z** [comment] 2018-09-28 22:02
Yes, still bad performance. This is what made me believe the renderer makes no difference at all, and it's not a bug in the OpenGL pipeline.

I'm not sure if this is Linux specific, but the bad performance on this game has to be caused by a bug somewhere.

**Comment by RinMaru** [comment] 2018-09-28 22:07
the lag is eliminated completely when you pause and even when exiting the stage you get a half a second glimpse of the area with no lag

**Comment by z0z0z** [comment] 2018-09-28 22:58
I'd like to note I'm not just having problems with that one stage. It's most of the game, that area is just is specifically really bad.

I just want someone with more knowledge than me to debug what's going on.

**Comment by mirh** [comment] 2018-09-29 09:31
Editing the title now that we "discovered" graphics has nothing to do with it, wouldn't hurt. 
Try playing with clamp settings or gamefixes.

**Comment by willkuer** [comment] 2018-09-29 10:10
Oh man you have an attitude... it’s amazing.

As you said MTVU doesn’t help I assume that VU is heavily used. Please verify that by letting the game run without MTVU and check indicators of fps, EE and GS. I’d expect EE to be at 100% and GS (possibly much) less than 90%. Also your gpu should be mostly idling and changing internal resolution moderately doesn’t affect game performance at all.

When you enable MTVU your fps might change slightly, EE% will go down und VU% rise above 50% (where MTVU often starts to become useless). Again gpu is bored and changing internal resolution doesn’t change performance.

If that’s the case there is not much you can do except for checking whether superVU is better than microVU and/or change VU clamping to none to get a small speed boost with possible graphics corruption side effects.

Game performance can only be improved by a few fps via settings. If your starting point is below 50% you could stop and play this game on your real ps2 or go on with the next game from my point of view.

Some general remarks:

MTVU doesn’t work nicely because this game heavily lets EE and VU thread synchronize which means all benefits of multithreading are gone. That’s not uncommon and not easy to solve in case it is possible. This is something not only pcsx2 is struggling with.

The mentioned gpu driver issues are not out of nowhere as gpu drivers can create cpu/gpu usage inefficiencies. To say that your gpu is bored and thus it’s not the driver’s fault is not reasonable.

To expect a performance improvement by a dev just looking into the game is not reasonable as well. First of all the core is not often touched nowadays and if at all only to improve accuracy to e.g. fix the last missing games for total in-game coverage. That’ll typically only make the emulator slower.

Then even if core would be touchable a lot of devs would hesitate to do it to not introduce regressions. There are no unit tests or integration tests for this project apart from manual testing (pcsx2 was just written before TDD and similar approaches went popular). So major refactorings are not within reach and small code adjustments will most likely not solve your problem.

In any case I’d highly suggest to either respect and consider the hints that were provided here by others because they have more clue what they are talking about or inform yourself better in advance by reading the blog/forum/general coding info. Just telling testers ‘I want you to test that and that’ and devs ‘I want a dev to look into sth sth’ in bold letters is not a proper way of communication.

**Comment by z0z0z** [comment] 2018-09-29 12:15
>‘I want a dev to look into sth sth’ in bold letters i
Not necessarily a developer, I wanted literally any regular user with a Windows PC to compare performance between DX11 and OpenGL renderer, or better, compare Windows and Linux performance on the same computer.

Perhaps it is a bug specific to AMD/Linux/mesa/LLVM.

Obviously a developer actually debugging this game and seeing what causes performance impacts would be great. I do not think I'm entitled to any open-source developer's time.

If you have sensed a defensive or entitled attitude from me, I believe it is because I preemptively do not want to be accused of just having a poorly performing system due to misconfiguration or PEBKAC.

I believe the bad performance in this specific game is abnormal and due to a software bug, likely in an area of PCSX2 which could use optimization or a fix.

That is why I made this. I want PCSX2 to be better for everyone. I was not aware no one even touched the core in years and no one is around the can.

**Comment by RinMaru** [comment] 2018-09-29 14:35
Im on windows and can confirm its not exclusive to Linux

**Comment by z0z0z** [comment] 2018-12-19 03:57
https://www.youtube.com/watch?v=qJY5JiCC5cw

A video from 2011 with a relatively weak processor running this at 60FPS with EE at 50-90%, in this same area I have EE at 100% with 40-55FPS.

Somewhere along the line, something went wrong...

Maybe I should try an ancient build of PCSX2 from 2011 or 2012? It probably won't even compile.

**Comment by z0z0z** [comment] 2018-12-19 23:04
Confirmed regression, I can run this game full speed through Wine on Linux using a build from 2011.

**Even modern Windows builds of PCSX2 run better through Wine than native Linux**

All tests with null renderer.

**PCSX2 0.9.8 (~2011) through Wine**
- Main menu
- 60 FPS : 80-85% EE

**PCSX2 git or 1.4 Linux**
- Main menu
- 45-50 FPS : 100% EE

**PCSX2 git through Wine**
- Main menu
- 60 FPS : 80-90% EE

**Comment by refractionpcsx2** [comment] 2018-12-19 23:10
To me the only difference is using Wine is quicker.  The 2011 build and latest git through Wine looks the same to me.

**Comment by z0z0z** [comment] 2018-12-20 01:18
> To me the only difference is using Wine is quicker. The 2011 build and latest git through Wine looks the same to me.

Pretty much the same, I seem to get mildly less EE usage with 0.9.8 but it's negligible.

The real problem is Windows Vs. Linux here.

**Comment by mirh** [comment] 2018-12-20 12:31
What ref said. 
Also, I'm wondering if this isn't related to #2648

**Comment by gregory38** [comment] 2018-12-20 12:38
No. Issue is mesa which isn't multi-threaded well. I sent some patches year ago. It was not merged. And I didn't have time to bother people to merge them.

So instead wine take care of multi-threading

**Comment by gregory38** [comment] 2018-12-20 12:41
Or it is due to the different threading model. But Mesa should be fixed first

**Comment by mirh** [comment] 2018-12-25 17:40
Could [this](https://bugs.freedesktop.org/show_bug.cgi?id=108263) also help?

**Comment by Mrlinkwii** [comment] 2021-12-09 19:32
is this still an issue ?

**Comment by HeroponRikiBestest** [comment] 2021-12-09 20:20
I could check, but does anyone know where this theater is? "Level 4" isn't helpful, the game doesnt number its stages, and what seems to be level 4, Saru-mon's castle, doesn't appear to have a theater.

**Comment by z0z0z** [comment] 2021-12-15 19:53
@HeroponRikiBestest 
> I could check, but does anyone know where this theater is? "Level 4" isn't helpful, the game doesnt number its stages, and what seems to be level 4, Saru-mon's castle, doesn't appear to have a theater.
It's actually stage 5. Called "Specter TV Studio". There's a movie theater section in it.

@Mrlinkwii 
> is this still an issue ?
I have a Ryzen 3600 now and it runs it much better than on my old CPU, but even that isn't enough to not have slowdowns in the movie theater of stage 5 . Something it does there is just extremely demanding with PCSX2.

Maybe if I had a 12900K/Ryzen 5800 it would run that section fine. A 3600 runs the rest of the game fine.

For the record, I absolutely don't care if you close this issue.

**Comment by TransparentBlue** [comment] 2021-12-15 21:49
iirc even just using the picture in picture function of the radar would easily halve framerate (sometimes to below 100% speed even on a 5900X), the theater issue might be similar in nature

**Comment by refractionpcsx2** [comment] 2022-06-13 23:54
Is this still a problem?

**Comment by RinMaru** [comment] 2022-06-14 00:32
> Is this still a problem?

ill check

**Comment by refractionpcsx2** [comment] 2022-06-14 00:33
If it is, can you post a screenshot of the slow area with all the metrics on screen (like EE, GS etc %'s)

and a GS Dump (under the Debug menu of the Qt builds) would be cool too.

**Comment by RinMaru** [comment] 2022-06-14 00:42
> If it is, can you post a screenshot of the slow area with all the metrics on screen (like EE, GS etc %'s)
> 
> and a GS Dump (under the Debug menu of the Qt builds) would be cool too.
![Screenshot 2022-06-13 203816](https://user-images.githubusercontent.com/15071652/173469745-e1fbc00a-1b0c-475b-82db-ef2d153dd163.png)
[snaps.zip](https://github.com/PCSX2/pcsx2/files/8895368/snaps.zip)

**Comment by refractionpcsx2** [comment] 2022-06-14 00:48
Okay well I get 200+ FPS on that, what is your GPU?

You can also increase your FPS by disabling HW readbacks, which is under Graphics->Advanced under the Game Properties.

**Comment by RinMaru** [comment] 2022-06-14 00:51
> Okay well I get 200+ FPS on that, what is your GPU?
> 
> You can also increase your FPS by disabling HW readbacks, which is under Graphics->Advanced under the Game Properties.

RX6700XT

**Comment by refractionpcsx2** [comment] 2022-06-14 00:52
Vulkan probably isn't super great on the 6700XT, not sure, DX12 might be better for you on that.  but yeah, hw readbacks

**Comment by RinMaru** [comment] 2022-06-14 00:54
compleatly breaks the video with that enabled but gets rid of the lag too

**Comment by refractionpcsx2** [comment] 2022-06-14 01:20
yeah, readbacks are painful, and not really solvable, unfortunately..

**Comment by Mrlinkwii** [comment] 2023-02-13 02:03
How has performance been recently?

**Comment by RinMaru** [comment] 2023-02-13 02:31
> How has performance been recently?

completely fixed with spin gpu readback

**Comment by GiladN1** [comment] 2023-02-13 06:44
enabling instant DMA under gamefixes provides a massive performance boost. I had a 25% performance increase when using the radar, and also during the cinema room in stage 4.

**Comment by Mrlinkwii** [comment] 2023-06-29 11:03
How has performance been recently?

**Closed** 2024-06-17 15:38 UTC
Labels: Bug, GS: Readbacks
