### ISSUE TITLE
[GSdx] San Andreas Radiosity - Upscaling offsets the radiosity pass?

### ISSUE THREAD

**Issue by Quidgebo** [PCSX2/pcsx2#2525] opened 2018-07-26 01:56 UTC
Development build v1.5.2456)
OGL HW mode
Safe preset
MTVU speed hack
"Auto Flush" HW hack enabled
Triple filter hack enabled (no change if disabled)
Accurate Data: Enabled (no change if disabled)
Blending Accuracy: High (no change if disabled)
CRC Hack Level: Partial
*Note: Using CRC hack level "Full" it fixes the offset double image yet also disables part of the effects so removes the heat haze/ripple effect seen when a sunny afternoon.

When up-scaling 2x-8x mode a very noticeable "double" or "ghost" outline left and above of the original image is present. It appears linked to the viewing angle as moves with camera angle. This was first reported on radiosity bug #600 by @FlatOutPS2 

The last comment from @aap on #600 seems to be accurate. The issue is still present even on OGL/DX11 software modes yet barely visible at native resolution, yet up-scaling seems to move and offset the radiosity pass as does using widescreen - meaning the passes for effects no longer match up. The higher the internal resolution used the greater the amount of blurred offset you get. Happens with Widescreen patches or not.

Seems a long standing issue, yet most won't see it if using the Full CRC level.
HW 8x Resolution:
![ogl hw 8x](https://user-images.githubusercontent.com/3399303/43236213-cba1f916-907b-11e8-88e4-94c9b66be8c6.png)

HW, widescreen disabled
![gsdx_20180726022717](https://user-images.githubusercontent.com/3399303/43236498-533a1f56-907d-11e8-8a4d-09456b814643.png)

OGL SW mode for comparison - slight offset double on the left street lamp for example yet mostly OK.
![ogl sw](https://user-images.githubusercontent.com/3399303/43236578-ce586e68-907d-11e8-8fab-adc6d8b03fb3.png)

GS Dump:
[gsdx_20180726022717.zip](https://github.com/PCSX2/pcsx2/files/2230110/gsdx_20180726022717.zip)

Without this bug GTA: SA would otherwise be near 'perfect' with all effects working. Even beating the PS4 emulation which suffers this same problem.

PC: Intel i5 6500, 8GB DDR4,
GPU Nvidia GTX 1050ti 4GB, Win 10 x64

**Comment by Quidgebo** [comment] 2018-07-31 08:37
TC Offset helps reduce the offset ghost, so far I've tried X 700 and Y 700 yet its not perfect - the offset seems relative to the viewing angle/camera position so not gone, but an improvement. In the below screen the bridge now has no ghost, nor the street light. Just the sides like trees and signs are obvious.

![tc offset](https://user-images.githubusercontent.com/3399303/43447304-1eafec50-94a3-11e8-9541-dbb6e62dcdc2.png)

I've been testing other settings:
• DX11 HW mode on GS 1.1.0 is just broken for GTA: SA so can't test fully.
With Auto Flush enabled, using None, Partial or Full CRC hack level it is just broken. Its looks as if the skipdraw "3" hack is enforced despite being set to 0. Luminosity, blooms etc are missing. You see a frame or two of lighting effect when starting the engine after pausing then all are removed.

![dx11-hw](https://user-images.githubusercontent.com/3399303/43447956-8deae312-94a4-11e8-8f3c-029a25e8c1b4.png)

Interestingly even in DX11 HW mode, if using Parial CRC level the heat haze effect works fine though. Just missing the lighting effects.

**Comment by lightningterror** [comment] 2018-07-31 10:08
Ye I kinda removed my comment earlier since the issue isn't completely fixed with tc offsets.

**Comment by gregory38** [comment] 2018-08-24 13:28
It is due to an half-pixel offset. However I think current hack might not detect this case (due to the way it is rendered)

**Closed** 2019-02-20 14:15 UTC
Labels: GSdx: Upscaling, Plugin: GSdx

**Comment by lightningterror** [comment] 2019-05-17 01:25
I did a quick test again and it's not an upscaling issue, the offset is there on sw renderer too. It's just that with upscaling it's easier to see because of the clearer image.

**Comment by KrossX** [comment] 2019-05-17 01:44
[SkyGFX - SA](http://gta.rockstarvision.com/skygfx/skygfx.html#SA)
It's an implementation of different RW methods and there does seem to be a small offset for the radiosity effect. There are even a few variables `radiosityFilterUCorrection` and `radiosityFilterUCorrection` which I would guess is just for that. Maybe different regions have different offsets. It would be nice to confirm with HW and different versions of the game.

**Comment by lightningterror** [comment] 2019-05-17 01:56
Yeah I see the same effect on the screenshots so it's not an issue.

**Comment by Quidgebo** [comment] 2019-05-24 09:15
@KrossX made me curious. So yes had a good experiment with GTA SA PC and SkyGFX/silentpatch etc as well as the PS4 emulated version.

Anyway - Wondered off the point... I've found 4x or 6x resolution with dev build 3128 and using both OGL HW, Large Buffer, HW hacks for Alpha Flush and TC offsets (500, 500) the impact of the native post processing is mostly countered (as removes it around the central viewing area and lessens the impact toward the edges of screen) and only minor ghosting remains equal to the native resolution/code.

The latest PCSX2 dev build improvements and the TC offset I'd say GTA SA is the most accurate yet "tweaked" way to play of them all! So playing this through the weekend :)

**Comment by HelelSingh** [comment] 2022-07-28 07:07
This issue still persists in the latest 1.7.0-3131 nightly build.

Software Mode :

![PCSX2 2022-07-28 12-12-40](https://user-images.githubusercontent.com/96559140/181441263-44572057-2c18-4ae4-ba83-85fd3606528d.png)

OpenGL HW (Native Res) :

![PCSX2 2022-07-28 12-13-14](https://user-images.githubusercontent.com/96559140/181441441-79d08c4a-bdb8-43af-8841-6a80898d3f2c.png)

OpenGL HW (8x Res) :

![PCSX2 2022-07-28 12-13-48](https://user-images.githubusercontent.com/96559140/181441545-16d92c2b-a5d7-4f98-99ec-712e4039c30d.png)

Texture Offsets (500,500) helps. But messes up HUD and Menu :

![PCSX2 2022-07-28 12-14-12](https://user-images.githubusercontent.com/96559140/181442769-97c90d70-cd5b-479b-8096-d7480cbf4405.png)

**Comment by refractionpcsx2** [comment] 2022-07-28 08:18
Of course it does? It's not something we can fix, it *is* offset on the ps2 (you can also see it on the palm tree leaves in native/software) and it gets exaggerated in upscaling because it was never intended to be upscaled, so it needs upscaling hacks, it will *never* be "Fixed".

**Comment by HelelSingh** [comment] 2022-07-28 09:22
Like, is there no chance that this could be fixed by something like **Half Pixel Offset** (currently this does nothing) in the future? As I know that hack fixes many effect alignment issues in various games.

**Comment by refractionpcsx2** [comment] 2022-07-28 09:24
Maybe? Who knows. If it does, it does, if not, well that's just the way it goes, I'm afraid.

**Comment by SwimmingInCircles** [comment] 2022-08-08 11:00
I'm having the same problem with the double outlines/ghosting. I'm running Aethersx2 on my Xbox Series X, would somebody be able to tell me the best settings to set the game to on a Series X to get rid of/minimalize the problem as it's driving me insane
