### ISSUE TITLE
[BUG]: Keyboard is not accurate to how it works on a real ps2

### ISSUE THREAD

**Issue by AmyRoxwell** [PCSX2/pcsx2#9175] opened 2023-07-05 23:13 UTC
### Describe the Bug

The keyboard doesn't register certain keys combination like it does on PS2, skipping them entirely, also, certain keys just straight up dont work (Like "[{", "]}" "\|" and even "."), PS2 allows you to use any keyboard and it will just transform the corresponding key, letter or symbol, to the position of the intended key. (So if you had a japanese game you can input Hiragana and Katakana characters with an US Keyboard and vices-versa) 
(Video with proof about the issue with the proper ps2 behavior also on it: https://www.youtube.com/watch?v=RLO5IkGEIS0)

### Reproduction Steps

1. Go to PCSX2 controller settings.
2. Go to USB Port 1 and enable HID Keyboard.
3.  Boot any game that allows you to use the keyboard (In my test I used Monster Hunter 1 Japanese).
4. Try to use shift + any number or shift + any symbol.

### Expected Behavior

Game should be able to input combinations with shift (Like Shift + 1) and be able to switch from lowercase to uppercase by pressing shift + caps lock, not matter if you use an US, EU or Japanese Keyboard.

### PCSX2 Revision

1.7.4683

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

EndeavourOS (Arch Linux based distro)

### CPU

Ryzen 5 5600

### GPU

Rx 6600

### Emulation Settings

![Screenshot from 2023-07-05 17-51-12](https://github.com/PCSX2/pcsx2/assets/89411895/e1aa400b-2530-4e8f-a4bd-40c4c17dabc4)

**Comment by F0bes** [comment] 2023-07-05 23:25
Duplicate of #7605

**Closed by F0bes** 2023-07-05 23:25 UTC
Labels: Bug
