### ISSUE TITLE
[BUG]: Cannot build PCSX2 from source with rapidyaml 0.5.0

### ISSUE THREAD

**Issue by mrkenhoo** [PCSX2/pcsx2#8427] opened 2023-03-18 15:39 UTC
### Describe the Bug

The build fails at the file `pcsx2/GameDatabase.cpp` with the error below:

`no viable conversion from 'c4::yml::ConstNodeRef' to 'const ryml::NodeRef'`

### Reproduction Steps

Install the AUR package `pcsx2-git` the usual with an AUR helper.

### PCSX2 Revision

v1.7.4243.r0.g8b7838883

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

**Comment by weirdbeardgame** [comment] 2023-03-18 15:41
No wait, this happens outside the AUR. It's a general issue with linux right now

**Comment by Mrlinkwii** [comment] 2023-03-18 15:42
duplicate of #8418

**Comment by weirdbeardgame** [comment] 2023-03-18 15:43
Also - https://discord.com/channels/309643527816609793/923492653788692480/1086602692295667722

**Comment by kamfretoz** [comment] 2023-03-18 15:53
I've put more details on #8418

**Comment by kamfretoz** [comment] 2023-03-18 22:25
can be closed once #8430 has been merged.

**Closed** 2023-03-18 22:28 UTC
Labels: Bug

**Comment by TellowKrinkle** [comment] 2023-03-18 22:31
BTW for the future, you can always force the bundled ryml by adding `-DUSE_SYSTEM_RYML=OFF`
