### ISSUE TITLE
[Question]Vulkan support?

### ISSUE THREAD

**Issue by Sunderland93** [PCSX2/pcsx2#1203] opened 2016-02-24 03:12 UTC
have any plans to support Vulkan in GSDx?

**Comment by Yui12** [comment] 2016-02-24 05:48
http://forums.pcsx2.net/Thread-So-Dolphin-has-implemented-DX12-support

**Comment by gregory38** [comment] 2016-02-24 10:47
The plan is to discuss it when driver/tools/GPU market is ready. Then we need to find game that are CPU limited by the driver.

**Comment by rz5** [comment] 2016-02-27 23:16
Potential test games could be Gran Turismo 4 and Zone of the Enders: The 2nd Runner, perhaps?

**Comment by gregory38** [comment] 2016-02-28 12:17
I have a dump for ZoE2 (anubis). Maybe you can generate me a long gs dump for gt4. However I know crc disable lots of draw calls for this game.

**Comment by ADormant** [comment] 2016-03-01 18:11
https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#introduction
https://www.khronos.org/registry/vulkan/specs/1.0/apispec.html
https://github.com/KhronosGroup
https://www.khronos.org/news/press/khronos-releases-vulkan-1-0-specification
https://www.khronos.org/registry/vulkan/
https://github.com/SaschaWillems/Vulkan
https://github.com/vlj/rpcs3/tree/vulkan
https://github.com/benvanik/xenia/commit/77a321135ed1b3761aac2834a74d89020c91626c
https://developer.nvidia.com/vulkan-android#samples
https://developer.nvidia.com/opengl-vulkan

http://developer.download.nvidia.com/assets/gameworks/downloads/secure/Vulkan_Beta_Drivers/GL_NV_draw_vulkan_image.txt?autho=1455930702_6e20c053df9f561ee2dfe9118e4d0421&file=GL_NV_draw_vulkan_image.txt

http://developer.download.nvidia.com/assets/gameworks/downloads/secure/Vulkan_Beta_Drivers/VK_NV_glsl_shader.txt?autho=1455930728_9ec8a4f1844d5e3e7d7600905fbd07cb&file=VK_NV_glsl_shader.txt

https://github.com/nvpro-samples
https://github.com/McNopper/Vulkan
https://github.com/nvpro-pipeline/vkcpp
https://github.com/john-chapman/VulkanTest
https://github.com/mlaveaux/VulkanRenderer
https://github.com/pld-linux/vulkan-loader
https://github.com/FaultyRAM/vulkan-sys
https://github.com/kainino0x/rust-vulkan
https://github.com/LunarG/VulkanSamples
https://github.com/KhronosGroup/Khronosdotorg/blob/master/api/vulkan/resources.md
https://github.com/tomaka/vulkano

**Comment by willkuer** [comment] 2016-03-02 10:37
Why do you always cite the internet? I guess the dev's know already that fancy new invention called 'google'. Also a collection of links without context are not attractive. If you want to summarize the history of vulcan implementation maybe you rather write something like a small blog entry emphasing the opportunities and differences in implementation.

**Comment by jcdenton2k** [comment] 2016-04-17 22:15
@willkuer 
The devs may not desire to start building on Vulkan until the tools and technology are past the alpha/beta phase and are properly mature.  It mitigates potential random bugs/issues attributed to the Vulkan support rather than the actual PCSX2 program.
If you desire a blog post, there are plenty of people who have already posted about it.

**Comment by willkuer** [comment] 2016-04-18 06:45
My post was an answer to a post that was deleted afterwards. I think one can see that my post is clearly not addressing gregory's request for a gs dump. The deleted post was a collection of something like 10-20 random links of projects implementing some vulkan features. It was like the best 20 entries of a google search regarding vulkan und thus imo completely unhelpful for the devs.

**Comment by gregory38** [comment] 2016-04-26 08:25
Closed as duplicate of #1047

**Closed by gregory38** 2016-04-26 08:25 UTC
Labels: Postponed, Question

**Comment by Squall-Leonhart** [comment] 2017-04-20 08:03
"The plan is to discuss it when driver/tools/GPU market is ready. Then we need to find game that are CPU limited by the driver."

sooo... Xenosaga during battle sequences with AGWS units being used?
