### ISSUE TITLE
Unreal Tournament (NTSC-U) [SLUS-20034] Game Freezes

### ISSUE THREAD

**Issue by shandawgy** [PCSX2/pcsx2#268] opened 2014-08-21 20:00 UTC
In ether hardware or software modes when u begin in game or first mission the game will freeze and hang.

My pcsx2 version is:
pcsx2-v1.2.1-511-g02b19b7

Plugins:
GSDx 20140818023333(MSVC 18.00,AVX) 0.1.16 [GSdx32-AVX]
XPad 0.2.0
SPU2-X 2014081802333 2.0.0
cdvdGigaherz (20140818023333ll) 0.9.0

My specs are:
Intel core i5-3470T CPU @ 2.90GHz
2x NVidia 560 GForce graphics card SLI
8gb Ram
Windows 8 64bit

**Comment by refractionpcsx2** [comment] 2015-08-18 14:50
Does this still happen on new GIT builds?

**Comment by yoshijin** [comment] 2016-01-11 15:35
On my setting the game boots fine and also able to play the first deathmatch. The game hangs after the match ends and there is onscreen prompt to press the "Fire" button. Hangs immediately on pressing fire button OR on its own shortly after. Have been trying latest git builds and also latest v1.4.0
Tried switching HW/SW modes on gsdx on openGL and DX11 with MTVU off. Lastly also tried messing with the VU legacy modes.

**Comment by joder666** [comment] 2016-01-11 16:27
This is a SPU-X issue. Depending on the module chosen the game will either freeze before/after a match (Xaudio) or have no music (portaudio).
DirectSound and waveout are woking OK.

**Comment by yoshijin** [comment] 2016-01-11 16:31
Okay then I'll report back after checking.

**Comment by yoshijin** [comment] 2016-01-11 20:18
Tried DirectSound and waveout modules but the game still froze. Even tried with No Audio (Emulate SPU2 only).
If it is working for you what exact spu settings you used.

**Comment by joder666** [comment] 2016-01-12 00:23
Ummm, i got v1.5.0-dev-61-ga6eb871 from orphis buildbot and the only changes i did where to renderer to opengl hardware (crcr hack level partial) and the output module of spux, nothing else.

**Comment by joder666** [comment] 2016-01-12 00:27
I only change the output module of spux after encounter the problem, everything else for spux i left untouched.
Also i used build v1.5.0-dev-61-ga6eb871 from http://buildbot.orphis.net/pcsx2/

**Comment by yoshijin** [comment] 2016-01-12 06:42
Didn't work. Still freezes after the match is over.

**Comment by yoshijin** [comment] 2016-01-12 19:41
Can you please confirm it doesn't happen with you after the end of the match and that you are able to proceed to next match.

**Comment by joder666** [comment] 2016-01-15 02:09
So this is what i found so far, my initial test i did it using a core 2 duo e8400 with build  v1.5.0-dev-61-ga6eb871. Played deathmatch till map "Turbine", no problems but the output modules xaudio and portdio will hang the game (before loading or after match) or have no sound.

I change my e8400 for a core2quad 9300 and tried again using the same build, and the game started showing this problem even with direct audio and waveout modules that where working OK.

So i hunted...

PCSX2 1.0 does not have this problem. SVN r5415 is the last build i found to not have this problem, at least it does not hang before the loading screen in all maps on death-match mode up to "Koos Galleon".

This happens with some maps not all and it varies depending on the output module selected and build. Again, some may hang before or after a match. Portaudio = no audio in any of the builds i've tried, even 1.0.

Here's the log with the hang.
https://gist.github.com/joder666/75abba04f40e5515ed95

**Comment by yoshijin** [comment] 2016-01-15 13:22
I have observed that the game hangs on the loading screen if I have MTVU turned on. I don't have an intel machine to try on. But still will try v1.0 and get back.

**Comment by refractionpcsx2** [comment] 2016-01-15 15:58
Just to rule it out, as your log stops relating to the music, have you tried the 1.0.0 spu2-x with the new version of pcsx2?

**Comment by joder666** [comment] 2016-01-15 17:34
I did no tried that since in newer builds the emu do not load the older dll, but as you said so i tried 1.0 spu2x with r5418 and r5932 (both present this problem) all seems fine.

**Comment by yoshijin** [comment] 2016-01-16 12:34
From my tests :
1)Got Sound output from all modules; no portaudio sound problem.

2)Trying to load a match (only oblivion is available at present) after the menu-screen background music stops playing results in a hang. Match loads fine if done quickly before the music stops. Reproduced on every occasion.

3)MTVU on/off has nothing to do with the problem as I later found out the above association.

4)pcsx2 v1.0 too didn't work for me.. hung after the match.

**Comment by refractionpcsx2** [comment] 2016-01-16 12:36
Are any other speed hacks being used or game fixes?

**Comment by yoshijin** [comment] 2016-01-16 12:44
Yes.. mVU Flag hack, INTC spin and Wait loop were on. And also automatic gamefixes were on.

**Comment by refractionpcsx2** [comment] 2016-01-16 13:19
ok thanks :) very odd issue.

**Comment by joder666** [comment] 2016-01-16 19:19
Umm you said the menu background music stopped for you, that may be part of the problem because it is on a loop, it never stops. If you stay on the menu screen and do nothing "demo mode"  will start.

As for 1.0 having problems for you also even wierder since i've played 12 maps on deathmatch (i am at "Ice station Zeto" currently) without this problem.

Also i forgot to mention that i haven't changed any of the default settings for any of the builds i tried but the output module.

**Comment by yoshijin** [comment] 2016-01-16 20:14
That's what I found out when tried the game on my PS2 console. The background music never stops.
Really weird behaviour. Probably that's the reason why. 
Also weird is I did not get portaudio problems which you got.

**Comment by willkuer** [comment] 2016-01-16 20:35
The WaitSema message in the end sounds a bit like a deadlock. Is spu2-x multithreaded? If yes, even in no audio mode?

Does any of you two testers have visual studio and preferably some experience in debugging?

**Comment by yoshijin** [comment] 2016-01-16 20:53
Sorry no debugging experience.

**Comment by joder666** [comment] 2016-01-17 00:35
I do have visual studio, but my coding/debugging experience is just above "Hello World".

**Comment by joder666** [comment] 2016-01-17 16:41
I do have visual studio, bug my coding/debugging experience is just above "Hello World".

**Comment by willkuer** [comment] 2016-01-17 19:50
I would suggest to:
1. build/run pcsx2 through the debugger (i think f5 in vs)
2. play till you observe the hang
3. halt the debugger (red rectangle)
4. look into threads list (somewhere in the bottom tabcontrol):
4a how many threads exist
4b where they are stalling
4c if there is an spu2-x thread check where it is (complete stacktrace)

**Comment by joder666** [comment] 2016-02-05 20:13
Check this logs please.
https://www.mediafire.com/folder/118rpy62b5ki7/Logs

I built a "release" build and ran it through the debugger. The logs contain the output of: output, threads and call stack windows.

**Comment by refractionpcsx2** [comment] 2016-02-05 22:02
Can't really see anything in those logs that would be useful.

**Comment by joder666** [comment] 2016-02-06 00:08
ummmmm..... anything else a "novice" can do to help? in this case.

**Comment by refractionpcsx2** [comment] 2016-02-06 01:08
It will either suck hard or not work, but if you can find ZeroSPU2 in one of the older PCSX2 releases and try that, at least we will know for sure it's an issue with SPU2-X

**Comment by joder666** [comment] 2016-02-06 03:14
I got zerospu2-r3878 and tried it with 0.9.8, SVN r5415 the problem is still present. Also tried the plugin with latest build, which detects the plugin, but no go same thing happen.

**Comment by yoshijin** [comment] 2016-02-10 08:51
I think it is a DMA/ADMA transfer timing problem as documented [here](http://forums.pcsx2.net/Thread-SPU2-X-v2)

**Comment by refractionpcsx2** [comment] 2016-02-10 09:37
It could be, it could also be the lack of an IRQ signal from the SPU2, or it could be watching for a memory location it never sees, could be anything.

**Comment by prafullpcsx2** [comment] 2016-11-09 12:58
My testing shows that this bug was introduced in r5418 where a delay cycle of 4 was introduced. I checked latest SPU-2x and the game seems to work fine with delay cycle value of 3 or lower through ini.

**Comment by willkuer** [comment] 2016-11-09 13:03
Maybe add spu settings to gamedbf until somebody wants to tackle such timing issues? I think ssakash had once a list of three or so games that profit from lower delay cycles as well.

**Comment by FlatOutPS2** [comment] 2016-11-09 13:27
> I think ssakash had once a list of three or so games that profit from lower delay cycles as well.

It's in the pull request: https://github.com/PCSX2/pcsx2/pull/1393

It might be a good idea to make a meta issue about this.

**Comment by atomic83GitHub** [comment] 2019-04-15 21:19
This can be close as this game is mentioned in the delay cycle meta.

**Comment by Pillowy57** [comment] 2020-11-07 09:00
XxMayhemPlayzxX94d |  on reddit said to do the following:
"Go to your Documents > PCSX2 > inis, then you click on SPU2-X.ini, and then change your DelayCycles to 1." This works I've tested it. I played a few rounds of unreal tournament and it works with no problems after I put the Delay cycles at 1. Have fun guys and I hope this helps

**Comment by refractionpcsx2** [comment] 2020-12-02 20:02
Fixed in #3959

**Closed by refractionpcsx2** 2020-12-02 20:02 UTC
Labels: Regression, SPU2

**Comment by Crsarmv7l** [comment] 2021-09-30 21:30
Freeze when starting a match is in 1.6.0

**Comment by refractionpcsx2** [comment] 2021-09-30 21:33
The game is fine now in the development builds, which is why this issue is closed.

**Comment by Crsarmv7l** [comment] 2021-10-01 02:32
I literally just tried it on the "stable" branch. It froze.

**Comment by Crsarmv7l** [comment] 2021-10-01 02:33
Where would I find a dev build?

**Comment by tadanokojin** [comment] 2021-10-01 02:33
This is not a support channel.
