### ISSUE TITLE
[BUG]: Vampire Night, bullet rendering issue.

### ISSUE THREAD

**Issue by gilderoylockhart01** [PCSX2/pcsx2#4805] opened 2021-09-22 10:42 UTC
### Describe the Bug

In the game "Vampire Night", there is an issue with the bullets displayed at the left of the screen where their textures doesn't display properly in PCSX2. I tried all the hacks/settings, nothing can solve the problem.

Note: they do display fine on Dobiestation.

### Reproduction Steps

Load the savestate provided with the dump and see the problem.

### Expected Behavior

The various bullets should display their textures fine like on real hardware.

### PCSX2 Revision

v1.7.0-dev-1789-gb8eb18836f

### Operating System

Windows 10 (64bit)

### CPU

I9 9900k

### GPU

RTX 3070

### GS Window Screenshots

The bug in action:

- PCSX2:

<img width="250" alt="Capture" src="https://user-images.githubusercontent.com/90222976/134329428-281a2f20-da95-40da-b43a-4160c6701760.PNG">

- Real hardware (taken from a youtube gameplay):

<img width="151" alt="Capture2" src="https://user-images.githubusercontent.com/90222976/134329455-9e5dde9a-fb70-4b7f-acd4-013490463c9f.PNG">

### Logs & Dumps

Blockdump + savestate : https://drive.google.com/file/d/1ZNYdwVyLRJobAwl0BfsAdq6k8oymj0Le/view?usp=sharing

**Comment by prafullpcsx2** [comment] 2021-09-22 13:19
It's an old gsdx regression but it's from the time where no gsdx builds are available to hunt down the culprit.

**Comment by prafullpcsx2** [comment] 2021-09-22 13:50
I found the builds where it was broken. Hunting is on now.

**Comment by refractionpcsx2** [comment] 2021-09-22 13:54
Just to elaborate on what I said, cos it "might" still be a CLUT issue (I mean, it looks like one lol), but the game may have preloaded it for the UI, so I can't test that with a blockdump.

**Comment by prafullpcsx2** [comment] 2021-09-22 14:02
https://github.com/PCSX2/pcsx2/commit/25072b99c70f5ea46c8eb3be1edad170388ba47e#diff-d263c5df551a66aedf4b91259dc25952c38b8d93d1ef323ffb4388803026dfaf

This is the commit that breaks it

**Comment by refractionpcsx2** [comment] 2021-09-22 14:05
Hmm can you try tellows gsoffset pr then? Probably won't fix it but you never know it's touching the same code

**Comment by gilderoylockhart01** [comment] 2021-09-22 14:53
Unfortunately the github action builds are not available anymore for that PR.

**Comment by prafullpcsx2** [comment] 2021-09-22 14:54
https://buildbot.orphis.net/pcsx2svn/index.php?m=fulllist

**Comment by gilderoylockhart01** [comment] 2021-09-22 15:35
Orphis doesn't seem to contain the build in question, it was only in action.

**Comment by prafullpcsx2** [comment] 2021-09-22 15:47
> Orphis doesn't seem to contain the build in question, it was only in action.

Sorry I didn't understand what you mean. Anyway here are both before and after plugins downloaded from the orphis link that I sent to you.
[gsdxr5018-5019.zip](https://github.com/PCSX2/pcsx2/files/7212116/gsdxr5018-5019.zip)

**Comment by refractionpcsx2** [comment] 2021-09-22 16:22
I've also added a GS Dump to our internal archive for @tadanokojin so he doesn't have to mess around with blockdumps and savestates

**Comment by tadanokojin** [comment] 2021-09-22 16:57
Okay, I see the issue.
![image](https://user-images.githubusercontent.com/26046960/134388166-c21f5c7f-e5af-4965-869d-8b249f50ad84.png)

**Comment by refractionpcsx2** [comment] 2021-09-22 17:09
> Okay, I see the issue.
> ![image](https://user-images.githubusercontent.com/26046960/134388166-c21f5c7f-e5af-4965-869d-8b249f50ad84.png)

nice!

**Closed** 2021-09-23 20:48 UTC
Labels: Bug, GS
