### ISSUE TITLE
[BUG]: DreamWorks Madagascar with bug elements

### ISSUE THREAD

**Issue by JoquiJorlas** [PCSX2/pcsx2#7866] opened 2023-01-12 17:36 UTC
### Describe the Bug

The game runs very well overall, with the exception of this bug I'm reporting, the smoke element doesn't match as it does on the original hardware, I'll attach a video for better identification.

PCSX2:

https://user-images.githubusercontent.com/117608301/212139515-474fb78b-25f6-4773-baf0-6844872f790f.mp4

https://user-images.githubusercontent.com/117608301/212139528-b2bcacc6-baaa-4722-b46f-2d527bc8bc5d.mp4

Real Hardware:

https://user-images.githubusercontent.com/117608301/212139586-ebe9b07a-dd71-4bfd-a5d8-26238126f597.mp4

https://user-images.githubusercontent.com/117608301/212139607-c7ec0d9c-c514-47cd-8f39-02f609d9aee9.mp4

### Reproduction Steps

When the character Alex (Lion) roars or when the janitor sweeps with the broom.

### Expected Behavior

A clean smoke, without the white smudge that appears.

### PCSX2 Revision

v1.7.3891

### Operating System

Windows 11

### CPU

i5-4460

### GPU

GTX 750 TI

**Comment by Mrlinkwii** [comment] 2023-01-12 17:39
gs dump/s of the issue ?

**Comment by JoquiJorlas** [comment] 2023-01-12 18:03
> gs dump/s of the issue ?

here it is

https://1drv.ms/u/s!AmMXnp__VuUGjibLz5KI7xdd_AJZ?e=sfKXW7

**Comment by refractionpcsx2** [comment] 2023-01-12 18:53
Problem seems to happen in software and hardware, making me believe it's not a GS problem.

Can you try enabling either the EE timing hack or Force GIF FIFO (or both) options under the per game Game Fixes screen? (You will need to go to Tools->Show advanced first) you can find this under the View->Game Properties menu when the game is running, or right click the game in the game list and hit properties if it is not running.

Let me know if either of them options fixes it/makes it worse

**Comment by JoquiJorlas** [comment] 2023-01-13 01:09
I did the tests in different combinations but unfortunately none of them had any effect, the problem remains exactly the same

**Comment by Goatman13** [comment] 2023-01-13 17:53
Lion roaring is fixed with VU nearest or positive rounding.

**Comment by refractionpcsx2** [comment] 2023-01-13 17:53
which VU? 1?

**Comment by refractionpcsx2** [comment] 2023-01-13 17:55
okay, it really could be a good idea to upgrade :D

**Comment by prafullpcsx2** [comment] 2023-01-13 18:27
VU1 Round mode positive or nearest fixes this. I am not sure which one of these is more reliable for this game though.

**Comment by refractionpcsx2** [comment] 2023-01-13 18:49
I tend to prefer nearest as an alternative to chop, though neither is really right, nearest is generally the least aggressive of the round modes.

**Comment by Goatman13** [comment] 2023-01-14 08:34
You can always patch VU program instead if you want to avoid nearest/positive rounding for whole VU1. It seems to be one bit wrong on `muli.xyzw vf22, vf22, I` 

```
// SLES-53225
// Add one bit in LOI 8388609.0
patch=1,EE,0034BA40,byte,01
patch=1,EE,0034BDE0,byte,01
patch=1,EE,0034C100,byte,01
patch=1,EE,0034C490,byte,01
patch=1,EE,0034C810,byte,01
```

**Comment by refractionpcsx2** [comment] 2023-01-14 12:45
That's awesome, thanks, but we have a bunch of other versions to deal with too, so we might need to still do rounding for them, unless you know enough people with the different versions.

**Comment by JoquiJorlas** [comment] 2023-01-14 18:55
> // SLES-53225
> // Add one bit in LOI 8388609.0
> patch=1,EE,0034BA40,byte,01
> patch=1,EE,0034BDE0,byte,01
> patch=1,EE,0034C100,byte,01
> patch=1,EE,0034C490,byte,01
> patch=1,EE,0034C810,byte,01

I made a cheat.pnach with this code and it really fixes the lion's roar problem, but the code causes other problems, some elements are hidden when applying this code:

**1. the smoke from the janitor's broom completely disappears:**
_with code:_

https://user-images.githubusercontent.com/117608301/212490858-6c3af1bf-fa6a-4967-8f0f-eaaee0dba9c8.mp4

_real hardware:_

https://user-images.githubusercontent.com/117608301/212490867-b5086925-51b0-4a4b-b057-ce9651129aea.mp4



**2. The dirt that appears when the zebra hits the hay disappears:**
_with code:_

https://user-images.githubusercontent.com/117608301/212490960-74110f05-7211-40dd-bef3-cf3b705cd8a3.mp4

_real hardware:_

https://user-images.githubusercontent.com/117608301/212490965-b62e6152-eb04-48d5-a3b0-28afd525c7d7.mp4

**3. The smoke from the gas flue pipe also disappears:**
_with code:_

https://user-images.githubusercontent.com/117608301/212490991-abbe946d-ba51-4442-9b8f-22c06560b425.mp4

_real hardware:_

https://user-images.githubusercontent.com/117608301/212491002-3bd9e445-c12f-4e11-8e31-b3671e67dcb3.mp4

(in this specific case, I tested the code ```// SLES-53225
// Add one bit in LOI 8388609.0
patch=1,EE,0034BA40,byte,05
patch=1,EE,0034BDE0,byte,05
patch=1,EE,0034C100,byte,05
patch=1,EE,0034C490,byte,05
patch=1,EE,0034C810,byte,05``` and it fixed 

https://user-images.githubusercontent.com/117608301/212491104-7fb4e650-d175-4a03-8d01-2e845bc0fd47.mp4


 but the other problems with this code had no effect).

I don't understand much about programming, and codes I don't know if I did everything right or if something is wrong, if the solution for this specific problem would be easy or difficult, thus being a bigger problem than it seems, maybe the implementation can be considered a temporary solution (because visually it looks better compared to the current state, despite the elements that disappear) so it's something to think about what can be done. Even so, thank you in advance for the support and the partial solution to the problem, for now I will use the code made by friend Goatman13 because it serves me well, if it is corrected in the future I will be even happier, hugs to the devs. I will be following

**Comment by refractionpcsx2** [comment] 2023-01-14 19:30
And if you use VU1 rounding set to nearest, does it still work?

**Comment by JoquiJorlas** [comment] 2023-01-15 08:38
> And if you use VU1 rounding set to nearest instead of the patch, does it still work?

Oh yes, in this case all the problems are solved, VU1 Rounding set to Nearest, and wihout the patch code. I'm sorry I didn't find this option before, I just now saw that it is in the advanced settings, but it really fixes the problem definitely:

![Captura de tela_20230115_053528](https://user-images.githubusercontent.com/117608301/212531102-c7f087af-833b-4c17-b47f-db0569bc7df9.png)

https://user-images.githubusercontent.com/117608301/212531111-eb108c77-565a-45a8-8b81-ab3a3103a7af.mp4

https://user-images.githubusercontent.com/117608301/212531117-5b712116-9969-4e70-a4cd-f0fb4e0eb547.mp4

https://user-images.githubusercontent.com/117608301/212531121-40e0e8a9-6ecd-4129-bab6-06c514e2b943.mp4

https://user-images.githubusercontent.com/117608301/212531123-74caca94-8889-4fdd-8785-c32e921d1158.mp4

**Comment by refractionpcsx2** [comment] 2023-01-15 14:34
Okay, we'll go with that then :)

**Comment by Oymat** [comment] 2023-01-15 15:56
Looking at his videos i'm not sure the trees look right. they're fading/becoming transparent. i've never played this game before but is op really sure that this is a normal ps2 behavior ?

**Comment by refractionpcsx2** [comment] 2023-01-15 15:57
It's not unusual on PS2 for pop in or fade in, it only has 4mb of video memory.

**Comment by JoquiJorlas** [comment] 2023-01-15 16:09
the problem of trees are caused by skidraw range that i change manually

**Comment by Oymat** [comment] 2023-01-15 16:15
> the problem of trees are caused by skidraw range that i change manually i think

Reset gs settings to default and see if it fixes it, if not then make sure it's not caused by the vu1 rounding.

**Comment by JoquiJorlas** [comment] 2023-01-16 01:23
I performed the test. The problem with the trees is not related to VU1 it is a natural problem of the game itself.

Default:
https://user-images.githubusercontent.com/117608301/212579593-cf63bd76-9af8-49cb-979d-598f6de0c1c8.mp4

VU1 Nearest:
https://user-images.githubusercontent.com/117608301/212579601-db749775-d5cb-473a-89c2-2eba07696b9d.mp4

The same transparency issue occurs in any configuration.

**Closed** 2023-01-17 11:15 UTC
Labels: Bug
