### ISSUE TITLE
[Feature Request] Controller hot key binding for exiting the emulator

### ISSUE THREAD

**Issue by latreides** [PCSX2/pcsx2#2364] opened 2018-04-04 12:41 UTC
The hot key to exit the emulator is only available on the keyboard.  This poses a problem for emulation setups that are hooked up to the TV.  (I have to carry a keyboard around with my emulation box, exclusively to exit from PCSX2).  Allowing users to bind a controller key to the exit hot key, or just taking the existing "Home" SDL controller binding (as many emulators tend to do), would allow PCSX2 to work better with emulator front ends hooked up to a TV.

**Comment by latreides** [comment] 2018-04-07 20:27
This is a feature/fix request for PCSX2, not for RetroArch.

**Comment by Kristijan1001** [comment] 2018-04-07 20:29
I am special dont mind me @latreides hahaha

**Comment by prog-amateur** [comment] 2018-11-01 05:36
Sorry but this is crazy to see no progress on a so much basic request. 
I have check all the world wide web without any information about it. Some people use antimicro or joy2key, but anyway, this should be an option into the emulator settings. 
Something like 'hotkey bindings'. Very simple. Please feel free to help, this is a priority. 
Thank you

**Comment by tadanokojin** [comment] 2018-11-01 05:44
@prog-amateur just use one of the applications you listed.

**Comment by bositman** [comment] 2018-11-01 11:43
This is a priority for you maybe, not for the project. If you feel so strongly about it, you are free to code it yourself. If you can't, you should wait when someone who has the skills, time and knowledge do it.

**Comment by prog-amateur** [comment] 2018-11-01 13:14
> This is a priority for you maybe, not for the project. If you feel so strongly about it, you are free to code it yourself. If you can't, you should wait when someone who has the skills, time and knowledge do it.

First of all, thank you (you and all the team members) for your contribution about this emulator. Please don't take it personal, but I think my impatient request is honest. 

I'm not a developer, but I've worked on many projects, and the most important thing when using a tool (in this case a controller since we're on a console emulation) is to at least close the program via this tool (the controller, AND the keyboard). Many use pcsx2 from retroarch, launchbox, hyperspin, arcade terminal or steam, or just a media center computer behind the TV, etc. and there is not always a keyboard to exit a game. 

I hope you understand my point of view and that of those who have been using your program for years. 

I wait for a long time. This thread is from pcsx2 official forum -> **2014** : 
https://forums.pcsx2.net/Thread-Closing-PCSX2-with-a-controller

You can easily understand that 4 pages of discussion since that date is not _my priority_ only. 
I understand you try to improve this software with cutting edges changes and bug fixes, but priority is open/close software. 

I hope this would improve the way I have published my first request. Thank you.

**Comment by vsub** [comment] 2018-11-01 16:57
Well I have a question.
How are you starting pcsx2,you must be using enternal program(launcher)otherwise you MUST have a keyboard or a mouse to run it
If you are starting it by using external program,why exactly is a problem to use another external program to do what pcsx2 can't do

For example,I can set a button on my gamepad with AutoHotKey to whatever I want(including closing pcsx2)and I can make that script to run the launcher you are using so you don't need to start two programs.
That key can also be set to do different things depending on the emulator you are currently using

**Comment by prog-amateur** [comment] 2018-11-01 18:13
> Well I have a question.
> How are you starting pcsx2,you must be using enternal program(launcher)otherwise you MUST have a keyboard or a mouse to run it
> If you are starting it by using external program,why exactly is a problem to use another external program to do what pcsx2 can't do
> 
> For example,I can set a button on my gamepad with AutoHotKey to whatever I want(including closing pcsx2)and I can make that script to run the launcher you are using so you don't need to start two programs.
> That key can also be set to do different things depending on the emulator you are currently using

Thank you for your feedback. On my side, this is how I use pscx2 : 
https://www.minimachines.net/actu/bartop-minitel-70309

I use retropie in this bartop, but I know also many people using hyperspin, launchbox, in arcade, home-made consoles with Steam-Linux, or bartops. And they all have the same issue : no button to exit while for any other emulator (even dolphin, N64, etc.), you can setup a button combo (e.g. Start + Select, etc.) for that. 

I am on Ubuntu, so AutoHotKey is not compatible. I have also tried AntiMicro but it is abandoned (I have a bug and we try to fix it with a developer, but without success). I think it is better to integrate the option directly into PCSX2 instead of a 3rd party software (because of the compatibility, dependence of the developer which can abandon at any time, and simply the ergonomics).

**Comment by tadanokojin** [comment] 2018-11-02 10:46
> I know also many people using hyperspin, launchbox, in arcade, home-made consoles with Steam-Linux, or bartops.

No need to repeat yourself.

> I am on Ubuntu, so unfortunately AutoHotKey is not compatible.

Did you try Wine?

>  I have also tried AntiMicro but it is abandoned (I have a bug and we try to fix it with a developer, but without success). 

It looks like your issue was closed as fixed https://github.com/juliagoda/antimicro/issues/28. 
I see no open issues on that project.

> I think it is better to integrate the option directly into PCSX2

I have to refer you to Bositman's advice.

> instead of a 3rd party software (because of the compatibility, dependence of the developer which can abandon at any time, and simply the ergonomics).

What do you think you're using when you use RetroPie's frontend?

**Comment by lightningterror** [comment] 2022-05-10 14:31
Duplicate of #2941

**Closed by lightningterror** 2022-05-10 14:31 UTC
Labels: Enhancement / Feature Request, GUI/Qt
