### ISSUE TITLE
[BUG]: weird glitch in Gran Turismo 4

### ISSUE THREAD

**Issue by Emi-pcsx2** [PCSX2/pcsx2#8235] opened 2023-02-24 00:59 UTC
### Describe the Bug

whenever you pass a certain point in tsukuba circuit, there is a black glitch

### Reproduction Steps

just use any car and jump on tsukuba. 

this is a link to a 2 second video showcasing the problem 

https://www.mediafire.com/file/u0vgufto2q6a45h/glitch.mp4/file

### Expected Behavior

glitch

### PCSX2 Revision

4133

### Operating System

Windows 10 (64bit)

### CPU

ryzen 5 3600

### GPU

gtx 1650 super 

### GS Settings

![image](https://user-images.githubusercontent.com/125753543/221065903-797c7bab-cd90-40e5-96de-871320d147b1.png)
![image](https://user-images.githubusercontent.com/125753543/221065945-a157d28a-0b31-49b5-9092-d304f7fc5bc8.png)

### Emulation Settings

![image](https://user-images.githubusercontent.com/125753543/221066004-e4d437e2-f7cf-4a53-ba97-a44382aafb31.png)

**Comment by RedDevilus** [comment] 2023-02-24 01:02
You can just link the videofile in github up to 50 MB and it will work in the browser as it gets autoconverted to work for future reference.

**Comment by lightningterror** [comment] 2023-02-24 02:09
Can you pause the game and take a gsdump when the issue appears? That looks like a mipmap issue Sten mentioned a couple of days ago.

**Comment by refractionpcsx2** [comment] 2023-02-24 09:57
Here's a dump, afaik it only happens in hw mode and you only see it on the first loop of the dump https://drive.google.com/file/d/1IsemSXRpmATutTOhB9XDe2o3SSjy9xyl/view?usp=share_link

**Comment by refractionpcsx2** [comment] 2023-02-27 22:02
Just messing with the dump and disabling safe features seems to stop the weird black glitch, so there might be some weird clear going on.

**Comment by SeruranBlue** [comment] 2023-03-05 16:16
same issue happen in fuji speedway 90s, in NTSC-J (SCPS-17001)

**Comment by Emi-pcsx2** [comment] 2023-07-17 22:44
So uhh

**Comment by Mrlinkwii** [comment] 2023-11-27 15:24
can this be re-checked on lastest nightly

**Comment by SeruranBlue** [comment] 2023-11-28 11:32
it seems it is fixed in NTSC-J (fuji speedway 90s)

**Comment by JordanTheToaster** [comment] 2023-12-01 15:42
Cannot reproduce on current master.

**Closed** 2023-12-01 15:44 UTC
Labels: Bug
