### ISSUE TITLE
Musashi Samurai Legend Hang/Screen Cut

### ISSUE THREAD

**Issue by Xaelath** [PCSX2/pcsx2#1274] opened 2016-04-01 13:24 UTC
Disc Issue?
- PCSX 1.4.0
- PCSX2 options Default
- Plugin used : gsdx(avx),lilipad,spu2-x,cdvdgigaherz,null
- Plugin Settings Default DX11

Description : The game hang without the help of Speedhacks, it will somehow move when speedhacks turned on, but it will still stuck after the load right after the 1st boss. The first hang will occur in Opening Animation if not skipped and speedhacks turned off

How to replicate - Start the game default use either iso/disc with speedhacks off, same problem will occur. Start Speedhacks or skip the opening and try the game till 1st boss and it will hang right after the game loads.

Last Known Version to work : Never worked even when it said Playable since theres only a few attempted and tried then explain the cause or finish at least till the first boss

PC Specifications : Intel HD 4000 (i3) 1.80ghz NVIDIA 740m 2GB 4GB Ram Win 7 Ultimate (32/64 Optimus)

Comments : Been trying for 3 years just to get pass the 1st boss, tried to search through youtube/forums mostly only have the "Flash thing" problem, TLB Miss error is mainly the cause.
The bottom part cut off didnt happen in 1.2.1

Old  : 
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/199672/emuLog.txt)
New : 
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/199749/emuLog.txt)

![untitled](https://cloud.githubusercontent.com/assets/4243587/14208026/9101a87a-f847-11e5-87b1-9f891d92f46f.jpg)

**Comment by ssakash** [comment] 2016-04-01 13:40
From observation, game seems to suffer three issues. 

* 1/ right border issues described on https://github.com/PCSX2/pcsx2/issues/1026
* 2/ TLB miss error messages.
* 3/ The PAL games is patched to use NTSC video mode which causes the bottom part to be cut off. relevant to the [following issue](http://forums.pcsx2.net/Thread-Invalid-Bug-Report-dragon-quest-VIII-PAL). **solution:** Re-rip the game from original disk without applying any patches.

@Xaelath 

I suggest you reformat your issue report following the format provided over [here](https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues).

**Comment by willkuer** [comment] 2016-04-01 13:51
> Loading savestate from slot 0...

and don't use savestates until the problem is resolved.

**Comment by ssakash** [comment] 2016-04-01 13:53
> MTVU speedhack is enabled, saved states may not be stable

Is the issue of hanging present when MTVU is disabled ?

**Comment by Xaelath** [comment] 2016-04-01 13:56
Give me a times to reformat and burn my disk to iso.
I tried to on and off mtvu btw. and it still doesnt work.

**Comment by nhydock** [comment] 2016-04-01 14:09
I reported this issue 5 years ago on google code.  It appears to be unsolvable because not even Sony's PS3 software emulator is capable of running the game without this error
https://code.google.com/archive/p/pcsx2/issues/1187

**Comment by Xaelath** [comment] 2016-04-01 14:23
Reformat.
The lighting isnt the main issue since i couldnt even pass 1st boss or turning off speedhack will cause TLB Error message in Opening

**Comment by Xaelath** [comment] 2016-04-01 14:27
Edit After Checking nhydock It seems they already pass the 1st boss.
Does that mean my iso/disc corrupted?

**Comment by ssakash** [comment] 2016-04-01 14:32
> Does that mean my iso/disc corrupted?

It's possible, ``TLB miss`` messages do occur when the ISO is not properly dumped from the disc.

**Comment by Xaelath** [comment] 2016-04-01 14:35
Alright then suspend the issues until i buy the Disc since theres a store not far from my house.
Thanks,

**Comment by ssakash** [comment] 2016-04-01 14:41
Why are you closing the issue ? I suggest to close it after you get a disc from the store and verify whether the issue is resolved. until then, why not keep the issue open ?

**Comment by Xaelath** [comment] 2016-04-01 14:54
I might get the disk in monday, i thought closing and reopening it count as suspending?
but oh well first thing first, the disc is the main key,
I'll give the Screen cut issues open and Lighting issues (which impossible they said?)

**Comment by Xaelath** [comment] 2016-04-05 01:50
After getting original disk
1. TLB Miss error issues gone
2. Screen cut issues also gone
3. The Lighting issues will remain the same i guess...

**Closed** 2016-04-05 04:11 UTC
