### ISSUE TITLE
Missing vertical resolution lines in GOW2.

### ISSUE THREAD

**Issue by James-F2** [PCSX2/pcsx2#2257] opened 2018-01-09 19:57 UTC
It looks like PCSX2 missing some lines in games that use the "None" deinterlacing option and the field height is 448 instead the usual 224 with interlaced games.
This happens with all plugins and scaling options.

GOW2, PCSX2 with 1:1 integer scaling of 512x448 in 1024x896.
Level 5 and Athena's Blades bottom line is missing, PS Symbols missing many lines, "=" symbol one grey line.
![gow2 1-to-1 scaling](https://user-images.githubusercontent.com/31185814/34740175-2c1081d6-f587-11e7-86f8-a40d36d4ef53.png)

512x448 1:1 window:
![512x448](https://user-images.githubusercontent.com/31185814/34740609-afd195cc-f588-11e7-811d-631163d53877.png)

PS2 on a CRT.
As it should be.
![symbols](https://user-images.githubusercontent.com/31185814/34740136-1669746e-f587-11e7-8d7a-6fe1e95bb9c1.jpg)
![text](https://user-images.githubusercontent.com/31185814/34740153-1a2f5a96-f587-11e7-8f31-7350dd946023.jpg)

**Comment by MrCK1** [comment] 2018-01-09 20:03
If you're using the build from #1918, you should comment there instead of making a new issue, it hasn't been merged yet.

**Comment by James-F2** [comment] 2018-01-09 20:08
This can be can be displayed with the normal PCSX2 build.
"Fit to Window/Screen" enter manual window size of 512x448.

**Comment by MrCK1** [comment] 2018-01-09 20:09
Oh ok, wasn't sure.

**Comment by James-F2** [comment] 2018-01-09 20:12
I believe something actually wrong with the "None" deinterlacer in 30fps 448 field height mode.
No line should be removed... there should be a reason for that.

**Comment by MrCK1** [comment] 2018-01-10 04:18
@James-F2 you should check 1.4.0 to see if this issue exists there.

**Comment by James-F2** [comment] 2018-01-10 04:35
Same thing with 1.4.0.

![1 4 0](https://user-images.githubusercontent.com/31185814/34755817-6d6b7ee0-f5cf-11e7-80d1-7889e39f01b9.png)

**Comment by MrCK1** [comment] 2018-01-10 04:37
Trying other games would be useful as well, to make sure the issue isn't limited to improper height detection of a certain game.

**Comment by James-F2** [comment] 2018-01-10 16:14
How does the height detection work?
In 1.4.0 THPS3 reports 447, while in 1.5.0   448.

Is there no general direction of thought as to what may cause so many lines in GOW to be missing?

**Comment by James-F2** [comment] 2018-01-11 04:48
Report;
Using large internal resolution in GSDx fixes the missing lines.
Can we assume that x1 resolution in GOW is reported incorrectly to GSDx by a prior stage?

![gow big internal resolution](https://user-images.githubusercontent.com/31185814/34809033-163510b0-f69b-11e7-983c-4b2835dfd201.png)

**Comment by MrCK1** [comment] 2018-01-24 20:07
@FlatOutPS2 @ssakash Any ideas on this?

**Comment by James-F2** [comment] 2018-02-08 17:16
Game in progressive.

One thing I completely forgot to mention is OpenGL Software does not have this problem and looks correct.

Here are some picture from my OSSC in 480p Line2x mode, GOWII in progressive mode.
![image 1](https://user-images.githubusercontent.com/31185814/35986692-6e52e43e-0d02-11e8-8f42-6dc5cf3fb8b1.jpg)
![image 2](https://user-images.githubusercontent.com/31185814/35986693-6e7c4eaa-0d02-11e8-82f6-24679c1a5433.jpg)

**Comment by lightningterror** [comment] 2018-10-15 06:12
Can you provide a GS dump of the issue ?

**Comment by Mrlinkwii** [comment] 2022-02-14 14:40
is this still an issue ? :slightly_smiling_face:

**Comment by lightningterror** [comment] 2022-03-17 00:39
Closing, no further information provided, also seems like an aa1 problem which hw renderer lacks.

**Closed by lightningterror** 2022-03-17 00:39 UTC
Labels: Bug, GS, Maybe?

**Comment by James-F2** [comment] 2022-12-02 10:35
> is this still an issue ? 🙂

Yes, it is still very much an issue.

Textures are rendered/scaled incorrectly at Native resolution with an HW based renderer.

![settings](https://user-images.githubusercontent.com/31185814/205273379-ad9f6754-4082-454b-a2b4-ca66647ff613.jpg)

SW 1
![SW 1](https://user-images.githubusercontent.com/31185814/205272872-5a8f151d-2b87-48a3-a338-973bcba63aaf.jpg)

Vulkan 1
![Vulkan 1](https://user-images.githubusercontent.com/31185814/205272883-d3aefe36-91b2-407b-a85f-d6ec5cdba7aa.jpg)

SW 2
![SW 2](https://user-images.githubusercontent.com/31185814/205272902-76615c50-8ffc-4a31-8afa-032a2cc0faf2.jpg)

Vulkan 2
![Vulkan 2](https://user-images.githubusercontent.com/31185814/205272893-22216b33-bf00-415f-8e5d-4657b9e83844.jpg)

**Comment by refractionpcsx2** [comment] 2022-12-02 10:42
Sure, that's called AA1 edge antialiasing, which HW mode doesn't support, and I'm not sure how easily it could quickly, this could be very slow.

**Comment by James-F2** [comment] 2022-12-02 10:53
From what I see it does not affect all textures, only some layers of Font/Text, Magic/Life Bar and similar that use this layer.
Maybe a partial solution or even a hack will be better than none at all?

**Comment by Mrlinkwii** [comment] 2022-12-02 10:56
@James-F2 Software rendering  is the solution for now

**Comment by James-F2** [comment] 2022-12-02 11:45
For future reference.
GoW1 -> Options -> Controller Display.
My real console and OSSC/RetroTINK are in storage but it looks like even the Software renderer is missing some lines.

Can someone grab a still image of this screen from the real console? That would be very helpful as reference.

Software
![SW 3](https://user-images.githubusercontent.com/31185814/205284503-425bbbd1-c7d0-4eab-af59-22be62f0f126.png)


Vulkan 1x
![Vulkan 3](https://user-images.githubusercontent.com/31185814/205284538-60475d8d-c745-43da-864a-7a79f210298a.png)


Vulkan 3x
![Vulkan 3 (x3 1080)](https://user-images.githubusercontent.com/31185814/205285039-708e6a95-e912-438d-b7a6-e6101270fd58.png)

**Comment by James-F2** [comment] 2022-12-04 16:31
Real Console for reference:
![Real Console](https://user-images.githubusercontent.com/31185814/205503121-dc395285-5310-4734-a5ff-23a7e8e41caa.jpg)
