### ISSUE TITLE
[BUG]: Emulator crashes when playing with two-player (two joystick and the second joystick press "start")

### ISSUE THREAD

**Issue by KondeU** [PCSX2/pcsx2#9785] opened 2023-08-13 03:17 UTC
### Describe the Bug

Emulator crashes while playing "Shin Sangoku Musou 5 Special" when pressing the second joystick "start" to join the game.

### Reproduction Steps

1. Run the pcsx2-qt.exe
2. Double click to load game iso file
![image](https://github.com/PCSX2/pcsx2/assets/29046736/fb94b847-a1a6-4aca-a272-315c7ca16d9c)
3. Go to the page where the second player joins in the game
4. Press the second joystick to join the game
5. Black screen with no sound
6. Crash!

### PCSX2 Revision

pcsx2-v1.7.4910-windows-x64-Qt

### Operating System

Windows 10 (64bit)

### CPU

11th Gen Intel(R) Core(TM) i7-11700

### GPU

NVIDIA GeForce RTX 3050

### Logs & Dumps

Crash log and coredump for visual studio file as following.
[crash-2023-08-13-01-05-40-863.zip](https://github.com/PCSX2/pcsx2/files/12328737/crash-2023-08-13-01-05-40-863.zip)
[crash-2023-08-13-01-08-15-433.zip](https://github.com/PCSX2/pcsx2/files/12328738/crash-2023-08-13-01-08-15-433.zip)

**Comment by stenzek** [comment] 2023-08-13 03:22
Crash dump is in the recompiler, because the game has jumped to invalid EE code.

**Comment by KondeU** [comment] 2023-08-13 03:46
Do you mean this may be an internal bug in the game? but it worked fine on my another computer with 1.6.0 version 🤣

**Comment by stenzek** [comment] 2023-08-13 03:47
"Working in 1.6" isn't very helpful, unless you can pinpoint which build regressed it. There's been thousands of changes since 1.6.

My guess would be a regression from the SIO/Pad rewrite. But it could be anything.

**Comment by KondeU** [comment] 2023-08-14 08:02
all right, maybe I just can keep an eye on the new version, maybe other changes will fix it...

**Comment by Mrlinkwii** [comment] 2023-11-27 15:18
can this be rechecked on latest nightly :)

**Comment by pv-oliveira** [comment] 2024-01-17 23:49
Is there a solution? I'm facing the same issue

**Comment by lightningterror** [comment] 2024-01-28 03:18
@KondeU Can this be re tested on latest Nightly, if the issue persists can you take a blockdump using 1.6 from starting the game till after pressing the start on the second joystick?

**Comment by Mrlinkwii** [comment] 2024-02-03 13:51
i think this may be a duplicate of  #8197 not sure tho

**Closed** 2024-11-23 12:16 UTC
Labels: Bug, GUI/Qt
