### ISSUE TITLE
[BUG] Certain PS2 BIOS revisions render text incorrectly

### ISSUE THREAD

**Issue by RedPanda4552** [PCSX2/pcsx2#4459] opened 2021-05-24 17:47 UTC
**Describe the bug**
The Browser section of the PS2 BIOS does not properly render text on some BIOS revisions. Text is generally supposed to have a strong outline, however that is not the case in PCSX2. It is worth noting only certain BIOS revisions have this issue. 

**To Reproduce**
Boot the BIOS and select Browser. At the memory card screen, observe the text on the top of the screen, it will not have the hard outline it should (screenshot from PCSX2, running my NTSC-U v1.60 BIOS).
![image](https://user-images.githubusercontent.com/6377490/119386467-8efc9900-bc95-11eb-88f5-d017a98164be.png)

**Expected behavior**
Text should have a strong outline on it (picture taken from a physical PS2, mind the quality of the screen, from the same NTSC-U v1.60 BIOS system).
![image](https://user-images.githubusercontent.com/6377490/119386696-e3a01400-bc95-11eb-824b-a595eb10a99d.png)

**GS Settings**
Software renderer, default options. Hardware renderer and its options do not help.

**Emulation Settings**
Preset 2.

Also tried EE/IOP and VU modes; all modes were ineffective.

Also tried gamefixes; all modes were ineffective or crashed the BIOS.

**System Info (please complete the following information):**
 -   PCSX2 Revision: 1.7.0-dev-1265
 -   OS: Win10
 -   CPU: Ryzen 7 5800X
 -   GPU: GTX 1070 Ti

**Logs and Dumps**
GS dump: [gsdx_20210524134652.zip](https://github.com/PCSX2/pcsx2/files/6534062/gsdx_20210524134652.zip)

**Comment by JordanTheToaster** [comment] 2021-05-24 17:48
Broken on Europe V2.00

![rtjrytkjmtyfkm](https://user-images.githubusercontent.com/80843560/119387312-ac932800-bcc0-11eb-810a-c6072dc48f25.jpg)

**Comment by WarWolfFloof** [comment] 2021-05-24 17:55
![20210524_130541](https://user-images.githubusercontent.com/84736897/119387852-87d68a80-bc97-11eb-88f8-fb9f5489d10e.jpg)
Does this on US Bios 1.60

Should look like this. Taken from Japanese bios 1.00
![20210524_130629](https://user-images.githubusercontent.com/84736897/119387951-a76db300-bc97-11eb-988a-cdbf964f2961.jpg)

**Comment by coornio** [comment] 2021-05-24 19:00
Never crossed my mind, as I hardly ever have reason to visit the BIOS to begin with, so good catch there. I have likewise attempted all settings that I could find to cause any sort of change to that, and it remains the same in both SW and HW rendering. The emulator itself appears to be doing something wrong, and not necessarily the GS plugin itself.

Since @WarWolfFloof found that it appears to work normally on early BIOS revisions, I'm thinking that one of them may have changed this very bit that's been carried over to all future revisions. Anyone got a collection of PS2 BIOS'es to try this out further and narrow it down?

**Comment by maxdlpee** [comment] 2021-05-24 21:23
![pic1](https://user-images.githubusercontent.com/77379259/119409035-11e51a00-bcbd-11eb-9e39-6ae88d8c36ea.png)
Can confirm it happens on USA 2.0 as well.

**Comment by tadanokojin** [comment] 2021-05-24 21:34
@coornio 

> I'm thinking that one of them may have changed this very bit that's been carried over to all future revisions. 

Figuring out which bios it broke on is not going to help. I'm confident it's like this on all of them but JP v1 which I'm already mildly annoyed is even being mentioned because it's so rare that I can almost guarantee no one legit owns it.

>  Anyone got a collection of PS2 BIOS'es to try this out further and narrow it down?

Don't encourage the pirates.

I don't need any more samples thank you.

**Comment by tadanokojin** [comment] 2021-05-25 03:19
Boot with EE on interpreter and EE cache enabled.

**Comment by RedDevilus** [comment] 2021-05-25 03:24
You don't even need to boot with that, just be on start screen go to Browser with EE on int and EE cache enabled, if you go back with recompiler and re-enter it will be wrong font (aka not in bold) again. 

PCSX2  EE on interpreter and EE cache:
![image](https://user-images.githubusercontent.com/24227051/119434846-4e466380-bd19-11eb-8636-34369a6712c5.png)

**Comment by maxdlpee** [comment] 2021-05-25 06:37
So the issue is from the recompiler then? Interesting, wonder why the JP 1.00 BIOS doesn't need that.

**Comment by refractionpcsx2** [comment] 2021-05-25 08:56
There you go, we now have a PR to fix this without requiring EE Cache.

**Comment by tadanokojin** [comment] 2021-05-25 21:07
> So the issue is from the recompiler then?

No. It's a lack of emulated dcache. It wouldn't be practical to emulate so Ref's PR fixes both the interpreter and the recompiler by making DMA instant so the EE doesn't have time to overwrite one transfer with another. It's an issue on both but it's more obvious on the interpreter due to what I presume is some differences in timing. We've always known about the issue but we sort of just shrugged and said it worked on the recompiler until someone pointed out it wasn't exactly right there either.

> wonder why the JP 1.00 BIOS doesn't need that.

That bios is hacked up and rushed out the door for the first consoles Sony released in Japan. Only so many of them were made and even less exist today. If someone wants to prove they own the rarest console revision associated with that bios I'll explain it to them. Otherwise I don't want to hear about it again.

**Comment by maxdlpee** [comment] 2021-05-26 04:26
> Otherwise I don't want to hear about it again.
I was just curious, that's all. But there's not much I can do if you don't want to talk. Maybe we should get this closed, since it seems the issue is resolved.

**Closed** 2021-06-05 01:01 UTC
Labels: Core, Requires EE Cache
