### ISSUE TITLE
[Linux] PCSX2 crash when bluetooth mouse reconnects and moves cursor over game window

### ISSUE THREAD

**Issue by kimimaru4000** [PCSX2/pcsx2#3426] opened 2020-05-27 01:26 UTC
***PCSX2 version:***
``PCSX2 1.7.0-0 - compiled on May 25 2020``

***PCSX2 options:***
[Logs and settings enclosed.](https://github.com/PCSX2/pcsx2/files/4685869/PCSX2_Logs.zip)

***Plugins used:***
```
GS: libGSdx-AVX2.so [GSdx (GCC 7.5.0 AVX2/AVX2) 1.2.0]
PAD: libonepad-legacy.so [OnePAD 0 1.3.0]
SPU2: libspu2x-2.0.0.so [SPU2-X 2.0.0]
CDVD: libCDVDnull.so [CDVDnull Driver 0 0.6.0]
USB: libUSBnull-0.7.0.so [USBnull Driver 0 0.7.0]
FW: libFWnull-0.7.0.so [FWnull Driver 0 0.7.0]
DEV9: libdev9null-0.5.0.so [DEV9null Driver 0 0.5.0]
```

***Description of the issue:***
``When playing any game, if my bluetooth mouse reconnects or wakes up and I move the mouse cursor over the game window with the mouse, the entire emulator will crash without warning. This occurs only when PCSX2 is running a game. If I move the cursor with a touchpad, it does not crash.``

The mouse is a TECKNET BM308 bluetooth wireless mouse.

***How to reproduce the issue:***
``Have the mouse disconnected or idle for a long time while playing a game. Reconnect the mouse or take it out of idle by clicking, then move the mouse cursor using the mouse over the game window.``

***Last known version to work:***
``N/A - have yet to test``

***PC specifications:***
```
CPU: Intel Core i7-9750H CPU @ 2.60GHz, 1 physical processor; 6 cores; 6 threads
GPU: GeForce RTX 2060
OS: Linux Mint 19.3 Tricia 64-bit
```

**Comment by tdeeb** [comment] 2020-09-22 02:54
Running this in a terminal, the last thing I see before the crash is "Trace/breakpoint trap." The issue still occurs on the Sep 21 2020 build and on Linux Mint 20 Ulyana.

**Comment by kenshen112** [comment] 2020-09-22 02:57
Can you run pcsx2 in GDB and get us a backtrace?

**Comment by tdeeb** [comment] 2020-09-22 04:19
This is what I got:
```
[Thread 0xef1ffb40 (LWP 81150) exited]
Stream Buffer 1Bank 65536byte 12banks 786432byte used

(PCSX2:81118): Gdk-CRITICAL **: 21:18:59.613: gdk_event_set_source_device: assertion 'GDK_IS_DEVICE (device)' failed

(PCSX2:81118): Gdk-CRITICAL **: 21:18:59.613: gdk_device_get_device_type: assertion 'GDK_IS_DEVICE (device)' failed

(PCSX2:81118): Gdk-CRITICAL **: 21:18:59.613: gdk_device_list_slave_devices: assertion 'GDK_IS_DEVICE (device)' failed

(PCSX2:81118): Gdk-CRITICAL **: 21:18:59.613: gdk_event_set_source_device: assertion 'GDK_IS_DEVICE (device)' failed

(PCSX2:81118): Gdk-CRITICAL **: 21:18:59.614: gdk_device_get_n_axes: assertion 'GDK_IS_DEVICE (device)' failed

(PCSX2:81118): Gdk-CRITICAL **: 21:18:59.614: gdk_event_set_source_device: assertion 'GDK_IS_DEVICE (device)' failed

Thread 1 "PCSX2" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xf502ba80 (LWP 81118)]
0xf6afe8a8 in ?? () from /usr/lib/i386-linux-gnu/libgdk-3.so.0
```

**Comment by kenshen112** [comment] 2020-09-22 04:26
So, there's the crash if you type `backtrace` or `bt` after that happens then copy all of that info in here that would be helpful

**Comment by tdeeb** [comment] 2020-09-22 05:03
Here's what I've got:
```
#0  0xf6b248a8 in ?? () from /usr/lib/i386-linux-gnu/libgdk-3.so.0
#1  0xf6b2f05e in ?? () from /usr/lib/i386-linux-gnu/libgdk-3.so.0
#2  0xf6b2ec09 in ?? () from /usr/lib/i386-linux-gnu/libgdk-3.so.0
#3  0xf6af38f7 in gdk_display_get_event ()
   from /usr/lib/i386-linux-gnu/libgdk-3.so.0
#4  0xf6b2e749 in ?? () from /usr/lib/i386-linux-gnu/libgdk-3.so.0
#5  0xf621b35d in g_main_context_dispatch ()
   from /usr/lib/i386-linux-gnu/libglib-2.0.so.0
#6  0xf621b609 in ?? () from /usr/lib/i386-linux-gnu/libglib-2.0.so.0
#7  0xf621b949 in g_main_loop_run ()
   from /usr/lib/i386-linux-gnu/libglib-2.0.so.0
#8  0xf6e25656 in gtk_main () from /usr/lib/i386-linux-gnu/libgtk-3.so.0
#9  0xf7810add in wxGUIEventLoop::DoRun() ()
   from /usr/lib/i386-linux-gnu/libwx_gtk3u_core-3.0.so.0
#10 0xf7ce6137 in wxEventLoopBase::Run() ()
   from /usr/lib/i386-linux-gnu/libwx_baseu-3.0.so.0
#11 0xf7ca80c2 in wxAppConsoleBase::MainLoop() ()
   from /usr/lib/i386-linux-gnu/libwx_baseu-3.0.so.0
#12 0xf78db883 in wxAppBase::OnRun() ()
   from /usr/lib/i386-linux-gnu/libwx_gtk3u_core-3.0.so.0
#13 0xf7d40cdb in wxEntry(int&, wchar_t**) ()
   from /usr/lib/i386-linux-gnu/libwx_baseu-3.0.so.0
#14 0xf7d41937 in wxEntry(int&, char**) ()
```

**Comment by tdeeb** [comment] 2020-09-23 02:47
@kenshen112 Does this suffice?

**Comment by kenshen112** [comment] 2020-09-23 02:49
That's good for now yeah

**Comment by Shoegzer** [comment] 2021-03-27 18:18
This issue, as I've also noted in the above referenced post, still occurs on Linux Mint 20.1 / Ubuntu 20.04 with kernel 5.8 built with gcc 10.2.0 (latest tested build is bc477e1ce10a54c279b681a8d6b99f34d5d0b8fb).  Using Nvidia 1070M with driver 460.39.

This may be caused by an X11 bug if memory serves, though I'm hoping pcsx2 can eventually work around it.  As one may imagine, this quite often gets in the way as any attempt to use a bt keyboard or mouse after starting PCSX2 causes it to crash.  

@tdeeb if you discover anything that may help until a proper fix is in place please post it here, I've tried lots of options including pausing PCSX2 before using keyboard etc. but nothing seems to work.

**Comment by tdeeb** [comment] 2021-03-30 04:17
I haven't discovered anything new unfortunately, but I'm wondering if this is really an X or GTK issue. I have yet to experience this issue on any other application, including other emulators. Are they perhaps using workarounds that avoid this? Or is something not implemented properly?

Keep in mind I don't have any experience working in X or GTK, so I'm just throwing ideas out there.

**Comment by Shoegzer** [comment] 2021-03-30 16:39
@tdeeb Actually ignore my previous comment, this seems to be a GTK3 issue and not anything related to X11 itself (I was working on a separate X11 issue when I wrote that).  Apparently something in the PCSX2 code triggers the GTK3 bug but I have no idea what it is.  You're right though that you'd expect this to be common among other applications that use GTK3.  While I use many of them too, I have yet to encounter one that immediately kills the application when you awaken a bluetooth mouse and cross the pointer over its draw frame.  That's why I was hoping PCSX2 could somehow work around it.  With any luck this is somewhere in the wxwidgets code and could get resolved with the eventual move to Qt, but we'll see.

**Comment by Shoegzer** [comment] 2021-07-09 20:19
@CookiePLMonster I had some small hope that your PR #4404 might have helped this issue given that it involves the draw frame, though it's entirely different (bluetooth / GTK related).  Testing against it confirmed this, unfortunately.  Any ideas you have here though would be quite welcomed.

**Comment by CookiePLMonster** [comment] 2021-07-09 20:24
Unless it reproduces on Windows I don't think I'd be able to provide any valuable feedback.

**Comment by Shoegzer** [comment] 2021-07-09 20:39
Ah okay, fair enough.  Given the assumed root cause somewhere in GTK-land I don't believe it would.  If you know anyone who may be familiar with this sort of thing in linux though, please feel free to join them to the thread, as I'm not sure who would be best myself.

**Comment by RedDevilus** [comment] 2021-07-09 20:42
Yeah 4404 was for a rare issue on windows where something like the NVIDIA overlay took the focus. It won't help this issue whatsoever. No idea what's going on with your system though.

**Comment by Shoegzer** [comment] 2021-07-09 20:49
Yup, I surmised such from the nature of the PR, but given the severity of this issue I always test against anything that has even a small hope of helping.

To be clear though, this issue should affect all linux systems, not just mine (at least we have two here that confirms this as well as more from #3868).

**Comment by tdeeb** [comment] 2021-07-10 00:01
I came across [GtkInspector](https://wiki.gnome.org/action/show/Projects/GTK/Inspector). From what I see in #3868, PCSX2 was debugged without GTK debug symbols which made it more difficult. Do you think this tool would help diagnose the problem?

**Comment by Shoegzer** [comment] 2021-07-10 17:34
I assume you mean to recompile PCSX2 with debug symbols and then retest using GtkInspector?  Perhaps it would help, though noting the following from the link you provided:

> To launch the GTK Inspector, focus your GTK application and press Control-Shift-D. Alternatively, move your mouse cursor to your desired widget and press Control-Shift-I to specifically inspect the widget under the mouse cursor. 

I assume the GTK Inspector process must be launched prior to reconnecting the bluetooth device given that not doing that would crash PCSX2 before the key combinations noted above can be entered.  I also hope the process will effectively capture useful data after the crash occurs.

Also, please feel free to test this yourself.  Given that you have a similar setup to mine, at the very least we'd have two results from which to draw conclusions.

**Comment by HeroponRikiBestest** [comment] 2022-01-07 03:17
On Linux Mint 20.2, the same thing happens if I connect a USB wired mouse during gameplay.
Bt:
```
(gdb) bt
#0  0x00007f16b1c2665d in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#1  0x00007f16b1c30999 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#2  0x00007f16b1c304dc in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#3  0x00007f16b1bf80f4 in gdk_display_get_event ()
    at /lib/x86_64-linux-gnu/libgdk-3.so.0
#4  0x00007f16b1c300f6 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007f16b1a5f17d in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f16b1a5f400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007f16b1a5f6f3 in g_main_loop_run ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007f16b1f1337d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007f16b2ce7575 in wxGUIEventLoop::DoRun() ()
    at /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0
#10 0x00007f16b3195d41 in wxEventLoopBase::Run() ()
    at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#11 0x00007f16b315d3da in wxAppConsoleBase::MainLoop() ()
    at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#12 0x00007f16b31e973d in wxEntry(int&, wchar_t**) ()
    at /lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#13 0x0000559695a691ec in main(int, char**)
    (argc=<optimized out>, argv=<optimized out>) at ../pcsx2/gui/AppMain.cpp:72
```

**Comment by marcoluc97** [comment] 2022-05-01 07:54
I know is still a wip but @stenzek do you think is worth it test QT about this bug or is too soon?

**Comment by Shoegzer** [comment] 2022-05-01 16:57
@stenzek If it helps, I've tested this issue with the Qt UI and I don't encounter it, so it seems to have been related to wx.   Others can report their results too, though assuming the same, I'd recommend closing this when Qt replaces wx officially.

**Comment by Shoegzer** [comment] 2022-10-03 00:12
@kimimaru4000 Can you close this issue?  This shouldn't occur for you on master with the Qt UI.

**Closed** 2022-10-03 00:15 UTC
Labels: OS: Linux, Needs Research

**Comment by kimimaru4000** [comment] 2022-10-03 06:56
Thanks everyone! I just tested with Qt and it is indeed fixed. Appreciate it!
