### ISSUE TITLE
[BUG]: "Hitman blood money" stained 

### ISSUE THREAD

**Issue by MBeeBR** [PCSX2/pcsx2#8987] opened 2023-06-16 14:00 UTC
### Describe the Bug

I finally got where I can report bugs!
As can be seen in the video a green and red spot appears
(Hitman - Blood Money)

https://github.com/PCSX2/pcsx2/assets/136722551/960c9301-6181-4219-93a8-d63ab132aeaa

### Reproduction Steps

just go the first mission.

### PCSX2 Revision

1.7.4585

### Operating System

Windows 10 (64bit)

### CPU

E5-2640 v3

### GPU

RX-570 4GB

### Emulation Settings

![unknown_2023 06 16-10 58](https://github.com/PCSX2/pcsx2/assets/136722551/49013f12-bc17-44dd-b432-b2fa12174bf3)

**Comment by Mrlinkwii** [comment] 2023-06-16 14:02
duplicate of #4251

**Closed** 2023-06-16 14:03 UTC
Labels: Bug
