### ISSUE TITLE
[GSdx] San Andreas Radiosity Broken - DX11 HW mode

### ISSUE THREAD

**Issue by Quidgebo** [PCSX2/pcsx2#2532] opened 2018-07-31 09:10 UTC
Development build v1.5.2456
DX11 HW mode
Internal resolution = x6
Anisotropic Filtering: 16x
Safe preset
MTVU speed hack
Auto Flush HW hack enabled
CRC Hack Level: Partial
CRC = B440A8FE

DX11 HW mode on GS 1.1.0 has broken effects for GTA: SA.

With Auto Flush enabled, using None, Partial or Full CRC hack level, all display as if the skipdraw "3" hack is enforced despite being set to 0. Lighting, radiosity and blooms effects are missing. If using Partial CRC hack level the heat haze effect works fine though, so shows that some layer effects are OK.

DX11 HW mode - Partial CRC hack level.
![gsdx_20180731094457](https://user-images.githubusercontent.com/3399303/43448738-94eb0960-94a6-11e8-870d-e3580375c5dc.png)

GS dump of DX11 HW mode.
[gsdx_20180731094457.zip](https://github.com/PCSX2/pcsx2/files/2244482/gsdx_20180731094457.zip)

To confirm it seemed to be within the plugin I copied GS v1.0.0 file from v1.4.0 and selected it in v1.5.0. As the auto Auto Flush hack isn't available shall ignore the known overlay issue, yet all lighting effects return along with the heat haze effect.

GS 1.0.0, DX11 HW - Same build, same options, no Auto Flush HW hack.
![image](https://user-images.githubusercontent.com/3399303/43450800-724a5f32-94ab-11e8-9409-64066f0751c0.png)

Found issue whilst testing and comparing for #2525.

**Comment by lightningterror** [comment] 2018-07-31 10:15
The game needs Hardware Depth on Direct3D which needs to be ported from OpenGL.

Duplicate of #2458

**Closed by lightningterror** 2018-07-31 10:15 UTC
Labels: GSdx: Depth, GSdx: Direct3D, GSdx: Hardware

**Comment by Quidgebo** [comment] 2018-07-31 10:40
OK thanks for the update. Shall follow 2458.
Can I confirm (simplistically I know) as it worked OK on GS plugin 1.0.0 yet there is no options to halt the previous overlay issues.

So my understanding is the change is caused by new code in 1.1.0 (which for example provides Auto Flush, mip-mapping etc) yet will in addition now need Hardware Depth to replicate the effects which worked before in GS 1.0.0 on DX11?

I'm just curious, still plan to use OpenGL as the better solution.
