### ISSUE TITLE
Tomb Raider Underworld NTSC-U & PAL (SLUS-21858) (SLES-55442) - Graphic glitches and very slow

### ISSUE THREAD

**Issue by LeCharlatan** [PCSX2/pcsx2#2027] opened 2017-07-26 21:03 UTC
Hi (again),

First, here are basics informations :

**PCSX2 :**

**Build :** Dev PCSX 1.5.0~git201707251955 (PPA PCSX2 Team Daily Builds)

**PCSX2 options :**

**GSDX :** OGL Backend
**Speed hacks :** OFF

**GSDX Options :**

**Texture Filtering :** Bilinear (PS2)
**Large Framebuffer :** ON (Checked)
**Internal Resolution :** 2x Native
**Anisotropic Filtering :** OFF
**Blending Unit Accuracy :** High (Recommended high-end PC)
**Automatic CRC level :** Partial (OpenGL Recommended)
**Mipmapping (Insert) :** Basic (Fast)
**Mipmapping :** ON (Checked)

**Description of the issue:**

**NTSC-U Version**

TR - Underworld is showing a bad glitches that makes the NTSC-U unplayable using OGL HW
![screenshot_20170726_215159](https://user-images.githubusercontent.com/22820335/28642712-a2146634-7253-11e7-9271-fde04daf7501.png)

It seems that OGL SW is working fine tho
![screenshot_20170726_215010](https://user-images.githubusercontent.com/22820335/28642752-c0b3b11c-7253-11e7-98e6-3b3705f6de96.png)

**PAL Version**

Unlike the NTSC-U version, PAL looks fine using OGL HW (maybe it's missing some glow effect) but, it misses the blue blinking square on choice menu on OGL HW

Missing blue blinking cursor (OGL HW)
![screenshot_20170726_223604](https://user-images.githubusercontent.com/22820335/28642894-39a9ae96-7254-11e7-9908-5b2b4b5afaa0.png)

Here it is ! (OGL SW)
![screenshot_20170726_223636](https://user-images.githubusercontent.com/22820335/28642967-87c8f956-7254-11e7-8dd1-4977b386e983.png)

**Note :** this blinking blue cursors does not appear on PAL version using OGL HW, however, the ntsc-u shows it, even on OGL HW

A last point about both versions, they're using 100% of one CPU's core and the game is extremely slow on some points. This only happens in-game, not on menus
![screenshot_20170726_220031](https://user-images.githubusercontent.com/22820335/28644104-77e489a2-7258-11e7-9943-3e57907b2b5f.png)

**How to reproduce the issue :**
Just launch games with OGL HW, it appears everytime
About DirectX 9/11 I've no idea since I'm not able to use it on Linux

**Last known version to work :**
Don't know

**PC specifications :**

**OS :** Kubuntu 16.04 (Xenial)
**CPU :** Intel i5 4690K (Haswell)
**GPU :** Nvidia GTX 1070 + Proprietary drivers 381.22
**RAM :** 32Go DDR3-1600

**Here GS Dump of both version in case of needs :** 

**NTSC-U :** [tr-underworld-ntsc-u.zip](https://github.com/PCSX2/pcsx2/files/1178023/tr-underworld-ntsc-u.zip)

**PAL :** [tr-underworld-pal.zip](https://github.com/PCSX2/pcsx2/files/1178026/tr-underworld-pal.zip)

Sorry maybe those two problems have nothing in relation with each other but I post them together. Hope I'm not doing wrong :)

**Comment by lightningterror** [comment] 2017-07-26 23:30
What are your crc ids for NTSC-U and PAL ?

**Comment by LeCharlatan** [comment] 2017-07-27 08:45
Hello @lightningterror 

Here are CRC of each version. I hope this is what you asked for since I'm not sure

PAL : CRC = 0x8E214549 
NTSC-U : CRC = 0x618769D6

**Comment by gregory38** [comment] 2017-07-27 10:48
Speed wise accurate blending isn't a good idea. Anyway the game suffer of texture cache issue. The best that can be done so far is CRC hack to remove bad draw calls.

**Comment by lightningterror** [comment] 2017-07-27 12:49
Well looking at the comparison I kinda knew the crc was missing for the US version.

Can you try this out ?
https://ci.appveyor.com/api/buildjobs/9h7yik9jrtxi3gvc/artifacts/pcsx2-v1.5.0-dev-2151-g828e24233-3219-vs2015-Win32-AppVeyor.7z

**Comment by LeCharlatan** [comment] 2017-07-27 12:58
Thanks both of you !

@gregory38 About speed, changing Blending Unit Accuracy to Basic doesn't change anything. I tried some other options but speed is still a problem (NTSC-U and PAL version both)

@lightningterror Ah, your link is for Windows, not Linux, I can't really use it :D

**Comment by lightningterror** [comment] 2017-07-27 13:08
Ops didn't see that , I dunno where to find the linux alternatives xD

**Comment by LeCharlatan** [comment] 2017-07-27 13:10
However I did write OS that I'm using T_T

Bad reader :p

**Comment by lightningterror** [comment] 2017-07-29 19:01
Check the new PPA build once it's available , the code is added in to the master.

**Comment by gregory38** [comment] 2017-07-29 19:13
To confirm, so far Linux is limited to PPA

**Comment by LeCharlatan** [comment] 2017-07-29 21:35
Hi @lightningterror 

Yep I did update my version some minutes ago and it works like the European version !
Then, it still missing the blue square on choice windows like my screenshot :)

Thanks for all efforts :D

**Note :** This new version freezes then crashes when push ESC button to close the game windows

**Comment by lightningterror** [comment] 2017-07-29 21:38
`Note : This new version freezes then crashes when push ESC button to close the game windows`

Does it happen if you set CRC hack level to None?

**Comment by LeCharlatan** [comment] 2017-07-29 21:46
Do you mean "Automatic CRC level" ?

**Comment by lightningterror** [comment] 2017-07-29 21:48
Yes what if you set it to "None (Debug) , do you still experience the crash?
You can put it back to Automatic once you are done with testing.

**Comment by LeCharlatan** [comment] 2017-07-29 21:49
Yes, it does happen if set it to "None"

(Edited previous message too late sorry)

**Comment by LeCharlatan** [comment] 2017-07-29 21:54
Okay I just tested another game, it does crash the same way when push ESC button, not only TB Underworld crashes then

**Comment by lightningterror** [comment] 2017-07-29 22:21
Can you track down the build that introduced the crash?

**Comment by LeCharlatan** [comment] 2017-07-29 22:30
Yeah easy, that's the add today in the PPA (since I update it on every new dev version)
The version I used to post the TR - Underworld issues was the version just before and it did not crash like that
So, the guilty is "1.5.0~git201707291440~ubuntu16.04.1"

**Comment by lightningterror** [comment] 2018-12-08 11:20
I'll close this since there's a crc hack in place and it's essentially a duplicate of https://github.com/PCSX2/pcsx2/issues/1318

**Closed by lightningterror** 2018-12-08 11:20 UTC
Labels: GSdx: Hardware, GSdx: Texture Cache, Plugin: GSdx, Workaround Possible
