### ISSUE TITLE
[BUG]: Persona 3 FES - Flickering with texture replacement

### ISSUE THREAD

**Issue by DniweTamp** [PCSX2/pcsx2#5862] opened 2022-04-13 20:36 UTC
### Describe the Bug

While using texture replacement feature (with both png and dds images) some ui elements in P3FES flicker between replaced and original variants for some reason. Which elements flicker and which don't is random between each play session. Font is always flickering.

### Reproduction Steps

All I did was dump some textures and upscale them, for testing. Was using Vulkan renderer. Later tried D3D11 and OGL - same thing.

### PCSX2 Revision

v1.7.2587

### Operating System

Windows 11

### CPU

i5-8250u

### GPU

Geforce MX130

### GS Settings

![image](https://user-images.githubusercontent.com/39583006/163266010-2d44ee62-20fa-46f1-b21e-6bc4ac3f56f7.png)
![image](https://user-images.githubusercontent.com/39583006/163266020-612514e9-0ab1-4270-a7b2-0c01bce58e85.png)
![image](https://user-images.githubusercontent.com/39583006/163266035-44432cd2-779c-4db3-ba48-ad61cd93709a.png)

### GS Window Screenshots

https://user-images.githubusercontent.com/39583006/163265693-3ad24084-46e1-4d31-98ce-0bede3cacc2d.mp4

**Comment by Gunlaus** [comment] 2022-04-14 22:28
Did you scale your texture's alpha before upscaling them and then revert them to original alpha value?

**Comment by DniweTamp** [comment] 2022-04-15 02:06
this is a raw upscale, the alpha was untouched

**Comment by FuxorLuck** [comment] 2022-04-15 08:20
I encoutred alot of textures become invisible ,turning black or become broken and here is what I am doing in order to fix it. 

Download ctt-ps and Image Magick Win64 static at 8 bits-per-pixel component to the same folder

https://forums.dolphin-emu.org/Thread-custom-texture-tool-ps-v50-1


I open ctt-ps Choose expert mode and in Operation I Choose PNG Alpha Manipulation, then customize data, enable modify and click customize and set A=1

![e50b9707cba0bcee7949af767dfdf2028705c16c](https://user-images.githubusercontent.com/55870574/163545087-b4e47312-5034-4cee-8401-3b8d0b1c78da.jpg)


Click the $ symbol and load the texture that is responsible for the issue or all of them if i dont know which texture is responsible click start 

Not sure if it's a pcsx2 bug.

**Comment by Gunlaus** [comment] 2022-04-15 20:29
https://github.com/PCSX2/pcsx2/blob/master/tools/texture_dump_alpha_scaler.py

**Comment by ZwipZwapZapony** [comment] 2022-04-20 15:01
In (at least) Secret Agent Clank, I experience something that seems related. I replaced a GUI texture, though rather than flickering, it's just sometimes the original texture and sometimes my replacement, switching every few minutes or so.

My uneducated guess is that when a texture is loaded, it's "randomly" either the original texture or the replacement.
In Persona 3, the text texture (possibly) reloads every frame, causing "random" flickering, while in Secret Agent Clank, it stays loaded for a longer time before being reloaded.

**Comment by DniweTamp** [comment] 2022-04-20 16:59
even if you do use the alpha scaling script (which does somewhat help), text will still be flickering (look at Mitsuru's text, near the end of the video)

https://user-images.githubusercontent.com/39583006/164283954-626599aa-5af5-4ed8-8491-afa05775b0e1.mp4

**Comment by stenzek** [comment] 2022-04-21 03:05
If you can isolate it to a single texture, I can look into it, but otherwise this isn't really enough information to investigate what's going on.

**Comment by DniweTamp** [comment] 2022-04-21 05:50
each font letter, in each color variant is a separate image

so uuuuuuuhhhhh yeah i don't know about that

**Comment by ZwipZwapZapony** [comment] 2022-04-22 13:01
I've found a way to reproduce it on demand in the PAL version of Secret Agent Clank (SCES-55496). If it matters, I'm using the Vulkan renderer.
This zip contains a texture that makes text have orange outlines instead of blue, as well as a (new game plus) save state for reproduction: [_Secret Agent Clank (SCES-55496) Custom Texture Bug.zip_](https://github.com/PCSX2/pcsx2/files/8541133/Secret.Agent.Clank.SCES-55496.Custom.Texture.Bug.zip)

\
\- Load the save state. Clank will be staring into a corner. Hold Triangle to open the Quick Select menu, then let go to close it. The bolt/money counter in the top right should now have the custom orange outlines.
\- Now use the right stick to turn the camera and look behind Clank. The bolt counter should now have the original blue outlines, even if you open the Quick Select menu again.
\- Now look into the corner in front of Clank and open the Quick Select menu again. The bolt counter should now have the custom orange outlines again.

(If that doesn't work, then pause the game, go to "Special" > "Cinematics", and load a cutscene. This should make the text have the custom orange outlines for one frame before the cutscene plays.)

**Comment by MrCK1** [comment] 2022-05-10 14:59
Closing this since texture replacement is provided as-is. Glitches with some games are expected.

**Comment by stenzek** [comment] 2022-05-10 15:02
Tbh this one could probably stay open, as it sounded like there was an issue, at least for the OP. Just can't do anything about it unless they provide replacement files, so I can see what's going on.

The Secret Agent Clank thing sounded like a non-issue, and just a different texture.

**Comment by DniweTamp** [comment] 2022-05-10 18:51
alright I got some P3HD textures ported https://drive.google.com/file/d/1VRWGVWXbUQEZfodG3Axy__ClEb0R-kM8/view?usp=sharing

**Comment by stenzek** [comment] 2022-05-11 09:55
Looking into it, I think this is entirely an issue with your replacements, not the system, so we can close this as invalid.

I couldn't reproduce the text flickering (but that just looks like it switching between normal and replacement textures; make sure you've handled all of them, the hash is probably slightly different).

As for the other broken elements on the screen, those errors are in your textures, not the system. Here's an example:
![image](https://user-images.githubusercontent.com/11288319/167822885-29c19369-08ad-4a1a-bd29-f5acf9c38168.png)

The corruption is present in the .dds files you uploaded.

I also confirmed that the textures dump correctly. Here's the one I was using for testing (`2c4dccf19f225781-71d7736c4416cb41-00005994.png`):
![2c4dccf19f225781-71d7736c4416cb41-00005994](https://user-images.githubusercontent.com/11288319/167823123-7a2adc79-2fbe-48a4-a735-816f86949c25.png)

**Comment by DniweTamp** [comment] 2022-05-11 10:14
I'm aware of corruptions in the dds itself
The font however should he fully replaced
Every letter is each own texture (at least when dumped, not in files), and it gets fully properly replaced in all previous "hacky inaccurate" implementations, as well as P3P on PPSSPP
alpha should be correct too, as it was scaled down using your python script

**Comment by stenzek** [comment] 2022-05-11 10:43
The only "flicker" I saw is when it was async loading the textures for the first time. Once they were loaded, it's fine.

Like I said, this is invalid, the issue is with your replacement textures, not the system.

**Comment by DniweTamp** [comment] 2022-05-11 10:51
Okay then. Are you at least able to upscale and replace text without running into the same issues?

**Comment by stenzek** [comment] 2022-05-11 10:57
I'm not really interested in spending time messing around with textures myself. Got plenty of other more important things to work on.

Like I said, if you can provide replacements (which aren't broken, yours are) that have an issue, I'll look into it, which I've done here, and I cannot reproduce your issue.

**Comment by DniweTamp** [comment] 2022-05-11 11:00
Well, the actual texture corruption we can fix ourselves, that's a non-issue. The only thing I'm concerned about is the font flickering, everything else is a non-issue. And the font textures are fine, no corruptions, no over the limit alpha, they are valid textures. And yet there is still flickering. Just because you checked 1-2 text boxes and it was fine doesn't mean it's a non-issue. Check some dialogue selection boxes, they seem to always introduce the flickering

**Comment by stenzek** [comment] 2022-05-11 11:04
I did check dialogue boxes. But considering you didn't even provide a memory card, if it's specific to one area, I don't really feel like guessing where it is.

**Comment by ZwipZwapZapony** [comment] 2022-05-15 10:57
Does this still happen in v1.7.2747?

**Comment by Scalerize** [comment] 2022-07-28 22:52
i'm using 1.7.3126 and on the 4th floor i get flickering in in some Places too, what fixed it for me was settnig vu to extra + preserve sign

**Comment by Mrlinkwii** [comment] 2023-09-09 16:50
closing  due to lack of response

**Closed by Mrlinkwii** 2023-09-09 16:50 UTC
Labels: Bug
