### ISSUE TITLE
[BUG]: Burnout 3: Texture Replacement "Blue Glaze" when blending accuracy is set to high or above

### ISSUE THREAD

**Issue by expo-B3** [PCSX2/pcsx2#8359] opened 2023-03-09 02:02 UTC
### Describe the Bug

When using the texture replacement feature of PCSX2 on Burnout 3: Takedown, replacing any texture with an image that has transparency enabled (even if there is no actual transparency within the image) will result in a "blue glaze" that is visible on reflective sections of the texture. This is most notable on blending accuracy settings high or above.
![image](https://user-images.githubusercontent.com/124372337/223893599-61fe3f41-d6dd-4988-bc89-af68c0624a0e.png)

### Reproduction Steps

Dump the Red Compact Type 1 Texture. Copy the file and paste it in the replacements folder, make sure the name of the file in replacements matches the name of the dumped texture. Set a toggle texture replacements hotkey and enter the garage. Toggle between blending accuracy modes medium or below and high or above. (This can be done with any vehicle/color, red compact 1 is just an example). Sometimes the replaced texture does not load, to circumvent this, toggle through the color options until you notice the change.

Note that the issue is more visible when you have loaded into a track like golden city. In the garage it is most visible at extreme angles.

### Expected Behavior

Increasing blending accuracy setting increases accurate shader blending without creating a "mirror" or "glaze" type effect.

### PCSX2 Revision

v1.7.4198

### Operating System

Windows 10

### CPU

Ryzen 5 5600X

### GPU

RX Vega 64

### GS Settings

![image](https://user-images.githubusercontent.com/124372337/223896491-de449a12-0638-4a8f-a0ac-8848ccadd68c.png)
![image](https://user-images.githubusercontent.com/124372337/223896520-ac2c614f-f32c-4264-82b6-34b9ce1ce992.png)
![image](https://user-images.githubusercontent.com/124372337/223904342-03c8a021-4a41-4a9e-96c0-7e511488bf54.png)

### Emulation Settings

![image](https://user-images.githubusercontent.com/124372337/223896318-2f635087-b5fb-4729-a10b-9f3e9a7dbde4.png)

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/124372337/223896447-ea690f1f-1eb1-4419-a97d-2c489790537b.png)

**Comment by stenzek** [comment] 2023-03-09 10:29
Can't reproduce, so closing as invalid. Wild guess, you're not scaling the alpha values correctly, see <https://github.com/PCSX2/pcsx2/blob/master/tools/texture_dump_alpha_scaler.py>

FWIW, there is supposed to be a slight blue reflection there, at least ingame (software confirms this).

**Closed by stenzek** 2023-03-09 10:29 UTC
Labels: Bug

**Comment by expo-B3** [comment] 2023-03-09 21:39
> Can't reproduce, so closing as invalid. Wild guess, you're not scaling the alpha values correctly, see https://github.com/PCSX2/pcsx2/blob/master/tools/texture_dump_alpha_scaler.py
> 
> FWIW, there is supposed to be a slight blue reflection there, at least ingame (software confirms this).

Thanks for checking it out, I'll try out the script.
