### ISSUE TITLE
[Feature Request]: AMD FidelityFX™ Super Resolution

### ISSUE THREAD

**Issue by MarcoEstevez** [PCSX2/pcsx2#6209] opened 2022-05-26 22:53 UTC
### Description

As title says, there are quite number of games that have numerous graphical issues when hardware renderers are being used, while software renderer works just perfect or at least better since it is more faithful to the real hardware, for instance, Ace combat series, or Ridge racer V to name some, of course, the drawback is that they play as native resolution, and so I wonder whether [AMD FidelityFX™ Super Resolution](https://www.amd.com/en/technologies/fidelityfx-super-resolution) can be a thing

Even on hardware when people with weak PCs can't afore high resolutions

### Reason

1. Make software renderer prettier.
2. In hardware renderers, fake higher resolution while maintain low hardware requirements, like using 3x (1080) but output at 4k

### Examples

Ace combat series, they don't render properly using hardware backends and higher IR

**Comment by Mrlinkwii** [comment] 2022-05-26 22:54
duplicate of #4649

**Closed** 2022-05-26 22:56 UTC
Labels: Duplicate
