### ISSUE TITLE
[BUG]: [Big Picture] Extra 'confirm' press required most of the time to select an item

### ISSUE THREAD

**Issue by WillySteichen** [PCSX2/pcsx2#10157] opened 2023-10-21 12:48 UTC
### Describe the Bug

As per the title, selecting an item in the big picture interface usually takes an additional 'confirm' press to allow it to register, but not always.
On certain occasions (like when opening big picture mode for the first time, or when you exit big picture mode by closing it through either pressing the 'exit/deny' button, or the pause menu hotkey after pressing the 'confirm' button only once), it will allow you to select something without requiring the additional press, but the additional press requirement will reoccur when you enter big picture mode again.
Pressing space on the keyboard, as well as 'exit/deny' on the controller will work without an additional press.

Happens with both the appimage and the Flatpak builds of PCSX2, as well as DuckStation.

### Reproduction Steps

Automap any controller through SDL to ensure it has been properly mapped, launch any game, enter big picture mode after you've successfully booted the game, select any item in the menu (easiest way to trigger the bug is to select resume, but save or load state also triggers it), enter big picture again and try to select something.

### Expected Behavior

Selecting an item shouldn't require an additional press.

### PCSX2 Revision

v1.7.5139

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Linux Mint 21.2, Steam Deck OS 3.4.10

**Comment by kamfretoz** [comment] 2024-01-07 14:40
Can't reproduce, running Arch Linux with v1.7.5416.

**Comment by WillySteichen** [comment] 2024-01-07 21:18
I can still reproduce it on my end with v1.7.5416 (appimage).

**Comment by TheTechnician27** [comment] 2024-02-03 14:03
Can't reproduce, Manjaro Flatpak v1.7.5539.

**Comment by WillySteichen** [comment] 2024-03-02 16:33
I'm still able to reproduce this issue with v1.7.5590 on both Linux (appimage), and a recently purchased Windows 11 PC.

**Comment by JordanTheToaster** [comment] 2024-03-02 16:37
Can't reproduce on Windows 10 v1.7.5590.

**Comment by WillySteichen** [comment] 2024-03-02 16:42
I've tried both with a Dualsense with SDL, and a Xbox Series controller with Xinput, and I could easily trigger it with both.

**Comment by mateuszklysz** [comment] 2024-03-13 11:25
I have the same issue - in my case, the first input is "transferred" to the game, immediately after resuming. If I click 2x (X) button on the "Resume Game" option, the game resumes and additionally presses the given button in the game itself. 
Each time I'm forced to double-click on the selected option.

I use Dualsense with SDL. Pressing options with the mouse doesn't generate this problem. 
I'm also able to reproduce this in Duckstation.

Operating System: Windows 11
PCSX2 Revision: v1.7.5611

**Closed** 2024-04-13 03:21 UTC
Labels: Bug, GUI/Qt
