### ISSUE TITLE
[BUG]: Database corrections for the rest of the Yamasa Digi World games

### ISSUE THREAD

**Issue by drachenschanze** [PCSX2/pcsx2#6981] opened 2022-09-01 10:12 UTC
### Describe the Bug

Yamasa Digi World 3 - Time Park, King Pulsar, Cyber Dragon (Japan)

![Capture](https://user-images.githubusercontent.com/96800307/187888236-c16aeb52-e5f9-4f4d-81f2-bd83fb75793f.PNG)

http://redump.org/disc/41909/

Yamasa Digi World 4 - Penguin Paradise, Crazy Shaman R, Zakzak Senryoubako R, Destroyer XX, King Pulsar (Japan)

![Capture2](https://user-images.githubusercontent.com/96800307/187888406-247e0e8d-7c92-431c-9b04-08d97e85383f.PNG)

http://redump.org/disc/39262/

Yamasa Digi World SP - Neo Magic Pulsar XX (Japan)

![Capture3](https://user-images.githubusercontent.com/96800307/187888638-45312c6b-b368-4492-9373-511946ce1add.PNG)

http://redump.org/disc/25011/

Yamasa Digi World SP - Neo Planett XX (Japan)

![Capture4](https://user-images.githubusercontent.com/96800307/187888930-5221b99c-e9a3-4748-b97d-90c93cc22c9d.PNG)

http://redump.org/disc/34367/

Yamasa Digi World SP DX - Neo Planett XX (Japan)

![Capture5](https://user-images.githubusercontent.com/96800307/187889100-3a4d9c6a-0ea3-4e8b-b4ff-8cc62e9719c5.PNG)

http://redump.org/disc/72810/

Yamasa Digi World 4 DX: Penguin Paradise, Crazy Shaman R, Zakzak Senryoubako R, Destroyer XX, King Pulsar doesn't show up in the game list at all. Not even as a missing entry.

http://redump.org/disc/46213/

### Reproduction Steps

Look at the game list

### PCSX2 Revision

pcsx2-v1.7.3271-windows-64bit-AVX2-Qt

### Operating System

Windows 10 (64bit)

**Comment by noigeaR** [comment] 2022-09-15 08:05
> Yamasa Digi World 4 DX: Penguin Paradise, Crazy Shaman R, Zakzak Senryoubako R, Destroyer XX, King Pulsar doesn't show up in the game list at all. Not even as a missing entry.

I couldn't reproduce this. SLPS 20257 was in GameDB already and shows up in the game list. Check that your game is not zipped or otherwise corrupt.
You can enable the system console, rescan the games and check the output on the console for errors.

The rest will be fixed once PR #7051 is merged (don't forget to rescan the games for the changes to show up in the game list).

**Closed** 2022-09-15 11:23 UTC
Labels: Bug, GameDB
