### ISSUE TITLE
Metal Gear Solid: Substance Codec background glitch

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#1955] opened 2017-05-28 14:01 UTC
***Game***  
Metal Gear Solid 2: Substance (Europe)
Metal Gear Solid 2: Sons Of Liberty (Europe)

***PCSX2 version:***
pcsx2-v1.5.0-dev-2104-g49840bb-windows-x86

***PCSX2 options:***
"Safest" presets, No hacks, all default settings.

***Bios:***  
SCPH-70004 v12 PAL

***Plugins used:***
Default plugins  
GSdx AVX2/AVX2 1.1.0 (tried with OGL,DX9,DX11 HW/SW)

***GS Dumps***
[Dump 01](http://www49.zippyshare.com/v/9Ngo3pT1/file.html)  
[Dump 02](http://www49.zippyshare.com/v/HdyZmOMp/file.html)

***Description of the issue:***
Codec background have glitches.

***How to reproduce the issue:***  
Load a Save (memory card)
Hit Select button and Codec is display correctly (Dump 01), exit codec.
Now re-enter into codec, and call Otacon, have a dialogue (skip it with triangle button), exit codec.
Now every time the codec is open it display a graphical glitch in background (Dump 02).

***PC specifications:***
- Intel i7-6700K @ 4.00Ghz  
- 32Gb Ram
- Dual Nvidia GTX 1080 (tried with SLI Enabled/Disabled) (Driver Version: 382.05)  
- Windows 10 64Bit  

***Screenshots:***
Here is correct displayed codec on first use:
![gsdx_20170528153031](https://cloud.githubusercontent.com/assets/23509130/26529322/307ce384-43be-11e7-86e7-0267e13a21c4.png)

Here is glitched codec background after talking with Otacon:
![gsdx_20170528153107](https://cloud.githubusercontent.com/assets/23509130/26529328/41c3a542-43be-11e7-9697-d5f7131d1a60.png)

**Comment by MrCK1** [comment] 2017-05-28 14:20
Didn you try manually adjusting CRC hacks?

**Comment by omega64** [comment] 2017-05-28 16:25
I've try some settings, CRC hacks, hardware and software, opengl and dx9 or dx11, in general hacks there is no special fix for this game, on hw hacks i've try some flags, but i never found a working solution for now. :(

**Comment by MrCK1** [comment] 2017-05-28 16:35
Does the effect appear correctly in 1.4.0 stable?

**Comment by omega64** [comment] 2017-05-28 16:39
Yeah at first time i've tried in 1.4.0 stable, and the glitch appears.
So when i open the issue here, the template say it is recommended to try the issue with latest dev build.

**Comment by omega64** [comment] 2017-05-28 17:18
[Here](http://web.archive.org/web/20161006014537/http://wiki.pcsx2.net/index.php/Metal_Gear_Solid_2:_Substance) "LoStraniero1991" who has tested the game to report it in compatibility list, has the same issue with older 1.1.0 version. (i use a web.archive.org to link the wiki because currently is in a shutdown state)
Seems like an old issue never fixed with this game.
I'm not a dev or technical guy so basically i can't help, but i can do my best for troubleshooting the issue,

**Comment by gregory38** [comment] 2017-05-30 14:22
I'm pretty sure the issue is the same as #1339 however if I understand the screenshot correctly, the issue in on the half-top not the half-bottom.

**Comment by omega64** [comment] 2017-05-30 15:00
@gregory38 , sorry i think you have understand wrong, maybe a screenshoot don't explain very well the situation, so i made a short video to help better understand what happen in this issue.

Here is the video: [Metal Gear Solid 2: Substance Codec Glitch PCSX2](https://youtu.be/_TRt9VkDQ5c)

**Comment by gregory38** [comment] 2017-05-30 15:06
It would be easier to tell us which part of the screen is bad. Anyway, as I said there is already a texture cache bug that could explain some corruptions on the half-bottom of the screen.

Note: I think the NTSC version is working correctly (OpenGL)

**Comment by omega64** [comment] 2017-05-30 15:27
For what i can see (and you can see in the [video](https://youtu.be/_TRt9VkDQ5c)) the whole screen is corrupted, it's not about half-top or half-bottom, the glitch cover the entire screen not a part.

**Comment by gregory38** [comment] 2017-05-30 15:53
At time 0:47 is the rendering correct ? Bottom is dark and top got some data (I got that with the dump)

**Comment by omega64** [comment] 2017-05-30 17:09
at [0:47](https://youtu.be/_TRt9VkDQ5c?t=47s) rendering is incorrect, it have a sort of full background texture, i'm not a tech guy (so can't read the dumps), but seems like a cached texture who remains cached incorrectly, and this full background texture only show when codec is open/closed, as you can see after talking with otacon.

correct rendering of codec is at [0:24](https://youtu.be/_TRt9VkDQ5c?t=24s)

i have also try view in first person at [0:48](https://youtu.be/_TRt9VkDQ5c?t=49s) and open the codec to show you it's like a full screen texture who overlay the codec open/close animation, when i press [select] to open the codec, at first the glitchy texture is fullscreen, then it start the codec animation and the texture goes zoomed-in.

i cannot understand what you mean about half-top and half-bottom part, to me for what i can see in the video/gameplay (not the dumps), the background glitchy texture cover all screen size not a part.

Maybe i'm wrong, and the issue is some tech stuff who i can't understand.

**Comment by gregory38** [comment] 2017-05-30 17:17
Yes it is likely a texture cache bug. I can't reproduce it with the dump. I know that MGS got some texture cache bugs (in codec) where it fails to detect an halfscreen offset.

Here a screenshot with the SW renderer of the 2nd dump. 
![screenshot_2017-05-30_19-15-32](https://cloud.githubusercontent.com/assets/1569559/26595633/5db9bda4-456c-11e7-8004-b6a1af1b2b89.png)

Hum, On which renderer did you take the dump ?

**Comment by omega64** [comment] 2017-05-30 23:45
Oh sorry about that,i forgot what exactly GS i have use to take the dumps (i think OGL but not sure), i have tried DX9,DX11,OGL, (SW & HW for all), and every time i switch GS i restart completely the game, to be sure texture are flushed and so on, but i have same result for all GS engines...

**Comment by refractionpcsx2** [comment] 2022-07-10 11:51
Can anybody confirm if this still happens? afaik the codecs are alright

**Comment by JordanTheToaster** [comment] 2023-02-13 14:42
Not an issue as of v1.7.4075.

**Closed** 2023-02-13 14:49 UTC
Labels: Bug
