### ISSUE TITLE
[BUG]: Panzer Elite Action - Fields of Glory (Europe) - Graphical issues on both SW and HW renderer

### ISSUE THREAD

**Issue by HeroponRikiBestest** [PCSX2/pcsx2#4793] opened 2021-09-20 18:36 UTC
### Describe the Bug

On both software rendering and opengl, various graphical issues are visible on your tank, as well as some other models (i.e. soldiers and some fences).

### Reproduction Steps

Simply play the game normally.

### Expected Behavior

I expected all models to be displayed correctly.

### PCSX2 Revision

PCSX2 1.7.0-20210817085737 - compiled on Aug 17 2021

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Linux Mint 20

### CPU

AMD Ryzen 7 PRO 4750U with Radeon Graphics

### GPU

Uses an iGPU, see cpu

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/50224630/134054645-948432d4-8ea2-46d5-aad6-a67c76d24ff5.png)
![image](https://user-images.githubusercontent.com/50224630/134054651-00065be8-8bce-4859-8d48-16773da9a12c.png)
![image](https://user-images.githubusercontent.com/50224630/134054653-6892df1b-3efd-4338-8ce9-a2927d587b8b.png)

![gs_20210920143411](https://user-images.githubusercontent.com/50224630/134055969-c23a5876-f024-4223-ba5b-f876473fd6c6.png)

### Logs & Dumps

Log: [log.txt](https://github.com/PCSX2/pcsx2/files/7197901/log.txt)
GSdump: [gs_20210920143325.gs.zip](https://github.com/PCSX2/pcsx2/files/7197923/gs_20210920143325.gs.zip)

**Comment by refractionpcsx2** [comment] 2021-09-20 18:58
That's an old version of PCSX2, can you please update to the latest development build and retry? Thanks

**Comment by gilderoylockhart01** [comment] 2021-09-20 19:04
This game have the exact same behaviour as Totally Spies. It will need a recent dev build with +3 cyclerate to work properly. The game uses strict m-bit timings to achieve the tank/character rendering.

**Comment by refractionpcsx2** [comment] 2021-09-20 19:21
If that's the case, then this is going to be a "Wont Fix" because there's not much we can do about that, you'll just need to adjust your settings.

**Comment by HeroponRikiBestest** [comment] 2021-09-20 19:39
I have re-tested on the latest build, the issue still remains, and +3 cyclerate does fix it. Also, the debug window thinks I'm running PES 5, but I imagine that's just an issue with them sharing the same serial or something.

**Comment by refractionpcsx2** [comment] 2021-09-20 19:44
> I have re-tested on the latest build, the issue still remains, and +3 cyclerate does fix it. Also, the debug window thinks I'm running PES 5, but I imagine that's just an issue with them sharing the same serial or something.

shouldn't be sharing serials

**Comment by HeroponRikiBestest** [comment] 2021-09-20 20:18
Ah, I looked at the gamedb. It seems that PES5 is incorrectly entered as SLES-53444 (the serial Panzer Elite uses). The serial should be SLES-53544 for PES5 instead.

**Comment by refractionpcsx2** [comment] 2021-09-20 20:29
That's now been fixed, thanks, that obviously went unnoticed!

**Comment by MarcoEstevez** [comment] 2021-09-21 08:05
But is that supposed to be automatically corrected now, sorry for my ignorance, I downloaded latest build, the one with #4796 and log shows that serial matches with database, but game is still broken, then I changed settings to +3 cyclerate and while it corrects model render problems, is too slow for my CPU, running at 25 fps at best

**Comment by refractionpcsx2** [comment] 2021-09-21 09:50
We only fixed the name, we can't automatically set the cycle rate, if you want to do that, you'll need to use a frontend like Spectabis, or just remember to set it.

**Comment by gilderoylockhart01** [comment] 2021-09-21 15:09
Also, it is important to mention the speed impact you are having is caused by GSDX, even on my PC back when I tested the game it made my 3070 having a hard time with it (vram spike).

**Comment by MarcoEstevez** [comment] 2021-09-21 18:19
Thanks for explaining

**Comment by MrCK1** [comment] 2022-03-05 20:10
What is the status of this bug on master @MarcoEstevez

**Comment by Goatman13** [comment] 2023-08-04 14:21
Since  `eeCycleRate: 3` is now a thing in gameDB, maybe this can be added with next DB update. Totally Spies run the same engine, so both games need the same settings. 

I looked into VU0/EE code, and there is no way to rearrange anything to make it more sane without serious rewrite on both EE and VU0 code.

**Comment by refractionpcsx2** [comment] 2023-08-04 14:32
Bummer, thanks for checking!

**Comment by LoStraniero91** [comment] 2024-05-05 13:29
v1.7.5196 caused a regression even with the current gamefix.

**Closed** 2024-05-10 00:39 UTC
Labels: Bug, Voodoo, Timing
