### ISSUE TITLE
[BUG]: Klonoa 2 - White flash after cutscene in Momett House when using software

### ISSUE THREAD

**Issue by Toastarrr** [PCSX2/pcsx2#7884] opened 2023-01-14 10:47 UTC
### Describe the Bug

Visiting Momett House after collecting enough dolls to unlock a new level or feature will play a brief cutscene. On software, this cutscene makes the screen flash white after ending.

The cutscene ends normally on hardware.

### Reproduction Steps

Visit Momett House after collecting enough dolls to unlock something.

### Expected Behavior

The screen should fade to black, then fade back in.

### PCSX2 Revision

PCSX2 Nightly - v1.7.3900

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 2600X Six-Core Processor

### GPU

4095MB NVIDIA GeForce GTX 1080

### GS Settings

Software Renderer

### GS Window Screenshots

![whiteflashscreenshot](https://user-images.githubusercontent.com/68636505/212467850-a4d490c0-d5eb-42a5-adb0-25666ae0f015.png)

### Logs & Dumps

[Google Drive link to GS dump](https://drive.google.com/file/d/1qL1TdKM9BMHx5SJWWBhsCZj4zVHd0cP6/view?usp=sharing)
[emulog.txt](https://github.com/PCSX2/pcsx2/files/10417163/emulog.txt)

**Comment by Toastarrr** [comment] 2023-01-14 12:04
Trying to record this bug using Nvidia ShadowPlay in fullscreen causes the recording to abruptly end and save when the white flash happens.

I don't know exactly what's happening under the hood, but it seems like something in PCSX2 is getting "reset" when this bug occurs.

**Comment by Oymat** [comment] 2023-01-14 12:19
Obviously a regression from removing vu1 clamping for this game.

**Comment by refractionpcsx2** [comment] 2023-01-14 12:38
Can you re-enable extra + sign clamping on VU1 and see if it resolves it? if so I'll put it back on.

**Comment by Toastarrr** [comment] 2023-01-14 12:53
Changing VU1 Clamping Mode to "Extra + Preserve Sign" does not resolve it.

**Comment by refractionpcsx2** [comment] 2023-01-14 12:54
is it resolved if you put it in software mode (F9)

**Comment by Toastarrr** [comment] 2023-01-14 12:57
The bug still happens in software mode. It doesn't happen in hardware regardless of VU1 Clamping setting.

**Comment by refractionpcsx2** [comment] 2023-01-15 15:29
can you record a multiframe GS Dump of one of these transitions? that might be useful.

The hotkeys (which you hold down for the recording period) should be R-Ctrl + R-Shift + F8, but you can modify it in the hotkeys, if you want something easier.

**Comment by Toastarrr** [comment] 2023-01-15 15:40
Here's a GS dump made while using software mode.
[GSdump.zip](https://github.com/PCSX2/pcsx2/files/10420534/GSdump.zip)

What's strange is that the dump file doesn't show the flash even though I saw it while recording. It's the same with the GS dump I posted yesterday.

**Comment by refractionpcsx2** [comment] 2023-01-15 15:50
well, that's annoying...

**Comment by refractionpcsx2** [comment] 2023-01-15 15:52
Okay so is there an easy point from a memcard save we can go to in order to reproduce it? along with some instructions (remember the likelyhood is none of us have played this game)

**Comment by Toastarrr** [comment] 2023-01-15 16:03
The fastest way I know to encounter it is to select Claire Moa Temple from the map, beat the boss by picking up enemies (Square) and throwing them (Square) at the flashing weak point, and then making a save state so you can replay the cutscene at the end.

It's a very short and easy boss, so it's hopefully not too much of a problem.
[Mcd001.zip](https://github.com/PCSX2/pcsx2/files/10420577/Mcd001.zip)

![ClaireMoaTemple](https://user-images.githubusercontent.com/68636505/212551935-8c811ed5-92f7-454a-b9c2-15c4633f8c13.png)

**Comment by refractionpcsx2** [comment] 2023-01-15 16:07
alright, thanks :)

**Comment by Toastarrr** [comment] 2023-01-16 11:37
I've discovered you don't even need to go further than the title screen to see the screen flash white after a fade-to-black

https://user-images.githubusercontent.com/68636505/212667013-148173ef-52f4-4b69-9cf4-b2b4872d2f6b.mp4

https://user-images.githubusercontent.com/68636505/212667019-1b30e3a2-e61e-46dc-b8c9-6fd70585575c.mp4


I discovered the title screen flash while creating a save where the Momett House issue I described in the first post can be seen.

[Mcd001.zip](https://github.com/PCSX2/pcsx2/files/10425191/Mcd001.zip)
To reproduce the bug described at the top of this thread, select Momett House from the map and watch the cutscene in software mode. The Claire Moa Temple instance can also be seen using this save by following the steps in my last post.
![MomettHouse](https://user-images.githubusercontent.com/68636505/212669057-2d05313f-acac-4706-a6c5-a6e774dcedb3.png)

**Comment by Oymat** [comment] 2023-01-20 14:37
i tried to replicate it on the exact same version SLUS-20151, with no luck, it could be caused by his ISO or his BIOS or it could be an amd issue.

**Comment by refractionpcsx2** [comment] 2023-01-20 14:38
I replicated it on the US version by letting the intro run.  Using an Nvidia 2080Ti, so it's not an AMD issue. Also it's a software renderer, so it's very unlikely to be vendor specific.

**Comment by Oymat** [comment] 2023-01-20 14:38
> I replicated it on the US version by letting the intro run. Using an Nvidia 2080Ti, so it's not an AMD issue. Also it's a software renderer, so it's very unlikely to be vendor specific.

Software is rendered on the cpu correct ? i was referring to his AMD Ryzen 5 2600X Six-Core Processor

**Comment by refractionpcsx2** [comment] 2023-01-20 14:40
oh right.. hmm, well I do have a Ryzen CPU. But it seems highly unlikely still.

**Comment by Toastarrr** [comment] 2023-01-31 21:05
This appears to be fixed on the newest build. Not sure what did it, though. Can you still replicate this @refractionpcsx2 ?

**Comment by refractionpcsx2** [comment] 2023-01-31 21:08
Can confirm it was fixed by #8014, nice :)

**Closed by refractionpcsx2** 2023-01-31 21:08 UTC
Labels: Bug, GS: Software
