### ISSUE TITLE
[BUG] Klonoa 2: cutscene inverse color effect does not appear correctly in HW mode

### ISSUE THREAD

**Issue by Igetin** [PCSX2/pcsx2#6727] opened 2022-07-27 19:04 UTC
### Describe the Bug

In Klonoa 2: Lunatea’s Veil, the opening cutscene of Embryo Compass features a sort of layered effect that has a glowing light in the background (the light changes between a few different colors), and a color inversion effect in the foreground. The foreground effect layer is see-through, but everything seen through the effect appears in inverted colors.

When using one of the hardware renderers (OpenGL or Vulkan), the combined effect results incorrectly in a solid (changing) color that prevents seeing behind the foreground effect layer. This issue does **not** come up when using the software renderer.

### Reproduction Steps

1. Run the game using the OpenGL or Vulkan renderer
2. Go to Embryo Compass and watch the opening cutscene
3. The effect renders as a solid color and prevents seeing behind the foreground effect layer

### Expected Behavior

The objects behind the foreground effect layer should be visible and have inverted colors.

### PCSX2 Revision

v1.7.3130

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Fedora 35

### CPU

AMD Ryzen 7 3700X

### GPU

AMD Radeon RX 6800 XT

### GS Window Screenshots

| Hardware (incorrect) | Software (correct) |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/14016863/181343513-be654e56-fc33-4f74-b8f7-db735099d5cc.png" width="300">  | <img src="https://user-images.githubusercontent.com/14016863/181343527-2c3e04a6-ccf3-479d-9883-3308d07802dd.png" width="300">  |
| <img src="https://user-images.githubusercontent.com/14016863/181343685-30d8e55c-96f7-419d-8298-440df61e122a.png" width="300">  | <img src="https://user-images.githubusercontent.com/14016863/181343688-5e2da005-7384-44ce-b453-e64cd56ea1d5.png" width="300">  |
| <img src="https://user-images.githubusercontent.com/14016863/181346814-d1cc4554-45dc-48b1-a61d-cdac9123384a.png" width="300">  | <img src="https://user-images.githubusercontent.com/14016863/181346820-3a4c8eb8-8594-4d5d-a26e-d6d71461efea.png" width="300">  |

##### Hardware (incorrect)

https://user-images.githubusercontent.com/14016863/181350964-c0a7a96e-5698-450d-81ac-23713a76bf81.mp4

##### Software (correct)

https://user-images.githubusercontent.com/14016863/181350995-2535fe31-59e2-43af-9cc9-834586caf18e.mp4

### Logs & Dumps

[GS dump on Google Drive](https://drive.google.com/file/d/1lzS0107kPv7qYM1W_8ECIIzyirdmce4D/view?usp=sharing)

**Comment by refractionpcsx2** [comment] 2022-07-27 19:06
Assuming a duplicate of #6723 or #6720, maybe both.

**Closed by refractionpcsx2** 2022-07-27 19:06 UTC
Labels: Bug

**Comment by refractionpcsx2** [comment] 2022-10-22 22:12
I know this was a dupe n all, but for data's sake, this is resolved if you set your blending accuracy to "full"
