### ISSUE TITLE
[BUG]: Timesplitters Future Perfect SLES-52993

### ISSUE THREAD

**Issue by Parallax71** [PCSX2/pcsx2#9900] opened 2023-09-03 09:52 UTC
### Describe the Bug

As you can see in the attached screenshot, the Sun crosses part of the stage, be it mountains or walls, it is very annoying. This happens in hardware mode, in any renderer, be it Vulkan, OpenGL... etc., in software mode it does not happen.
![TimeSplitters - Future Perfect_SLES-52993_20230903114011](https://github.com/PCSX2/pcsx2/assets/142044650/a1948907-0eb5-4775-8d51-c22873efce40)
[TimeSplitters - Future Perfect_SLES-52993_20230903114011.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/12505653/TimeSplitters.-.Future.Perfect_SLES-52993_20230903114011.gs.zst.zip)

### Reproduction Steps

The quickest way to check this is to choose 1 player, create a profile, choose game mode "Action", and "Team Duel", then choose the map "Vietnam", once the game starts simply advance along the path from the front until going outside.

### Expected Behavior

I hoped the sun wouldn't go through walls and mountains

### PCSX2 Revision

v1.7.4977

### Operating System

Windows 10 (64bit)

### CPU

i7 6700

### GPU

GTX 1070

**Comment by stenzek** [comment] 2023-09-03 09:56
Please use search next time.

Duplicate of https://github.com/PCSX2/pcsx2/issues/8990.

**Closed by stenzek** 2023-09-03 09:56 UTC
Labels: Bug
