### ISSUE TITLE
Burnout 3/R/D: VU1 Interpreter Breaks Various Effects

### ISSUE THREAD

**Issue by escape209** [PCSX2/pcsx2#1851] opened 2017-03-10 23:46 UTC
***PCSX2 version:***
1.5.0-dev-1921

***PCSX2 options:***
* VU1 set to Interpreter for the first screenshot
* VU1 set to MicroVU Recompiler for the second screenshot 

***Plugins used:***
GSdx D3D11 SW.

***Description of the issue:***
When VU1 is set to Interpreter, many of the effects become broken. One of those effects is the cars' exhaust fumes. An observation I made is that the result of setting VU1 to Interpreter is identical to what happens if you use MicroVU Recompiler and set the VU rounding mode to Positive, so it's probably a rounding issue.

![gsdx_20170310232535](https://cloud.githubusercontent.com/assets/8225831/23817348/5c576932-05ea-11e7-9862-f5e8665c6b95.png)
MicroVU Recompiler

![gsdx_20170310232550](https://cloud.githubusercontent.com/assets/8225831/23817387/a007a32c-05ea-11e7-818a-5cbce5345b8b.png)
Interpreter

***How to reproduce the issue:***
1. Get into a race.
2. Go to Config > Emulation Settings > VUs and set VU1 to Interpreter.

***Last known version to work:***
This behaviour has always been present AFAIK.

***PC specifications:***
CPU: Intel i5-6400
GPU: AMD Radeon HD 7770
RAM: 4GB DDR4 @ 2133MHz
OS: Windows 10 x64

**Comment by refractionpcsx2** [comment] 2017-03-11 11:08
The interpreter is quite broken and pretty much abandoned, it shouldn't be used for regular playing.

**Comment by DisorderIy** [comment] 2017-03-11 16:51
@refractionpcsx2 I was going to post a screenshot for MicroVU with positive rounding, but didn't, since it would've been the same as the interpreter screenshot.

But I see what you mean, so I'll close this.

**Comment by ssakash** [comment] 2017-03-11 17:10
A bug is still a bug, reopening it. Also it's a shame for an interpreter to have a bug which doesn't exist on the recompiler, most people use the interpreter for reference. :P

**Comment by refractionpcsx2** [comment] 2017-03-11 17:38
It's probably not a bug, the interpreter is completely broken, there's LOTS of bugs.  Nobody uses the VU Interpreter for reference :P

**Comment by gregory38** [comment] 2017-03-11 18:21
It would be nice to have a very accurate implementation of VU. I.e. software float

**Comment by refractionpcsx2** [comment] 2017-03-11 18:54
The biggest problem is we haven't implemented all the tricks and hacks that are in the recompilers. I have implemented a few in recent years (like delayed VI's on branches) which has improved things somewhat, but there is still lots of problems.

**Comment by woj1993** [comment] 2017-03-11 21:46
@refractionpcsx2 @gregory38 @ssakash Most people will try interpreter as tool to fix game or check is bug on CPU (recompiler) or GPU (graphic plugin) part because in many emulator interpreter is slowest but most compatible option. It doesn't help we inform user that VU1 interpreter is bugged in text help because if user knows how any other emulator he probably won't wait these 5 second. Even I was thinking that if something won't work to try it on interpreter. We should inform user that this option is broken renaming it from Interpreter to Interpreter (dropped) or Interpreted (broken).

P.S. We should fix it also when there will be enough time.

**Comment by refractionpcsx2** [comment] 2017-03-12 13:31
@woj1993 maybe so, but none of the interpreters in PCSX2 have worked properly in some time.

**Closed** 2021-09-12 15:12 UTC
Labels: Bug, Vector Units, Interpreter
