### ISSUE TITLE
007: From Russia with Love - oringe verticle lines

### ISSUE THREAD

**Issue by Levan7** [PCSX2/pcsx2#3951] opened 2020-11-27 19:37 UTC
Using PCSX2 1.7.0-20201127075728 - compiled on Nov 27 2020 build on w10 x64

In the beginning of the first mission origen vertical lines appear

Using default speed settings appears on dx11 and opengl

![vid](https://user-images.githubusercontent.com/5770076/100480004-786fed80-3109-11eb-9946-2864cb12b119.gif)

GS dump
[snaps.zip](https://github.com/PCSX2/pcsx2/files/5609359/snaps.zip)
emulog
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/5609358/emuLog.txt)

**Comment by MrCK1** [comment] 2020-11-27 19:38
Duplicate of https://github.com/PCSX2/pcsx2/issues/3875. Closing

**Closed by MrCK1** 2020-11-27 19:38 UTC
