### ISSUE TITLE
Metal Gear Solid 2: Sons of Liberty (U) locker door issue in SW mode.

### ISSUE THREAD

**Issue by levonnn** [PCSX2/pcsx2#3295] opened 2020-03-20 10:32 UTC
**pcsx2-v1.5.0-dev-3391-gbf9519433-7012-vs2019-Win32**

**PCSX2 options:**
Native resolution. Tried various settings. Works fine in OGL HW, the problem happens in SW mode.

**Screens:
OGL  HW:**
![](https://i.imgur.com/CX7DaR6.png)

**OGL SW:**
![](https://i.imgur.com/YBXLpm5.png)

**gsdx snap:**
https://filebin.net/etqqpw2feciivxr4

**How to replicate the problem:**
Get into a locker.

**PC specifications:**
i7 2700, GTX 760, Windows 7 64 Bit

**Comment by Muhlawor** [comment] 2020-04-21 21:57
Same

**Comment by prafullpcsx2** [comment] 2020-05-24 11:59
Upload gsdump on github itself. Filebin uploads expire within a week and so are of no use. Same applies to your other issue.

**Comment by lightningterror** [comment] 2020-06-07 11:52
Can latest dev build be retested?

**Comment by prafullpcsx2** [comment] 2020-06-07 12:12
![gsdx_20200607173459](https://user-images.githubusercontent.com/12788199/83968300-e0c1dd00-a8e5-11ea-86ad-f77818ede165.png)

Still the same. Attaching a gsdump as original one expired.
[mgs2 sw mode problem.zip](https://github.com/PCSX2/pcsx2/files/4742028/mgs2.sw.mode.problem.zip)

**Comment by Mrlinkwii** [comment] 2022-05-10 11:45
Still an issue on 1.7.2730.

**Comment by stoniemahonie** [comment] 2023-01-11 14:36
SW v1.7.3879 Compiled on Jan 10 2023

![Metal Gear Solid 2 - Sons of Liberty_SLUS-20144_20230111153213](https://user-images.githubusercontent.com/13390608/211832643-1b5d2b38-30a2-4364-bd02-02a23427743e.png)

HW (3x Native) v1.7.3879 Compiled on Jan 10 2023


![Metal Gear Solid 2 - Sons of Liberty_SLUS-20144_20230111153440](https://user-images.githubusercontent.com/13390608/211833234-8b2b35b7-5626-45de-b9d2-2f6483df76b3.png)

**Comment by refractionpcsx2** [comment] 2023-01-11 14:42
Still broken here

![image](https://user-images.githubusercontent.com/6278726/211834941-fdc140ce-efd0-4b5c-9c18-5b9b7930a904.png)

What CPU do you have, @stoniemahonie ? and was it AVX2 to SSE4 version of PCSX2 you used?

**Comment by bslenul** [comment] 2023-01-11 15:39
> SW v1.7.3879 Compiled on Jan 10 2023

Move the camera around, if you don't move at first it looks like it's fine (although you can already see some kind of horizontal lines, just like on your SW screenshot):

![image](https://user-images.githubusercontent.com/33353403/211846950-161f1a28-f0be-49f6-a37b-b17632ae011a.png)

But then if you move the camera the glitches start to appear:

![image](https://user-images.githubusercontent.com/33353403/211847053-869b7fee-ab3e-422c-a271-1f657976dd19.png)

**Comment by LoStraniero91** [comment] 2023-03-16 18:40
This bug occurs also on other surfaces, like the shadow around this light.

**![image](https://user-images.githubusercontent.com/29802222/225720864-c28e0d9a-a02c-43b4-9e88-e483d7061435.png)**

**Comment by rangiTM** [comment] 2023-04-19 08:10
I could reproduce the bug in v1.7.4397 with anti-blur hacks on. It could be fixed by turning anti-blur off.

**Comment by refractionpcsx2** [comment] 2023-04-19 08:17
Still broken for me with anti-blur off. you sure you didn't hot switch to software then turn off anti-blur? cos that goes back to hw mode.

**Comment by kohmaeda** [comment] 2023-04-19 10:11
That’s exactly what I did. Sorry for the false lead!

**Comment by Mrlinkwii** [comment] 2023-10-16 22:18
still an issue as of 1.7.5122 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/577a6048-1ce7-4f1e-a734-98aaea08e5a7)

**Comment by TheTechnician27** [comment] 2024-04-14 23:05
[Metal Gear Solid 2 - Sons of Liberty_SLUS-20144_20240414175723.zip](https://github.com/PCSX2/pcsx2/files/14972415/Metal.Gear.Solid.2.-.Sons.of.Liberty_SLUS-20144_20240414175723.zip)

Link asked for a new GS dump, so I've provided two here in two different lockers (just in case different backgrounds could somehow play into this). Has this been tested on original hardware?

**Comment by bslenul** [comment] 2024-04-15 00:01
Still broken for me (1.7.5704), make sure to move the camera around once in a locker, or the glitch might not be visible:

![Metal Gear Solid 2 - Substance_SLUS-20554_20240415014656](https://github.com/PCSX2/pcsx2/assets/33353403/71400571-29c3-4e23-8c15-5af7fa78a0fc)

[Metal Gear Solid 2 - Substance_SLUS-20554_20240415014656.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/14972589/Metal.Gear.Solid.2.-.Substance_SLUS-20554_20240415014656.gs.zst.zip)

**Closed** 2024-05-15 17:13 UTC
Labels: Bug, GS: Software
