### ISSUE TITLE
[GSdx] Rogue Galaxy (any version) has wrongly colored text

### ISSUE THREAD

**Issue by piorrro33** [PCSX2/pcsx2#1333] opened 2016-04-30 20:52 UTC
-PCSX2 version: any, tested with latest master and 1.3.0.

-PCSX2 options: Safest, no speedhacks, all settings set to the best accuracy possible.

-Plugins used: GSdx, SPU2-X, LilyPad, Gigaherz CDVD, the rest are null plugins.

-Plugin settings: Tested with all renderers.

-Description: When using HW renderers, some text is emulated in black while it should be white.
Bad: http://a.pomf.cat/igcefr.png
Good (SW/OGL HW with blending unit acc full/ultra): http://a.pomf.cat/ukhvvz.png

-How to replicate: Set your renderer to OGL/D3D11/D3D9 HW (if using OGL HW set blending unit accuracy to anything but full/ultra). Boot the game, select continue, enjoy.

-Last known version to work: Probably never worked fine. Tried with 1.3.0 and worked fine with Blending Unit Accuracy set to High.

-PC specifications : Intel Core i7-4790 @ 3.60 GHz (working with turbo mode at 4 GHz); ASUS GeForce GTX 750 Ti 2GB

Tested with Rogue Galaxy NTSC-U but I have all the ISOs so I can try with the other ones if needed.

**Comment by prafullpcsx2** [comment] 2016-04-30 21:18
It should work fine with Blending Unit Accuracy set to full.

**Comment by piorrro33** [comment] 2016-04-30 21:21
That is what I meant. It just won't emulate correctly without it.

**Comment by prafullpcsx2** [comment] 2016-04-30 21:22
What's the fps difference between old "high" and new "full" ?

**Comment by piorrro33** [comment] 2016-04-30 21:23
Without framelimiter it's 40 FPS more-or-less, IIRC.

**Comment by gregory38** [comment] 2016-04-30 21:30
What is your issue exactly? D3D is deprecated.

**Comment by piorrro33** [comment] 2016-05-01 06:19
The issue is that the text isn't properly emulated (== black) if Blending Unit Accuracy is set to anything other than Full or Ultra, while a few versions ago it was working fine when it was set to High.

**Comment by bositman** [comment] 2016-05-01 10:09
I don't recall it ever working with anything below Full, can you point us the version that worked with high?

**Comment by piorrro33** [comment] 2016-05-01 11:17
@bositman I just checked on 1.5.0-dev-44 and it works fine with High.

**Comment by gregory38** [comment] 2016-05-01 12:45
Could you generate me a gs dump of those letters so I can give it a look. However old behavior could be wrong, and the new one correct.

**Comment by piorrro33** [comment] 2016-05-01 13:56
GS dump: https://mega.co.nz/#!pV0BBapY!kSA9AQd76tpSTrEMV73JmN3QIG9Mf_exiiHoiMNUaBk

**Comment by gregory38** [comment] 2016-05-01 14:50
Here some explanation, first implementation process all sprites as accurate blending. New implementation limit to GS draw call that will cost less than 100 GPU draw call. If it require more 
Rogue will requires 350 GPU draw call.
```
Without framelimiter it's 40 FPS more-or-less, IIRC.
```
What is the base level fps. 10 +/- 40 isn't the same as 150 +/- 40.

**Comment by piorrro33** [comment] 2016-05-01 15:00
When using High, in this screen I'm around 313 FPS while when I'm using Max, I'm around 225 FPS, so it's a loss of 88 FPS. So okay I understand what this means, thanks for the explanation.

**Comment by gregory38** [comment] 2016-05-01 15:08
I can put a limit of 350 draw call in high. However for this screen, perf will be the same as max. As everything is renderer with sprite. It would be interesting to have fps value in game.

**Comment by piorrro33** [comment] 2016-05-01 15:58
FPS value?

**Comment by gregory38** [comment] 2016-05-01 15:59
What speed do you have when you render real 3d stuff in the game. Because 2D menu are always fast and light.

**Comment by bositman** [comment] 2016-05-01 16:37
I found another game (Life Line) with the same exact issue, not sure if I mind having blending on full

**Comment by gregory38** [comment] 2016-05-01 16:49
Please give me a dump

**Comment by bositman** [comment] 2016-05-01 17:12
Here you go: http://bositman.pcsx2.net/dumps/lifeline_blending_letters.rar

**Comment by gregory38** [comment] 2016-05-01 20:53
The game render letters with triangles. I'm afraid that we need to cope with hardware limitation.

**Comment by vsub** [comment] 2016-05-01 22:24
@piorrro33 
> When using High, in this screen I'm around 313 FPS while when I'm using Max, I'm around 225 FPS, so it's a loss of 88 FPS. So okay now I understand what this option means, thanks for the explanation.

I have almost the same pc(i7 4771,GTX750TI)but on that screen,I can't get more than 195fps while using the latest beta and only the recommended hacks...and native resolution.
Maybe you are using certain pcsx2/gsdx version with certain settings...or maybe you are looking at the percentage and post it as a fps(195fps is around 330%)

Also on that screen,I don't get any speed difference(5 at max)between none and ultra blending accuracy.

And also,using anything other than none,makes a bug a lot more visible(using native doesn't help and it's almost visible in sw mode too)

1.Some fade in/out semi transparent highlighting...exist only in OGL mode(including OGL SW mode)...barely visible only while using None BUA

2.Always visible...to a different extent depending on the rendering mode(even at native/sw mode)

![123](https://cloud.githubusercontent.com/assets/5032540/14944667/265cbf2c-1003-11e6-8795-516dc0fec5e8.jpg)

**Comment by piorrro33** [comment] 2016-05-02 05:33
Hi,
I dear you I was looking at the FPS, not at the percentage. I'm going to 
check again when I'll be home (in around 6 hours) but I'm pretty sure I was 
right.
By the way I wasn't using any speedhack and my game was running in native 
resolution. The only hack I enabled was a GSdx HW hack called Preload Data 
Frame which fixes the bad textures with water, but that's it. I'm using 
GSdx with AVX2 btw, so that might be why you're not having as many FPS, but 
I might be plain wrong.

**Comment by vsub** [comment] 2016-05-02 05:48
I also used the AVX2 version and btw the memory cards selection screen,where is this...from the title screen=>continue or entering a save point?

From the title screen(where there is no music)without speedhacks,I also get around 330fps(max 620 with the recommended speed hacks)
From a save point without speedhack around 155fps and with them 195fps

**Comment by bositman** [comment] 2016-05-02 09:56
Lol thanks to @piorrro33 it seems that Preload Data Frame does indeed fix the rainbow colored water, great :D Although I have to confirm the bugs vsub noted as well. Maybe create a new issue for em

**Comment by gregory38** [comment] 2016-05-02 10:52
```
(including OGL SW mode)
```
Is 1 also broken in SW?

For 2, do you have any hack enabled (included preload data frame).

**Comment by vsub** [comment] 2016-05-02 11:53
1.Actually it's fine in OGL SW mode(pressing F9 doesn't change the combobox with the renderers and I may though that I'm still using OGL SW but I'm actually using OGL HW)
OGL HW:
None - visible(if you move the camera slowly at that save point(Rosa Near the Church)you will see semi transparent white squares blinking on certain places and fade in/out which looking at them without moving the camera)
Minimal to Ultra - more visible than none but the visibility amount is the same on all modes 

2.No,native resolution,OGL HW,Partial\Full CRC,None BUA,Accurate Date on/off...it becomes more visible at 2x scaling and above
![32132](https://cloud.githubusercontent.com/assets/5032540/14953728/ffb3199e-1074-11e6-9672-23a48a0e31dd.jpg)

While using None BUA,those are also visible but a lot less and they become even less visible while using anything above native but problem 2 start to become more visible

**Comment by bositman** [comment] 2016-05-02 11:57
You are using AF, tried disabling it?

**Comment by vsub** [comment] 2016-05-02 12:00
Hmm,yes,setting AF to off fixes problem 1

**Comment by piorrro33** [comment] 2016-05-02 15:17
@vsub Yeah I was benchmarking from the load menu after the title screen, that explains why we didn't have the same results.
About these issues, N°1 seems to be fixes with native resolution from what I read, I'll go check N°2 when I'll be able to access my computer. 

@bositman Yeah I've been searching for a workaround for a while and I'm quite proud I found it! ^^

**Comment by turtleli** [comment] 2016-05-02 15:33
@vsub I think the Windows GSdx GUI needs updated so that it doesn't disable AF for OGL when 8-bit textures is enabled.

**Comment by piorrro33** [comment] 2016-05-02 15:52
@vsub I just checked on my real copy of the game on PS2 and it seems like N°2 is not a bug, since it is present on PS2 as well.

**Comment by vsub** [comment] 2016-05-02 16:55
I clear that game 2 or 3 times on my PS2 and that black thing definitely is not there.

It's seems Texture Filtering has something to do with it
OGL HW,TF off and using native - it's like 2 or 3% visible(you have to look really hard to see it)
OGL HW,TF off,anything above native - weird black lines at the bottom and right

OGL HW,TF Bilinear(PS2) and using native - the black is replaced by semi transparent white
OGL HW,TF Bilinear(PS2),anything above native - weird black lines at the bottom and right

DX9/11 HW,TF off and using native - the problem is not visible
DX9/11 HW,TF off,anything above native - the problem is not visible

DX9/11 HW,TF Bilinear(PS2) and using native - fade in/out white lines
DX9/11 HW,TF Bilinear(PS2) and anything above native -- faster fade in/out white lines

And btw,using forced texture filtering makes problem 1 to look extra bad even with AF disabled...especially at native

**Comment by piorrro33** [comment] 2016-05-02 17:21
Oh okay now I clearly see what you meant and now that I look at it, it's not on my screen. Might want to make a separate issue since we're getting a little bit off-topic.

**Comment by gregory38** [comment] 2017-03-13 18:14
Initial issue was related to accurate blending. Yes I know it is slow but we can't do better with current GPU  limitation.

So I close it with the previous limitation.

**Closed by gregory38** 2017-03-13 18:14 UTC
Labels: Fixed in openGL
