### ISSUE TITLE
GSdx-TC: Misdetection of texture shuffle

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#2449] opened 2018-05-23 18:50 UTC
***PCSX2 version:***
v1.5.0-dev-2388

***Description of the issue:***
Currently Big Mutha Truckers experiences vertical stripes that aren't properly rendered across HW renders.
The Texture cache detection is not handled properly.

GL debug log.
```
T:Oth    ID:627    S:Cache    => TC: Lookup Target(Color) 1280x1024, hit: 2 (0x0, C_16)
T:Oth    ID:627    S:Cache    => TC: dst Color hit (full): 142 (0x1400, C_16)
T:Error    ID:627    S:Mid    => FBMASK SW emulated fb_mask:3fff on 16 bits format
T:Oth    ID:627    S:Cache    => TC: Remove Src Texture: 141 (0x0)
```
Full log
[GSdx_opengl_debug_hw.zip](https://github.com/PCSX2/pcsx2/files/2032573/GSdx_opengl_debug_hw.zip)

Raw dump texture name with the effect.
_00627_f5001_rt1_00000_C_16

***Workaround:***
Currently there is a CRC hack in place to skip the bad draw calls but the idea is to one day properly detect the effect.

***Preview:***
![gsdx_20180509172752](https://user-images.githubusercontent.com/18107717/40444718-56da570a-5eca-11e8-8539-1f699395200e.png)

***Dump:***
[Big Mutha Truckers.gs.zip](https://github.com/PCSX2/pcsx2/files/2032434/Big.Mutha.Truckers.gs.zip)

Related issue https://github.com/PCSX2/pcsx2/issues/1339

**Comment by gregory38** [comment] 2018-05-23 19:27
It would be nice to put more gl log in particular for buffer @ 0x0 and 0x1400. So I can understand what is the issue.

**Comment by lightningterror** [comment] 2018-05-23 19:43
Is this enough ?

https://pastebin.com/34fUevLX

**Comment by gregory38** [comment] 2018-05-23 20:31
Is it the start of the log. The issue is first access to 0x1400 is 16 bits.

I think we can use the following heuristic to detect the effect (GSRendererHW)
* Texture and frame are at same location
* Texture and frame are 16 bits
* Fbmask is 0x3fff (typical value of tex shuffle)
(Or a crc hack :p)

**Comment by gregory38** [comment] 2018-05-23 20:43
On 2nd thought, main issue is the miss. Texture will be invalid even if we detect the effect.
My guess is that 0x1400 should be a part of 0xa00 (bottom ?)

**Comment by lightningterror** [comment] 2019-02-26 18:34
Gaelic Games Hurling and Gaelic Games Football 2 to add to the list. Both PAL.

**Comment by MrCK1** [comment] 2019-02-26 18:36
You'll have to add James Bond From Russia With Love. Half screen and/or stripes on all HW renderers.

**Comment by lightningterror** [comment] 2019-02-26 18:37
Sonic Unleashed as well. Half screen plus vertical stripes.

**Comment by tadanokojin** [comment] 2019-12-22 11:10
This a meta for TC issues?
If so edit top message with checkbox of games affected.

**Comment by refractionpcsx2** [comment] 2022-05-09 17:56
Looks fine now

![image](https://user-images.githubusercontent.com/6278726/167469121-006a8f59-37bf-4cc5-83f5-30506c8c8d9b.png)

**Closed by refractionpcsx2** 2022-05-09 17:56 UTC
Labels: GS: Hardware, GS: Texture Cache
