### ISSUE TITLE
[BUG]: Growlanser 5 & 6 - "Preload Frame Data" HW Hack not working since pcsx2-v1.7.2908

### ISSUE THREAD

**Issue by Risae** [PCSX2/pcsx2#6797] opened 2022-08-07 14:50 UTC
### Describe the Bug

Growlanser 5 and 6 suffers from this bug: #4925

It used to be possible to activate the Hardware Hack called `Preload Frame Data` to fix this issue, but since `pcsx2-v1.7.2908` #5349 this does not work anymore. I tested the up-to-date `pcsx2-v1.7.3180-windows-64bit-AVX2-wxWidgets` and the issue still persists.

### Reproduction Steps

Play Growlanser 5 or 6 using `pcsx2-v1.7.2908` and enable the `Preload Frame Data` hack. The issue is not present in `pcsx2-v1.7.2907`.

### Expected Behavior

The hack works as it did in pre `pcsx2-v1.7.2908`.

### PCSX2 Revision

`pcsx2-v1.7.3180-windows-64bit-AVX2-wxWidgets`

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 2700X

### GPU

RTX 2070

### GS Settings

Default settings with Preload Frame Data Hack manually enabled.

### Emulation Settings

Default settings with Preload Frame Data Hack manually enabled.

### GS Window Screenshots

Growlanser 5 US using `pcsx2-v1.7.2907` with `Preload Frame Data` enabled:
![gs_20220807163826_Growlanser - Heritage of War _NTSC-U__SLUS-21571](https://user-images.githubusercontent.com/37260321/183296261-4c031e37-f9b3-4dc6-916e-8cc179e4a516.png)

Growlanser 5 US using `pcsx2-v1.7.2908` with `Preload Frame Data` enabled:
![gs_20220807164027_Growlanser - Heritage of War _NTSC-U__SLUS-21571](https://user-images.githubusercontent.com/37260321/183296390-88495904-2414-4d2d-a42e-1ff574d09f5e.png)

Growlanser 5 US using `pcsx2-v1.7.3180` with `Preload Frame Data` enabled:
![Growlanser - Heritage of War _NTSC-U__SLUS-21571_20220807164242](https://user-images.githubusercontent.com/37260321/183296522-d8044eb0-ddec-4e2d-b67d-7d343c45012c.png)

### Logs & Dumps

GS Dump:
[Growlanser - Heritage of War _NTSC-U__SLUS-21571_20220807164518.gs.zip](https://github.com/PCSX2/pcsx2/files/9276981/Growlanser.-.Heritage.of.War._NTSC-U__SLUS-21571_20220807164518.gs.zip)

PCSX2 Log:
[log.txt](https://github.com/PCSX2/pcsx2/files/9276987/log.txt)

**Comment by iMineLink** [comment] 2022-08-19 12:37
It looks like the game is using a double buffer technique.
In short terms the issue is caused by a buffer copy which is not properly emulated in HW due to its strange in-game implementation, and before #5349 this was hidden with the preload frame hack activated.

The game uses the depth buffer at 0x1c00 and color buffers at 0x0 and 0xe00 at even and odd frames for rendering the main scene and presenting.
At a certain point during a frame, the game has drawn a backup copy of the depth buffer in the color buffer.
It will now copy the data back from the color buffer to the depth buffer at 0x1c00 using a sequence of small moves (all in the same draw).
This cannot be yet emulated correclty in HW.
The moves happen in SW (beware that at least we are lucky, by chance the color target is fully readback in InvalidateLocalMem so the sequence of SW moves succeed).
Before #5349 the depth buffer at 0x1c00 was trashed as soon as the first move hits it.
So when later it was referenced for the character draw, it would be reloaded from the gs memory where it was copied back as a byproduct of the first move operation.
Now instead it is kept but only a small fraction of it is marked dirty (#5349 does not detect all the overlapping writes but tries to detect more of them) so only a small rectangle is re-uploaded later (32,16 => 40,24).
It is thus fully black because the depth buffer at 0x1c00 is cleared at the beginning of the draw.
Actually this sequence of moves should better be high-level emulated with a single stretch rect from the color buffer at 0x0/0xe00 and the depth buffer at 0x1c00; this would preserve the upscaling and improve the performances.
An OI hack to do this job in the hw renderer would fit perfectly here.

```
T:Oth	ID:22	S:Cache	=> TC: Lookup Source <0,0 => 128,128> (0x32c0, P_8, BW: 2)
T:Oth	ID:22	S:Cache	=> TC: src miss (0x32c0, 0x3eb4, P_8)
T:Oth	ID:22	S:Cache	=> TC, 1024-bit PaletteMap (Size 20): Added new palette.
T:Error	ID:22	S:Mid	=> Target size for 0 8 0: 512x448
T:Oth	ID:22	S:Cache	=> TC: Lookup Target(Color) 512x448, hit: 4 (0x0, C_32)
T:Oth	ID:22	S:Cache	=> Move! 0x0 W:1 F:C_32 => 0x1c00 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x0, 1, C_32) r(0, 0 => 32, 16)
T:Perf	ID:22	S:	=> TC: Read Back Target: 4 (0x0)[fmt: 0x0]. Size 512x448
T:Oth	ID:22	S:Cache	=> TC: ComputeSurfaceOffset - Cached HIT element (size 1), [B] BW 8, PSM Z_32, BP 0x1c00 (END 0x29e7) + OFF <32,16 => 40,24> ---> [A] BP 0x1c00 (END: 0x1c1f).
T:Oth	ID:22	S:Cache	=> TC: Dirty in the middle [aggressive] of Target(Depth) 5 [PSM:Z_32 BP:0x1c00->0x29e7 BW:8 rect(32,16=>40,24)] write[PSM:C_32 BP:0x1c00 BW:1 rect(0,0=>64,32)]
T:Oth	ID:22	S:Cache	=> Move! 0x0 W:1 F:C_32 => 0x1c00 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x0, 1, C_32) r(0, 16 => 32, 32)
T:Perf	ID:22	S:	=> TC: Read Back Target: 4 (0x0)[fmt: 0x0]. Size 32x16
T:Oth	ID:22	S:Cache	=> TC: Dirty in the middle [aggressive] of Target(Depth) 5 [PSM:Z_32 BP:0x1c00->0x29e7 BW:8 rect(32,16=>40,24)] write[PSM:C_32 BP:0x1c00 BW:1 rect(0,0=>64,32)]
T:Oth	ID:22	S:Cache	=> Move! 0x0 W:1 F:C_32 => 0x1c00 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x0, 1, C_32) r(32, 0 => 64, 16)
T:Perf	ID:22	S:	=> TC: Read Back Target: 4 (0x0)[fmt: 0x0]. Size 32x16
T:Oth	ID:22	S:Cache	=> TC: Dirty in the middle [aggressive] of Target(Depth) 5 [PSM:Z_32 BP:0x1c00->0x29e7 BW:8 rect(32,16=>40,24)] write[PSM:C_32 BP:0x1c00 BW:1 rect(0,0=>64,32)]
T:Oth	ID:22	S:Cache	=> Move! 0x0 W:1 F:C_32 => 0x1c00 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x0, 1, C_32) r(32, 16 => 64, 32)
T:Perf	ID:22	S:	=> TC: Read Back Target: 4 (0x0)[fmt: 0x0]. Size 32x16
T:Oth	ID:22	S:Cache	=> TC: Dirty in the middle [aggressive] of Target(Depth) 5 [PSM:Z_32 BP:0x1c00->0x29e7 BW:8 rect(32,16=>40,24)] write[PSM:C_32 BP:0x1c00 BW:1 rect(0,0=>64,32)]
T:Oth	ID:22	S:Cache	=> Move! 0x20 W:1 F:C_32 => 0x1c20 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x20, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0x20 W:1 F:C_32 => 0x1c20 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x20, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0x20 W:1 F:C_32 => 0x1c20 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x20, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0x20 W:1 F:C_32 => 0x1c20 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x20, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0x40 W:1 F:C_32 => 0x1c40 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x40, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0x40 W:1 F:C_32 => 0x1c40 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x40, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0x40 W:1 F:C_32 => 0x1c40 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x40, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0x40 W:1 F:C_32 => 0x1c40 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x40, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0x60 W:1 F:C_32 => 0x1c60 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x60, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0x60 W:1 F:C_32 => 0x1c60 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x60, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0x60 W:1 F:C_32 => 0x1c60 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x60, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0x60 W:1 F:C_32 => 0x1c60 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x60, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0x80 W:1 F:C_32 => 0x1c80 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x80, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0x80 W:1 F:C_32 => 0x1c80 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x80, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0x80 W:1 F:C_32 => 0x1c80 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x80, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0x80 W:1 F:C_32 => 0x1c80 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0x80, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xa0 W:1 F:C_32 => 0x1ca0 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xa0, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xa0 W:1 F:C_32 => 0x1ca0 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xa0, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xa0 W:1 F:C_32 => 0x1ca0 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xa0, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xa0 W:1 F:C_32 => 0x1ca0 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xa0, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xc0 W:1 F:C_32 => 0x1cc0 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xc0, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xc0 W:1 F:C_32 => 0x1cc0 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xc0, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xc0 W:1 F:C_32 => 0x1cc0 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xc0, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xc0 W:1 F:C_32 => 0x1cc0 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xc0, 1, C_32) r(32, 16 => 64, 32)
.... it goes on for hundreds of lines ....
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xcc0, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xcc0 W:1 F:C_32 => 0x28c0 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xcc0, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xce0 W:1 F:C_32 => 0x28e0 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xce0, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xce0 W:1 F:C_32 => 0x28e0 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xce0, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xce0 W:1 F:C_32 => 0x28e0 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xce0, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xce0 W:1 F:C_32 => 0x28e0 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xce0, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xd00 W:1 F:C_32 => 0x2900 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd00, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xd00 W:1 F:C_32 => 0x2900 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd00, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xd00 W:1 F:C_32 => 0x2900 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd00, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xd00 W:1 F:C_32 => 0x2900 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd00, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xd20 W:1 F:C_32 => 0x2920 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd20, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xd20 W:1 F:C_32 => 0x2920 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd20, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xd20 W:1 F:C_32 => 0x2920 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd20, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xd20 W:1 F:C_32 => 0x2920 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd20, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xd40 W:1 F:C_32 => 0x2940 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd40, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xd40 W:1 F:C_32 => 0x2940 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd40, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xd40 W:1 F:C_32 => 0x2940 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd40, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xd40 W:1 F:C_32 => 0x2940 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd40, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xd60 W:1 F:C_32 => 0x2960 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd60, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xd60 W:1 F:C_32 => 0x2960 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd60, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xd60 W:1 F:C_32 => 0x2960 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd60, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xd60 W:1 F:C_32 => 0x2960 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd60, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xd80 W:1 F:C_32 => 0x2980 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd80, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xd80 W:1 F:C_32 => 0x2980 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd80, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xd80 W:1 F:C_32 => 0x2980 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd80, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xd80 W:1 F:C_32 => 0x2980 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xd80, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xda0 W:1 F:C_32 => 0x29a0 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xda0, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xda0 W:1 F:C_32 => 0x29a0 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xda0, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xda0 W:1 F:C_32 => 0x29a0 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xda0, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xda0 W:1 F:C_32 => 0x29a0 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xda0, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xdc0 W:1 F:C_32 => 0x29c0 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xdc0, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xdc0 W:1 F:C_32 => 0x29c0 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xdc0, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xdc0 W:1 F:C_32 => 0x29c0 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xdc0, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xdc0 W:1 F:C_32 => 0x29c0 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xdc0, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xde0 W:1 F:C_32 => 0x29e0 W:1 F:C_32 (DIR 00), sPos(0 0) dPos(32 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xde0, 1, C_32) r(0, 0 => 32, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xde0 W:1 F:C_32 => 0x29e0 W:1 F:C_32 (DIR 00), sPos(0 16) dPos(32 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xde0, 1, C_32) r(0, 16 => 32, 32)
T:Oth	ID:22	S:Cache	=> Move! 0xde0 W:1 F:C_32 => 0x29e0 W:1 F:C_32 (DIR 00), sPos(32 0) dPos(0 16) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xde0, 1, C_32) r(32, 0 => 64, 16)
T:Oth	ID:22	S:Cache	=> Move! 0xde0 W:1 F:C_32 => 0x29e0 W:1 F:C_32 (DIR 00), sPos(32 16) dPos(0 0) size(32 16)
T:Oth	ID:22	S:Cache	=> TC: InvalidateLocalMem off(0xde0, 1, C_32) r(32, 16 => 64, 32)
T:Oth	ID:22	S:Cache	=> Write! ...  => 0x3300 W:2 F:P_8 (DIR 00), dPos(0 0) size(128 128)
T:Oth	ID:22	S:Cache	=> Write! ...  => 0x3eb0 W:0 F:C_32 (DIR 00), dPos(0 0) size(16 16)
```

**Comment by refractionpcsx2** [comment] 2023-02-25 11:22
This can be fixed on current master with Tex in RT, maybe @JordanTheToaster or @Mrlinkwii can do it :)

**Closed** 2023-02-25 12:28 UTC
Labels: Bug
