### ISSUE TITLE
Regresion? Call of Duty 3, Opengl hardware renderer in latest build crashes pcsx2.

### ISSUE THREAD

**Issue by joder666** [PCSX2/pcsx2#987] opened 2015-11-21 11:10 UTC
Booting Call of Duty 3 with Opengl hardware renderer using https://github.com/PCSX2/pcsx2/commit/df87b64ca59724509755ed2e44ac0ad263a9f91e, crashes the emu just before the press start screen.
This did not happen with https://github.com/PCSX2/pcsx2/commit/1437640bc55d94c902f93d172f4ce961ad328654.

Options used for GSdx:
-Hardware Depth
-Accurate Date
-CRC Hack level (Partial)
-Bending accuracy (Basic)
All else set to default settings.

Opengl software and d3d rederers do not present this problem.

Log:
https://gist.github.com/joder666/30006655745a9872e909

PC:
Core2Duo E8400
GTX 560 ti (Latest drivers installed, 359.0)
4gb ram
Windows 7 x64

**Comment by ssakash** [comment] 2015-11-21 11:25
could you try to find the exact commit which causes the crash ? , that would make work a lot easier :)

**Comment by joder666** [comment] 2015-11-21 16:24
Ohhh sh!!!@.. i made a mistake :( .... While retesting some builds to update the OP, i found out its not a game problem but a GUI one, or something along.

Before i posted the bug, while testing renderers, i set on (ticked the box) HW hacks, and selected "Preload data frame" and "Align Sprite" for DX11 renderer to see if that solves some of the graphical issues. It does not.

So i moved to test OpenGL, *untick* the HW hacks box, set Gsdx with options in the OP, boot the game, Crashed before the press start screen.

Apparently the emu does not "forget" that the HW hacks box is not ticked (on) and still apply "Preload data frame" if selected. Have to removed (untick) it and then untick the HW Hacks box to avoid the crash.

If "Preload data frame" is not selected, even with other options on, setting off HW hacks does not crash the emu.

I tracked down the problem to **v1.3.1-1465-g7a69812** as the first showing this problem.
**v1.3.1-1463** and older are OK.

**Comment by ssakash** [comment] 2015-11-22 07:53
There are two issues addressed on this report:

- [x] Preload Data Frame option would still get used in case of disabled HW hacks checkbox 
- [ ]  Enabling Preload Data Frame option causes this game to crash.


#991 addresses the first issue by making sure that the Preload Data Frame option wouldn't get used in the case of disabled HW hacks checkbox. The remaining issue is the problem of crashing when the option is enabled, looks like a job for @gregory38  :)

**Comment by gregory38** [comment] 2015-11-22 10:56
Can I have a summary of what trigger the crash (game, configuration) ?

**Comment by joder666** [comment] 2015-11-26 23:50
@gregory38 Using latest build with default settings, use opengl hardware, set HW hacks and select Preload Data Frame, boot Call of Duty 3.

**Comment by MrCK1** [comment] 2015-12-16 22:43
I don't think this is limited to COD3. Both games I tested (Wipeout Fusion and Gran Turismo 4) crash as well if Preload Data Frame is enabled. 

The funny thing is that booting in OGL SW and then switching to HW works fine. Enabling the option while in-game has no effect either.

Basically the crash is only triggered after a reboot. Here's my log from WOF: http://pastebin.com/PvTXwAAC

**Comment by gregory38** [comment] 2015-12-28 10:46
I confirm the crash on GT4 (and likely plenty of games).

Note for myself:
The issue is that I marked dirty the full upscaled RT. Dirty implementation likely expect a size based on GS mem (not the much bigger upscaled RT). It will trigger a massive upload of data that overflow various buffers (m_temp_buffer & pbo). I need to find a way to crop the dirty to the real (unknown) fb size.

**Comment by gregory38** [comment] 2015-12-28 17:03
The crash must be fixed in latest GIT. Could people test it. I only checked the first seconds on GT4.

**Comment by joder666** [comment] 2015-12-29 00:54
Its fixed for COD3.Also Guitar hero 3 suffered the same issue, fixed as well.

**Closed** 2015-12-29 07:27 UTC
Labels: GSdx: Hardware, Regression
