### ISSUE TITLE
[BUG]: Rumble Racing - Log filled with "Invalid guest transfer direction. Please report"

### ISSUE THREAD

**Issue by 7e3J4y** [PCSX2/pcsx2#5124] opened 2021-12-09 07:19 UTC
### Describe the Bug

When playing this game, the output log is filled with this:

Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues

This game has also been experiencing random hangs, I'm unsure if that is related, I have been playing around with various settings and it persists.

### Reproduction Steps

Simply booting this game and reaching the initial memory card screen outputs one line of that message to the log. Continuing onto the main menu prints around a hundred more. It persists through playing the game.

### PCSX2 Revision

1.7.2101

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 3800X

### GPU

RX 5700XT

### GS Settings

Tried with 6x and native render resolution

### Emulation Settings

All emulation settings settings default, tried with speedhacks on safe preset, safe preset with MTVU and fast CDVD, and speedhacks disabled.

### Logs & Dumps

PCSX2 Nightly - v1.7.2101 Compiled on Dec  5 2021
Savestate version: 0x9a290000

Host Machine Init:
	Operating System =  Microsoft Windows 10, 64-bit
	Physical RAM     =  16315 MB
	CPU name         =  AMD Ryzen 7 3800X 8-Core Processor
	Vendor/Model     =  AuthenticAMD (stepping 00)
	CPU speed        =  3.892 ghz (16 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  178bfbff 7ed8320b
	x86EFlags        =  2fd3fbff

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA
	SSE4a 

The current power profile is 'High performance'.
The current min / max processor states
AC: 100% / 100%
Battery: 5% / 100%

Reserving memory for recompilers...
[GameDB] 10738 games on record (loaded in 243ms)
HLE Host: Set 'host:' root path to: \

Patches: No CRC found, using 00000000 instead.
isoFile open ok: D:\ROMs\PS2\Rumble Racing (USA).bin
	Image type  = CD
 * CDVD Disk Open: CD, 1 tracks (1 to 1):
 * * Track 1: Data (Mode 1) (255720 sectors)
Current Renderer: Direct3D 11
Selected DXGI Adapter
	Name: AMD Radeon RX 5700 XT
	Vendor: 1002
GS Lookup CRC:00000000
GS Lookup CRC:00000000
48000 SampleRate: 
McdSlot 0 [File]: D:\Emulators\PCSX2\memcards\8MB Card.ps2
McdSlot 1 [File]: [disabled]
EE/iR5900-32 Recompiler Reset
	Bios Found: USA     v01.60(07/02/2002)  Console
	BIOS rom1 module not found, skipping...
	BIOS rom2 module not found, skipping...
	BIOS erom module not found, skipping...
# Initialize memory (rev:3.63, ctm:196Mhz, cpuclk:147Mhz detected)
# Total accessable memory size: 32 MB (B:2:8:0) (363:2:7c30)
# TLB spad=0 kernel=1:12 default=13:30 extended=31:38
# Initialize Start.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize User Memory ...

PlayStation 2 ======== Hard reset boot
 ROMGEN=2002-0207, IOP info (CPUID=1f, CACH_CONFIG=0, 2MB, IOP mode)
 <20020207-164243,ROMconf,PS20160AC20020207.bin:11552>
# Initialize Scratch Pad ...
# Initialize Done.

EE DECI2 Manager version 0.06 Feb  7 2002 16:41:20
  CPUID=2e20, BoardID=0, ROMGEN=2002-0207, 32M

Patches: No CRC found, using 00000000 instead.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_201.74;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC
found 0 symbols
ELF (cdrom0:\SLUS_201.74;1) Game CRC = 0x2F5354BE, EntryPoint = 0x00100008
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_201.74;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC

IOP Realtime Kernel Ver.0.9.1

    Copyright 1999 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadelf: fname cdrom0:¥SLUS_201.74;1 secname all
loadelf version 3.30
Input ELF format filename = cdrom0:¥SLUS_201.74;1
1 00100000 000eef80 ...............
2 0024b000 00000010 .
Loaded, cdrom0:¥SLUS_201.74;1
start address 0x100008
gp address 00000000
# Restart Without Memory Clear.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize Scratch Pad ...
# Restart Without Memory Clear Done.
Elf entry point @ 0x00100008 about to get recompiled. Load patches first.
[GameDB] Searching for 'slus-20174' in GameDB
[GameDB] Found 'slus-20174' in GameDB
[GameDB] Searching for patch with CRC '2f5354be'
[GameDB] No CRC-specific patch or default patch found
[GameDB] Searching for 'slus-20174' in GameDB
[GameDB] Found 'slus-20174' in GameDB
[GameDB] Searching for patch with CRC '2f5354be'
[GameDB] No CRC-specific patch or default patch found
GS Lookup CRC:2F5354BE
GS Lookup CRC:2F5354BE
Get Reboot Request From EE
ROM directory not found

PlayStation 2 ======== Update rebooting..

PlayStation 2 ======== Update reboot complete
cdvdman Init

IOP Realtime Kernel Ver.0.9.1

    Copyright 1999 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadmodule: fname cdrom0:¥MODULES¥SIO2MAN.IRX args 0 arg 
loadmodule: id 25, ret 0
loadmodule: fname cdrom0:¥MODULES¥MCMAN.IRX args 0 arg 
loadmodule: id 26, ret 0
loadmodule: fname cdrom0:¥MODULES¥MCSERV.IRX args 0 arg 
loadmodule: id 27, ret 0
loadmodule: fname cdrom0:¥MODULES¥PADMAN.IRX args 0 arg 
loadmodule: id 28, ret 0
loadmodule: fname cdrom0:¥MODULES¥LIBSD.IRX args 0 arg 
loadmodule: id 29, ret 0
loadmodule: fname cdrom0:¥MODULES¥AUDIO.IRX args 0 arg 
loadmodule: id 30, ret 0
(UpdateVSyncRate) Mode Changed to NTSC.
	... with user configured refresh rate: 59.93 Hz
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues
Invalid guest transfer direction. Please report: https://github.com/PCSX2/pcsx2/issues

**Comment by seta-san** [comment] 2021-12-09 19:51
can confirm this.. but it also seems to only happen in the menus. i can't replicate the hangs. if this wasn't in the logs i would assume that this had no issues. what i've played would qualify it for a perfect rating so far.

**Comment by 7e3J4y** [comment] 2021-12-09 20:03
The hangs have happened more consistently for me during split screen multiplayer, they're always during races and not in menus... They aren't a common occurrence, though I still have no idea why they happen.

**Comment by seta-san** [comment] 2021-12-09 20:13
i'll have to test later after work. i just ran a 2p split screen race without issue. so far the worst part of this game seems to be that it's a bad remake of mario kart that started development for the ps1 and given a hillbilly theme.

**Comment by 7e3J4y** [comment] 2021-12-09 20:21
Is there any way I can provide any meaningful data that would be of assistance when it happens to me? The entire emulator locks up when it happens and I don't see anything in the output log aside from the invalid guest transfer direction.

**Comment by seta-san** [comment] 2021-12-09 20:28
not if it isn't doing anything crazy in the logs. when it crashes does it say that there was something like a TLB Miss?

**Comment by 7e3J4y** [comment] 2021-12-11 19:08
I got a recording last night of the hang/crash happening (incase it would be useful) though there doesn't appear to be any useful information. I enabled all output on the log but there's nothing new there when it happens... The only noteworthy thing I can think of is when the game hangs, pcsx2 as a whole seems to be frozen, but the title bar of the game window continues to update. EE jumps to 99-100 after it hangs. I can provide the video should anybody want it.

**Comment by HeroponRikiBestest** [comment] 2021-12-11 19:56
Sure, post the video. A few questions;
- About how often does the crash happen?
- Does it happen on any specific track, or can it happen on any of them?
- Does it seem to be consistently caused by anything? I.e. a specific powerup being used?

**Comment by 7e3J4y** [comment] 2021-12-11 20:30
https://drive.google.com/file/d/1TELc_9DJg6RxccyyvSzKRlVDUZLkd-yA/view?usp=sharing

The recording is 2 minutes long and the hang happens in the last quarter of it.

It's a little random but it isn't super common. Could happen on the first race, or might go 5 or 10 races until it happens. It seems to happen to me primarily in multiplayer. I have had this hang happen one time in single player, and several in multiplayer.

It seems to be able to happen on any track.

I haven't noticed anything that could be "triggering" it. Most of the time, it seemed like it was happening while controllers are vibrating, and they continued to until pcsx2 is terminated, but that didn't happen on this one that I captured.

**Comment by seta-san** [comment] 2021-12-11 23:52
Are you using the 32 bit build of pcsx2 or 64bit?

**Comment by 7e3J4y** [comment] 2021-12-12 17:18
It appears I am using a 32 bit build. Does pcsx2 have a 64 bit version? It's not making itself very apparent to me if so..

**Comment by seta-san** [comment] 2021-12-12 17:21
yeah. i thought that the crash was due to some sort of memory leak but i played it and still couldn't get a crash but also no memory leak.

**Comment by HeroponRikiBestest** [comment] 2021-12-13 08:48
Okay, I played about 4 races in multiplayer, then left the game on overnight on the same session and at some point it crashed. (Probably not very long after I left it, if you said it only took a few races for you). As you said, the EE is at 99%, and there doesn't seem to be anything interesting in logs. 
![image](https://user-images.githubusercontent.com/50224630/145779851-1b9b8470-4b1b-43c9-8660-a9cf42c5a5aa.png)
![image](https://user-images.githubusercontent.com/50224630/145779868-b92b8dd8-d871-4efd-a751-964164d06d64.png)
Log: [emuLog.txt](https://github.com/PCSX2/pcsx2/files/7702261/emuLog.txt)
Blockdump: https://drive.google.com/file/d/1pFjhUscwyB0BmkIObA7s3_KPvXYOcqoM/view?usp=sharing
I'm gonna be leaving the window open, so if you need anything more from me from this session, let me know.

**Comment by HeroponRikiBestest** [comment] 2021-12-13 16:45
Also, I dunno if it's an issue, but is this supposed to be possible in rumble racing's demo? It's been stuck here for like 10 minutes, the demo eventually ended and cycled to the next one (logs are from after) but it seems odd considering I imagine they're scripted, although I don't know for certain.
[emuLog.TXT](https://github.com/PCSX2/pcsx2/files/7705352/emuLog.TXT)
[Rumble Racing (USA) (2021-11-13 11-21-29).dump.zip](https://github.com/PCSX2/pcsx2/files/7705359/Rumble.Racing.USA.2021-11-13.11-21-29.dump.zip)
https://drive.google.com/file/d/1fV5wPshyYmaCkRYWEAyxb_LpPhbKbrX7/view?usp=sharing
Here's the gsdump, but it doesn't seem to extract properly
[gsdum.zip](https://github.com/PCSX2/pcsx2/files/7705466/gsdum.zip)

**Comment by HeroponRikiBestest** [comment] 2021-12-13 17:48
@7e3J4y, next time you play, can you try playing with clamping mode full? I tested for a while with it on and the game didnt seem to crash. (For all i know, it might work with extra + preserve sign too).

**Comment by HeroponRikiBestest** [comment] 2021-12-13 20:21
Also not sure if this is an issue, but if you go through enough demos, the game will just start failing to load the race and go back to the menu immediately after the load screens. To reproduce it on your own, just uncap the framerate, skip the opening fmv, then leave it on the main menu and hit a button immediately if it loads into a race. It doesn't take too long to reproduce. Nothing interesting in the logs though.
[Rumble Racing (USA) (2021-11-13 12-46-46).dump.zip](https://github.com/PCSX2/pcsx2/files/7706728/Rumble.Racing.USA.2021-11-13.12-46-46.dump.zip)

**Comment by HeroponRikiBestest** [comment] 2021-12-19 02:34
Okay, I've been testing this game nonstop for the past 5 days. I have tested the following configurations on master, and all of them have still frozen/crashed eventually


```
VU combos
chopzero + Normal 
chopzero + extrapreserve
positive + normal

EE combos
chopzero + Normal
nearest + extra+preserve
negative + extra+preserve
positive + extra+preserve
chopzero + extra+preserve
nearest + none
negative + none
positive + none
chopzero + none 


Gamefixes
DMAC
EE TIMING
OPH

Other
interpreter + ee cache
```
Additionally, the game crashes on both https://github.com/PCSX2/pcsx2/pull/5180 and https://github.com/PCSX2/pcsx2/pull/3357 (as a stand-in for 1.6.0, for some reason I can't disable the framelimiter on 1.6.0, which would make testing impractical).

If anyone has any other ideas about what to test, please let me know and I'll do it.

**Comment by seta-san** [comment] 2021-12-19 03:42
disable the rumble feature by going into the game's controller settings and press "L1" to be able to disable it

**Comment by refractionpcsx2** [comment] 2021-12-19 03:46
rumble feature? What are you talking about?

**Comment by seta-san** [comment] 2021-12-19 03:48
> I haven't noticed anything that could be "triggering" it. Most of the time, it seemed like it was happening while controllers are vibrating, and they continued to until pcsx2 is terminated, but that didn't happen on this one that I captured.

OP gave a clue that it might be happening because of the controller's rumble feature.

**Comment by refractionpcsx2** [comment] 2021-12-19 03:49
oh right, didn't see that.

**Comment by HeroponRikiBestest** [comment] 2021-12-19 03:56
I didn't see that either. Alright, I'll try it

**Comment by HeroponRikiBestest** [comment] 2021-12-19 06:13
@seta-san I turned it off I the menu before starting a race, it still crashed.

**Comment by seta-san** [comment] 2021-12-19 06:14
what can cause the emulator to crash like that? no exception error message, no tlb miss, no messages in the log?

**Comment by HeroponRikiBestest** [comment] 2021-12-19 06:15
Well, the emulator doesn't "crash" per se, the emulation window freeze and becomes black once you interact with it. You can still interact with the settings window, but you'll need to force close the program.

**Comment by refractionpcsx2** [comment] 2021-12-19 06:16
Could be stuck in a loop somewhere. You'd have to run the emu through Visual Studio (or some IDE with a debugger) and when it hangs, pause the program and see where it is and what state it's in.

**Comment by seta-san** [comment] 2021-12-19 06:20
i modified the function that gives the "Invalid guest transfer direction. Please report" error just to see what value the switch was getting, and it was always 3 when it did it. so, it was getting something that was potentially undocumented behavior, but it wasn't some wild number showing up there like 27

**Comment by refractionpcsx2** [comment] 2021-12-19 06:21
I think that is entirely unimportant here.

**Comment by seta-san** [comment] 2021-12-19 06:22
right now that's the only potentially weird thing the game is doing that it's bothering to tell us about

**Comment by refractionpcsx2** [comment] 2021-12-19 06:23
Well it won't actually do anything in that scenario, it will just be ignored, so it's unlikely to be the cause of any hang. I'll be surprised if it is.

**Comment by seta-san** [comment] 2021-12-19 06:24
i'm just concerned that there might have been undocumented behavior it's supposed to do but doesn't.

**Comment by refractionpcsx2** [comment] 2021-12-19 06:33
Entirely possible, but the result would be missing graphics, not freezes.

**Comment by HeroponRikiBestest** [comment] 2021-12-20 22:21
After doing a backtrace of the EE thread [message.txt](https://github.com/PCSX2/pcsx2/files/7748224/message.txt) and the GS thread [message.txt](https://github.com/PCSX2/pcsx2/files/7748220/message.txt), @tellowkrinkle told me to comment out `if (!m_RingBufferIsBusy.load(std::memory_order_relaxed))` in MTGS.cpp line 675, which seems to have fixed the issue. According to him, 

> It's not very efficient but I need to rewrite our semaphore usage to get rid of that race condition (which we have in all our threading, both GS and VU)
For reference, the race condition is this:
1. GS thread finishes processing its work, checks the work list and sees that there's none left
2. EE thread adds new piece of work
3. EE thread checks GS busy status and sees that it's busy and decides not to wake it
4. GS thread sets busy status to false and goes to sleep
5. GS is thread is now asleep even though it has work to do

There's not a very big window between when the GS thread notices it has no work and when it marks itself as not busy, but it does exist and I think you're hitting it.  Disabling the check on the EE thread isn't great because it means the GS thread will stay awake for way longer than it needs to (if EE thread adds work 100 times, the GS thread will process all the work and then spin 99 times until it fully clears all its notifications) but it's the best we have until I add a fancier semaphore implementation.

> It doesn't seem super common and it's going to affect performance
I know it's an issue and I know how I want to fix it, I just have a lot of things to fix right now

**Comment by 7e3J4y** [comment] 2021-12-20 23:38
Wow, I had no idea this issue would end up getting so much attention, much less end up (more or less) solved. Thank you for all the time you spent testing this @HeroponRikiBestest :) And thank you to everyone who contributes to this wonderful emulator!

**Comment by HeroponRikiBestest** [comment] 2021-12-20 23:54
@7e3J4y well, it might be a while before it gets "truly" solved. If you know how to compile from source, build it with the change tellow made. You'll take a hit in performance, but your computer should handle it fine.

**Comment by 7e3J4y** [comment] 2021-12-21 00:42
So it seems it can! I don't know why but I figured there would actually be a performance hit, but it doesn't seem like there is. Thanks again! I'll keep this copy until I poke around in a year or so to see if it's been fixed :)

**Comment by HeroponRikiBestest** [comment] 2021-12-21 00:45
Again, your machine is pretty powerful, so the hit shouldn't affect you. Let us know if you still experience crashing.

**Comment by tellowkrinkle** [comment] 2022-04-28 01:20
This was hopefully fixed by #5825, please test (preferably comparing 1.7.2596 to 1.7.2597 to see if you can reproduce on 1.7.2596 but not 1.7.2597)

**Comment by HeroponRikiBestest** [comment] 2022-04-28 01:23
@7e3J4y, would you mind testing on the latest version?

**Comment by 7e3J4y** [comment] 2022-04-28 06:13
I've played the game for about an hour or so and it hasn't crashed yet. It will need to be tested quite a bit more to be able to tell if that is fixed or not.

What I can say is that there are no more "Invalid guest transfer direction" entries in the log. I also recall there being some bugginess with the demos that play if you idle on the main menu? I've been watching them for a bit and I don't see anything out of the ordinary anymore.

I'll make a point to play this more in the coming week and report back :)

**Comment by lightningterror** [comment] 2022-05-20 22:55
Will close as assumed fixed, otherwise can be re opened.

**Closed by lightningterror** 2022-05-20 22:55 UTC
Labels: Bug, GS
