### ISSUE TITLE
[BUG]: Devil May Cry (USA) broken geometry / graphic bugs

### ISSUE THREAD

**Issue by felixthecat1970** [PCSX2/pcsx2#4884] opened 2021-10-07 15:40 UTC
### Describe the Bug

Devil may cry (USA) 
redump HASH SHA1 checked OK, 
has rare grapic bugs in cutscenes (main character coat wrong position)
gameplay has fast jumping like behavior (no controllers configured, atttached for discard) default run options

### Reproduction Steps

run default options

### Expected Behavior

was working ok around May 2021 dev builds

### PCSX2 Revision

dev-1907

### Operating System

Windows 10 (64bit)

### CPU

ryzen 5 3400g

### GPU

vega 11

### GS Settings

Tested Configs:
Default
Safe profile enabled option
Avx2 build
default pcsx2 build

### Emulation Settings

Default

### GS Window Screenshots

https://user-images.githubusercontent.com/12580269/136417194-1242dd73-4b29-41be-bd3d-546d15a38151.mp4
![gs_20211007100907](https://user-images.githubusercontent.com/12580269/136417917-6cd63550-2fd8-4671-ba7b-67b744160c51.png)

### Logs & Dumps

[software mode emuLog.txt](https://github.com/PCSX2/pcsx2/files/7305027/software.mode.emuLog.txt)
[default emuLog.txt](https://github.com/PCSX2/pcsx2/files/7305028/default.emuLog.txt)
[safe mode emuLog.txt](https://github.com/PCSX2/pcsx2/files/7305029/safe.mode.emuLog.txt)

**Comment by refractionpcsx2** [comment] 2021-10-07 16:19
probably due to my recent CDVD changes, there's "read command abort" messages in the console. Can you try it on #4881 ?

**Comment by refractionpcsx2** [comment] 2021-10-07 19:46
Now fixed in master. Turns out it wasn't a regression, as a result of fixing a bug we uncovered a clamping issue ;)

**Closed as completed** 2021-10-07 19:45 UTC
Labels: Bug, Recompiler, R5900
