### ISSUE TITLE
[BUG]: Ratchet: Deadlocked LOD/Mipmapping issue

### ISSUE THREAD

**Issue by lextra2** [PCSX2/pcsx2#11061] opened 2024-04-11 02:34 UTC
### Describe the Bug

When walking to a shop terminal, you can see garbage textures. Might be mipmap/LOD related.
Tested with software renderer.

### Reproduction Steps

Go to the player hub
Find the shop terminal
Slowly walk towards/away from it to see garbage textures.

https://github.com/PCSX2/pcsx2/assets/20690384/2b1989ac-f003-4a73-a2c8-4c7859a1ad80

### Expected Behavior

LOD transition shouldn't reveal garbage textures.

### PCSX2 Revision

v1.7.5697

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 9 3900X

### GPU

AMD Radeon RX 6950 XT

### GS Settings

Software defaults

### Emulation Settings

All default

### GS Window Screenshots

![Ratchet - Deadlocked_SCUS-97465_20240411042132](https://github.com/PCSX2/pcsx2/assets/20690384/83789cb7-6105-4ccd-b146-9fd32ae2c953)

### Logs & Dumps

[Ratchet - Deadlocked_SCUS-97465_20240411042132.gs.zip](https://github.com/PCSX2/pcsx2/files/14940552/Ratchet.-.Deadlocked_SCUS-97465_20240411042132.gs.zip)

**Comment by JordanTheToaster** [comment] 2024-04-11 02:35
Known issue with software mode.

**Comment by TheTechnician27** [comment] 2024-04-13 11:27
Specifically, this is a dupe of #5008, where the full four mainline games are already covered (although the title of that one ought to be changed to reflect that it's not just GC that does this).

**Comment by Mrlinkwii** [comment] 2024-04-15 10:15
since this is a duplicate of #5008 im gonna close the issue :)

**Closed by Mrlinkwii** 2024-04-15 10:15 UTC
Labels: Bug
