### ISSUE TITLE
[Enhancement] Folder Memory Card Grouping

### ISSUE THREAD

**Issue by shinra358** [PCSX2/pcsx2#1116] opened 2016-01-13 13:23 UTC
I would like to request to code this option to group the same game saves into it's own folder labeled with just the main game id number. Currently, it mixes all the game saves together.

Example:

SLUS75638/                 <----game id / game save folder
SLUS75638-746453     <----saves for that one game in that folder
SLUS75638-746454
SLUS75638-746455
SLUS75638-746456

This would make things neater and easier to find.

**Comment by refractionpcsx2** [comment] 2016-01-13 20:39
Not quite sure i understand what you mean. At the moment does it not just put all the saves for the same game in a single folder, like how the ps2 does it?

**Comment by tsunami2311** [comment] 2016-01-13 21:34
i still use the old memory card single file function, dont really care for extra folders and more space used, but ihave to agree with refraction

**Comment by shinra358** [comment] 2016-01-14 00:06
@refractionpcsx2 no, it basically saves all the save games together like that ps2 harddrive that came with FF11 or like a giant memory card.

**Comment by refractionpcsx2** [comment] 2016-01-14 00:07
Oh, I thought there was a folder per game like the memory cards actually do

**Comment by shinra358** [comment] 2016-01-14 00:11
Here is a pic: http://postimg.org/image/zdwiwa4fh/

that long list of saves with the similar numbers is FFXII.
unless we can group it manually by the game id number in a folder already?

**Comment by refractionpcsx2** [comment] 2016-01-14 00:14
Maybe that's how ff12 saves work on the ps2, I've never looked, none of your other games seem to be doing  it

**Comment by shinra358** [comment] 2016-01-14 00:16
That's because I really haven't been playing other games that much and havent dumped my saves from my real ps2 yet. And those are just 1 save file per game. I haven't made multiple saves for other games yet. That's why you only see 1 for the other games.

**Comment by refractionpcsx2** [comment] 2016-01-14 00:18
Can you test  it with your other games to see if it does happen? We don't want to be chasing something that is by design of the game and we can't change that if the game expects it

**Comment by shinra358** [comment] 2016-01-14 00:19
Ok, brb.

**Comment by refractionpcsx2** [comment] 2016-01-14 00:44
Yeah please test no-square games

**Comment by refractionpcsx2** [comment] 2016-01-14 00:45
Non - square, stupid phone

**Comment by shinra358** [comment] 2016-01-14 00:54
Metal Gear S2 same thing. 

Have to remember though, not all games let you save in multiple saves and some games have multiple saves inside one slot like Smackdown vs Raw and Cy-Girls.

**Comment by vsub** [comment] 2016-01-14 04:27
Each save(if the game don't use single file for all save slots or don't use separate folder per save)is saved into a separate folder and it's added a suffix representing the save slot number(that's how it is not the PS2 too inside the memory card when you check with uLaunchELF)

What shinra358 is suggesting is what I also want to request
1.Get the game id and create a folder
2.Inside that folder,save all the saves that the game

For example:
BASLUS-21005-98
BASLUS-21005-95
BASLUS-21005-96
BASLUS-21005-97

PCSX2 will create a folder named BASLUS-21005 and put all of those saves inside
If it's possible to use the game name for the folder,will be even better(I always have problems finding the save I want...I have to start the game,get the game id and search for that name inside the folder)
I have 223 folders

**Comment by willkuer** [comment] 2016-01-14 08:25
Maybe one should ping @AdmiralCurtiss to get more relevant input.

**Comment by AdmiralCurtiss** [comment] 2016-01-14 08:45
Currently the host file system replicates the file/folder structure just how it looks on a real console, each 'save file' (ie, icon in the BIOS) gets its own folder, and depending on how the game handles multiple saves you either end up with one folder/icon that has all the saves, or one folder/icon per save.

To make this work as requested, you'd have to add a layer of indirection to make the host file system paths not equal the paths the PS2 sees on the memory card. Certainly doable, one would have to add a setting, ideally per memory card, that enables or disables that indirection and if it's turned on you take the first 12 or so characters from each folder name and create an extra parent folder with that name where the save goes into.

You'd have to be careful to correctly handle duplicate names, though, or actually split the folder names which could get difficult if the folder names have no suffix after the game ID. Or I guess enforce that subfolder names start with the parent name? That seems most reasonable and also allows fairly easy transfer between cards that enable that feature and cards that don't.

**Comment by willkuer** [comment] 2016-01-14 09:32
How so you actually validate that a save belongs to a game? The same feature should allow you to create subfolders with the slxs number or crc, or?

**Comment by AdmiralCurtiss** [comment] 2016-01-14 10:29
Well all games do write their own region/game ID (BASLUS-12345) at the beginning of their saves. Technically they could write whatever, but I assume Sony enforced this since it's true for every save I've ever seen. So you can validate it with that.

And yeah, the parent folder name is technically arbitrary, but you need to somehow re-locate the save folders and/or otherwise prevent multiple saves with the same name across multiple folders.

**Comment by vsub** [comment] 2016-01-16 08:52
I just made a tool kinda do what is requested here
http://forums.pcsx2.net/Thread-Folder-Memory-Card-Manager-FMCM

**Comment by refractionpcsx2** [comment] 2023-01-31 15:13
This issue has just come up again, and I'm really confused to what exactly is being asked in this thread.

How folder memcards work now

You save a game, it makes a folder inside the folder memcard with that games unique ID BASLUS-12345 or whatever, inside that it will make its own saves as if it was its own memcard.

Is this not what is wanted?  There seems to be a lot of assigning custom names to saves, but we can't do that becasue the game does its own file access, and the whole idea behind folder memcards is to mirror the file system in linux/windows that the PS2 would see, but also provide one card per game.

So if somebody could explain to me what exactly is requested in this thread and how it's expected to work? I'd be most grateful.

If not, then I guess we can go ahead and close cos it makes no sense to me, otherwise.

**Comment by shinra358** [comment] 2023-01-31 15:21
having your saves be read by games when youre using this memory card mode

**Comment by shinra358** [comment] 2023-01-31 15:36
well its from 2016 so i thought this thread was different until i looked at
the title. but it would be nice for the games to be able to read from this
structure and it would also be nice to display the game name beside the
game code and just not have pcsx2 read the game name but said name is for
us to know which game saves it is without looking it up.

the title actually means grouping games into folders and still having
everything to work. recursive paths i think its called. looking within
folders inside folders for the save.

**Comment by refractionpcsx2** [comment] 2023-01-31 15:39
but games are in folders and their saves all go inside that one folder, this is what I don't understand, you're asking to group games together, but I don't know what you mean by that beyond the current functionality.

**Comment by shinra358** [comment] 2023-01-31 16:09
same way games are detected in dolphin. the games can be seen in the main
folder, games can also be seen in the subfolders. so all im saying is have
the memory card folders also be detected in a subfolder. so if i want to
group them by a category, i can put the save folders in that one folder.
real ps2 hdd backup can do this.

right now its main foldr/scus-4567.
id like to be able to:
main folder/scus-4567,
main folder/rpgs/scus-4532,
and
main folder/action/scus-2134

the detection of memory card folders within subfolders within the main
folder.

**Comment by refractionpcsx2** [comment] 2023-01-31 16:14
okay, I see, so how's that gonna work? 

do you move them manually? not very user friendly
does it automatically do it, does it use genres like you have? who's going to update the 10k entries in the gamedb to do that.  What if the next person wants it categorised by game series? or region?

Further to this, what reasion does a user have to be messing around in a folder memcard anyways? They aren't supposed to be overly user friendly, but enough so you can find a serial and pull out a memcard save, or import one from your PS2 (which will have exactly the same folder names)

**Comment by shinra358** [comment] 2023-01-31 16:29
we make the folders to group them in ourselves and just place the saves
there. thats it. you dnt need to update a database. the save folders will
still be named the same.

and if youre gnna also make pcsx2 be able to read them, just tell it to
look for the save folders within the subfolder


the ps2 real hdd allowed u to group into categories but you couldnt use any
saves in games bcuz it was made just for backup.

this would be a new addition to have us group into categories AND have the
games be able to read read and write from them while in subfolders

**Comment by Mrlinkwii** [comment] 2023-01-31 16:30
>the ps2 real hdd allowed u to group into categories but you couldnt use any
saves in games bcuz it was made just for backup.

thats fine , but were talking about  memory cards not hdd tho

**Comment by shinra358** [comment] 2023-01-31 16:40
me saying 'folder memory card' is the same as this existing 'hdd' feature.
just different wording

**Comment by lightningterror** [comment] 2024-06-17 15:27
It was discussed that this wasn't a good idea so closing.

**Closed by lightningterror** 2024-06-17 15:27 UTC
Labels: Enhancement / Feature Request, Core, Memory Card
