### ISSUE TITLE
Tekken 5 Pirate's Cove Sound Bug

### ISSUE THREAD

**Issue by mateusPreste** [PCSX2/pcsx2#3946] opened 2020-11-26 08:05 UTC
![](https://static.wikia.nocookie.net/tekken/images/b/b6/Pirate_cove_3.jpg/revision/latest/scale-to-width-down/400?cb=20130929041135&path-prefix=en)

**Describe the bug**
The sound of falling coins is played endlessly while the fight is going on on the Pirate's Cove map

**To Reproduce**
Just play in a Pirate's Cove and move your character

**Expected behavior**
The sound effect of falling coins shouldn't be reproduced when the characters are out of the coin piles

**System Info (please complete the following information):**
 - PCSX2 Revision: dev-632
 - OS:  Windows 10
 - CPU:  i5-3570
 - GPU: RX 570

**Comment by MrCK1** [comment] 2020-11-27 19:39
@mateusPreste are you able to check 1.6 stable to see if the issue is present there? Otherwise, please try older PCSXw versions incase this is a regression

**Comment by mateusPreste** [comment] 2020-11-28 03:43
SLUS_21059 - US Region
no speedhacks, 
Same issue on pcsx2 1.6.0 and 1.7.0 dev-632, story and training mode, 
the coin sound is reproduced whenever the characters move, regardless of whether they are on top of the coins or not

SPU2 settings (default)
![image](https://user-images.githubusercontent.com/21023906/100493006-12836600-3109-11eb-8a3d-f2c3d5fd4d07.png)

**Comment by refractionpcsx2** [comment] 2020-11-28 03:45
I tried the exact version you have and the coin sound didn't repeat, the closest I could get was if I did a kick it played twice, presumably once for the kick and once for the leg coming back down.  Does it not always happen.

**Comment by mateusPreste** [comment] 2020-11-28 03:59
sorry for the incorrect description, but the problem I want to report is that the sound of coins moving is reproduced when the characters are in areas where there are no coins

**Comment by mateusPreste** [comment] 2020-11-28 04:04
Note that the game does not reproduce the sound of the coins when the two characters are outside the piles of coins, and the sound comes back when they are on top of the coins again

https://youtu.be/YnnJ6ExpzWY?t=340

unfortunately i couldn't find the scenes from the ps2 version, but i believe the behavior should be the same for what i remember playing on ps2

**Comment by refractionpcsx2** [comment] 2020-11-28 04:12
Okay I found the problem and corrected it, it's now fixed on master, whenever the new build becomes available (635 I guess?) you'll have it.

**Comment by refractionpcsx2** [comment] 2020-11-28 04:32
Ok it's now available, can you double check that sorted it?

**Comment by mateusPreste** [comment] 2020-11-28 04:46
@refractionpcsx2 it's fixed now, you are amazing!

**Comment by refractionpcsx2** [comment] 2020-11-28 04:50
No problem :)

**Closed by refractionpcsx2** 2020-11-28 04:50 UTC
Labels: Bug, Floating Point Accuracy, Waiting feedback
