### ISSUE TITLE
[BUG]: application crash upon booting any iso

### ISSUE THREAD

**Issue by surfup5** [PCSX2/pcsx2#5904] opened 2022-04-17 20:48 UTC
### Describe the Bug

when attempting to launch any iso file, the emulator crashes and closes. This began after the latest patch on the discovery app store on the steam deck. Before the patch push everything worked great.

### Reproduction Steps

Launch any iso, i used ratchet & clank. The entire emulator will close.

### Expected Behavior

I expected the  game to launch properly.

### PCSX2 Revision

v1.7.2622

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

**Comment by refractionpcsx2** [comment] 2022-04-17 20:55
please update your PCSX2, I believe it was fixed in 2623, but might as well get the latest.

**Comment by atmurr** [comment] 2022-04-17 20:57
Same here on v1.7.2622, using Fedora 35 and the flatpak version of PCSX2. I'll test again once 2623 is pushed to flathub.

**Comment by kenshen112** [comment] 2022-04-17 20:59
You can unlock the steam deck filesystem and use the AUR pcsx2-git package. I've been working on optimizing it with steam deck usage and it features the fix

**Comment by seta-san** [comment] 2022-04-17 22:09
Just also make sure the resources folder is updated

**Comment by TheGag96** [comment] 2022-04-18 23:48
Every AppImage version I've been spot checking from the past couple months has brought up an assertion fail handler on booting an ISO . Also, at the very least the latest ones also hang on saving General Settings. The FlatHub version does not hang but just immediately closes on booting an ISO. I even tried an 32-bit AppImage from before they were discontinue, but it doesn't even start because the Steam Deck doesn't have a 32-bit libfuse installed.

**Comment by SamRH** [comment] 2022-04-19 00:31
@TheGag96 any chance you could test whether https://github.com/PCSX2/pcsx2/actions/runs/2183121904 (there's an appimage in the artifacts zip downloaded from the bottom of the page) works for you? I suggest renaming it to PCSX2.appimage or something shorter when you extract it to rule out the weird name causing issues.

Fixes are in PCSX2 that will mean the flathub package starts working whenever the flathub maintainers update it - I believe it gets automatically updated every 7 days so in about 5 days or so. Crashes here were likely caused by two seperate issues that are now fixed.

The link I've given you above is a build including https://github.com/PCSX2/pcsx2/pull/5908 which should resolve the AppImage issues that occur on some Linux distributions and the issue I believe you're currently encountering with the AppImage. This is a third issue that is AppImage specific. The other two issues are also fixed in the above build.

**Comment by SamRH** [comment] 2022-04-19 00:47
More info related to my above comment.

This issue is likely resolved by having a build that includes:

https://github.com/PCSX2/pcsx2/pull/5891 and 
https://github.com/PCSX2/pcsx2/pull/5902


If you're encountering this issue while also using a recent AppImage you also likely need to wait until something like https://github.com/PCSX2/pcsx2/pull/5908 is merged.

If you are using the flathub version (the one Steam Deck Discover uses) and want a more up to date version that includes the fixes sooner you'll need to get the flathub maintainer to bump the version in https://github.com/flathub/net.pcsx2.PCSX2 - if you look at recent commits it's pretty simple and they may welcome a pull request.

**Comment by TheGag96** [comment] 2022-04-19 01:04
Yes, that works much better! Was getting into games and changing settings no problem.

**Comment by sssembler** [comment] 2022-04-20 14:58
To prevent this in the future is there no functional testing going on? basically whoever broke it should have realised.

**Comment by refractionpcsx2** [comment] 2022-04-20 15:00
We don't have a Steam Deck, nor do we support it. *why* should we have realised? all the Windows/Linux/Mac versions worked absolutely fine.

**Comment by RedDevilus** [comment] 2022-04-20 15:03
Or you can send a steam deck ;)

**Comment by sssembler** [comment] 2022-04-20 15:03
Found the guy who broke it.

**Closed** 2022-04-20 19:24 UTC
Labels: Bug
