### ISSUE TITLE
Battlefield 2 Modern Combat Graphics Issue HW Mode

### ISSUE THREAD

**Issue by hehk1234** [PCSX2/pcsx2#4265] opened 2021-03-01 22:26 UTC
Hello good night, this game has problems to run in hardware mode, only via software that it runs with the rendered graphics. I've tested both my notebook that has a GTX1060 + 8750H and also on my i9 9900KS + RTX3090 computer. I did the dump via rendering software. My drivers are the most recent available and I have tested them on several versions of PCSX2, even on the 1.7.0 betas.
Dumped as recommended CTRL + SHIFT + F8

https://drive.google.com/file/d/1lyZjGnSF6ri-Y2uWXqh7FjL7yRXUrWRz/view?usp=sharing

**Comment by Mrlinkwii** [comment] 2021-03-01 22:29
hello :wave: , i think theirs a issue already about that game  https://github.com/PCSX2/pcsx2/issues/1565

**Comment by tadanokojin** [comment] 2021-03-01 22:30
Issue template not filled out properly and this is a dupe of https://github.com/PCSX2/pcsx2/issues/1565

**Closed by tadanokojin** 2021-03-01 22:30 UTC
