### ISSUE TITLE
[BUG]: Persona 3 FES - NTSC SLUS-21621 - Visual Artifacts

### ISSUE THREAD

**Issue by ThisNekoGuy** [PCSX2/pcsx2#5928] opened 2022-04-21 03:42 UTC
### Describe the Bug

`Note: my GPU driver is the Nvidia 510.60.02 revision`

Moving between free-roam areas (non-combat scenes) throughout the game can cause large graphical artifacts that can either follow the player around and, in some cases, NPCs following the player.

Given that the Vulkan renderer is somewhat new, I take it that this was never not already an issue with it for this game.

### Reproduction Steps

1. Load Persona 3 FES
2. Play until you can access to the dorm rooms at the beginning and can walk around freely there
3. Attempt to enter vacant rooms there (this isn't the only way to trigger this issue; it can occur naturally though progression as well)
4. Leave the entered vacant room if it hasn't already occurred
5. See that there are artifacts on the ground that follow the player around

### Expected Behavior

- Very noticeable graphical artifacts should not occur

### PCSX2 Revision

v1.7.2641

Compiler: Clang 13.0.1 (v86-64-v3)

Compiled with: `-march=znver2 -mtune=znver2 -O3 -pipe -fno-plt -minline-all-stringops -fexceptions`
                         LDFLAGS=`-Wl,-O3,--sort-common,--as-needed,-z,relro,-z,now`

```bash
export AR="/usr/bin/llvm-ar"
export NM="/usr/bin/llvm-nm"
export AS="/usr/bin/llvm-as"
export RANLIB="/usr/bin/llvm-ranlib"
export STRIP="/usr/bin/llvm-strip"
export OBJCOPY="/usr/bin/llvm-objcopy"
```

[Compiled via the AUR](https://aur.archlinux.org/packages/pcsx2-git)

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch

### CPU

Ryzen 7 3700X

### GPU

RTX 2080 Ti

### GS Settings

<details><summary>Screenshots:</summary>

![Screenshot_20220420_222621](https://user-images.githubusercontent.com/28468662/164365960-346d1af9-1cf6-4982-90cb-2b356e9f988f.png)
![Screenshot_20220420_222637](https://user-images.githubusercontent.com/28468662/164365985-f652cffb-a16e-4aab-92c6-cb3fb3c70578.png)
![Screenshot_20220420_222649](https://user-images.githubusercontent.com/28468662/164366004-6aa5cc13-f91a-4ad4-991a-c185e79df3f2.png)

The rest of the menus are set to their defaults.

</details>

### Emulation Settings

Using the safe preset with these being the only edits:

![Screenshot_20220420_222910](https://user-images.githubusercontent.com/28468662/164366302-2878d331-e8e5-43ca-88fe-a496982b331b.png)

### GS Window Screenshots

<details><summary>Screenshots:</summary>

![gs_20220420190347_host__mnt_extraStorage_Gaming_Emulation_PS2 Emulation_Original ISOs_Modded P3 FES_SLUS_216 21 ELF](https://user-images.githubusercontent.com/28468662/164366461-7965488f-db30-4249-be3a-843c9f9c5749.png)
![gs_20220420190552_host__mnt_extraStorage_Gaming_Emulation_PS2 Emulation_Original ISOs_Modded P3 FES_SLUS_216 21 ELF](https://user-images.githubusercontent.com/28468662/164366497-23ed312a-041a-4a3a-b63d-cf75f110245f.png)
![gs_20220420192951_host__mnt_extraStorage_Gaming_Emulation_PS2 Emulation_Original ISOs_Modded P3 FES_SLUS_216 21 ELF](https://user-images.githubusercontent.com/28468662/164366449-7ca37ab9-2c7b-443b-ae4b-e64ae794a261.png)

</details>

### Logs & Dumps

[GSdumps.zip](https://github.com/PCSX2/pcsx2/files/8526967/GSdumps.zip)

I've included three separate instances where this occurs (can also happen to follower NPCs but isn't shown in these dumps).

My game is slightly modded but these changes are unrelated to where these issues occur and are used implemented via hostFS and executing the game via targeting the `.ELF` file dumped from the disc (doesn't actually end in that extension on the disc itself though, I renamed it). That said, it should still be reproducible normally.

If necessary, I can provide pnaches I used as well (one was related to widescreen that's not from the PCSX2 team/community)

**Comment by stenzek** [comment] 2022-04-21 07:21
I'm not going to bother investigating this if you don't test on a clean/unpatched game, and compare with the other renderers.

**Comment by ThisNekoGuy** [comment] 2022-04-21 17:10
It shouldn't be that serious but fine, give me a few minutes

**Comment by ThisNekoGuy** [comment] 2022-04-21 17:31
Still occurs in the vanilla game with Vulkan:
[GSdump.zip](https://github.com/PCSX2/pcsx2/files/8533299/GSdump.zip)
![gs_20220421122907_Shin Megami Tensei - Persona 3 FES _NTSC-U__SLUS-21621](https://user-images.githubusercontent.com/28468662/164517565-2600705e-00ae-4508-8d17-ad5cf4856bef.png)

I'll be back with OpenGL

**Comment by ThisNekoGuy** [comment] 2022-04-21 17:35
Seems to happen with OpenGL too, actually :thinking: 

[OpenGL GSdump.zip](https://github.com/PCSX2/pcsx2/files/8533339/OpenGL.GSdump.zip)
![gs_20220421123325_Shin Megami Tensei - Persona 3 FES _NTSC-U__SLUS-21621](https://user-images.githubusercontent.com/28468662/164518132-6fb3709a-cbe1-4a1e-a68f-35db5700b011.png)

**Comment by refractionpcsx2** [comment] 2022-04-21 17:36
Can I see your speedhacks and gamefixes tab also?

**Comment by ThisNekoGuy** [comment] 2022-04-21 17:37
![Screenshot_20220421_123721](https://user-images.githubusercontent.com/28468662/164518574-3bd5cfd9-87b8-4108-977f-96216c115b16.png)
![Screenshot_20220421_123749](https://user-images.githubusercontent.com/28468662/164518643-5596c186-4aa1-41c6-974b-eda8f9bad34b.png)

**Comment by refractionpcsx2** [comment] 2022-04-21 17:43
I matched your settings and used your GS Dump, and I can't reproduce it

![image](https://user-images.githubusercontent.com/6278726/164519544-746d0659-fd2f-41aa-b64a-427dfa9273e2.png)

**Comment by ThisNekoGuy** [comment] 2022-04-21 17:49
Maybe an issue with the Nvidia driver? :thinking: 
Talking to Nvidia about Linux driver issues is a pain; they don't really take direct messages except by email (to which they never respond to) at `linux-bugs@nvidia.com`...

They have a forum with stockpiled driver issues that they also almost never respond to though; I'd think to try that (maybe) but my account there is 2FA locked and I busted my phone, so I can't really do that :/

**Comment by refractionpcsx2** [comment] 2022-04-21 17:50
Are Mesa drivers available for you? It could be worth trying them rather than official drivers.  It's always possible it's a driver issue but I didn't know of any issues with recent drivers, but then I can only speak for windows lol

**Comment by ThisNekoGuy** [comment] 2022-04-21 17:54
The only open-source equivalent to mesa for Nvidia on Linux is `nouveau`, which historically far behind the capabilities of the proprietary driver and, additionally, not very compatible with a variety of cards including my own

**Comment by refractionpcsx2** [comment] 2022-04-21 17:55
Maybe check for a newer nvidia driver then? I think 510 is a few months old now

**Comment by ThisNekoGuy** [comment] 2022-04-21 17:57
The latest release versioning between Windows and Linux are different; `510.60.02` _is_ the latest driver release:
https://www.nvidia.de/Download/processFind.aspx?psid=106&pfid=885&osid=12&lid=9&whql=&lang=en&ctk=0&qnfslb=01

**Comment by refractionpcsx2** [comment] 2022-04-21 17:59
RIP I guess :P

Can you reproduce the bug with the gsdump also? just to make sure we're on the same page here.

**Comment by ThisNekoGuy** [comment] 2022-04-21 18:01
How do I load the dump?

**Comment by refractionpcsx2** [comment] 2022-04-21 18:02
If you can't see the GS Dump Debugger under the debug menu, open your PCSX2_ui ini file and in the top section without a heading add

DevMode=enabled

then reload PCSX2 and it should be there.

**Comment by ThisNekoGuy** [comment] 2022-04-21 18:07
![Screenshot_20220421_130635](https://user-images.githubusercontent.com/28468662/164524237-fa154087-2b97-4e74-ae9d-2272110406b7.png)
This is what I get with the debugger Lmao

**Comment by refractionpcsx2** [comment] 2022-04-21 18:08
hmm yes, something is very wrong with either your drivers or your GPU :P

**Comment by ThisNekoGuy** [comment] 2022-04-21 18:09
Not in all cases though, the other two Vulkan snaps seemed fine? Which is odd

**Comment by refractionpcsx2** [comment] 2022-04-21 18:10
if vulkan is okay, that would imply there's an issue with the OGL driver. OGL and Vulkan was fine for me

**Comment by ThisNekoGuy** [comment] 2022-04-21 18:12
Well, the screenshot I just showed you was also from Vulkan; so that's 1/4th of the Vulkan dumps that seem to come out like that so far

**Comment by refractionpcsx2** [comment] 2022-04-21 18:13
Which GS Dump is that one? Did you upload it?

**Comment by ThisNekoGuy** [comment] 2022-04-21 18:13
I uploaded all of the GS dumps; that one I just showed you was included in the initial report up top

**Comment by refractionpcsx2** [comment] 2022-04-21 18:42
Okay yes that one glitches for me too, but being that it's the mod, I'm not sure how much I trust it, however it also glitches in software mode, which means it's likely the core the error is coming from, so it could be worth disabling the presets and enabling the EE Timing hack, see if that resolves it.

**Comment by refractionpcsx2** [comment] 2022-04-21 18:54
So the unmodified version is fine?

**Comment by ThisNekoGuy** [comment] 2022-04-21 18:55
In the debugger, at least; still happens at runtime for both but the only dump we've seen so far that both you and I have seen glitches in is that one with the NPC in the modded version

**Comment by refractionpcsx2** [comment] 2022-04-21 18:58
Can you try with a multi frame GS Dump by doing Shift + Ctrl + F8, see if you can capture it over several frames?

Though I suspect the problem is possibly a core issue.  Can you also try the GIF FIFO gamefix, or maybe try turning on MTVU under speedhacks or something..

**Comment by ThisNekoGuy** [comment] 2022-04-21 18:59
Do you want Vanilla or modded, given that we've seen something on that side?
(Honestly, aside from a widescreen pnach, the only things that modded version touches is game content - not the engine or what have you)

**Comment by refractionpcsx2** [comment] 2022-04-21 19:00
I'd prefer vanilla, I have little desire to support modded games as I can't trust their reliability, but if we can get the normal version working, I'd be fine with that.

**Comment by ThisNekoGuy** [comment] 2022-04-21 19:36
This one is going to be a bit too large to upload here...
Going to have to use a cloud storage link:
https://mega.nz/file/VuIUwA5a#OU0vFPzjajBq7Tp1aF0EieN_dabwZ-Yp2XShZ68s7uU

The issue is still present in-game with both of those options you suggested (individually) but attempting to load the GSdump gave me a few issues:
- It's 1 file but it's seen by PCSX2 as 3 separate dumps (not sure if that's abnormal)
- "Dumps 2 and 3" here, render as black screens
- On one occasion, "dump 3" did seemingly load properly (appeared to be in a loop) (after waiting a little to stop being a black screen) but the issue wasn't present when this loaded either

This a log that PCSX2 spit out:
[log.txt](https://github.com/PCSX2/pcsx2/files/8534532/log.txt)

Side note:
PCSX2 crashes if I try to open the dumps after shutting down the loaded ISO with a message about a Vulkan instance; just something I thought I'd mention

**Comment by MrCK1** [comment] 2022-05-10 14:56
@refractionpcsx2 are we set to close this if the dump is working fine?

**Comment by ThisNekoGuy** [comment] 2022-05-14 05:15
I mean, the dump works fine, but visual oddities like that are certainly not intended / representative of the original hardware...

**Comment by lightningterror** [comment] 2022-08-09 03:41
Would be nice to reset all settings, this looks like a misconfiguration, anyway wasn't reproduced so closing.

**Closed by lightningterror** 2022-08-09 03:41 UTC
Labels: Bug

**Comment by ThisNekoGuy** [comment] 2022-08-09 04:39
@lightningterror I've done this before, it makes no difference
Quite judgemental to assume I've not done so

I've since updated the GPU driver though and moved to the new open-source kernel module driver, so I'll come back with more data soon. Please re-open this.

**Comment by lightningterror** [comment] 2022-08-09 04:41
Sure, if the issue persist I will re open it.
