### ISSUE TITLE
[BUG]: SLUS-21041 - Shadow Hearts Covenant - Black Screen on certain scenes / locks game

### ISSUE THREAD

**Issue by IrealiTY** [PCSX2/pcsx2#7139] opened 2022-10-05 22:54 UTC
### Describe the Bug

Game soft locks when trying to leave the area, resulting in a black screen that requires the game to be reset.
Reached a point in the game when even trying to open the Save menu locks up the game.

I attempted different hacks / modes (software, vulkan, opengl etc) combinations and resetting settings to default.

### Reproduction Steps

It's a bit harder to reproduce generally, since until I reached the area where it locks up no matter what, it was pretty random if it would happen or not.

But in the provided save states, you just try accessing the door at the bottom of the room or at the top of the room.
Alternatively, Open the Menu (Triangle) and go to Data.

### PCSX2 Revision

1.7.3371

### Operating System

Windows 11

### CPU

Ryzen 5900x

### GPU

RTX 3080

### GS Settings

As mentioned above, default settings only 16;9 was a constant (tested with and without the widescreen hack though)

### Logs & Dumps

[Shadow Hearts - Covenant [Disc1of2]_SLUS-21041_20221006002045.zip](https://github.com/PCSX2/pcsx2/files/9719451/Shadow.Hearts.-.Covenant.Disc1of2._SLUS-21041_20221006002045.zip)
[SaveState - pre blackscreen.zip](https://github.com/PCSX2/pcsx2/files/9719457/SaveState.-.pre.blackscreen.zip)
[SaveState - during blackscreen.zip](https://github.com/PCSX2/pcsx2/files/9719458/SaveState.-.during.blackscreen.zip)

**Comment by refractionpcsx2** [comment] 2022-10-06 23:35
can you try turning on FastCDVD

**Comment by IrealiTY** [comment] 2022-10-07 21:08
Just tested it, same result.
[Shadow Hearts - Covenant [Disc1of2]_SLUS-21041_20221007224635.zip](https://github.com/PCSX2/pcsx2/files/9737492/Shadow.Hearts.-.Covenant.Disc1of2._SLUS-21041_20221007224635.zip)

I tested going to this room again and on the 3rd attempt it worked fine, but considering this issue happened before, and the report above was a catastrophic version of the issue, I could very much foresee it happening again.

**Comment by refractionpcsx2** [comment] 2022-10-07 22:32
I know about the black screens during battles, in this issue I'm more concerned with the black screens and lockups.

**Comment by RaduNastase** [comment] 2022-10-12 16:16
This issue is also in Aethersx2 (android).

**Comment by refractionpcsx2** [comment] 2022-10-12 16:16
well yeah, Aethersx2 is basically PCSX2 on android.

**Comment by RaduNastase** [comment] 2022-10-12 16:18
Indeed, 

edited my previoous comment, but the idea is that the bug is there for this game.

**Comment by johnnymaq** [comment] 2022-10-17 04:05
I'm replicating this on the past few versions, including the most recent. Been using savestates to combat it since it's random. Had it happen maybe 8 times through the playthrough. Includes most black screen transitions including 'after battle into world' and cutscenes.

**Comment by IrealiTY** [comment] 2022-10-19 18:43
I reached around 50% of the Disc 2 of the game, and had 0 black screens so far. Whereas on Disk 1 it was basically a guarantee.

**Comment by BParks21** [comment] 2022-10-19 20:31
Are you using fast forward/frame unthrottle at all? I get a soft lock frequently when transitioning to certain areas but it usually only happens if I used unthrottle at least once.

**Comment by RaduNastase** [comment] 2022-10-20 03:51
I never used any fast forward or anything, and it gave me random black screens on both discs.

**Comment by BParks21** [comment] 2022-10-20 13:29
> I never used any fast forward or anything, and it gave me random black screens on both discs.

Ahh ok I see.

**Comment by SummonerL** [comment] 2022-12-01 18:43
@IrealiTY, have you experienced this issue any more since turning on FastCDVD? I am currently playing this on my Steam Deck and have ran into this issue several times.

**Comment by Fothsid** [comment] 2022-12-01 19:25
Settings don't affect the issue as far as I know and the lockups are completely random.
The game has a custom IOP module for file operations, so it's very likely the developers might have done something funky in there. _What_ they did specifically is not really known without reverse engineering it. (They did leave in debug symbols in the module file, though)

**Comment by refractionpcsx2** [comment] 2022-12-01 19:30
I'm pretty sure CDVD reading should be slower than it is on PCSX2, but I'm not quite sure needs to be slower, I've exhausted most of the physical limitations (seeks, spin downs, rotational delay etc).

I guess one solution would be to replace FastCDVD with a "CDVD Speed" option where you can choose Slow, Normal, Fast. That way the "slow" version can be closer to the value I expect to be correct, under the guise of a hack (I guess), and we can also make FastCDVD more aggressive than it is now, which isn't very compared to the old 1.6 version of the hack.

**Comment by Hmarochos6581** [comment] 2023-08-02 14:59
Just want to say, I'm playing right now and this black screens soft-lock popping very frequently. The game structure itself is very convenient in this matter, because you have a lot of opportunities to save during playthrough, but man, it's annoying af.

**Comment by falco360** [comment] 2023-09-28 20:04
Was this issue ever resolved/fixed?

**Comment by falco360** [comment] 2023-09-28 20:38
> I actually ended up in somebodies stream the other night who was playing it, and it seems to still be an issue. They were getting around it by making savestates and loading them if it fails to load.
> 
> I wish I knew why it was doing it :(

That’s a real bummer
Does Open PS2 loader function similarly to PCSX2?
If so,I can tell you that the same issue exists when playing on console with Open PS2 loader and it is fixed by setting the Callback timer to 50(I think that was the number)
Although the latest OPL revisions just use a compatibility mode to do the exact same thing(ex:mode 1=set callback timer to 50)

**Comment by refractionpcsx2** [comment] 2023-09-28 20:42
?Thanks for the info, but I don't know what callback that's relating to :(

**Comment by falco360** [comment] 2023-09-28 20:44
I’ll see if I can dig up some info on this

**Comment by Fothsid** [comment] 2023-09-28 21:35
Mode 1 in OPL seems to enable the `IOPCORE_COMPAT_ACCU_READS` flag inside their settings structure, so searching for bitfield masks with that might help?

https://github.com/ps2homebrew/Open-PS2-Loader/blob/17efb447b77442e1a85715d194c3d7b4b5ad0b94/modules/iopcore/cdvdman/cdvdman.c#L841

https://github.com/ps2homebrew/Open-PS2-Loader/blob/17efb447b77442e1a85715d194c3d7b4b5ad0b94/modules/iopcore/cdvdman/cdvdman.c#L294

https://github.com/ps2homebrew/Open-PS2-Loader/blob/17efb447b77442e1a85715d194c3d7b4b5ad0b94/modules/iopcore/cdvdman/cdvdman.c#L303

..etc

**Comment by refractionpcsx2** [comment] 2023-09-28 21:36
problem is, introducing those accurate speeds is what broke it, for us.

**Comment by falco360** [comment] 2023-09-28 21:47
> problem is, introducing those accurate speeds is what broke it, for us.

Maybe remove it(for that game,if possible)?
🤔

**Comment by refractionpcsx2** [comment] 2023-09-28 21:55
It's not possible.

**Comment by falco360** [comment] 2023-09-28 21:59
> It's not possible, neither is that a solution.

I see…

**Comment by demonkingzaine** [comment] 2023-10-02 23:44
Out of curiosity since it was mentioned here I decided to setup OPL in PCSX2 and can report that setting compatibility mode 1 as indicated seems to solve the problem. You can even get achievements to work as far as I can tell if you link OPL to the correct base game in PCSX2 but widescreen patches through PCSX2 don't work and cheats have to be set after the game has loaded.

Looking at what OPL is doing for Mode 1 Compatibility (If I'm reading it right) seems to boil down to setting it to read immediately, limiting sector buffer? (Not sure on this but it's limiting sector something to a max of 8) count to 8, and setting DVD speed to 2200KB/s or 2.2MB/s (A little less then 2X. CDs are apparently set to 900KB/s.)

Not sure if any of that information is really helpful though.

**Comment by refractionpcsx2** [comment] 2023-10-02 23:56
Thanks for looking, but I already pretty much do that :/

**Comment by demonkingzaine** [comment] 2023-10-03 01:00
Well If it was this simple it would already work lol. 

After looking at all of this I'd be interested in seeing personally how the game behaves with more variable CDVD speed options though. I remember a while back you floated the idea of replacing fastCDVD with more granular speed options which would be neat to see eventually. 

As it stands I'll take the incredibly jank "Play it through OPL dumped on an HDD image" as good enough for me for the time being. Because if the issue is still possible through that then it's at least substantially less common as my usual method for triggering it has thus far failed to do so.

Thanks for all the hardwork.

**Comment by refractionpcsx2** [comment] 2023-10-03 01:24
yeah, I need to look more at it because I'm not happy with what's going on, but I'm not sure right now what to do. we ran some tests, and the PS2 speed was absolutely freaking close to PCSX2

**Comment by refractionpcsx2** [comment] 2023-10-08 15:03
It's a long shot, but can you try the game with https://github.com/PCSX2/pcsx2/pull/10080

I'm hoping it helps a bit, but I don't have high hopes lol, this game hates me.

**Comment by demonkingzaine** [comment] 2023-10-08 15:08
I'll give it a shot once it finishes building artifacts. lol Fingers crossed.

**Comment by refractionpcsx2** [comment] 2023-10-08 15:10
It should accurately set the speed to 2.2mb/sec (it was 2.7 before, but I was working on changing it locally), plus some other things.

**Comment by refractionpcsx2** [comment] 2023-10-08 15:48
It's finally built @demonkingzaine , sorry about that, I had to fix up warnings and tidy things up a bit.

**Comment by demonkingzaine** [comment] 2023-10-08 16:00
Unfortunately my testing of #10080 seems to indicate that it indeed does not fix the problem. Sorry Ref.

**Comment by refractionpcsx2** [comment] 2023-10-08 16:01
darn :( Oh well. Thanks for trying.

**Comment by demonkingzaine** [comment] 2023-10-09 06:18
I had the opportunity to meet with a friend who has a PAL copy of the game today and we decided to try it out just out of curiosity since we had nothing better to do and other reports on the issue aside from this one never specified region. The title of this issue seems to be apt as this issue appears to be NTSC-U only (We don't have access to an NTSC-J copy so it might happen there too) as despite our best efforts we couldn't get it to crash/hang either on 1.7.5092 or PR #10080. Rather then hating you perhaps it just hates North America.

**Comment by Fothsid** [comment] 2023-10-09 08:27
In that case I would say it's worth comparing the FIO.IRX (file I/O) modules between the two releases. The NA version had symbols embedded, if PAL has them two then finding possible differences should quick enough.

**Comment by demonkingzaine** [comment] 2023-10-10 01:33
Had a moment so I setup Ghidra and pulled both versions respective FIO.IRX into it. Unfortunately difference checking between the two of them didn't come up with anything, it's possible both I and Ghidra are missing something (myself especially MIPS has never been my strongest language and I haven't touched it in 15 years) but nothing in particular stands out as different or wrong. None of the other standard modules appear to differ between the two either.

However checking the modules lead me to SDRV_IOP.IRX which pulling it into Ghidra seems to show it to be a custom Audio/IOP module with plenty of differences between the two versions. So this could unfortunately possibly be a Knockout Kings 2001 esqe situation and it's doing something PCSX2 just doesn't appreciate. Unfortunately there appear to be no symbols so we're probably at the point someone more knowledgeable will likely need to take over. 

If there's anything else I can do to help just let me know.

**Comment by refractionpcsx2** [comment] 2023-10-10 06:32
SDRV, that sounds like an audio module, though this all started happening when I changed cdvd timings, but maybe it's a steaming audio problem not sure..

Really appreciate you driving in though, very cool

**Comment by refractionpcsx2** [comment] 2023-10-10 06:49
Do you have a memcard save where this can be gotten to happen frequently? It would be useful for testing

**Comment by refractionpcsx2** [comment] 2023-10-10 07:45
Thanks! :)

**Comment by refractionpcsx2** [comment] 2023-10-10 19:48
I think I've sussed it, can you try #10088 ?

**Comment by demonkingzaine** [comment] 2023-10-11 01:36
Trying it now @refractionpcsx2 Fingers Crossed.

**Comment by demonkingzaine** [comment] 2023-10-11 02:00
Fixed by #10088 

I have done 20+ straight minutes of area transitions, my eyes hurt.

**Comment by BParks21** [comment] 2023-10-11 02:10
@refractionpcsx2 You are a wizard!

**Closed** 2023-10-11 15:06 UTC
Labels: Bug

**Comment by refractionpcsx2** [comment] 2023-10-11 17:13
Enjoy guys :D Thank you for your help testing, and I hope I never have to talk to you about this game again :P
