### ISSUE TITLE
Dragon quest VIII lines and ghosting with Opengl

### ISSUE THREAD

**Issue by LuismaSP89** [PCSX2/pcsx2#2129] opened 2017-11-15 10:35 UTC
***PCSX2 version:***
1.5.0-dev-2211-g58f2b6c25
 
 ***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``

Some stripes when opengl is used, this doesn´t happen with dx11 with the same settings.

Tried different HW hacks, with no result (Even align sprite)

Images attached, maybe is difficult to see in a screenshot capture and with a little screen. I use a 32" screen and it certainly can be seen.

***PC specifications:***
i7 4790k
16GB DDR3 
GTX 970
Windows 10 x64

DX11 SCREENSHOTS (With no lines)
![5x dx11](https://user-images.githubusercontent.com/12205048/32831539-f95f465a-c9f8-11e7-8a23-983b69e1a77c.jpg)
![3x dx11](https://user-images.githubusercontent.com/12205048/32831540-f97eb1fc-c9f8-11e7-9756-9b8a8d38ea73.jpg)

OPENGL SCREENSHOTS (With lines)
![5x opengl](https://user-images.githubusercontent.com/12205048/32831757-a191c65e-c9f9-11e7-8cc2-90aa99d588a1.jpg)
![3x opengl](https://user-images.githubusercontent.com/12205048/32831758-a1b25086-c9f9-11e7-9e05-bdc5285fa2ee.jpg)

**Comment by ssakash** [comment] 2017-11-15 12:23
What about ``OpenGL (Software mode)``?

**Comment by MrCK1** [comment] 2017-11-15 13:13
What are your GSdx settings? I've seen this when running at higher than 4x native.

**Comment by LuismaSP89** [comment] 2017-11-15 20:30
@MrCK1 The 2nd and 4th images are 3x native. The 1st and 3rd are 5x native and the problem appear in both of the Opengl screenshots. (last two, with red arrows) It can be an artifact of upscaling, but in directx 11 that problem doesn´t happen¿?

My other settings are: 

HW hacks: 

Half-pixel offset: Normal (Vertex)
Round sprite: Half

-------------------------------------
CRC hack level: Normal

Texture filtering: Bilinear (Forced)

Interlacing: Auto

Anisotropic: 16x

Mipmapping: Basic

-Large framebuffer (on)
-Accurate Date (on)

Blending unit accuracy: High

I tested enabling/disabling/change all these settings, and no changes. Tested too with all HW hacks enabled/disabled (Merge sprite, align sprite, wild arms offset- The same result. Only looks perfect under DX11.

**Comment by MrCK1** [comment] 2017-11-15 20:34
I've got an idea. Does the anything change if you turn on/off 8-Bit Textures in DX11?

**Comment by LuismaSP89** [comment] 2017-11-15 20:37
@ssakash The problem persist even using software mode under opengl. (Image attached with red arrows) Maybe is difficult to see because the screenshot and the pixelation with software mode, but ingame can bee seen better.

![opengl software](https://user-images.githubusercontent.com/12205048/32858876-25803560-ca4d-11e7-85fb-887ad25376fa.jpg)

**Comment by LuismaSP89** [comment] 2017-11-15 20:41
@MrCK1 Nope, no changes with 8 bit textures on/off under DX11.

**Comment by LuismaSP89** [comment] 2017-11-15 20:47
Btw, i realized there are other problems too under opengl, a ghosting issue (Even with half pixel offset) under DX11 all works ok once more. (All backends with same settings)

OPENGL:
![opengl](https://user-images.githubusercontent.com/12205048/32859356-86112a0a-ca4e-11e7-9e61-658cae303d42.jpg)

DX11:
![dx11](https://user-images.githubusercontent.com/12205048/32859357-8635b6ae-ca4e-11e7-946b-850f4b50def9.jpg)

**Comment by MrCK1** [comment] 2017-11-15 20:48
Well it looks more like the post-processing is missing in DX11. I'm sure HPO special could fix the ghosting, but that's not really the focus of the issue here.

**Comment by LuismaSP89** [comment] 2017-11-15 21:01
@MrCK1 In my case, switching between HPO normal-special-special (-aggressive) has no effect, and even disabling it looks better than enabled with the ghosting problem (All under opengl)

**Comment by LuismaSP89** [comment] 2019-01-20 22:51
Update: DX11 now has depth support and other updates ported from opengl, but the issue still happens in the opengl backend only.

**Comment by lightningterror** [comment] 2019-03-01 17:54
Can someone upload a gs dump of this issue ?

**Comment by LuismaSP89** [comment] 2019-03-01 18:04
Here you go:

[snaps.zip](https://github.com/PCSX2/pcsx2/files/2920546/snaps.zip)

**Comment by KrossX** [comment] 2019-03-01 19:29
Could you take some comparison screenshots with 4:3 aspect ratio? Also disable shader effects if you're using them.

**Comment by LuismaSP89** [comment] 2019-03-01 22:17
Here with the 16:9 and shaders enabled:
![1](https://user-images.githubusercontent.com/12205048/53669512-97f98e00-3c77-11e9-98d0-4a220d82eb38.jpg)

Here with 4:3 and shaders disabled:
![2](https://user-images.githubusercontent.com/12205048/53669510-97f98e00-3c77-11e9-9a33-23852acb6591.jpg)

Ghosting problem persists in both (Remember this only happens in Opengl, directx is Ok) and the lines problem seems to be related with the "texture filtering of display" option under "shaders" this option increases the lines, but one more time only in Opengl in directx works perfect and the game looks more clean.

**Comment by KrossX** [comment] 2019-03-01 22:23
Alright, I'm gonna bother you a bit more cuz I cannot reproduce it. Can you please do the 4:3 test with shaders disabled but fullscreen like your previous screenshots and png comparing dx11 and ogl? It seems d3d11 just doesn't do the post processing and thus no lines. Keep texture filtering of display enabled, it just makes lines that would've disappear due to resolution difference, visible.

**Comment by LuismaSP89** [comment] 2019-03-01 22:39
Don't worry, you don't bother me, thanks for the help.


DX11 no shaders, 4:3, texture filtering of display enabled:
![gsdx_20190301233337](https://user-images.githubusercontent.com/12205048/53670380-d3498c00-3c7a-11e9-85e3-63f15629bdb6.png)

Same config with OPENGL:
![gsdx_20190301233420](https://user-images.githubusercontent.com/12205048/53670381-d3e22280-3c7a-11e9-9aca-35ef790450b6.png)

**Comment by Kumikiri** [comment] 2019-07-26 19:48
> _**PCSX2 version:**_
> 1.5.0-dev-2211-g58f2b6c25
> 
> _**Description of the issue:**_
> `(What's the problem? - Screenshots showing the issue if applicable)`
> 
> Some stripes when opengl is used, this doesn´t happen with dx11 with the same settings.
> 
> Tried different HW hacks, with no result (Even align sprite)
> 
> Images attached, maybe is difficult to see in a screenshot capture and with a little screen. I use a 32" screen and it certainly can be seen.
> 
> _**PC specifications:**_
> i7 4790k
> 16GB DDR3
> GTX 970
> Windows 10 x64
> 
> DX11 SCREENSHOTS (With no lines)
> ![5x dx11](https://user-images.githubusercontent.com/12205048/32831539-f95f465a-c9f8-11e7-8a23-983b69e1a77c.jpg)
> ![3x dx11](https://user-images.githubusercontent.com/12205048/32831540-f97eb1fc-c9f8-11e7-9756-9b8a8d38ea73.jpg)
> 
> OPENGL SCREENSHOTS (With lines)
> ![5x opengl](https://user-images.githubusercontent.com/12205048/32831757-a191c65e-c9f9-11e7-8cc2-90aa99d588a1.jpg)
> ![3x opengl](https://user-images.githubusercontent.com/12205048/32831758-a1b25086-c9f9-11e7-9e05-bdc5285fa2ee.jpg)

Hi,

I don't know if it's approppriate here to ask this but I don't know how to contact you.
I wanted to ask you how did you achieve DQ VIII looking like this on PCSX2 ? Is there some kind of special settings with shaders ? Mine doesn't look as good as yours.

**Comment by lightningterror** [comment] 2019-07-27 01:24
@Kumikiri this isn't a place for support, use the forums, thanks.

Anyway the glow effect should work now on dx11 too. It was a blending effect which was ported recently from opengl.
If you want you can set blending to None on both backends to not render the effect.

**Comment by lightningterror** [comment] 2020-11-27 20:47
Lines should be fixed now, as for ghosting it's result of upscaling.

**Closed by lightningterror** 2020-11-27 20:47 UTC
Labels: GS: Upscaling, Plugin: GS

**Comment by LuismaSP89** [comment] 2020-11-29 16:35
@lightningterror Yes, lines are fixed now, thank you : )

Regarding the ghosting, yes, it persist, I think improved a bit and there are less noticeable, but now can be seen on both backends, DX11 and Opengl. I assume this is because you or another dev implemented a opengl feature that are missing on DX11 and now the DX11 is on pair with Opengl, in this case I'll try to disable depth emulation or other effects to see if there's a way to solve it.
