### ISSUE TITLE
[BUG]: GOD OF WAR 2 - sun is visible through walls and buildings

### ISSUE THREAD

**Issue by psennermann** [PCSX2/pcsx2#5427] opened 2022-01-30 17:36 UTC
### Describe the Bug

the sun is visible through walls and buildings (see image below)
The problem can be fixed enabling "Auto Flush" option in the Hack settings, but it creates some minor cromatic aberration in the game background and also has a great impact on performance

### Reproduction Steps

play the game

### Expected Behavior

the sun should be invisible behind a wall

### PCSX2 Revision

v.1.7.2282

### Operating System

Windows 10 (64bit)

### CPU

i7 -7700

### GPU

RTX 2060 super

### GS Settings

![Capture1](https://user-images.githubusercontent.com/6342467/151710402-a676d327-5f14-4cb3-a107-3977fdfac6fb.JPG)
![Capture2](https://user-images.githubusercontent.com/6342467/151710407-17ad6a46-f5c4-4a06-97d1-ddd0c4870df2.JPG)

### Emulation Settings

safe preset + MTVU

### GS Window Screenshots

![GOW2](https://user-images.githubusercontent.com/6342467/151710444-136950dd-1334-49ce-a55f-5caf24685712.JPG)

**Comment by gilderoylockhart01** [comment] 2022-01-30 17:38
Auto Flush is a requirement for that game, the speed impact has been mitigated very heavily in the latest dev build.

**Comment by psennermann** [comment] 2022-01-30 18:21
> Auto Flush is a requirement for that game, the speed impact has been mitigated very heavily in the latest dev build.

on my system with Auto Flush usually fps are fine, but sometimes during some fights they dip under 10 fps and the game becomes a slide-show...

**Comment by seta-san** [comment] 2022-02-02 02:49
https://github.com/PCSX2/pcsx2/issues/1860
https://github.com/PCSX2/pcsx2/issues/3751
https://github.com/PCSX2/pcsx2/issues/3993

The sun is broken

**Comment by MrCK1** [comment] 2022-02-14 14:27
Closing since the issue is resolved by using auto flush

**Closed by MrCK1** 2022-02-14 14:27 UTC
Labels: Bug
