### ISSUE TITLE
Appveyor/Travis CI issues

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1081] opened 2016-01-02 19:53 UTC
The free plan is quite slow to compile full PCSX2 build for each commits/PRs/branches. The current build is 38 min for vs2015. So each commits take more than 1 hours.

Would it be possible to limit the number of configuration of GSdx. Maybe limit to AVX2 and SSE2.

**Comment by willkuer** [comment] 2016-01-02 23:01
I guess parallel compilation as in the travis case is not possible/wouldn't be for free?

**Comment by turtleli** [comment] 2016-01-02 23:39
Yeah, parallel isn't free. And it's slow on the PCSX2 repo but not my own repo for no good reason at all.

Some potential solutions (some were briefly discussed on IRC):
 * Don't build all GSdx configurations
 * Build only certain branches - PR #1078 shows we're doing pointless builds
 * Use rolling builds - build only the latest commit on each branch/PR if multiple jobs on each branch/PR are queued up
 * Remove VS2013 build - I'm against this unless we drop VS2013 compilation

**Comment by gregory38** [comment] 2016-01-03 12:38
Let's go first with the removal of GSdx configuration to keep only 2 of them instead of 4.

**Comment by willkuer** [comment] 2016-01-03 17:07
Is it possible to ping/request builds on demand? I think dev builds can be considered unstable even if your commits are most of the time relatively safe. So if vs2013 breaks in one version thats not the worst that could ever happen. Maybe just ~monthly request vs2013 builds of the master branch but not of pr's anymore?

I think waiting one hour or slightly less if gsdx versions are reduced doesnt sound bad.

Actually parallel debug and devel versions could be more interesting for testers...

**Comment by turtleli** [comment] 2016-01-03 20:00
On demand builds are possible, but I think it's best if we know immediately when a compilation error occurs.

Current build times on my repo:
5 GSdx builds (SSE2, SSSE3, SSE4, AVX, AVX2) - ~ 34 minutes
3 GSdx builds (SSE2, SSE4, AVX2) - ~28 minutes
2 GSdx builds (SSE2, AVX2) - ~25 minutes

So we'll probably save 18 minutes on the PCSX2 repo by reducing to 2 GSdx configurations (my repo is approximately 2x faster).

Another thing that can be done it to use fast_finish in appveyor.yml so it aborts if there's a compilation error - if the VS2015 build fails, the VS2013 build won't run.

**Comment by gregory38** [comment] 2016-01-05 08:48
Ok, so let's keep 2 GSdx build. 18 minutes gain could be enough.

Build error could be limited to a single VS version (and there are rarely a build error anyway).

By the way, there are couple of options that might be or not interesting such as
* git clone depth
* build priority
* fetch repository as zip archive
* cache some directories ? ( third party ?)
I really don't know the impact of those options.

**Comment by gregory38** [comment] 2016-01-09 17:56
Fwiw, the build has a massive slow down here.What is it? Is it the linking stage? Is link optimization enabled on the build such as LTO/PGO?
```
Creating library C:\projects\pcsx2\bin\\pcsx2.lib and object C:\projects\pcsx2\bin\\pcsx2.exp
  Generating code
```

**Comment by gregory38** [comment] 2016-01-09 17:59
Otherwise won't it be possible to provide precompiled .lib for some 3rdpardy (like wx?)

**Comment by gregory38** [comment] 2016-01-09 19:53
Well, not nice.
```
Build execution time has reached the maximum allowed time for your plan (60 minutes).
```

**Comment by turtleli** [comment] 2016-01-09 20:59
git clone depth, zip - would probably save a few seconds at most, it take ~15s each when it works, that max time error was a weird error, it didn't get past the git clone stage.
build priority - If I understand the docs correctly, that only applies if we have multiple projects using appveyor. I don't think it applies to branches.
cache - need to investigate and figure out if it can be used.

> Is link optimization enabled on the build such as LTO/PGO?

Yes, LTO.

> Otherwise won't it be possible to provide precompiled .lib for some 3rdpardy (like wx?)

I'm not sure. It would probably be best to redo where Visual Studio places its build files first before considering this - the files are everywhere, and it does make it more annoying to use grep.

I'll reduce the number of GSdx builds soon.

**Comment by gregory38** [comment] 2016-01-09 21:46
IMHO, LTO likely bangs the resources (cpu & RAM). Would it be possible to remove it for the bot or do you think perf impact will be small.

**Comment by turtleli** [comment] 2016-01-09 22:26
I don't think that'd be easy, or at least I don't know a way.

I'm wondering whether it's just not performing a parallel build for some strange reason. I'll investigate on my repo.

**Comment by gregory38** [comment] 2016-01-09 22:30
In this case, why not a dev build ? (just throwing random idea)

**Comment by turtleli** [comment] 2016-01-09 22:56
I don't think that'd be ideal if we need to benchmark performance.

**Comment by gregory38** [comment] 2016-01-11 08:37
I enabled rolling build until we find a better solution (if it exists).

**Comment by turtleli** [comment] 2016-03-15 19:38
Hmm, it seems like I don't have the correct permissions to restart/cancel builds on this repo. Rolling builds seems to cancel any PR build jobs that are running, and it would be nice to restart them.

**Comment by gregory38** [comment] 2016-03-15 21:24
Let's retry without rolling build.

**Comment by turtleli** [comment] 2016-04-12 23:03
I change the title to AppVeyor/Travis CI issues, since it will most likely be me who deals with any issues.

I've not updated Travis CI to use clang 3.8 yet since that fails to compile PCSX2:
https://travis-ci.org/turtleli/pcsx2/jobs/122381072#L5040

**Comment by gregory38** [comment] 2016-04-30 14:32
Fwiw,  I saw this information here https://www.appveyor.com/updates/2015/07/21
```
"If you see Free (VS 2015) on your plan page then your free account has
already been moved to a new faster environment with Visual Studio 2015.
If your plan is just Free drop us a line and we'll move your account
over to a new environment!"
```
So I send them an email this morning. Maybe it could explain why you're env were faster.

**Comment by turtleli** [comment] 2016-04-30 17:07
It says my plan is Free(G1)

**Comment by gregory38** [comment] 2016-04-30 17:15
Mine is just free

**Comment by gregory38** [comment] 2016-05-15 10:56
What do you think of https://docs.travis-ci.com/user/caching/#ccache-cache for travis.

On my system ccache is really helpful.

**Comment by turtleli** [comment] 2016-05-15 11:37
Looks useful, I'll experiment with it on my repo.

I'll probably add gcc6 at some point too - so far there is more coloured output + extra warnings (misleading indentation) - https://travis-ci.org/turtleli/pcsx2/jobs/130108222

**Comment by gregory38** [comment] 2016-05-15 12:06
Gcc 6 will be nice. If ccache buffer is big enough, it could really cut execution time. Well I guess it depends of IO speed too. But I expect to have few cache miss. Note I'm not sure clang support ccache (well)

**Comment by turtleli** [comment] 2016-05-16 20:09
Ok. ccache helps for 32-bit. clang works too, though I had to manually symlink it.

The 64-bit build doesn't seem to benefit, I'm not sure why.
```
cache directory                     /home/travis/.ccache
cache hit (direct)                     0
cache hit (preprocessed)               9
cache miss                          2003
called for link                      128
preprocessor error                     4
no input file                          4
files in cache                       323
cache size                         439.9 Mbytes
max cache size                     512.0 Mbytes
```

**Comment by gregory38** [comment] 2016-05-16 20:16
Silly question but did you build it after a 64 bit build or after a 32 bit build.

**Comment by turtleli** [comment] 2016-05-16 20:34
I didn't test locally. I set up Travis CI to use separate caches for each build configuration, and I've checked they're not all using the same cache.

**Comment by turtleli** [comment] 2016-06-01 12:25
llvm have switched off their apt repos temporarily so I might remove clang until it's resolved (or I find another package provider).

Also forgot to mention I tried a 64 bit no simd build with Travis CI but it didn't improve caching.

**Comment by gregory38** [comment] 2016-07-06 07:25
Dunno why 64 bits cache doesn't work.

Anyway, I saw that windows max-compress the final binary.
```
7z a -mx9 %folder_name%.7z %folder_name%
```
Is `x` stand for extreme ? Is default option good enough for the compression level? What is the speed impact ?

**Comment by turtleli** [comment] 2016-07-07 20:55
`x` is for compression level. 5 is default. I tested locally with threaded compression turned off. On average, default takes 5.36s (4548kb) and max takes 5.76s (4456kb). I don't think much time will be saved on the buildbot.

**Comment by gregory38** [comment] 2016-07-17 09:32
Good news Appveyor upgrades the infrastructure. We're now around 6 minutes instead of 25. The new VM has 2 CPU cores, I don't know if we already use them (likely) or if we need special conf.

**Comment by gregory38** [comment] 2016-09-04 15:05
Minor stuff. But on travis log you can see those errors.
```
$ clang-3.8-32 --version
clang-3.8-32: command not found
```
I think it is related to the compiler name in `.travis.yml`

**Comment by turtleli** [comment] 2016-09-04 16:12
That was deliberate so each compiler version would use different caches. It might not be necessary anymore though - it seems Travis CI have updated how caching works and it'll take environment variables into account now.

**Comment by turtleli** [comment] 2016-10-01 01:41
I noticed branches with `/` in them fail in AppVeyor. The issue is that the branch name is used as part of the folder name. I'll probably just change it so it doesn't do so.

**Comment by gregory38** [comment] 2016-10-01 08:22
Oh! That's the reason.

**Comment by lightningterror** [comment] 2017-08-31 15:39
Do all GSdx configurations compile with the same speed ? Perhaps the 2 fastest can be picked out of the total 3 atm.

**Comment by turtleli** [comment] 2017-08-31 18:33
? AppVeyor currently compiles only 2 of them (SSE2, AVX2).

**Comment by lightningterror** [comment] 2017-09-01 05:19
Yes I know , I'm just talking about if swapping SSE2 or  AVX2 with SSE4 can give different results.

**Comment by hlide** [comment] 2017-09-01 07:57
Visual Studio 2015 offers:
- SSE
- SSE2
- AVX
- AVX2

Obviously, there is no SSE4. I would have preferred they offer SSE2 instead of SSE and SSE4 instead of SSE2. But they don't.

But honestly, I think GCC do a far better job with SSE/AVX stuff than Visual Studio 10/13. gid15 and I coded an accurate software renderer for GE (PSP) and we had a better result and more constant FPS with GCC. I didn't try with Visual Studio 2015/2017.   

So unless that Appveyor SSE2/AVX2 configuration has nothing to do with visual studio code generation, you cannot have a SSE4 configuration.

**Comment by turtleli** [comment] 2017-09-01 09:16
> Yes I know , I'm just talking about if swapping SSE2 or AVX2 with SSE4 can give different results.

It's not going to make much difference, and AppVeyor doesn't take that long anyway compared to when it was initially set up (~9min instead of ~30min for a build job that includes 2 GSdx builds). It'd probably be fine to even build all 3 on AppVeyor.

> So unless that Appveyor SSE2/AVX2 configuration has nothing to do with visual studio code generation, you cannot have a SSE4 configuration.

It's related to GSdx compile configurations, not VS codegen.

**Comment by turtleli** [comment] 2017-09-01 09:44
On some other notes:
 * AppVeyor has added the old DirectX SDK to their VS2017 image, so we can have a VS2017 build too. It does require switching over to one of the Windows 10 SDKs (their VS2017 image doesn't seem to include the 8.1 SDK that we're currently using). I'm not sure if that will affect Vista compatibility (I haven't checked - IMO we should drop Vista support soon).
 * We could perhaps switch one of the Travis CI GCC builds to use gcc 7.x (I haven't tested on my own repo yet).

**Comment by hlide** [comment] 2017-09-01 09:55
I have VS2017 and I can select Windows SDK 8.1. At least, at work I have several projects which compiles with VS2017 compiler but uses Windows SDK 8.1 (those projects were done in VS2010). But I wonder if SDK 8.1 was an addition to the fact I also installed the VS2015 build tools so I can build VS2015 projects through VS2017.

**Comment by turtleli** [comment] 2017-09-01 10:06
AppVeyor doesn't include the 8.1 SDK on their VS2017 image, or at least that's what their documentation suggests: https://www.appveyor.com/docs/build-environment/

**Comment by willkuer** [comment] 2017-09-01 10:47
Vista has a market share of

- 0.1% according to [w3](https://www.w3schools.com/browsers/browsers_os.asp) and [steam](http://store.steampowered.com/hwsurvey/)
- 0.4% according to [netmarketshare](https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0)

**Comment by turtleli** [comment] 2017-09-01 11:23
> Compatibility with the orphis build bot?

Good question, I completely forgot about it...

**Comment by danilaml** [comment] 2017-09-02 18:43
@turtleli regarding WDK 8.1 on appveyor I saw this https://github.com/appveyor/ci/issues/1694
Can you check if it's true?

**Comment by turtleli** [comment] 2017-09-02 21:18
It's true.

**Comment by lightningterror** [comment] 2018-04-03 09:52
There's also an issue with appveyor not canceling older commits in favor of new ones.
For example if you update a PR several times and push those changes then you will need to wait for all the previous push changes to compile first. You could end up waiting hours.

**Comment by turtleli** [comment] 2018-08-25 09:47
@lightningterror Can you test if you can trigger a rebuild on AppVeyor (you can use my debugger PR)? I changed the AppVeyor permissions slightly.

**Comment by turtleli** [comment] 2018-08-25 09:57
I forgot to mention this a while back. AppVeyor now only retains builds for 6 months.

**Comment by lightningterror** [comment] 2018-08-25 10:05
Nope, I still can't.

**Comment by turtleli** [comment] 2018-08-25 10:13
Try again.

**Comment by danilaml** [comment] 2018-08-25 10:56
AppVeyor has rather peculiar account/user system: https://www.appveyor.com/docs/team-setup/#switching-between-accounts

**Comment by lightningterror** [comment] 2018-09-03 03:16
Is it possible for Appveyor/Travis to disable building either branch or pr when a pr is open from a pcsx2 branch ? Since it's basically duplicating the same work.

**Comment by arcum42** [comment] 2018-09-03 03:26
That does seem rather redundant. I made sure my last commit on my branch passed before doing a pr for it.

**Comment by turtleli** [comment] 2018-09-03 09:46
They're a bit different. The PR build builds master merged with the branch and not the branch on its own.

**Comment by lightningterror** [comment] 2018-09-10 22:57
Were the permissions changed on Travis ? I can no longer restart builds.

**Comment by lightningterror** [comment] 2018-11-18 06:14
Perhaps we can disable **Build pushed branches** and enable daily **Cron jobs** on master branch.
I guess that's one way to make sure separate pushed branches don't build along with the pushed pull request from the repo.

**Comment by lightningterror** [comment] 2020-12-02 20:15
Closing as we moved to github actions.

**Closed by lightningterror** 2020-12-02 20:15 UTC
Labels: Build | Project System
