### ISSUE TITLE
[BUG]: The Incredibles: abyssal performance with the OpenGL Hardware renderer.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#5392] opened 2022-01-23 14:30 UTC
### Describe the Bug

In the game "The Incredibles", there is a very very strange behaviour happening.

When any bit of water shows up on the screen or near the character, the OpenGL hardware renderer will absolutely *tanks* the framerate.

Switching to Vulkan will almost result in a straight doubling of performance, which makes no sense at all, yeah, vulkan is great but that doesn't justify that (especially on Nvidia).

### Reproduction Steps

Load the GSdump, see the problem with the OpenGL render.

### Expected Behavior

The game should deffinitely not be *that* slow with OpenGL.

### PCSX2 Revision

v1.7.2261

### Operating System

Windows 11

### CPU

I9 9900K

### GPU

RTX 3070

### GS Window Screenshots

The bug in action:

Vulkan:
![vulkan](https://user-images.githubusercontent.com/90222976/150683188-bbc2685f-38d8-4175-899f-c203e25c8541.png)

OpenGL:
![OpenGL](https://user-images.githubusercontent.com/90222976/150683197-e51d3d9e-5372-408f-a4c1-4e5b8ac1c216.png)

### Logs & Dumps

GSdump:
[The Incredibles - slow OpenGL perf.zip](https://github.com/PCSX2/pcsx2/files/7920669/The.Incredibles.-.slow.OpenGL.perf.zip)

**Comment by MrCK1** [comment] 2022-01-23 14:44
- 77FPS on Full blending with the dump (GL)
- Ultra drops to 23FPS, are you sure the blending isn't set too high on your end?

**Comment by gilderoylockhart01** [comment] 2022-01-23 14:50
I made sure blending wasn't the issue so I put it to minimum but still, it's not a pretty picture, in the GSdump I have 130 % with 8x in OpenGL and 250 % with vulkan.

**Comment by MrCK1** [comment] 2022-01-23 14:58
I'm not sure what to tell you. As I said, Vulkan will outperform GL in some scenarios. Replaying the GS dump doesn't always give accurate numbers either.

**Comment by JordanTheToaster** [comment] 2022-01-23 15:01
I'm getting 95 fps with OpenGL Full with the dump so I'm not sure what the problem is either.

**Comment by gilderoylockhart01** [comment] 2022-01-23 16:32
Okay, so this might be an nvidia bug only? In this case replaying the GSdump does give me the same results as playing the game normally.

In fact, this performance issue always existed with OpenGL, is there an explanation as to why vulkan is *that*more faster in this case?

**Comment by Mrlinkwii** [comment] 2022-01-23 16:32
>Okay, so this might be an nvidia bug only?

i doubt it   , @JordanTheToaster  has an nvidia GPU

**Comment by gilderoylockhart01** [comment] 2022-01-23 16:33
Which one?

**Comment by JordanTheToaster** [comment] 2022-01-23 16:42
I have an RTX 2060 Super on driver 511.23.

**Comment by gilderoylockhart01** [comment] 2022-01-23 17:52
Yeah, super weird, you have way higher OpenGL performance than my RTX 3070 in this game.

**Comment by Squall-Leonhart** [comment] 2022-01-27 13:38
are you guys testing with a high resolution scale? gilderoy is.

4096x4088, 

check your pcie bus util.

**Comment by gilderoylockhart01** [comment] 2022-01-29 10:08
My PCIE bus utilization is very low as you can see:

![Capture d’écran 2022-01-29 110552](https://user-images.githubusercontent.com/90222976/151656830-0e24ab3f-5965-4541-9007-657578b6e25a.png)

But look at this very strange graph, the gpu core utilization ramps up slowly then reach the 100% mark with OpenGL, note that this is with the GSdump so the game startup is not taken into account here:

![Capture d’écran 2022-01-29 110612](https://user-images.githubusercontent.com/90222976/151656879-43e408ad-46e9-4e03-b0e6-3f3837b2f2e6.png)

**Comment by Squall-Leonhart** [comment] 2022-01-29 10:42
whats the core clock like when the utilisation peaks?

**Comment by gilderoylockhart01** [comment] 2022-01-29 10:45
The core clock jumps to 2100Mhz:

![image](https://user-images.githubusercontent.com/90222976/151658034-d193d29c-7f4f-4d1d-a562-c029f7f76601.png)

**Comment by Squall-Leonhart** [comment] 2022-01-29 10:46
have you got resizable bar enabled?

**Comment by gilderoylockhart01** [comment] 2022-01-29 10:46
Yes.

**Comment by Squall-Leonhart** [comment] 2022-01-29 11:19
test with it disabled, the behavior sounds similar to one experienced with dxvk 1.9.3 in https://github.com/doitsujin/dxvk/issues/2438 where the gpu ran out of available memory, nvidia gpu's get unusually high load under low video memory scenarios contrary to what you'd expect.

**Comment by gilderoylockhart01** [comment] 2022-01-29 12:25
Yup, you are effectively right, I tested with re-bar off and I get an insanely improved performance, the speed now hovers between 190 and 201% in GL, which makes more sense regarding the GL to Vulkan scaling.

**Comment by lightningterror** [comment] 2022-04-23 16:36
Closing as this looks like an external issue.

**Closed by lightningterror** 2022-04-23 16:36 UTC
Labels: Upstream | External
