### ISSUE TITLE
[BUG]: HTTP over Sockets does not appear to work properly

### ISSUE THREAD

**Issue by Zero1UP** [PCSX2/pcsx2#10433] opened 2023-12-18 06:07 UTC
### Describe the Bug

Using the sockets option for networking, HTTP requests do not always seem to work properly, For instance downloading a patch file for SOCOM Combined Assault (NTSC). This works fine if you use PCAP Switched.

### Reproduction Steps

Using Socom Combined Assault, set the DNS IP to 67.222.156.250 and use Sockets. Once you connect online and you select the universe, you will be prompted to download the update. Let it download and once the progress bar fills it SHOULD ask you to save to the memory card. More times than not it will just stop downloading.

### Expected Behavior

File should download and prompt the player to save it.

### PCSX2 Revision

v1.7.5309

### Operating System

Windows 10

### CPU

AMD Ryzen 9 3900x

### GPU

Nvidia GTX 970

### Logs & Dumps

[SCA Logs.zip](https://github.com/PCSX2/pcsx2/files/13700001/SCA.Logs.zip)

**Comment by xCENTx** [comment] 2023-12-19 15:13
Analyzing the dumps it seems like the SOCKET protocol might have some issues with writing the data to memory card and backpatching the result

**Comment by Blackburn29** [comment] 2023-12-20 03:26
> Analyzing the dumps it seems like the SOCKET protocol might have some issues with writing the data to memory card and backpatching the result
> 
> You said sockets does not always seem to work properly, which I take to mean that you have encountered instances where it would work, do you have a log of sockets where it works to better compare differences ?

The codes loaded in this dump appear to be a DNAS bypass and a domain override based on the addresses in the log output. Which appear to be unrelated to this bug report.

**Comment by stenzek** [comment] 2023-12-20 05:03
I'm not going to close this myself since it's not my area, but anything that requires tampering with online authentication potentially violates DMCA, and not really something we as a project can be affiliated with.

I'd suggest trying to reproduce the bug in a different scenario that isn't dependent on bypassing access control. That would make it possible for us to investigate without risk.

**Comment by Blackburn29** [comment] 2023-12-20 05:08
> I'm not going to close this myself since it's not my area, but anything that requires tampering with online authentication potentially violates DMCA, and not really something we as a project can be affiliated with.
> 
> I'd suggest trying to reproduce the bug in a different scenario that isn't dependent on bypassing access control. That would make it possible for us to investigate without risk.

There is 0 risk here. It’s simply a method of connecting to a local dev server to emulate online functions.

**Comment by stenzek** [comment] 2023-12-20 05:12
Are you a lawyer? Because I am not, and thus prefer to be cautious with such things. There is precedent against emulating online servers, even more so when we're talking about authentication (whether it be CD keys, hardware, etc).

**Comment by Blackburn29** [comment] 2023-12-20 05:17
> Are you a lawyer? Because I am not, and thus prefer to be cautious with such things. There is precedent against emulating online servers, even more so when we're talking about authentication (whether it be CD keys, hardware, etc).

The entirety of this emulator falls under your statement as well. So that’s not really relevant. As for a lawyer no, but I know many. 

I’m not here for a bickering match. I’ll just work with the dev9 contributor directly to resolve the issue.

**Comment by Zero1UP** [comment] 2023-12-20 05:18
> I'm not going to close this myself since it's not my area, but anything that requires tampering with online authentication potentially violates DMCA, and not really something we as a project can be affiliated with.
> 
> I'd suggest trying to reproduce the bug in a different scenario that isn't dependent on bypassing access control. That would make it possible for us to investigate without risk.

I never specified that it was even required. For whatever reason when I made a backup of my games they always fail the internal DNAS (-403) check so I just use a bypass as a means of convenience so I don't have to constantly swap disks out of my drive. It doesn't change the outcome. Most people don't have this issue, all you have to do is load up the game.

**Comment by stenzek** [comment] 2023-12-20 05:22
Emulating hardware is not the same as emulating online services.

I politely asked for an alternative way for us to reproduce the bug, but if you're not interested in doing so, then we're done here.

**Closed by stenzek** 2023-12-20 05:22 UTC
Labels: Bug
