### ISSUE TITLE
Grand Theft Auto: Vice City HW text looks wrong (PAL)

### ISSUE THREAD

**Issue by AmbientMalice** [PCSX2/pcsx2#1329] opened 2016-04-30 06:03 UTC
-PCSX2 version: v1.5.0-20160429001616

-PCSX2 options: Defaults.

-Plugins used: Defaults.

-Plugin settings: GL HW & GL SW.

-Description: 2D elements like text have odd patterns similar to embossing. Not affected by upscaling, but more noticable.

SW
![gsdx_20160430155027](https://cloud.githubusercontent.com/assets/10704701/14934207/feaaa2f8-0eec-11e6-95a3-0b819aa7fc26.png)
HW
![gsdx_20160430155024](https://cloud.githubusercontent.com/assets/10704701/14934202/b452401c-0eec-11e6-949b-86e94647286c.png)

-How to replicate: Run the game. Issue appears anytime normal HUD is active.

-Last known version to work: Don't know. I think it was always this way.

-PC specifications: CPU: Intel Q9400z GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit

**Comment by pepiczech77** [comment] 2016-04-30 08:11
You are using old version of PCSX2. Try latest master.

**Comment by AmbientMalice** [comment] 2016-04-30 08:49
@pepiczech77 Sorry, that was a typo.

**Comment by refractionpcsx2** [comment] 2016-04-30 11:32
can you show us your GSDX settings?

**Comment by AmbientMalice** [comment] 2016-04-30 11:37
![gta_set](https://cloud.githubusercontent.com/assets/10704701/14935636/b7c1ed54-0f1b-11e6-8a4b-ccb5fbbec282.PNG)

**Comment by refractionpcsx2** [comment] 2016-04-30 11:39
Okay can you try again with anisotropic filtering off, just to rule that out.  Maybe play with a few other settings to see if they are causing it

**Comment by AmbientMalice** [comment] 2016-04-30 11:52
Tried various settings, and different backends. No difference.

I did notice the following when the resolution is cranked up:
This is software.
![shadow_1](https://cloud.githubusercontent.com/assets/10704701/14935666/34a77c20-0f1d-11e6-8d67-b0b372759c4a.png)
This is HW.
![shadow_2](https://cloud.githubusercontent.com/assets/10704701/14935667/3bfd7b28-0f1d-11e6-9f52-c7102881828a.png)
The drop shadow+overlay texture isn't being layered properly.
![shadow_3](https://cloud.githubusercontent.com/assets/10704701/14935672/5b84750a-0f1d-11e6-88c0-39acbe2341f2.jpg)

**Comment by FlatOutPS2** [comment] 2016-04-30 12:03
Looks like a similar issue to #935

**Comment by DPersonalized** [comment] 2016-05-02 17:54
Does setting "Sprite" to "Half" make things any better?

**Comment by MrCK1** [comment] 2016-05-16 01:38
Half sprite does not fix anything. Anisotropic filtering, 8-bit textures, Blending Unit changes show no difference for me.

**Comment by FlatOutPS2** [comment] 2016-05-16 13:45
> Half sprite does not fix anything. Anisotropic filtering, 8-bit textures, Blending Unit changes show no difference for me.

What about full sprite and the round sprite equivalents? If you haven't already, you could also try some TC offset values.

**Comment by DPersonalized** [comment] 2016-05-16 16:01
> What about full sprite and the round sprite equivalents? If you haven't already, you could also try some TC offset values.

Just tried all those things with my PAL copy and none of them worked. This is with D3D11, mind.

**Comment by MrCK1** [comment] 2016-05-18 02:03
Bad effect happens on all 3 HW renderers (OGL, DX11, DX9) 

My tests were done on OGL

**Comment by MrCK1** [comment] 2016-08-14 04:58
PR #1514 improves the text situation in this game. Unfortunately, I'm not sure why it isn't being applied consistently. 

The only areas where the overlay transparency is fixed are the money counter, health, and location names. Other elements such as the pause menu are not affected for some reason.

Appveyor PR:

![vicecitytext_appveyorpr](https://cloud.githubusercontent.com/assets/16314399/17647317/dbd3424c-61b9-11e6-9f59-da9261eac07f.png)

Git Builds:

![vicecitytext_gitbuild](https://cloud.githubusercontent.com/assets/16314399/17647318/e161eb5a-61b9-11e6-9158-9f6e67743a71.png)

**Comment by FlatOutPS2** [comment] 2016-08-14 15:43
@MrCK1 Can you post a GS Dump of the issue?

**Comment by MrCK1** [comment] 2016-08-14 16:20
@FlatoutPS2 will do later

**Comment by refractionpcsx2** [comment] 2016-08-14 16:25
When you say git builds, you don't mean the automatic ones no?

**Comment by MrCK1** [comment] 2016-08-14 16:41
@refractionpcsx2 Yes, I'm talking about the automatic ones. I could always compare 1.4.0 stable, but the end result is the same up until this PR

**Comment by gregory38** [comment] 2016-08-14 22:57
Oh not too bad. I'm afraid it will be difficult to do a better job. But I need to confirm first the remaining issue.

**Comment by MrCK1** [comment] 2016-08-15 02:27
@FlatOutPS2 [Here you go](http://www.filedropper.com/vicecitynewalphatestogl) :)

**Comment by gregory38** [comment] 2016-08-15 09:42
Please test again latest git.

For the record, it was partially working as the game uses 2 depth format 16 and 24 bits. Code was only tested on 24 bits. You guess it right, the remaining letters was a 16 bits depth.

**Comment by MrCK1** [comment] 2016-08-15 18:02
@gregory38 Great job, but unfortunately now the minimap texture isn't clipping correctly. [Here's another GS dump](http://www.filedropper.com/vicecityminimapclipregression)

![vicecity_minimap](https://cloud.githubusercontent.com/assets/16314399/17673736/83847b96-62f0-11e6-9e64-d3bfc6f42d5c.png)

**Comment by gregory38** [comment] 2016-08-15 21:49
There is something wrong with my depth optimization. I need to check the value of the vertex directly as the vertex trace got some strange rounding.

**Comment by FlatOutPS2** [comment] 2016-08-15 21:50
This issue also applies to GTA III. It also has the same regression with the mini map.

**Comment by gregory38** [comment] 2016-08-15 21:54
Sorry bedtime for me. But I'm happy that regression was quickly spotted

**Comment by gregory38** [comment] 2016-08-16 05:35
Issue fixed. Just a minor rounding issue.

**Comment by FlatOutPS2** [comment] 2016-08-25 10:50
This has now been fixed in OGL and DX renderers, so time to close this.

**Closed by FlatOutPS2** 2016-08-25 10:50 UTC
Labels: Fixed in openGL, GSdx: Hardware
