### ISSUE TITLE
[BUG]: Graphical glitches in ATV Offroad Fury 2 (USA)

### ISSUE THREAD

**Issue by miccmike** [PCSX2/pcsx2#7611] opened 2022-12-18 12:30 UTC
### Describe the Bug

Using the ReDump hash of ATV Offroad Fury 2 (USA) rev 2.00. Graphics during races go insane, making the game unplayable
![ATV Offroad Fury 2_SCUS-97211_20221218131643](https://user-images.githubusercontent.com/112952233/208298039-19c298c5-f6bd-41fb-ba1f-e52f0220a1bc.png)

### Reproduction Steps

enter any race

### PCSX2 Revision

nightly v1.7.3732

### Operating System

Windows 10 (64bit)

### CPU

ryzen 5 3600

### GPU

gtx 1660

### GS Window Screenshots

![ATV Offroad Fury 2_SCUS-97211_20221218132338](https://user-images.githubusercontent.com/112952233/208298463-801a335c-22f8-4af9-8e9f-98d3529658cc.png)

### Logs & Dumps

[ATV Offroad Fury 2_SCUS-97211_20221218132338.gs.zip](https://github.com/PCSX2/pcsx2/files/10253819/ATV.Offroad.Fury.2_SCUS-97211_20221218132338.gs.zip)

**Comment by Mrlinkwii** [comment] 2022-12-18 13:04
try playing in software mode only

**Comment by miccmike** [comment] 2022-12-18 14:50
yeah thats fixes it, probably should be marked somewhere tho. thanks

**Comment by refractionpcsx2** [comment] 2022-12-18 16:16
It's still a bug, please leave this open.

**Comment by SlyCooperReloadCoded** [comment] 2022-12-18 18:48
Since this is a Rainbow Studios game, I should mention that another game from them, MX Unleashed, also had a bug similar to this at one point, but it was fixed by either disabling or enabling Instant VU1.  That doesn't fix this though, but maybe it could be related?  Switching to Software and then back to hardware does temporarily fix this, but water will turn invisible.

**Comment by parkerlreed** [comment] 2023-02-04 04:12
Software mode is also subpar for this game on many platform. Slows to a crawl on Steam Deck

**Comment by refractionpcsx2** [comment] 2023-02-04 04:15
I think saying "Many platforms" when you mean just Steam Deck is a bit disingenuous.  You have to remember Steam Deck was never our primary focus, it is a low powered handheld device, it's gonna struggle with more taxing stuff like software mode, that's just how things are.

We know that's not an ideal solution but that's the best there is right now.

**Comment by RedDevilus** [comment] 2023-02-04 04:17
ATV Offroad Fury 3 I had to disable MTVU as it made performance worse, I wonder if that might also be a similar issue. Ignoring the graphical issues at the moment for comparison sake.

**Comment by stenzek** [comment] 2023-02-04 04:21
> Software mode is also subpar for this game on many platforms. Slows to a crawl on Steam Deck

Such comments are entirely unhelpful and unconstructive. Having a low-power quad core struggle with software? Of course that's the case. Any 6+ core device made in the last 5 years will be fine.

**Comment by parkerlreed** [comment] 2023-02-04 04:47
I didn't mean anything by it... Sorry the wording was bad. 

I was just trying to keep the discussion going as this is a game that I love and would like to see running better. Was thinking someone might have had a suggestion or tweak to try out.

@RedDevilus Tried Multi threaded VU off with OpenGL SW and didn't see much if any difference. Thanks for the tip.

I'll keep trying settings to see if anything helps.

**Comment by SlyCooperReloadCoded** [comment] 2023-02-04 08:32
Software renderer isn't entirely irrelevant here.  The game's compatibility page says that if you go ingame, switch to Software, then back to hardware, the issue will be fixed, but there will be no water anywhere, but only visually, you can still ride through the "water".

**Comment by parkerlreed** [comment] 2023-02-04 16:11
I had tried switching renderer mid way but since it was a game override and not a global setting I couldn't find a way to change it while the game was running. Is there a secret to changing the game specific override for the Qt interface?

**Comment by Mrlinkwii** [comment] 2023-02-04 16:14
@parkerlreed  press f9

**Comment by SlyCooperReloadCoded** [comment] 2023-02-04 16:17
I mean that's a workaround, not a real solution, I just thought it was a good thing to bring up since software renderers were mentioned.

**Comment by stenzek** [comment] 2023-02-04 17:03
This is turning into a support thread and isn't the purpose of the issue tracker - please use the discord server for that.

**Comment by Bubblegum3390** [comment] 2023-10-31 21:50
An update to this issue - as of recent nightly builds (tested 1.7.5175) the water effect now renders correctly on all hardware renderers at native resolution. Any upscaled resolution results in the water effect being broken like known. A workaround for high resolution play is to go to Graphics - Advanced settings and set Hardware Download Mode to Disabled (Ignore Transfers) this will disable the water graphics effect.

**Comment by SlyCooperReloadCoded** [comment] 2023-11-01 03:11
I decided to try this, and yeah, native res on hardware works now, but increase the internal resolution and it breaks.

**Comment by refractionpcsx2** [comment] 2023-11-01 09:09
Yes upscaling makes it really explode, native looks like it works but I don't think it's quite right, a good year for that is Splashdown which is the same dev and they do the same trick for water

**Comment by TheTechnician27** [comment] 2024-02-13 22:47
I can confirm that native resolution works just fine for me, but the water effects are, as pointed out, a bit broken on HW mode.

[ATV Offroad Fury 2_SCUS-97211_20240213163134.zip](https://github.com/PCSX2/pcsx2/files/14272916/ATV.Offroad.Fury.2_SCUS-97211_20240213163134.zip)

Every single place in the game that has water loaded seems to have 3 readbacks, while everywhere that doesn't has 0. This contrasts with ATVOF 3 which has only one readback with water and ATVOF 1 which has no water whatsoever.

As noted, upscaling breaks sprites like nobody's business.

[ATV Offroad Fury 2_SCUS-97211_20240213163827.zip](https://github.com/PCSX2/pcsx2/files/14272943/ATV.Offroad.Fury.2_SCUS-97211_20240213163827.zip)

While upscaling (but not while on native), if you change half-pixel offset to 'align to native', the game just freezes and isn't recoverable without shutting down PCSX2. This does not happen with any other upscaling fix.

If you select 'disable depth emulation', it fixes all the garbage, but the water is still gone.

**Comment by refractionpcsx2** [comment] 2024-02-13 22:50
GS dumps won't show the problem because it relies on a readback to the EE and processing in the core, which GS Dumps don't reproduce.

**Comment by TheTechnician27** [comment] 2024-02-13 22:50
> GS dumps won't show the problem because it relies on a readback to the EE and processing in the core, which GS Dumps don't reproduce.

It so happens that the multiframe I sent in the second one shows the problem, at least on my end.

**Comment by refractionpcsx2** [comment] 2024-02-13 22:53
yes, it happens because it's baked in to the dump.

**Comment by TheTechnician27** [comment] 2024-02-13 22:57
> yes, it happens because it's baked in to the dump.

Oh, I see. So you can see the problem, but it won't give you anything useful about why it happened in the first place? Makes sense. Any thoughts on why Align to Native might crash the game only when in that garbage state? I speculate that the one readback being done away with when 'disable depth emulation' is enabled is what's fixing the garbage, but I don't know enough to say that beyond just conjecture. I'll be more than happy to test ATVOF 3 and 4 to see if I can get similar results. I tested 3 already on native resolution, but I hadn't realized the issue now was solely with upscaling.

**Comment by refractionpcsx2** [comment] 2024-02-13 23:00
disable depth emulation screws up the reading back, so instead of it half working it doesn't work at all, though I'm not sure on the correct solution atm.

native is also a problem with the effect, though offroad fury 2 shows it less than Splashdown.

**Comment by TheTechnician27** [comment] 2024-02-13 23:31
[ATV Offroad Fury 3_SCUS-97405_20240213172937.zip](https://github.com/PCSX2/pcsx2/files/14273308/ATV.Offroad.Fury.3_SCUS-97405_20240213172937.zip) It looks like the water in Offroad Fury 3 works just fine, by comparison. 1 readback, but upscaling in this game breaks nothing. So given it works in 1 and 3 and Maj says it works in 4, this is exclusively a 2 problem. Which leads us back to square 1, but at least we can rule out this being present in the other games.

**Comment by SlyCooperReloadCoded** [comment] 2024-02-14 02:59
3 and 4 aren't Rainbow Studios games which I bet has something to do with it.  I recall MX Unleashed, another Rainbow Studios game, had a similar problem with terrain textures at certain angles, and something to do with Instant VU1 was the fix.  Perhaps that's a lead?

**Closed** 2024-08-10 22:47 UTC
Labels: Bug, GS: Hardware, GS: Readbacks
