### ISSUE TITLE
[onepad][linux] DS3 clone not recognized at all

### ISSUE THREAD

**Issue by clbr** [PCSX2/pcsx2#1291] opened 2016-04-13 18:01 UTC
I have a DS3 clone controller connected via USB. The system sees it fine, other emulators see it fine, but onepad doesn't see it at all - the configuration dialog only offers keyboard/mouse in the dropdown.

I'm using 1.4.0 from the official ppa.

$ ./sdl-jstest --list
Found 1 joystick(s)

Joystick Name:     'Gasia Co.,Ltd PS(R) Gamepad'
Joystick Number:    0
Number of Axes:    27
Number of Buttons: 19
Number of Hats:     0
Number of Balls:    0

**Comment by clbr** [comment] 2016-04-14 18:19
I see the official build was using SDL2, so I built 1.4.0 myself with SDL 1.2. And what do you know, my controller is seen and working.

I suggest to move the official package back to SDL 1.

**Comment by johnathana** [comment] 2016-04-17 09:34
I can confirm clbr. 

I am using ubuntu:14.04 and it seems SDL2 does not detect the gamepad. On the other hand libsdl1.2debian:i386 does the job but you have to recompile onepad against that library.

Probably it's distro specific because under fedora SDL2 works fine.

**Comment by gregory38** [comment] 2016-04-17 10:52
There are several versions of SDL2. Could you give us the exact fedora/ubuntu version?

**Comment by clbr** [comment] 2016-04-17 12:06
Mine is 2.0.2+dfsg1-3ubuntu1.

**Comment by gregory38** [comment] 2016-04-17 12:28
And let's me guess fedora is 2.0.4?

**Comment by johnathana** [comment] 2016-04-17 18:09
Sorry for my late reply.

For Fedora: SDL2-2.0.3-7
For Ubuntu: 2.0.2+dfsg1-3ubuntu1.1 

Seems that SDL-1.2 detects gamepads throught /dev/input/js*, that works fine. I had to use the onepad plugin from pcsx2-1.2.2-r5896-lnx.

**Comment by clbr** [comment] 2016-04-17 19:12
> Seems that SDL-1.2 detects gamepads throught /dev/input/js*

My kernel does not have JS support at all, so SDL 1.2 also works via the evdev node under /dev/input/event*.

**Comment by gregory38** [comment] 2016-04-26 11:52
Honestly it seems to be an SDL 2.0.2 bug (SDL 2.0.4 is out)

**Comment by hazrpg** [comment] 2016-06-04 15:32
Just a suggestion, but Ubuntu 16.04 is now out and comes packaged with 2.0.4 of the SDL libraries. If you have the time to upgrade (the upgrade process has worked flawlessly for me and many many others), and see if that fixes your issue? Ubuntu 16.04 seems to be far more stable than 14.04 ever was.

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04 LTS
    Release:	16.04
    Codename:	xenial

    $ apt show libsdl2-2.0-0
    Package: libsdl2-2.0-0
    Version: 2.0.4+dfsg1-2ubuntu2

**Comment by gregory38** [comment] 2017-04-28 09:35
New onepad version available. Code is based on the SDL2 auto-setup feature. It should work now.

**Comment by lightningterror** [comment] 2018-02-23 16:31
I'll close this since it has been marked as fixed and no feedback was provided for a year now.

If the problem remains it can be reopened.

**Closed by lightningterror** 2018-02-23 16:31 UTC
Labels: Fixed, OS: Linux, Plugin: OnePad, Upstream | External, Waiting feedback
