### ISSUE TITLE
[Debugger bug] Enabled breakpoints interfere with step out

### ISSUE THREAD

**Issue by Aced14** [PCSX2/pcsx2#1182] opened 2016-02-15 05:35 UTC
**PCSX2 version:**
v1.5.0-dev-336-g1718d07 (2016-02-14)

**PCSX2 options:**
Defaults. No options modifications affect this issue.

**Plugins used:**
Defaults (GSdx32-AVX, LyliPad, SPU2-X, cdvdGigaherz, USBnull, FWnull and DEV9ghzdrk). No particular plugins affect this issue.

**Plugin settings:**
GSdx (Direct3D11 software mode). No settings modifications affect this issue.

**Description:**
In PCSX2's debugger, pressing the "Step Out" button doesn't currently break at the right spot if an enabled breakpoint is situated on the way to the return address. It'll break on the enabled breakpoint instead of the return address.

Stepping out should ignore all enabled breakpoints, to prevent them from interfering with its intended purpose.

**How to replicate:**

1. Use PCSX2 v1.5.0-dev-336-g1718d07 (2016-02-14) or later. Older versions are affected by this bug, but need more replication steps than what I've provided.
2. Launch PCSX2 and fast boot any game.
3. Open the debugger and add 2 breakpoints that you're sure will be reached (has to be deeper in the game's ELF logic than the entrypoint). Both breakpoints must be enabled. To simplify testing, they should both be situated in the same function and within a few lines of each other.
4. Fast boot the game again and wait for the first breakpoint to be triggered.
5. In the debugger's top left panel, take note of the ra (return address) register's value.
6. Press the "Step Out" button. It'll break on the second breakpoint.
7. Press the "Step Out" button again. It'll break on the return address.
8. Step 6 didn't work as expected. It should've had the same outcome as step 7. In other words, it should've resumed running, ignored the 2nd breakpoint and breaked on the return address.

**Last known version to work:**
Never worked. Oldest tested version: v1.3.1-187-g0ab0c6c (2015-04-27).

**PC specifications:**
CPU: Intel Core i7 2600K @ 3.4GHz; GPU: XFX Radeon HD 6970 2GB; OS: Windows 7 SP1

**Other comments:**
@Kingcom @NZJenkins FYI :).

**Comment by Kingcom** [comment] 2016-02-15 06:12
This is working as intended, and works this way in other debuggers too (eg Visual Studio). Also note that step out doesn't just use ra, it analyzes the current stack frame (and the code of the function) to figure out where to return to. I think that currently requires a specific BIOS version, but it's easy to port to other versions.

To everyone fixing all these issues, sorry for not being any help. Not much time at the moment.

**Comment by turtleli** [comment] 2016-02-15 20:12
I agree with Kingcom - this is expected behaviour. So I'm closing this issue.

**Closed by turtleli** 2016-02-15 20:12 UTC

**Comment by Aced14** [comment] 2016-02-16 04:35
In that case, my bad :(. From my perspective it felt kind of odd. Didn't realize other debuggers honour enabled breakpoints in the midst of stepping out.

@Kingcom Even though I've been opening all these recent issues, I absolutely love the debugger. Thanks a bunch for having created it in the first place :)! I've spent countless hours using it over the past few years to create hacks that would've otherwise been next to impossible without it. My intent with the issues is to help shed light on longstanding bugs/omissions that may have gone unnoticed.
