### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by navaronbracke** [PCSX2/pcsx2#8385] opened 2023-03-12 19:36 UTC
### Describe the Bug

When editing input bindings for a controller, pressing a controller button to assign an input also assigns a keyboard key, despite only the controller button being pressed.

### Reproduction Steps

1) Connect a Dualshock 4 controller
2) Go to `Settings > Controllers > Controller Port 1 DualShock 2`
3) Ensure that the `Bindings` tab is selected
4) Click `New Profile` at the bottom and give it a name. Don't copy over settings from another profile
5) Click the `D-pad Up` control and press the `D-pad Up` key on the Dualshock 4 controller
6) The key now displays `Keyboard/Up & SDL-0/DPadUp`. This should have been `SDL-0/DPadUp` because the keyboard key was not pressed.

![image](https://user-images.githubusercontent.com/23480364/224568702-77a3276f-76b7-4e46-bdf3-0d6be57bcf71.png)

### Expected Behavior

Only the controller button is assigned to the input. No keyboard key is assigned to the input.

### PCSX2 Revision

NightlyBuild 1.7.4223

### Operating System

Windows 10 (64bit)

**Comment by JordanTheToaster** [comment] 2023-03-12 21:05
Cannot reproduce.

**Comment by Buzzardsoul** [comment] 2023-03-12 21:11
> Cannot reproduce.

Same here.

**Comment by refractionpcsx2** [comment] 2023-03-12 21:11
I suspect you have steam open, close it, then restart pcsx2 and try again.

As it can't be reproduced by anybody else, it's probably user error, I would suggest using our forum or discord.

**Closed by refractionpcsx2** 2023-03-12 21:11 UTC
Labels: Bug

**Comment by navaronbracke** [comment] 2023-03-13 11:54
Can confirm that closing Steam did work.
