### ISSUE TITLE
[BUG]: Need For Speed Undercover (SLUS-21801) - Purple ground in software mode

### ISSUE THREAD

**Issue by Satan86** [PCSX2/pcsx2#5078] opened 2021-11-28 11:26 UTC
### Describe the Bug

When using SW renderer, the ground will have shades of purple, doesn't happen on either HW renderer

### Reproduction Steps

Go into any quick race or career mode, as soon as you start driving a car you'll see it

### Expected Behavior

Ground shouldn't have purple colours, as it doesn't on PS2

### PCSX2 Revision

dev-2083

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 5600x

### GPU

GTX 1050 Ti

### GS Settings

![image](https://user-images.githubusercontent.com/61447828/143765560-9a74be9b-d7f9-4b8b-80ae-e1f1c687720b.png)
(Auto flush on or off makes no difference, it's just to improve performance)

### Emulation Settings

Default preset

### GS Window Screenshots

![image](https://user-images.githubusercontent.com/61447828/143765599-0a6ff455-e72b-41e4-894c-a50338370543.png)

### Logs & Dumps

[gs_20211128112047.gs.zip](https://github.com/PCSX2/pcsx2/files/7613419/gs_20211128112047.gs.zip) GS Dump
[SLUS-21801 - (7029F4DB).zip](https://github.com/PCSX2/pcsx2/files/7613422/SLUS-21801.-.7029F4DB.zip) Save State jumping right to the gameplay

**Comment by MrCK1** [comment] 2021-12-07 05:55
@Satan86 Are you able to check 1.6 to see if the issue is present there? It would be nice to narrow down the build if it's a regression.

**Comment by refractionpcsx2** [comment] 2022-02-25 21:11
Fixed by #5569

**Closed** 2022-02-27 15:22 UTC
Labels: Bug, GS: Software
