### ISSUE TITLE
GSdx video recording: Wrong video FPS when running game in Progressive scan

### ISSUE THREAD

**Issue by bositman** [PCSX2/pcsx2#832] opened 2015-09-17 09:51 UTC
-Description: When recording a video with the internal recording feature of GSdx (F12) and running a game in progressive scan mode, the video file created has 29,97 FPS instead of the 59,94 FPS it should have, resulting in half speed videos.

-How to replicate: Boot a game, set it in progressive scan mode and record a video using F12

-Last known version to work: Never worked, @gigaherz had hacked me a GSdx that fixed this by setting the game in NTSC mode when running in progressive scan but it was a quick hack.

-Other comments: I think the code responsible is here: https://github.com/PCSX2/pcsx2/blob/master/plugins/GSdx/GSCapture.cpp#L180

@avih I believe you could tackle this :)

**Comment by avih** [comment] 2015-09-17 10:31
Surely @gabest11 would have more to say on this than myself ;)

**Comment by bositman** [comment] 2015-09-17 10:33
Yeah but given no one has fixed it over 10 years I thought someone who is around could tackle it :P

**Comment by avih** [comment] 2015-09-17 10:40
Well, while a popular feature with some, I've never used the recording myself.

I'd have expected it to either record 25/29.97 fps where each frame is interlaced (which could be deinterlaced back to 50/59.94 fps afterwards), or indeed record 60 (59.94?) fps progressive.

Does it record 29.97 interlaced frames normally (not in progressive mode)? or 29.97 progressive frames? or 29.97 fps fields?

**Comment by bositman** [comment] 2015-09-17 12:19
This is the mediainfo output, It does not show a scan type and from what I read this is what happens when you have mixed interlaced modes in a file

General
Format                         : AVI
Format/Info                    : Audio Video Interleave
File size                      : 166 MiB
Duration                       : 9s 443ms
Overall bit rate               : 148 Mbps

Video
ID                             : 0
Format                         : YUV
Codec ID                       : YUY2
Codec ID/Info                  : YUV 4:2:2 as for UYVY but with different component ordering within the u_int32 macropixel
Duration                       : 9s 443ms
Bit rate                       : 148 Mbps
Width                          : 640 pixels
Height                         : 480 pixels
Display aspect ratio           : 4:3
Frame rate                     : 29.970 fps
Color space                    : YUV
Chroma subsampling             : 4:2:2
Compression mode               : Lossless
Bits/(Pixel*Frame)             : 16.026
Stream size                    : 166 MiB (100%)

**Comment by avih** [comment] 2015-09-17 12:47
> -Description: When recording a video with the internal recording feature of GSdx (F12) and running a game in progressive scan mode, the video file created has 29,97 FPS instead of the 59,94 FPS it should have, resulting in half speed videos.

For the sake of this discussion I'll say "60" when I actually mean 59.94. Please let me know if this simplification hurts the discussion.

I'm not sure I fully understand the description (I might, but I want a clarification).
- Does it only records half of the frames you want recorded?
- Does ir record more frames than you want recorded? (e.g. that every other frame is a copy of the previous frame).
- Does it record all frames, but by default plays at half speed, but if you speed it up during playback to 2x speed, then it plays correctly at 60 fps?
- Or something else?

I did some tests, as far as I can tell so far, it records always at the full frame rate (60), and records exactly all the frames which show on screen. If the content is interlaced, then it will show with blend/blur/bob/whatever deinterlace method you choose. Overall, while I didn't try to exhaust all combinations, it looks to me like it does the right thing, or at least a thing from which the right thing can be later extracted (e.g. weave ends up in practice in 30 frames where each of them is interlaced, but if the recording is of 60fps, then you might want to discard every other frame and then deinterlace the rest. important - the recording should be at the exact vertical resolution of GSdx to be able to deinterlace later).

If the content is frame-oprogressive, then I can see it still records all frames (60 per second), but since the content itself only displays 30 fps, the recording ends up with every other frame a duplicate of the previous frame, _and_ it indeed has a 30fps property of the clip so it plays at half speed. However, you you speed up playback x2, then it plays at the correct speed.

So my leading questions are:
1. What exactly you see at the GS window title? (interlace mode, base resolution, etc - everything).
2. How is GSdx configured - specifically what internal resolution do you use? x2? x3? custom? (which?) etc.
3. Which resolution do you use for the recording?

And the main question after I have replies for the above:
- With the clip which plays at half speed and which you consider buggy - if you speedup playback by x2 speed, does it become perfect (I'm guessing smooth 60fps) ? or does it still have issues? (ignore the sound for now).

**Comment by gabest11** [comment] 2015-09-17 13:01
I think vsync is called twice for progressive mode, once after sending data, once empty. In that case, dups are saved and half rate is no good. Not sure if it is always the case, but than we could just set full rate on the video.

**Comment by avih** [comment] 2015-09-17 22:10
Just collecting some data for the record and as a base for discussion:
- Shadow of the colossus (PAL) in 60hz: title shows "**Interlaced (field)**", recording ends up with 60fps and plays at normal speed but every other frame is a duplicate (so effectively 30fps). Also, in PCSX2 it never shows interlace artifacts and doesn't need deinterlacing.
- Shadow of the colossus (PAL) in 60Hz progressive: the title shows "**Progressive (frame)**", recording ends up as 29.97 and plays at half speed, but speeding it x2 results in identical to the above (60 frames per second of playback, the game looks in normal speed and every other frame is a duplicate).
- Ico (PAL) 60hz: title shows "**progressive (frame)**" and the result is the same as with SoTC in progressive mode (half speed playback by default, every other frame is a dup, speeding it up x2 looks in normal speed).
- Disgaea 2: Title shows **Interlaced (frame)** and this time it's actually interlaced (artifacts visible if not deinterlacing) - recording ends up as 60fps without duplicates and plays back at normal speed. This is expected with bob, but it also happens with weave, which is really weird IMO. It _looks_ like we get 60 different interlaced frames per second (I single stepped the frames), or 120 fields/sec, which just can't be true. But anyway, it recorded whatever happens on screen, in whatever deinterlace mode which I chose.
- GOW2 (ntsc) title shows "**interlaced (field)**", and doesn't require deinterlace (no artifacts), the recording ends as 60fps and plays at the correct speed, _but_, there are no duplicate frames. I.e. GOW2 does actual real 60fps.

Assuming the above are the different categories we have, these are some data points:
- interlaced (field) seems to me like not really interlaced images. In pcsx2 it end up as either actual 30fps or actual 60fps, and doesn't need deinterlacing. Recording it always ends up with 60fps clip which plays at the right speed, but if the original content was actually 30 images/sec, then the recording ends up with dup every other frame.
- Interlaced (frame) seems to be "the real deal" as far as interlace goes. it also ends up as 60fps clip just how it shows on screen - with whatever deinterlacer which was used. The only weird thing here for me is that weave ends up with different 60 interlaced _frames_ per second, or 120fields/s which can't be right.
- Progressive (field) I only saw as 30 actual fps (though maybe it could also be 60 real images/s, don't know), and on my test cases the recording ended up with the same frames as with Interlaced(field), but the clip properties had the fps at 30, and so it plays at half speed. Speeding it up x2 seems to fix everything (for the time being not calling dup frames "an issue").
- Progressive (frame) - never saw this one in my test clips. I don't know if it exists.

These are things which might be fixable:
- In progressive (frame) the reported clip fps seems to be half of what it should. the frames themselves seem fine (i.e. no missing frames).
- in both progressive (field) and interlaced (field), it can end up with dup every other frame if the original content is updated at 30fps. We could maybe try to detect it and don't record dup frames, but since interlaced(field) can also have real 60fps, possibly even at the same game (though i didn't notice such scenario), then the safe approach is probably keeping it as is - if the content is 30fps then the recording will end up with dup every other frame, and can be fixed later.
- In Interlaced (frame) - fine (up to the quality of the deinterlacer) when deinterlacing, but we should _probably_ be able to make a recording of a proper interlaced (and not deinterlaced) clip, i.e. "normal" weave of 30 weaved frames/s = 60 fields/s. I think it's likely that such clip could be generated from the current recording (assuming the recording resolution is identical to the internal resolution), so no biggie here either.

**Comment by avih** [comment] 2015-09-17 22:21
Ah, I realized what it does with weave. On every 60fps image it updates another field, so it ends up with 60 different weaved images which are composed of 60 fields, and each field appears on two consecutive images. So dropping either the odd or even frames would end up as proper normal interlaced clip which could be deinterlaced later. Mystery solved.

**Comment by avih** [comment] 2015-09-17 23:42
Edited the above with GT4 info which can output progressive with real 60fps.

This means we should not fix this by only recording half the frames, but rather by setting the clip's rate to twice as we do now. Other than this, all the frames are there, and even now it behaves perfectly when played at 2x speed.

**Closed** 2015-09-19 11:46 UTC
Labels: Bug, Plugin: GSdx
