### ISSUE TITLE
[BUG]: DJbox - Game crashes on startup

### ISSUE THREAD

**Issue by Sukotto-1999** [PCSX2/pcsx2#10790] opened 2024-02-08 00:17 UTC
### Describe the Bug

The game crashes when starting up.

### Reproduction Steps

Start DJBox on PCSX2.

### Expected Behavior

The game should boot into the screen where it says "PlayStation BB Unit required".

### PCSX2 Revision

v1.7.5550

### Operating System

Windows 11

### CPU

Intel Core i5-9400F

### GPU

NVIDIA GTX 1650

### GS Settings

Vulkan HW or SW.

**Comment by refractionpcsx2** [comment] 2024-02-08 00:18
Duplicate of #5169

**Closed by refractionpcsx2** 2024-02-08 00:18 UTC
Labels: Bug

**Comment by Sukotto-1999** [comment] 2024-02-08 00:24
Whoops? Sorry.

**Comment by refractionpcsx2** [comment] 2024-02-08 00:27
no problem, good to give a quick search first, but sometimes they get missed from different spellings/word spacing.
