### ISSUE TITLE
Trailer fails to play in Spyro: A Heros Tail 40% of the time

### ISSUE THREAD

**Issue by Masamune3210** [PCSX2/pcsx2#858] opened 2015-09-29 20:57 UTC
Version - PCSX2 1.3.1-20150928094130
Specs - i5 2500k @ 4.0 GHz, 11GB DDR3, GTX 660
Description - About 40% of the time, if you pick the Trailer for Crash Twinsanity in the extras menu for Spyro A Hero's Tail, the game will dump you out into the main menu again instead of playing the Trailer correctly
Procedure - Start Spyro, go to extra menu, play Crash trailer

**Comment by yorkiesandskittles** [comment] 2015-10-01 18:17
Could this be a problem with the game itself? In SpongeBob SquarePants: Battle for Bikini Bottom, playing a trailer can fail. but this is only because the game is registering the press of the X button twice (even though it was only pressed once); once when you access the trailer and the second time when playing the trailer, which stops the trailer and throws you back to the main menu.

**Comment by deadair3210** [comment] 2015-10-01 21:32
I'm not sure as my PS2 is currently not hooked up. I dont think this is the case though as the sound from the trailer is never played,instead the menu music just resumes

**Comment by ramapcsx2** [comment] 2015-10-01 22:24
Is the game requiring a patch to start? (an automatic gamefix) 
There's really too many possibilities where this bug could come from.
I suspect timing or implementation bugs on the IPU or the DMAC IPU section but it could just as well be an odd SPU2 sync glitch.

**Comment by deadair3210** [comment] 2015-10-02 00:30
Game does not require a patch to start, just tested by turning off the Automatic Gamefixes and hitting Boot Full after picking the game.

**Comment by deadair3210** [comment] 2015-10-02 00:30
If you tell me what to do I can help any way I can.

**Comment by atomic83GitHub** [comment] 2018-01-23 13:25
Did you test the game with the last 1.5dev build?

**Comment by coornio** [comment] 2021-12-17 10:46
Time for a necro! When tested on the latest 1.7, this behavior cannot be reproduced. Video plays reliably each time, despite starting it over 20 times in a row. I feel it's safe to close this again.

**Closed** 2021-12-17 10:50 UTC
