### ISSUE TITLE
[BUG] browse file crash

### ISSUE THREAD

**Issue by hy9902** [PCSX2/pcsx2#3947] opened 2020-11-26 14:30 UTC
**Describe the bug**

ISO Selector -> Browse, select window popup, do noting, wating 10s, pcsx2 is shutdown

**To Reproduce**

ISO Selector -> Browse, select window popup, do noting, wating 10s, pcsx2 is shutdown

**System Info (please complete the following information):**
 - PCSX2 Revision: dev-632
 - OS:  Windows 10 Chinese
 - CPU: i5-2500k
 - GPU: GTX 1060

**Comment by Fabianpaw** [comment] 2020-11-26 21:02
Going from your very vague description, I and a few others tried to reproduce this, but weren't able to.
Only thing that stuck out is that your Windows is in Chinese, so I took the burden and changed my user language to Traditional Chinese (Hong Kong), and even changed the folder name to chinese characters, yet was still unable to reproduce the issue.
To sum it up: You need to provide more info.

**Comment by hy9902** [comment] 2020-11-27 05:17
Select  window has ps2 iso 
<img width="590" alt="no_crash" src="https://user-images.githubusercontent.com/8055358/100413581-b55cc580-30b2-11eb-9991-70d0dbdbfca7.png">
<img width="590" alt="crash" src="https://user-images.githubusercontent.com/8055358/100413632-d9200b80-30b2-11eb-9d3f-333a7901a8c2.png">

**Comment by refractionpcsx2** [comment] 2020-11-27 08:16
What do you mean "select window has ps2 iso"? I just browsed to my iso's tried clicking around, nothing happened that was incorrect, could still select my iso.

**Comment by yxmline** [comment] 2020-11-29 16:45
This problem may be caused by hardware failure of mechanical hard disk, solid state disk or memory??

**Comment by MrCK1** [comment] 2020-11-30 22:41
Closing since we are unable to reproduce.

**Closed by MrCK1** 2020-11-30 22:41 UTC
Labels: Cannot Reproduce, Invalid
