### ISSUE TITLE
[BUG] Kingdom Hearts II - Atlantica Finishing Last Musical Fatal Error

### ISSUE THREAD

**Issue by Kidboy17** [PCSX2/pcsx2#4257] opened 2021-02-27 08:11 UTC
**Describe the bug**
After finishing the last musical and the screen says CLEAR the emulator crashes when transitioning to a new scene when using development build. The crash does not happen on the stable 1.6.0 build.

**To Reproduce**
Beat the last musical in Atlanica using any build after 1.6.0

**System Info (please complete the following information):**
 - PCSX2 Revision: v1.7.0-dev-1017-g7512c01ca
 - OS: Windows 7 Ultimate 64 bit
 - CPU:  i-5 4670k
 - GPU:  RTX 2070

Log Dump
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/6053953/emuLog.txt)

**Comment by refractionpcsx2** [comment] 2021-02-27 16:10
Can you provide a savestate please

**Comment by Kidboy17** [comment] 2021-02-27 20:55
I can not provide a savestate because the files are 18mbs each and github only allows 10mb max. I even compress them with winzip and winrar and it only reduces it by a 1 mb. 

Also this only happens when you beat the musical in the story mode and the scene switches to Sora using his keyblade on the keyhole. Playing the musical anytime afterwards does not reproduce the fatal error.

**Comment by refractionpcsx2** [comment] 2021-02-27 21:07
upload it to filedropper.com and put a link here.

**Comment by Kidboy17** [comment] 2021-02-27 21:16
http://www.filedropper.com/slus-21005da0535fd00

http://www.filedropper.com/slus-21005da0535fd00p2s

Here are the links to the savestate and backup. The savestate is right after the completion of the musical, before it saves CLEAR and transitions to a new scene.

**Comment by refractionpcsx2** [comment] 2021-02-27 21:23
Thanks, what was the earliest build you tried after 1.6?

**Comment by Kidboy17** [comment] 2021-02-27 21:43
I haven't tried any earlier builds unfortunately.

**Comment by refractionpcsx2** [comment] 2021-02-27 21:49
okay your OP said "any build after 1.6", a lot has happened since then. if would be nice if you could narrow it down at least somewhat.

**Comment by Kidboy17** [comment] 2021-02-27 22:01
Ok. The earliest I could use my savestate was build v1.7.0-dev-1002-g25628d09e. When I try to use the savestate on builds before that one, it says the savestate is incomplete or corrupted. I just tried with 10 different builds starting with 990 and going back to 54.

The error is present in the 1002 build.

**Comment by refractionpcsx2** [comment] 2021-02-27 22:03
yes you will likely need to play to that point again on the earlier build from a memcard save, a savestate will generally only work between a certain number of builds.

**Comment by Kidboy17** [comment] 2021-02-27 22:05
I would have to replay the entire game up to that point in order to do that as I went past it with 1.6.0 last night for just that part and then switched back to the 1017 build after the scene and continued to play until I decided to post the error.

**Comment by Squall-Leonhart** [comment] 2021-02-28 01:51
This actually occurs on the PS3 remake as well so i suspect its a race condition in the game rather than an emulator bug.

**Comment by kenshen112** [comment] 2021-02-28 01:52
It's possible it's the condition is being  caused by bad emulation as it doesn't occur on ps2. And doesn't occur on 1.6

**Comment by refractionpcsx2** [comment] 2021-02-28 01:55
Unless it happens randomly and Kidboy17 just got lucky on 1.6

**Comment by Squall-Leonhart** [comment] 2021-02-28 02:20
I don't know if the KH1 chernabog crash on NTSC editions was ever fixed, it could be linked to that.

**Comment by Squall-Leonhart** [comment] 2021-02-28 05:46
Need a memcard save to confirm, but I believe the goemon TLB preload hack will stop this crash.

**Comment by Squall-Leonhart** [comment] 2021-02-28 09:13
Ok, This has to be an abuse of save states and jank accumulation.


[kingdom hearts 2.zip](https://github.com/PCSX2/pcsx2/files/6056482/kingdom.hearts.2.zip)

**Comment by refractionpcsx2** [comment] 2021-02-28 15:11
@Kidboy17 when you say you complete the last musical, do you mean the "A New Day is Dawning" song, or do you mean you have to complete them ALL?

**Comment by Kidboy17** [comment] 2021-02-28 22:58
@refractionpcsx2 I mean the "New Day is Dawning" song. Crash only occurs in Story mode

**Comment by kenshen112** [comment] 2021-02-28 23:05
Oh, then that save might not do it ref

**Comment by refractionpcsx2** [comment] 2021-02-28 23:32
> Oh, then that save might not do it ref

You're right, it didn't

**Comment by Squall-Leonhart** [comment] 2021-03-01 06:00
Crash did not occur in story mode for me, either your games all janked up from heavy use of save states or theres an issue with your disk/image

**Comment by refractionpcsx2** [comment] 2021-03-01 08:59
> > I mean the "New Day is Dawning" song. Crash only occurs in Story mode
> 
> Crash did not occur in story mode for me, either your games all janked up from heavy use of save states or theres an issue with your disk/image that only 1.7 faults on.
> 
> Please test with my provided save file on your end.
> 
> If it does, try remaking the disk image, or install this [Xaudio 2.8 and 2.9 installer for Windows 7.zip](https://github.com/PCSX2/pcsx2/files/6059458/Xaudio.2.8.and.2.9.installer.for.Windows.7.zip) and set spu to Xaudio.

well the crash happened for me on my copy with his savestate. It does the end of level stuff for about 10-20 seconds, then loads a bit, then TLB misses.  I mean it could be a number of things, it could be savestate jank, could be the combination of things he happened to do or the score he happened to get, I dunno, I'm kinda stumped.

**Comment by Squall-Leonhart** [comment] 2021-03-01 09:32
> well the crash happened for me on my copy with his savestate. It does the end of level stuff for about 10-20 seconds, then loads a bit, then TLB misses.

I got that as well, but it seems to just be the state, Interpretter continues past the error  but goes on to only playing the sound of bubbles with a black screen,

i enabled all logs and scoured it in comparison to my own good attempt and it didn't seem to show any differences except for his encountering the TLB miss.

Score would be easy enough to match.

I'm also considering the possibility of it being the SPU being set to port audio instead of xaudio, the ps2 was never known for running games 90 something hours.

This could even already have been fixed by your feb 27 commits.

**Comment by refractionpcsx2** [comment] 2021-03-01 09:33
I doubt portaudio would be the problem, I'm using xaudio right now and it doesn't make a difference and it doesn't affect emulation.

**Comment by Squall-Leonhart** [comment] 2021-03-01 09:37
I think it'll be a bit much to play 30+ something hours of game in a row to try and reproduce this, when memcards are the correct way to save in between sessions, 

Is there any way to compare the memory state of the broken case with mine that clears?

**Comment by refractionpcsx2** [comment] 2021-03-01 09:38
You could do a binary compare after extracting the parts of the savestate i guess, but you'd have to do it at pretty much exactly the same time, otherwise you're going to have to go through all the differences from being at a different part of the game.  So yes you *could* do it, but it probably isn't feasible.

**Comment by Squall-Leonhart** [comment] 2021-03-01 09:49
The only change I would want to see at this point is catching the resulting exception and invoking emulation shutdown instead of the process crashing

@Kidboy17 

You didn't happen to save/reload your way through the song to get that score did you?

**Comment by Kidboy17** [comment] 2021-03-02 02:09
@Squall-Leonhart I did use save/load to get the score. I did it with all the musicals and never had an issue until the very last one. I did the musicals throughout the story, as soon as they were available and not back to back.

**Comment by RocketRobz** [comment] 2022-03-13 06:06
This seems to be fixed. Haven't gotten any crashes on my side.

**Comment by refractionpcsx2** [comment] 2022-03-13 06:09
Nice :) I'll close this then.

**Closed by refractionpcsx2** 2022-03-13 06:09 UTC
Labels: Bug
