### ISSUE TITLE
[BUG]: Toggling Software Render stops video recording, leaves "Video Recording" toggle still active

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#8626] opened 2023-04-09 19:01 UTC
### Describe the Bug

The video stops recording, but no warning is given. The toggle for "Video Recording" is still checked

### Reproduction Steps

1) Start a game
2) Start a video Recording in hardware (vulkan) mode
3) Switch to Software Rendering

Result:
The video stops recording, but no warning is given. The toggle for "Video Recording" is still checked

### PCSX2 Revision

1.7.4342

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment] 2023-04-09 19:01
thats working as intended

**Comment by Meerkov** [comment] 2023-04-09 19:02
> edit: a warning is given that the recording ended

No warning is given. Are you sure?

**Comment by Mrlinkwii** [comment] 2023-04-09 19:03
i just tried it rn , unless you turned off the warnings , it gives one

**Comment by RedDevilus** [comment] 2023-04-09 19:05
That's normal behaviour, you can't cherry chain video recording like that.

**Comment by Mrlinkwii** [comment] 2023-04-09 19:08
https://user-images.githubusercontent.com/17685135/230791781-93fbddb5-407c-42a1-b845-b2ef7209b3f2.mp4

@Meerkov   as you can see i got the  warning that it was stopping recording  when i switched to SW

**Comment by Meerkov** [comment] 2023-04-09 19:20
Regardless of whether it's expected behavior for the video to stop recording, or whether a warning is given, the toggle is still toggled showing that video recording is enabled.

Maybe it's not clear what is being reported here. I'll record a video to better show the issue.

Maybe I did turn off warnings (though I can't find where that setting is) however the toggle should be untoggled to mark that it is no longer recording still.

https://www.youtube.com/watch?v=wzO_Cfq4zpI

**Comment by stenzek** [comment] 2023-04-10 03:29
Marking as a won't fix unfortunately, the way things are set up, the core has no way of notifying the frontend that video recording has stopped, and I don't want to add a host entry point just for this.

**Closed by stenzek** 2023-04-10 03:29 UTC
Labels: Bug
