### ISSUE TITLE
Harry Potter and Chamber of Secrets - Game crashes with allocation error.

### ISSUE THREAD

**Issue by dagonar** [PCSX2/pcsx2#362] opened 2014-11-29 11:53 UTC
-PCSX2 version: 1.2.1.0, Feb  3 2014

-PCSX2 options: Defaults

-Plugins used: GSdx0, Lilypad 0.11.0, SPU2-X r5830, nulls on the others.

-Plugins settings: Defaults

-Description: Game crashes after booting it up. Screen just freezes on the Memory Card reading option.

-How to replicate: Boot the game and let it get to the memory card option.

-PC specifications: CPU: AMD Phenom II x6 1050 @ 3.2gHz, GPU: AMD Radeon HD 6970, OS: Ubuntu 14.04 amd64

-Other comments: Windows 8 used for running the emulator.

-Log:
   HLE Notice: ELF does not have a path.

Initializing plugins...<br/>
    - Init GS

Windows 6.2.9200
    Init PAD<br/>
    Init SPU2<br/>
    Init CDVD<br/>
    Init USB<br/>
    Init FW<br/>
    Init DEV9<br/>

Plugins initialized successfully.

Opening plugins...<br/>
    Opening GS<br/>
    Opening PAD<br/>
    Opening SPU2<br/>
    Opening CDVD<br/>
isoFile open ok: D:\Juegos\PCSX2 1.2.1\Iso\Harry Potter and The Chamber of 
Secrets.bin<br/>
    Image type  = CD<br/>
- CDVD Disk Open: CD, 1 tracks (1 to 1):
- \* Track 1: Data (Mode 1) (274585 sectors)
  Opening USB
  Opening FW
  Opening DEV9
  McdSlot 0: D:\Juegos\PCSX2 1.2.1\memcards\Mcd001.ps2
  McdSlot 1: D:\Juegos\PCSX2 1.2.1\memcards\Mcd002.ps2
  Plugins opened successfully.
  EE/iR5900-32 Recompiler Reset
  Bios Found: USA     v02.20(10/02/2006)  Console
  BIOS rom1 module not found, skipping...
  BIOS rom2 module not found, skipping...
  BIOS erom module not found, skipping...
  - (UpdateVSyncRate) Mode Changed to NTSC.
  - (UpdateVSyncRate) FPS Limit Changed : 59.94 fps
  - (SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_205.76;1
  - (SYSTEM.CNF) Software version = 1.00
  - (SYSTEM.CNF) Disc region type = NTSC
  - ELF (cdrom0:\SLUS_205.76;1) Game CRC = 0xC5473413, EntryPoint = 0x00100008
  - (SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_205.76;1
  - (SYSTEM.CNF) Software version = 1.00
  - (SYSTEM.CNF) Disc region type = NTSC
  - (SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_205.76;1
  - (SYSTEM.CNF) Software version = 1.00
  - (SYSTEM.CNF) Disc region type = NTSC
  - (EE pc:001F6E18) TLB Miss, addr=0x0 [load]
  - Vif1: Unknown VifCmd! [40]
  - Vif1: Unknown VifCmd! [3c]
  - (EE pc:001F6E54) TLB Miss, addr=0x4 [load]
  - Vif1: Unknown VifCmd! [40]

**Comment by gregory38** [comment] 2015-11-12 12:08
Could you test with a different value of the EE speed slider (both way)

**Comment by Zerowalker** [comment] 2016-02-03 10:06
Been testing this myself though PAL version.
I can force myself to the Menu with Speedhacks, but i can't start a new game.
I tried the current git, or very close to it (too long name), got it from EmuCr.

Been checking on this game every now and then for years, seems as a problematic one;(

**Comment by mrchrismania** [comment] 2016-07-03 10:15
the only issue i have with this is the audio crackling on dolphin emulator.

**Comment by Zerowalker** [comment] 2016-07-03 10:40
This is PCSX2 though xD

**Comment by ramapcsx2** [comment] 2017-08-29 13:17
@refractionpcsx2 Hey, could you check if we implement this?
https://github.com/jpd002/Play-/commit/993599970a66c4de5ac46f61d7e670dc6e5bf2c6

**Comment by refractionpcsx2** [comment] 2017-08-29 13:24
Yes, all channels that can stall have their stall/drain code implemented. Places where we weren't sure it debug outputs something, but I never get anything on this game.

**Comment by ramapcsx2** [comment] 2017-08-29 15:17
Okay, I vaguely remember this code. Ancient history but I didn't get it back then, don't get it today.
It's just the nature of the GIF ;p

**Comment by refractionpcsx2** [comment] 2017-08-29 15:30
I guess I can look in to that and see if I can record it doing stalls, but I could have sworn it didn't lol

**Comment by refractionpcsx2** [comment] 2017-08-29 17:47
see this is what makes me think it isn't that

```
32bit Stall Source Changed to 3
32bit Stall Destination Changed to 8
GSdx Lookup CRC:C7D5A403
32bit Stall Destination Changed to 0

```

**Comment by refractionpcsx2** [comment] 2017-08-29 18:31
So I did a bunch of messing, and the only result i got was the little pentagon thingy when it's loading stopped showing when i broke it, making it more granular didn't help at all, so no I don't think that's our issue.

**Comment by ssakash** [comment] 2017-08-30 01:25
> I believe that's the CSR?

Yeah

**Comment by MrCK1** [comment] 2017-09-13 15:51
@refractionpcsx2 @ssakash We can close this now as the game is now playable thanks to a new patch from Kian Stevens. Prafull has also confirmed that the game is in working order. Great work guys!

http://forums.pcsx2.net/Thread-Fixing-unplayable-games?page=25

**Comment by refractionpcsx2** [comment] 2017-09-13 15:57
Nice! It would be interesting to see what that patch stops from running, to see if we can narrow down what is actually causing it so we don't need a patch.  Plus I suspect similar issues are affecting the other harry potter games too.

I shall mark this as closed though :) Great job Kian Stevens

**Closed by refractionpcsx2** 2017-09-13 15:57 UTC

**Comment by MrCK1** [comment] 2017-09-13 16:07
@refractionpcsx2 This is what Kian _thinks_ he did to fix the crashes. The rest of the reference is in the thread itself.


> To get it working, I basically looked at which function(s) cause the crashes and nop them. I think prafull mentioned this earlier on. It's really just remembering patterns of which functions appear the most when the game crashes.
> One of my replies above showed a screenshot of literally hundreds of the same function (they have an address of 0x8XXXXXXX in the debugger) and they all seem to cause issues when doing things like loading the game etc. So, I assumed that 0x80000000 was the start of those functions and nopped it. You can see that in the pnach.
> 
> And you're right, the only VIF commands are 40 and 3c, kind of validating my theory that the 8 command crashed the game. I think the reduced amount of VIF commands makes the game play better now.

**Comment by refractionpcsx2** [comment] 2017-09-13 16:09
Yeah the VIF thing doesn't make any actual sense. Curious of what is in that address space though, I thought the BIOS was up there...

**Comment by gregory38** [comment] 2017-09-13 17:22
Ox8..... is the kernel physical addresse space. Which means only kernel privilege mode can access it (syscall, interrupt maybe?). The first 32MB are "mapped" to the EE memory. And initial 100kB part is indeed the EE kernel.

What are the exact address. Maybe code is wrongly executed in user space instead of kernel space.

**Comment by Kian-Stevens** [comment] 2017-09-13 20:57
Yeah... I don't understand how it works myself. I just saw those functions appear frequently when the game crashed (because they appeared when the game was loading/saving)

Strangely enough, nopping any other 0x8 function would cause the game to crash sooner/stop in game music from playing etc. At least it works.

**Comment by MrCK1** [comment] 2017-09-13 21:00
@gregory38 The original post was removed for being off topic, but I've duplicated all the references for you here 👍 

> 
> I'm seeing this function in the debugger literally every time the game crashes (along with 'Vif1: Unknown VifCmd! [8]' in the console). It might not mean anything but it's worth a mention:
![image](https://user-images.githubusercontent.com/16314399/30400310-7257cb44-98a4-11e7-8c72-65bbc728f072.png)

> Here's that same function's position in the debugger:
>   
![image](https://user-images.githubusercontent.com/16314399/30400329-846d962e-98a4-11e7-990e-e5a099637ff9.png)
> 
> Doing anything to this function seems to crash the game or the emulator, keep in mind. Its value is 0xFFFFFFFF. If I understand correctly, that value is either positive or negative depending on how the processor handles it. I might be wrong, but it could have a part to play.
> 
> I also see this function quite often too:
>    
![image](https://user-images.githubusercontent.com/16314399/30400380-b807f3f8-98a4-11e7-80d3-b2654a5e6a9b.png)
> 
> That function also has a value of 0xFFFFFFFF. I see it pop up when the game is running, mostly when you load a save, or if you go through a door and the game has to load. But then I sometimes see it when the game crashes. Here's the function's position in the debugger:
> 
![image](https://user-images.githubusercontent.com/16314399/30400468-f41c3c6e-98a4-11e7-8ba1-faa36aad9dda.png)
> 
> There's tons of that same function, and any one of them can pop up with a value of 0xFFFFFFFF. 
> I find it strange how these two functions are the only ones I see with such an odd value, and yet they both appear when the game crashes.
> 
> I'm mostly concerned about the first function though. The only time I ever see that is when the game crashes, and it always has that value. The other function(s) are a bit more flexible; sometimes they appear on a crash, sometimes they don't, but they always seem to have the same value.
> Maybe it could mean something. But like I said, it's worth a mention.

**Comment by gregory38** [comment] 2017-09-14 08:24
Some useful information based on @MrCK1 / @Kian-Stevens  post.

You could find the memory mapping [in the blog](https://pcsx2.net/developer-blog/265-mmu-mini-series-part2-4.html). It misses the upper 4kB page and maybe others tricks.

Syscall +5/-5 allow to return from an interrupt handler to normal execution. Minus means that it can reuse a kernel stack (whereas plus means to create a new stack).

`0xFFFF_FFFF` value could be an error of the debugger. Entry is the initial PC of the EE thread. If I remember correctly the upper part of the memory contains a CPU context. No code. The debugger read a known memory location that contain the current thread id. And then lookup the kernel TCB (`thread control block`) structure data. It would be interesting to check manually the value.

I need to check `0x80003AE0` address. My feeling is that section contains no code (only garbage data)

**Comment by gregory38** [comment] 2017-09-14 08:36
Oh I mixed-up `stack frames` and `threads`. I think `0xFFFF_FFFF` is correct, it is because you're in kernel execution context. You're not inside a thread so you can't rewind the stack to the top.

**Comment by gregory38** [comment] 2017-09-15 07:17
So I confirm that `0x8000_0000` is the TLB (segmentation fault of the game) refill exception.

On my bios, I have some code in `0x8000_3AE0`. It is the sleep_thread function. I suspect that debugger doesn't manage to print correct code for the kernel.

Based on the pnach. I guess the game tried to access wrong address. Either the game requires correct TLB emulation (such as goemon). Or there is a bug in the emulation (more likely). I'm really suprised that a single nop is enough.

Here the TLB refill exception code (constants are propagated by a script)
```
# backup t9 register in memory
80000000:	01801a3c 	lui	k0,0x8001
80000004:	785359ff 	sd	t9,(0x80015378)

# load exception cause in t9
80000008:	00681940 	mfc0	t9,$Cause

# Get the exception handler from the exception array (handler = exception[CPU.cause_id])
8000000c:	01801a3c 	lui	k0,0x8001
80000010:	7c003933 	andi	t9,t9,0x7c
80000014:	21d05903 	addu	k0,0x80010000,t9
80000018:	40535a8f 	lw	k0,0x5340(k0)

8000001c:	0180193c 	lui	t9,0x8001
# Jump to the handler and execute it
80000020:	08004003 	jr	k0
# restore t9 register
80000024:	785339df 	ld	t9,(0x80015378)
```

It would be interesting to know who trigger the bad memory access. You can have the bad PC in COP0.EPC register (dunno if debugger support them).

@prafullpcsx2 @Kian-Stevens can you confirm me that you do a single NOP ?

**Comment by Kian-Stevens** [comment] 2017-09-15 12:38
Yes, I did a single NOP, at 0x80000000. You can have a look at the pnach for yourself (thread link below). The rest of the pnach is the work of [@prafullpcsx2.](

http://forums.pcsx2.net/Thread-Harry-Potter-and-The-Chamber-of-Secrets-SLES-51192-E?pid=569903#pid569903

**Comment by gregory38** [comment] 2017-09-15 12:49
I'm really surprised that it helps and that it didn't break further the code.

**Comment by Kian-Stevens** [comment] 2017-09-15 14:06
If I'm honest, me too. I was surprised when it started working. But like I said, nopping any other 0x8 function broke the game.

**Comment by MrCK1** [comment] 2017-09-15 16:04
Maybe it would be helpful to run a debug log with Memory, Unknown Registers, COP, ect.

**Comment by gregory38** [comment] 2017-09-16 15:57
@Kian-Stevens did you test the behavior on the EE interpreter with/without the patch ?

**Comment by Kian-Stevens** [comment] 2017-09-17 16:24
@gregory38 No I didn't, sorry.

**Comment by refractionpcsx2** [comment] 2017-09-17 22:58
I've tested the game with the interpreter, it doesn't make any difference, it still throws a load of VIF errors and dies.

**Comment by Tettetsunade** [comment] 2019-04-15 14:10
Hi, I state that this is the first time I have this problem and I don't know where to put my hands, it gives me the same problem (I think) of the guy who wrote the post and I don't know how to solve .. someone with good patience can help me? thank you very much infinitely
