### ISSUE TITLE
Growlanser 3 Save Freeze

### ISSUE THREAD

**Issue by Ronnie21093** [PCSX2/pcsx2#3074] opened 2019-08-16 02:14 UTC
***PCSX2 version:***
''v1.5.0-dev-3252-g9830b2dd9''

- **Notes**:
  - It's preferred to only report bugs which are present on the [latest development builds](https://pcsx2.net/download/development.html).
  - The PSX backward compatibility mode is still in its early stage of development. Issue reports are too early at this point.

***PCSX2 options:***
``All Default`'

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``All Default``

- **Note**: In case the issue is a graphical problem with the GSDX plugin, please provide basic information like ``Renderer/Internal resolution/CRC Hack level/Other relevant options`` which were used to reproduce the issue. Additionally, providing a [GS dump](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of the issue would also be helpful.

***Description of the issue:***
``The game freezes when attempted to save.``

***How to reproduce the issue:***
``Constantly save until the game freezes.``

***Last known version to work:***
``Unknown``

***PC specifications:***
``Windows 7, Intel Xeon E5-1520, 16 GB RAM, GTX 1070``
![GL3Save](https://user-images.githubusercontent.com/33608007/63138751-76bffc00-bf90-11e9-88e1-6b63bd82a45a.png)

**Comment by MrCK1** [comment] 2019-08-16 03:23
Do you have MTVU enabled or not? IIRC it has to be disabled.

**Comment by Ronnie21093** [comment] 2019-08-16 07:10
> Do you have MTVU enabled or not? IIRC it has to be disabled.

It is already disabled.

**Comment by Ronnie21093** [comment] 2019-08-17 03:00
If anyone is able to fix this issue, please reply to the thread so I know the latest version of PCSX2 can run the game without freezing when I try to save.

**Comment by turtleli** [comment] 2019-08-18 19:27
Closing as duplicate of #107.

**Closed by turtleli** 2019-08-18 19:27 UTC
Labels: Duplicate
