### ISSUE TITLE
Fps Go Down ( Bandai Game ) + spyro enter the dragonfly Have Agian Black Image

### ISSUE THREAD

**Issue by zerr10** [PCSX2/pcsx2#1283] opened 2016-04-08 01:28 UTC
My observations following Something bad is happening with the file "EXE" and the code in the Latest Versions Such As "1.4.0" and in the last Kopilacji "Pcsx2-v1.5.0-dev-552-g0ab7b63-windows-x86" However, in the version of "PCSX2 -r5875 (1.2.1) + newest Plugin GSdx32SSE2.dll "FPS are higher in the Games with Bandai" Constant 50 FPS "but the latest scenes emulator FPS is even smaller for - 5 FPS
version "" Pcsx2-r5875 (1.2.1) + newest Plugin "You can even run Spyro Enter The Dragonfly but at the last version" Pcsx2-v1.5.0-dev-552-g0ab7b63-windows-x86 "Again in this game is Black Image Sad
whether it be corrected? version in the future? 5 FPS is a lot less Sad

Now I use a version of PCSX2-r5875 (1.2.1) + newest Plugin if you can please, Amend it because I do not know if other games will go with as the old version of the PCSX2-r5875 (1.2.1) in addition lacks a few options.

and it is not fault free computer just something changed in the code exe. I hope that developery will notice and improve :)

if you need it can not even take a screenshot of the FPS that is the difference in versions

AMD A8 APU 3870 4x3,0Ghz R7 250X 2GB of RAM 8GB of 1866MHz Dual windows 10 pro 64x

**Comment by zerr10** [comment] 2016-04-08 01:34
and another question is whether the game works depends on whether the plug GS version emulator?
because if I have more FPS in the older version I prefer to use it but the other games that instance did not work will work as it will add the latest plug GS?

**Comment by willkuer** [comment] 2016-04-08 07:11
Please visit the forum to get support. This is just a bug tracker.

Emulation speed can drop with increasing version number. The emulator gets more accurate and thus is more demanding. You can always use older versions if they yielded sufficient results.

Spyro regression is a bit suprising. If I remember correctly it works because of a hack/pnach from the gamedbf. Maybe you disabled automatic game fixes. However it would be good to ask first for support in the forum to validate your results.

**Comment by gregory38** [comment] 2016-04-08 08:06
For all AMD users, if you're driver is still broken  you can read/complain on this thread https://community.amd.com/thread/194895

**Comment by Dokman** [comment] 2016-04-08 09:10
"The issue has been resolved and the fix will be part of a future driver release. In the meantime, if you use dual-source blending, don't use separate shader objects."

But... what we can do?

**Comment by gregory38** [comment] 2016-04-08 10:26
Use an older GSdx version. There will be soon a legacy GSdx plugin. You could also complain on AMD to release the fix sooner.

**Comment by gregory38** [comment] 2016-04-26 16:42
For performance issue. Please use the forum.

**Closed by gregory38** 2016-04-26 16:42 UTC
