### ISSUE TITLE
Graphics bug with Gust games with DX11 Hardware renderer

### ISSUE THREAD

**Issue by RyleFury** [PCSX2/pcsx2#932] opened 2015-10-27 14:37 UTC
-PCSX2 version: v1.3.1-1017-g60a90aa and after

-PCSX2 options: I tried all possible settings in DX11 Hardware

-Plugins used: All GSdx plugins available (SSE2, SSSE3, SSE4, AVX, AVX2)

-Plugin settings: The bug is only here in the DX11 Hardware renderer with any setting.

-Description: In games developped by Gust, a black grid appears in the background at some locations. The bug appears distinctly in Mana-Khemia. 

-How to replicate: Put the GSdx plugin renderer to Direct3D11 (Hardware). Boot the game. After the memory card loading, you will see that bug a little moment. In the game, if you open the menu, you can clearly see that bug like in the screenshot below.

-Last version to work: v1.3.1-1016-gd2e4dac

-PC specifications:
CPU: Intel Core i5-4460 @ 3.2Ghz
GPU: NVIDIA GeForce GTX 570
OS: Windows 7 SP1

![mk1_pcsx2_dx11hard_grid_bug](https://cloud.githubusercontent.com/assets/15344342/10761101/357b8686-7cc0-11e5-943f-4b218ee41819.png)

**Comment by gregory38** [comment] 2015-10-27 15:30
@ref you will love this one ;)

**Comment by refractionpcsx2** [comment] 2015-10-27 15:57
Whoopie... :P

**Comment by i30817** [comment] 2015-10-27 17:22
Funny enough, a mana khemia 2 blacklines bug was fixed recently on the opengl renderer (great work gregory).

**Comment by gregory38** [comment] 2015-10-27 17:44
As a side note, openGL is a real alternative to Dx on Nvidia GPU.

**Comment by refractionpcsx2** [comment] 2015-10-27 22:32
Do we know what commit fixed this in opengl? might at least give me a hint to the problem. Considering I suck at debugging directx and know little about directx itself :p

**Comment by gregory38** [comment] 2015-10-27 22:51
AFAIK, this bug is about the nvidia driver scaling stuff. Mana Khemia 2 is another story, and it is likely linked to accurate blending/tex shuffle.

**Comment by refractionpcsx2** [comment] 2015-10-27 23:00
scaling bugs? :/ so you mean my hack broke it?

MK2 isn't getting fixed any time soon, I don't know how to implement that on DX, you'd probably have a better time of it than me :p You're free to install WINE lol

**Comment by gregory38** [comment] 2015-10-27 23:02
Yes or I look at the wrong commit.
```
-Last version to work: v1.3.1-1016-gd2e4dac
```

**Comment by refractionpcsx2** [comment] 2015-10-27 23:16
That shouldn't have caused that much problem, ugh, alright ill look in to that see if i can get the value low enough so it doesn't break MK but stops the annoying shaking

**Comment by gregory38** [comment] 2015-11-08 13:46
Status?

**Comment by refractionpcsx2** [comment] 2015-11-08 14:04
I haven't looked yet lol, I really have no idea what I'm doing.

**Comment by gregory38** [comment] 2015-11-08 14:32
I'm bot the one that asked to check regression :p Good luck.

**Comment by refractionpcsx2** [comment] 2015-11-08 16:05
Hmm, this is one of those cases where you can't have one without the other.  The only way I've managed to fix this is if you have the sprite hack enabled (on "Half"), you can't have the nvidia fix.  as far as I know any game which uses the sprite hack doesn't need the nvidia fix, so you will just need to make sure this is enabled manually.  I hoped to do detection in the viewport set function, turns out reading the app config is excruciatingly slow.

Is this an acceptable tradeoff?

**Comment by gregory38** [comment] 2015-11-08 16:30
You need to cache the config variable

**Comment by refractionpcsx2** [comment] 2015-11-08 16:47
thats kinda what i've done now. the variable is copied on d3d11 create, then that variable is checked in the set viewport function.

**Comment by refractionpcsx2** [comment] 2015-11-10 22:58
Should be workable now, as long as you enable the sprite hack, which the game needs anyway, it should be fine.

**Closed by refractionpcsx2** 2015-11-10 22:58 UTC
Labels: GSdx: Hardware, Regression

**Comment by RyleFury** [comment] 2015-11-10 23:48
Thank you :)
