### ISSUE TITLE
Separate GSdx.ini files for different renderers

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#881] opened 2015-10-07 20:15 UTC
I'd like for Direct3D11 and OpenGL specifically to have separate .ini files because as most of us know AMD's drivers suck at OpenGL so while I can play games at 6xIR on the D3D11 renderer, I CANNOT do that on the OpenGL renderer.

This would make switching between renderers easier since you wouldn't need to change your settings (CRC Hacks and IR, mostly) every time you watch to switch renderers.

**Comment by avih** [comment] 2015-10-07 20:21
So basically you want to OGL to have its own configuration of CRC hacks and IR (internal resolution)?

**Comment by willkuer** [comment] 2015-10-07 20:29
I can think of two possible natural solutions:

1. Fork OGL from GSDx as GSOgl -> different ini-Files are naturally included. Drawback: Forking is probably bad for parallel improvements on Dx and OGL

2. Use the command line or one of the frontends to select the ini-File you want to use.

I would suggest the second solution. We already have a solution to your problem and it works nicely.

**Comment by karasuhebi** [comment] 2015-10-07 21:38
@avih yeah, basically. I don't really change any other settings myself, but there might be other settings that other users might change depending on what renderer they're using so it might still be a good idea to have two separate .ini files. I mean even if those are the only two settings people change when switching renderers (there might be others like the HW Hacks, for example) it would still be a good idea to have two files IMO, because if you get users used to their IR setting or CRC Hack setting changing on a renderer switch, they might think all settings are saved on a per-renderer basis and it might lead to confusion if this is not the case.

I do like your solution though, it takes care of my specific issue very quickly and simply. :)


@willkuer:

1. Forking seems a bit extreme for such a small issue. Not sure how the developers would feel about that.

2. I don't want to have to use CLI commands or a third-party program to solve this issue. That seems unnecessary. Having .ini files for each renderer is not unheard of. That's how Dolphin does it.

**Comment by willkuer** [comment] 2015-10-07 21:47
I was actually making this request as it bugged me some time and would be part of your solution.

The two parallel ini-Entries was something avih added after I posted. At least this is now the first time I saw it.

The problem I would see is that somebody might request the same for different gpu adapters. If he is mobile he wants to use the internal gpu and lower IR and for sure no OGL but while he is connected he wants to have OGL and use his dedicated nvidia gpu.

So I think to solve that issue internally you would need to implement some kind of profile system where you can declare different sets of settings and can switch between them by some gui elements. (I would like to mention again that pcsx2 frontents allow that - but sure who really likes 3rd party software?)

**Comment by karasuhebi** [comment] 2015-10-07 21:51
>The problem I would see is that somebody might request the same for different gpu adapters. If he is mobile he wants to use the internal gpu and lower IR and for sure no OGL but while he is connected he wants to have OGL and use his dedicated nvidia gpu.

That's exactly why I want two .ini files so that people can change any setting they want on a per-renderer setting, not just the settings we're talking about here.

>So I think to solve that issue internally you would need to implement some kind of profile system where you can declare different sets of settings and can switch between them by some gui elements.

That sounds a bit more complicated than it needs to be. Per-renderer .ini files should be fine IMO.

**Comment by willkuer** [comment] 2015-10-07 22:11
What happens if the guy with the internal gpu once want to use dx9 native and once dx9 3xnative? Per renderer switch is a specific solution to a possibly general problem. What happens if somebody really implements opencl? I think one should consider a general solution here.

**Comment by karasuhebi** [comment] 2015-10-07 22:57
Fair enough.

**Comment by jcdenton2k** [comment] 2015-10-11 03:58
Use a frontend.  Problem solved.  Please don't take up limited dev resources on such minor stuff like this because you don't want to use a frontend.  They're there for a reason.

**Comment by karasuhebi** [comment] 2015-10-11 23:08
Even if I wanted to, I can't use a 3rd party frontend. I gzip my images.

**Comment by avih** [comment] 2015-10-12 12:21
> Even if I wanted to, I can't use a 3rd party frontend. I gzip my images.

I don't see why it should be an issue, but if it is, it's an issue with the front end which doesn't "support" it.

**Comment by vsub** [comment] 2015-10-12 12:32
I don't know how pcsx2 read the ini files but if it's this way...read the ini which is in category1 and has key name something1(that's how autohotkey works),then how about using the existing keys(settings)and just duplicate them in the ini but place them in different categories.

If you use DirectX,pcsx2 will read the settings from the DX category and if it's OpenGL,pcsx2 will read from the OpenGL category

[DirectX]
nativeres=3
[OpenGL]
nativeres=1

**Comment by avih** [comment] 2015-10-12 12:53
> I don't know how pcsx2 read the ini files but if it's this way...read the ini which is in category1 and has key name something1(that's how autohotkey works),then how about using the existing keys(settings)and just duplicate them in the ini but place them in different categories.

You're suggesting implementation details of a specific solution, but it's not even agreed that the problem needs solving, and even if it was agreed, it wasn't agreed which solution would be best. Implementation details are relevant only after it's agreed that this problem needs solving and a solution was chosen, possibly from several solutions, and we're not there yet.

The "problem" is that he wants different set of configurations chosen according to whether the renderer is D3D or OGL.

The problem with this problem is that it solves only the OP's concerns, but one could easily imagine other cases where settings are desirable according to HW/SW renderer, or many other "triggers".

PCSX2 in general (and specifically GSdx too) takes an approach where all the settings are configurable, but there are no per-game settings (except internally to fix game issues), as well as no "dependent" settings (except the presets system, but that's not the same as this issue). PCSX2 is not likely to become a settings manager, and so is GSdx. It's just too much effort which could easily be implemented externally, like with 3rd party launchers.

To manage different settings, or different settings per game, etc, one should use external tools. Or stick to a single set of settings and that's it.

**Comment by karasuhebi** [comment] 2015-10-12 16:03
>I don't see why it should be an issue, but if it is, it's an issue with the front end which doesn't "support" it.

That is correct, it's a problem with support from the frontends. I did not mean to imply the issue was gzip compression itself or PCSX2's implementation of it, I'm truly sorry if that's the way it came across. I love PCSX2's gzip support. :)

>The problem with this problem is that it addresses only the OP's concerns, but one could easily imagine other cases where settings are desirable according to HW/SW renderer, or many other "triggers".

What other settings did you think of that could be desirable if one is switching between a HW or SW renderer? Other than shader stuff, the hardware and software renderers essentially already have separate settings within GSdx.

From what I can see, the only thing that would really be useful is different settings for the OpenGL and Direct3D **hardware** renderers. Although @willkuer's comment (what if someone gets OpenCL working really well) made me think that we should just make every renderer have its own .ini file, not just the OpenGL and Direct3D hardware renderers. That way any renderer that might come along in the future has its own .ini file. This also takes care of your concern, @avih, of separate settings being desirable based on if it's a HW renderer or a SW renderer, even though like I said, I don't think that's needed since SW renderers basically have their own settings anyway.

>More generally, and ultimately, what he wants is different settings per game. The different settings for D3D/OGL is just a compromise he's willing to take.

That's incorrect. What I want is different GSdx settings per renderer. My apologies if that's how it came across but I have little to no desire for per game settings to be implemented into the GUI. There's already a CLI switch that takes care of that particular need (--cfgpath) quite beautifully so I don't think its really necessary to have it exposed in the GUI. Although less technical users might find it handy.

Per renderer .ini files, ladies and gentlemen. That's all I want. GSdx_OGL.ini and GSdx_D3D.ini.

**Comment by avih** [comment] 2015-10-12 16:09
> My apologies if that's how it came across

It didn't, but I had to make an educated guess since you didn't really describe what the actual problem is.

> Per renderer .ini files, ladies and gentlemen. That's all I want. GSdx_OGL.ini and GSdx_D3D.ini.

No. On its own no one would care how many ini files are used and for what. This "solution" solves a problem which you have. And it might not be the best solution.

Describe exactly what the problem is. I.e. in which cases exactly you would you like the IR and CRC hacks to change when you change renderer, and why would you change renderer?

**Comment by gregory38** [comment] 2015-11-08 13:51
Me too I think it is a bad idea. Otherwise we need to support by game setting.
Shall we close the issue?

**Comment by avih** [comment] 2015-11-08 14:10
IMO yes.

**Closed** 2015-11-08 14:30 UTC

**Comment by karasuhebi** [comment] 2015-11-18 01:02
>Describe exactly what the problem is. I.e. in which cases exactly you would you like the IR and CRC hacks to change when you change renderer, and why would you change renderer?

I thought I had done that in the OP. My apologies. The problem is that when I'm switching between the D3D11 hardware renderer and the OGL renderer (mostly for testing purposes), I have to go in and change my IR setting since performance tanks when I switch to the OGL renderer (yay AMD OGL support). This makes testing that requires switching renderers slightly annoying and I'd rather have it where each renderer has its own IR value.

>Otherwise we need to support by game setting.

Why would we need to support per game settings if we do per renderer settings? That seems like a slippery slope fallacy.
