### ISSUE TITLE
[BUG]: Accent and Symbol Keys not recognized by USB Keyboard Emulation

### ISSUE THREAD

**Issue by Dimenarius** [PCSX2/pcsx2#10308] opened 2023-11-23 14:01 UTC
### Describe the Bug

The QT-Version does not have support for accent keys like "ä" or "ü" or symbol keys like "!" or "?".

Only letters and numbers are possible. Some symbol keys work but are placed differently like "+", "*" or "-"

The Numpad works as usual regarding these keys.

It may be that "," also doesn't work however that's unsure.

### Reproduction Steps

-Enable HID-Keyboard on USB Port 1 (Controller Settings)
-Launch a game with USB Keyboard Support (technically the Network Configuration Assistant from Online Games also works)
-Try typing a sentence with accents (for example in NTGUI when choosing the Setting Name)

### Expected Behavior

Possibility of being able to use accent and symbol keys during emulation.

In the WxWidgets-Version this was still possible without issue.

### PCSX2 Revision

v1.7.5224

### Operating System

Windows 11

**Comment by stenzek** [comment] 2023-11-23 15:48
Duplicate of #7605. FWIW I have no interest in actioning this, but PRs welcome, so long as it uses Qt's key events and not the disgusting hackery of the old USB impl.

**Closed by stenzek** 2023-11-23 15:48 UTC
Labels: Bug, USB
