### ISSUE TITLE
[App][l10n] Quick wizard language setting bug

### ISSUE THREAD

**Issue by piorrro33** [PCSX2/pcsx2#1207] opened 2016-02-27 08:15 UTC
EDIT: Jump to the 4th message ;)

Hello,
I just noticed that this string is not present in the template and is therefore not localizable. http://a.pomf.cat/tsyavi.png
Hope this gets fixed, since this is quite minor.

**Comment by mirh** [comment] 2016-02-27 16:26
It's there to be honest. Both the [french](https://github.com/PCSX2/pcsx2/blob/master/locales/fr_FR/pcsx2_Main.po#L583) translation and [template](https://github.com/PCSX2/pcsx2/blob/master/locales/templates/pcsx2_Main.pot#L480). And I just tested and it works fine in Italian here.

**Comment by piorrro33** [comment] 2016-02-27 16:35
It seems like it is, but it's not loading for whatever reason. I'll compile my version and try if it works.

**Comment by piorrro33** [comment] 2016-02-27 16:39
Okay, I actually figured out the bug. So, when I pick System Default or French on the very first screen, and then I import my settings, it will turn back into English U.S. since it was the value that was set in my imported settings. So whether it is a bug or not, I don't know.

**Comment by mirh** [comment] 2016-02-27 17:24
I'd suggest to reword the issue title then

**Comment by piorrro33** [comment] 2016-02-27 18:01
Done.

**Comment by gregory38** [comment] 2016-03-01 09:27
So basically, import settings also gets the old language setting. Some people could see it as a feature rather than a bug.

**Comment by mirh** [comment] 2016-03-01 10:51
Mhh.. I'm not sure. 
Why Back button should be translated will Finish shouldn't?

**Comment by willkuer** [comment] 2016-03-01 11:30
What happens if you revisit this window after finalizing the initialization? Is this button always in the wrong language?

**Comment by piorrro33** [comment] 2016-03-01 15:04
I think it's localized if you revisit the window.

**Comment by willkuer** [comment] 2016-03-01 17:10
I guess gregory is right. If there is language information written in the ini it should be imported. However it should happen in a consistent way.

**Comment by CookiePLMonster** [comment] 2018-10-29 10:11
Turns out you still can confuse first time wizard so much so you end up seeing it in three different languages... I'll post repro steps later today, but as of the latest development build I got a 100% repro rate on this anomaly.

It looks like different elements of windows pick their language basing on different rules (I also was able to get Back and Cancel in one language, and Next in another).

**Comment by lightningterror** [comment] 2018-10-29 12:06
I guess the solution would be to first popup the window for importing settings, and not after the language is selected.

**Comment by CookiePLMonster** [comment] 2018-10-29 15:39
I would just ignore language when importing - it's the kinda setting which
you may not want to migrate.

And even then half of the buttons being in wrong language implies a
different kind of bug somewhere. Had the settings been overwritten, it
probably wouldn't manifest itself just like this.

**Comment by CookiePLMonster** [comment] 2018-10-29 18:00
Alright, I managed to narrow down repro steps to a sensible repro path. Turns out there are at least two issues with languages in Quick Wizard and I'll cover both.

Everything has been tested on the latest development build.

### Pre
a. Choose a set of three languages:
  - Language A - language corresponding to your OS regional settings (the one PCSX2 automatically picks during the first launch; in my case - Polish).
  - Language B - the one you used in PCSX2 prior to an "upgrade" (in my case - Dutch).
  - Language C - language you'll want to pick in Quick Launch wizard (in my case - English).

b. Ensure PCSX2 language is set to **B**
c. Ensure PCSX2 will run a Quick Start wizard next time by setting `RunWizard=1`

# Reproduction steps
1. Run PCSX2 - Quick Start wizard will show up, using language **A**.
2. In the drop-down list, select language **C**.

## Bug no. 1
3a. Click "Apply" - wizard's language changes to **C**.
4a. Select **Next**, then  **Import**.
5a. Observe navigation buttons - Back/Cancel are displayed in language **A**, Next is displayed in language **B**.
6a. Click **Next**, then **Finish**.
7a. Observe

### Observed results
Navigation buttons are displayed in mixed languages. PCSX2 ignores language selection from Quick Startup wizard.

### Expected results
After clicking "Apply" on the initial screen, all navigation buttons and PCSX2 overall is displayed in language **C**.


## Bug no. 2
3b. Do **NOT** click "Apply".
4b. Select **Next**.
5b. Observe the pop-up.

### Observed results
Pop-up displays in language **C**, even though we did not click "Apply".

### Expected results
Pop-up displays in language **A**.


If we can agree that the expected results are desirable*, I'll begin work on a PR fixing both those issues.

*I think we can all agree that navigational buttons displaying in mixed languages is a bug, however.

**Comment by CookiePLMonster** [comment] 2018-10-29 21:46
I have pushed #2664, a fix for mixed languages in navigation bars.

Since we didn't agree on whether picked language should be ignored at Import time or not, I have not touched that part of the issue yet.

**Comment by lightningterror** [comment] 2020-04-30 17:13
I will close this as one of the issues has been resolved, whereas the other seems more like a feature.

**Closed by lightningterror** 2020-04-30 17:13 UTC
Labels: GUI/WX
