### ISSUE TITLE
Crash Bandicoot: The Wrath of Cortex Fog and Water Effects On GS Hardware]: 

### ISSUE THREAD

**Issue by Codexmsters** [PCSX2/pcsx2#6180] opened 2022-05-24 23:45 UTC
### Describe the Bug

Fog and water effects Error

### Reproduction Steps

Press F9 To Fix

### Expected Behavior

PCSX2 Emulator Error

### PCSX2 Revision

PCSX2 Nighty v1.7.2797

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 3400G 

### GPU

Radeon RX 570 Series

### GS Settings

D3D11

### Emulation Settings

100%

### GS Window Screenshots

![gs_20220524204049_Crash Bandicoot - The Wrath of Cortex_SLUS-20238](https://user-images.githubusercontent.com/102823175/170149517-f0253012-b223-4f0d-a324-d9665d2b823d.png)

**Comment by Codexmsters** [comment] 2022-05-24 23:47
Software Rende
![gs_20220524204054_Crash Bandicoot - The Wrath of Cortex_SLUS-20238](https://user-images.githubusercontent.com/102823175/170149874-e588a99e-2967-45aa-9e83-d7df80afb6c5.png)
r

**Comment by lightningterror** [comment] 2022-05-25 00:37
Duplicate #2380

**Comment by dio-gh** [comment] 2022-05-25 00:44
Uhh, no idea if it's a duplicate of that. In general, none of what can be seen in this ticket should happen on latest nightly.

For one, GameDB should force on FBC and PFD. It doesn't for me, but even then, the CRC hack on mainline will cut the effect out. Even if you disable CRC hacks, this is not how it will be broken, and once you apply the correct settings, it will match Software.

I have not the slightest idea how the game looks like this for the poster, but I'm very doubtful it's the same issue as in that other ticket, and nor can I repro.

**Comment by dio-gh** [comment] 2022-05-25 01:06
I see the poster has swapped out the screenshot.

Closable, that's how the game looks with CRC hacks on, working as intended. Confirmed duplicate of another related issue.

**Comment by Codexmsters** [comment] 2022-05-25 01:12
@ #6005

**Closed** 2022-05-25 01:16 UTC
Labels: GS: Hardware
