### ISSUE TITLE
gz.pindex.tmp files not being deleted

### ISSUE THREAD

**Issue by tony971** [PCSX2/pcsx2#1666] opened 2016-11-20 01:48 UTC
***PCSX2 version:***
v1.5.0-dev-1599-gd64db65

***PCSX2 options:***
Default

***Description of the issue:***
All of my games have been compressed with the .gz format. Loading them generates a pindex temp file. However, this file is not temporary. It continues to stay in the game directory forever.

***How to reproduce the issue:***
Compress a game in a .gz file, load game, close game/close PCSX2, look in folder.

***Last known version to work:***
N/A

***PC specifications:***
CPU: Intel Core i5-6300u GPU: GTX 940m OS: Windows 10 64 Bit

**Comment by willkuer** [comment] 2016-11-20 05:33
I think that is intended. You need some index to access the single parts of the iso. Pcsx2 creates this index once upon first reading the compressed file and stores it to keep the loading time small.

@avih is the expert here.

**Comment by avih** [comment] 2016-11-22 16:04
It's temporary in the sense that it's not part of the ISO and if the user deletes it and then re-opens the gzip compressed ISO file, then PCSX2 can (and will) re-generate it automatically again.

However, generating it takes time (30-60s depending mostly on the ISO size and HDD performance) - as I'm sure you know, and so this file is kept such that next time you open the same gzip compressed ISO it starts instantly.

Using this index is unavoidable with gzip since this format was not designed to allow fast access to any point at the compressed file, and so the file is scanned once and this index is generated, and then saved to disk such that it doesn't have to scan the entire file again next time you open it.

What you can do though, is use a hidden option which sets the location of this file such that it doesn't clutter your directory where your ISOs are.

You can control it via the configuration `GzipIsoIndexTemplate` at `PCSX2_ui.ini`, where `$(f)` represents the ISO full path+name if it appears at the beginning, or the ISO name without path otherwise. examples:
- `GzipIsoIndexTemplate=$(f).pindex.tmp` - this is the default config where the index file is the same dir and name as the original ISO - but with an additional suffix.
- `GzipIsoIndexTemplate=c:/pcsx2_tmp_gz/$(f).pindex.tmp` will put all your gz tmp files at `c:\pcsx2_tmp_gz\` - *note* that:
  - You must first create this dir yourself.
  - There could be issues if you have two different ISO.gz files at different dirs but which have the same name (because their index file names will be the same).

Shall we close this issue?

**Comment by willkuer** [comment] 2016-11-22 16:16
One possible alternative would be to set the default pindex folder to the system's temporary folder (i.e. Windows -> '%TEMP%'). But not sure if it is better (especially regarding the naming clash mentioned by above).

**Comment by avih** [comment] 2016-11-22 16:34
> One possible alternative would be to set the default pindex folder to the system's temporary folder (i.e. Windows -> '%TEMP%'). But not sure if it is better (especially regarding the naming clash mentioned above).

Using env vars is already supported by this system, e.g. you could use `%TEMP%/$(f).pindex.tmp` for instance. But yes, the fact that it can fail for legitimate use cases makes it not good enough as a default config IMO.

**Comment by ramapcsx2** [comment] 2016-12-08 16:16
The usual suggestion is to put files like these in My Documents for Windows, or the user directory / Linux.
This should be the default, as it (probably?) is for other files, such as savestates and memcards.

**Comment by gregory38** [comment] 2017-03-11 10:57
On linux tmp data (aka the index) can be put in $XDG_CACHE_HOME. 

Otherwise, it is a valid issue. Or do we keep current situation ?

**Comment by avih** [comment] 2017-03-11 11:19
TBH, it's not clear to me what the issue actually is. It _seems_ that the OP complains that the file is described as temporary but stays after PCSX2 closes, which he finds confusing/inaccurate.

If that is the case, we can just call it a disposable cache file instead (which would be a better description indeed). Thought we should probably do so at the docs only, as I don't want to affect users who already have the index files with the old names, and I don't think it's worth supporting two names to support both.

**Comment by gregory38** [comment] 2017-03-11 11:35
@tony971 is it ok for you ? Shall we close this report ?

**Comment by gregory38** [comment] 2017-03-12 17:01
@tony971 Is it ok for you ? Or do you want some changes ?

**Comment by gregory38** [comment] 2017-03-13 17:21
Oh seem my IA stutters :stuck_out_tongue:

**Comment by MirandaStreeter** [comment] 2017-09-04 06:56
Hi, I've tried to redirect the disc image index to its own custom folder I created in my pcsx2 installation, but the following format...
> GzipIsoIndexTemplate=c:/pcsx2_tmp_gz/$(f).pindex.tmp

Didn't work. Depending on how I formated it the index file would either not appear (no idea where it went) or return to its default location.

So, I used the format I observed in the rest of the ini file, and used two double backslashes between each folder hierarchy, such as 
>\\Games\\Library\\Sony\\etc.

But, the instant I boot a disc image it always truncates the last two backslashes. For example, 
>//index//$(f).pindex.tmp

ends up as 
>//index$(f).pindex.tmp

which saves to the parent folder, and appends my intended foldername to the beginning of the filename instead. To observe the specific behavior, if I add four backslashes before the file variable it saves correctly, but, as it's only deleting two slashes at a time, on the next boot it'll save to the parent directory again.

I've fixed this by adding the word "index" to the beginning of my filenames, so it looks like "/pcsx2/index/index.nameOfGame.iso.gz.pindex.tmp", but now I'm seeing index so many times the word has lost all meaning to me.

**Comment by avih** [comment] 2017-09-04 07:28
> GzipIsoIndexTemplate=c:/pcsx2_tmp_gz/$(f).pindex.tmp

Note that you need to create the directory yourself, and in advance, as has been noted in my post above. Otherwise, it should work, and if it doesn't, then please post the log from the console when it fails.

**Comment by tony971** [comment] 2017-09-05 13:36
I just didn't understand what the "temp" files were. I didn't know that they were meant to be permanent and prevented huge delays in bootup times. This issue can be closed if you want, but a rename might be warranted for future idiots like me.

**Comment by MirandaStreeter** [comment] 2017-09-06 00:58
@avih  I knew from the beginning I had to create the directory myself. That wasn't the problem, the problem is the syntax you provided, and even using correct syntax bugs out by removing the last two backslashes, causing it to save to the parent directory.

**Comment by avih** [comment] 2017-09-06 04:59
> the problem is the syntax you provided, and even using correct syntax bugs out

I referred exactly to this. The syntax I provided _should_ work. I mentioned the directory should be created because I didn't know if you did that or not, and added that if it still doesn't work, post exactly what you put at that line at the INI file and also the console log.

I still stand by my request - the template I provided should work, and if it doesn't, give us more (exact) details of what doesn't work.

Also, FYI, this `/` is slash, sometimes also called forward slash. And this `\` is back-slash.

So when you say:
> truncates the last two backslashes. For example,  `//index//$(f).pindex.tmp` ...

But it doesn't actually have any backslash, I don't understand what you mean.

Do note that my example which you and me quoted: `GzipIsoIndexTemplate=c:/pcsx2_tmp_gz/$(f).pindex.tmp` has the following components:
- A drive letter (`c`)
- A colon (`:')
- A (forward) slash (`/`)
- A directory name (`pcsx2_tmp_gz`)
- Another (forward) slash.
- And `$(f).pindex.tmp` which means "The original file name with additional `.pindex.tmp` extension"

So if you follow this template and it still doesn't work, give us the exact details such that we can figure out why it doesn't work. Because it should work.

**Comment by willkuer** [comment] 2017-09-06 14:13
There might be some windows vs linux slash convention clash.

**Comment by FlatOutPS2** [comment] 2018-01-07 13:16
@avih What @MirandaStreeter said is true. If you use 2 backslashes instead of 1 forward slash like "D:\\games\\$(f).pindex.tmp" it ends up removing the second 2 backslashes in the ini and it ends up like this: "D:\\games$(f).pindex.tmp". It will work, but it stores the index file in the main folder of "D:\".

If works as intended when using "D:/games/$(f).pindex.tmp"

When using "D:\games\$(f).pindex.tmp" it will fail, though not remove any backslash, but there is a mistake in the log. It will print this twice:

```
"Invalid gzip index template 'D:ames(f).pindex.tmp'.
Template must contain exactly one '$(f)' and must not end with it. Abotring.
```

It removes the / and the first character following it (though that's expected behaviour handing strings, it should probably be handled differently).
And "Abotring" should probably be "Aborting". 😛

**Comment by avih** [comment] 2018-01-07 13:39
Feel free to fix it.

**Comment by turtleli** [comment] 2018-01-08 11:30
The double backslash issue is actually an issue caused by environment variable expansion in wxConfigBase. If `D:\\games\\aaa$(f).pindex.tmp` is used, the backslashes aren't truncated. The issue is with the character sequence `\\$`.

**Closed** 2022-12-25 17:54 UTC
Labels: Question / Discussion, Waiting feedback
