### ISSUE TITLE
Speed/Framelimiter issues with Valkyrie Profile 2

### ISSUE THREAD

**Issue by whatisthat** [PCSX2/pcsx2#40] opened 2014-05-03 17:56 UTC
I have two computers I use for PCSX2.

My Laptop: cpu i5 graphic NVIDIA 740M ram 8gb - win7 x64
My PC: AMD Phenom graphic: ati 6670 ram 8gb - win7 x64

The game runs slowly in many scenes, around 40fps in both computers. Sometimes after playing a little (30 min or more) randomly the speed increases to around 75fps. After this, the fps limiter does not work anymore and it is too fast in fights. The only solution I have found is to close pcsx2 and open it again.

I have tested this using a PCSX2 build from commit c6d8b52.

Thank you

**Comment by bositman** [comment] 2015-08-17 20:02
Can anyone reproduce this?

**Comment by willkuer** [comment] 2015-08-18 07:57
How can one reproduce this if there is no instruction how to reproduce it? I think the forum would've known this issue if it exists. I guess most of us have played longer than 30 min.

**Comment by bositman** [comment] 2015-08-18 10:09
Yes that's what I'm asking if anyone has experienced this after long plays, although my money is that the OP just hit F4 at some point...

**Comment by gregory38** [comment] 2015-11-07 17:21
No news, so I close it. Please reopen it if the issue is still valid.

**Closed by gregory38** 2015-11-07 17:21 UTC
Labels: Bug
