### ISSUE TITLE
[LINUX]PCSX2 ETHERNET ENABLED 1.7.0 DEV CRASH on Resident evil outbreak STARTUP, no LOG (ARCH LINUX)

### ISSUE THREAD

**Issue by samuk190** [PCSX2/pcsx2#3912] opened 2020-11-10 10:11 UTC
***PCSX2 version:***
PCSX2 DEV 1.7.0-20201108162843 - compiled on Nov 10 2020 (64 BITS)
``(For example, stable build v1.6.0 (or) development builds v1.7.0-dev-xxx)``

- **Notes**:

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``
SAFEST

- **Note**: Generally it's recommended to have settings as default as possible and use the ``Safest`` preset. If there's no issue with these settings but there is an issue with some other non-default option, then please state it explicitly.

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``
STANDARD PLUGINS THAT COME WITH IT.

***Description of the issue:***
``(What's the problem? - Screenshots showing the issue if applicable)``
The game(Resident evil outbreak 1 and 2)  doesnt open when option "Ethernet" is enabled on DEV9 Plugin

***How to reproduce the issue:***
``(Detailed step by step guide on how to replicate the issue)``
Download resident evil outbreak file 2 or 1 (japan iso) 
enable ethernet under dev9 option 
boot

***Last known version to work:***
It worked flawlessy on ubuntu with 1.6.0. 
Flatpack doesnt come with dev9 plugin so I was unable to try with it.
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
my low end pc:
Host Machine Init:
	Operating System =  Linux 5.8.18-1-MANJARO x86_64
	Physical RAM     =  24045 MB
	CPU name         =  AMD Ryzen 7 1700 Eight-Core Processor
	Vendor/Model     =  AuthenticAMD (stepping 01)
	CPU speed        =  3.589 ghz (16 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  178bfbff 7ed8320b
	x86EFlags        =  2fd3fbff
GPU GTX 1070

**Comment by samuk190** [comment] 2020-11-10 10:12
I was unable to get log, its empty on the pcsx2 folder

**Comment by refractionpcsx2** [comment] 2020-11-10 11:57
Apparently your question was answered on the AUR comments

**Comment by GovanifY** [comment] 2020-11-10 11:57
You need to have the rights to use the interface with dev9. Either you give yourself the rights to a tap interface bridged to your network or you launch pcsx2 as root and use whatever interface. Closing as this isn't a regression, but feel free to ask questions if you are still confused!

**Closed by GovanifY** 2020-11-10 11:57 UTC
Labels: Dev9, OS: Linux

**Comment by samuk190** [comment] 2020-11-11 12:05
@GovanifY  funny that it works with CLR9_DEV with 1.6.0 pcsx2. 
the problem only behaves on gigahertz dev9..

**Comment by GovanifY** [comment] 2020-11-11 12:27
@samuk190 That's because CLR used a per port implementation which had to be configured per game and would never work for all edge cases.
