### ISSUE TITLE
[BUG]: PCSX2 crashes when trying to run a game using vulkan on Wayland

### ISSUE THREAD

**Issue by pupilo-py** [PCSX2/pcsx2#8200] opened 2023-02-19 14:24 UTC
### Describe the Bug

Using the X11 graphics server works perfectly, but when I switch to the Wayland graphics server and try to run a game using vulkan, PCSX2 closes instantly.

![2023-02-19-11-16-54](https://user-images.githubusercontent.com/58078395/219954243-29eb4c44-fe3f-42e1-b80f-881ebf22f499.gif)

![Screenshot_20230219_111938](https://user-images.githubusercontent.com/58078395/219954297-598fa518-331b-49b8-b92f-f51e65b856c3.png)

### Reproduction Steps

1 - Change the X11 graphics server to Wayland
2 - Use the Vulkan API
3 - I try to run a game
4 - PCSX2 closes.

### Expected Behavior

Run the game using the Vulkan API.

### PCSX2 Revision

v1.7.4117

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Kubuntu 22.10

**Comment by pupilo-py** [comment] 2023-02-19 14:28
My system specs:

![image](https://user-images.githubusercontent.com/58078395/219954470-14cc494a-1969-4f90-88a0-3a17aae5050a.png)

**Comment by stenzek** [comment] 2023-02-19 14:46
Duplicate of #8198 which was invalid.

Please don't spam our issue tracker, or we will have to block you.

**Closed by stenzek** 2023-02-19 14:46 UTC
Labels: Bug

**Comment by pupilo-py** [comment] 2023-02-19 14:50
@stenzek 

I had to duplicate the issue because I brought up the problem in the other issue and you simply ignored the problem, because of a print run of the flatpak version, even though I explained that it occurred in both versions. So I created this new one just listing the appimage version.

**Comment by stenzek** [comment] 2023-02-19 14:58
The screenshot doesn't matter. I ran it myself and it works fine.

If you're not going to at least provide a backtrace, there is nothing else to discuss here.

**Comment by pupilo-py** [comment] 2023-02-19 15:05
> The screenshot doesn't matter. I ran it myself and it works fine.
> 
> If you're not going to at least provide a backtrace, there is nothing else to discuss here.

I went to the logs area, but it didn't provide any, the only thing I could do was a screenshot of the application running through the terminal and graphical mode. But that's it, if you can't do something, that's fine, sorry to bother you.

**Comment by RedDevilus** [comment] 2023-02-19 15:08
Backtraces don't get shown in logs, you need something like visual studio (code) to run and debug and see where it crash and it will give you the steps of process and why it crashes.

**Comment by stenzek** [comment] 2023-02-19 15:10
There's nothing we can do when you don't tell us where it's crashing. The log file doesn't say that, a backtrace does.

All I can guess it's something funky with NVIDIA/Wayland, which is out of our control anyway.

**Comment by pupilo-py** [comment] 2023-02-19 15:15
Thank you very much for your attention, really. Sorry for any inconvenience.
