### ISSUE TITLE
Ratchet and Clank series: bug in HW mode.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#2088] opened 2017-10-06 15:34 UTC
***PCSX2 version:***
Last 1.5 dev

***PCSX2 options:***
All default, Only MTVU is enabled (bug also without)

***Plugins used:***
All default, GSDX OpenGL

***Description of the issue:***
The Ratchet and Clank series have a big issue in OpenGL mode.In some levels (Aquatos in the 3rd, Catacrom 4 in Gladiator), the graphics of the game disappear after visiting a weapon seller or by pausing the game in OpenGL mode

![capture](https://user-images.githubusercontent.com/26351275/31285589-fff52bee-aabb-11e7-8972-cbbf06cd266c.JPG)

***GSDUMP***
https://drive.google.com/open?id=199hYw5E6zETf4XksyztuzMtRa3-6Exlc

***How to reproduce the issue:***
Set GSDX in OpenGL mode, load Ratchet Gladiator, go in the Catacrom 4 level, pause the game and exit the pause menu. Same for Ratchet and Clank 3 in the Aquatos level.

***Last known version to work:***
Don't exist, was broken before.

***PC specifications:***
AMD fx8350  GTX 780Ti  Windows 10 64 Bit

**Comment by MrCK1** [comment] 2017-10-06 15:35
Try toggling mipmapping? Is automatic gamefixes enabled?

**Comment by atomic83GitHub** [comment] 2017-10-06 15:42
Toggling mipmapping don't solve the issue, automatic gamefixes and Widescreen patch are disabled.

Note: the DX11 render is not affected and work nice.

**Comment by MrCK1** [comment] 2017-10-06 15:44
Can you test 1.4.0 and see if the issue still exists?

**Comment by atomic83GitHub** [comment] 2017-10-06 15:46
Yes, the issue is also on 1.4.0 version.

**Comment by MrCK1** [comment] 2017-10-06 15:48
Can you go further back to 1.2.1 and 1.0.0?

**Comment by atomic83GitHub** [comment] 2017-10-06 15:57
1.0.0 don't have a OpenGL render Under GSDX and 1.2.1 crash when pausing.

**Comment by MrCK1** [comment] 2017-10-06 16:05
Are both SW and HW render modes in OGL affected?

**Comment by atomic83GitHub** [comment] 2017-10-06 16:08
Yes.

**Comment by Dreadmoth** [comment] 2017-10-06 21:13
Enabling Fast Texture Invalidation hack or Disable Depth Emulation hack seems to prevent this issue from occurring. It won't fix it if it has already occurred - rebooting the game seems to be necessary in that case.

**Comment by atomic83GitHub** [comment] 2017-10-10 17:04
Here is the blockdump from the main menu to the bug:
https://drive.google.com/file/d/0B0Ph0W1NYxIVekNUbnlacmNfeVk/view?usp=sharing

**Comment by lightningterror** [comment] 2017-11-28 11:51
The gs dump isn't available. Also can you provide a savestate with the block dump ?

**Comment by atomic83GitHub** [comment] 2017-12-06 17:19
I have updated the link. Here it is: https://drive.google.com/open?id=199hYw5E6zETf4XksyztuzMtRa3-6Exlc

**Comment by Bettehem** [comment] 2018-05-14 16:29
@Dreadmoth Thanks, this fixed the issue.

**Comment by JanLeonard** [comment] 2022-08-23 10:02
Recently the hack could be disabled.
I've track that since #6659 was merged the issue no longer occur
At least (Aquatos in the 3rd, Catacrom 4 in Gladiator) 
From mentioned PR:
> This works for everything I've checked so far, and results in a framebuffer size of 512x448 instead of 512x896 as was common before

idk for sure if this was causing it but, every time the bug appear using debug build the height during invalidation local memory in TC was doubled.
Someone spot another location/planets or events where the bug could came out?

To test this issue we can't use a dump or savestate we must load using memcard as @Dreadmoth mention

> If a save state is made after the issue has occurred, the issue will persist if the save state is loaded (even after changing settings and rebooting) - a memory card save must be loaded to fix it.

**Comment by refractionpcsx2** [comment] 2022-08-23 10:09
I'd be nervous of relying on that to disable the hack, I suspect it's possibly masking the issue, rather than fixing it, which happens a lot in the TC, so it might rear its ugly head again.

**Comment by refractionpcsx2** [comment] 2023-06-06 12:34
Should be resolved now, I believe, if this continues please reply and we can reopen.

**Closed by refractionpcsx2** 2023-06-06 12:34 UTC
Labels: GS, GS: Texture Cache
