### ISSUE TITLE
Valkyrie Profile: Silmeria [NTSC-U] - missing audio, softlock during cutscene

### ISSUE THREAD

**Issue by trostboot** [PCSX2/pcsx2#1555] opened 2016-09-09 17:40 UTC
-PCSX2 version: PCSX2 1.5.0-20160905201613, also tested with 1.0.0 and 0.9.6

-PCSX2 options: Defaults, no speedhacks, also tested with EE/IOP and VU interpreters

-Plugins used: GSdx, SPU2-X, Pokopom

-Plugin settings: D3D11 SW

-Description: Entering the boss room in the Turgen Mines dungeon triggers a short cutscene.
Audio is completely missing during the scene.
Half-way through the scene the game softlocks. Some animations will continue to play, but the cutscene does not advance and trigger the boss.
Skipping the cutscene results in the fight proceeding normally.

-How to replicate: Enter the boss room in Turgen Mines.

-Last known version to work: Unknown, probably never worked. There's at least one vague mention of this issue on the forums dating back to 2011.

-PC specifications: Intel i5 4690k, 16GB RAM, AMD Radeon 270X, Win10 64bit.

Memory Card: 
[vp2lock.zip](https://github.com/PCSX2/pcsx2/files/464484/vp2lock.zip)
Simply go right one room after loading the supplied save.

Emulog:
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/464526/emuLog.txt)

**Comment by willkuer** [comment] 2016-09-09 17:47
Can you please post the emulog after you observed the problem?

**Comment by trostboot** [comment] 2016-09-09 18:02
Updated with log.

**Comment by vsub** [comment] 2016-09-09 19:24
Probably some audio related thread get stuck.
Here is something interesting

1.Set the audio Synchronizing Mode to Async Mix
2.Run the game in window mode
3.When the cut scene start,set the game window as inactive(for example click on the taskbar)and then activate it(click on it)

This will result in half a second pause and then the audio will return and the cut scene will continue

**Comment by trostboot** [comment] 2016-09-09 19:41
Interesting, that's literally the one SPU setting I didn't try changing. Setting it to Async before entering the room fixes the cutscene completely. None and Timestretch break it.

**Comment by willkuer** [comment] 2016-09-09 23:10
Maybe check as well the hidden delayCycle setting in spu2-x.ini. I think default is 4. Try low numbers as 0,1,... instead.

**Comment by vsub** [comment] 2016-09-10 03:58
No change,only async with the method above fixes the problem

**Comment by jcdenton2k** [comment] 2016-09-21 23:50
Could someone please add this to the wiki?  That capcatcha used doesn't seem to load properly on my browser (even with a portable clean version with no extensions enabled).  I'd love for the team to switch it to reCaptcha or something like that.

**Comment by FlatOutPS2** [comment] 2016-09-25 21:17
Added fix to the wiki page, and as the issue has been resolved I'll close it.

**Closed by FlatOutPS2** 2016-09-25 21:17 UTC

**Comment by trostboot** [comment] 2016-09-26 06:14
How has this been resolved? Using async mix is a workaround, but the issue is still there and thus shouldn't be closed.

**Comment by FlatOutPS2** [comment] 2016-09-26 09:40
If changing a setting doesn't count as a fix, hundreds of issues would still be open. Not every game works perfectly with default settings. PCSX2 options aren't just cosmetic.

**Comment by Bracket-** [comment] 2016-09-29 15:27
Should using Async audio really be considered a fix? A temporary workaround until the problem is understood and/or fixed, sure. This shouldn't be treated like some issues that simply can't be properly fixed.  

An issue is and issue and closing them simply because there's a workaround or alternative available is bad practice in my opinion.

**Comment by trostboot** [comment] 2016-09-29 16:07
@Bracket-  Personally I agree with that. That's what an issue tracker and proper labelling should be for. 
But as an outsider to the project I'm not too comfortable arguing about it beyond what was already said. If they're happy with the current practice, that's their right, I suppose.

**Comment by FlatOutPS2** [comment] 2016-09-29 18:38
> Should using Async audio really be considered a fix? A temporary workaround until the problem is understood and/or fixed, sure. This shouldn't be treated like some issues that simply can't be properly fixed/implemented that require hacks.
An issue is an issue and closing them simply because there's a workaround or alternative available is bad practice in my opinion.

If Async audio caused several other major issues in the game, you'd make a good point, but as there don't seem to be any, it is a good fix for this game. Keeping all the issues that are fixed by changing a setting open, would make it very difficult to focus on and fix the issues that don't have any solution. You have to realize there are only a handful of people actively working on this project.

**Comment by jcdenton2k** [comment] 2016-09-29 23:29
Is there any way to make this an 'Automatic' gamefix for this specific game?
I realize how much I'd loathe adding in yet another custom hack just for one game but it could be 'temporary' until the devs have time to address the underlying compatibility issues causing the workaround to be necessary.

Just for fun, pulled out my disc from storage, ripped it to my hard drive, transferred it to my PS2's internal hard drive, then loaded it up via OPL.  It seems the game itself absolutely pushed the PS2 to the limit so even on actual real hardware it encounters some slight slowdown/stuttering at times.

They really need to do a PC re-release of this game already >_>
