### ISSUE TITLE
[Request] Another vertical black line hack?

### ISSUE THREAD

**Issue by mondaychicken** [PCSX2/pcsx2#3277] opened 2020-03-08 07:49 UTC
I played Tales of Symphonia with this patch(830B6FB1.pnach)

and found out it have no vertical black line without vertical line hack and more 

clear.

This patch is in 'No interlacing codes' section. 
https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=605007#pid605007

Maybe, Vertical line problem is related to interacing.

If we can know how it works, 

it helps many vertical black line games and blur filter games.

Screenshot
default setting + native x5 + with this patch 
https://imgur.com/a/ENTaeGO

default setting + native x5
https://imgur.com/a/0QG5HFt

Thanks.

**Comment by mirh** [comment] 2020-03-08 21:15
And you did test that sprite hacks and whatnot wouldn't work instead?

**Comment by tadanokojin** [comment] 2020-03-08 21:49
What he is saying is that the hack isn't needed with the de-interlace code, Probably because it does a sprite copy for the final frame.

Typical of large sprite copies on the GS is to split them up like that for performance reasons since the GS cache misses a lot in the horizontal direction. That's probably the cause.

**Comment by mondaychicken** [comment] 2020-03-09 08:11
@mirh 
Sorry, I did not test that.

@tadanokojin 
Yes, I think so.
Can be implemented pcsx2 ?  ex) GSdx option style
It will help to improve image quality.

**Comment by mirh** [comment] 2020-03-09 18:37
>  Sorry, I did not test that.

Then please, test that frist. It should be enough and the proper fix.

**Comment by mondaychicken** [comment] 2020-03-22 10:43
The built-in black line hack works properly,
But it has big difference on image quality.

Screenshot
with built-in black line hack
![gsdx_20200322192133](https://user-images.githubusercontent.com/35862336/77247477-ead42800-6c74-11ea-9297-399faa91f731.png)

with no interlacing patch
![gsdx_20200322192333](https://user-images.githubusercontent.com/35862336/77247495-27078880-6c75-11ea-8d3b-b524a200fba2.png)

**Comment by lightningterror** [comment] 2020-03-22 11:39
I'll go ahead and close this since we have a working hack/solution, for blur no interlace patches can be used.

**Closed by lightningterror** 2020-03-22 11:39 UTC
Labels: Invalid

**Comment by mirh** [comment] 2020-03-22 16:08
> But it has big difference on image quality.

Of course, fixing "blur" is the whole point of the no interlacing hack lol.
