### ISSUE TITLE
Auto update on PCSX2

### ISSUE THREAD

**Issue by clorophilla** [PCSX2/pcsx2#3054] opened 2019-08-03 05:41 UTC
PCSX2 version: 1.5.0-any

***Description of the issue:***
I don't know how feasible this is, but I think an auto-update function for PCSX2 on dev builds would be pretty nice (Just like Dolphin, it has one). We don't have frequent updates like said emulator, but still it's better than doing updates manually and since games get fixes, could be a godsend. I don't know if it's possible on Linux, though.

**Comment by tadanokojin** [comment] 2019-08-03 05:46
Linux side (at least Ubuntu) has daily PPA.

However, I've expressed some interest in this as well for Windows.
I've proposed that we build with appveyor and push the builds to github releases to avoid appveyor's retention policy.

**Comment by mirh** [comment] 2019-08-08 09:53
Duplicate of  #2439

**Comment by mirh** [comment] 2019-09-13 08:36
The thing is, Orphis server doesn't come for free. 
And that couple of ads he has are a pretty fair compensation for him.

**Comment by yesiateyoursheep** [comment] 2019-09-13 08:49
Fair, how about the updater shows the site in order to show the changelogs? It would in concept be very much like the Dolphin updater, which shows a window with a description of the changes and asks for confirmation. It would also increase the number of ad views and bypass ad blockers in the browser.

**Comment by mirh** [comment] 2019-09-13 08:58
"Showing the site" would feel really shitty to be honest, considering we'd have to embed webkit. 
... or wait, perhaps there's just an OS function that makes you rely on internet explorer... but that also seem overly messy. 

But if it's just for the changelog text, maybe it could be possible to have a tiny json on the main website that get parsed. I'm not sure if pcsx2 even ships any network feature though?

**Comment by yesiateyoursheep** [comment] 2019-09-13 09:10
You can definitely embed an IE instance, though definitely not a cross-platform or future-proof way to go about it.
Networking doesn't need to be added to pcsx2 as the updater should be an entirely independent executable.

The complications make it obvious as to why this has been put off though.

**Comment by mirh** [comment] 2019-09-13 09:18
Cross-platform isn't an issue. Linux has already those magical things called *repositories*. 
If it's another executable, well.. It's just about somebody wanting to write some code.

**Comment by yesiateyoursheep** [comment] 2019-09-13 10:55
I'd be happy to give it a crack. I'll try and find a way to package everything needed into one executable file.

**Comment by yesiateyoursheep** [comment] 2019-09-15 04:22
I've created a concept for the UI. Unfortunately, the ads on Orphis' site don't seem to work with Internet Explorer in IE7 compatibility mode, which is what we might be stuck with without an external library.

I installed CEF as a solution to that, but it's ludicrously large (over 100MB). So unless we can fix ads on Orphis' site, an updater that shows the site is easily possible, but wouldn't meet the requirements.

So I've added the web UI updater to [a branch on a fork on my GitHub](https://github.com/PCSX2/pcsx2/compare/master...yesiateyoursheep:updater). Here's a screenshot;
![image](https://user-images.githubusercontent.com/7791524/64916621-dea67400-d7d4-11e9-9474-ddd39c3ba2c7.png)

I'll be moving to another branch with a simplified updater that notifies the user when an update is out and links to the site. Possibly within the main window of pcsx2? I'll see what I can do.

**Comment by mirh** [comment] 2019-09-15 10:10
You [aren't forced](https://weblog.west-wind.com/posts/2011/May/21/Web-Browser-Control-Specifying-the-IE-Version) to IE7 mode. 
We could easily ask orphis to add the X-UA-Compatible tag. 

And having a viewer to its page, also showing the ads, is really a super nice thought.

**Comment by yesiateyoursheep** [comment] 2019-09-15 10:47
I might try to clone his site and add the tag first to see if it works. It's a random JS issue, so I have no idea if X-UA-Compatible will fix it. I'll also email him tomorrow to see if he's responsive at all.

**Comment by yesiateyoursheep** [comment] 2019-09-15 22:53
The results were inconclusive, I wasn't getting any script errors, but they still weren't rendering on my test server. I've contacted Orphis to see if it works on the real server, in the meantime, I'll continue working on a simpler update checker within the main frame of PCSX2. I'm thinking I'll use a combination of the two in the end.

I have two branches in my fork of pcsx2 to follow and contribute to, if anyone is interested.
https://github.com/yesiateyoursheep/pcsx2/tree/updater
https://github.com/yesiateyoursheep/pcsx2/tree/simple-updater

**Comment by RedDevilus** [comment] 2022-01-15 00:23
Similar to https://github.com/PCSX2/pcsx2/issues/3179

**Comment by yiays** [comment] 2022-01-15 00:46
Regarding the concept of a chocolatey package, there's now a far better source for nightly builds, [GitHub Actions](https://github.com/PCSX2/pcsx2/actions/workflows/windows-workflow.yml) though I'm not sure if there's a way to directly download the latest build, every commit is built and is [accessible via the GitHub API](https://docs.github.com/en/rest/reference/actions#list-artifacts-for-a-repository). The only catch is that the API caller must be logged in in order to download artifacts - as to why this isn't very helpful for a client-side auto-updater.

**Comment by RedDevilus** [comment] 2022-01-28 22:09
If you guys really want a PCSX2 updater for now, there exist the forum if you don't want to wait any longer:
https://forums.pcsx2.net/Thread-Simple-PCSX2-Updater

**Comment by seta-san** [comment] 2022-05-19 23:07
This is implemented on qt builds.

**Closed** 2022-05-19 23:11 UTC
Labels: Question / Discussion, Maybe?, GUI/Qt
