### ISSUE TITLE
[BUG]: Screen turns off while playing

### ISSUE THREAD

**Issue by Terminykos** [PCSX2/pcsx2#8729] opened 2023-04-24 17:24 UTC
### Describe the Bug

Hi,
I have set my screen to turn off after 5 minutes of inactivity and never had any problem with other games or emulators. Only with PCSX2 my screen turns off after 5 minutes when I'm in the middle of a game. I tried to change the video render and checked "Inhibit screensaver" but nothing changed.
I'm using PikaOS 22.10 and PCSX2 Nightly v1.7.4410 with and AMD RX 6700 XT (Mesa Driver 23.0.3)

### Reproduction Steps

Just playing a game.

### PCSX2 Revision

v1.7.4410

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

PikaOS 22.10

**Comment by Mrlinkwii** [comment] 2023-04-24 17:52
Are you using the appimage , If so x11 or Wayland?

**Comment by Terminykos** [comment] 2023-04-24 22:18
I'm using the flatpak and x11

**Comment by CharlesThobe** [comment] 2023-04-24 23:36
> I'm using the flatpak provided by the distro's software manager and x11

Only the appimage is supported by the pcsx2 team, try the appimage and if you can't reproduce the issue there then please close this bug.

**Comment by stenzek** [comment] 2023-04-25 03:41
Clearly not our bug. We don't support crappaks.

**Closed by stenzek** 2023-04-25 03:41 UTC
Labels: Bug

**Comment by Terminykos** [comment] 2023-04-25 21:42
Thank you, perfectly working with the appimage! I didn't know that the flatpack was some kind of "rebuilded" package from random people ;)
