### ISSUE TITLE
[BUG]: Wild Arms 3 texture dump error

### ISSUE THREAD

**Issue by Cyberosis** [PCSX2/pcsx2#8070] opened 2023-02-07 09:49 UTC
### Describe the Bug

I wanted to redo/upscale the UI in Wild Arms 3 to make the game more pleasant to play. When I started dumping though, pcsx2 grabbed the same textures over and over with garbage graphics around them. It seems pcsx2 is incorrectly determining the texture area in buffer. It samples double the height and width so it thinks that if anything changes in that area it's a new texture. It only does this with UI elements.

Highlighted these examples:
![e8461534c811505e-6cfa548e5f5c9b50-00006klhklaac](https://user-images.githubusercontent.com/60300155/217209835-5b57edbd-3c1d-45c5-b90d-eaed92c5273b.png)
![5e5b5e60efd42fdf-e4a52411711906-00005993](https://user-images.githubusercontent.com/60300155/217209899-594cb24a-a45c-46b7-b84f-2f49afdd8976.png)

### Reproduction Steps

Start Wild arms 3 and enable texture bumping. Then look at text textures in dump folder

### Expected Behavior

Exports UI textures at proper size and independently of buffer garbage.

### PCSX2 Revision

v1.7.4019

### Operating System

Windows 10 (64bit)

### CPU

AMD 5900X

### GPU

RTX 3080

**Comment by refractionpcsx2** [comment] 2023-02-07 09:51
This is quite normal for games, especially if the texture size isn't a power of two, it will go to the next size up, so you end up with a bunch of garbage, in fact #8015 attempts to get around this in some cases to make it nicer to use.

**Comment by stenzek** [comment] 2023-02-07 10:04
Try the PR refraction linked, otherwise this is a WONTFIX as it's likely workign as intended.

**Closed by stenzek** 2023-02-07 10:04 UTC
Labels: Bug

**Comment by Cyberosis** [comment] 2023-02-07 10:19
Thanks For the explanation. had no idea it was a known thing, sorry for the repeat issue.

**Comment by refractionpcsx2** [comment] 2023-02-07 10:21
It's all good, we don't expect everybody to know how the PS2 works.

**Comment by Cyberosis** [comment] 2023-02-07 10:57
Can't seem to get the github to compile. Maybe I should just wait till it's merged. This is probably over my heard

**Comment by Mrlinkwii** [comment] 2023-02-07 11:00
@Cyberosis  theirs no need ,click this link here https://github.com/PCSX2/pcsx2/actions/runs/4090352450 and dowbnload :)

**Comment by Cyberosis** [comment] 2023-02-07 19:56
Thanks! This did in fact improve things slightly. The text is still busted but the art behind it is exporting correctly now. I'll take it
