### ISSUE TITLE
[BUG] Crash Twinsanity upscaling regression

### ISSUE THREAD

**Issue by ManDude** [PCSX2/pcsx2#3976] opened 2020-12-06 01:37 UTC
**Describe the bug**
Crash Twinsanity simply does not upscale correctly. On any upscale setting, the game resolution will be almost halved, with every pixel seen on-screen being turned into a 2x2 pixel OR 1x2 pixel. This means that 2x resolution will actually look *worse* than 1x native resolution due to the inconsistent pixel size, and to achieve something closer to 2x resolution you would have to use 4x resolution instead, which has obvious performance drawbacks on top of not looking like 2x resolution either. Here is a snapshot of the game at native 512x512 resolution, and another one below with the game at 2x upscaled 1024x1024 resolution.

![gsdx_20201206012923](https://user-images.githubusercontent.com/7569514/101269088-9caf7800-3762-11eb-9162-391fd136af4b.png)
![gsdx_20201206012932](https://user-images.githubusercontent.com/7569514/101269089-9d480e80-3762-11eb-93a7-afb9d3ae0848.png)

(the cyan-looking line is due to the half-screen behavior and is not relevant this issue)

**To Reproduce**
Simply use any upscale setting in GSdx.

**Expected behavior**
I expect the resolution to maintain a crisp resolution, which isn't the case for this game. Previous versions worked fine (I am trying to figure out at which point this behavior regressed) (EDIT: still happens as far back as 1.5.0-dev-3072, strange... I wonder if it's actually caused by some nasty driver update? I wouldn't know).

**GS Settings**
Does not matter, I have tried every single setting and none of them were affecting this issue, thus I left everything in default.

**Emulation Settings**
None of the speedhacks, or other emulation settings, had any relevant impact on the game's upscaled visuals.

**System Info (please complete the following information):**
 - PCSX2 Revision: v1.7.0-dev-652, 32-bit.
 - OS: Windows 10 64-bit
 - CPU: AMD Ryzen 5 3500U @ 2.1GHz
 - GPU: AMD Radeon Vega 8 Graphics

**Comment by lightningterror** [comment] 2020-12-11 00:04
Tested it, couldn't reproduce it.

**Comment by RedDevilus** [comment] 2022-04-11 00:02
This in GameDB:
```
  gsHWFixes:
    halfPixelOffset: 2 # Fixes depth lines.
```
    
Atleast fixes that horizontal line, not sure how to interpret the rest of the issue.

**Comment by RedDevilus** [comment] 2022-04-11 00:08
I'll close this for now, it should be fine in my opinion. Can always be re-opened.

**Closed by RedDevilus** 2022-04-11 00:08 UTC
Labels: Bug, GS: Hardware

**Comment by ManDude** [comment] 2022-04-11 04:33
Yeah, it's fixed for me as well now. I don't know when, how or why, but at least it's over now.

**Comment by Ghost-Frank-Woods** [comment] 2023-07-25 19:37
Hello, I have encountered a problem with the game Crash Twinsanity on pcsx2. I have tested the old and new versions, but when playing the cutscenes of the game, I get lag and ticks, and I have very little lag in the game. Please tell me what to do to solve the problem?
