### ISSUE TITLE
USBqemu not showing usb devices and randomly crash the emulator when starting a game

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2060] opened 2017-08-30 20:44 UTC
***PCSX2 version:***
Last 1.5 dev

***PCSX2 options:***
All default

***Plugins used:***
All default (USBqemu is with the emulator)

***Description of the issue:***
-***The USBqemu plugin not work: it show a blank window when selecting a device***
![image](https://user-images.githubusercontent.com/26351275/29894033-6330d172-8dd4-11e7-8e79-13d353c7b39f.png)
-***USBqemu can crash a game when it start***

***How to reproduce the issue:***
Load PCSX2 with USBqemu.

***Last known version to work:***
Don't exist, the plugin was also broken before.

***PC specifications:***
Intel Core 2 Duo E8600 Gigabyte GTX 780Ti Windows 10 64 Bit

**Comment by turtleli** [comment] 2017-08-30 21:35
Duplicate of #106 and #310?

**Comment by atomic83GitHub** [comment] 2017-08-31 00:20
Oops, I don't check that, topic closed.

**Closed** 2017-08-31 00:20 UTC
