### ISSUE TITLE
Changing default paths work unreliably (wxGTK 2.8, GTK 2, KDE4)

### ISSUE THREAD

**Issue by akien-mga** [PCSX2/pcsx2#1120] opened 2016-01-16 10:49 UTC
Hi there,

I built v1.4.0 on Linux against wxGTK 2.8 / GTK 2 and am running it in KDE4.
When trying to change the default path to a folder (e.g. the folder for savestates), I need to click browse and select the path I want to use at least twice until it's actually set as the path that will be used.

This video aims at showing how to reproduce the issue: http://remi.verschelde.fr/files/misc/pcsx2-redefine-folder.mkv

I can't test against wxGTK 3.0 right now as my distro's version is built against GTK 3, and from what I could see in the CMakeLists.txt it looks like PCSX2 does not support GTK 3 very well yet. I might check if the issue is reproducible in another DE though (i.e. using another file dialog than KDE's).

**Comment by gregory38** [comment] 2016-01-20 13:10
There is an option to enable GTK3 on cmake. It is not yet properly tested but it might be enough to test the behavior of the box.

**Comment by akien-mga** [comment] 2016-01-20 15:00
That's a good point, I'll try a wxGTK 3.0 / GTK 3 build as it should already provide interesting input.

**Comment by akien-mga** [comment] 2016-01-24 15:22
I've tried a wxGTK 3.0 / GTK+3 build but several plugins seem to fail building against GTK+ 3.19.7. Here's a complete build log, search for "error:" to see the issues: [pcsx2-1.4.0-wxgtk3.0-gtk3-build.0.20160124150004.txt](https://github.com/PCSX2/pcsx2/files/102390/pcsx2-1.4.0-wxgtk3.0-gtk3-build.0.20160124150004.txt)

**Comment by akien-mga** [comment] 2016-01-24 15:26
BTW in the meantime I've moved from Mageia 5 to Mageia Cauldron (development version of the future 6th release) and thus to Plasma 5 instead of KDE4, but the issue is the same as described above, so it's at least not KDE4-specific.

**Comment by turtleli** [comment] 2016-01-26 19:40
On the GTK+3 compilation error - don't build the extra plugins, they don't compile with GTK+3.

What GTK+2 theme you are using? I can't reproduce this since I only have a Browse button.

**Comment by akien-mga** [comment] 2016-01-26 20:15
> What GTK+2 theme you are using? I can't reproduce this since I only have a Browse button.

Adwaita IIRC. Note that my video shows the bug when using the preset folders, but the bug also happens for me with the Browse button only. Browsing and selecting one folder won't work, but doing it a second time (or third time, not sure) will work fine.

**Comment by turtleli** [comment] 2016-01-26 20:31
Ok, I missed that, but it works on the first time on my Linux boot (wxGTK2.8 / GTK+2 / Fluxbox). I'll see whether any of my VMs can reproduce the issue.

But it might be better just to compile against wxGTK3 / GTK+3 - last I checked there were fewer issues than with wxGTK2.8.

**Comment by turtleli** [comment] 2016-02-09 23:54
Well, I tried on wxGTK3 / GTK2 / KDE4, I still only had a browse button and that worked fine.

So I don't know whether it's because I'm not testing the right theme (I haven't looked very hard) or whether it's wx2.8 specific, which I hope it is, because then I can just close this issue ;)

**Comment by gregory38** [comment] 2016-11-08 19:35
@akien-mga do you still have the issue ? Could you try with WX3 (GTK3)

**Comment by lightningterror** [comment] 2018-02-22 21:42
Is this issue still present ?

**Closed** 2018-03-02 23:22 UTC
Labels: GUI/WX, OS: Linux, Waiting feedback
