### ISSUE TITLE
Graphical regression in v1.5.0-dev-2574

### ISSUE THREAD

**Issue by Bezier89** [PCSX2/pcsx2#2617] opened 2018-10-04 02:59 UTC
***PCSX2 version:***
Started in version v1.5.0-dev-2574-g629d2bd42. Confirmed issue is not present in v1.5.0-dev-2573-g92484a841. Issue is still present in latest build (v1.5.0-dev-2584-g940263d49).

***PCSX2 options:***
All options are default (tested with freshly unzipped pcsx2). OpenGL renderer at native resolution.

***Description of the issue:***
Soulcalibur III has messed up colors. See screenshots at bottom.

***How to reproduce the issue:***
Open Soulcalibur III. View start screen.

***Last known version to work:***
v1.5.0-dev-2573-g92484a841

***PC specifications:***
CPU: Intel Core i3-4170T
GPU: Nvidia GeForce 860m
OS: Windows 10 64 Bit

@KrossX It would appear https://github.com/PCSX2/pcsx2/commit/629d2bd425b6270625b470ebe22279ad9f100620 has introduced some major graphical regressions (at least in Soulcalibur III).

v1.5.0-dev-2573-g92484a841:
![gsdx_20181003221646](https://user-images.githubusercontent.com/6324883/46450457-4fd54e80-c75f-11e8-88cd-0e74abbeeb91.png)
![gsdx_20181003221655](https://user-images.githubusercontent.com/6324883/46450456-4fd54e80-c75f-11e8-9f7d-40928697b234.png)

v1.5.0-dev-2574-g629d2bd42:
![gsdx_20181003221827](https://user-images.githubusercontent.com/6324883/46450455-4fd54e80-c75f-11e8-9e34-6ed2e8455a9a.png)
![gsdx_20181003221835](https://user-images.githubusercontent.com/6324883/46450454-4f3cb800-c75f-11e8-9967-fdb5bbb89d43.png)

**Comment by lightningterror** [comment] 2018-10-04 03:04
Can you upload a GS dump of the issue ?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by Bezier89** [comment] 2018-10-04 03:17
Done: [gsdx.zip](https://github.com/PCSX2/pcsx2/files/2444776/gsdx.zip)

**Comment by lightningterror** [comment] 2018-10-04 13:32
Me and KrossX aren't able to reproduce the issue, are you sure it's a regression and not some setting causing it ?

**Comment by Bezier89** [comment] 2018-10-04 14:20
Definitely a regression - I did a binary search to find the exact version where it started happening. All testing was done without changing any settings, i.e. I unzipped pcsx2,  copied the bios, started pcsx2, and booted the game.

Perhaps it only happens with Nvidia cards, or with particular graphics drivers? Is there any additional information I could post that would help? I'm currently using Nvidia GeForce Drivers v399.07.

**Comment by KrossX** [comment] 2018-10-04 15:09
Can you try this test files and see if the issue is fixed? [gsdx_test.zip](https://github.com/PCSX2/pcsx2/files/2446914/gsdx_test.zip)

**Comment by Bezier89** [comment] 2018-10-04 15:17
@KrossX Sure thing, but will have to wait until I get home :) Will update with results tonight.

**Comment by Silanda** [comment] 2018-10-04 15:51
FWIW, this is happening to me too using my current build (v1.5.0-dev-2584). Nvidia GTX1080 on driver version 411.70.

Both of those test plugins worked just fine for me.

**Comment by KrossX** [comment] 2018-10-04 16:02
Nice! One more then. [GSdx32-SSE2_test3.zip](https://github.com/PCSX2/pcsx2/files/2447103/GSdx32-SSE2_test3.zip)

**Comment by Silanda** [comment] 2018-10-04 18:13
That one looks good too.

**Comment by KrossX** [comment] 2018-10-04 18:32
Sweet! Thank you very much.

**Comment by lightningterror** [comment] 2018-10-04 19:02
Can you retest latest build both opengl and dx11 ?

**Comment by Silanda** [comment] 2018-10-04 20:08
Problem only appears to affect OpenGL. The last build posted seems to work in both while my original build works as expected in DX11 but not GL.

**Comment by lightningterror** [comment] 2018-10-04 20:11
Cool, then I'll close this since the latest build fixed the issue.

**Closed by lightningterror** 2018-10-04 20:11 UTC
Labels: High Priority, Plugin: GSdx, Regression

**Comment by Bezier89** [comment] 2018-10-05 00:19
Interestingly, replacing the plugin with any of the three test plugins doesn't fix the issue for me, but using v1.5.0-dev-2587 *does* fix the issue for me. Maybe there's some sort of caching of the plugin going on? Or I'm just doing something wrong. Regardless, it works in the latest build for me. Thanks @lightningterror @KrossX @Silanda

**Comment by lightningterror** [comment] 2018-10-05 00:29
You probably forgot to change the plugin from AVX2 to SSE2 since the 3 provided were SSE2 only compiled.

**Comment by Bezier89** [comment] 2018-10-05 00:57
That'll do it!
