### ISSUE TITLE
[Feature Request]: Simple Update 

### ISSUE THREAD

**Issue by CassiusOtho** [PCSX2/pcsx2#5420] opened 2022-01-28 21:25 UTC
### Description

It would be great if the development version had a one click update feature. RPCS3 has a great way of implementing this I have attached some videos below to better visualize how it looks like on the front end to provide some inspiration.

RPCS3 does this two ways. The first video shows the update feature on the home screen in the upper right corner. This is the quickest method because after “Update Available!” is clicked, the “Download Update” option opens us. Clicking on this opens the “Update Available” window which lists the current version, latest version, the version age. It gives the user the option to update, not update, and to show details of the changelog.

[https://streamable.com/qtqb7o](url)

The second way also starts off from the home screen, but it uses the middle left corner of toolbar by clicking the “Help” option. This method takes a bit longer. Next the “Check for Updates” is selected and then the process is similar to the aforementioned example. 

[https://streamable.com/fjb5mg](url)

### Reason

- How will it make things easier for you?
This would make it much easier for us to update to the latest version. There wouldn't be a need for us to go to the github page, manually download the latest build, go to the proper directory containing all the pcsx2 files that need to be updated, and lastly  paste and override the old files. This would save us a lot of time especially for the developer build which is receiving updates regularly. This would also be a great way to keep people engagement of people just starting in emulation. 

- How does this feature help your enjoyment of the emulator?
It helps us save a lot of time! Which means that it gives us more time to play games! 

- What does it provide that isn't being provided currently?
A fast, easy, and user friendly way to update to the latest build. 

### Examples

Examples provided above under the "Description" section.

**Comment by RedDevilus** [comment] 2022-01-28 21:27
Duplicate of https://github.com/PCSX2/pcsx2/issues/3054

**Closed by RedDevilus** 2022-01-28 21:27 UTC
Labels: Enhancement / Feature Request

**Comment by CassiusOtho** [comment] 2022-01-28 21:31
@RedDevilus Thank you for the response. I will go ahead and delete the feature request.

**Comment by CassiusOtho** [comment] 2022-01-28 21:36
@RedDevilus Sorry, I thought I was able to delete the feature request myself. Would it be possible for an admin to delete this post?

**Comment by F0bes** [comment] 2022-01-28 21:36
It's already closed. You're all good. :)
