### ISSUE TITLE
[Feature Request]: i.LINK support

### ISSUE THREAD

**Issue by Sal89** [PCSX2/pcsx2#11515] opened 2024-07-07 19:48 UTC
### Description

i.LINK support for Gran Turismo games (Gran Turismo 3: A-Spec, Gran Turismo Concept and Gran Turismo 4) would be nice. A demo build of Gran Turismo Concept is forced to be played such way

### Reason

Some days ago, a new demo build of Gran Turismo Concept was made public. This demo is the Subaru Driving Simulator. The problem is that i.LINK ismandatory for play it. Will be the [i.LINK] stuff implemented sooner or later? Other builds have the same issue (including Gran Turismo 3: A-Spec), since the feature isn't here, but since is "useless" in these isn't a problem. The issue is that under "Machine ID" will be never displayed a number in order to start a race

### Examples

![image](https://github.com/PCSX2/pcsx2/assets/108551020/7e23ea4e-9b29-4172-ae57-6e531e938bdb)

**Comment by Mrlinkwii** [comment] 2024-07-07 19:49
duplicate of #4472

**Closed** 2024-07-07 19:49 UTC
Labels: Enhancement / Feature Request
