### ISSUE TITLE
The inis folder in 1.4.0 is called inis_1.4.0

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#1090] opened 2016-01-08 15:47 UTC
I don't think this is expected behavior because v1.3.1-1620-g165d286(which is actually the same rev)still uses inis

**Comment by willkuer** [comment] 2016-01-08 16:00
Expected vs intended. Unexpected by users intended by devs.

**Comment by vsub** [comment] 2016-01-08 16:08
And why exactly if the git version is using inis instead of inis_1.4.0

**Comment by willkuer** [comment] 2016-01-08 17:28
I dont know. I just know that there was some consideration about ini backward and forward compatibility and i think the result of the consideration was something like there wont be automatic ini compatibility as long as there is no setting management system. 

I never had issues with old inis but there was some issue that seems to occur.

**Comment by bositman** [comment] 2016-01-09 17:05
We had bad conflicts with existing inis and since we didn't have time to create a system to import and downgrade ini settings, we hackfixed it like this :P

**Comment by willkuer** [comment] 2016-01-09 17:20
What are actually the problems? I only heard there are problems but neither on github nor in the forum i ever saw explicitely which settings has this issue.

**Comment by TheStruggleForAntiSpaghetti** [comment] 2016-01-25 12:00
Understood.
Can I ask what the policy for :1.4.0 versions is? Because of the Launchers/Utilities interacting with the \inis folder.

**Comment by RebelliousX** [comment] 2016-02-02 01:37
Each ini file should have a header with its own version number, if that number mismatched with the current one, user have to reconfigure. This is how I do it in TwinPad. Or implement an import function of previous versions configurations.

**Comment by ssakash** [comment] 2016-04-28 06:11
Closing this issue since the renaming of inis folder was only intended for the stable version to prevent some bad conflicts.

**Closed by ssakash** 2016-04-28 06:11 UTC
Labels: Question

**Comment by avih** [comment] 2016-04-28 22:11
Can someone please summarize this subject? specifically: Is it still relevant? In development builds? in release builds?

If it's still relevant:
- What problems does it solve (specifically)?
- What are the alternatives? someone mentioned version at the ini file, which sounds like a good idea to me. Any issues with this approach?

**Comment by TheStruggleForAntiSpaghetti** [comment] 2016-04-29 03:56
While closing, why wasn't at least specified what is going to happen with this? Is it also going to appear in a future/the next stable release? Then I can at least anticipate on it in the code with the next release of my app.

TIA

**Comment by ssakash** [comment] 2016-04-29 04:36
> Can someone please summarize this subject? specifically: Is it still relevant? In development builds? in release builds?

The issue is that people were confused on why the ``inis`` folder had been renamed on the latest stable version. (Since this has never happened before on any older stable versions)

This lead to problems for front-end developers who rely on the exact name of the folder for fetching the value from the INI files. 

> If it's still relevant:
- What problems does it solve (specifically)?
- What are the alternatives? someone mentioned version at the ini file, which sounds like a good idea to me. Any issues with this approach?

Problem is not relevant anymore as it only influences the 1.4 stable build. Versioning the INI file seems like a good idea which could avoid hacks like these in the next stable version. (But not relevant to the following issue, as this issue was made on intent to know whether it was intentional to only rename the ``inis`` folder on 1.4 stable version and not on development builds)

> While closing, why wasn't at least specified what is going to happen with this? Is it also going to appear in a future/the next stable release? Then I can at least anticipate on it in the code with the next release of my app.

Probably because there are no plans yet on how to handle this on the next stable version. Please open a separate issue if you want to discuss about it, thanks.

**Comment by avih** [comment] 2016-04-29 08:46
Thanks. Right, so I also checked it, and indeed right now it only create and uses `inis` (and not `inis_1.4.0`) - both in my own DEVEL build and also from the buildbot.

So I'll guess unless we decide to use the same trick again with the next release, the next release will keep using `inis`.

Also, while it's great that whoever uses development builds can use an "unversioned" ini folder, TBH, it might be OK that different release versions use specific ini folder with the release name. Not 100% sure about it though.
