### ISSUE TITLE
Emulation window title doesn't get updated when in fullscreen

### ISSUE THREAD

**Issue by mirh** [PCSX2/pcsx2#2002] opened 2017-07-05 12:29 UTC
The one with FPS, gs utilization and all. 
They always keep the same until you get back to windowed.

**Comment by ssakash** [comment] 2017-07-05 12:54
I don't think I reproduced this issue before, I probably caused this one on my recent update to deal with the SMODE2 delay. (Maybe?)

I'll look into this after I reach home.

**Comment by ssakash** [comment] 2017-07-05 13:08
Some good news: I wasn't the one who caused this issue! 😌

**Comment by ssakash** [comment] 2017-07-05 13:11
Though I've managed to find the source of the issue. If my deduction is correct, the regression was caused by Flatout's PR : https://github.com/PCSX2/pcsx2/pull/1737 and it seems to be [turtleli's idea](https://github.com/PCSX2/pcsx2/pull/1737/commits/a3ad5445d528671b916e4b27cb133f0265b25f43#r94878687), though I personally disagree with turtleli. The overhead on updating the title while in fullscreen is close to nothing.

**Comment by lightningterror** [comment] 2017-07-05 13:15
It's not really a regression then.

> The overhead on updating the title while in fullscreen is close to nothing.

I'd agree with that or just remove the title while in fullscreen.

**Comment by ssakash** [comment] 2017-07-05 13:18
@mirh 

You're fine with turtleli's decision (or) do you insist on changing back to the older behavior?

> It's not really a regression then.

How is it not a regression? The title bar was still being updated on full screen mode at the builds prior to #1737.

> just remove the title while in fullscreen.

Isn't that what normally happens? You can't see the title while you're in full screen.

**Comment by mirh** [comment] 2017-07-05 13:24
I was also thinking to that tbh
And I mean, I just spotted this in a pretty lazy "why should I open fraps when I can quickly check FPS in task manager" mood. 

And.. both scales are almost as insignificant as possible. 
Though I was thinking that, should I use some keyboard shortcut to change anything title-relevant (say, frame limiting) then the frozen title would even state the wrong.

**Comment by Hirato** [comment] 2017-07-05 13:59
Please don't fix this; I can't get OBS to attach to a window whose title doesn't remain static. :(

**Comment by ssakash** [comment] 2017-07-05 14:02
I'm impressed that I came back on right time. 😱 

![time](https://snag.gy/uNWdoj.jpg)

Either way to summarize the issue,

* Turtleli's opinion: Most people won't notice the frozen fps state which would be updated in a second after returning to windowed mode and hence save some overhead by disabling the title update on full screen.

* However, people with hawk eyes like @mirh notice the delay and are a bit annoyed with it and there isn't really anything costly on setting the title at full screen mode, actually this was the windows behavior for all these time before Flatout's PR.

Though personally I don't mind either turtleli's suggestion or mirh's suggestion, it's not really much of an issue for me.

**Comment by ssakash** [comment] 2017-07-05 14:05
> Please don't fix this; I can't get OBS to attach to a window whose title doesn't remain static. :(

That's a rather valid reason. I presume OBS doesn't work on 1.4 stable version?

**Comment by ssakash** [comment] 2017-07-05 14:12
Actually, let's just close this issue. I think people can deal with a 1 second lag on updating the title when we return to windowed mode, it's really not a concern when comparing it with potential problems which might arise when linking with other programs which require a static title. (Like the one mentioned by @Hirato)

@mirh 
If you're not satisfied with the reasoning, feel free to reopen the issue.

**Comment by ssakash** [comment] 2017-07-05 14:15
Thinking again, I'd prefer to get [confirmation](https://github.com/PCSX2/pcsx2/issues/2002#issuecomment-313112876) from @Hirato before closing the issue. (It would be a shame to close this if OBS/_whatever_ doesn't actually rely on a static title :P)

**Comment by lightningterror** [comment] 2017-07-05 14:22
Hmm I did record with obs + quick sync but that was on the older version not the studio. I haven't tested that one. I can test it in about 2 weeks when I'm back home xD

**Comment by Hirato** [comment] 2017-07-05 14:25
I can't say, I always used Linux and I've been building from git every time I wanted to run PCSX2 (even back when you were SVN based on googlecode) :P

The fact of the matter is when the window is fullscreen (and the title not updating) I can record the window via OBS, if its window ed(and the title updates) it just immediately focuses the console window instead of the game window.
I can use screen capture instead as a workaround but it has all kinds of little graphical glitches and pacing issues.

**Comment by AlessandroVetere** [comment] 2017-07-05 14:33
Maybe best solution would be to add an option to make window title static (both windowed and fullscreen) while by default the title is dynamic (both windowed and fullscreen), as the overhead is close to null.

**Comment by willkuer** [comment] 2017-07-05 14:56
I think you can do that. You can adjust the title bar template in the ini file. Then you can delete everything non-static.

**Comment by mirh** [comment] 2017-07-05 15:00
> Please don't fix this; I can't get OBS to attach to a window whose title doesn't remain static. :(

That's totally an issue that should be fixed on OBS end then. 
I don't know what they do to hook window, but it would be 200% dumb to rely on window title. 

> Maybe best solution would be to add an option to make window title static

It doesn't _really_ seem anything 99.9% of people would care. 

> I think you can do that. You can adjust the title bar template in the ini file. Then you can delete everything non-static.

^^

**Comment by AlessandroVetere** [comment] 2017-07-05 15:32
So if @Hirato (and anyone who needs such behaviour) can change on his side the ini file to obtain static title, the default should be that the title is always dynamic IMHO.

**Comment by Hirato** [comment] 2017-07-05 16:35
So I did two quick experiments.

Experiment 1: `TitleTemplate=Slot: ${slot} | Speed${limiter}: ${omodef}-${omodei} | ${gsdx}`
OBS was able to follow the game window just fine even if the data changed.
It however lost the handle upon toggling fullscreen.

Experiment 2: `TitleTemplate=Slot: ${slot} | Speed${limiter}: ${speed} ${omodef}-${omodei} | ${gsdx}`
OBS was able to follow the game window once it got a handle on it, but if even one character mismatched in the title it couldn't get said handle in the first place.
It was a bit more temperamental, it didn't always lose the handle, but it often did if I (un)maximised the window or moved it partly offscreen; resizing the window pretty much always made it lose it.

I suspect a lot of those standard window operations results in the window effectively being destroyed and recreated internally, and that the last known title is merely being used by OBS to try and find the window once the handle has been lost.
The title updates destroying the window would explain the weird flickering I see in the recordings if I capture PCSX2 via the screen capture method.



OBS seems to be able to track Firefox's windows just fine if I switch tabs (which changes the title), but it cannot track PCSX2's game window if it's even one character out (eg, use the first TitleTemplate above and change SaveState slot while configuring an xcomposite capture (or the window equivalent?))
So I honestly don't know if it's a OBS issue (since firefox works fine), a wxwidgets issue, or a PCSX2's usage of wxwidgets issue.

**Comment by mirh** [comment] 2017-07-05 18:04
You can use [this tool](https://www.nirsoft.net/utils/gui_prop_view.html) to track window handle, process/thread ID. 
I can hardly understand why you'd suppose window is being recreated over and over again. 

You should report to them this.

**Comment by Hirato** [comment] 2017-07-06 11:33
As I mentioned previously, I'm on Linux.
I don't know what the proper tool to use there would be, I presume xprop? The closest thing to what looks like the Window ID in the output is `_NET_WM_USER_TIME_WINDOW(WINDOW)`

The window being destroyed is an implementation detail that the desktop environment itself tries to make transparent with varying degrees of success.
For example on Windows, changing various window properties do result in the window being destroyed and recreated - eg anything that indirectly ends up calling CreateWindowEx. I'll concede that I jumped to conclusions over what may trigger such a call.
You generally don't notice unless for example you're a .NET developer and happen to be relying on `Application.OpenForms` to be correct...

I also don't really know what Linux (or more specifically Xorg/X11) does in this regard.
But anyways, I'll stop stinking up this ticket for now. :)

**Comment by mirh** [comment] 2017-07-06 11:52
> I don't know what the proper tool to use there would be, I presume xprop?

Oh, sorry. I had confused you with the other guy which is on linux, but still talks about windows problems (which indeed I was reporting). 
You are instead talking of OBS on linux (which I never really had thought of, lol) and pcsx2 on linux. 

In this case I'm not all that sure about my non-assumptions anymore, but still (be it a x.org/obs/wm bug) it doesn't seem something on our side.

**Closed** 2017-07-12 20:07 UTC
Labels: GUI/WX, OS: Windows, Regression
