### ISSUE TITLE
[GSdx] Weird major slowdowns from certain effects with DX11

### ISSUE THREAD

**Issue by AltimorTASDK** [PCSX2/pcsx2#602] opened 2015-06-12 10:00 UTC
SMT Nocturne, DDS, and DDS2: Almost every battle effect. Off the top of my head: Focus, Berserk, Gaea Rage, Bullet-Time and Showtime skills.
Persona 3 and 4: Any enemies with iridescent shaders, like Emperor Beetles

Tested with an i7 965 and an Nvidia GTX 660 Ti. Reverting to DX9 seems to fix it completely, but doesn't allow MSAA without lowering the z buffer bit depth. If anyone wants to try to tackle it I can provide save states where the issues happen.

**Comment by refractionpcsx2** [comment] 2015-06-12 10:56
Which branch are you using? is it the latest git for that branch?  Need a bit more details please.

**Comment by vsub** [comment] 2015-06-12 17:03
Hmm,yes...I'm using the latest beta(default settings)and I'm fighting against 3 Emperor Beetles and 1 Primitive Idol(Persona 4)

The speed is ~130fps and if I use 2xMSAA,the speed will go down to 30 and even less.
And if I use 4xMSAA,pcsx2 is either running at less than 1fps of it just freezes.

Kill all the enemys except one:
Emperor Beetle - No MSAA 207fps / 2xMSAA 60fps
Primitive Idol - No MSAA 207fps / 2xMSAA 207fps

In OGL mode the speed a barely affected(130=>110)...not like in DX9/11 mode but the speed without msaa is little lower than DX11

i7 4771 and GTX750TI

**Comment by refractionpcsx2** [comment] 2015-06-12 22:56
So is it fine until you put MSAA on?

**Comment by vsub** [comment] 2015-06-12 23:55
Seems that way but it doesn't apply only to those enemys

**Comment by refractionpcsx2** [comment] 2015-06-13 00:02
I don't care about the enemies, I just want to know what settings cause the slowdown

**Comment by vsub** [comment] 2015-06-13 00:29
The MSAA....huge speed drop if it's used but the speed goes down only if certain conditions are met(fighting against certain enemys or looking at certain effects)

And when I tried it again the difference between 2x and 4x is 7fps less,between 4x and 8x is ~10fps less and between 8x and 16x,there is no difference.
The EE and GS are below 30%

**Comment by ssakash** [comment] 2015-06-13 01:36
At which build was this problem started ?

**Comment by AltimorTASDK** [comment] 2015-06-13 01:37
http://forums.pcsx2.net/Thread-Persona-3-And-4-Certain-enemies-groups-slow-down-game

The Persona bug has been around since at least 2011. I don't know if the Nocturne engine bug is separate.

**Comment by gregory38** [comment] 2015-06-13 06:30
OpenGL doesn't support MSAA.

**Comment by Bigpet** [comment] 2015-06-13 06:45
@gregory38 you should probably clarify with "the GSdx OpenGL render doesn't support MSAA"

**Comment by gregory38** [comment] 2015-06-13 07:01
Yes. So I decide to not implement MSAA support in the the GSdx OpenGL render.

**Comment by gregory38** [comment] 2015-07-20 13:35
I think the issue is that games that read back the target to use it as an input texture.
No MSAA:
1/ fast case: a raw copy
2/ slow case: a downscaling copy

With MSAA, you add a new step because you need to downsample the target. I don't know the speed impact but if you need to do 10/100 times by frame, overhead will become important. Besides I suspect an increases of memory requirements (due to extra target).

Except if it is a regression, I think we can close this bug report as it is likely a normal behavior. Do you agree.

**Comment by AltimorTASDK** [comment] 2015-07-20 21:50
That makes sense, maybe Nocturne is using it for additive rendering? If that is the case then yeah, this isn't really a bug.

**Comment by gregory38** [comment] 2015-07-21 07:08
Games also read the RT for effect based on depth such as depth of field (it is a bit more complicated than to directly read the depth).

**Closed by gregory38** 2015-07-21 07:08 UTC
