### ISSUE TITLE
[Feature Request]: Enable mouse mapping hotkey

### ISSUE THREAD

**Issue by ElTioRata** [PCSX2/pcsx2#11272] opened 2024-05-20 00:35 UTC
### Description

Add an option in the controller setting that can allow the user to bind a button to enable mouse mapping when he needs it.

### Reason

Some games uses the left stick for both player movement and aiming (e.g. Metal Gear Solid), therefore the mouse and keyboard user will bind the left stick axis to WASD and the mouse axis, can result in weird involuntary input from the player when he tries to transition from using the mouse to using WASD like accidentally moving the character with the mouse after the player left the aiming mode. A solution to this problem could be letting the user enable mouse mapping by holding a hotkey when he needs it (e.g. hotkey is bound to right mouse button, such button is also bound to the aiming button in the game, so the mouse mapping will only be disabled when the right mouse button is released or pressed again).

Related feature request: #7325 

### Examples

To my knowledge, there isn't any emulator that implemented this.

**Comment by JordanTheToaster** [comment] 2024-05-20 00:50
Duplicate of #7118

**Comment by stenzek** [comment] 2024-05-20 02:27
Duplicate of https://github.com/PCSX2/pcsx2/issues/7118

**Closed by stenzek** 2024-05-20 02:27 UTC
Labels: Enhancement / Feature Request

**Comment by ElTioRata** [comment] 2024-05-20 02:57
Yikes. I forgot about it.
