### ISSUE TITLE
[BUG]: Super Shanghai 2005 (Japan) [SLPM-62552] [CRC32-0e24a958]

### ISSUE THREAD

**Issue by spacemul** [PCSX2/pcsx2#5122] opened 2021-12-08 15:55 UTC
### Describe the Bug

Black screen after Starfish logo

### Reproduction Steps

Just launch the game

### PCSX2 Revision

1.7.2103

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 3600

### GPU

RTX 3070

**Comment by HeroponRikiBestest** [comment] 2021-12-09 21:13
Logs: [emuLog.txt](https://github.com/PCSX2/pcsx2/files/7688466/emuLog.txt)
Suffers from a lot of TLB misses. 
Its status is playable in the gamedb, so there may have been a regression somewhere.

**Comment by HeroponRikiBestest** [comment] 2021-12-09 22:11
Where is that code? 
Regardless, I see it marked as playable because of https://forums.pcsx2.net/Thread-Super-Shanghai-2005-SLPM-62552-J--29329. I tried this pnach on the pcsx2 version specified (0.9.8) but it didn't work, although the crc they specificed for the elf was different, so I had to change the filename for it to work. There don't appear to be any other known releases of this game, so maybe they were using a modified dump. Regardless, the screenshots they included show it using zerogs 0.9.5, which as far as I know wasn't one of the default PCSX2 plugins at that release, so they could have been using different plugins.

**Comment by refractionpcsx2** [comment] 2021-12-09 22:13
https://github.com/PCSX2/pcsx2/blob/master/pcsx2/CDVD/CDVD.cpp#L62
Change line 62 and 75 to eCycle = 3000; 

and here https://github.com/PCSX2/pcsx2/blob/master/pcsx2/CDVD/CDVD.cpp#L1307
1307 and 1312 change to seektime = cdvd.ReadTime + ((cdvd.BlockSize / 4) * 12);

Then the game will work (with the Fast CDVD speedhack)

**Comment by gilderoylockhart01** [comment] 2021-12-10 17:46
Everything which worked in 0.98 but not after is to take with a grain of slat because the DMAs were instant during that time period.

Does this game goes further with a much slower EE?

**Comment by HeroponRikiBestest** [comment] 2021-12-10 18:13
Nope, it outright crashes.
Log: [output.txt.zip](https://github.com/PCSX2/pcsx2/files/7694651/output.txt.zip)
Backtrace from core dump: [backtrace.txt](https://github.com/PCSX2/pcsx2/files/7694654/backtrace.txt)

**Comment by refractionpcsx2** [comment] 2021-12-10 19:54
No the game does not work on Dobiestation but apparently does on Play (probably because of things being instant)
No there isn't anything you can do
Yes I can see where it's breaking on CDVD
No I don't know how to fix it right now.

I think that covers everything.

**Comment by gilderoylockhart01** [comment] 2021-12-12 09:54
Haha, sorry if you felt I was rude with this. That's typically one situation where having the DMA instant option as a gamefix would make things easier to test.

That said, a blockdump of the game would be nice to have if you have one please.

**Comment by refractionpcsx2** [comment] 2021-12-12 12:29
[Super Shanghai 2005 [SLPM 62552] (J) (2021-11-12 12-27-51).zip](https://github.com/PCSX2/pcsx2/files/7698711/Super.Shanghai.2005.SLPM.62552.J.2021-11-12.12-27-51.zip)

Sure, here you go. The problem isn't when the TLB misses happen, it's near the beginning of loading, a bunch of files fail to open (I guess it decided they took too long, even though it had to seek across the disc??)

**Comment by spacemul** [comment] 2021-12-12 12:50
like that ?

[Super Shanghai 2005 (Japan) [SLPM-62552] [CRC32-0e24a958] (2021-11-12 13-49-28).zip](https://github.com/PCSX2/pcsx2/files/7698749/Super.Shanghai.2005.Japan.SLPM-62552.CRC32-0e24a958.2021-11-12.13-49-28.zip)

**Comment by gilderoylockhart01** [comment] 2021-12-12 16:43
Yeah that's fine thanks. From what I can see, only delay VIF1 stalls does something, it doesn't tlb miss and takes less time to read that "audio?" file.

**Comment by refractionpcsx2** [comment] 2021-12-27 05:09
Okay so the game does a CD Read command and a CDVD reset in quick succession and causes collision issues, wiping out the TOC and failing the read.  Kind of a similar issue to Ecco the Dolphin.

kr_ps2 has made a patch for this and will be added shortly.

**Closed** 2021-12-27 18:02 UTC
Labels: Bug, CDVD
