### ISSUE TITLE
[BUG]: Spongebob Games don't see saves after a restart when using a folder memory card

### ISSUE THREAD

**Issue by piplup55** [PCSX2/pcsx2#6708] opened 2022-07-25 01:06 UTC
### Describe the Bug

the game doesn't see the save in the load screen (might afflict more spongebob games)
![image](https://user-images.githubusercontent.com/100526773/180674014-a797eb74-a9a7-468e-bf9f-b7ae208459df.png)

### Reproduction Steps

1. create a new save
2. close the game
3. reopen the game goto the loading screen

### Expected Behavior

the game should see the save files
![image](https://user-images.githubusercontent.com/100526773/180674384-3516e289-6bfc-4447-a5ee-a1bf94b8f916.png)

### PCSX2 Revision

v1.7.3115

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Arch Linux

### CPU

Ryzen 7 3700X

### GPU

RX 6600 XT

### Emulation Settings

Internal Resolution: 4x

**Comment by bositman** [comment] 2022-07-25 21:52
Did this always happen? Did you try the last stable release (1.6) to cross check?

**Comment by piplup55** [comment] 2022-07-26 00:47
it doesn't happen on 1.6 i just tested it and it's fine 
![image](https://user-images.githubusercontent.com/100526773/180898842-10b28831-bdde-4c0b-ab6b-63f7962901ca.png)

**Comment by Mrlinkwii** [comment] 2022-09-15 11:48
are you using a file memcard ? a folder memcard?

**Comment by piplup55** [comment] 2022-09-19 14:57
> are you using a file memcard ? a folder memcard?

i was using a folder memory card but it was also happening with the normal 8mb card, doesn't seem to happen with the 8mb card anymore (at the time of reporting this bug it was happening on the 8mb card) still happens with the folder

sorry for the late reply i been away

**Comment by Mrlinkwii** [comment] 2022-11-19 22:27
@piplup55  can you check latest nighty ?

**Comment by piplup55** [comment] 2022-11-20 10:23
> @piplup55 can you check latest nighty ?

tested with the same results

**Comment by TheTechnician27** [comment] 2024-02-06 22:36
Hey, Piplup, I was wondering which version you're playing. This works for me with a folder memcard on NTSC-U, but perhaps it could be a regional thing?

**Comment by refractionpcsx2** [comment] 2024-02-06 22:37
Keep in mind a bunch of memcard stuff has changed since November 2022

**Comment by TheTechnician27** [comment] 2024-02-06 23:44
> Keep in mind a bunch of memcard stuff has changed since November 2022

Well in that case, we might just have a closed issue on our hands if Piplup can't reproduce it on the latest nightly. Nice.

**Comment by piplup55** [comment] 2024-02-07 15:28
adding on to what @kamfretoz said, i've learned it's only a restart of the emulator that makes the saves disappear, if you exit to the main menu in game the saves will still show

**Comment by kamfretoz** [comment] 2024-02-07 15:32
just double checking here, can you test with both file memcard and folder memcard too? for me its only broken when using folder memcard

**Comment by piplup55** [comment] 2024-02-07 16:28
> just double checking here, can you test with both file memcard and folder memcard too? for me its only broken when using folder memcard

yeah it's only folder memory card now that has this issue now, updating the title to make it more clear

**Comment by refractionpcsx2** [comment] 2024-02-07 19:18
That's interesting, it almost sounds like it's not reloading the folder index correctly..

**Comment by TheTechnician27** [comment] 2024-02-07 19:32
> That's interesting, it almost sounds like it's not reloading the folder index correctly..

As best I can tell from the emulog window (I still can't get it to save to the .txt file for some reason), the first time I boot the game, it reads:

[  749.4892] McdSlot 0: [Folder] /home/myname/.var/app/net.pcsx2.PCSX2/config/PCSX2/memcards/SpongeBob.ps2
[  749.4893] (FolderMcd) Indexing slot 0 with filter "SLUS-20904".
[  749.4893] HLE Host: Set 'host:' root path to: /run/user/1000/doc/9ac657a6/PlayStation 2/SpongeBob/Movie

I do various stuff, and from there, I shutdown and reopen, which reads:

[  978.6501] McdSlot 0: [Folder] /home/myname/.var/app/net.pcsx2.PCSX2/config/PCSX2/memcards/SpongeBob.ps2
[  978.6502] (FolderMcd) Indexing slot 0 with filter "SLUS-20904".
[  978.6503] HLE Host: Set 'host:' root path to: /run/user/1000/doc/9ac657a6/PlayStation 2/SpongeBob/Movie

So at the very least, it seems like it's performing the indexing correctly. However, one idea I have to test this is to have two sessions of the game open at the same time and see if closing out of one of them screws up the save file for the other concurrent session.

**Comment by refractionpcsx2** [comment] 2024-02-07 19:34
yeah but what does the index file look like? it's one thing for it to load it, it's another to contain all the files inside it :P

**Comment by TheTechnician27** [comment] 2024-02-07 19:38
I can send over a copy of the memcard if you'd like. I opened Session 1 of the test and created a new save file, then when I opened Session 2, it couldn't read the save file. So I think that rules out this somehow being caused by the shutdown itself.

[SpongeBob.ps2.zip](https://github.com/PCSX2/pcsx2/files/14200711/SpongeBob.ps2.zip)

This is the memcard as it is mid-play session.

**Comment by refractionpcsx2** [comment] 2024-02-07 19:41
do you have a normal memcard save too? for comparison

**Comment by TheTechnician27** [comment] 2024-02-07 19:42
Let me grab one for you real quick.

But ref, I just performed another test, and I don't think you're going to like what I have to say.

**Comment by TheTechnician27** [comment] 2024-02-07 20:22
Okay, so I've tested a few games:

* It's consistently reproducible in Movie (from here I won't be attempting this multiple times; the rest of these tests assume no issues with reproducibility).
* It's reproducible in BfBb.
* It doesn't work in Revenge of the Flying Dutchman (both Nick games but with this one developed by Blue Sky instead of Heavy Iron).
* It doesn't work in Scooby (published by WB and THQ and made by Heavy Iron).
* Doesn't work in Nicktoons Unite!
* It doesn't work in Atlantis SquarePantis (Nick/THQ + Blitz Games).

So unless Piplup has seen it in other games, I think this is isolated to BfBB and Movie, which are to each other what OoT and Majora's Mask are to each other: sister games in basically the same engine.

**Comment by piplup55** [comment] 2024-02-08 01:03
> Okay, so I've tested a few games:
> 
>     * It's consistently reproducible in Movie (from here I won't be attempting this multiple times; the rest of these tests assume no issues with reproducibility).
> 
>     * It's reproducible in BfBb.
> 
>     * It doesn't work in Revenge of the Flying Dutchman (both Nick games but with this one developed by Blue Sky instead of Heavy Iron).
> 
>     * It doesn't work in Scooby (published by WB and THQ and made by Heavy Iron).
> 
>     * Doesn't work in Nicktoons Unite!
> 
>     * It doesn't work in Atlantis SquarePantis (Nick/THQ + Blitz Games).
> 
> 
> So unless Piplup has seen it in other games, I think this is isolated to BfBB and Movie, which are to each other what OoT and Majora's Mask are to each other: sister games in basically the same engine.

i only have bfbb and the movie game so i can only confirm it for those two games, i might have a copy of atlantis squarepantis around somewhere if i find it i will edit this comment

**Closed** 2024-02-12 13:51 UTC
Labels: Bug, Memory Card
