### ISSUE TITLE
[Bug]: .gz compressed ISO reading broken

### ISSUE THREAD

**Issue by PixelCrusader** [PCSX2/pcsx2#5162] opened 2021-12-14 23:41 UTC
### Describe the Bug

As of version v1.7.2117, attempting to launch a game in Iso.gz format will send the user to the PS2's UI, as if there were no disc in the drive at all.  The games load fine with v1.7.2116. The problem persists as of v1.7.2133.

### Reproduction Steps

Attempt to boot a game compressed to Iso.gz format with 7-Zip.

### Expected Behavior

The game boots.

### PCSX2 Revision

v1.7.2133

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment] 2021-12-15 08:24
.gz games haven't worked since plugins were merged, since there's no plugin that supports it. I recommend converting your ISO's to using CSO or CHD formats.

**Comment by tellowkrinkle** [comment] 2021-12-15 08:47
> .gz games haven't worked since plugins were merged

I think you're thinking of bz2

We still seem to have a class for reading them, must have broken something https://github.com/PCSX2/pcsx2/blob/37ccd81985a16bb9790ba26cd3a54a9536b39a81/pcsx2/CDVD/GzippedFileReader.cpp

**Comment by refractionpcsx2** [comment] 2021-12-15 09:00
I didn't realise either of them worked. My bad.

**Comment by refractionpcsx2** [comment] 2021-12-15 09:38
Found the problem, fixed on master now, should be in the next dev build.

**Closed** 2021-12-15 09:38 UTC
Labels: Enhancement / Feature Request

**Comment by PixelCrusader** [comment] 2021-12-15 11:22
Cool. Thanks!

**Comment by avih** [comment] 2021-12-17 10:57
> Found the problem, fixed on master now, should be in the next dev build.

Still not fixed completely. While it does load the gz ISO, it doesn't load nor save the index file.

So this results in the gz ISO file getting indexed on every load or after pause.

Previously, the file would get indexed once, and saved to disk at the same dir as the ISO.gz file (by default).

As far as I can tell:
- v1.7.2116 is OK (loads gz ISO, creates/read the index).
- v1.7.2117 is broken - doesn't load gz ISO at all.
- After your the fix: loads the gz ISO but doesn't load/save the index, and re-index on every load (without saving to disk).

**Comment by refractionpcsx2** [comment] 2021-12-17 10:59
That's strange, I had an index file 🤔 

What OS are you on?

**Comment by avih** [comment] 2021-12-17 11:00
> What OS are you on?

Win 10 21H2.

**Comment by avih** [comment] 2021-12-17 11:14
> * After your the fix: loads the gz ISO but doesn't load/save the index

Correction: it does read the index if it exists, but it doesn't save it to disk if it's missing (apparently my 1st attempt was with an old/unsupported index file - which it didn't load).

With v1.7.2116:
```
This may take a while (but only once). Scanning compressed file to generate a quick access index...
50MB 100MB 150MB 200MB 250MB 300MB 350MB 400MB 450MB 500MB 550MB 600MB 650MB 700MB 
OK: Gzip quick access index file saved to disk: '<path-to-ISO.gz.pindex.tmp>'
isoFile open ok: '<path-to-ISO.gz>'
```

With v1.7.2137:
```
This may take a while (but only once). Scanning compressed file to generate a quick access index...
50MB 100MB 150MB 200MB 250MB 300MB 350MB 400MB 450MB 500MB 550MB 600MB 650MB 700MB 
isoFile open ok: '<path-to-ISO.gz>'
```

Note the missing line `OK: Gzip quick access index file saved to disk ..`.

**Comment by refractionpcsx2** [comment] 2021-12-17 11:21
Okay yeah I've reproduced, I'm investigating

**Comment by avih** [comment] 2021-12-17 11:35
> apparently my 1st attempt was with an old/unsupported index file - which it didn't load

OK, now I finally got it.

I tried both the 32it and 64bit versions of pcsx2, and the issue where the index file is not loaded due to "invalid size" is with the 64 version.

I'm guessing the saved data depends on integer sizes, and these differ between 32/64 versions of pcsx2.

This means, at least for now, that the gz index file is not currently compatible between 32/64 versions of PCSX2.

But anyway, regardless, the real issue is that the file is not saved. Let's ignore pcsx2 64 for now.

**Comment by refractionpcsx2** [comment] 2021-12-17 11:47
It was just because the routine for writing a new index file was trying to open the index for reading instead of writing.  It should be fixed on master now. I tested it and it creates a new index file and subsequent runs uses the existing index file.

**Comment by avih** [comment] 2021-12-17 11:51
Nice. Thanks.

I'll try it out once the CI build is ready.

**Comment by avih** [comment] 2021-12-17 12:02
> I'll try it out once the CI build is ready.

Confirmed looks ok (created, and loaded later).

**Comment by refractionpcsx2** [comment] 2021-12-17 12:05
Awesome :)
