### ISSUE TITLE
Onimusha 4 keeps spamming "libdma: sync timeout"

### ISSUE THREAD

**Issue by vsub** [PCSX2/pcsx2#2468] opened 2018-06-02 19:03 UTC
I tried the latest beta with default settings and some older 1.5 beta but it is the same.

It happens on almost all screens(title\pause\map\options...)
It is spamming that message so fast that it make the game to run at less than 10fps(from 90 with fps limiter off)
The only fix is to disable the EE logging from the console
It is also spamming
IPU Invalid Intra DC Precision, switching to 9 bits
and
IPU1 running when IPU1 DMA disabled! CHCR 5 QWC 233
 but the libdma is so fast that you can barely see those

From starting the game until the title screen and then closing pcsx2,pcsx2 saves a 15mb log file

**Comment by lightningterror** [comment] 2018-06-11 09:46
I'll close this in favor/duplicate of #2132

**Closed by lightningterror** 2018-06-11 09:46 UTC
Labels: Bug, IPU
