### ISSUE TITLE
Chinese BIOS does not work

### ISSUE THREAD

**Issue by Qwest8K** [PCSX2/pcsx2#3141] opened 2019-10-25 18:57 UTC
***PCSX2 version:*** v1.5.0-3309

***PCSX2 options:*** EE/IOP and VU default settings, disabled all speedhacks and fixes.

***Plugins used:*** Default plugins and settings, except LilyPad with disabled Xinput and DirectInput APIs, unplugged second controller and assigned on keyboard first controller (DualShock 2).

***Description of the issue:*** Black screen on trying to run BIOS of Chinese model PS2.

***How to reproduce the issue:*** Dump bios from one and only Chinese PS2 model SCPH-50009 and run it on emulator.

***Last known version to work:*** Unknown

***PC specifications:*** CPU - Intel Core i7-4790K @ 4.00GHz; GPU - Zotac GeForce GTX 980 4GB; OS - Windows 7 SP1 64 Bit.

**Comment by ssakash** [comment] 2019-10-25 18:58
Could you provide the content of your emulog while reproducing this issue?

**Comment by Qwest8K** [comment] 2019-10-25 19:04
Yes.
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/3773400/emuLog.txt)

**Comment by RedPanda4552** [comment] 2019-10-25 22:13
Was this a "No Disc" boot? If not, could you try that?

**Comment by Qwest8K** [comment] 2019-10-25 22:46
It was boot without disk.

**Comment by kozarovv** [comment] 2020-05-29 08:05
While i was looking on emulogs posted here (ziped one): https://forums.pcsx2.net/Thread-Ape-Escape-2-SCCS-40001-C?pid=609711#pid609711 
I noticed that bios can't load rom2:GB18030. 

I found that pcsx2 code, have possible issues: 
https://github.com/PCSX2/pcsx2/blob/2af05a92f8046a5e9151bf014a9e0a9a8375032b/pcsx2/MemoryTypes.h#L18
ROM sizes are hardcoded which seems to be wrong because according to google ROM1, and EROM can have different size than hardcoded ones. For SCPH-50009 and SCPH-70006 both additional roms seems to be 512kb, and erom 3mb. 

https://github.com/PCSX2/pcsx2/blob/2af05a92f8046a5e9151bf014a9e0a9a8375032b/pcsx2/Memory.cpp#L154
So this memory map will overwrite ROM1 (if full 512kb will be loaded). 

Emulog provided by user on forum have more info than one provided here. This bios can't work properly without ROM2, so loading only BIN file for sure not gonna work. 

`open name rom2:GB18030 flag 1 data 4a678
open fd = -6`

This is where bios fail for now when all files are provided. 
As far as i know this is loaded by rom0:ADDROM2
GB18030 file is probably FONT file for Chinese characters. 

Also maybe something is wrong here: 
https://github.com/PCSX2/pcsx2/blob/2af05a92f8046a5e9151bf014a9e0a9a8375032b/pcsx2/Memory.h#L84

All this seems to be unused, or maybe i just can't find where. 

That what i was able to find without having that PS2 model, and it's bios. Maybe that info will help somehow.

**Comment by Qwest8K** [comment] 2020-05-30 04:08
@kozarovv Sorry, but I do not see any log in the link that you showed.

**Comment by kozarovv** [comment] 2020-05-30 06:24
Post there was removed, and i didn't made copy. 

In log with boot bios, last line before restart was:  
`open name rom2:GB18030 flag 1 data 4a678 open fd = -6`

On log with game loading it was something about rom0:ADDROM2. 
Looks like rom2 isn't properly supported in PCSX2. Plus issues i mentioned above.

**Comment by Qwest8K** [comment] 2020-05-30 07:38
Well I have originals:
[emuLog of game launch trying.txt](https://github.com/PCSX2/pcsx2/files/4705265/emuLog.of.game.launch.trying.txt)
[emuLog of Chinese BIOS launch trying.zip](https://github.com/PCSX2/pcsx2/files/4705267/emuLog.of.Chinese.BIOS.launch.trying.zip)

**Comment by kozarovv** [comment] 2020-06-05 10:03
This version should fully support Chinese Bios, if someone is able to test, and post result, then i can create PR, or at least describe what is wrong. Full bios dump is required (.bin .rom1 .rom2).

[pcsx2.zip](https://github.com/PCSX2/pcsx2/files/4735286/pcsx2.zip)

**Comment by Qwest8K** [comment] 2020-06-05 19:08
@kozarovv I made tests as you asked me in PM in PCSX2 forum:
1) Emulator's build that you provided to me really nicely runs BIOS of SCPH-50009 with .BIN and both .ROM files. In hardware mode, there is a graphic artifact at the bottom of the screen:
![Graphic artifact at the bottom of the screen](https://user-images.githubusercontent.com/38340995/83911767-7f7afc00-a775-11ea-9391-6d4823ba53c6.png)
2) However, if try to boot any game through the Chinese BIOS by a full load, then this screen will appear: 
![gsdx_20200605203104](https://user-images.githubusercontent.com/38340995/83912821-2a3fea00-a777-11ea-8504-8a8e7b625dea.png)
3) And this is a log file of "Boot ISO (full)" through Chinese BIOS:
[emuLog if trying to run any game with Boot ISO (full).txt](https://github.com/PCSX2/pcsx2/files/4737926/emuLog.if.trying.to.run.any.game.with.Boot.ISO.full.txt)
4) But with fast ISO boot, games runs as they should. In particular - Chinese edition of Ape Escape 2 [SCCS 40001]:
![Main menu of Chinese Ape Escape in PCSX2](https://user-images.githubusercontent.com/38340995/83913483-2c567880-a778-11ea-9196-05092db33bc6.png)
5) I tested it only a little time and game work on "Playable" level. Hardware mode has a color issue: 
![Ape Escape 2 (China) hardware mode color issue](https://user-images.githubusercontent.com/38340995/83913929-ec43c580-a778-11ea-8c78-68370efdbc05.png)

**Comment by kozarovv** [comment] 2020-06-05 19:37
Thank you for testing. 

Full boot seems to be some different issue in pcsx2, not related to SCPH-50009 bios itself. 
Looks like every BIOS that have additional rom1 size grater than 256KB will fail to full boot on pcsx2. 
I tested that on my SCPH-50004 bios, and full boot also fail. I tried to fix that in few ways, including reserving more memory, but no luck for now.

**Comment by lightningterror** [comment] 2020-08-08 20:13
Fixed in #3439

**Closed by lightningterror** 2020-08-08 20:13 UTC

**Comment by seta-san** [comment] 2020-08-09 18:00
> Yes.
> [emuLog.txt](https://github.com/PCSX2/pcsx2/files/3773400/emuLog.txt)

@Qwest8K could you please write a compatibiltiy report for the chinese version of ape escape using the latest development build and the chinese bios? 
https://forums.pcsx2.net/Thread-Ape-Escape-2-SCCS-40001-C?pid=576504#pid576504

**Comment by Qwest8K** [comment] 2020-08-13 04:00
@seta-san 
Done: https://forums.pcsx2.net/Thread-Ape-Escape-2-SCCS-40001-C?pid=612135#pid612135

**Comment by ab310714gz4700** [comment] 2023-10-28 20:40
DTL-H50009 Debug Chinese BIOS does not work yet

**Comment by mirh** [comment] 2023-10-29 12:28
The problem there may be the debug part (#1549), not the region.

**Comment by AKuHAK** [comment] 2024-07-05 14:48
> I noticed that bios can't load rom2:GB18030.

Yes, `rom2:GB18030` was actually cropped in 512kb dumps of rom2.
