### ISSUE TITLE
Enabling Speedhack presets disables (grayed out) Vsync option

### ISSUE THREAD

**Issue by psennermann** [PCSX2/pcsx2#1642] opened 2016-10-30 11:59 UTC
**_PCSX2 version:**_
1.5.0-1498

**_Description of the issue:**_
`(What's the problem? - Screenshots showing the issue if applicable)`

Enabling the preset option (from 1 to 6) in the pcsx2 emulation/configuration options, grayes out the Vsync option (which is funny, since Vsync is not a speedhack), so the only way to enable Vsync in PCSX2 is to disable the speedhack preset.

**_How to reproduce the issue:**_
Enable the speedhack preset option, set it from 1 to 6 and see that the Vsync option is grayed out

**_Last known version to work:**_
I think Vsync has always been managed this way

**_PC specifications:**_
CPU: Intel Core 2 Duo E8600 GPU: GTX 950 OS: Windows 10 64 Bit

**Comment by FlatOutPS2** [comment] 2016-10-30 12:09
Preset is not just for speedhacks, it is a general emulation options preset and keeps unexperienced users from ruining their experience by enabling the wrong options. If you want to enable advanced features like vsync, which could cause emulation issues, you'll just have to disable the preset.

**Comment by trostboot** [comment] 2016-10-30 16:09
Care to elaborate on issues caused by vsync? It's been my experience that, if anything, leaving vsync off is what causes issues in newer Windows versions where vsync is always enforced through the DWM for non-exclusive applications like PCSX2, resulting in poor framepacing (although even that might just happen under certain conditions, I've never tried to figure it out in more detail once I've noticed enabling vsync in PCSX2 fixes it).

**Comment by jcdenton2k** [comment] 2016-10-31 21:13
Windows Desktop Composition (Desktop Windows Manager) is always on in Windows 8 and later:
https://msdn.microsoft.com/en-us/library/hh848042.aspx

The Display Driver Must Support Vsync-Control:
https://msdn.microsoft.com/en-us/library/ff569520(VS.85).aspx

DWM Info:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa969540(v=vs.85).aspx

On Windows 7 it can be disabled but enabling Vsync without Triple Buffering can increase input latency in certain scenarios.  Having both Vsync AND Triple Buffering mitigates this issue entirely BUT it requires significantly more RAM consumption (and specifically on-board GPU ram).

DWM doesn't give me any issues on Win7 x64 personally, but others have experienced issues depending on their setups.

More details on vsync + triple buffering in detail (article from 2009 but still relevant):
http://www.anandtech.com/show/2794/2

**Comment by avih** [comment] 2016-10-31 21:25
As @FlatOutPS2 said, we tried to carefully balance between presets which cannot be "broken" to options people would still like to modify while presets are enabled. We've modified this over the years, for instance initially MTVU was part of the presets (and turned off while presets are enabled), but once MTVU has proved stable enough to keep always on, we "freed" it from under presets control and now it can be modified also while presets are enabled.

We can reconsider to move some options to or out of the preset controls, but do keep in mind that you can choose a preset and then disable the presets checkbox - which would leave the settings exactly like the preset defined - only now without the preset enforcement.

Specifically for the vsync control, IIRC the main reason to disable it was that enabling vsync was reducing the framerates for systems which are not super fast. E.g. it's possible that your system could support consistent 60fps for some games without vsync enabled, but with vsync it would not reach consistent 60fps, and we wanted the preset to prevent this degradation.

FWIW, I still think that it's good that the presets disable vsync, but if enough people think it should not affect the vsync option, and good arguments are provided, we could change it. It's not set in stone.

**Comment by jcdenton2k** [comment] 2016-11-02 00:20
I'd say just leave it as-is while adding in the informative tooltip.
Presets should be designed for anyone who isn't technical enough to understand things in detail.

**Comment by trostboot** [comment] 2016-11-18 17:08
I've seen a couple of threads lately on the forum (latest being this one: http://forums.pcsx2.net/Thread-Soul-calibur-3-the-heavy-one ) where users encountered stuttering that was fixed by enabling vsync in PCSX2, which also mirrors my own experience at the very least since switching to Win10.

I would presume that as over time more and more Windows users will be on 10, this will become more of an issue. 
So if enabling vsync in PCSX2 can still cause drops in emulation performance (despite the Windows desktop enforcing vsync anyway), but disabling vsync in PCSX2 causes stuttering despite the emulation running at full speed, then there is a problem.

In my opinion, and looking at this from a Windows-only perspective since I don't know how it behaves in Linux, if presets continue to include vsync, then it should at least be enabled for the safer presets.

Perhaps the better, but more involved solution would be to look at what causes the stuttering in the first place.

An updated tooltip indicating the problems it can cause would be very helpful either way.

**Comment by psennermann** [comment] 2016-11-18 22:15
I'm also on Windows 10 and with every emulator that I've tried (from SNES to Wii), if I don't enable Vsync for non-exclusive fullscreen (like playing in a window), I always get some stuttering...that's the reason why I started this issue

**Comment by avih** [comment] 2016-11-18 22:35
> I'm also on Windows 10 and with every emulator that I've tried (from SNES to Wii), if I don't enable Vsync for non-exclusive fullscreen (like playing in a window), I always get some stuttering...that's the reason why I started this issue

That's all well and fine, and you could and can enable vsync in PCSX2. The question here is not whether or not vsync _may_ help, but rather whether we want to allow beginners who use presets to enable vsync and potentially hamper their overall emulation speed.

**Comment by trostboot** [comment] 2016-11-19 10:58
The flipside of that is, do you want to have beginners who use presets experience stuttering despite the emulation running at full speed?

I've tested a couple of games with framelimits off and vsync in PCSX2 on and off. I've seen no difference in emulation speed. Again, this is on Win10 with vsync forced on - the behaviour might be different on other platforms.
However, if we look at the Steam survey, Win8 and up (where this is relevant) are already at nearly 60% and growing.

If there is a split in how this affects platforms, then I would suggest dropping vsync entirely from the presets and instead updating the vsync tooltip taking into account the platform differences.

**Comment by gregory38** [comment] 2017-03-11 10:58
So what is the conclusion on this issue/question ?

**Comment by avih** [comment] 2017-03-11 11:11
I don't think there was a conclusion, but I'd vote to leave it as is. Whoever wants vsync can disable the presets and have finer manual control over the options in general.

**Closed** 2017-03-12 16:59 UTC
Labels: Bug, GUI/WX, Maybe?, Won't Fix

**Comment by gregory38** [comment] 2017-03-12 17:01
Let's close it. Behavior depends on people/machine. So let's keep the current situation.

**Comment by jcdenton2k** [comment] 2017-03-13 21:35
Let's not make changes/decisions based on Steam Hardware Survey.  It isn't the be-all or end-all of what people actually use for something like emulation.

**Comment by ramapcsx2** [comment] 2017-03-14 19:21
The issue has less to do with Win10 or not, and more with the actual computer power. Cases where the game barely reaches 60FPS without VSync and cases where the machine is fast enough create groups that would prefer the VSync option off and on respectively. A really good choice can't be made, and I support @avih's position to favor the weaker machines. (Because I assume presets are mostly used by beginners looking for speed.)
