### ISSUE TITLE
Game can't detect memcard at certain point [Tales of Legendia]

### ISSUE THREAD

**Issue by clbr** [PCSX2/pcsx2#1540] opened 2016-08-28 15:21 UTC
On 1.4.0, in Tales of Legendia, the game can't detect a memcard in the "do you want to save?" dialog right after fighting Giet. All save points before that, and the one after it work fine.

It's a curious bug where only that one save point does not see the memcard. This is all during the same run, pcsx2 was not restarted between the save points.

No version is known to work.

PC: Phenom II X6, Linux, Radeon HD4350.

**Comment by clbr** [comment] 2016-08-28 15:29
ISO details: [SLUS-21201] [43AB7214]

**Comment by FlatOutPS2** [comment] 2016-08-28 15:36
Please follow these guidelines when making an issue report: https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues

And also try the latest 1.5.0 release.

**Comment by clbr** [comment] 2016-08-28 16:00
-PCSX2 options: Defaults, no settings modifications affect the issue
-Plugins used: defaults
-Plugin settings: defaults

I can't try the latest git release now, sorry. Was any other info missing?

**Comment by FlatOutPS2** [comment] 2016-08-28 16:38
These are two missing:
-Last known version to work: (Try some older stable versions like 1.2.1 and 1.0.0 to see if it worked before).

-PC specifications: CPU: Intel Core i5 2500K @ 4.3Ghz GPU: Gigabyte Geforce GTX660 Windforce OC 2GB OS: Windows 7 SP1 (32-bit or 64-bit)

And add the info to the first post. ;)

**Comment by clbr** [comment] 2016-08-28 16:55
Added. I believe the hw doesn't matter though, since the only components that can affect memcard detection are pcsx2 core and the memcard plugin?

**Comment by willkuer** [comment] 2016-08-28 19:20
Full emulog after you observed the issue could be helpful.

**Comment by clbr** [comment] 2016-09-02 15:22
The emulog contains nothing interesting, but attaching it anyway. I also have a savestate a few seconds before this, it reproduces the issue every time.

emulog:
```
Loading language translation databases for 'Finnish' [fi_FI]
	pcsx2_Main not found -- translation dictionary may be incomplete.
	pcsx2_Iconized not found -- translation dictionary may be incomplete.
SetLanguage: Requested translation is not implemented yet.
Fontconfig error: Cannot load default config file
PCSX2 1.4.0-0- compiled on Apr 14 2016
Savestate version: 0x9a0b0000

Host Machine Init:
	Operating System =  Linux 3.17.8-laxy i686
	Physical RAM     =  7976 MB
	CPU name         =  AMD Phenom(tm) II X6 1055T Processor
	Vendor/Model     =  AuthenticAMD (stepping 00)
	CPU speed        =  2.810 ghz (6 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  178bfbff 00802009
	x86EFlags        =  efd3fbff

x86 Features Detected:
	SSE2.. SSE3
	MMX2  .. 3DNOW .. 3DNOW2.. SSE4a 

Loading language translation databases for 'Finnish' [fi_FI]
	pcsx2_Main not found -- translation dictionary may be incomplete.
	pcsx2_Iconized not found -- translation dictionary may be incomplete.
SetLanguage: Requested translation is not implemented yet.
Installing POSIX SIGSEGV handler...
Reserving memory for recompilers...
(GameDB) Database Not Found! [/home/ps2/bin/GameIndex.dbf]

Loading plugins...
	Binding   GS: /home/ps2/bin/plugins/libGSdx-1.0.0.so 
	Binding  PAD: /home/ps2/bin/plugins/libonepad-1.1.0.so 
	Binding SPU2: /home/ps2/bin/plugins/libspu2x-2.0.0.so 
	Binding CDVD: /home/ps2/bin/plugins/libCDVDnull.so 
	Binding  USB: /home/ps2/bin/plugins/libUSBnull-0.7.0.so 
	Binding   FW: /home/ps2/bin/plugins/libFWnull-0.7.0.so 
	Binding DEV9: /home/ps2/bin/plugins/libdev9null-0.5.0.so 
Plugins loaded successfully.

HLE Notice: ELF does not have a path.


Initializing plugins...
	Init GS
	Init PAD
	Init SPU2
	Init CDVD
	Init USB
	Init FW
	Init DEV9
Plugins initialized successfully.

Opening plugins...
	Opening GS
Current Renderer: SDL (Software mode)
	Opening PAD
	Opening SPU2
	Opening CDVD
isoFile open ok: /home/ps2/games/Tales of Legendia.iso
	Image type  = DVD
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (1924512 sectors)
	Opening USB
	Opening FW
	Opening DEV9
McdSlot 0 [File]: /home/ps2/PCSX2/memcards/Mcd001.ps2
McdSlot 1 [File]: /home/ps2/PCSX2/memcards/Mcd002.ps2
Plugins opened successfully.
EE/iR5900-32 Recompiler Reset
	Bios Found: USA     v02.00(14/06/2004)  Console
	BIOS r module not found, skipping...
	BIOS r module not found, skipping...
	BIOS e module not found, skipping...
(UpdateVSyncRate) Mode Changed to NTSC.
(UpdateVSyncRate) FPS Limit Changed : 59.94 fps
# Initialize memory (rev:3.70, ctm:392Mhz, cpuclk:294Mhz detected)

PlayStation 2 ======== Hard reset boot
 ROMGEN=2004-0614, IOP info (CPUID=1f, CACH_CONFIG=0, 2MB, IOP mode)
 <20040614-100909,ROMconf,PS20200AC20040614.bin:11696>
# Total accessable memory size: 32 MB (B:2:8:0) (370:2:7c30)
# TLB spad=0 kernel=1:12 default=13:30 extended=31:38
# Initialize Start.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize User Memory ...
# Initialize Scratch Pad ...
# Initialize Done.

EE DECI2 Manager version 0.06 Feb  6 2003 08:38:48
  CPUID=2e20, BoardID=0, ROMGEN=2004-0614, 32M

(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_212.01;1
(SYSTEM.CNF) Software version = 1.01
(SYSTEM.CNF) Disc region type = NTSC
found 0 symbols
ELF (cdrom0:\SLUS_212.01;1) Game CRC = 0x43AB7214, EntryPoint = 0x00100008
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_212.01;1
(SYSTEM.CNF) Software version = 1.01
(SYSTEM.CNF) Disc region type = NTSC


IOP Realtime Kernel Ver.0.9.1

    Copyright 1999 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadelf: fname cdrom0:Â¥SLUS_212.01;1 secname all
loadelf version 3.30
Input ELF format filename = cdrom0:Â¥SLUS_212.01;1
0 00100000 002daf80 ..............................................
Loaded, cdrom0:Â¥SLUS_212.01;1
start address 0x100008
gp address 00000000
# Restart Without Memory Clear.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize Scratch Pad ...
# Restart Without Memory Clear Done.
Get Reboot Request From EE
ROM directory not found

PlayStation 2 ======== Update rebooting..

PlayStation 2 ======== Update reboot complete
cdvdman Init


IOP Realtime Kernel Ver. 2.2

    Copyright 1999-2002 (C) Sony Computer Entertainment Inc. 

Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadmodule: fname cdrom0:Â¥IRXÂ¥SIO2MAN.IRX;1 args 0 arg 
loadmodule: id 25, ret 0
loadmodule: fname cdrom0:Â¥IRXÂ¥SIO2D.IRX;1 args 0 arg 
loadmodule: id 26, ret 0
loadmodule: fname cdrom0:Â¥IRXÂ¥MCMAN.IRX;1 args 0 arg 
loadmodule: id 27, ret 2
loadmodule: fname cdrom0:Â¥IRXÂ¥MCSERV.IRX;1 args 9 arg thpri=40
loadmodule: id 28, ret 2
loadmodule: fname cdrom0:Â¥IRXÂ¥DBCMAN.IRX;1 args 0 arg 
loadmodule: id 29, ret 0
loadmodule: fname cdrom0:Â¥IRXÂ¥PAD2Â¥DS2U_D.IRX;1 args 0 arg 
loadmodule: id 30, ret 0
loadmodule: fname cdrom0:Â¥IRXÂ¥LIBSD.IRX;1 args 0 arg 
loadmodule: id 31, ret 0
loadmodule: fname cdrom0:Â¥IRXÂ¥KORGIVAG.IRX;1 args 48 arg vag=1024
KORG IOP Sound Driver - version1.0 rev.31  (C)2001-2005 KORG Inc.
loadmodule: id 32, ret 0
loadmodule: fname cdrom0:Â¥IRXÂ¥IXAUDIO.IRX;1 args 0 arg 
loadmodule: id 33, ret 0
DVCI: "Â¥AFSÂ¥SYS_REG.AFS" found.
DVCI: "Â¥AFSÂ¥FIELD.AFS" found.
DVCI: "Â¥AFSÂ¥SND.AFS" found.
DVCI: "Â¥AFSÂ¥MAP.AFS" found.
DVCI: "Â¥AFSÂ¥BATTLE.AFS" found.
DVCI: "Â¥AFSÂ¥MOVIE.AFS" found.
DVCI: Total 6 files.
PS2RNA: sceSifAllocIopHeap(133184) ret=0x00134c00
PS2RNA: sceSifAllocIopHeap(2256) ret=0x00155500
PS2RNA: sceSifAllocIopHeap(8256) ret=0x00155e00
IxAudio Ver 1.0.0.7

gpSound    - 00158700 Address :        0 Bytes
gpMusic    - 00158700 Address :    98304 Bytes
gpCache    - 00170700 Address :   270336 Bytes
IOP  FreeMemory               :   220928 Bytes
IOP  MaxFreeMemory            :   215552 Bytes
SPU2 ManagementMemory[S]      :     5000
SPU2 ManagementMemory[E]      :   200000
SPU2 EffectWork[C0]           :   1DFFFF
SPU2 EffectWork[C1]           :   1FFFFF

 > Selected savestate slot 0
Loading savestate from slot 0...
	filename: /home/ps2/PCSX2/sstates/SLUS-21201 (43AB7214).00.p2s
	Loading GS
	Loading SPU2
EE/iR5900-32 Recompiler Reset
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
 > Selected savestate slot 0
	Backing up existing state in slot 0.
Saving savestate to slot 0...
	filename: /home/ps2/PCSX2/sstates/SLUS-21201 (43AB7214).00.p2s
	Saving GS
	Saving SPU2
(gzipThread) Data saved to disk without error.
[IOP] Stop_Music
[IOP] Stop_Music
[IOP] Stop_Music
[IOP] Stop_Music
[IOP] Stop_Music
 > Selected savestate slot 0
	Backing up existing state in slot 0.
Saving savestate to slot 0...
	filename: /home/ps2/PCSX2/sstates/SLUS-21201 (43AB7214).00.p2s
	Saving GS
	Saving SPU2
(gzipThread) Data saved to disk without error.
[IOP] Stop_Music
[IOP] Stop_Music
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
 > Selected savestate slot 0
	Backing up existing state in slot 0.
Saving savestate to slot 0...
	filename: /home/ps2/PCSX2/sstates/SLUS-21201 (43AB7214).00.p2s
	Saving GS
	Saving SPU2
(gzipThread) Data saved to disk without error.
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
 > Selected savestate slot 0
	Backing up existing state in slot 0.
Saving savestate to slot 0...
	filename: /home/ps2/PCSX2/sstates/SLUS-21201 (43AB7214).00.p2s
	Saving GS
	Saving SPU2
(gzipThread) Data saved to disk without error.
[15:19:24.154] Auto-ejecting memcard [port:0, slot:0]
Closing plugins...
	Closing DEV9
	Closing FW
	Closing USB
	Closing CDVD
	Closing SPU2
	Closing PAD
	Closing GS
Plugins closed successfully.
Shutting down plugins...
Plugins shutdown successfully.
(GameDB) Unloading...
```

Savestate: https://u.pomf.is/tltrub.p2s
Original filename: SLUS-21201 (43AB7214).00.p2s

**Comment by willkuer** [comment] 2016-09-02 15:35
If there is a bug it's probably saved in the savestate. It's highly recommended not to use savestates upon observing bugs but rather saving somewhere (:D) and restart the emulation. That you can reproduce the bug with the savestate is not remarkable but rather something like expected.

Have you tried getting to the same point without using savestates?

**Comment by clbr** [comment] 2016-09-02 15:43
Yes, the first time I got there, 5 days ago, was without savestates. The state is just to speed up everyone's testing, because the last save point is an hour before this point (and I already saved over it, so I can't provide it anymore, I'm afraid).

**Comment by clbr** [comment] 2016-09-02 15:45
Oh, and in case it matters, this is again completely my own playthrough and completely my own save.

**Comment by clbr** [comment] 2016-09-02 15:51
I take daily backups, so I can provide a memcard with a save point about two hours before this.

**Comment by clbr** [comment] 2016-09-02 16:34
Here's the memcard two hours before the bug point.
https://u.pomf.is/fewart.gz

**Comment by vsub** [comment] 2016-09-02 21:09
Works fine here(well kinda)

I loaded the save above and go all the way to the same point before the fight and I was able to successfully save the game and after the battle and some cut scenes,the game ask me if I want to save and it was again without any problems.

It will randomly not work if I load a save state but when I choose "No" when it ask me if I want to cancel saving,then it will detect the card but not correctly.

It seems a savestate also remembers the memory card state because after I did my first test I created another save and  I must have 3 saves in the card(the original one,the one before the battle and one after the battle)but after loading the savestate and proceeding to the "asking if I want to save the game",there were only two saves.

And if I go to Config=>Memory Cards=>hit ok=>choose no on canceling to save,the game will reload the card and it will display all 3 saves.

Here is the card if someone want to do some tests(slot 2 is before the battle and I level up the characters to max level to make it easier beating the boss)
http://www30.zippyshare.com/v/nvLQ4LFh/file.html

**Comment by MrCK1** [comment] 2020-11-10 22:39
Is someone able to verify if this is an actual issue on latest dev? Thanks.

**Comment by HeroponRikiBestest** [comment] 2021-12-06 10:50
I can check, but @vsub do you still have your memory card saves? Your link is dead.

**Comment by Mrlinkwii** [comment] 2022-11-19 21:47
is this still  an issue on latest nightly ?

**Comment by clbr** [comment] 2022-11-20 06:56
I've already completed the game years ago and have no interest of going back.

**Comment by guidodi** [comment] 2024-04-26 06:03
[Mcd001.zip](https://github.com/PCSX2/pcsx2/files/15125972/Mcd001.zip)

This is fixed in latest 1.7.5746, I leave a save in case someone want to check. Save after the fight.

**Comment by Mrlinkwii** [comment] 2024-04-26 17:09
@guidodi  thanks for letting us know :)

**Comment by refractionpcsx2** [comment] 2024-04-26 19:19
Well I'll assume you guys are right as I can't test it. If someone finds it broken we can reopen :)

**Closed by refractionpcsx2** 2024-04-26 19:19 UTC
Labels: Memory Card
