### ISSUE TITLE
Destroy all Humans 

### ISSUE THREAD

**Issue by LasagnaPie** [PCSX2/pcsx2#55] opened 2014-05-28 07:14 UTC
There is graphical artifacts covering the entire screen in Hardware mode, both DX/GL, software is fine. 

![destroy all humans](https://cloud.githubusercontent.com/assets/7449866/3101580/88724120-e637-11e3-97db-8e111e03cf56.jpg)

**Comment by gregory38** [comment] 2015-06-30 10:14
Could you test the build of this thread http://forums.pcsx2.net/Thread-GSdx-2-0 ?
Note: OpenGL only

**Comment by gregory38** [comment] 2016-04-25 15:05
A test of newer GSdx version will be nice (still openGL)

**Comment by FlatOutPS2** [comment] 2016-04-25 15:14
Hasn't been fixed in master or with #1306 PR.

**Comment by gregory38** [comment] 2016-05-02 18:59
Is it ok with latest channel effect ?

**Comment by FlatOutPS2** [comment] 2016-05-02 19:27
Latest git still has the same issue.

**Comment by refractionpcsx2** [comment] 2016-05-02 22:42
The latest git still has the shadowy mess over the screen, the only effect fixed was the darkening of the background when you bring a menu up

**Comment by gregory38** [comment] 2016-05-05 17:31
Oh too bad

**Comment by Twilit-Soul** [comment] 2017-02-12 08:14
Still happening, by the way.

-PCSX2 version: v1.5.0-dev-1885-gf86ea9f

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx, SPU2-X, LilyPad, Gigaherz CDVD, the rest are null plugins

-Plugin settings: Tested GSdx DX11 hardware and software renderers. The issue is fixed with a DX11 software renderer of GSdx

-How to replicate: Load into game and as soon as you reach actual gameplay (past the start menu) it's happening.

-Last known version to work: Unknown, probably never worked

-PC specifications:
CPU: Intel Core i5 6600K @ 3.5Ghz (OC'd to 4.3Ghz)
GPU: Geforce GTX 970 (no OC)
16GB
OS: Windows 10 Pro 64-bit

**Comment by Twilit-Soul** [comment] 2017-02-12 08:21
Setting Skipdraw in Hardware Hacks to 5 seems to alleviate the issue somewhat, but I'm not knowledgable enough about the game or the emulator to know if this is a good work-around.

**Comment by BreakPoints** [comment] 2017-03-11 05:41
It does get rid of the garbage shadow stencil but also disables most, if not all, post effects so the game ends up looking very flat. Definitely more playable though.

**Comment by FloppyDisk1** [comment] 2017-08-02 01:27
Any update on this issue?

**Comment by BreakPoints** [comment] 2017-08-02 15:07
Bug is still present in DaH 1 & 2 in latest dev release (pcsx2-v1.5.0-dev-2149). All we can really do is wait for a fix to be figured out.

**Comment by KevinSkull** [comment] 2017-09-13 10:31
Setting it to skipdraw 3 only has minor textures issues such as jetting or when using saucer 

while skipdraw 5 breaks the subtitles and some menus from not displaying

**Comment by mirh** [comment] 2018-09-07 22:26
Could you try playing with clamp modes like it was done in #1436?

**Comment by RinMaru** [comment] 2018-09-08 01:57
cant even get ingame now it eats up all 8GB of ram and freezes the game

**Comment by MrCK1** [comment] 2018-09-08 01:59
Turn down your GSdx settings then.

**Comment by RinMaru** [comment] 2018-09-08 02:00
what ones?

**Comment by MrCK1** [comment] 2018-09-08 02:00
Probably your resolution.

**Comment by RinMaru** [comment] 2018-09-08 02:02
no clamping mode doesn't fix the screen artifacts

**Comment by MrCK1** [comment] 2018-09-08 02:03
On both the EE and VU? You could also try using SuperVU and playing with both EE and VU rounding modes as well.

**Comment by RinMaru** [comment] 2018-09-08 02:07
yea nothing gets rid of them. also once I got in game and changed my gsdx settings back it works fine so something is going wrong when it has to access the MC

**Comment by MrCK1** [comment] 2018-09-08 02:09
Sorry, I misread the issue. I was thinking of #1436

**Comment by Stryxus** [comment] 2020-05-10 16:49
(This is all from DAH2 experience)

Although performance has increased substantially in 1.6.0, this still remains an issue.

Iv seen people complain that you fall through the world while in hardware mode but this seems to be something coming from enabling manual game fixes, a reboot of PCSX2 is required to fix this issue. The NPC's still sometimes trip over and vehicles only fall through the ground when transmogrifying them.

The UI issues remain but are hardly as bad as they used to be. The game is still playable with the UI bugs because the vital parts of them remain (Health bar without border and visible text on selection).

**Comment by BreakPoints** [comment] 2020-05-13 18:25
The falling through the floor issue was mentioned in [issue 1436.](https://github.com/PCSX2/pcsx2/issues/1436) I am unsure if the Clamp = Full caused this but I have found after playing for a decent amount of time on the software renderer, NPCs start spawing and getting stuck in the ground to the point where I can't complete missions (DaH2).

**Comment by kakashi314** [comment] 2023-01-01 18:21
Can anyone check if this issue still exists ?

**Comment by refractionpcsx2** [comment] 2023-01-01 18:23
Yeah it still happens

**Closed** 2023-03-01 21:13 UTC
Labels: Bug, GS, GS: Hardware
