### ISSUE TITLE
[BUG]: Auto flush upscaling bug in Jak 3

### ISSUE THREAD

**Issue by EvilPlayer1** [PCSX2/pcsx2#6969] opened 2022-08-31 14:02 UTC
### Describe the Bug

Some visual effects are glitching with enabled auto flush in HW mode with any resolution.

### Reproduction Steps

Look on any objects, which have "image moving" effect.

### Expected Behavior

Image without glitches.

### PCSX2 Revision

v1.7.3265

### Operating System

Windows 11

### CPU

i7-11700

### GPU

GTX 1660 SUPER

### GS Settings

![Screenshot 2022-08-31 16-58-00](https://user-images.githubusercontent.com/90133207/187696777-c59c7bc8-435a-49bc-aa8f-7b2e9cf9cefd.png)
![Screenshot 2022-08-31 16-58-05](https://user-images.githubusercontent.com/90133207/187696781-0a828b7c-2e30-4372-a95f-81bca1d12008.png)
![Screenshot 2022-08-31 16-58-11](https://user-images.githubusercontent.com/90133207/187696786-462a6458-7c6e-423a-b5b5-256b68c04638.png)

### Emulation Settings

![Screenshot 2022-08-31 16-58-32](https://user-images.githubusercontent.com/90133207/187696841-7f44bff6-ddfd-40a1-8f7f-9cff0341e5aa.png)
![Screenshot 2022-08-31 16-58-37](https://user-images.githubusercontent.com/90133207/187696845-6188b2de-0a3e-4f52-8e12-1fe37ab6e6b2.png)
![Screenshot 2022-08-31 16-58-40](https://user-images.githubusercontent.com/90133207/187696848-bd1cab9b-a6ab-4dde-8479-185699deffb1.png)

### GS Window Screenshots

HW:
![Screenshot 2022-08-31 16-53-34](https://user-images.githubusercontent.com/90133207/187696982-cf87c86b-d77e-40d9-847e-868107de81ee.png)
SW:
![Screenshot 2022-08-31 16-53-42](https://user-images.githubusercontent.com/90133207/187697010-1adfd672-4114-41ad-a5cb-ad5d32fd817e.png)

**Comment by refractionpcsx2** [comment] 2022-08-31 14:03
You're standing on a heat vent. It's SUPPOSED to do that.

**Comment by EvilPlayer1** [comment] 2022-08-31 14:06
I should play without auto flush? This effect looks awful.

**Comment by refractionpcsx2** [comment] 2022-08-31 14:09
either without autoflush, or don't upscale, that's basically your options.

**Comment by refractionpcsx2** [comment] 2022-08-31 14:13
anyway, as it says in the issue template

> We do not accept issues relating to upscaling at this time

So I'm gonna close this. Thanks for the report.

**Closed by refractionpcsx2** 2022-08-31 14:13 UTC
Labels: Bug

**Comment by EvilPlayer1** [comment] 2022-08-31 14:18
> I guess the third option is don't stand around admiring heat vents ;)

This bug is so huge from far. 
![Screenshot 2022-08-31 17-16-48](https://user-images.githubusercontent.com/90133207/187701058-3fc9f58e-e987-4b4d-b0f2-5501140e2d51.png)

**Comment by refractionpcsx2** [comment] 2022-08-31 14:19
It's not a bug, that's how the heat effect works.

**Comment by EvilPlayer1** [comment] 2022-08-31 14:31
Just a question. Is it possible to fix these broken screens? I think it's not random bug. Some of them were "selected" to be broken.
![Screenshot 2022-08-31 17-22-56](https://user-images.githubusercontent.com/90133207/187704087-be62a501-b8f0-4b7b-b69f-e9d7ca097627.png)

**Comment by refractionpcsx2** [comment] 2022-08-31 14:33
It might possibly be fixed by this PR https://github.com/PCSX2/pcsx2/issues/6969

but that has a bunch of work before it can be merged, but does fix some texture problems

**Comment by EvilPlayer1** [comment] 2022-08-31 14:48
Last moment: I see strange bug, when flying above the water. Last playe played in March, and if I am correct, I didn't notice something like that.
![Screenshot 2022-08-31 17-46-24](https://user-images.githubusercontent.com/90133207/187707952-fbc656fc-38bb-4703-b919-c245e98165c8.png)
