### ISSUE TITLE
Spider-Man 2  texture bugs

### ISSUE THREAD

**Issue by ADormant** [PCSX2/pcsx2#649] opened 2015-07-11 19:03 UTC
It looks like this https://www.youtube.com/watch?v=QDb50qtisqI probably a texture cache issue.

**Comment by prafullpcsx2** [comment] 2015-07-11 19:23
Nice coincidence, I was posting about it in the forums but just noticed your report here. i will rather continue here now.

Here is the GS dump.

http://www.filedropper.com/spiderman2

**Comment by karasuhebi** [comment] 2015-08-05 14:41
@ADormant Are you having that issue in the latest dev builds? The PCSX2 build the uploader used in that video is very old.

**Comment by bositman** [comment] 2015-08-19 22:29
Since no one bothered to make an actual proper bug report, I'll do it and close this.

**Closed by bositman** 2015-08-19 22:29 UTC
Labels: GSdx: Hardware

**Comment by FlatOutPS2** [comment] 2018-03-04 16:28
Also Duplicate of #775
