### ISSUE TITLE
[AMD Windows update driver (15.2)] show a white screen under OpenGL.

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2154] opened 2017-11-30 20:38 UTC
***PCSX2 version:***
Last 1.5dev

***PCSX2 options:***
All default

***Plugins used:***
All default

***Description of the issue:***
The OpenGL render don't work on my 15.2 Windows update driver. It show a white screen look:

![capture](https://user-images.githubusercontent.com/26351275/33453811-45809bae-d617-11e7-9001-0a18f63b3e6c.PNG)

***How to reproduce the issue:***
Load PCSX2 with the OpenGL render with the 15.2 AMD driver.

***Not a regression:***

***PC specifications:***
Intel Core I53230m AMD radeon hd 7600m Windows 10 64 Bit

**Comment by MrCK1** [comment] 2017-11-30 20:39
I thought you had an Nvidia GPU? Also, how new is this AMD driver?

**Comment by atomic83GitHub** [comment] 2017-11-30 20:41
#MrCK1: It is not the same PC :).

This is a special version packed with Windows Update and was made in 2015.

**Comment by MrCK1** [comment] 2017-11-30 20:41
Microsoft WHQL drivers often differ from the latest available, I would check the AMD website.

**Comment by atomic83GitHub** [comment] 2017-11-30 20:48
It is not available on the AMD website. I have found one link about this version:
https://www.touslesdrivers.com/index.php?v_page=3&v_code=5860

**Comment by MrCK1** [comment] 2017-11-30 20:51
Looks like your product family has been moved to legacy support. I would say that's part of the problem here: http://support.amd.com/en-us/download/desktop/legacy?product=legacy3&os=Windows%2010%20-%2064

**Comment by MrCK1** [comment] 2017-11-30 21:01
@atomic83GitHub Can you download the installer and see if it will let you install the newest driver? Otherwise, I'm going to close this most likely.

**Comment by atomic83GitHub** [comment] 2017-11-30 21:02
The legacy support is not the issue here, the driver available on the AMD website don't seems to have the issue so it can be a specific driver issue.

**Comment by MrCK1** [comment] 2017-11-30 21:04
The point is, this is a significantly older driver - from March 2016 nonetheless. If you hardware doesn't support the newest AMD driver, that's not really our problem. The least we can assume is that it doesn't exist in the newest driver (excluding every other thing that's currently wrong with them)

**Comment by atomic83GitHub** [comment] 2017-11-30 21:07
The final beta for non GCN product seems to fix the issue, thanks. But it would be nice to add a warning message for the users of this driver because, other OpenGL based applications like Bluestacks work exactly the same on booth driver so it's strange ^^.

**Comment by lightningterror** [comment] 2017-11-30 21:14
What is the driver version that shows on gpuz ?
Can you upload the atioglgl.dll ?

**Comment by atomic83GitHub** [comment] 2017-11-30 21:23
GPUz show: 15.8 beta rev:15.201.1151.
I will upload atioglgl.dll later.

**Comment by lightningterror** [comment] 2017-11-30 22:39
You can get hybrid 17.1.1 drivers here.
https://forums.guru3d.com/threads/16-101-2901-1001.409002

Duplicate. #1552

**Closed by lightningterror** 2017-11-30 22:39 UTC
Labels: Duplicate, Upstream | External, Won't Fix

**Comment by mirh** [comment] 2017-12-13 10:46
Ehrm.. FTR they have maybe just a file from 17.1.1, that hardly make a difference. 
For the remainder they are just what you could call "kind-of-16.3"

**Comment by lightningterror** [comment] 2018-06-11 16:59
I did a bit more digging in this and it is a regression.

821 somewhat works, some elements are semi transparent but the background isn't white/doesn't flicker anymore.
7682bf9b497db4a6e930f4ed13f74d05deb14083 v1.5.0-dev-821-g7682bf9b4 https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.5.0-dev-821-g7682bf9b4&platform=windows-x86

852 introduced it with the new SSO partial working workaround.
7202cac7d0f5eb071358c8e2850b55aaaeb837b5 v1.5.0-dev-852-g7202cac7d https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.5.0-dev-852-g7202cac7d&platform=windows-x86

Well in a nutshell the old Catalyst drivers are worse than Crimson so it's a driver issue.

**Comment by mirh** [comment] 2018-06-11 18:07
*Old*.. as in how much?
Stuff between 15.7-15.8 was broken AF iirc. 

For the reminder, even [13.9](https://github.com/PCSX2/pcsx2/pull/2033#issuecomment-322407714) should be in a working state (I mean, at least \*anything\* more than just a blank screen)

**Comment by lightningterror** [comment] 2018-06-11 19:46
@atomic83GitHub can you test this out ?

[GSdx32-SSE4.zip](https://github.com/PCSX2/pcsx2/files/2091505/GSdx32-SSE4.zip)

**Comment by atomic83GitHub** [comment] 2018-06-23 09:43
There is still a white screen with this, but anyway I update my driver with the one you mentioned and it work fine (aside AMD issues).
