### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by mitch03** [PCSX2/pcsx2#7239] opened 2022-10-19 10:35 UTC
### Description

Adding a usb link to psp emulator (ppsspp) 

### Reason

to be able to unlock extra items and features in games

### Examples

in Jak X you can link the game to a psp game and can unlock vehicles

**Comment by Mrlinkwii** [comment] 2022-10-19 10:37
duplicate of  #3527

**Closed** 2022-10-19 10:37 UTC
Labels: Enhancement / Feature Request
