### ISSUE TITLE
Burnout 3/Revenge/Dominator - Sun Glow Can Be Seen Through Surfaces

### ISSUE THREAD

**Issue by escape209** [PCSX2/pcsx2#883] opened 2015-10-07 21:36 UTC
This is a known issue, but I'm opening this issue here so that if there is any progress on it being fixed, then it can be posted here and eventually (hopefully) marked as solved, in addition to the fact that it hasn't been mentioned on the issue tracker yet.

Anyway, this bug seems to be a core bug, as it appears in all of GSdx's software and hardware renderers, as well as in ZeroGS. It's a pretty easy issue to understand - you can see the sun through walls, when it should disappear when your view of it is completely (not partially) obscured by an object. The bug happens in Burnout 3: Takedown, Burnout Revenge and Burnout Dominator, of which the versions for all regions are affected (basically, PAL and NTSC.)

No combination of settings in the Emulation settings window, nor the GSdx settings window has been able to fix the bug (including Synchronized MTGS.)

**Comment by FirstRoboticsGuy999** [comment] 2015-10-11 16:41
This isn't just a Burnout issue. It happens in games like Gran Turismo 4 as well. It probably has something to do with alpha sorting or that fact that the PS2 doesn't have depth buffer support.

I found a great write-up by Matt Godbolt that explains some of the PS2's rendering limitations. http://xania.org/201003/swat-ps2-renderer

**Comment by gregory38** [comment] 2015-10-12 20:26
PS2 has depth support. It misses stencil / color swizzle / shader ... Well it just misses everything.

There is still a bug in SW when doing read/write to a texture so it could still be a GSdx bug. But it could also be a core bug.

**Comment by DPersonalized** [comment] 2016-01-10 13:53
It seems like it's not the sun that's showing through walls and it's actually just its glow effect. Setting Skipdraw to 28 will remove the sun's glow, meaning it won't show through walls, but it will appear as just a yellow circle in the sky:

Skipdraw 0
![gsdx_20160110131542](https://cloud.githubusercontent.com/assets/8225831/12221792/205cb830-b7a1-11e5-87e9-e708fa9a4dcc.PNG)

Skipdraw 28
![gsdx_20160110131710](https://cloud.githubusercontent.com/assets/8225831/12221799/4615e146-b7a1-11e5-9b55-031cdd36a17d.png)

**Comment by willkuer** [comment] 2016-01-10 14:16
28?

I never heard such a large value. For 27 you can still see the glow?
Thanks for the hint. This makes support much easier.

**Comment by DPersonalized** [comment] 2016-01-10 14:28
The glow is indeed **still** there at 27 :scream:

**Comment by FlatOutPS2** [comment] 2016-10-06 14:26
This issue has recently been solved for software mode thanks to https://github.com/PCSX2/pcsx2/commit/a123e6518521f3d59c628678c11031a4d2d8358c

It still affects the hardware modes though.

**Comment by jcdenton2k** [comment] 2016-10-09 16:15
Wanted to mention that the 'Sun Rays' would appear through buildings/walls in FF12 as well.  It didn't bother me enough to post about it but it has been an ongoing issue since forever.

I'll test out with software mode and report back with details if needed.

**Comment by RedDevilus** [comment] 2020-05-10 19:46
Seems to still be a problem in HW mode and SW as always works well.

**Comment by jeremybris** [comment] 2022-02-27 23:09
Bug is also in:
- #257 - Manhunt
- #1860 - Ace Combat 5
- #2249 - Syphon Filter
- #2766 - Tekken 5
- #2817 - Silent Hill 2
- #3751 - Need for Speed Most Wanted
- #3993 - Gran Turismo 4
- #5409 - Alias
- Power Drome (Underwater Level)
- 007: From Russia with Love (Second Level)
- Final Fantasy XII (Mentioned above)
- Probably other games

A similar issue was resolved in the PS3 emulator. I don't know if this will help:
- caused by https://github.com/RPCS3/rpcs3/pull/8479
- fixed by https://github.com/RPCS3/rpcs3/pull/9354

**Comment by refractionpcsx2** [comment] 2022-07-10 12:00
Does this still happen in recent 1.7 builds? if it does can we get a GS Dump?

**Comment by Mrlinkwii** [comment] 2022-07-10 12:17
[burnout light though object.zip](https://github.com/PCSX2/pcsx2/files/9079023/burnout.light.though.object.zip)
heres a GS dump :slightly_smiling_face:

**Comment by JimScript** [comment] 2022-07-10 17:10
Lego Racers 2 has the same problem as well:
![gs_20220710100117_LEGO Racers 2_SLUS-20042](https://user-images.githubusercontent.com/66685584/178154563-b2fb94fe-8c31-441e-9fe2-d0ac29ba7b90.png)
GS Dump:
[gs_20220710095656_LEGO Racers 2_SLUS-20042.zip](https://github.com/PCSX2/pcsx2/files/9079493/gs_20220710095656_LEGO.Racers.2_SLUS-20042.zip)
![gs_20220710100711_LEGO Racers 2_SLUS-20042](https://user-images.githubusercontent.com/66685584/178154782-bc0a02aa-a380-42b7-b701-12cc02638b49.png)
GS Dump:
[gs_20220710100711_LEGO Racers 2_SLUS-20042.zip](https://github.com/PCSX2/pcsx2/files/9079512/gs_20220710100711_LEGO.Racers.2_SLUS-20042.zip)

Thing is, switching to software doesn't immediately get rid of it(as seen in the GS Dumps), it's like there is a culling system in the software mode that isn't in the hardware mode.

**Comment by refractionpcsx2** [comment] 2022-07-10 17:42
Can you make your own thread for that please? It's likely not the same problem (a lot of different things can cause this!). Since it takes a moment to kick in, it probably needs to download the picture to work it out, which means it might not show in the GS dump.

**Comment by JimScript** [comment] 2022-07-10 18:03
Right, sorry it looked close enough of a problem to comment, I have made a separate issue here(#6605).

**Comment by refractionpcsx2** [comment] 2022-07-10 18:15
Thanks :)

**Comment by twoco** [comment] 2022-07-29 18:27
@jeremybris Thanks for your list of existing issues or duplicated (If this bug is caused by the same reason). Btw. you have a misstake in your list. For Need for Speed Most Wanted it's #3993.

**Closed** 2022-10-30 14:46 UTC
Labels: GS, GS: Hardware

**Comment by Softernet** [comment] 2022-10-30 16:20
[#7267](https://github.com/PCSX2/pcsx2/pull/7267) does not fix this issue.

**Comment by refractionpcsx2** [comment] 2022-10-30 16:26
Can you provide a GS Dump? Because the three I tried, it did.

**Comment by Softernet** [comment] 2022-10-30 16:32
Everything is fine. There was a misunderstanding due to the Manual Hardware Render Fixes checkbox.

**Comment by refractionpcsx2** [comment] 2022-10-30 16:35
Yeah that would break it too ;)
