### ISSUE TITLE
[BUG]: PCSX2 "Failed to open" BIOS files with uppercase extensions

### ISSUE THREAD

**Issue by skierpage** [PCSX2/pcsx2#5954] opened 2022-04-25 10:03 UTC
### Describe the Bug

I followed the PCSX2 Getting Started instructions to dump my PS2 BIOS files which created the files `SCPH-70012_BIOS_V12_USA_200.{BIN,EROM,NVM,ROM1,ROM2}. I ran the PCSX2 flatpak and pointed it at the BIOS files and chose my machine BIOS, then opened my game ISO (SSX on Tour)

But `~/.var/app/net.pcsx2.PCSX2/config/PCSX2/logs/emuLog.txt` contains
```
        BIOS rom1 module not found, skipping...
        BIOS rom2 module not found, skipping...
        BIOS erom module not found, skipping...
...
Failed to open NVM file '/path/to/PCSX2_bios_files/SCPH-70012_BIOS_V12_USA_200.nvm' for writing
```
Note the program is trying to open files with lowercase extensions (`.nvm`), but the dumped files have uppercase extensions (`.NVM`). I ran strace on the flatpak and confirmed it is attempting e.g.
```
newfstatat(AT_FDCWD, "/home/spage/Documents/Games/PCSX2_bios_files/SCPH-70012_BIOS_V12_USA_200.rom1", 0x7f2d06cba490, 0) = -1 ENOENT (No such file or directory)
```
_However_, SSX on Tour starts up and runs! I don't see how PCSX2 can work when it indicates it can't read these files :confused: 

### Reproduction Steps

- Dump your PS2 BIOS per Getting Started
- Run the PCSX2 flatpak
- Look at the `emuLog.txt` file.

### Expected Behavior

Maybe the instructions should tell the user to rename the dumped BIOS files to have lowercase extensions.

### PCSX2 Revision

PCSX2 Nightly - v1.7.2648 Compiled on Apr 24 2022

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Fedora (running Flatpak)

**Comment by refractionpcsx2** [comment] 2022-04-25 10:07
PCSX2 only needs to see the main BIN/ROM0 file, the others are generally unimportant unless you're in China, but yeah it should be detecting them.

**Comment by skierpage** [comment] 2022-04-25 19:57
> It would work on Windows as the paths are case insensitive. The "simple" solution would to rename the files and make the extensions lowercase.

Should https://pcsx2.net/guides/basic-setup/#dumping-the-bios mention this? (BTW, I have a  [pull request](/PCSX2/pcsx2-net-www/pull/106) improving the guide.) An alternative is to change PCSX2 code to use uppercase extensions in
```c
//   This function does not fail if rom1, rom2, or erom files are missing, since none are
//   explicitly required for most emulation tasks.
...
        LoadExtraRom("rom1", eeMem->ROM1);
        LoadExtraRom("rom2", eeMem->ROM2);
        LoadExtraRom("erom", eeMem->EROM);
...
        std::string mecfile(FileSystem::ReplaceExtension(BiosPath, "mec"));
        std::string nvmfile(FileSystem::ReplaceExtension(BiosPath, "nvm"));
```

> As far as I can tell, even going back a few versions, PCSX2 has searched for lowercase extension ROM files.
...
> PCSX2 only needs to see the main BIN/ROM0 file

I think the main `.BIN` file loads because `FindBiosImage()` looks at every file in `EmuFolders::Bios` regardless of extension to find one that looks like it holds the main BIOS.

BTW, when SSX on Tour appeared in a window with sound, I jumped up and down :joy:. Thanks for your work!

**Comment by stenzek** [comment] 2022-04-30 03:04
> An alternative is to change PCSX2 code to use uppercase extensions in

That would break everyone's existing setups on Linux/Mac which are using the lowercase extensions (which was the case, going back at very least a few stable releases).

IMO, the least risky solution is to add a rename step in the guide.

**Comment by OdinVex** [comment] 2022-06-12 13:22
Feels weird, considering PS2 uses UDF for discs, and they're all upper-case named. Might should've been upper from the start for a sense of continuity? I dunno, chiming in.

**Comment by stenzek** [comment] 2022-06-12 13:45
> considering PS2 uses UDF for discs,

Most if not all use ISO9660. I'm not sure if the firmware/BIOS is even able to speak UDF, I've never checked.

**Comment by OdinVex** [comment] 2022-06-12 16:05
> > considering PS2 uses UDF for discs,
> 
> Most if not all use ISO9660. I'm not sure if the firmware/BIOS is even able to speak UDF, I've never checked.

? For the PS2 DVDs even? Could have sworn it was ISO+UDF/UDF.

**Comment by j8r** [comment] 2022-07-20 17:49
Can be fixed by https://github.com/flathub/net.pcsx2.PCSX2#bios-issues I guess?

**Comment by Florin9doi** [comment] 2022-08-30 09:33
https://github.com/Florin9doi/pcsx2/commit/68bc9402c9edeb4a220cc8021dfe4e75385da87a

**Comment by refractionpcsx2** [comment] 2022-08-30 09:35
> [Florin9doi@68bc940](https://github.com/Florin9doi/pcsx2/commit/68bc9402c9edeb4a220cc8021dfe4e75385da87a)

why are you opening the NVM as read only? it can be modified at any time by the BIOS (if the user changes any options)

**Comment by Florin9doi** [comment] 2022-08-30 09:40
For the same reason it is opened read-only now : https://github.com/PCSX2/pcsx2/blob/aae53fb9da136f372a5fb0526950538374fdfde0/pcsx2/CDVD/CDVD.cpp#L193

**Comment by refractionpcsx2** [comment] 2022-08-30 09:42
fair enough, the diff was just confusing, looked like you'd changed it.

**Comment by stenzek** [comment] 2022-08-30 09:50
I wonder if a general "open case insensitive" routine would be better. i.e. if the open fails, read the directory, and look for any matches without case sensitivity. Because otherwise e.g. `.Mec` still wouldn't work on unix, but would be fine on Windows.

**Comment by Florin9doi** [comment] 2022-08-30 10:09
The bios dumpers usually write all uppercase or all lowercase file extensions. Other combinations are less likely to be encountered. Another issue is to decide which file to use when multiple files are present : `.nvm`, `.Nvm` or `.NVM`. Ideally is to have the user decide, but would be too much headache for nothing.

**Comment by TheTechnician27** [comment] 2024-03-17 22:35
I haven't the slightest idea why I can't reproduce this, but link suggested I try: I've capitalized the file extensions, and the line `Failed to open NVM file '/path/to/blahblahblah.nvm' for writing` or anything similar doesn't appear anywhere in the Zsh log or in the emulog window. Instead, the .NVM file remains, and when the game is booted (trying SSX On Tour as well), a .nvm file is simply created as well.

**Comment by F0bes** [comment] 2024-11-28 19:37
The recommended and best (totally not biased 😄) BIOS dumper biosdrain uses all lowercase for the output files.
I'm not opposed to someone adding some sort of `FileSystem::OpenFileCaseInsensitive`, where it looks for the file and falls back to a case insensitive search to fix this issue reports scenario. This doesn't warrant a bug report though.

**Closed by F0bes** 2024-11-28 19:37 UTC
Labels: Bug, OS: Linux

**Comment by F0bes** [comment] 2024-11-28 19:52
The user doesn't specify the nvm, mec, etc files. What does PCSX2 change here?

**Comment by F0bes** [comment] 2024-11-28 20:03
If it's such a outstanding issue for you then PR a fix.

Our [recommended dumping procedure](https://pcsx2.net/docs/setup/bios) will provide a working configuration for users. Any other configuration is and has been considered ill-formed.

**Comment by F0bes** [comment] 2024-11-28 20:18
ill-formed is a fact, it has never worked with any version of PCSX2 on case-sensitive file-systems.

> With this kind of dialog I'd wonder if you'd even pull a Pull Request.

I could care less about your, honestly disrespectful, discourse on this issue. If you can manage to write good code without your grandstanding about `nvm` extensions getting in the way, I don't have an issue with pulling it. My goal is to move the project forward, not sit here bumhurt.

> Edit: I'd rather a second opinion on your closing this Issue.

The second opinion called you a dick.


This is far from on-topic. I am locking.
