### ISSUE TITLE
GSdx Shader discussion.

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#788] opened 2015-08-22 08:28 UTC
@gabest11 if you don't mind, I have a couple of question for you.

1/ Have you ever tried to do the Q perpective correction with the GPU hardware unit?
Basically in the VS

```
w = 1 / q;
out.t = st * w;
glPosition *= w; 
```

The only draw back is that we need to flatten in the CPU the Q value for sprite. Actually I'm not sure how behave the GS when Q isn't flat for sprite. Maybe it will be interpolated.

2/ What is the purpose of HalfTexel in bilinear mode ?

```
uv = st.xyxy + HalfTexel;
dd = frac(uv.xy * WH.zw);
```

My first understanding was to emulate the texel center of the GS. But HalfTexel is a 0.5 texel of the GPU texture size not the GS texture size (different when upscaling is enabled). So I suspect it is only used to take into account the texel center of the GPU texture.

I think the root cause of upscaling ghosting is related to a half texel.
UV = Integer Value + Half GS Texel. (range from 0.5 to S+0.5)
Current a 4x upscaling will do
4x UV = 4 \* Int + 4 \* Half GS Texel = 4 \* Int + 2 (range from 2 to S+2)
Maybe we could replace it by
4x UV = 4 \* Int + Half GPU texel (range from 0.5 to S + 0.5)

It might work better than the current HalfPixelOffset hack.

**Comment by gabest11** [comment] 2015-08-22 10:23
You have to use q per pixel to get perspective correct textures, if it was that simple q would not even exists, only s/t was given. Basically, you divide any parameter you want to interpolate by the depth (z works just fine in a special case), calculate the parameter and 1/z per pixel, and re-multiply them again for each pixel.

I'm not sure you know how bilinear sampling works, so I explain it. There is s/t, the two floating point texture coordinates, which have a texel center of 0.5, so that at 0.5/0.5 you have to sample exactly the first texel without any blending. The sampling process adds and subs 0.5 from s/t, creating four pairs (0,0) (1,0) (0,1) (1,1), rounding them down (floor), and blends the four sampled color values together by the fraction of the top left sample, which is exactly 0 in this case, so you get the top left texel without blending with the other three. 

It is simply not possible to change the texture size and adapt the texture coordinates to it, if you multiply by the scaling factor, the texel center is no longer accurate. Want to upscale by 2? That 0.5 I used in my example becomes 1.0 (0.5,0.5) (1.5,0.5) (0.5,1.5) (1.5,1.5), wrongly blending by 0.5 and all four texels are used.

The only real solution is MSAA, in that case you leave the texture coords and the colors alone (ie only sample once per pixel), but at each pixel, the screen is divided into further pixels, you do the z test by each sub-pixel and the geometry becomes higher resolution. The problem is, you have to store the additional sub-pixels of the render target somewhere, until it is finally displayed or reused as a texture, then you average them together to restore the original resolution.

**Comment by gregory38** [comment] 2015-08-22 11:10
Here the formulae of interpolations done by the rasterizer

![opengl_interpolation](https://cloud.githubusercontent.com/assets/1569559/9423575/a3ece87e-48c9-11e5-9399-c5bbbb33dfe2.png)


Currently the first one is used with w=1.0f. In this case it is equivalent to the 2nd one (linear interpolation). If we set w as 1/Q and premult S/T by w, it would be equivalent to use Q per pixel. However it is not clear for me what is the impact on the z-depth. It seems XYZ coordinates are firstly divided by W so I premult them with W.

```
It is simply not possible to change the texture size and adapt the texture coordinates to it,
```
Hum.

I'm not thrilled about MSAA. Everytime we want to reuse the RT as a texture it costs an extra downspampled step. It is not suited to the rendering by column (I mean vertical page) of the GS. Besides I'm not sure I could read a multisampled RT from the shader. It helps to emulate blending and fbmask correctly.

Maybe instead of emulating the GS, we could emulate the effect directly. For example if the game want to scale down by 2 the RT, we could detect it based on the VertexTrace and replaces the shader to do the scaling (at least bypass UV stuff). I'm afraid it is going to be too complex.

**Comment by gabest11** [comment] 2015-08-22 11:38
In the sw renderer I also premultiply by 1/q and set fst=1 when I find Q to be constant (by looking at the vertex trace), that's an old trick, don't know why it isn't implemented in the vertex shader, too. Maybe it wasn't that critical.

z does not need perspective correction, because it is used to do it. As I said, 1/z is roughly w.

**Comment by gregory38** [comment] 2015-08-22 11:55
Yes I saw this trick. It cost extra shader permutation so I'm not sure it worth the extra complexity. Above trick will reduce shader permutation and works for any q. The perspective correction is done by the raster unit instead of the FS. The per-fragment q division is still here but free.

I search a bit on the depth. The position outputed in the VS is in the clip space, so I need to premult Z by W (X & Y too).
```
The value of gl_Position is in what OpenGL calls "clip space". It is a homogeneous coordinate system. In particular, the XYZ extents of clip space are [-W, +W]. So each vertex is in its own clip space.

... the clipped vertices are transformed to normalized device coordinate (NDC) space. This means dividing the XYZ of the clip space by W. All of these vertices are in the range [-1, 1].
```

**Comment by gabest11** [comment] 2015-08-22 12:51
Just keep in mind that stq can be anything, as long as their ratio point to the right texture location. Not necessarily following the normal 3d rendering guildlines.

**Comment by gregory38** [comment] 2015-08-22 14:43
Hum. I think the math will hold but it is a valid point. In the end I need to benchmark it. I'm not sure it will make a difference anyway

**Comment by lightningterror** [comment] 2024-09-15 18:47
Closing as this is no longer discussed/relevant.

**Closed by lightningterror** 2024-09-15 18:47 UTC
Labels: Question / Discussion, GS
