### ISSUE TITLE
[BUG]:  Time Crisis 2 Guncon2 split-screen calibration issue

### ISSUE THREAD

**Issue by ZTylerDurden** [PCSX2/pcsx2#10118] opened 2023-10-15 20:46 UTC
### Describe the Bug

Time Crisis 2 NTSC- SLUS-20219

Intro calibration screen works fine except it does not translate well for 2 player split-screen mode accuracy for Guncon2 USB emulation.

### Reproduction Steps

All default settings, then:
Guncon2 USB 1P and 2P set to mouse bindings

Calibrate using the calibration intro splash screen for TC2.  Shots will line up fine according to mouse pointer.

Select 2 player split screen mode.  Shots in-game will no longer line up according to mouse pointer.

### Expected Behavior

Split-screen shots should line up with mouse pointer.

For reference, legacy pcsxs2 nuvee plugin used these screen coordinates to accommodate split-screen mode.  They improve the experience for 1.7 but still not accurate.

X Scale (Sensitivity): 95 
Y Scale (Sensitivity): 45 
Center X: 390
Center Y: 150
Screen Width: 640
Screen Height: 240

### PCSX2 Revision

PCSX 1.7.5098

### Operating System

Windows 10 (64bit)

### CPU

i7-8700k

### GPU

RTX 4070

### GS Settings

Default

### Emulation Settings

Default

**Comment by stenzek** [comment] 2023-10-16 00:39
Probably a duplicate of #7618. The whole value range thing needs to get removed, and instead pull it from the PCRTC contig, but due to users being, well, users, I completely lost interest in doing so. If someone wants to take it on, go nuts.

**Closed by stenzek** 2023-10-16 00:39 UTC
Labels: Bug
