### ISSUE TITLE
[Regression] Beyond good and evil fmv's flickering

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2138] opened 2017-11-17 16:41 UTC
***PCSX2 version:***
Last 1.5 dev

***PCSX2 options:***
All default , speedhacks enabled (bug also without)

***Plugins used:***
All default

***Description of the issue:***
The beyond good and evil fmv's tends to flicker with the last 1.5git version of PCSX2, the screenshots don't render the issue accurately

Before:
![capture](https://user-images.githubusercontent.com/26351275/32957405-e5d55272-cbbb-11e7-937a-a0575d7d82ef.PNG)

After:
![capture32](https://user-images.githubusercontent.com/26351275/32957425-f1e3dd40-cbbb-11e7-9155-5de435baba6f.PNG)

***How to reproduce the issue:***
Load PCSX2 and Beyond good and evil, go to the extra menu and load the BGE E3 trailer.

***Last known version to work:***
PCSX2 1.5dev 721

***PC specifications:***
AMD fx8350 Gainward 780ti Windows 10 64 Bit

***GSdump and Blockdump***
https://drive.google.com/file/d/1hpJTCFyuK9qxMIqVH1xTPQifyeoJ1Ev0/view?usp=sharing

**Comment by MrCK1** [comment] 2017-11-17 16:45
Did you try switching to software mode?

**Comment by atomic83GitHub** [comment] 2017-11-17 16:47
Software mode do not solve the issue.

**Comment by MrCK1** [comment] 2017-11-22 17:57
@atomic83github Can you please try to update the information in your other issues before opening new ones. Finding the specific build when these regressions was introduced will help us out a lot! Thanks!

**Comment by atomic83GitHub** [comment] 2017-11-22 18:01
I am on it :), the buildbot also seems to work.

**Comment by atomic83GitHub** [comment] 2017-11-22 18:33
#MrCK1 Do you know where I can find more older build than 1.5dev 1223?

**Comment by atomic83GitHub** [comment] 2017-11-23 05:49
1.5dev 790 have the issue, so it was introduced between 650 and 790.

**Comment by MrCK1** [comment] 2017-11-23 05:51
Can you narrow it down further then?

**Comment by atomic83GitHub** [comment] 2017-11-23 17:53
Sorry but I can't do any further without your help, the only version I can found is 1.5dev 786 wich have the issue so it is between 650 and 786.
Have you any build under 786 and after 650?

**Comment by turtleli** [comment] 2017-11-23 20:47
v1.5.0-dev build list at https://gist.github.com/turtleli/a7de466bdf0aac4d028be5fa82a31de2 (It should be correct, but I don't guarantee this).

**Comment by atomic83GitHub** [comment] 2017-11-23 21:17
Thanks! I will try this ASAP.

**Comment by atomic83GitHub** [comment] 2017-11-24 11:51
***I found the culprit build! It's the v1.5.0-dev-721-g265ea82.***

***Here it is***
https://drive.google.com/file/d/1PwGnlTDmSRGE7YoPnRYlimOgEJ2alruL/view?usp=sharing

**Comment by gregory38** [comment] 2017-11-24 13:55
@ssakash updated this code recently (maybe it is still on a pending PR). It would be nice to test it too.

**Comment by atomic83GitHub** [comment] 2017-11-24 14:16
I had test on it, still the bug.

**Comment by ssakash** [comment] 2017-11-24 14:28
Could you try testing by uncommenting the ``//#define ENABLE_ACCURATE_BUFFER_EMULATION`` line?

**Comment by atomic83GitHub** [comment] 2017-11-24 14:36
How can I enable Accurate Buffer?

**Comment by lightningterror** [comment] 2017-11-24 15:12
[GSdx32-SSE4.zip](https://github.com/PCSX2/pcsx2/files/1501999/GSdx32-SSE4.zip)

**Comment by atomic83GitHub** [comment] 2017-11-24 15:17
It don't solve the issue unfortunately.

**Comment by ssakash** [comment] 2017-11-24 15:18
I'll look into this issue later then.

**Comment by MrCK1** [comment] 2017-11-26 05:24
It would be worth looking into https://github.com/PCSX2/pcsx2/issues/1357 as well (in regards to flickering), but it was reported to be affected by a different build.

**Comment by gregory38** [comment] 2018-01-02 17:08
Hum, was the GS wrapping memory hack option tested ?

**Comment by atomic83GitHub** [comment] 2018-01-02 17:20
Yes but it does not change anything, still the regression.

**Comment by FlatOutPS2** [comment] 2018-01-06 14:50
There are 2 kinds of flickering here. One was introduced by https://github.com/PCSX2/pcsx2/commit/758cf2588817044110323d96042d543c4f606f2f
This flickering can be resolved by enabling the GS memory wrapping hack.

A different flickering(the regression PR is linked by @atomic83GitHub ) is caused by the menu background appearing instead of the FMV image.
This issue is triggered by m_TEX0.TBP0 being almost as large as MAX_BLOCKS and the max.y value ends up going from 1280 to 32. The entire 1280 size is then cleared, which reveals the menu background(this is always active behind the FMV) as only the reduced 32 size gets restored.

**Comment by ssakash** [comment] 2018-01-06 17:11
It's due to a bug in the load size saturation, the algorithm used for limiting the load value doesn't seem accurate. Also nice to see you after such a long time Flatout xD

**Comment by ssakash** [comment] 2018-02-06 12:37
@atomic83GitHub 

Could you recheck #2122? I just made some minor updates to it.

**Comment by FlatOutPS2** [comment] 2018-02-06 12:45
@ssakash There's no change to this issue.

**Closed** 2018-03-03 03:31 UTC
Labels: Plugin: GSdx, Regression
