### ISSUE TITLE
[Feature Request] add yadif2x or dxva2 deinterlacer

### ISSUE THREAD

**Issue by whatwwkd4496** [PCSX2/pcsx2#2671] opened 2018-11-03 17:32 UTC
its better than blend, bob and weave.

**Comment by mirh** [comment] 2018-11-03 18:29
De-interlacing for film is (and cannot) be the same of real-time software. 
I'd be surprised if somebody hadn't already come up with a "smarter" algorithm that somehow someway is better than the rude ones we use. But without actual other ideas here, I'd say this is duplicate of #1458

**Comment by mirh** [comment] 2018-11-04 17:37
TVs aren't using yadif either for the records. 
And dxva2, by its [strictest design](https://docs.microsoft.com/en-us/windows/desktop/medfound/dxva-video-processing#overview), only guarantees you.. bob. 

On the other hand, I guess like hooking into whatever custom deinterlacing algorithm driver ***might*** be offering (or leaving this kind of work up to the [display circuitry](https://forums.creativecow.net/thread/3/952892#952958) itself) wouldn't be bad at all. 

I'm not sure if that could easily play out with ps2 [mad usage](https://www.reddit.com/r/emulation/comments/92x56t/ps2_disabled_interlacing_cheats/) of buffers though. Guess like that could be the new title of this feature request..

At least allowing "passing through" of interlacing should be trivial instead, potentially falling back in what I was asking for #2059.

**Comment by whatwwkd4496** [comment] 2018-11-05 04:33
tvs are not emulating ps2 games too, for the record. 
and no gpu capable running pcsx2 games doing bob deinterlace by default.
yadif and HW GPU deinterlacing already got their own algorithm finalized so don't you worry about that.
since the age of pc dvd playback, GPUs got their own dedicated video processor, which oflloads decoding deinterlacing, scaling and post processing.
if it's too scary to implement, just make it optional. so it can be bypassed when not activated.
why are you giving me these retrograde links and docs, have some real life modern experience.

**Comment by whatwwkd4496** [comment] 2018-11-08 13:53
why ever commented on the issue you have no knowledge and the skill to do it.

**Comment by whatwwkd4496** [comment] 2018-11-08 13:53
don't reply if it's not about the issue.

**Comment by MrCK1** [comment] 2018-11-08 14:01
To be honest you're coming off as a bit entitled.

There's no minimum amount of experience or qualifications required to contribute to an *open-source* project here, nor are we in a rush.

People aren't always right, but that doesn't mean you should criticize them for trying to propose ideas if they're wrong. What @mirh posted above is still relevant to the issue here.

**Comment by whatwwkd4496** [comment] 2018-11-09 00:19
it's as relevant to anything pcsx2

**Comment by bositman** [comment] 2018-11-09 11:22
You won't get far with that attitude and trash talk. You are here REQUESTING something, while providing no help whatsoever how what you request could be implemented or without any coding knowledge of how this could work on PCSX2. So stop the smart talk and start being helpful, or we can just ignore you and be done with it.

**Comment by sirdanielk** [comment] 2018-11-10 13:55
I doubt its possible to use dxva2 deinterlacing outside video decoding chain. According to MS docs https://docs.microsoft.com/en-us/windows/desktop/medfound/dxva-video-processing#creating-a-video-processing-device
> Before using DXVA video processing, the application must create a video processing device. 
So neither dxva deinterlacing nor scaling in emulator.
Whats more, do not forget pscx2 is a low level emulator which is recreating console internals in digital world of programming as it was in real life. This means - injecting additional, processing between console components would be really hard if not possible. The only place i would see yadif is at FMV decoding, and ONLY then, if that decoding would be managed by ffmpeg libraries hooked somehow in pcsx2.
Lately, i saw a thread about progress frames enabling by crc so no deinterlacing would be involved at all, that is a nice solution.

**Comment by mirh** [comment] 2018-11-11 02:33
Which would be the first link I provided. 
OTOH it's not entirely wrong to give a check to hardware capabilities.

[Nvidia's purevideo](https://web.archive.org/web/20160608064715/https://forum.doom9.org/showthread.php?t=172191) beats yadif tbh. ~~And we are talking about the video decoding block they have been shipping [since 2004](https://www.anandtech.com/show/1573/4) here, not some [GPGPU](https://macsphere.mcmaster.ca/bitstream/11375/9394/1/fulltext.pdf) [shenanigan](http://sam.cs.lth.se/ExjobGetFile?id=510).~~
Ok, turns out they used CUVID there, still. 

Having ffmpeg read data inside emulation is total insanity though, if any this whatever thing should work directly with pcsx2 framebuffer (again, if even doable to begin with). 

Then, [dxva interop](https://docs.microsoft.com/en-us/windows/desktop/direct3darticles/surface-sharing-between-windows-graphics-apis) should be possible with d3d ex apis actually. 
In addition to that, there's also [MFT](https://docs.microsoft.com/en-us/windows/desktop/medfound/video-processor-mft) (even though [nobody](https://stackoverflow.com/questions/35040983/video-processor-mft-and-deinterlacing) seems to [understand](https://stackoverflow.com/questions/35099078/de-interlacing-with-mediafoundation) how) and [D3D11VA](https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/ne-d3d11-d3d11_video_processor_processor_caps), all of which should sport the "devices" provided by the gpu driver too. 
I can see `VectorAdaptiveDevice_AMD`, `MotionAdaptiveDevice_AMD` and `AdaptiveDevice_AMD` for example here in dxva checker. 

Last but not least there are [proprietary](https://github.com/intel/gstreamer-media-SDK/commit/9ff71ba3bd01fe99a3060111896de33f3424ed60) [sdks](http://developer.amd.com/wordpress/media/2013/11/MediaSDK_User_Guide_1_1_Beta.pdf#page=27)... 
but long story short it seems wrong for pcsx2 to experiment with any of this, considering all the other priorities.

**Comment by avih** [comment] 2018-11-11 06:09
@mirh please stop. It's a valid feature request to want better deinterlacing. Whether it's yadif or a system interface or a shader or anything else is implementation details. No point in going on about it. If someone wants to and can implement/integrate it reasonably, no one would object.

**Comment by lightningterror** [comment] 2022-05-10 10:24
Closing, trivial.

**Closed by lightningterror** 2022-05-10 10:24 UTC
Labels: Enhancement / Feature Request
