### ISSUE TITLE
Power Drome Z Buffer Clear

### ISSUE THREAD

**Issue by belldandu** [PCSX2/pcsx2#473] opened 2015-03-12 15:14 UTC
http://forums.pcsx2.net/Thread-Bug-Report-Power-Drome-NTSC-U-SLUS-20978
http://forums.pcsx2.net/Thread-GSdx?page=474 
http://forums.pcsx2.net/Thread-Power-Drome-SLUS-20978-U

**Comment by refractionpcsx2** [comment] 2015-06-02 11:31
Can you retry with the latest git version in opengl with accurate_colclip=1 in the ini file please?

**Comment by kamijoutouma** [comment] 2015-06-02 23:25
Sure i'll do it when I get home

**Comment by kamijoutouma** [comment] 2015-06-04 07:31
which ini file @refractionpcsx2

**Comment by refractionpcsx2** [comment] 2015-06-04 09:02
yeh the gsdx.ini

as long as you used openGL it would take effect

**Comment by kamijoutouma** [comment] 2015-06-04 09:06
yeah i tried that with the one made 49? minutes ago nothing changed the issue still occurs even when using openGL @refractionpcsx2

**Comment by refractionpcsx2** [comment] 2015-06-04 09:07
ok thanks for testing, can you provide a GS Dump?

**Comment by kamijoutouma** [comment] 2015-06-04 09:08
how do i do that? @refractionpcsx2

**Comment by refractionpcsx2** [comment] 2015-06-04 09:11
When you're on the scene with the problem, hold down shift+F8 for a couple of seconds, it will then put a BMP file showing the error and a .gs file in your "snaps" folder. 7zip them and upload them somewhere :)

**Comment by kamijoutouma** [comment] 2015-06-04 09:21
ah here you go https://www.dropbox.com/s/axwz6ll5ntcxma4/snaps.7z?dl=0

**Comment by refractionpcsx2** [comment] 2015-06-04 09:41
Thanks :) You wanna add it to your list @gregory38 ? :)

**Comment by gregory38** [comment] 2015-06-04 16:49
Well it could be EE/VU bug too. So I won't look into it soon.

**Comment by ssakash** [comment] 2015-06-04 17:19
@kamijoutouma

Did zerogs have this problem ?

**Comment by kamijoutouma** [comment] 2015-06-04 23:41
This question was asked before in one of the threads earlier and the answer was yes.
Also there was some extra info that about 25% of the bottom part pf the screen was all black all the time in zerogs as well.
@ssakash

**Comment by karasuhebi** [comment] 2015-06-07 19:15
Just to clear something up, just because ZeroGS also has the issue doesn't necessarily mean it's not a GS issue, right?

**Comment by MrCK1** [comment] 2017-11-04 01:01
This isn't valid so I'm closing it. Either way it's technically playable according to Dabore in the forums (from Sept. 2015):

> the last time i tried... it worked with a daily git version from the buildbot. you gotta use the opengl renderer and enable the HW depth option. it had lil glitches in the menus but the races worked. Smile

**Comment by ssakash** [comment] 2017-11-08 07:49
@MrCK1 

``Invalid`` label is for cases where the issue was never present in any revisions. In this case, this issue seems to be present in an [older version of PCSX2](https://forums.pcsx2.net/Thread-Power-Drome-SLUS-20978-U?pid=433024#pid433024), so it's not invalid technically. For issues which were present before in an older version and not present anymore, don't use an invalid label.

Also I'd prefer if tests are done on latest development builds before closing the issues, who knows? A regression might've occured after the time Dabore did his test.

**Comment by tadanokojin** [comment] 2020-01-27 14:28
I have discovered the cause of the bug. It's in fact a gsdx bug (and likely ZeroGS too).
This game clears depth by setting FBP = ZBP and the FRAME psm = ZBUF psm and drawing sprites 32 pixels wide and 32 pixels apart from each other. This is confirmed to work on real hw.

It works because if you divide the page in half the left side of the page and the right side of the page will address different blocks due to z formats and color formats swizzling.

However, since the game uses z24 for the frame psm there was a detail I was missing.
In the event that the a z psm is specified for FRAME the GS will internally use a color format for depth. This was also confirmed to be the case via hw test.

Thanks to efforts by water111 and refraction, I was able to fix this bug in Dobiestation.
See https://github.com/PSI-Rockin/DobieStation/pull/273

**Closed** 2022-02-27 15:22 UTC
Labels: Bug, GS, GS: Depth
