### ISSUE TITLE
Driving Emotion Type-S - severe problems

### ISSUE THREAD

**Issue by FMecha** [PCSX2/pcsx2#3694] opened 2020-09-14 00:44 UTC
***PCSX2 version:***
pcsx2-v1.7.0-dev-233-g6229b204f-windows-x86

***PCSX2 options:***
Mostly default with Safest speedhack and MTVU

***Plugins used:***
GSdx32-AVX2 1.1.0 (Direct3D 11, mostly default settings)
(all other plugins are defaults))

***Description of the issue:***
This game's problems are already well-known that it's marked only in-game, but I've reporting it here for documentation purposes:

- Using Hardware mode will lead to corrupted rainbows on the top of the race screen. [GS Dump](https://github.com/PCSX2/pcsx2/files/5215489/DET-S.GS.Dump.zip)
- Urban Highway and Provence have severe physics problems - this prevents you from racing in Urban Highway as the game disqualifies you at 3 countdown due to the player being out of bounds (just watch the attract demo to see how it happens) while Provence's physics fail after one or two turns. (Suzuka East works fine though - I haven't tried other courses since they're locked)
![gsdx_20200914071937](https://user-images.githubusercontent.com/68824023/93032649-ebb2a900-f65c-11ea-9dd0-90857fc661e3.png)
![gsdx_20200914073652](https://user-images.githubusercontent.com/68824023/93032763-6b407800-f65d-11ea-8a9f-956d6618156c.png)
![gsdx_20200914072451](https://user-images.githubusercontent.com/68824023/93032766-6da2d200-f65d-11ea-8c08-4c2a34ab1e1d.png)
- Loading West Coast will cause the game to return to BIOS/browser, with the following console log (there's also failures to load course data files? every track suffer from this but only West Coast causes a reset):
```
can't open file -> data/monaco/monaco.l01 [0]
file size 32904
file size 2060
file size 292
file size 24676
file size 56
file size 140
file size 518
file size 16228
file size 152
file size 128
infinity light info.
[0] -0.0e-18 -0.0e+20 0
lens flara info.
[0] 0.0e+1 0 0.0e-18
wall fname [monaco.wal]
file size 2008
file size 461608
### talloc_info addr:1f8f300 size:70c00
tex num 50
tex 128 64
### talloc_info free
file size 1119656
### talloc_info addr:1eee880 size:111680
tex num 218
tex 64 64
### talloc_info free
file size 3452552
### talloc_info addr:1cb4f80 size:34af80
tex num 224
138 100
169 100
mipmap start
mipmap id 1  level 0
mipmap id 1  level 1
mipmap id 1  level 2
mipmap id 2  level 0
mipmap id 2  level 1
mipmap id 2  level 2
mipmap end
### talloc_info free
file size 5603772
### talloc_info addr:1aa7c80 size:558280
EMB Version [0]
obj num 2782
2782
chk mater num.
mater num 2453
envmap 6
### talloc_info free
complete.
end course init [7219 1894]
file size 2777
file size 744
file size 2418
file size 5124
can't open file -> data/replay.lf [0]
file size 551232
### talloc_info addr:1f79500 size:86a00
file size 2464
### talloc_info free
can't open file -> data/start.lf [0]
file size 36032
### talloc_info addr:1ff7180 size:8d80
# Restart.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize User Memory ...
# Initialize Scratch Pad ...
# Restart Done.
```

***How to reproduce the issue:***
Load any race at one of the mentioned tracks.

***PC specifications:***
Acer Aspire A315-55G (Intel Core i5-1021U / NVIDIA GeForce MX230 / 8 GB RAM / Windows 10 2004 [10.0.19041.508] 64-bit)

**Comment by MrCK1** [comment] 2020-09-14 00:47
Which region of the game is this? NTSC or PAL?

**Comment by FMecha** [comment] 2020-09-14 00:52
> Which region of the game is this? NTSC or PAL?
NTSC (SLUS-20113)

**Comment by MrCK1** [comment] 2020-09-14 00:53
Thanks, we already have an idea what the issue is.

**Comment by refractionpcsx2** [comment] 2020-10-26 08:56
The physics and loading problems should be fixed once #3864 is merged, the hardware problems with the garbage on the screen still remain however

**Comment by tadanokojin** [comment] 2020-10-29 09:44
Problem with garbage is a texture cache issue. It needs texture in rt but current implementation isn't good. #3479 might help but it's still WIP.

**Comment by refractionpcsx2** [comment] 2020-10-29 09:49
#3479 does indeed improve it, but it's not perfect, there looks like there's "dirt" on the screen, which aren't there in SW mode
![image](https://user-images.githubusercontent.com/6278726/97552302-00a88900-19cc-11eb-9ef7-ddfd0730b07f.png)

**Comment by refractionpcsx2** [comment] 2022-05-09 18:20
This is resolved

![image](https://user-images.githubusercontent.com/6278726/167472528-19f12bf8-7568-4718-a906-7ba96ee9572d.png)

**Closed by refractionpcsx2** 2022-05-09 18:20 UTC
Labels: Bug, GS, GS: Hardware, GS: Texture Cache
