### ISSUE TITLE
[BUG]: Impossible to properly bind force feedback with USB Wheel under Qt

### ISSUE THREAD

**Issue by oxyacetylene** [PCSX2/pcsx2#8646] opened 2023-04-12 06:26 UTC
### Describe the Bug

There seems to be no proper way to bind force feedback for a racing wheel under the Qt UI. 

### Reproduction Steps

1. Plug in Logitech G29 Racing Wheel with Logitech Gaming Software running
2. Start PCSX2
3. Attempt to bind buttons for Driving Force Pro wheel (successful)
4. Attempt to bind force feedback - PCSX2 asks for input
5. Turn the wheel
6. Force Feedback UI element returns SDL-0 and nothing else
7. Force Feedback does not function in Gran Turismo 4

### Expected Behavior

It would probably be best to have a dropdown box in order to manually select your Force Feedback option due to the ambiguity on how you're expected to bind something like this

### PCSX2 Revision

v1.7.4370 (Qt)

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment] 2023-04-15 03:58
Duplicate of #8612.

**Closed by stenzek** 2023-04-15 03:58 UTC
Labels: Bug, USB
