### ISSUE TITLE
[BUG]: PCSX 2 doesn't start because of vulkan-1.dll

### ISSUE THREAD

**Issue by rashvash** [PCSX2/pcsx2#5941] opened 2022-04-23 11:41 UTC
### Describe the Bug

PCSX 2 doesn't start because of vulkan-1.dll giving the message (see screenshot). happens BOTH in Win 10 x64 and Win 7 x64.

Addition: Well, guys, it seems this is where I stop testing PSCX 2. Today after I reported the vulkan-1.dll bug in Discord. Stenzek (who is very resentful and sensitive guy as we know from the story with Duckstation and Retroarch with childish grudges of Stenzek at some guys (I'm not among them) answered with loads of foul language and insults to my adress and instead of helping to solve the problem and of looking into it he simply band me in both PSCX 2 and Duckstation discord channels (even though I didn't write anything on Duckskstaion discord channel today) . After I critized hos work a little (and vulkan-1.dll problem appeared only in 1.7 build after vulkan implementation, which is actually Stenzek's work) he got furios again and ban me to cover his mistakes.(yeah that's how he solves the problems usually). Maybe because guys like Stenzek solve porblems and bugs of PSCX 2 like that we still got 1,15 % perfect and many games unplayable, partially playable, partially playable with millions of fixed games after 20 years of development. I can only add today I also tested Duckstation a lot. And send lotsa bug reports to DS discord channel. With screenshots and detailed descriptions of bugs and none of them were ever solved. I asked for Konami justifier support in Duckstation YEARS ago. Stenzek promised to implement it. As you've already guessed it was never done. I'm not amongst the guys who mocked him in this retroacrh-DS situation (though I think his grudges are childish and he constantly acts like a child). I know he's very resentful and nervous guy. Today he started insulting me out of blue and ended by banning me out of blue.

### Reproduction Steps

0.Kick lazy and  non-able developers always saying it's not a bug it's a feature
1.use videocard w/o vulkan support.
2.use devbuilds after Stenzek's vulkan implementation
3.run PCSX 2.exe
4,Get the error message (see screenshot)

### Expected Behavior

1.Run PCSX 2 normally on videocards w/o vulkan support and then let users to select the renderer
2.Fix the problem like bring it to the point 1 above or make verions w/o Stenzek's shitty implemented Vulkan.

### PCSX2 Revision

1.7.2647

### Operating System

Windows 10 (64bit)

**Comment by lightningterror** [comment] 2022-04-23 11:44
Duplicate of #5940

**Closed by lightningterror** 2022-04-23 11:44 UTC
Labels: Duplicate
