### ISSUE TITLE
Onimusha 3 Demon Siege

### ISSUE THREAD

**Issue by dml360** [PCSX2/pcsx2#7106] opened 2022-09-30 16:19 UTC
### Describe the Bug

Using the version PCSX2 Nigtly v1.7.3344
when increasing the internal resolution, these stripes appear next to the image as in the photo (Vulkan OpenGL Direct3D)
![Pcsx2-v1 7 3344-windows-64bit-avx2-qt Screenshot 2022 09 30 - 13 00 07 73](https://user-images.githubusercontent.com/35852102/193311766-90f2127b-1255-4d59-a1a3-5a7e1c0daf2f.png)

when activating "half pixel offset" in (Normal Vertex), this error is corrected, however it breaks the shadows as in the photos below

![Pcsx2-v1 7 3344-windows-64bit-avx2-qt Screenshot 2022 09 30 - 13 03 25 58](https://user-images.githubusercontent.com/35852102/193312298-56fde281-a468-4252-b1b1-25e4796830cc.png)

![Pcsx2-v1 7 3344-windows-64bit-avx2-qt Screenshot 2022 09 30 - 13 03 29 98](https://user-images.githubusercontent.com/35852102/193312336-6edee977-c21f-4925-8299-a109f5849742.png)

these bugs did not occur in the version PCSX2 v1.7.0- dev 472

SPECS

i5 8400
GTX 1060 6gb
16gb 2666
W10

### Reproduction Steps

In any configuration as described above, errors occur

### PCSX2 Revision

PCSX2 Nigtly v1.7.3344

### Operating System

Windows 10 (64bit)

### CPU

i5 8400

### GPU

GTX 1060

**Comment by refractionpcsx2** [comment] 2022-09-30 17:44
Duplicate of #5851

We're tracking this there.

**Closed by refractionpcsx2** 2022-09-30 17:44 UTC
Labels: Bug
