### ISSUE TITLE
[BUG]: WASAPI & USB Settings Not configurable for proper use of USB settings IE: Headsets

### ISSUE THREAD

**Issue by BOBCAMO** [PCSX2/pcsx2#10727] opened 2024-01-26 15:10 UTC
### Describe the Bug

WASAPI Not configurable for proper use of USB settings for Headset and Mic use for in-game. at least for Mortal Kombat Deception and Armageddon, and Metal Gear Solid 3: Subsistence Online(AKA MGO1), the old way of configuring the USB settings seems to be about the only way to get the mic's and headsets to work online. there is people who actually do want to be able to use this. rather this be on a full and stable release instead of a fork or old version. 
this seems to almost want to work in the newest versions but when selecting a headset, there is a button for "Settings" but it sometimes grey's out or nothing happens when clicking on it. screenshot for this will be below.
![controller settings](https://github.com/PCSX2/pcsx2/assets/27203793/b35e8cd2-fa6a-486a-82dd-7a6fca726465)

### Reproduction Steps

just try to use any aspect of the USB mic or headset. if there is push-to-talk, the mic lights up but no audio. not hard to test. setup headset, go online, there is no mic audio.
this was tested with 3 different people, all of which the headsets and mic's work online for MKA with an older or forked versions of the emulator. many variations of USB headset settings were tried also.

### Expected Behavior

i don't really care how it should work, but i'll provide a picture of an older version the way it worked there.
but for ease of use, just being able to select "USB Headset" then Selecting the Mic and Headset respectively should do.
but on these older versions i feel these are also bugged as most of them need BOTH port's 1 & 2 need to be occupied for the headset to usually work this way. which makes it hard to use both keyboard AND headset as some games you can only use a headset in certain portions of the game. MKA for example, in a raceroom with push to talk, or in a fight which is open mic. but in the lobby, a keyboard is a must.
 
 
![Screenshot 2024-01-26 094315](https://github.com/PCSX2/pcsx2/assets/27203793/f4ccf69a-dde4-4179-b2c7-8dbad547db90)

### PCSX2 Revision

v1.7.5519

### Operating System

Windows 11

### CPU

Ryzen 7 5800x3D

### GPU

RTX 3070ti

### GS Settings

tested on default settings as a precaution.

### Emulation Settings

tested on default settings as a precaution.

### GS Window Screenshots

tested on default settings as a precaution.

### Logs & Dumps

no crashes.

**Comment by stenzek** [comment] 2024-01-26 15:46
Duplicate of #8316. Nobody has been interested in looking into it so far.

WASAPI isn't a thing, the USB code is cross-platform now.

**Closed by stenzek** 2024-01-26 15:46 UTC
Labels: Bug

**Comment by BOBCAMO** [comment] 2024-01-26 15:53
> Duplicate of #8316. Nobody has been interested in looking into it so far.
> 
> WASAPI isn't a thing, the USB code is cross-platform now.

wasn't sure if it was, just pointed it out as that's the only thing that works from anything old to new. hence the screenshots showing it is a thing and was. i don't know any of the coding, just what showed on the emulators as i keep older versions of PCSX2 and a couple of forks for testing. but glad there is another post that's still open, did search, must have used the wrong keywords so it didn't show.
