### ISSUE TITLE
OpenGL regression in Final Fantasy X: Wakka's Element Reels overdrive shows a black screen

### ISSUE THREAD

**Issue by karasuhebi** [PCSX2/pcsx2#995] opened 2015-11-23 09:00 UTC
I found a regression in GSdx's OpenGL renderer:
![kftsyg5](https://cloud.githubusercontent.com/assets/6857825/11332671/87ec2e9a-9195-11e5-8b1f-be52b176c164.png)

It's supposed to look like this:
![lel](http://i.imgur.com/0PoShrq.png)

Sadly the problem is intermittent but thankfully it's very easy to replicate so it doesn't take long to find out if a given build has the issue or not. From some testing @Sarania and I performed, it seems that only PCs with AMD GPUs can replicate the issue, although we managed to get the error to show up on his PC (NVIDIA GPU) by me sending him a saved state that was created while the issue was occurring. Interestingly enough, even if he loaded the saved state using the D3D11 renderer it still occurred. O_O

I managed to bisect the issue quite a bit and found that the regression occurred somewhere between builds 157 and 170. I couldn't track down exactly what commit caused it since the buildbot has no builds in between those two. Build 157 was built on April 23, 2015 and the commit corresponding to it is 258b734. Build 170 was built on April 25, 2015 and the commit corresponding to it is f0182f9. The regression happened in one of the commits from April 24:
https://github.com/PCSX2/pcsx2/commits?page=38

P.S. I would love for someone on Linux to try to replicate this as it seems the regression occurred around the time DATe was being implemented but the Windows GUI still didn't have an option to turn it on so I had no way of testing if that made a difference or not.

P.P.S. Build 170 has some crazy texture flickering going on that kinda looks like the old ZeroGS screenshot I provided for #983. I first saw the issue on build 182 so I would assume the issue goes from 170-182 and possibly even further than that. Don't know if that's relevant? I would assume it isn't. Just found it interesting and wanted to mention it.

**Comment by karasuhebi** [comment] 2015-11-23 09:12
@gregory38 Would a GS dump help?

**Comment by gregory38** [comment] 2015-11-23 15:07
Nah dump is useless. @Sarania reproduction is bad. GSdx just reuse a badly computed texture. OMG I did so much commits :(
Do you have the issue if you enable accurate date?

**Comment by gregory38** [comment] 2015-11-23 15:08
Is your driver opengl 4.5 capable?

**Comment by Sarania** [comment] 2015-11-23 20:26
My reproduction wasn't meant to be a reproduction. I tried for about 30 minutes to reproduce it normally, including using his memory card save and I could not. The save state thing was only a one off to determine if it was even coming from PCSX2 and my rationale is since it was saved in the state, it is.

**Comment by karasuhebi** [comment] 2015-11-23 20:45
@gregory38 It's not that many commits, just 12. :package: 

Yes, the problem happens even with Accurate DATe on.

About my driver, I believe so. GPU-Z doesn't give tell me which OpenGL version is supported but Wikipedia says my card is OpenGL 4.5 capable. I also get this from PCSX2's console log:
3.x GL context successfully created
OpenGL information. GPU: AMD Radeon HD 7900 Series. Vendor: ATI Technologies Inc.. Driver: Core Profile Forward-Compatible Context 15.200.1062.1003
Buggy driver detected, GL_ARB_separate_shader_objects will be disabled

INFO: GL_EXT_texture_filter_anisotropic is available
INFO: GL_ARB_gpu_shader5 is available
INFO: GL_ARB_draw_buffers_blend is available
INFO: GL_ARB_separate_shader_objects is NOT SUPPORTED
INFO: GL_ARB_shader_image_load_store is available
INFO: GL_ARB_copy_image is available
INFO: GL_ARB_buffer_storage is available
INFO: GL_ARB_clear_texture is available
INFO: GL_ARB_clip_control is available
INFO: GL_ARB_direct_state_access is available
INFO: GL_ARB_texture_barrier is available

**Comment by gregory38** [comment] 2015-11-23 20:57
Edit the ini file and add those 2 options.
```
override_GL_ARB_buffer_storage = 0
override_GL_ARB_texture_barrier = 0
```
If no improvement, get a dev (not debug, neither release) build somewhere. It will generate a `GSdx_opengl_debug.txt` log file.

**Comment by karasuhebi** [comment] 2015-11-24 00:53
I added the lines to GSdx.ini and confirmed through the console log that they were taking effect. The bug still presented itself though. Where could I get a dev build? @Sarania, could you build me one?

**Comment by Sarania** [comment] 2015-11-24 01:56
If you just need the main executable I can. If you need GSdx in devel too then I can't per this thread: 
http://forums.pcsx2.net/Thread-Can-t-install-DirectX-SDK

Here is the main PCSX2 if that's it: https://www.dropbox.com/s/bn2wsfgdn0eulcj/pcsx2dev.7z?dl=0

But I'd wait on @gregory38 to see if GSdx needs to be devel too first.

**Comment by Nobbs66** [comment] 2015-11-24 18:17
if it needs it, then let me know. I'll compile it if I have time.

**Comment by karasuhebi** [comment] 2015-11-24 18:18
Thanks, I appreciate that @Nobbs66. If you have time, could you try reproing my issue? You have an AMD GPU. :)

**Comment by Nobbs66** [comment] 2015-11-24 18:20
what issue again?

**Comment by Sarania** [comment] 2015-11-24 18:21
@Nobbs66 lol read the OP of this issue scrub.

**Comment by karasuhebi** [comment] 2015-11-24 18:23
@Nobbs66 Really? lol

Just in case: Wakka's Element Reels overdrive gets me a black background screen on OpenGL. It doesn't happen all the time but it happens often enough that you can reproduce it pretty quickly. If you want I can send you a memory card file where you're about to walk into a boss fight and Wakka has his overdrive gauge full.

**Comment by Nobbs66** [comment] 2015-11-24 18:40
oh...

**Comment by karasuhebi** [comment] 2015-11-25 03:08
I don't know if this is related or not but it certainly looks like it is. Using the OpenGL renderer when you enter a random encounter, the screen looks like this:
![lel](http://i.imgur.com/dAU0PiV.png)

Using the Direct3D11 renderer, the screen looks like this when you go into a random encounter:
![lel](http://i.imgur.com/nTYSvPS.png)

**Comment by Sarania** [comment] 2015-11-25 18:10
@karasuhebi I definitely think it's related as both of those effects use the "Take a screenshot of the scene" and use that "screenshot" inside the effect method.

**Comment by karasuhebi** [comment] 2015-11-25 18:12
@Sarania Yeah, that's exactly what I was thinking. :)

@gregory38 So do I just need a devel pcsx2.exe or do I need a devel GSdx DLL as well?

**Comment by gregory38** [comment] 2015-11-25 18:28
GSDX ofc

**Comment by karasuhebi** [comment] 2015-11-25 18:31
OK thanks. I'll see if @Nobbs66 can make me one and then I'll return with feedback.

**Comment by karasuhebi** [comment] 2015-11-25 18:58
@Nobbs66 was kind enough to provide a devel version of the latest GSdx but it's not making a log file. Where should I be looking for it?

**Comment by Sarania** [comment] 2015-12-04 20:30
@gregory38 Can you answer @karasuhebi question so this can get more testing please :smile:

**Comment by ssakash** [comment] 2015-12-04 20:43
I think you need to set `debug_opengl = 1` on INI file. (probably ?)

**Comment by karasuhebi** [comment] 2015-12-04 20:43
I actually got on IRC and asked him about it that same day. He told me to add debug_opengl = 1 and debug_glsl_shader = 1 to my GSdx.ini to get GSdx_opengl_debug.txt, but that didn't work. I told @Nobbs66 about it and upon seeing the two lines @gregory38 asked me to add to GSdx.ini, he suggested I try a debug build instead of a devel build. Haven't gotten around to doing that but @Sarania just suggested I try a devel PCSX2.exe along with the devel GSdx dll, so I'm about to try that.

**Comment by Sarania** [comment] 2015-12-04 20:44
He tried that, gregory told him to in IRC.

But he was only using a devel GSdx and not main EXE, I told him he might need both.

Woops Ninja'd

**Comment by gregory38** [comment] 2015-12-04 20:46
Normally it only depends on GSdx. However maybe debug info wasn't enabled in this old build (remember that openGL was done on linux and is quite recent). However if you can find the bad commit, it might help.

**Comment by karasuhebi** [comment] 2016-09-23 04:30
I don't think I can find the bad commit, I know basically nothing about coding. I'm sorry, I narrowed it down as much as I could in the OP. :(

**Comment by FlatOutPS2** [comment] 2016-09-23 09:42
So this issue still happens with the latest git build?

**Comment by gregory38** [comment] 2016-11-09 18:35
@karasuhebi what is the status of latest build ? Is the bug still the overdrive or the encounter ?

**Comment by FlatOutPS2** [comment] 2017-02-15 13:02
I tried reproducing this issue, but I could not fully reproduce it. I tried the latest current git build, v1.4.0, several 2015 1.3.1 builds and the 170 build mentioned in the OP. The crazy texture flickering issue in build 170 was there, and it sometimes caused the reel background and the random encounter break to be displayed incorrectly, but it was never completely black. I tried build 199 after 170 and the flickering was gone, and the reel background and the random encounter backgrounds always worked correctly in that and all the subsequent builds I tried.

**Comment by karasuhebi** [comment] 2017-03-21 05:10
Uh...holy shit. What happened to OGL in the latest dev build? O_O

https://www.youtube.com/watch?v=BsQnwpIL-wk

**Comment by DisorderIy** [comment] 2017-03-21 08:40
@karasuhebi This is an issue with the AMD drivers.

**Comment by MrCK1** [comment] 2018-04-03 16:47
Can somebody else try and reproduce this on latest git? If not, we can close this.

**Comment by lightningterror** [comment] 2018-04-13 15:07
@karasuhebi @Sarania is this still an issue ?

**Comment by MrCK1** [comment] 2018-12-18 04:36
Are we still doing anything about this? @FlatOutPS2 @karasuhebi Anybody :P

**Comment by RedDevilus** [comment] 2021-10-03 19:03
Seems fine in latest master (upscaled or not), no idea how OP got this issue.

![image](https://user-images.githubusercontent.com/24227051/135767756-a9ff4e97-e724-4782-9e3b-c1701da7a38f.png)

![image](https://user-images.githubusercontent.com/24227051/135767739-da1810a2-361e-4c8e-948e-5955f45fef33.png)

**Comment by karasuhebi** [comment] 2021-10-04 01:53
I'll test again in a few days.

**Comment by refractionpcsx2** [comment] 2021-11-23 00:12
This looks like it's fine now then, so I'll close for now, of course if it isn't mention it, give us a GS dump and I'll reopen.

**Closed by refractionpcsx2** 2021-11-23 00:12 UTC
Labels: GS: Hardware, Regression, Cannot Reproduce
