### ISSUE TITLE
[BUG]: NVIDIA is not used when launching with prime-run

### ISSUE THREAD

**Issue by michelesr** [PCSX2/pcsx2#5247] opened 2022-01-01 16:50 UTC
### Describe the Bug

On Linux laptops with NVIDIA Optimus, prime-run is the recommended way to run graphical applications on the NVIDIA card running proprietary drivers.  

This works nicely with other OpenGL applications:

```
$ cat $(which prime-run)
#!/bin/bash
__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"

$ prime-run glxinfo | grep -i nvidia
client glx vendor string: NVIDIA Corporation
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 495.46
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL version string: 4.6.0 NVIDIA 495.46
OpenGL shading language version string: 4.60 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 495.46
```

When running `prime-run PCSX2` and starting the emulation, the Intel iGPU is used instead.

### Reproduction Steps

- run `prime-run PCSX2`
- start emulation

### Expected Behavior

The NVIDIA dGPU is used instead of the Intel iGPU.

### PCSX2 Revision

v1.7.2101 and master (b6dafff52464c343ce4a53d54d793e7cbec0696d)

### Operating System

Linux (64bit)

### Distribution

Arch Linux

**Comment by kenshen112** [comment] 2022-01-01 16:58
Are you using a specific package?

**Comment by michelesr** [comment] 2022-01-01 17:03
> Are you using a specific package?

Just the latest package from Arch Linux community repository:

```
Name            : pcsx2
Version         : 1.7.2101-1
Description     : A Sony PlayStation 2 emulator
Architecture    : x86_64
URL             : https://www.pcsx2.net
Licenses        : GPL2  GPL3  LGPL2.1  LGPL3
Groups          : None
Provides        : None
Depends On      : gcc-libs  glibc  libaio  libasound.so  libcap  libfmt.so=8-64  libfreetype.so=6-64  libgdk-3.so=0-64  libgdk_pixbuf-2.0.so=0-64  libgio-2.0.so=0-64  libGLEW.so  libgl  libglib-2.0.so=0-64
                  libgobject-2.0.so=0-64  libgtk-3.so=0-64  libharfbuzz.so  libpcap.so=1-64  libpng  libportaudio.so=2-64  libpulse.so=0-64  libsamplerate.so=0-64  libudev.so=1-64  libx11  libxcb  libxml2
                  libxrandr  libyaml-cpp.so=0.7-64  sdl2  soundtouch  wxgtk3  wxgtk-common  xz  zlib
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 17.26 MiB
Packager        : Maxime Gauduin <alucryd@archlinux.org>
Build Date      : Mon 06 Dec 2021 08:55:18 AM GMT
Install Date    : Fri 31 Dec 2021 01:27:09 AM GMT
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : Signature
```

And the regular `linux` kernel package and nvidia proprietary drivers that are shipped on Arch Linux repos.

**Comment by kenshen112** [comment] 2022-01-01 18:06
Can you try with the AUR package? There's a few differences between them that might yield a different result

**Comment by michelesr** [comment] 2022-01-01 19:06
Nope:

```
PCSX2 Nightly - v1.7.2184 Compiled on Jan  1 2022
Savestate version: 0x9a2b0000

Host Machine Init:
	Operating System =  Arch Linux
	Physical RAM     =  15622 MB
	CPU name         =  Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Vendor/Model     =  GenuineIntel (stepping 0A)
	CPU speed        =  2.205 ghz (12 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 7ffafbbf
	x86EFlags        =  2c100800

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA
	Pcsx2 was compiled as 64-bits.

Installing POSIX SIGSEGV handler...
Reserving memory for recompilers...
HLE Host: Set 'host:' root path to: /

Patches: No CRC found, using 00000000 instead.
isoFile open ok: /home/michele/Games/ps2/Kingdom Hearts II (USA).iso
	Image type  = DVD
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (1936768 sectors)
Kbd Accelerator 'F11' is mapped to unknown command 'Sys_FreezeGS'
Current Renderer: OpenGL
EGL Version: 1.5
EGL Extensions: EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_CHROMIUM_sync_control EGL_EXT_buffer_age EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_EXT_swap_buffers_with_damage EGL_IMG_context_priority EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_KHR_swap_buffers_with_damage EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_NOK_texture_from_pixmap EGL_WL_bind_wayland_display 
Trying version 4.6 (Core)
Got version 4.6 (Core)
Created a OpenGL context
GL_VENDOR: Intel
GL_RENDERER: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
GL_VERSION: 4.6 (Core Profile) Mesa 21.3.2
GL_SHADING_LANGUAGE_VERSION: 4.60
1 program binary formats supported by driver
INFO: GL_ARB_sparse_texture is NOT SUPPORTED
INFO: GL_ARB_sparse_texture2 is NOT SUPPORTED
INFO: GL_ARB_gpu_shader5 is available
INFO: GL_ARB_shader_image_load_store is available
INFO: GL_ARB_clear_texture is available
INFO: GL_ARB_direct_state_access is available
INFO: GL_ARB_texture_barrier is available```

**Comment by kenshen112** [comment] 2022-01-01 19:43
To further isolate the issue. Does it work if you're running pcsx2 manually compiled?

**Comment by F0bes** [comment] 2022-01-01 20:18
Do you by chance have `optimus-manager`? I can reproduce the issue with it installed. That being said, running glxgears with prime-run fails under this scenario too.

Without `optimus-manager` I cannot reproduce the issue when running `prime-run pcsx2`

---- System info ----

```
[ty@ty-manjaro ~]$ uname -a
Linux ty-manjaro 5.4.164-1-MANJARO #1 SMP PREEMPT Wed Dec 8 09:53:07 UTC 2021 x86_64 GNU/Linux
```

```
[ty@ty-manjaro ~]$ nvidia-smi
Sat Jan  1 15:13:38 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 495.44       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
```

GL Init when executed with `pcsx2`
```
Created a OpenGL context
GL_VENDOR: Intel
GL_RENDERER: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
GL_VERSION: 4.6 (Core Profile) Mesa 21.2.5
GL_SHADING_LANGUAGE_VERSION: 4.60
```

GL Init when executed with `prime-run pcsx2`
```
Created a OpenGL context
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: Quadro T2000/PCIe/SSE2
GL_VERSION: 4.6.0 NVIDIA 495.44
GL_SHADING_LANGUAGE_VERSION: 4.60 NVIDIA
```

A workaround is to use `optimus-manager` and manually switch between dedicated and integrated. I have it configured to use my dGPU when plugged in and iGPU when not. Unfortunately it seems like you lose the ability to easily switch with `prime-run` however.

**Comment by michelesr** [comment] 2022-01-01 20:43
> Do you by chance have optimus-manager? 

No, I used nvidia-xrun in the past with PCSX2 and it was working fine, but `prime-run` seems more practical to me, expecially since I use Sway as main window manager, and do offloading to XWayland (but the problem can be reproduced with i3 on X too)

**Comment by michelesr** [comment] 2022-01-01 21:24
So, I built from source with:

```
./build.sh --use-system-yaml 
```

And then I run:

```
prime-run bin/PCSX2-linux.sh
```

But that didn't help

**Comment by michelesr** [comment] 2022-01-20 16:19
Btw, the new version with the Vulkan backend allows choosing the adapter, so I can select the NVIDIA card from the dropdown menu. So the issue is only related to the OpenGL backend. So far didn't have other issue using `prime-run` which other OpenGL apps so not sure why it's only happening for PCSX2.

**Comment by Mrlinkwii** [comment] 2022-10-13 18:48
is this still an issue on master

**Comment by michelesr** [comment] 2022-10-13 19:57
> is this still an issue on master

It still seems to be the case in v1.7.3398. 

Running nvidia-smi gives me no process running on the card with OpenGL (it does with Vulkan when the Nvidia adapter is selected)

How do I open the log in the new QT interface?

**Comment by JosephDFG** [comment] 2022-10-22 01:08
This appears to be version related.
With the AUR package I got the same issue, even while using `prime-run`
But with the appimage given on [their website](https://pcsx2.net/downloads/) `prime-run` uses the nvidia drivers just fine.
Not rlly a solution, but thought I'd let you know.

**Comment by kenshen112** [comment] 2022-10-22 01:11
I'll fix that this evening

**Comment by refractionpcsx2** [comment] 2022-10-22 01:12
if it's just the AUR, that's up to the packagers to fix (kenshen, i guess). Closing since our appimage apparently works.

**Closed by refractionpcsx2** 2022-10-22 01:12 UTC
Labels: Bug, OS: Linux

**Comment by pjagiello** [comment] 2023-02-10 12:42
... so it seems I encountered this in #8074, and prime-run does in fact pick the Intel card, and it does happen with the AppImage (as of release 4041).
