### ISSUE TITLE
[BUG]: Herdy Gerdy - Crashes and  graphical glitch in the map 

### ISSUE THREAD

**Issue by xiriby** [PCSX2/pcsx2#8815] opened 2023-05-09 19:54 UTC
### Describe the Bug

1. The setting hash cache options make the game crash
PCSX2 log just keep printing 

GS: Memory allocation failure.
Create texture failed: 0x887A0005
D3D12: Executing command buffer due to '

endlessly

 hash cache can't  be disabled since it causes the graphical issue

2. Map is in the wrong color 

### Reproduction Steps

1. Play on hardware mode and set the hash cache set to partial /full 
when using Directx12
Start a new game and after a few minutes the game crashes

2. Start a new game, talk to the boy and press yes, talk to the old lady, and press yes 

### Expected Behavior

1. Game doesn't crash
2. The map is shown correctly 

### PCSX2 Revision

1.7.4481

### Operating System

Windows 10 (64bit)

### CPU

I7-8700

### GPU

GTX 1060 6GB

### GS Settings

Any hardware rendering 

### Emulation Settings

Default

### GS Window Screenshots

HW:

![Herdy Gerdy_SLES-50751_20230509234335](https://github.com/PCSX2/pcsx2/assets/101547056/0cbc68ad-645c-4c5f-88c0-5a884308c624)

Sw:
![Herdy Gerdy_SLES-50751_20230509234337](https://github.com/PCSX2/pcsx2/assets/101547056/17a65d00-b67b-4253-99f1-415e0a6046e3)

HW hash cache is set to None:
![Herdy Gerdy_SLES-50751_20230509234153](https://github.com/PCSX2/pcsx2/assets/101547056/4ff85fca-b989-4bf1-8930-e0cbfbcb7bb0)

### Logs & Dumps

1. Crash dump
[emulog.txt](https://github.com/PCSX2/pcsx2/files/11436003/emulog.txt)

2. The map
[Herdy Gerdy_SLES-50751_20230509224656.zip](https://github.com/PCSX2/pcsx2/files/11435578/Herdy.Gerdy_SLES-50751_20230509224656.zip)

**Comment by xiriby** [comment] 2023-05-09 20:22
> Annoyingly I can't reproduce the glitch from your GS Dump, but you can fix the colour of the brown part by using high blending accuracy
> 

I didn't notice I wasn't  on Full Hash Cache fixes the issue so sorry my bad

**Comment by refractionpcsx2** [comment] 2023-05-09 20:24
Okay, but this may still be a bug, I'll ask the guy who wrote the hash cache stuff to see if he knows why it might break with it off.

**Comment by xiriby** [comment] 2023-05-09 20:25
> Okay, but this may still be a bug, I'll ask the guy who wrote the hash cache stuff to see if he knows why it might break with it off.

wait I remember Why I disabled this in the first place it makes the game crashes

**Comment by xiriby** [comment] 2023-05-09 20:45
> please, thanks. Though I think these are both symptoms of something not being right underneath that hash cache kinda covers up.

I updated my issue and added emulog

**Comment by mrtawsiti3** [comment] 2023-06-20 12:47
I have graphical glitches using Vulkan and SW or any renderer

[](https://ibb.co/CM8Tyy0)

**Comment by refractionpcsx2** [comment] 2023-06-20 12:53
> > please, thanks. Though I think these are both symptoms of something not being right underneath that hash cache kinda covers up.
> 
> I updated my issue and added emulog

[  117.3360] D3D12: Executing command buffer due to 'Couldn't allocate texture.'
[  117.3407] Create texture failed: 0x887A0005
[  117.3408] GS: Memory allocation failure.
[  117.3410] Create texture failed: 0x887A0005

This would suggest you've run out of VRAM, what is your upscaling set to? Can you try a lower value?

**Comment by mrtawsiti3** [comment] 2023-07-05 08:15
Tested with the latest build and game now gets stuck at the white screen after you pick up the boots

**Comment by lightningterror** [comment] 2024-11-23 00:21
I was unable to reproduce any crash with partial or full texture preloading on dx12. Closing assumed fixed, otherwise can be re opened.

**Closed by lightningterror** 2024-11-23 00:21 UTC
Labels: Bug, GS: Hardware
