### ISSUE TITLE
Warning on GLib2's GTimeVal deprecated declarations

### ISSUE THREAD

**Issue by rffontenelle** [PCSX2/pcsx2#3314] opened 2020-04-14 17:52 UTC
***PCSX2 version:***
1.5.0-20200408193126 - compiled on Apr 14 2020

***PCSX2 options:***
N/A

***Plugins used:***
N/A

***Description of the issue:***

GTimeVal is deprecated in favor of GDateTime since GLib 2.62 (see [API reference](https://developer.gnome.org/glib/stable/glib-Date-and-Time-Functions.html#GTimeVal)), outputing the following warning message:

```
In file included from /usr/include/gtk-2.0/gtk/gtk.h:126:
In file included from /usr/include/gtk-2.0/gtk/gtkmenutoolbutton.h:30:
In file included from /usr/include/gtk-2.0/gtk/gtktoolbutton.h:30:
In file included from /usr/include/gtk-2.0/gtk/gtktoolitem.h:31:
/usr/include/gtk-2.0/gtk/gtktooltips.h:73:3: warning: 'GTimeVal' is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
  GTimeVal last_popdown;
  ^
/usr/include/glib-2.0/glib/gtypes.h:545:35: note: 'GTimeVal' has been explicitly marked deprecated here
typedef struct _GTimeVal GTimeVal GLIB_DEPRECATED_TYPE_IN_2_62_FOR(GDateTime);
                                  ^
/usr/include/glib-2.0/glib/gversionmacros.h:909:49: note: expanded from macro 'GLIB_DEPRECATED_TYPE_IN_2_62_FOR'
# define GLIB_DEPRECATED_TYPE_IN_2_62_FOR(f)    GLIB_DEPRECATED_TYPE_FOR(f)
                                                ^
/usr/include/glib-2.0/glib/gmacros.h:1014:37: note: expanded from macro 'GLIB_DEPRECATED_TYPE_FOR'
#define GLIB_DEPRECATED_TYPE_FOR(f) G_DEPRECATED_FOR(f)
                                    ^
/usr/include/glib-2.0/glib/gmacros.h:950:44: note: expanded from macro 'G_DEPRECATED_FOR'
#define G_DEPRECATED_FOR(f) __attribute__((__deprecated__("Use '" #f "' instead")))
```

See full build log: 
[pcsx2-git-1.5.0.r3401.49e316e48-1-x86_64-build.log](https://github.com/PCSX2/pcsx2/files/4476715/pcsx2-git-1.5.0.r3401.49e316e48-1-x86_64-build.log)

***How to reproduce the issue:***
Build PCSX2 using glib>=2.62

In my case, I built the AUR package [pcsx2-git](aur.archlinux.org/packages/pcsx2-git/)

***Last known version to work:***
N/A

***PC specifications:***
Arch Linux (rolling, 64-bit), [glib2 2.64.2](https://www.archlinux.org/packages/core/x86_64/glib2/)

**Comment by arcum42** [comment] 2020-04-14 20:32
Duplicate of #3315 

Both were introduced by the same version of GLib at the same time.

**Closed by arcum42** 2020-04-14 20:32 UTC
