### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by frantisekz** [PCSX2/pcsx2#1629] opened 2016-10-16 23:40 UTC
**_PCSX2 version:**_ All when compiled with GTK3

**_Plugins used:**_
GSDX HW/SW

**_Description of the issue:**_
PCSX2 crashes when compiled with --gtk3 and run on Wayland Session. Adding --egl (which is necessary on Wayland) doesn't help.

```

Gdk-WARNING **: gdkwindow-x11.c:5554 drawable is not a native X11 window
Current Renderer: OpenGL (Hardware mode)
EGL: Failed to get a window surface
Wrong X11 display/window
GSopen Failed: return code: 0xffffffff

```

There are two possible ways of fixing the issue:
*Making app request X11 backend (which is workaround more than fix)
*Fixing the app :)

First option is just adding "GDK_BACKEND=x11 " before executing the PCSX2 itself.

**_How to reproduce the issue:**_
Compile latest PCSX2 with --gtk3
Run PCSX2 on Wayland Session (Fedora 25 default)

**Comment by gregory38** [comment] 2016-10-17 10:04
First EGL/X11 must be corrected to work on all drivers. The code is quite old now and not yet bullet proof.

Then X11 code must be replaced with wayland stuff. I guess it means both Window/Event managements. Full wayland support is a low priority for me (patches are welcome).  I guess 2nd step will be to port event to libinput.  And finally do window stuff.

**Comment by frantisekz** [comment] 2016-10-17 13:19
I can do PR for enforcing X11 backend through the sh file but I have no idea how to solve this if somebody runs PCSX2 from executable directly.

Regarding libinput, I am not 100% sure but in my understanding this is only for input device <=> userspace, not application <=> input device handling.

**Comment by gregory38** [comment] 2016-10-17 13:23
Easy. Running the executable directly isn't supported. I don't have a better solution.

Honestly I don't really know all those stuffs. But I know that we include X11 file to handle some keyboard/mouse events.

**Comment by frantisekz** [comment] 2016-10-17 13:43
Ok, PR is here: https://github.com/PCSX2/pcsx2/pull/1630

It affects only GTK3 as GTK2 ignores GDK_BACKEND variable (and should automatically use XWayland).

**Comment by gregory38** [comment] 2016-10-21 15:54
For the record, EGL code is potentially correct. It didn't work on my Nvidia driver because it is too old. I don't plan to update soon to validate it.

**Comment by gregory38** [comment] 2016-10-21 16:16
@frantisekz do you know if we need to migrate the code from Xlib to Xcb in order to support Wayland ?

**Comment by frantisekz** [comment] 2016-10-21 19:41
@gregory38 yes, porting from Xlib to XCB is necessary.
Both SDL2 and GTK3 support native Wayland.

Regarding the porting, I think reading blog of Martin Gräßlin, KWin developer ( https://blog.martin-graesslin.com ) can enlight some background around porting from X to Wayland.

Regarding dropping GLX - this would probably need extensive testing as it was not very reliable few years ago on some drivers.

@jobs-git Benchmarks you've mentioned are about XWayland, where performance will always be a little bit smaller (rendering needs to go both through X and Wayland) compared to native Wayland/or native X. Look at this (native Wayland vs native X): http://www.phoronix.com/scan.php?page=article&item=f25-alpha-wayland&num=2

There is room for improving perf on Wayland but developers are targeting feature parity with X atm.

**Comment by gregory38** [comment] 2016-10-21 20:30
Well egl (or glx) is only used to get an opengl context and a surface. Then we only swap back&front buffer. We are far from the requirement of a compositor. So it ought to be stable enough for us.

I'm not sure to understand why we need xcb here.

**Comment by frantisekz** [comment] 2016-10-21 23:30
This goes behind my understanding on this topic.

I've read just some article about moving from xlib to xcb in order to support Wayland.

**Comment by Sunderland93** [comment] 2016-10-22 02:22
> Debian still uses GTK2 as WX backend (and likely others distribution). It will be already a huge improvement to convert xlib code to GTK3 and drop GTK2 support. But it won't happen soon...

I am sorry for my stupid question, but why GTK? Why not Qt5?

**Comment by sudonim1** [comment] 2016-10-22 02:32
Because rewriting everything is a massive pain and best avoided?

**Comment by gregory38** [comment] 2016-10-22 11:40
Because Dolphin got too much dev that don't know what to do from their free time ;) So why Qt and not GTK ? As sudonim said, upgrading to GTK3 is a matter of few files to update. Qt is everything.

**Comment by gregory38** [comment] 2016-10-22 13:02
So I got a small discussion on IRC with Nouveau guys. It seems XCB is useless on wayland too (but not 100% sure). On my side, I tried to boot with EGL and the mesa SW rasterizer. The EGL part seems to be good (I have the image too ;) )
```
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
EGL: Mesa Project : 1.4 (DRI2)
EGL: extensions supported: EGL_KHR_create_context EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_MESA_configless_context 
OpenGL information. GPU: Gallium 0.4 on softpipe. Vendor: VMware, Inc.. Driver: (Core Profile) Mesa 13.1.0-devel (git-b835255)
INFO: GL_EXT_texture_filter_anisotropic is available
INFO: GL_ARB_gpu_shader5 is NOT SUPPORTED
INFO: GL_ARB_draw_buffers_blend is available
INFO: GL_ARB_viewport_array is available
INFO: GL_ARB_shader_image_load_store is available
INFO: GL_ARB_clear_texture is NOT SUPPORTED
INFO: GL_ARB_texture_barrier is NOT SUPPORTED
INFO: GL_ARB_get_texture_sub_image is available
```

Looking at your log
```
Gdk-WARNING **: gdkwindow-x11.c:5554 drawable is not a native X11 window
Current Renderer: OpenGL (Hardware mode)
```

We are currently extracting an X11 window from the Wx/GTK window widget. I guess it doesn't work as expected on Wayland. The relevant code can be found here https://github.com/PCSX2/pcsx2/blob/master/pcsx2/gui/AppMain.cpp#L963

```
#ifdef __WXGTK__
	// The x window/display are actually very deeper in the widget. You need both display and window
	// because unlike window there are unrelated. One could think it would be easier to send directly the GdkWindow.
	// Unfortunately there is a race condition between gui and gs threads when you called the
	// GDK_WINDOW_* macro. To be safe I think it is best to do here. It only cost a slight
	// extension (fully compatible) of the plugins API. -- Gregory

	GtkWidget *child_window = GTK_WIDGET(gsFrame->GetViewport()->GetHandle());

	gtk_widget_realize(child_window); // create the widget to allow to use GDK_WINDOW_* macro

	GdkWindow* draw_window = gtk_widget_get_window(child_window);

#if GTK_MAJOR_VERSION < 3
	Window Xwindow = GDK_WINDOW_XWINDOW(draw_window);
#else
	Window Xwindow = GDK_WINDOW_XID(draw_window);
#endif
	Display* XDisplay = GDK_WINDOW_XDISPLAY(draw_window);

	pDsp[0] = (uptr)XDisplay;
	pDsp[1] = (uptr)Xwindow;
#else
	pDsp[0] = (uptr)gsFrame->GetViewport()->GetHandle();
	pDsp[1] = NULL;
#endif
```

**Comment by gregory38** [comment] 2016-10-22 13:20
Hum a quick look on GTK code. Some quote taht could be useful on the future
* `GdkWaylandDisplay *wayland_display = GDK_WAYLAND_DISPLAY (gdk_window_get_display (window))` Note: window is a GdkWindow*
* `struct wl_surface * gdk_wayland_window_get_wl_surface (GdkWindow *window)`

Wayland tutorial
* https://jan.newmarch.name/Wayland/EGL/
* https://github.com/eyelash/tutorials/blob/master/wayland-egl.c

Wayland API
*  wl_egl_window_create (to create the egl native window)

**Comment by DmitryHetman** [comment] 2017-05-16 12:19
https://jan.newmarch.name/Wayland/index.html

**Comment by DmitryHetman** [comment] 2017-05-16 12:21
X11 must be optional, Wayalnd have so much less overhead than X11.

**Comment by gregory38** [comment] 2017-05-16 12:37
@DmitryHetman 
Are you sure than Wayland is faster ? **X**wayland is likely slower but I doubt that Wayland is faster than X11. Having a compositor doesn't improve speed.

Anyway, steps are 
* Wait WX 3.2 release
* Drop GTK2 support
* Plug wayland surface to Core/GSdx

**Comment by hellbringer616** [comment] 2017-10-19 13:07
Sorry for using a Phoenix down on this old topic;
Ubuntu released 17.10 today which ships with Wayland as the default window compositor. I'll beta test in the coming weeks to see how PCSX2 runs in Wayland.

I know Ubuntu isn't the ONLY distribution, but it is one of the most popular so we may want to try to iron out these issues and get Wayland support in PCSX2 (and by we i mean the devs as i lack any coding knowledge :) )

**Comment by lightningterror** [comment] 2018-04-06 17:13
Is this still an issue since #1630 was merged ?

**Comment by frantisekz** [comment] 2018-04-06 17:43
It depends - PCSX2 now runs through XWayland when launched on Wayland session. So, it doesn´t crash, but optimal will be native PCSX2 Wayland support.

**Comment by hellbringer616** [comment] 2018-04-06 19:02
I've used it on an off since my last post 6 months ago; only thing I've noticed is having to hit escape about 5 times for it to exit full screen every now and again.

Nothing serious like crashes however

**Comment by jobs-git** [comment] 2018-04-08 16:38
Dear all, dont use Qt toolkit, its gonna be phased out soon, now that majority of Linux Distro is going back to Gnome 3 and only few used KDE plasma, well, my best guess could be KDE will also move to gtk. Qt is too ugly, its always better to go to native GUI.

**Comment by mirh** [comment] 2018-04-08 17:31
Meanwhile lxde switched to qt.. 
Whatever. 
Anyway, the blocker is this https://trac.wxwidgets.org/ticket/17702
Nothing to see here. Upstream tag maybe?

**Comment by Sunderland93** [comment] 2018-04-08 18:16
@jobs-git bullshit. KDE, Budgie 11, LXQt....and many, MANY professional tools using Qt. GTK 3 is crap by design

**Comment by jobs-git** [comment] 2018-04-12 22:11
@Sunderland93 you can go bullshting yourself anytime you like but Qt is a sad tech that is going to go into treasure box sooner. kde is welcome to join gtk though.

**Comment by Sunderland93** [comment] 2018-04-13 09:14
@jobs-git only in your sweat dreams. Even Dolphin, RPCS3, Citra, Yuzu, mGBA are using Qt. Because Qt - is the best cross platform toolkit ever. I plan to start working on Qt gui for PCSX 2 in foreseeable future.If someone does not start before me

**Comment by gregory38** [comment] 2018-04-13 09:49
Guys, it isn't reddit here !!! So could you stop this non-sense.

PCSX2 isn't wayland compatible. Mostly the input, there are some code for the graphic (GSdx side) but nothing was tested, and code isn't done yet. So this issue should remain open. Basically we might look into Wayland when we drop GTK2 completely (and wx is ready)

**Comment by bmwalters** [comment] 2020-12-29 04:19
Working on this in my fork https://github.com/bmwalters/pcsx2

Current status is that it displays a game window with EGL on native Wayland. Already ran into a couple big issues so it will be a bit involved:
- Linux PAD code calls into xlib directly for input processing. My [plan is to re-implement](https://github.com/bmwalters/pcsx2/tree/wayland/pcsx2/PAD/SDL) Linux PAD on top of pure SDL.
- Currently it creates a new instead of using the Wx / GTK window provided by `FrameForGS` because GTK doesn't expose retrieving a `wl_egl_window` from a `GdkWindow`. Could maybe get the `wl_surface` from GDK then create a subsurface that completely covers it?

![screenshot of wayland workspace with game window](https://user-images.githubusercontent.com/4380777/103258449-3927fd00-4952-11eb-8f9b-27653c853b97.png)

**Comment by stenzek** [comment] 2021-10-30 08:35
Fixed by https://github.com/PCSX2/pcsx2/pull/4905

**Closed** 2021-10-30 08:52 UTC
Labels: Enhancement / Feature Request, OS: Linux, Low Priority
