### ISSUE TITLE
[BUG]: Kingdom Hearts missing left-side edge of the text bubble

### ISSUE THREAD

**Issue by RocketRobz** [PCSX2/pcsx2#5639] opened 2022-03-13 06:39 UTC
### Describe the Bug

Any text bubble on-screen will have the left-side edge cut off.

### Reproduction Steps

- If continuing from saved data, talk to any NPC.
- If starting a new game, pick a weapon, and wait until you're asked if you pick the weapon.

### Expected Behavior

Any text bubble on-screen are displayed properly.

### PCSX2 Revision

v1.7.2443

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 1600 Six-Core Processor, 3.40 GHz

### GPU

AMD Radeon RX 570

### GS Window Screenshots

![gs_20220312233120_Kingdom Hearts _NTSC-U__SLUS-20370](https://user-images.githubusercontent.com/16110127/158048110-accc0a79-8c4a-4206-89fd-6fedc1898ee8.png)

### Logs & Dumps

[gs_20220312233120_Kingdom Hearts _NTSC-U__SLUS-20370.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/8239079/gs_20220312233120_Kingdom.Hearts._NTSC-U__SLUS-20370.gs.xz.zip)

**Comment by Tzerinas** [comment] 2022-03-13 09:42
Bug seems to only exist on the DX11 renderer. OpenGL and Vulkan work fine for me.

**Comment by lightningterror** [comment] 2022-03-13 10:54
The dump doesn't run here, can you upload a new one?

**Comment by refractionpcsx2** [comment] 2022-03-13 13:19
The dump is fine.

**Comment by RocketRobz** [comment] 2022-03-13 14:50
Vulkan gives the same issue on my side.

**Comment by lightningterror** [comment] 2022-03-13 15:21
Seems that https://github.com/PCSX2/pcsx2/pull/5221 introduced the regression.

**Comment by Tzerinas** [comment] 2022-03-13 15:37
Rechecked to confirm and I don't have the issue on Vulkan. I do have an Nvidia GPU in comparison to RocketRobz. Maybe that helps.

**Comment by stenzek-push** [comment] 2022-03-14 06:08
Should be fixed by https://github.com/PCSX2/pcsx2/pull/5645.

The inconsistency with Vulkan was probably because not all drivers support the provoking vertex last extension (e.g. older AMD drivers, probably Intel), and it was only broken when this **was not** supported (same as D3D).

**Closed** 2022-03-14 08:47 UTC
Labels: Bug, Regression, GS: Direct3D
