### ISSUE TITLE
[BUG]: Error message on non-existent savestate load.

### ISSUE THREAD

**Issue by coornio** [PCSX2/pcsx2#6457] opened 2022-06-19 06:54 UTC
### Describe the Bug

As the title describes:

![image](https://user-images.githubusercontent.com/11655762/174469301-5202ab64-f834-403e-ae3e-599e6f974855.png)

Attempting to load a savestate from a slot that doesn't actually have one associated with it results in the above (pointless) error. This, in turn, freezes input from the game to whatever you were holding at the time as it hijacks focus to the error window.

### Reproduction Steps

Load a savestate slot without an actual savestate behind it.

### Expected Behavior

Such an action shouldn't throw an error. It needs to merely display a message on the imgui popups at the top left corner about how the slot is empty and that should be it.

The current error message should only appear when a savestate is actually corrupt/invalid **AND** present. 

### PCSX2 Revision

1.7.2961

### Operating System

Windows 11

**Comment by stenzek** [comment] 2022-06-19 09:46
Duplicate of https://github.com/PCSX2/pcsx2/issues/6437, and fixed by https://github.com/PCSX2/pcsx2/pull/6438

**Closed by stenzek** 2022-06-19 09:46 UTC
Labels: Bug

**Comment by coornio** [comment] 2022-06-19 09:48
How'd I miss that xD
