### ISSUE TITLE
[New FIX] Fix which disables all other hacks and fixes during FMV

### ISSUE THREAD

**Issue by Al0ner** [PCSX2/pcsx2#2552] opened 2018-08-13 21:52 UTC
From personal experience, among the large AAA-games, one of the most problematic remains "PRIMAL", due to the very low FPS. Maybe I'm not the first, but I was able to seriously increase the FPS in it, by including these options:

![1](https://user-images.githubusercontent.com/41343638/44060089-257b3ec2-9f5c-11e8-85d8-6677f3188923.png)
![2](https://user-images.githubusercontent.com/41343638/44060090-259f648c-9f5c-11e8-90a3-86accca4f2c4.png)

In this case, in the gameplay of problems is not yet seen. But during FMV playback, the sound begins to stutter. This is partly due to the "OPH Flag Hack" - which is partially corrected by the "EE timing hack". But most of all the stuttering of the sound is due to "EE Cyclerate" and this is not being corrected in any way.

Therefore, i think we needs a fix, which when playing FMV - would disable all other hacks and fixes.

**Comment by MrCK1** [comment] 2018-08-13 21:56
The sound is stuttering *because* you're using hacks, they're labeled as such for a reason.

**Comment by Al0ner** [comment] 2018-08-13 22:09
I know why I stutter, I wrote about it myself. Using speedhacks is the only way to increase fps in the gameplay. But in FMV they are not needed, because in there fps is normal. Therefore, automatically disabling speedhacks and fixes - it would be an excellent solution.

**Comment by lightningterror** [comment] 2018-08-14 10:03
See #2435

**Comment by MrCK1** [comment] 2018-08-29 20:47
Closing this since it's essentially a duplicate of #2435

**Closed by MrCK1** 2018-08-29 20:47 UTC
Labels: Duplicate

**Comment by lightningterror** [comment] 2018-08-29 21:12
> Closing this since it's essentially a duplicate of #2435 

It's still an issue since the PR isn't merged yet.
