### ISSUE TITLE
[BUG]: Spontaneous changing of "custom window size" values after pausing the full-screen emulation process

### ISSUE THREAD

**Issue by VladimirVSC** [PCSX2/pcsx2#7017] opened 2022-09-08 16:41 UTC
### Describe the Bug

Pausing the full-screen emulation with Escape button (and resuming it afterwards), provides spontaneous changing of "custom window size" values to full-screen values.

### Reproduction Steps

1: Set "custom window size" values as "640X480", for example.
2: Starting the emulation in full-screen mode.
3: Pausing the process with Escape button.
4: Resuming the process.
5: Double-click to return to window mode.
The window size somehow becomes equal to fullscreen size, and "custom window size" values in General Settings section are changed to full-screen-equal values.
It only works when pausing and resuming the emulation in full-screen mode; pausing the window-size emulation works fine.

### Expected Behavior

"Custom window size" values should stay the same, unless user himself changed it.

### PCSX2 Revision

v1.7.3256

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

LMDE 5

**Comment by LeCharlatan** [comment] 2023-01-04 23:10
Hi @VladimirVSC is this happening on Qt version or WX ?
Can't reproduce this bug on Qt version so, if that bug happens only on WX version, we may close this issue.

**Comment by refractionpcsx2** [comment] 2023-01-25 22:37
sounds like a WX build, and no response, so closing. Can reopen if the OP responds that it's still an issue on Qt builds.

**Closed by refractionpcsx2** 2023-01-25 22:37 UTC
Labels: Bug
