### ISSUE TITLE
[GSDX/GS] Catlevania: LoI/CoD - incorrect/missing shadows

### ISSUE THREAD

**Issue by Kein** [PCSX2/pcsx2#380] opened 2014-12-08 00:22 UTC
Old, but relevant information can be found here:
http://code.google.com/p/pcsx2/issues/detail?id=282

D3D11/D3D9 Software:
http://i.imgur.com/o3tMn6F.png

D3D11 Hardware:
http://i.imgur.com/XiWxQMp.png

OpenGL Hardware:
http://i.imgur.com/MihgfEg.png

**Comment by gregory38** [comment] 2015-05-19 11:45
Could you generate a gs dump of the issue? 1
1/ Install latest git version
2/ hit shift-F8 on the bad rendering image
3/ file will be generated in snaps directory

**Comment by Kein** [comment] 2015-05-19 17:04
Sure:
https://www.dropbox.com/s/c2qhlehr2o8k74e/LoI_dump.rar?dl=0

**Comment by gregory38** [comment] 2015-05-26 15:57
I pushed a "partial" fix for opengl. You can try it, if you disable CRC and enable accurate colclip. However it will impact the perf. Any feedback is appreciated.
```
UserHacks = 1
UserHacks_DisableCrcHacks = 1
accurate_colclip = 1
```

**Comment by Kein** [comment] 2015-07-01 17:31
Was it merged?

**Comment by Kein** [comment] 2015-07-01 18:18
Tested on PCSX2 1.3.1-20150701182720 - shadows work fine with CRC preset "Minimal", FPS seems stable 60 too.
Castlevania: Curse of Darkness works fine too. There is shadows as well.
(Also, both games feature better and more accurate lighting, though this commit has nothing to do with it)
Lovely.

**Comment by gregory38** [comment] 2015-07-01 18:21
Shadows might be a bit better when the new gsdx is merged PR #628

**Comment by gregory38** [comment] 2015-07-31 20:24
I develop a new branch (https://github.com/PCSX2/pcsx2/pull/688) with a faster colclip algorithm. Now you can fine tune the blending accuracy. I think you can play both Castlevania without any major speed hit. Could you test it?

**Comment by Kein** [comment] 2015-07-31 21:33
I could, but I don't have a build from that branch and don't have dev. env. to compile it.

**Comment by gregory38** [comment] 2015-07-31 21:34
No worry. I hope to merge the branch next weeks.

**Comment by Kein** [comment] 2015-08-03 08:14
Regression:
http://i.imgur.com/21bs4ID.jpg
http://www13.zippyshare.com/v/FNfXiI3v/file.html

Shadow casts weird sps-like glitches.

**Comment by gregory38** [comment] 2015-08-03 08:36
:( Could you check in native mode?

**Comment by gregory38** [comment] 2015-08-03 16:51
I can't reproduce it. My scene is the character on the stair. Maybe a bit too late.

**Comment by gregory38** [comment] 2015-08-03 17:00
See PR #697

**Comment by Kein** [comment] 2015-08-04 18:15
Regression fixed (tested on High Compaibiltiy mode or higher).

(as a dside-note: on Medium/Basic it spams about noclip not being supported and the shadow is a little bit pale)

**Comment by gregory38** [comment] 2015-08-04 18:45
Please be precise, in which build the regression is fixed? Latest git? or in the build above?

I need to remove the warning. Higher level are slower but more accurate. It explains why the shadow is pale.

**Comment by Kein** [comment] 2015-08-04 19:27
I'm talking about this plugin https://github.com/PCSX2/pcsx2/pull/697
The one you requited to be compiled.
Used it with PCSX2 1.3.1-20150803084625

**Comment by gregory38** [comment] 2015-08-04 19:31
Did you notice a big speed impact?

**Comment by Kein** [comment] 2015-08-04 19:57
Hmm, not really. I just did a quick test with LoI, there is a place in th beginning where it used to lag horribly. Without vsync and in High Compatibility  moe (3x native) I received 125-130FPS, in Full mode - around ~80-82fps, and in Ultra it is fluctuating around 72-75FPS.

Castelavania's aren't that demanding anymore it seems. Note that I used "safe" speedhacks.

GTX670/Core i7 3770k (3.5-3.9Ghz)

**Comment by gregory38** [comment] 2015-08-04 20:05
Great. Full and Ultra are mostly debug option. High is already quite accurate and it seems playable.

**Comment by bositman** [comment] 2015-08-18 12:14
Indeed high is enough for this game. Closing this, DX11 still has the issue bug since we have the fixed in opengl tag, no need to keep it open.

**Closed by bositman** 2015-08-18 12:14 UTC
Labels: Fixed in openGL, GSdx: Hardware, Plugin: GSdx
