### ISSUE TITLE
Missing tooltip GSDX windows build

### ISSUE THREAD

**Issue by tsunami2311** [PCSX2/pcsx2#578] opened 2015-06-03 23:08 UTC
Accurate blend, Accurate color clip, Accurate data, gregory say these have tool tips in linux, There is no tooltips in windows builds, Infact there are no tool tips for any of the checkable options in the main window of gsdx in windows builds.

Most people probably know what texture filtering/allow 8bit textures/Anisotropic Filtering do so i can see why those might not need tooltips, but i gona venture guess most wont know what Accurate blend, Accurate color clip, Accurate data.

Should the windows builds have tooltips for GSDX options like the linux ones does?

**Comment by karasuhebi** [comment] 2015-06-03 23:31
Also all of those other options have explanations on the wiki page for GSdx, these new ones don't.

**Comment by ssakash** [comment] 2015-06-04 01:41
Could be done easily, the problem is the precise definition. I should make sure that the information on tooltip is accurate before starting the work.

**Comment by tsunami2311** [comment] 2015-06-04 01:56
Im sure it is listed on wiki problem is very few people know about the wiki let alone update.

I was mostly after what Accurate blend, Accurate color clip, Accurate data. do i know what the other i mention do, gregory has says there tooltip for the above in linux build maybe just pull them from the linux build?

**Comment by ssakash** [comment] 2015-06-04 06:04
will be added. I think I could also reuse the helper strings as tooltip. shouldn't be a problem ;)

**Comment by gregory38** [comment] 2015-06-04 06:37
There are some tooltips in GSSetting.cpp for IDC_PALTEX/IDC_ACCURATE_DATE/IDC_ACCURATE_BLEND/IDC_ACCURATE_COLCLIP. You just need to reuse them.

**Comment by gregory38** [comment] 2015-06-08 09:59
any status?

**Comment by ssakash** [comment] 2015-06-08 12:04
it seems that I can't reuse the tooltip format on the linux dialog.cpp , they are dependent on the WTK widgets. I guess I would go for a alternative with another tooltip function specifically for the resource files. though, the tool tip description would be still the same as linux. will report about the progress after it's completion.

**Comment by gregory38** [comment] 2015-06-08 17:24
???

I think it will be somethings like that. You need to call dialog_message(IDC_*) to get the text string and then you just set to the button
```
text = dialog_message(IDC_ACCURATE_DATE);
SetWindowText(GetDlgItem(m_hWnd, IDC_ACCURATE_DATE), text));
```

**Comment by ssakash** [comment] 2015-06-08 17:41
Yes, this method could also be done. I will PR it quite soon.

**Comment by tsunami2311** [comment] 2015-07-24 16:45
what happen to this? or this be held back till 1.4 stable?

**Comment by ssakash** [comment] 2015-07-24 16:57
actually, I thought of holding this out till some ideas here get's decided. http://forums.pcsx2.net/Thread-Enhancement-PCSX2-GUI-Windows
if there was agreement for #1 in GSdx plugin settings, we could have it as a description box instead of crowded tooltips. either way, I did some initial work on tooltips. Haven't checked it out yet https://github.com/PCSX2/pcsx2/compare/master...ssakash:patch-36

I would still consider waiting for people's opinion on that, if there's a agreement. description box could be used instead of tooltips. (something similar to how HW hacks show the explanation text)

**Comment by tsunami2311** [comment] 2015-07-24 20:25
I see was just curious cause you said u did the week ago and forgot to push it threw, Probably good idea to wait to see what comes of gui windows changes

**Comment by gregory38** [comment] 2015-08-20 11:05
Turtleli, I let you manage this issue.

**Comment by turtleli** [comment] 2015-08-20 11:26
Will be fixed after I'm done with #754. Code is more or less done.

**Comment by Nobbs66** [comment] 2015-08-31 18:09
Can this be closed, or are there things still needing to be done?

**Comment by tsunami2311** [comment] 2015-08-31 18:32
i think it can be close as far i can tel turtleli has added all the missing tooltips gui changed builds

**Comment by karasuhebi** [comment] 2015-08-31 18:42
Nope, can't be closed yet. PR hasn't been merged yet. Look at the line right above your comment.

**Closed** 2015-09-03 21:49 UTC
Labels: Plugin: GSdx
