### ISSUE TITLE
GSdx software mode, horrible hitching (windows)

### ISSUE THREAD

**Issue by wareya** [PCSX2/pcsx2#1391] opened 2016-06-06 08:38 UTC
When I try to run in software mode with the threads setting set to more than 1, I experience extremely terrible hitches and stuttering that bring performance down to worse than 10% realtime in certain scenes, in particular the Georama view in Dark Cloud 1. This seems to go back to the end of last year.

I downloaded random ancient buildbot builds in no particular order and the first one I found at random that doesn't have the problem is from 2015-08-20 (per file modification date). A build from 2015-11-21 (per file modification date) includes the horrible hitching.

I continued to bisect and the first build on orphis that contains the breakage on my system is "1416-gb6f78d8", which was built 2015-11-09 4:23 my time (currently EDT). The former build is "1415-g9bb990e", which was built 2015-11-08 3:36 my time (currently EDT).

Working as of: https://github.com/PCSX2/pcsx2/commit/9bb990e
Broken as of: https://github.com/PCSX2/pcsx2/commit/b6f78d8

To note, if necessary, the next build (1417) after the first broken one has a commit hash of 44d8930; yes, they're both broken for the sake of sanity. The former build to the working build(1415) is 1408 and has a commit hash of 8ed56bd, and is indeed also working.

...b6f78d8 is a very innocuous commit, so something fishy is going on. Maybe the buildbot started compiling with different settings or it got the labels wrong. If necessary I could start compiling old stages of development myself but I want to get this up first in case someone knows what's going on.

The horribleness and randomness of the hitching increases with thread count.

Running on an i5-6600, skylake, no dedicated GPU, applies to both DX9 and DX11 and can't check OGL because the plugin doesn't boot with it selected. Can't use hardware mode as a workaround because the iGPU is not quite fast enough for all scenes; software mode and 9bb990e are faster. Windows. Up-to-date graphics drivers.

**Comment by turtleli** [comment] 2016-06-06 09:21
1416 was the switch from VS2013 to VS2015. We have some sort of issue with Skylake CPUs and VS2015.

See #998 - please also post there as well, your cpu doesn't use hyperthreading (or my google skills suck) and it rules out hyperthreading as the cause.

Closing as a duplicate.

**Closed by turtleli** 2016-06-06 09:21 UTC
Labels: Duplicate

**Comment by wareya** [comment] 2016-06-06 09:22
Thank you!
