### ISSUE TITLE
[BUG]: Wave Rally SLPS-20170 White Color water and strange reflections

### ISSUE THREAD

**Issue by seta-san** [PCSX2/pcsx2#9836] opened 2023-08-23 20:17 UTC
### Describe the Bug

the color is far more white than it should be and there's a strange reflection going down the middle of the water
![Wave Rally_SLPS-20170_20230823150338](https://github.com/PCSX2/pcsx2/assets/8851653/db65821f-0b0d-4caf-84b2-a4195e1f42d7)

### Reproduction Steps

just start a race

### Expected Behavior

![Wave Rally_SLPS-20170_20230823150334](https://github.com/PCSX2/pcsx2/assets/8851653/8b33a0cb-4b68-4277-824c-5417803f9845)

### PCSX2 Revision

1.7.4940

### Operating System

Windows 11

### CPU

i5-9600

### GPU

rtx 3060

### Logs & Dumps

[Wave Rally_SLPS-20170_20230823150338.gs.zip](https://github.com/PCSX2/pcsx2/files/12423017/Wave.Rally_SLPS-20170_20230823150338.gs.zip)

**Comment by Mrlinkwii** [comment] 2023-08-23 20:37
duplicate of #6554

**Closed by Mrlinkwii** 2023-08-23 20:37 UTC
Labels: Bug
