### ISSUE TITLE
Audio CD inserted.

### ISSUE THREAD

**Issue by SySy233** [PCSX2/pcsx2#5432] opened 2022-01-30 22:10 UTC
### Describe the Bug

Audio crackling when playing an audio cd. Skipping/starting etc

IOP Unknown 8bit write to addr 0x1f40209 = 0x0
IOP Unknown 8bit write to addr 0x1f40209 = 0x0
IOP Unknown 8bit write to addr 0x1f40209 = 0x0
IOP Unknown 8bit write to addr 0x1f40209 = 0x0
IOP Unknown 8bit write to addr 0x1f40209 = 0x0
IOP Unknown 8bit write to addr 0x1f40209 = 0x0

Multiple times on the Program Log.

### Reproduction Steps

Insert an Audio CD into PCSX2.

### Expected Behavior

Audio playing perfectly without skipping.

### PCSX2 Revision

v1.7.2289

### Operating System

Windows 10 (64bit)

**Comment by Mrlinkwii** [comment] 2022-01-30 22:11
Duplicate of #4178

**Closed** 2022-01-30 22:12 UTC
Labels: Bug
