### ISSUE TITLE
Ace Combat 4 Shattered Skies (NTSC-U) [SLUS-20152] Black lines and missing graphics only in Hardware mode

### ISSUE THREAD

**Issue by shandawgy** [PCSX2/pcsx2#260] opened 2014-08-20 00:29 UTC
When you start a new game and go to select the plain the plane is missing textures and is looking really grey but if you enable software mode this problem is fixed.

On top of that All ace combat games in the series have very thin black lines when running in hardware mode.  
Ace Combat 4 Shattered Skies (NTSC-U) [SLUS-20152]
Ace Combat 5 - The Unsung War (NTSC-U) [SLUS-20851]
Ace Combat Zero - The Belkan War (NTSC-U) [SLUS-21346]

pcsx2-v1.2.1-511-g02b19b7

Plugins:
GSDx 20140818023333(MSVC 18.00,AVX) 0.1.16 [GSdx32-AVX]
XPad 0.2.0
SPU2-X 2014081802333 2.0.0
cdvdGigaherz (20140818023333ll) 0.9.0

My specs are:
Intel core i5-3470T CPU @ 2.90GHz
2x NVidia 560 GForce graphics card SLI
8gb Ram
Windows 8 64bit

**Comment by mirhl** [comment] 2015-01-26 01:01
Black (vertical) lines with non-native resolutions gets addressed with [Racer_S fixed gsdx](http://forums.pcsx2.net/Thread-GSdx?page=469#pid424524)

**Comment by gregory38** [comment] 2015-05-19 11:51
What is the status of this game with latest GSdx upscaling hack?

**Comment by mirhl** [comment] 2015-05-19 17:12
We had already discussed plenty of times :)

Besides that [tiny line](http://forums.pcsx2.net/Thread-GSdx?page=522#pid457755) I really wouldn't be able to spot issues.

**Comment by gregory38** [comment] 2015-05-19 18:36
Well my hidden question was, can I close the bug?

**Comment by mirhl** [comment] 2015-05-20 13:21
And my hidden answer is yes, if you are sure this is already best method.

**Comment by gregory38** [comment] 2015-05-23 09:45
Ok. Good so I close it.

**Closed by gregory38** 2015-05-23 09:45 UTC
Labels: Bug, GSDX: Hardware, Plugin: GSDX

**Comment by AnotherLife** [comment] 2017-03-26 21:37
In non-native resolutions I see many black lines/rectangles all over the screen in OpenGL HW renderer, can someone confirm?

Why was this issue closed, is it a regression?

**Comment by mirh** [comment] 2017-03-26 22:04
Because it gets fixed by enabling allign sprite hacks (and/or merge_pp_sprite)
