### ISSUE TITLE
PCSX2 Latest Is Very Slow with Games

### ISSUE THREAD

**Issue by JuniorEC** [PCSX2/pcsx2#3058] opened 2019-08-04 16:25 UTC
***PCSX2 version:***
``v1.5.0-0``

***Plugins used:***
![Captura de tela de 2019-08-04 13-19-38](https://user-images.githubusercontent.com/24255719/62426422-12ad5600-b6bb-11e9-9de0-552428502484.png)
![Captura de tela de 2019-08-04 13-20-02](https://user-images.githubusercontent.com/24255719/62426423-1345ec80-b6bb-11e9-94a8-905c93d0abb4.png)

- **Note**: 

***Description of the issue:***
``
I am trying to run some games like:
SSX On tour;
PES 2010;
FIFA 07;
LEGACY OF KAYN I and II;

But when running it through ISO, the game is only 15FPS even changing the settings to the simplest. I can't play any games, is there any incompatibility with linux?``

***PC specifications:***
``CPU: Intel i7 7th
  GPU: NVIDIA GTX 750Ti (Proprietary Nvidia drivers)
  OS: Ubuntu 19.04 64 Bit``

***LOG***
```
Initializing plugins...
	Init GS
	Init PAD
	Init SPU2
	Init CDVD
	Init USB
	Init FW
	Init DEV9
Plugins initialized successfully.

Patches: No CRC found, using 00000000 instead.
Opening plugins...
	Opening GS
	Opening PAD
	Opening SPU2
Expression 'GetExactSampleRate( hwParams, &defaultSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 895
Expression 'GetExactSampleRate( hwParams, &defaultSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 895
Expression 'GetExactSampleRate( hwParams, &defaultSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 895
Expression 'GetExactSampleRate( hwParams, &defaultSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 895
Expression 'GetExactSampleRate( hwParams, &defaultSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 895
Expression 'GetExactSampleRate( hwParams, &defaultSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 895
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
Expression 'GetExactSampleRate( hwParams, &defaultSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 895
Cannot connect to server socket err = Arquivo ou diretório inexistente
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = Arquivo ou diretório inexistente
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
Cannot connect to server socket err = Arquivo ou diretório inexistente
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
 SPU2-X: Enumerating PortAudio devices:
 Device 0: 'sysdefault' (ALSA)
 Device 1: 'front' (ALSA)
 Device 2: 'surround40' (ALSA)
 Device 3: 'surround51' (ALSA)
 Device 4: 'surround71' (ALSA)
 Device 5: 'samplerate' (ALSA)
 Device 6: 'speexrate' (ALSA)
 Device 7: 'pulse' (ALSA)
 Device 8: 'upmix' (ALSA)
 Device 9: 'vdownmix' (ALSA)
 Device 10: 'dmix' (ALSA)
 Device 11: 'default' (ALSA) (selected)
	Opening CDVD
isoFile open ok: /home/nekomamushi/Documentos/PS2/Pro Evolution Soccer 2010/Pro Evolution Soccer 2010.iso
	Image type  = DVD
 CDVD Disk Open: DVD, Single layer or unknown:
 Track 1: Data (Mode 1) (1723824 sectors)
	Opening USB
	Opening FW
	Opening DEV9
McdSlot 0 [File]: /home/nekomamushi/.config/PCSX2/memcards/Mcd001.ps2
McdSlot 1 [File]: /home/nekomamushi/.config/PCSX2/memcards/Mcd002.ps2
Plugins opened successfully.
EE/iR5900-32 Recompiler Reset
	Bios Found: Japan   v01.00(17/01/2000)  Console
	BIOS r module not found, skipping...
	BIOS r module not found, skipping...
	BIOS e module not found, skipping...
Initialize memory (rev:3.17, ctm:393Mhz, cpuclk:295Mhz )
OpenGL information. GPU: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) x86/MMX/SSE2. Vendor: Intel Open Source Technology Center. Driver: (Core Profile) Mesa 19.0.8
INFO: GL_EXT_texture_filter_anisotropic is available
INFO: GL_ARB_gpu_shader5 is available
INFO: GL_ARB_viewport_array is available
INFO: GL_ARB_shader_image_load_store is available
INFO: GL_ARB_clear_texture is available
INFO: GL_ARB_direct_state_access is available
INFO: GL_ARB_texture_barrier is available
INFO: GL_ARB_get_texture_sub_image is available

Current Renderer: OpenGL (Hardware renderer)
No extenstion supported to get available memory. Use default value !
Available VRAM/RAM:3840MB for textures
GSdx Lookup CRC:0
GSdx Lookup CRC:0

PlayStation 2 ======== Hard reset boot
 ROMGEN=2000-0117, IOP info (CPUID=1f, CACH_CONFIG=ffffffff, 2MB, IOP mode)
 <20000117-050310,ROMconf,:11232>
Total accessable memory size: 32 MB (B:2:8:0)
TLB spad=0 kernel=1:12 default=13:30 extended=31:38
Initialize Start.
Initialize GS ...
Initialize INTC ...
Initialize TIMER ...
Initialize DMAC ...
Initialize VU1 ...
Initialize VIF1 ...
Initialize GIF ...
Initialize VU0 ...
Initialize VIF0 ...
Initialize IPU ...
Initialize FPU ...
Initialize User Memory ...
Initialize Scratch Pad ...
Initialize Done.

EE DECI2 Manager version 0.06 Dec 10 1999 17:48:37
  CPUID=2e20, BoardID=0, ROMGEN=2000-0117, 32M

Patches: No CRC found, using 00000000 instead.
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_219.18;1
(SYSTEM.CNF) Software version = 1.02
(SYSTEM.CNF) Disc region type = NTSC
found 0 symbols
ELF (cdrom0:\SLUS_219.18;1) Game CRC = 0x6579BD4D, EntryPoint = 0x00100008
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_219.18;1
(SYSTEM.CNF) Software version = 1.02
(SYSTEM.CNF) Disc region type = NTSC



IOP Realtime Kernel Ver.0.9.1


    Copyright 1999 (C) Sony Computer Entertainment Inc. 


Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadelf: fname cdrom0:¥SLUS_219.18;1 secname all
loadelf version 3.30
Input ELF format filename = cdrom0:¥SLUS_219.18;1
0 00100000 00312480 ..................................................
Loaded, cdrom0:¥SLUS_219.18;1
start address 0x100008
gp address 00000000
Loader 'cdrom0:¥SLUS_219.18;1':pc=00100008
Elf entry point @ 0x00100008 about to get recompiled. Load patches first.
sce_fileio: unrecognized code ff
GSdx Lookup CRC:6579BD4D
GSdx Lookup CRC:6579BD4D
Get Reboot Request From EE

PlayStation 2 ======== Update rebooting..

PlayStation 2 ======== Update reboot complete
cdvdman Init
IOP Realtime Kernel Ver. 2.2
    Copyright 1999-2002 (C) Sony Computer Entertainment Inc. 
Reboot service module.(99/11/10)
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
(UpdateVSyncRate) Mode Changed to NTSC.
(UpdateVSyncRate) FPS Limit Changed : 59,94 fps
cdvd driver module version 0.1.1 (C)SCEI
loadmodule: fname cdrom0:¥IOP¥SIO2MAN.IRX;1 args 0 arg 
loadmodule: id 25, ret 0
loadmodule: fname cdrom0:¥IOP¥MTAPMAN.IRX;1 args 0 arg 
loadmodule: id 26, ret 0
loadmodule: fname cdrom0:¥IOP¥PADMAN.IRX;1 args 0 arg 
loadmodule: id 27, ret 0
loadmodule: fname cdrom0:¥IOP¥MCMAN.IRX;1 args 0 arg 
loadmodule: id 28, ret 2
loadmodule: fname cdrom0:¥IOP¥MCSERV.IRX;1 args 0 arg 
loadmodule: id 29, ret 2
loadmodule: fname cdrom0:¥IOP¥LIBSD.IRX;1 args 0 arg 
loadmodule: id 30, ret 0
loadmodule: fname cdrom0:¥IOP¥SDRDRV.IRX;1 args 0 arg 
SDR driver version 4.0.1 (C) SCEI
 Exit rsd_main 
loadmodule: id 31, ret 2
loadmodule: fname cdrom0:¥IOP¥CRI_ADXI.IRX;1 args 30 arg thpri=39
CRI ADX Driver Ver.9.44(Feb 28 2005 19:25:04)
CRI ADX Driver : sceSdInit Call = 0
CRI ADX Driver : Main Thread Priority = 39
CRI ADX Driver : PSM Thread Priority  = 39
CRI ADX Driver : DTX Thread Priority  = 48
CRI ADX Driver : SPU CORE Number = 1
loadmodule: id 32, ret 2
loadmodule: fname cdrom0:¥IOP¥USBD.IRX;1 args 7 arg dev=10
USB Driver (Version 1.4.0)
loadmodule: id 33, ret 2
loadmodule: fname cdrom0:¥IOP¥USBKEYBD.IRX;1 args 0 arg dev=10
loadmodule: id 34, ret 0
loadmodule: fname cdrom0:¥IOP¥CDVDSTM.IRX;1 args 0 arg dev=10
loadmodule: id 35, ret 2
DVCI: "¥0_SOUND.AFS" found.
DVCI: "¥E_SOUND.AFS" found.
DVCI: "¥M_SOUND.AFS" found.
DVCI: "¥F_SOUND.AFS" found.
DVCI: "¥Q_SOUND.AFS" found.
DVCI: "¥0_TEXT.AFS" found.
DVCI: "¥U_TEXT.AFS" found.
DVCI: "¥M_TEXT.AFS" found.
DVCI: "¥F_TEXT.AFS" found.
DVCI: "¥Q_TEXT.AFS" found.
DVCI: "¥OVER.AFS" found.
DVCI: Total 11 files.
PS2RNA: sceSifAllocIopHeap(99904) ret=0x000bdc00
PS2RNA: sceSifAllocIopHeap(2256) ret=0x000d6300
PS2RNA: sceSifAllocIopHeap(6208) ret=0x000d6c00
loadmodule: fname cdrom0:¥IOP¥AUDIO.IRX;1 args 0 arg dev=10
loadmodule: id 36, ret 0
Stream Buffer 1Bank 32768byte 5banks 163840byte used
Closing plugins...
	Closing DEV9
	Closing FW
	Closing USB
	Closing CDVD
	Closing SPU2
	Closing PAD
	Closing GS
Plugins closed successfully.
```

**Comment by MrCK1** [comment] 2019-08-04 21:53
Try turning down resolution

**Comment by berarma** [comment] 2019-08-05 08:21
I'm having a similar problem. Games run at very low fps except on the language selection menu where it runs full speed. I've tried all 3 GS plugins, native resolution and MTVU, same everytime.

The games I tried are Soulcalibur II and God of War II. Both games ran at (or nearly) full speed on PCSX2 1.4.0 on a slower system (AMD FX-8350 + Nvidia GTX 1060 6GB + 8GB RAM).

The EE thread shows 99-100% CPU usage while the GS thread shows lower than 5-10%. How is yours?

I've tried with two systems running Debian Buster:
- AMD Ryzen 3600 + Nvidia GTX 1060 6GB + 16GB RAM
- AMD Ryzen 2400G + 16GB RAM

Same results on both systems.

**Comment by gregory38** [comment] 2019-08-05 08:50
Disable large frame buffer and reduce upscaled resolution. Potentially your gpu vram is not big enough

**Comment by JuniorEC** [comment] 2019-08-05 13:08
> Try turning down resolution

I tried the simplest settings and it didn't work. :(

**Comment by JuniorEC** [comment] 2019-08-05 13:17
> I'm having a similar problem. Games run at very low fps except on the language selection menu where it runs full speed. I've tried all 3 GS plugins, native resolution and MTVU, same everytime.
> 
> The games I tried are Soulcalibur II and God of War II. Both games ran at (or nearly) full speed on PCSX2 1.4.0 on a slower system (AMD FX-8350 + Nvidia GTX 1060 6GB + 8GB RAM).
> 
> The EE thread shows 99-100% CPU usage while the GS thread shows lower than 5-10%. How is yours?
> 
> I've tried with two systems running Debian Buster:
> 
> * AMD Ryzen 3600 + Nvidia GTX 1060 6GB + 16GB RAM
> * AMD Ryzen 2400G + 16GB RAM
> 
> Same results on both systems.

My GS thread shows lower than 5-10%. But in menu is 100%.
I will try an old version 1.4.0 and report the results.

**Comment by berarma** [comment] 2019-08-05 22:41
Version 1.5.0 packaged on Debian runs terribly slowly. I've finally built PCSX2 myself from the latest git code and it works flawlessly. So the package in Debian might have caught a bad snapshot of the git code. The same could have happened in Ubuntu. Try installing the latest dev version in case you didn't or do as me.

**Comment by JuniorEC** [comment] 2019-08-06 12:22
> Version 1.5.0 packaged on Debian runs terribly slowly. I've finally built PCSX2 myself from the latest git code and it works flawlessly. So the package in Debian might have caught a bad snapshot of the git code. The same could have happened in Ubuntu. Try installing the latest dev version in case you didn't or do as me.

I tried to build from the code, and I haven't succeeded yet. The package version is slow. I tried using version 1.4.0 package, and obitive some errors:

```
$ ./PCSX2
./PCSX2: error while loading shared libraries: libpangoxft-1.0.so.0: cannot open shared object file: No such file or directory
```

```
$ ./PCSX2-linux.sh
ERROR the plugin (./plugins/libUSBnull-0.7.0.so) miss some dependencies
    libpangoxft-1.0.so.0 => not found

ERROR the plugin (./plugins/libdev9null-0.5.0.so) miss some dependencies
    libpangoxft-1.0.so.0 => not found

ERROR the plugin (./plugins/libCDVDnull.so) miss some dependencies
    libpangoxft-1.0.so.0 => not found

ERROR the plugin (./plugins/libGSdx-avx2-1.0.0.so) miss some dependencies
    libGLU.so.1 => not found
libpangoxft-1.0.so.0 => not found
libpng12.so.0 => not found

ERROR the plugin (./plugins/libFWnull-0.7.0.so) miss some dependencies
    libpangoxft-1.0.so.0 => not found

ERROR the plugin (./plugins/libspu2x-2.0.0.so) miss some dependencies
    libpangoxft-1.0.so.0 => not found
libSoundTouch.so.0 => not found

ERROR the plugin (./plugins/libGSdx-intel-sse4-1.0.0.so) miss some dependencies
    libGLU.so.1 => not found
libpangoxft-1.0.so.0 => not found
libpng12.so.0 => not found

ERROR the plugin (./plugins/libGSdx-1.0.0.so) miss some dependencies
    libGLU.so.1 => not found
libpangoxft-1.0.so.0 => not found
libpng12.so.0 => not found

ERROR the plugin (./plugins/libonepad-1.1.0.so) miss some dependencies
    libpangoxft-1.0.so.0 => not found

./PCSX2: error while loading shared libraries: libpangoxft-1.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by mirh** [comment] 2019-08-08 09:55
https://askubuntu.com/questions/401408/glassfish-updatetool-error-loading-libpangoxft-1-0-so-0

**Comment by berarma** [comment] 2019-08-08 12:05
> I tried to build from the code, and I haven't succeeded yet. The package version is slow. I tried using version 1.4.0 package, and i got some errors:

There's a PPA for Ubuntu with development builds here: https://launchpad.net/%7Epcsx2-team/+archive/ubuntu/pcsx2-daily

**Comment by JuniorEC** [comment] 2019-08-13 12:16
> https://askubuntu.com/questions/401408/glassfish-updatetool-error-loading-libpangoxft-1-0-so-0

I followed the commands in this post, but got the same error.

**Comment by JuniorEC** [comment] 2019-08-13 12:17
> > I tried to build from the code, and I haven't succeeded yet. The package version is slow. I tried using version 1.4.0 package, and i got some errors:
> 
> There's a PPA for Ubuntu with development builds here: https://launchpad.net/%7Epcsx2-team/+archive/ubuntu/pcsx2-daily

I tested with this version and got the same results.

**Comment by JuniorEC** [comment] 2019-08-13 12:17
> > https://askubuntu.com/questions/401408/glassfish-updatetool-error-loading-libpangoxft-1-0-so-0
> 
> thank you.
> I followed the commands in this post, but got the same error.

**Comment by LeCharlatan** [comment] 2019-08-22 00:15
Hi @JuniorEC 

By chance do you use free or proprietary Nvidia drivers ?
Your issue report doesn't give much informations :p

**Comment by JuniorEC** [comment] 2019-08-22 11:51
> By chance do you use free or proprietary Nvidia drivers ?
> Your issue report doesn't give much informations :p

I am using the proprietary drives and I tested with the free drivers, the same result happens.

**Comment by LeCharlatan** [comment] 2019-08-22 14:02
Hey JuniorEC,

By reading your log, I can't find any "Nvidia" GPU mentioned there but this line : 

"OpenGL information. GPU: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) x86/MMX/SSE2. Vendor: Intel Open Source Technology Center. Driver: (Core Profile) Mesa 19.0.8"

That probably means your system is using the Intel + MESA, not the Nvidia GTX 750ti, the problem may come from that part.

For instance, using a Nvidia GPU, the log shows this line : 

"OpenGL information. GPU: GeForce GTX 1070/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver: NVIDIA 430.40"

Regards

**Comment by mirh** [comment] 2019-08-22 14:55
So it may be a duplicate of #2967

**Comment by LeCharlatan** [comment] 2019-08-22 21:07
Yep it could be

@JuniorEC do you use bumblebee or prime ?

**Comment by Mrlinkwii** [comment] 2021-12-05 10:50
is this still an issue on the latest dev builds ?

**Comment by refractionpcsx2** [comment] 2022-03-22 09:31
Closing, no response in 4 months, plus Github is not a support forum.

**Closed by refractionpcsx2** 2022-03-22 09:31 UTC
Labels: OS: Linux
