### ISSUE TITLE
PCSX2 for win32 could not detect SHIFT and CTRL key

### ISSUE THREAD

**Issue by poodle111** [PCSX2/pcsx2#674] opened 2015-07-24 12:47 UTC
PCSX2 for win32 could not detect SHIFT and CTRL key.

pcsx2/windows/WinKeyCodes.cpp:28 TranslateVKToWXK()
Issue code:
	case VK_LSHIFT:
	case VK_RSHIFT: key_code = WXK_SHIFT; break;

	case VK_LCONTROL:
	case VK_RCONTROL: key_code = WXK_CONTROL; break;

fixed code:
	case VK_LSHIFT:
	case VK_RSHIFT:
	case VK_SHIFT: key_code = WXK_SHIFT; break;

	case VK_LCONTROL:
	case VK_RCONTROL:
	case VK_CONTROL: key_code = WXK_CONTROL; break;

**Comment by avih** [comment] 2015-07-24 13:01
What's the use case where it doesn't work? I.e. how to reproduce the bug?

**Comment by poodle111** [comment] 2015-07-24 13:51
E.x.
States_CycleSlotForward           = F2
States_CycleSlotBackward          = Shift-F2
Issued version ignores States_CycleSlotBackward.

**Comment by avih** [comment] 2015-07-24 14:06
Well, shift is used by several of the default shortcuts such as the one you just specified, and it's the first time I hear from someone that it doesn't work. It certainly works for me and many others. I do believe you though if you say it doesn't work for you.

Maybe you have some older/special/non-standard keyboard which has only one shift?

While I don't say your patch is a bad one, I'm trying to understand under which cases shift doesn't work, since it's definitely works for the majority of the users.

**Comment by turtleli** [comment] 2015-07-24 14:08
My bad, I introduced the regression rather recently preparing things for wx3.0.

**Comment by poodle111** [comment] 2015-07-24 14:14
Lylipad.cpp:1510 PadKeyEvent() convertes VK_LSHIFT and VK_RSHIFT to VK_SHIFT.
Also sends VK_SHIFT by Padnull v0.0.10 and SSSPSX PAD Pressure mod v1.7.1 on my enviroment (Normal 106JP USB keybord).

**Comment by avih** [comment] 2015-07-24 14:59
OK, Apparently it's broken indeed. I haven't tested shortcuts with shift recently, and now I have, and it's broken. The regression starts on June 26th when PR #598 got merged.

**Comment by avih** [comment] 2015-07-26 06:05
@turtleli are you sending a PR to fix this?

**Closed** 2015-07-26 12:02 UTC
Labels: Bug, Core, GUI/WX

**Comment by avih** [comment] 2015-07-26 12:37
Huh.. this is weird. I was about to close this issue since it's now fixed, only to find out that.. I already did that? Did github deduce that #675 fixes this and closed it itself??!?

**Comment by ssakash** [comment] 2015-07-26 12:39
it got closed a minute after the merge, Git's getting smarter :p

**Comment by Morten242** [comment] 2015-07-26 12:39
Yes, it does:
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by ssakash** [comment] 2015-07-26 12:41
@turtleli  used the keyword, That makes sense.

**Comment by avih** [comment] 2015-07-26 12:42
Huh.. `!github make me rich`
/me waits

**Comment by ssakash** [comment] 2015-07-26 13:00
Lol :laughing:
