### ISSUE TITLE
Ferrari Challenge - Trofeo Pirelli [PAL] - Hardware graphical issues.

### ISSUE THREAD

**Issue by MarcoEstevez** [PCSX2/pcsx2#1731] opened 2017-01-02 00:19 UTC
Game looks perfect on Software Mode any back-end, Hardware mode shows some ghost misplaced graphics all over the scene. At the botton, can be also seen a small bar with graphical artifacts.

![image](https://cloud.githubusercontent.com/assets/3447089/21583611/ef720f16-d088-11e6-8a61-33cd1d7c0c80.png) 

***PCSX2 version:***
PCSX2 1.5.0-20161224200947 - compiled on Dec 24 2016

***PCSX2 options:***
I tried with the most standard ones, no GS Hacks
I Used OpenGL backend with 3x IR

***Plugins used:***
GSdx32-AVX2.dll 

***PC specifications:***
Host Machine Init:
	Operating System =  Microsoft Windows 10 Home (build 14393), 64-bit
	Physical RAM     =  7986 MB
	CPU name         =  Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
	Vendor/Model     =  GenuineIntel (stepping 03)
	CPU speed        =  2.393 ghz (8 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 7fdafbbf
	x86EFlags        =  2c100000

***x86 Features Detected:***
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA

**Comment by refractionpcsx2** [comment] 2017-01-02 03:12
Looks like one for @ssakash !

**Comment by ssakash** [comment] 2017-01-02 09:26
Yeah, I can't look into this without a GS dump. The bottom issue seems like a issue due to lack of buffer size, potentially "Large Framebuffer" might help (maybe?), also it would also be useful to try the ``Half-pixel offset`` hack to check if it solves the upper blurring issues.

Also I presume the issue is limited only to upscaled resolutions? please correct me if I'm wrong.

**Comment by FlatOutPS2** [comment] 2017-01-02 10:40
Also try the "Wild Arms Offset" hack and the TC offsets. I've seen similar issues with several other racing games. The normal Half-pixel offset didn't fix it entirely. Maybe @gregory38 's new HPO version would do the trick. Does it still require `UserHacks_HalfPixelOffset_New = 1` to be added to the ini?

**Comment by MarcoEstevez** [comment] 2017-01-02 11:32
Here you have GS Dump!

https://drive.google.com/file/d/0ByJrCj2X0ZpAWWRicE5feWV0Qlk/view?usp=sharing

**Comment by MarcoEstevez** [comment] 2017-01-02 11:39
Half-pixel Offset almost fixed it   :-D

![image](https://cloud.githubusercontent.com/assets/3447089/21588546/0769057a-d0e8-11e6-97ef-b9ffd42a8ce1.png)


Half-pixel + wild arms

![image](https://cloud.githubusercontent.com/assets/3447089/21588566/556ec55c-d0e8-11e6-9410-7f40f76fdce8.png)

**Comment by refractionpcsx2** [comment] 2017-01-02 14:10
I think we need a new label, "Fixed with HW Hack" what say you? @ssakash and @gregory38 ?

**Comment by ssakash** [comment] 2017-01-02 14:39
> I think we need a new label, "Fixed with HW Hack" what say you? @ssakash and @gregory38 ?

I think a label would be useful to sort all of those cases where HW hacks are necessary to solve certain issues. However I'm not sure whether the label should be ``GSdx: Fixed with HW hack`` **(or)** just ``Fixed with HW hack``...

Regardless of all those stuffs, my current condition is rather pitiful. I don't even have the internet speed to download a single GS dump. *sigh*.

**Comment by refractionpcsx2** [comment] 2017-01-02 14:46
It should be `Fixed with HW hack`, to be inline with `Fixed with OpenGL`.

**Closed** 2017-09-29 12:47 UTC
Labels: GSdx: Hardware, GSdx: Upscaling
