### ISSUE TITLE
 Cruisin 3 by Abyss demo black screen

### ISSUE THREAD

**Issue by benderscruffy** [PCSX2/pcsx2#1309] opened 2016-04-26 08:33 UTC
PCSX2 version: GIT v1.5.0-dev-625-g87867be
CPU options: EE/IOP defaults, VUs defaults
Plugins used: GSdx GIT, SPU2-X GIT

http://www.pouet.net/prod.php?which=61225
nothing but a black screen

**Comment by Catarax** [comment] 2016-04-26 18:44
![tbsncdo](https://cloud.githubusercontent.com/assets/3964507/14829829/d5a29a66-0bed-11e6-9328-371be39f384b.png)

**Comment by refractionpcsx2** [comment] 2016-05-15 21:11
Can you see if this ever worked?

**Comment by MrCK1** [comment] 2016-05-16 02:34
Just tested it, .zip comes with .iso and .elf. Only ELF boots properly - needs IOP set to interpreter. The program is basically an 8-bit chiptune with some very neat visualizations

![gsdx_20160515222502](https://cloud.githubusercontent.com/assets/16314399/15278969/343a3f80-1aed-11e6-877f-2321ba602a8e.png)
![gsdx_20160515222352](https://cloud.githubusercontent.com/assets/16314399/15278929/e2f56280-1aec-11e6-828a-978c5454aaa9.png)
![gsdx_20160515222438](https://cloud.githubusercontent.com/assets/16314399/15278946/04b4fb10-1aed-11e6-8266-436a157df1f2.png)
![gsdx_20160515222446](https://cloud.githubusercontent.com/assets/16314399/15278950/08d5a55a-1aed-11e6-8443-4780b3ca5458.png)

**Comment by gregory38** [comment] 2016-08-17 17:37
@MrCK1 You just need IOP as interpreter ? If yes, either it is a timing issue either an instruction is badly coded on IOP. We need to find which one.

**Comment by MrCK1** [comment] 2016-08-21 16:05
@gregory38 Yes, IOP interpreter is all it needed. I'll test again now that 3 months have passed; but I'm not expecting anything different ;)

**Comment by gregory38** [comment] 2016-08-21 16:13
Well the goal is to dump all logs (add new one) to compare both CPU (recompiler vs interpreter). Then find the diff. Unfortunately there is no easy way (unlike EE code) to mix recompiler with interpreter.

**Comment by atomic83GitHub** [comment] 2021-06-07 16:15
The issue is now documented. Closing.

**Closed by atomic83GitHub** 2021-06-07 16:15 UTC
Labels: Bug, Recompiler
