### ISSUE TITLE
Massive slowdown when "No Sound" is selected

### ISSUE THREAD

**Issue by yorkiesandskittles** [PCSX2/pcsx2#456] opened 2015-02-17 15:27 UTC
1) What version of the product are you using? On what operating system?  
Latest version as of February 17th 2015 
Windows 8.1 x64  

2) What steps will reproduce the problem? 
1. Go to Config > Audio > SPU2 Plugin Settings 
2. Set "Module" to "0 - No Sound (Emulate SPU2 only)" while game is running  

3) What is the expected output?  What do you experience instead? 
I expected little/no change in FPS or even a speedup, but instead I experienced a drop from 50FPS (full speed) all the way down to 16FPS with No Sound enabled.  

4) Please provide any additional information below. 
GS utilization dropped down from ~10% to 0% and EE utilization skyrocketed from ~75% to 100%

**Comment by ssakash** [comment] 2015-02-18 14:42
what specific game does this problem occur on ?

**Comment by adamd10d** [comment] 2015-02-18 21:47
Burnout 3: Takedown (SLES-52584)

**Comment by ssakash** [comment] 2015-02-20 03:00
Sorry but, we can't reproduce this issue. I tried this in the latest dev build and the problem didn't occur and, i also asked another member to test it out and, it still didn't occur.IMO Something is wrong on your side.

**Comment by ramapcsx2** [comment] 2015-02-22 14:07
I can't reproduce the problem either. The issue might trigger only on specific hardware.

**Comment by ssakash** [comment] 2015-02-22 15:24
@adamd10d  could you try checking whether the specific problem is on the version 1.2.1 and, providing the emulog when this issue occurred can also help.

**Comment by bositman** [comment] 2015-03-01 22:19
Tried setting No sound before running the game? It sounds like something is getting messed up when the emulator tries to apply the new settings while running the game

**Comment by adamd10d** [comment] 2015-03-02 18:06
Still the same when setting no sound before running. It also seems to happen with no game, which I didn't think to check before.

**Comment by bositman** [comment] 2015-08-18 14:08
Can anyone else reproduce this? If not we should mark it as invalid..

**Comment by Nobbs66** [comment] 2015-08-18 14:13
Nope. It's probably limited to a single game or piece of hardware.

**Comment by bositman** [comment] 2015-08-19 22:09
Well it's not the game because we tested that, so if it's tied to a certain piece of HW it's probably some kinda driver bug and not our code.

**Comment by Nobbs66** [comment] 2015-08-19 23:01
Yeah, so it can be marked as invalid

**Closed** 2015-08-20 08:14 UTC
Labels: Invalid
