### ISSUE TITLE
prince of persia sands of time PAL, gsdx hardware mode causes blurriness

### ISSUE THREAD

**Issue by hcgamer** [PCSX2/pcsx2#111] opened 2014-07-12 11:00 UTC
1) Did the game ever work correctly
yes in pcsx2-r5451, but I don't know exactly at which revision it's been broken, sorry

2) What steps will reproduce the problem?
select gdsx harware mode (dx9 or dx11) and just go to the title screen, or anywhere in gameplay

3) What exactly happens when you experience this issue (listing any console errors or screen output you receive)?
the screen is blurry, pixelated

4) What version of PCSX2 are you using? On what operating system? Plugins?
Windows 7 x64
PCSX2 1.2.1
GDSx Hardware mode

5) Please provide any additional information below
tested on a fresh install, all settings to default
tested with all speed hacks deactivated, no effect
my gfx card is Sapphire HD7870 with catalyst drivers v14.4
in pcsx2-r5451, everything works just fine in hardware mode

**Comment by atomic83GitHub** [comment] 2017-12-26 14:57
So the issue can be close right?

**Comment by MrCK1** [comment] 2017-12-26 16:59
No, TC Offset isn't really a nice fix. Somebody needs to retest on latest git anyways.

**Comment by lightningterror** [comment] 2018-01-12 02:39
Merge sprite may also work or some other similar hacks. I don't believe for the status to be changed to on latest dev, only difference is it has newer hacks to play around.

**Comment by MrCK1** [comment] 2018-01-12 02:41
The new HPO implementstion may be enough.

**Comment by FlatOutPS2** [comment] 2018-01-12 11:05
No, it's not. I believe auto flush helped some, but none of the other fixes work.

X,Y Texture offset can help, but it changes per resolution so it isn't ideal and can cause other effects to move off center too.

**Comment by kenshen112** [comment] 2020-04-30 00:18
Auto Flush and Merge Sprite don't "Fix" the issue proper but they will clear up a lot of the blur. If one wants optimal settings currently. I'd say that due to the blurring even with the hacks the game looks much more correct and better at native.

**Comment by MrCK1** [comment] 2020-12-02 20:13
Closing since this is not a bug, PS2 games aren't designed to be upscaled and many have similar issues to this as such.

**Closed by MrCK1** 2020-12-02 20:13 UTC
Labels: GS: Hardware, Plugin: GS
