### ISSUE TITLE
[BUG]: Tokimeki Memorial 3 models rendering incorrectly in HW mode

### ISSUE THREAD

**Issue by leeks39** [PCSX2/pcsx2#5589] opened 2022-03-02 17:36 UTC
### Describe the Bug

If using any hardware renderer, models are only rendered on the left side of the screen. Functions perfectly in with software renderer.

### Reproduction Steps

Boot up game, start new file and progress through textboxes until a 3D model is displayed.

### Expected Behavior

Model should render in full.

### PCSX2 Revision

v1.7.2212

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 5 2600

### GPU

NVIDIA GeForce RTX 2060

### GS Window Screenshots

Software rendering:
![gs_20220302111206](https://user-images.githubusercontent.com/54217130/156414770-bc89ee82-9ab2-4bd8-a6bf-5c332f8491b2.png)

Direct3D 11 Rendering (similar results with other HW rendering)
![gs_20220302111247](https://user-images.githubusercontent.com/54217130/156414959-8c4c15f4-3a25-46bc-a2b6-b25c94269399.png)

### Logs & Dumps

GSdump:
[tokimekimemorial3halfscreenrender.zip](https://github.com/PCSX2/pcsx2/files/8171686/tokimekimemorial3halfscreenrender.zip)

**Comment by Tokman5** [comment] 2022-03-02 17:48
Try this:
39F79CBA.pnach 

gametitle=Tokimeki Memorial 3 (NTSC-J) (SLPM-65080) 
patch=1,EE,200FF000,extended,24070003 
patch=1,EE,200FF004,extended,50E50001 
patch=1,EE,200FF008,extended,24050005 
patch=1,EE,200FF00C,extended,08079350 
patch=1,EE,200FF010,extended,27BDFFF0 
patch=1,EE,201E4D38,extended,0803FC00 //27BDFFF0 
patch=1,EE,205F3630,extended,95009400 //87009400 
patch=1,EE,205F37A0,extended,95009400 //87009400
patch=1,EE,202AB20C,extended,0C03FC03 //0C07934E

**Comment by leeks39** [comment] 2022-03-02 18:05
This worked, I also found the Half-screen fix in the HW hack settings. Thank you very much for your help.

**Comment by RedDevilus** [comment] 2022-03-02 18:08
It's still a valid problem to me even if there is a workaround pnach.

**Comment by seta-san** [comment] 2023-04-07 17:48
this actually may be a regression from 1.5.27**
![Jgs1R7r](https://user-images.githubusercontent.com/8851653/230654104-6b26acfe-654f-46db-89f8-3e2468468455.jpeg)

**Comment by Mrlinkwii** [comment] 2023-04-07 17:49
Which exact commit do you know?

**Comment by seta-san** [comment] 2023-04-07 17:50
i don't know exactly. i just saw this image on japan's 5chan

**Comment by seta-san** [comment] 2023-04-07 17:50
but look at the task bar at the bottom to see what version they are running

**Comment by seta-san** [comment] 2023-04-07 19:11
idon't know . i tested the first and last builds of 1.5.27**. i tested a build in 1.5.27*. and i tested 1.4 and they all have the problem. i might have been taken in by a troll especially since it looks like it's linux running dx11 and even if you were using wine why wouldn't you use ogl and not need yet another translation layer.

**Comment by seta-san** [comment] 2023-10-11 05:59
okay. there might be a fix for this.

Texture Inside RT: Inside Target + Disable Depth Emulation

**Comment by seta-san** [comment] 2023-10-11 06:16
half the screen doesn't exist like you see in this issue.
turning on Texture Inside RT causes the right side to sort of start to come into existence and disable depth emulation solidifies it.

https://youtube.com/shorts/CDwKwjo_its?feature=share

**Comment by stenzek** [comment] 2023-10-11 07:31
As I've said many times, disabling depth is never a solution. Preventing depth lookups in the TC and making it load from local memory makes instead no sense.

**Comment by seta-san** [comment] 2023-10-11 07:33
that's fine.. but why have disable depth then?

**Comment by stenzek** [comment] 2023-10-11 07:34
It can be helpful in pinpointing where the issue might be, but it should never be used as a fix.

**Comment by stenzek** [comment] 2023-10-11 12:02
Check the game with #5589. Dump is fixed, but I added tex-in-rt to the GameDB, so the game should be fine with auto fixes too.

**Comment by seta-san** [comment] 2023-10-11 19:46
looks great

**Closed** 2023-10-12 01:56 UTC
Labels: Bug, GS: Hardware
