### ISSUE TITLE
Burnout 3: Takedown Missing Flags/Texture

### ISSUE THREAD

**Issue by davepalmeruk** [PCSX2/pcsx2#3407] opened 2020-05-21 01:34 UTC
Build 1.7.9-dev 20200520165617

Defaults from new with standard plugins. AXV2. MTVU speed-hack only. Safe (2) profile.
Started game on software OGL (fix sun glow or lighting glow effects like street signs or tunnel lighting). Loaded first race without memory card - Silver Lake.

Description:
So upon starting I notice something missing I'm sure I remember from the original hardware...
Silver Lake had flags on poles along the start/finish line. USA flags if memory is correct. The poles at 45 degrees are present off roofs/buildings, yet no flags which I think animated slightly hence 2004 mind=blown.

I doubted myself - maybe a different platform release? Checked both SW render modes, then both HW render modes at native resolution. No flags. Then tried just with enabled "Allow 8 bit textures". 

Bingo, for D3D11 HW only they show up, not for OGL HW. - Grey flags yet no texture.

[GSdumps.zip](https://github.com/PCSX2/pcsx2/files/4660141/GSdumps.zip)

Last known version to work: Unknown - Possible none.
PC specifications: Intel i7-7700, 16GB 2400mhz, RTX 2060 Super

**Comment by davepalmeruk** [comment] 2020-05-21 11:09
Hmmm ok. Not convinced they were present on PS2 - a compare video  shows no flags on the poles at 3:07 on the hardware. Odd I can find trace of them yet no in SW mode.

**Comment by tadanokojin** [comment] 2020-05-21 16:30
Disable bilinear

**Comment by tadanokojin** [comment] 2020-05-21 17:19
I can't find any video evidence of the flags on real hw. It may be a developer oversight that only works on certain versions of the map or something. The game correctly addresses the texture but it is sending 0s for ST. I can check my copy on real hw when I get a minute.

**Comment by tadanokojin** [comment] 2020-05-21 18:30
@MrCK1 confirmed the flags aren't there on real hw on his copy.

**Comment by tadanokojin** [comment] 2020-05-23 22:13
I'm gonna close this since the flags aren't there on real hw as far as we can tell.

OP if you notice anything else off let us know.

**Closed by tadanokojin** 2020-05-23 22:13 UTC
