### ISSUE TITLE
[BUG]:  Shadow Hearts: Covenant Crash during screen transition load

### ISSUE THREAD

**Issue by rockettuner** [PCSX2/pcsx2#6914] opened 2022-08-25 12:30 UTC
### Describe the Bug

During a screen transition, where it fades to black to load the next area, it get's stuck. It seems to randomly happen.

### Reproduction Steps

Move from one area to another causing an area load.

### PCSX2 Revision

1.7.3242

### Operating System

Windows 10 (64bit)

### CPU

Ryzen 5 2600

### GPU

GTX 1660ti

**Comment by refractionpcsx2** [comment] 2022-08-25 12:31
Turn on the fast cdvd speedhack and it will likely start working.

**Comment by rockettuner** [comment] 2022-08-25 14:04
nope, still happens

**Comment by refractionpcsx2** [comment] 2022-08-25 14:42
Well, yeah, cos they're old, probably pre to me changing the CDVD stuff (which is the cause of it).

I thought FastCDVD got around it though, so I'm surprised there..

**Comment by refractionpcsx2** [comment] 2022-08-25 18:06
Have you got a memcard save just before the transition that crashes?

also how consistently does it crash?

**Comment by rockettuner** [comment] 2022-08-25 20:11
It's not a specific transition. I've been slowly progressing by getting from save point to save point. When it crashes I just load the last save point and continue and it doesn't crash at the point it crashed before. it's super inconsistent.

**Comment by refractionpcsx2** [comment] 2022-08-25 20:17
Can you try it on #6916 once it's built please.

**Comment by rockettuner** [comment] 2022-08-25 20:41
sure

**Comment by rockettuner** [comment] 2022-08-27 13:02
yeah, seems to have fixed it. Thanks.

**Comment by refractionpcsx2** [comment] 2022-08-27 13:02
whoa don't close it, I haven't committed it yet.

**Comment by rockettuner** [comment] 2022-09-19 20:48
sure

**Comment by refractionpcsx2** [comment] 2022-09-19 20:54
Thanks :) Sorry I meant the PR you originally tested, just to be clear, not the nightly builds :D

**Comment by rockettuner** [comment] 2022-09-19 21:07
That, I might not be able to do, I've been updating the nightly and don't remember the PR version number, I tested

**Comment by refractionpcsx2** [comment] 2022-09-19 21:30
It's linked above

**Comment by johnnymaq** [comment] 2022-10-17 04:04
I'm still replicating this on the past few versions, including the most recent. Been using savestates to combat it since it's random. Had it happen maybe 8 times through the playthough. Includes most black screen transitions including 'after battle into world' and cutscenes.

**Comment by Godsmercenary8** [comment] 2023-03-03 07:03
This problem isn't resolved. It is happening to me in 1.7.4179

**Comment by kudas20** [comment] 2023-04-02 12:49
I also like to report that the issue still occurred in v1.7.4320. I already tested with enabling and disabling Fast CDVD, and both still freeze mostly when going into new area in dungeon. The freeze mostly occurred when I walk too long searching for enemy in one area and then go into another area, then the black screen occurred when transitioning. Sometimes it freeze when transitioning to save screen too.

**Closed** 2023-10-08 11:14 UTC
Labels: Bug
