### ISSUE TITLE
[BUG]: Somewhere between v1.7.4459 and v1.7.3425 Metal rendering performance has been degraded.

### ISSUE THREAD

**Issue by NotLazy** [PCSX2/pcsx2#8781] opened 2023-05-03 15:18 UTC
### Describe the Bug

When running Sly 3 with Metal renderer on MacOS, performance is affected based on which version of PCSX2 I run.

### Reproduction Steps

Using an M1 Pro Macbook Pro with 16GB of ram, use PCSX2 v1.7.4459 to run Sly 3, and you'll notice 7fps or lower in pretty much the entire game.

### Expected Behavior

Using an M1 Pro Macbook Pro with 16GB of ram, use PCSX2 v1.7.3425 to run Sly 3, and you'll notice 50-59fps in most parts of the game with certain scenes encountering lower (30-49fps).

### PCSX2 Revision

v1.7.4459

### Operating System

macOS 13 (Ventura)

### CPU

M1 Pro

### GPU

M1 Pro

### GS Settings

I'm using settings from [this](https://www.reddit.com/r/macgaming/comments/smvqum/these_are_the_best_pcsx2_settings_for_the_latest/) reddit post, however, no matter what settings I use, I only encouter 7fps on 4459 and I only encounter 50-59 on 3425 by using the settings in that post.

**Comment by NotLazy** [comment] 2023-05-03 15:19
Note, this issue may affect other games, Sly 3 is just something that is very easy to notice the issue on, as it's the most "intensive" game in my library.

**Comment by Mrlinkwii** [comment] 2023-05-03 15:22
are you upscaling

**Comment by lightningterror** [comment] 2023-05-03 15:26
@NotLazy Can you bisect which build introduced the issue?

**Comment by stenzek** [comment] 2023-05-03 15:37
It _could_ be the `no_ds` improvements, which regressed performance in Vulkan, which I fixed in #8716, but didn't apply to Metal (since I can't test it).

**Comment by NotLazy** [comment] 2023-05-03 15:44
> Edit: Also, don't use stupid settings from users, stick with the defaults, only really changing upscaling.

I'd like to mention the blending accuracy being changed from default to Ultra (or "Maximum" on my GS) actually _did_ improve performance for me, specifically in sly 3

**Comment by DigitalMajestic** [comment] 2023-05-03 19:20
Confirmed on M1 Ventura, when running the attached (Sly 2) GS dump in v1.7.3425 I can reach 330% speed, but in 1.7.4460 I can't even reach 40% speed.



<img width="1440" alt="1-7-3425" src="https://user-images.githubusercontent.com/40978750/236021795-72a4e5ea-894f-4049-891b-4319cf6c1f64.png">
<img width="1435" alt="1-7-4460" src="https://user-images.githubusercontent.com/40978750/236021816-dfc7da37-4a83-4919-8553-ec83f9e80d26.png">

[Sly_2_-_Band_of_Thieves_SCUS-97316_20221019165824.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/11390191/Sly_2_-_Band_of_Thieves_SCUS-97316_20221019165824.gs.xz.zip)

**Comment by DigitalMajestic** [comment] 2023-05-03 19:44
Bisected to 1.7.4125 #8210

**Comment by refractionpcsx2** [comment] 2023-05-03 21:24
@stenzek was close, it was the no_rt improvements. 

So what the game does, is hundreds of draws, 2 points (yes, 2 dots, not sprites or triangles) swapping between drawing to the framebuffer and only updating the depth buffer.  So it's constantly switching between the two.

putting the old no_rt back in, which doesn't disable it seems to resolve the performance issue, however we've been talking about a "buffered context" where if a game is swapping between 2 contexts and changing nothing else (like this game is doing), then firing it all as 2 draws, instead of a few hundred + render pass/state updates, so it should massively improve it for all renderers.

For now I'm not sure what the best way forward is, it could be an optimisation that Sten did with render passes which Metal needs to stop it tanking as he mentioned before, but that's kinda beyond me.

Maybe @TellowKrinkle can take a look?

**Comment by refractionpcsx2** [comment] 2023-05-03 22:29
@TellowKrinkle I have fixed this with #8784 so i dunno if you're happy with that and just want me to convert it in to a normal PR and merge that, or if you wanna expand further on the other changes in #8716?  I didn't wanna do too much more as coding blind is not fun :P

**Closed** 2023-05-03 23:10 UTC
Labels: Bug, GS: Hardware, Regression
