### ISSUE TITLE
[BUG]: Setting BIOS folder to an invalid folder path string creates 3 different folders in the pcsx2 folder

### ISSUE THREAD

**Issue by ISuckGood** [PCSX2/pcsx2#8218] opened 2023-02-21 17:35 UTC
### Describe the Bug

Random folders created when changing bios folder to an invalid folder

### Reproduction Steps

1. Open c:\Users\xxxsource\repos\pcsx2\bin\pcsx2-qt.exe
2. Settings -> Bios
3. delete directory folder and add "xxx"
4. press enter
5. close pcsx2
6. observe 3 folders in the root
c:\Users\xxx\source\repos\pcsx2\bin\x\
c:\Users\xxx\source\repos\pcsx2\bin\xx\
c:\Users\xxx\source\repos\pcsx2\bin\xxx\

### Expected Behavior

No folders created in root of pcsx2 exe if the string is invalid

### PCSX2 Revision

PCSX2 Nightly - v1.7.4118

### Operating System

Windows 11

**Comment by refractionpcsx2** [comment] 2023-02-21 17:37
Duplicate of #7215

**Closed by refractionpcsx2** 2023-02-21 17:37 UTC
Labels: Bug, GUI/Qt
