### ISSUE TITLE
Glare issues in "From Russia, with love"

### ISSUE THREAD

**Issue by twarnercool2** [PCSX2/pcsx2#1128] opened 2016-01-18 08:05 UTC
Graphics issue:

Issue title: Glare still visible in cover

-PCSX2 version: v1.5.0-dev-110-ge472713

-PCSX2 options: Defaults, no settings modifications affect the issue

-Plugins used: GSdx, SPU2-X, xpad, Linuz ISO/Gigaherz CDVD, the rest are null plugins

-Plugin settings: Defaults, no settings modifications affect the issue

-Description: The glare of lights are visble in walls

http://i.imgur.com/PucS92x.jpg?1

-How to replicate: Look at wall with glare

-Last known version to work: Unknown

**Comment by willkuer** [comment] 2016-01-18 10:12
Can you please try to set skipdraw to a very large value? IIRC such an issue is solved in GT4 using skipdraw of 27.

**Comment by ssakash** [comment] 2016-01-18 11:16
Is the issue present on software mode ? just to make sure that the issue is only specific to the hardware renderer.

if the issue is solved on software renderer then please provide a comparison screenshot of a picture  with issue and without issue , so those who have never played the following game can identify what's actually the issue.

**Comment by FlatOutPS2** [comment] 2016-02-05 23:18
As the OP hasn't responded yet: The issue is gone at Skipdraw 5(on skipdraw 3 there are hundreds of lights visible for some reason), and it isn't present in software mode.

**Comment by gregory38** [comment] 2016-04-26 16:50
Could someone test latest openGL git.

**Comment by FlatOutPS2** [comment] 2016-04-26 16:57
I tested it on 1306 PR, and the then latest GIT, no change.

**Comment by gregory38** [comment] 2016-04-26 16:58
Damn you're efficient. Thanks you for the test.

**Comment by FlatOutPS2** [comment] 2016-09-12 21:14
This issue hasn't been solved. The lights in the game also cause massive slowdown. It runs at over 100 fps when facing away from the lights, and in single digits when looking towards the lights. The slowdown also affects Software mode, but is less severe(the lights aren't visible through walls in SW mode). Skipdraw hack set to 5 removes the issue visibly in HW mode, but the slowdown remains.

**Comment by MrCK1** [comment] 2018-01-03 05:12
Anyone able to try autoflush? I don't believe it was available when this was made.

**Comment by FlatOutPS2** [comment] 2018-02-24 19:32
This issue can be resolved in OpenGL by using `Unscale Point and Line`.

**Comment by MrCK1** [comment] 2018-12-02 07:19
Issue can be closed since UPL is enabled by default. No problems were shown in DX11 or OGL.

**Closed by MrCK1** 2018-12-02 07:19 UTC
Labels: GSdx: Hardware, GSdx: Upscaling, Plugin: GSdx
