### ISSUE TITLE
[Regression]: Games not working in specific renderers

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#8260] opened 2023-02-25 18:23 UTC
### Describe the Bug

Launching or playing specific games in specific renderers crashes it and overflows the RAM. It's like it's not exiting properly.

Like 007 and potentially others.

Vulkan:

`Unhandled exception at 0x00007FFA998D4408 (ntdll.dll) in pcsx2-qtx64-avx2-dev.exe: 0xC0000005: Access violation reading location 0x0000000000000000
`
![image](https://user-images.githubusercontent.com/24227051/221373043-7d05494a-bf0d-4ea8-a69e-f04f5457877b.png)
![image](https://user-images.githubusercontent.com/24227051/221373053-770cb2cc-a432-4706-ac25-e08d2cf0a79f.png)
![image](https://user-images.githubusercontent.com/24227051/221373054-22030b2a-e719-4bf3-b747-62014c3a8fce.png)
![image](https://user-images.githubusercontent.com/24227051/221373060-4a5a8ead-4d2f-4d03-8483-d75b1814598e.png)

D3D11:
![image](https://user-images.githubusercontent.com/24227051/221373451-bea53b3b-b5a9-4850-b46c-907a8f710a11.png)

D3D12:

![image](https://user-images.githubusercontent.com/24227051/221373206-94a82f0b-1f53-4a0c-87bd-305a4c1c302c.png)

OpenGL:

![image](https://user-images.githubusercontent.com/24227051/221373275-fe670916-0a1d-484c-aafa-3f722d8d6e4a.png)

![image](https://user-images.githubusercontent.com/24227051/221373310-fe65e2b9-9f49-4f04-9135-b341e747fc53.png)

Software:

![image](https://user-images.githubusercontent.com/24227051/221373339-0f79e62f-5b0d-40bc-95ae-8f7e7a534a69.png)

### Reproduction Steps

- Run a game (not all games)
- Crashes

### Expected Behavior

Not crash

### PCSX2 Revision

v1.7.4141

### Operating System

Windows 10 (64bit)

### If Linux - Specify Distro

/

### CPU

i7-9750H

### GPU

RTX 2060M

### GS Settings

/

### Emulation Settings

/

### GS Window Screenshots

/

### Logs & Dumps

[007_-_Everything_or_Nothing_SLUS-20751_20230225144134.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/10831965/007_-_Everything_or_Nothing_SLUS-20751_20230225144134.gs.zst.zip)

**Comment by ISuckGood** [comment] 2023-02-25 19:09
which game crashes ?

**Comment by JordanTheToaster** [comment] 2023-02-25 19:11
It seems to be related to DATE in some way when crashing with DX12.

**Comment by RedDevilus** [comment] 2023-02-25 19:12
If I knew that, I wouldn't say 'and others'. Test it instead of posting I dunno.

**Comment by ISuckGood** [comment] 2023-02-25 20:08
I tried 4 games on my list on windows using local built exe and i didnt see any memory issues. i started the each game and changed rendered 10 times

**Comment by omega-tuna** [comment] 2023-02-25 23:20
Oh it's not crashing but it certain is maxing out my RTX 3060 Ti in opengl even at native res. It would probably cause a crash for sure depending. I'm not seeing high ram usage but I only played the intro mission I'd say there is something wrong with it for sure using opengl since it's fine for me in vulkan, D3D11, D3D12 and Software

**Comment by ISuckGood** [comment] 2023-02-25 23:22
> Oh it's not crashing but it certain is maxing out my RTX 3060 Ti in opengl even at native res (runs extremely slowly). It would probably cause a crash for sure depending. I'm not seeing high ram usage but I only played the intro mission but I'd say there is something wrong with it for sure using opengl since it's fine for me in vulkan, D3D11, D3D12 and Software

Are you using your own built exe or  you downloaded it using the automatic updater ?

**Comment by omega-tuna** [comment] 2023-02-25 23:27
It would make less sense to use your own build when testing, but i could try another build for sure

**Comment by omega-tuna** [comment] 2023-02-25 23:47
Funny enough I didn't even have to roll my own build. It stopped doing it after i clicked restore defaults for the options. Maybe some setting isn't being applied correctly. I do recall messing with manual game fixes quite a bit before when I was trying out stuff with ridge racer V

**Comment by refractionpcsx2** [comment] 2023-02-25 23:49
we know about the speed regression in Ridge Racer V intro, just haven't had time to look in to it yet.

**Comment by omega-tuna** [comment] 2023-02-25 23:54
Oh no i meant 007 was going slowly till i restored my default settings. I meant i was playing around with the manual game fixes with ridge racer V before testing it out

**Comment by Shoegzer** [comment] 2023-02-26 00:58
Seeing the same issue here with True Crime: NYC. Constant crashing in specific spots while driving throughout the city, and in cutscenes with Vulkan renderer, but it's fine with OpenGL and Software. Crashing occurred on a build made immediately before the recent #8242 was merged that made rendering changes for this title, but crashing did not occur on builds made a few weeks ago and prior.

System information:

* OS: Linux Mint 21.1 / kernel 5.19
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070 / driver 525.78

**Comment by ISuckGood** [comment] 2023-02-26 01:38
I managed to reproduce a crash with this settings 
1. directx12 and 2k resolution  in ace combat 4 intro and in Digital devil saga 1 intro . With opengl and dx11 it doesnt crash but its some weird slow downs sometime. Vulkan seems fine.

**Comment by stenzek** [comment] 2023-02-26 03:04
DX12 should be fixed with #8265.

**Comment by omega-tuna** [comment] 2023-02-26 03:59
So my issue wasn't even related to the one here, lol

**Comment by ISuckGood** [comment] 2023-02-26 11:09
> DX12 should be fixed with #8265.

yes dx12 dont crash anymore in ace combat 4

**Closed** 2023-02-26 15:37 UTC
Labels: Bug, Regression
