### ISSUE TITLE
PCSX2 unabled to load Reshade when using OpenGL

### ISSUE THREAD

**Issue by hellbringer616** [PCSX2/pcsx2#2356] opened 2018-03-28 15:58 UTC
***PCSX2 version:***
`` v1.5.efc1274``

***PCSX2 options:***
``Default for everything except the following:
Speedhacks: MTVU and Recommended Speedhacks are enabled.
GSDX: OpenGL Hardware (or software)
Custom Resolution of 3600x2400
Biliner forced
Accurate date set to high.``

***Plugins used:***
``(Relevant/Non-default settings of GS/PAD/SPU2/CDVD/USB plugins)``

***Description of the issue:***
``When launching PCSX2 with Reshade an error "(2) Cannot find suitable pixel Format." the PCSX2 window stays black and says it cannot load plugins.``

***How to reproduce the issue:***
``Install reshade to PCSX2 directory, configure PCSX2 to use GSDX OpenGL hardware or software``

***Last known version to work:***
``(If the issue isn't present in an older PCSX2 version, it would be helpful to mention the full title of that version. Narrowing it down to the build/commit that first introduced the issue is even better!)``

***PC specifications:***
``CPU: INtel Core i7 8700k 5ghz
GPU: GTX 1080 ti
OS: Windows 10 Home x64``

**Comment by hellbringer616** [comment] 2018-03-28 16:00
#2106 has a fix posted by @RibShark when using DX11, however this does not work for OpenGL.

**Comment by lightningterror** [comment] 2018-03-28 16:19
Weird I just tried it and it works. What is the opengl32.dll version that you have from Reshade ?

**Comment by hellbringer616** [comment] 2018-03-28 16:45
it's 3.1.1.243

But i think you're right; I've been searching and it seems to only be PCSX2 with Windows 10 that has the issue :/

**Comment by mirh** [comment] 2018-03-30 18:08
Because the fix was d3d11-specific? 
Try `set __COMPAT_LAYER=InjectDLL<.\opengl32.dll> && pcsx2.exe`

If that works.. I think you should open a [ticket](https://reshade.me/forum/troubleshooting) with the reshade guys.

**Comment by hellbringer616** [comment] 2018-03-30 18:39
@mirh 
I am not sure how to do that as he posted a custom d3d11.dll that when placed in the pcsx2 folder it works.

I'm not sure it's a Reshade issue as Reshade works fine with other programs; Skyrim, Fallout, Redream, Dolphin. all working

**Comment by mirh** [comment] 2018-03-30 19:13
Replace opengl32.dll with whatever the dll name reshade use. 

We weren't sure either whose fault it was, but eventually it seems like a problem of the injector.

**Comment by mirh** [comment] 2018-03-31 09:04
If you *keep reading the thread*, you see the same is achievable with some command from cmd. 
Again, instead of pointing to d3d11 dll, you should point to opengl32 one.

**Comment by shinra358** [comment] 2018-04-02 06:35
@mirh can you put this in .bat format?:
set __COMPAT_LAYER=InjectDLL<.\opengl32.dll> && pcsx2.exe

**Comment by hellbringer616** [comment] 2018-04-10 17:13
@shinra358 
I've made a batch file; however i am at work and thus i cannot test it.

If you wouldn't mind doing so and reporting back, that would be amazing.
[Win10-OGL-ReshadeFix.zip](https://github.com/PCSX2/pcsx2/files/1895618/Win10-OGL-ReshadeFix.zip)

**Comment by shinra358** [comment] 2018-04-10 17:37
I will test it when i get off. Thanks. Im on win7 btw just in case that
will interfere w something since i see w10 in the filename.

**Comment by hellbringer616** [comment] 2018-04-10 17:56
Afraid so.
From my understanding this issue is limited to Windows 10; PCSX2; and Reshade when used together.

**Comment by shinra358** [comment] 2018-04-10 17:58
Issue is on win7 as well.

**Comment by shinra358** [comment] 2018-04-10 17:59
I still use 1.1 bcuz 3.0 not so good.

**Comment by lightningterror** [comment] 2018-04-10 18:28
I believe anything lower than 3.1 won't work (since Reshade provides it's own gl dll, and if the gl version is lower than 3.1 it won't work on pcsx2 1.5).

**Comment by shinra358** [comment] 2018-04-10 19:06
Without anything, it works for me, i can see the upper left dialog but the
screen is all black. You can still hear the game. If i window the game, u
can see it for a brief moment b4 it goes black again. So, knowing that, do
you still think the gl versions are the cause? Cant remember what opengl
version reshade 1.1 uses.

**Comment by hellbringer616** [comment] 2018-04-10 20:01
@lightningterror I believe Shinra means Reshade version 1.1, not OGL v1.1
I use v3.1 as it has a load of extra shaders; by my understanding; though i've just recently gotten into Reshade.
@shinra358 
That is a different issue than mine; which is an error saying "(2) Cannot find suitable pixel Format".
However it sounds like the same issue that was reported in the other thread that i nabbed the fix from; so using the above fix might work, it's at least worth a shot.

A word of caution: All i did was turn the code into a batch file; so I've no clue how to undo it.

**Comment by shinra358** [comment] 2018-04-11 03:54
for me, the .bat just shows for a split second and disappears. launched it in admin mode. nothing happened and still black screen on opengl.

**Comment by Arcadius34** [comment] 2019-03-02 21:03
Just going to put these out here. ReShade's latest version, 4.2.0 as of March 1st, 2019, has fixed the OpenGL pixel format issue... issue.

So, you can now use OpenGL PCSX2 renderer with ReShade! Yay!

Alongside that, with a simple fix, you can now have ReShade working with PCSX2 in both D3D11 and OpenGL renderers, yay. Good job on ReShade Crosire for fixing that.

**Comment by mirh** [comment] 2019-03-03 13:25
https://reshade.me/forum/troubleshooting/4777-opengl-problems-with-reshade-4-0#32661
And this is the explanation. 

So.. can we close now?

**Comment by MrCK1** [comment] 2019-04-23 20:39
Sounds like it's working :)

I'll close this.

**Closed by MrCK1** 2019-04-23 20:39 UTC
Labels: Fixed in OpenGL, Upstream | External
