### ISSUE TITLE
PCSX2 installation want to remove other programs

### ISSUE THREAD

**Issue by Vitali80** [PCSX2/pcsx2#3009] opened 2019-07-05 13:41 UTC
I tried to install PCSX2 from PPA on Linux Mint 19.1 and it wants to remove other software as Audacious or DOSBox! Is this a bug?

> ~$ sudo apt-get install pcsx2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  audacious-plugins-data libampache-browser libaudcore5 libaudgui5 libaudqt2
  libaudtag3 libcue1 libguess1 libportmidi0 libqt5multimedia5 libsdl-net1.2
  libsidplayfp4 libutf8proc2 mame-data python3-pyqt5.qtopengl
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libaio1:i386 libnotify4:i386 libportaudio2:i386 libsdl2-2.0-0:i386
  libsndio6.1:i386 libsoundtouch1:i386 libwayland-client0:i386
  libwayland-cursor0:i386 libwayland-egl1:i386 libwxbase3.0-0v5:i386
  libwxgtk3.0-0v5:i386 libxkbcommon0:i386 libxss1:i386
Suggested packages:
  sndiod:i386
Recommended packages:
  notification-daemon:i386 libusb-0.1-4:i386
The following packages will be REMOVED
  antimicro audacious audacious-plugins dosbox ffmpeg fs-uae fs-uae-launcher
  guvcview hatari libavdevice57 libguvcview-2.0-2 libmikmod3 libsdl-sound1.2
  libsdl2-2.0-0 libsdl2-ttf-2.0-0 libwayland-egl1-mesa mame mgba-qt mgba-sdl
  pcsxr stella
The following NEW packages will be installed
  libaio1:i386 libnotify4:i386 libportaudio2:i386 libsdl2-2.0-0:i386
  libsndio6.1:i386 libsoundtouch1:i386 libwayland-client0:i386
  libwayland-cursor0:i386 libwayland-egl1:i386 libwxbase3.0-0v5:i386
  libwxgtk3.0-0v5:i386 libxkbcommon0:i386 libxss1:i386 pcsx2:i386
0 to upgrade, 14 to newly install, 21 to remove and 0 not to upgrade.
Need to get 9,298 kB of archives.
After this operation, 275 MB disk space will be freed.

**Comment by gregory38** [comment] 2019-07-05 16:27
Yes but not our bug.

Try to install the additional package 1by 1.

**Comment by RedPanda4552** [comment] 2019-07-14 00:22
Looks like apt might have a laundry list of other things to take care of.

Consider doing a big sweep to make sure everything is "clean" first:

`sudo apt autoremove` && sudo apt update && sudo apt upgrade`

If this is still happening afterwards, might be something to keep an eye on, but as greg and LT have pointed out, this is probably upstream and an issue with apt or the like.

**Comment by SergeyLatyshev** [comment] 2019-07-19 05:12
Use flatpak instead.
`sudo add-apt-repository ppa:alexlarsson/flatpak`
`sudo apt install flatpak gnome-software-plugin-flatpak`
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
`flatpak install flathub net.pcsx2.PCSX2`

**Comment by lightningterror** [comment] 2019-07-23 15:42
I will close this since the issue is external.

**Closed by lightningterror** 2019-07-23 15:42 UTC
Labels: Upstream | External
