### ISSUE TITLE
[BUG]: Dear Boys Fast Break - Game prompts disabled in basketball game

### ISSUE THREAD

**Issue by Sukotto-1999** [PCSX2/pcsx2#10800] opened 2024-02-10 12:20 UTC
### Describe the Bug

The game does not react to button prompts in a basketball game. Could be related to an issue related to real hardware (modchip)

https://youtu.be/G1VQpPb8Ue0

### Reproduction Steps

Start a basketball game in Dear Boys Fast Break

### Expected Behavior

Game works perfectly

### PCSX2 Revision

1.7.5552

### Operating System

Windows 11

### CPU

Intel Core i5-9400F

### GPU

NVIDIA GTX 1650

**Comment by Mrlinkwii** [comment] 2024-02-10 12:39
cannot reproduce on latest nightly , by default the game dosent enable the analog sticks , you have to turn them on manually to use them

**Comment by Sukotto-1999** [comment] 2024-02-10 12:50
> cannot reproduce on latest nightly , by default the game dosent enable the analog sticks , you have to turn them on manually to use them

What settings did you use?

**Comment by Mrlinkwii** [comment] 2024-02-10 12:59
default settings ,  in game you need  to hold L1 for the button prompts to appear over the player , thats mentioned in the controls sections
![image](https://github.com/PCSX2/pcsx2/assets/17685135/7ee3380d-a234-4643-9513-ce1ed0946de3)

**Comment by TheTechnician27** [comment] 2024-05-28 07:12
As this issue seemingly reflects a misunderstanding by the user about how the underlying game works and not a bug in PCSX2's emulation, is it safe to close it?

**Closed** 2024-05-28 08:54 UTC
Labels: Bug
