### ISSUE TITLE
Crash Bandicoot The Wrath of Cortex "Under water levels"

### ISSUE THREAD

**Issue by JOHN30011887** [PCSX2/pcsx2#2380] opened 2018-04-11 23:40 UTC
***PCSX2 version:***
1.5.0-dev-2194

***PCSX2 options:***
Default

***Plugins used:***
![capture 2](https://user-images.githubusercontent.com/12979984/38965834-e465e342-4376-11e8-94aa-c95f81184b66.PNG)

***Description of the issue:***
Underwater texture is broken in all the underwater levels, first one to see this issue is level 7

Software mode (how it should look)
![opengl software](https://user-images.githubusercontent.com/12979984/38648213-ea36dffe-3de7-11e8-9be9-60c27e73ef33.png)
opengl hardware mode with native resolution
![opengl hardware with native resolution](https://user-images.githubusercontent.com/12979984/38648212-ea1ec608-3de7-11e8-8dcd-d604e342682e.png)
opengl hardware with any higher resolution
![opengl hardware with any higher resolution](https://user-images.githubusercontent.com/12979984/38648211-ea0776c4-3de7-11e8-8955-c8fa0c9cf7e2.png)

***How to reproduce the issue:***
Happens with all hardware options, software it will show correct but obv very low resolution
Here is my settings i use for this game
![capture](https://user-images.githubusercontent.com/12979984/38965837-f2350ee4-4376-11e8-9358-b8a3e9c064b0.PNG)

***Last known version to work:***
There is none
However the water can be turned off using HW Hacks then select "Disable Depth Emulation"
The option "Disable Depth Emulation" also fixed the top left texture flicker

***PC specifications:***
windows 10 64bit
i7 4790k
gtx 980
16gb ram

**Comment by MrCK1** [comment] 2018-04-12 13:33
Don't use custom resolution or large framebuffer and enable Accurate Date. Use a resolution multiplier instead and see if that fixes it first.

If that doesn't work, turn up the blending accuracy(I don't know if this game has a half-bottom issue)

**Comment by MrCK1** [comment] 2018-04-12 13:34
You're also using old plugins,.make sure you upgrade your dev build if necessary and choose the plugins that have 2018 in the string.

**Comment by JOHN30011887** [comment] 2018-04-12 16:44
yeah iv already tried the resolution multipliers, makes no difference but thanks about mentioning the others, il now just keep large framebuffer off and keep enabled Accurate Date for this game, 
iv often messed with the settings to see for fixes and atm turning off the water effect seems the only solution for now

i have often thought this game for atleast the water levels suffers from the half bottom issue

And omfg you are right, for past year iv always just copied over the new dev files and when i open pcsx2 it would ask to import or overwrite and i always said import 

It has made no difference to this game, with the proper 2018 plugins, still looks like the images i posted but thanks again for help :)

**Comment by JOHN30011887** [comment] 2018-04-19 01:08
Seems this game does have that half bottom issue, this is level 1, has same fog wall issue as Crash Twinsanity 

![pcsx2_2018_04_19_02_05_08_326](https://user-images.githubusercontent.com/12979984/38965766-7a61a97c-4376-11e8-81f7-6f6d4b2d28a8.png)

**Comment by legend800** [comment] 2018-04-19 01:57
Yeah, try skipdraw hack until it fixes it. In Matrix - Path of Neo it was 4. Even if you use the new skipdraw offset, it still caused other side effects that barely made it worth it. Really can't wait for a fix for that.

**Comment by killerjn** [comment] 2018-05-17 03:30
try the following disable this option (interlacing = none)

![2018-05-16 22_26_08-gsdx settings](https://user-images.githubusercontent.com/32747059/40155309-a5811802-5958-11e8-8f5f-eaa02fa9f0c1.png)

**Comment by JOHN30011887** [comment] 2018-05-19 22:37
You dont have it cause your on directx 9, dx9 and 11 seems to disable the fog by default (depth emulation)
With the under water level i listed you will most likely see scrambled textures on the top left and missing water texture

**Comment by JOHN30011887** [comment] 2018-05-19 22:41
[https://youtu.be/5mRn2SM9PLM?t=156](url)

Not my vid but this is how fog should look for that level

Also as said before im sure this is that half bottom issue as it affects fog and water :)

**Comment by Macley-Kun** [comment] 2018-10-11 20:32
![image](https://user-images.githubusercontent.com/26381427/46832072-63a73300-cda5-11e8-9b52-fe7941849bfb.png)
I use the above settings, and i changed the frame skip to 12!
![image](https://user-images.githubusercontent.com/26381427/46832095-702b8b80-cda5-11e8-94da-149ad7328e0a.png)
It's quite alot better, haven't tested it out proper. But maybe this helps abit until the issue is being assigned.

**Comment by JOHN30011887** [comment] 2018-10-15 17:41
skipdraw left box put a 1 and right box put a 3

**Comment by MrCK1** [comment] 2018-12-10 21:40
Some depth work has been done on DX. You could try latest git but I wouldn't expect any positive change.

**Comment by JOHN30011887** [comment] 2018-12-10 22:59
Yeah i was proper messing/testing with dx11 on latest version, since i can now disable depth setting but no luck, still the same issues as above unfortunately

**Comment by JOHN30011887** [comment] 2019-01-21 16:52
Disk region type  = NTSC
Game CRC = 0x103B5706

**Comment by lightningterror** [comment] 2019-01-21 16:56
Can you upload a gs dump, same spot as the issue in the last pic ?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by JOHN30011887** [comment] 2019-01-21 17:17
So i re tested with the latest version v1.5.0-dev-2899-g548d6b31b

same settings and crc hack is on partial, tried dx11 and opengl hardware, 
now all the water is gone completely in the water levels even the bubbles until i reached the sub then the screen went to sh*t, heres pic to show what i mean
![screenshot 2](https://user-images.githubusercontent.com/12979984/51489221-9ba81400-1d9f-11e9-8c92-0256b5ed15b2.png)

As for level 1 that fog wall is completely gone now so fog is disabled which is better than the half screen issue as before

@lightningterror i can try make one but since the fog wall (my last pic) is now gone it might be waste of your time?

seems for now only issue is when entering the yellow sub machine that happens later in level 7

**Comment by JOHN30011887** [comment] 2019-01-21 18:03
https://mega.nz/#!mlYgkS5a!5zwHm7IwxcSS9VAz5aJK2LZdhPg2kbqY_ZT-MhWyln0

Here are 4 GS Dumps
1 - broken water (yellow sub)
2 - Broken water (water should fill whole screen)
3 - broken water (top left textures flickering)
4 - fog wall

Only one that now shows up even when crc hack is on partial is 1 - broken water (yellow sub)
the rest dont show, i put my crc hack to debug when i made the 4 of these

As i said above with latest pcsx2 issues 2,3 and 4 are removed when on crc hack partial but i thought id add them just incase for more help

**Comment by JOHN30011887** [comment] 2019-04-09 23:19
Was the files of any use? :)

**Comment by lightningterror** [comment] 2019-04-09 23:50
Ah right, I forgot to add the extra info here, unsupported channel shuffle.

```
T:Oth	ID:75	S:Cache	=> TC: Lookup Target(Color) 3072x3072, miss (0x3600, C_32)
T:Oth	ID:75	S:Cache	=> TC: dst Color hit (full): 62 (0x2200, P_8)
T:Error	ID:75	S:Mid	=> Reading RT as a packed-indexed 8 bits format
T:Oth	ID:75	S:Cache	=> TC, 1024-bit PaletteMap (Size 49): Added new palette.
T:Error	ID:75	S:Mid	=> Channel shuffle effect detected (2nd shot)
T:Error	ID:75	S:Mid	=> Channel not supported
```

Debug build also seems to hit this assert as well
https://github.com/PCSX2/pcsx2/blob/e73607395b12da518390a58105500dc636f8d973/plugins/GSdx/Renderers/HW/GSTextureCache.cpp#L140

**Comment by lightningterror** [comment] 2019-09-19 14:10
@JOHN30011887 why was the issue closed?

**Comment by JOHN30011887** [comment] 2019-09-19 14:44
I can reopen it if you want?

Personally i closed it as i got rid of my ps2 disk and iso, so i cant further test this issue, and since i was the one to report it and pretty much the only person in here complaining about it i thought i should close it so the issues page hasn't got reports open that cant by looked at by the person that created it

**Comment by JOHN30011887** [comment] 2019-09-19 14:46
Ah ok sorry :)

**Comment by Macley-Kun** [comment] 2019-09-19 14:49
>  since i was the one to report it and pretty much the only person in here complaining about it
Actually, me and some other people also joined this discussion with the same problem :P using the software way did work as a workaround, but isn't preferd.

I'm sure this can be tested by using some iso that is found on the internet (i do not endorse piracy, but for the sake of fixing a bug i would say it's ok).

**Comment by Macley-Kun** [comment] 2019-09-19 14:56
Excuses, i wanted to refer that multiple users have this issue aswell, like me. I'm sure someone else also has an iso that can replicate the issue.

**Comment by JOHN30011887** [comment] 2019-09-19 14:58
Its not an excuse so dont be an ass!

**Comment by Macley-Kun** [comment] 2019-09-19 14:59
I said sorry b/c i said a bad word that was flagged :x

**Comment by dio-gh** [comment] 2022-05-01 01:44
#5990 improves this, but it's still not perfect. Even on native, there are discrepancies between SW and HW:

SW:
![image](https://user-images.githubusercontent.com/10439488/166128521-721243b9-37f5-47ce-b974-68b942f14a18.png)

HW without CRC hacks:
![image](https://user-images.githubusercontent.com/10439488/166128532-90c4125c-bba8-4959-854e-e14653db1f9a.png)

Note the metal bar in the middle, on the outside of the tube. It doesn't go all the way to the bottom of the screen.

The submarine scene also has minor discrepancies, the headlights sometimes flash on HW (regardless of the CRC hacks). However, not even SW is perfect:

![image](https://user-images.githubusercontent.com/10439488/166128571-71a5d596-35b2-44fc-9259-1537b9acf54f.png)

Note the handful of pixel columns on the left.

Overall, the problem should be improved after the aforementioned PR, but even on HW + native res there are still some problems, SW isn't perfect either, and HW + upscaling pretty much requires the use of the CRC hacks.

**Comment by Codexmsters** [comment] 2022-05-25 01:04
Duplicate of #6180

**Comment by kakashi314** [comment] 2023-01-06 15:01
Hardware:
![image](https://user-images.githubusercontent.com/121500889/211038255-fa6608cd-f8e1-40b4-abed-0d04116e40ee.png)
Software:
![image](https://user-images.githubusercontent.com/121500889/211038289-634a3e2d-0961-4330-bd0f-206e2962ce02.png)

**Comment by refractionpcsx2** [comment] 2023-01-06 15:07
Do you have a GS Dump @kakashi314  ?

**Comment by kakashi314** [comment] 2023-01-06 15:11
> Do you have a GS Dump @kakashi314 ?

[Crash Bandicoot - The Wrath of Cortex_SLUS-20238_20230106180940.gs.zip](https://github.com/PCSX2/pcsx2/files/10361060/Crash.Bandicoot.-.The.Wrath.of.Cortex_SLUS-20238_20230106180940.gs.zip)

**Comment by refractionpcsx2** [comment] 2023-01-06 15:16
Where is the human face thing you mentioned?

![image](https://user-images.githubusercontent.com/6278726/211041091-fe5d3317-7e41-4a3b-a7e5-639586cb40d0.png)

**Comment by refractionpcsx2** [comment] 2023-01-06 15:21
I don't see it? Can you point it out to me?

![image](https://user-images.githubusercontent.com/6278726/211042009-2e03dc29-8069-494e-bba8-586f660f6a3b.png)

**Comment by kakashi314** [comment] 2023-01-06 15:24
I don't know why they're not showing up on  your end. but here's a pic
![Crash Bandicoot - The Wrath of Cortex_SLUS-20238_20230106181755](https://user-images.githubusercontent.com/121500889/211042563-405b54f9-7dc0-455b-a07c-5310d4119b67.PNG)

**Comment by refractionpcsx2** [comment] 2023-01-06 15:26
You've Forced Bilinear texture filtering on. Please don't do that.

**Comment by kakashi314** [comment] 2023-01-06 15:27
> You've Forced Bilinear texture filtering on. Please don't do that.

Scale to host refresh rate seems to be the cause. very strange, i didn't know they can affect the gs

**Comment by refractionpcsx2** [comment] 2023-01-06 15:28
That makes no sense... and it doesn't here, only the option I said causes it

![image](https://user-images.githubusercontent.com/6278726/211043438-6ef7cdaf-cffa-4b7b-9066-3951eccdd93a.png)

**Comment by kakashi314** [comment] 2023-01-06 15:30
Indeed. but checking and unchecking scale to host refresh rate seems to remove it as well. so i thought that was the cause, my bad.

**Comment by kakashi314** [comment] 2023-01-06 15:39
Anyways disabling Depth emulation seems to restore the jellyfish. without causing any issues that i can notice :)

**Comment by Oymat** [comment] 2023-01-20 16:26
The sky in the first level is also not the right colour, missing the fog effects that the crc hack removed
Software:
![image](https://user-images.githubusercontent.com/122278577/213751031-2b4c4578-4411-48ba-b78d-f3cf0e89663a.png)


Hardware:
![Crash Bandicoot - The Wrath of Cortex_SLUS-20238_20230120192148](https://user-images.githubusercontent.com/122278577/213750725-95bb1d3f-ed31-47a1-bcc4-ef7f2114ee6a.png)

Gs dump:
[Crash Bandicoot - The Wrath of Cortex_SLUS-20238_20230120192148.gs.zip](https://github.com/PCSX2/pcsx2/files/10468064/Crash.Bandicoot.-.The.Wrath.of.Cortex_SLUS-20238_20230120192148.gs.zip)

**Closed** 2023-04-01 14:45 UTC
Labels: GS: Hardware, GS: Texture Cache, Needs Research
