### ISSUE TITLE
Vampire: Darkstalkers Collection (Low FPS and Textures wrong)

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2#3481] opened 2020-06-21 05:53 UTC
Issue:
![image](https://user-images.githubusercontent.com/24227051/85217526-460bd880-b392-11ea-99a1-c8ff1721e31e.png)

Gsdump:
[Vampire Darkstalkers Collection.zip](https://github.com/PCSX2/pcsx2/files/4808961/Vampire.Darkstalkers.Collection.zip)

Forum:
https://forums.pcsx2.net/Thread-Project-code-name-darkstalker-resurrection?pid=606836#pid606836
has a gsdx plugin. (Not a proper fix)

Workaround:
![image](https://user-images.githubusercontent.com/24227051/85217701-0d6cfe80-b394-11ea-9f09-f8cb32eaaaab.png)
Location: plugins\GSdx\Renderers\HW\GSTextureCache.cpp
Original:
![image](https://user-images.githubusercontent.com/24227051/85217712-27a6dc80-b394-11ea-90b8-9fb7f052bb06.png)

Needs a proper fix instead of this temporary workaround.

**Comment by Silanda** [comment] 2020-06-21 13:26
Street Fighter Alpha Anthology has the same problem.

Software mode works fine but it's best to set Rendering Threads to 0. This game really doesn't like the GS to be multithreaded it seems. That way it ran full speed on my retired 3570k.

**Comment by Immersion95** [comment] 2020-06-22 09:33
Yes I can confirm that software rendering + rendering thread to 0 is the solution.

**Comment by RedDevilus** [comment] 2020-06-22 12:24
Issue is about the HW mode primarily. SW mode not running out of the box just amplified the need of an issue on GitHub.

**Comment by tadanokojin** [comment] 2020-06-22 15:51
Sounds like a lot of synch causing slowdown in sw mode.
TBH code above is not really a hack, well it's complicated. It's like commenting out an optimization that is breaking some other stuff too.

**Comment by RedDevilus** [comment] 2020-06-22 16:00
Yeah it breaks other games but if you want a temporary workaround then that will work for now. It's just for something to look into in the future so that there is a proper fix.

**Comment by BinhoKof99** [comment] 2021-12-27 20:15
please solve the problems of these collections as they both have content that not one of the other games in the franchises has

**Comment by BinhoKof99** [comment] 2022-03-09 19:21
apparently they will never solve this problem

**Comment by F0bes** [comment] 2022-03-09 19:22
There's a lot of big things being worked on currently including an entire new UI. Sorry that no one is dedicating time to this single title in the entire PS2 library. Be patient or go elsewhere please.

**Comment by refractionpcsx2** [comment] 2022-03-09 19:24
If you're getting shitty about us not fixing your game, you have 2 options.

1. Go fuck yourself and find another emulator, we do this in our free time for free, we are not beholden to your whims.
2. Fix it yourself.

**Comment by RedDevilus** [comment] 2022-03-09 20:02
Mindset:
https://raccoon.onyxbits.de/blog/reactions-bugreport-free-support/

**Comment by Tiger3784** [comment] 2022-05-16 05:25
I wanted to modify the textures of these collections with waifu2x-caffe but the emulator doesn't dump or load the textures in software mode

**Comment by coornio** [comment] 2022-05-17 10:32
> I wanted to modify the textures of these collections with waifu2x-caffe but the emulator doesn't dump or load the textures in software mode

@Tiger3784 Don't hijack/revive github issues for unrelated problems. Visit the discord if you have questions about things.

**Comment by Immersion95** [comment] 2022-08-27 08:01
Since the latest updates : 
-SW speed is 2x-3x what it was (we needed rendering thread to 0 then)
-HW speed is on par with SW
-Res x3 or x5 prevents the characters from having stripes
-Background are still messed up

This also applies to Street Fighter Zero Generations/Alpha Anthology

**Comment by Mrlinkwii** [comment] 2023-05-13 20:54
can this and Street Fighter Zero Generations/Alpha Anthology be check on latest nightly :)

**Comment by Silanda** [comment] 2023-05-13 23:57
Vastly improved, though Vampire Savior has some issues at the top of the screen.

**Comment by Mrlinkwii** [comment] 2023-05-14 00:05
> Vastly improved, though Vampire Savior has some issues at the top of the screen.

Can I have a gs dump for that ?

**Comment by Silanda** [comment] 2023-05-14 00:16
Here you go.

![Vampire Darkstalkers Collection_SLPM-65998_20230514011504](https://github.com/PCSX2/pcsx2/assets/4227434/afa50f05-508e-4a16-b3f4-c5a602519e55)

[Vampire Darkstalkers Collection_SLPM-65998_20230514011504.gs.zip](https://github.com/PCSX2/pcsx2/files/11470847/Vampire.Darkstalkers.Collection_SLPM-65998_20230514011504.gs.zip)

**Comment by refractionpcsx2** [comment] 2023-05-14 00:52
I see what's going on. So it's moving the framebuffer inside itself (moving it left), but as far as it's concerned it's still being drawn.  I'll add a check to see if it's moving data between itself, then force the entire thing to flush.

**Comment by Mrlinkwii** [comment] 2023-05-14 10:24
@Silanda  can you try #8854  when you get a moment :)

**Comment by Silanda** [comment] 2023-05-14 13:39
I've done a quick test of #8854 on the Darkstalkers Collection and the Street Fighter Anthology, and all looks good as far as I can see.

**Comment by Immersion95** [comment] 2023-05-14 20:53
It now renders perfectly at HW/Native.

Unfortunately stripes appear heavily at any upscaled resolutions which didn't appear on previous builds at x3/x5 (it also affects SFIII). This has nothing to do with this PR though and was introduced months ago.

While it's great that it works with HW, there is no practical benefit over SW if upscaled res is not working.

At native : Character sprites resolution doesn't match the output resolution so it's not pixel perfect like the arcade version.

**Comment by refractionpcsx2** [comment] 2023-05-14 20:58
On my PR?

![image](https://github.com/PCSX2/pcsx2/assets/6278726/d59fc977-9566-4a1b-9d24-046a6c9dff8e)

What's wrong with that, sorry?

**Comment by Immersion95** [comment] 2023-05-14 21:37
> On my PR?
> 
> ![image](https://user-images.githubusercontent.com/6278726/238209231-d59fc977-9566-4a1b-9d24-046a6c9dff8e.png)
> 
> What's wrong with that, sorry?
> 
> It could be street fighter needs round sprite half as well.

It's perfect with your PR, Street Fighter Alpha Anthology does need Round Sprite Half :).

**Comment by refractionpcsx2** [comment] 2023-05-14 21:39
ok cool, thanks :)

What are the Street Fighter games which need round sprite half? Then we can add them to the GameDB.

**Comment by Immersion95** [comment] 2023-05-14 21:48
> ok cool, thanks :)
> 
> What are the Street Fighter games which need round sprite half? Then we can add them to the GameDB.

Here it is :) : 

SLES-54085:
  name: "Street Fighter Alpha Anthology"
SLUS-21317:
  name: "Street Fighter Alpha Anthology"
SLPM-66409:
  name: "Street Fighter Zero - Fighters Generation"
SLPM-66854:
  name: "Street Fighter Zero - Fighters Generation [Best Price]"

**Comment by refractionpcsx2** [comment] 2023-05-14 22:02
Cool, I'll add those (or one of the tester/db dudes) once my PR merges :)

**Closed** 2023-05-16 00:20 UTC
Labels: Bug, GS: Texture Cache
