### ISSUE TITLE
GSDX: Flames are incorrectly rendererd on Ben 10 Alien Force : Vilgax Attacks

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#1438] opened 2016-06-29 11:50 UTC
**Description of the Issue**:

The flames and sparks are incorrectly rendered on the following game on all of the hardware renderers. However, they're rendered correctly on the software renderer.

**Comparison Pictures**:

* ``OpenGL (Hardware mode)``

![Ben10_vilgax_hardware_mode.png](http://ultraimg.com/images/2016/06/29/Ben10_vilgax_hardware_mode.png)

* ``Software Renderer``

![Ben10_vilgax_software_mode.png](http://ultraimg.com/images/2016/06/29/Ben10_vilgax_software_mode.png)

* The spark issue would be a bit hard to notice just by looking at the pictures, here's a GIF to easily  notice it.

![GIF_Ben10_Vilgax_Attacks.gif](http://ultraimg.com/images/2016/06/29/GIF_Ben10_Vilgax_Attacks.gif)

**Test Case**: [**Master branch**](https://github.com/PCSX2/pcsx2) with head at https://github.com/PCSX2/pcsx2/commit/1f4f55bcc9cf6ecf4b9109e76a06c5e7e3123857

**GS Dump**: [**Download Link**](https://www.dropbox.com/s/oscogtyqko1f759/Ben10_Vilgax_Attacks_Flame_issue.rar?dl=0)

**Comment by prafullpcsx2** [comment] 2016-07-04 05:27
Most probably it's a regression caused by https://github.com/PCSX2/pcsx2/commit/59ef668fd2d0d599b3667e715a102f756ac05dd3

**Comment by ssakash** [comment] 2016-07-04 08:26
Confirmed , #1222 is the culprit. Nice work on finding it prafull !

**Comment by gregory38** [comment] 2016-07-05 07:35
Hum, I would be very lucky but it might worth to check #1434

**Comment by ssakash** [comment] 2016-07-06 08:01
#1434 doesn't fix the issue.

FWIW, I tried to bisect the issue by checking out the status of detached head:

``git checkout  d922225e692690d7d7bb6fe5e835c06beddb50cd``
**HEAD at https://github.com/PCSX2/pcsx2/pull/1222/commits/d922225e692690d7d7bb6fe5e835c06beddb50cd** : The issue is present.

`` git checkout 9aea76b0e80b87a0362263a1437cd7476e18138a``
**HEAD at https://github.com/PCSX2/pcsx2/pull/1222/commits/9aea76b0e80b87a0362263a1437cd7476e18138a** : The issue doesn't exist.

So the [regression](http://t2.gstatic.com/images?q=tbn:ANd9GcTQCEcyGKxhNVTSDbqgKu8XILrVvR-AVLB570mOKNs-y_3GwTb_) was caused by https://github.com/PCSX2/pcsx2/pull/1222/commits/d922225e692690d7d7bb6fe5e835c06beddb50cd

**Comment by ssakash** [comment] 2016-07-08 10:01
@gregory38 

Here's a summary of the issue after some debugging : 

> TC: Dirty in the middle of Target(Color) 94 (0x3000)
TC: Dirty in the middle of Target(Color) 411 (0x3040)
TC: Dirty in the middle of Target(Color) 440 (0x3020)
TC: Dirty in the middle of Target(Color) 411 (0x3040)
TC: Dirty in the middle of Target(Color) 94 (0x3000)

```
 Texture base pointer : 12288 , Texture end block : 13312 , TW base pointer : 13212 , TW end block : 13224 
 Texture base pointer : 13184 , Texture end block : 13312 , TW base pointer : 13212 , TW end block : 13224 
 Texture base pointer : 13088 , Texture end block : 13344 , TW base pointer : 13120 , TW end block : 13248 
 Texture base pointer : 13024 , Texture end block : 13536 , TW base pointer : 13216 , TW end block : 13225 
```

**Note**:
``Texture base pointer`` = ``m_TEX0.TBP0``
``Texture end block `` = ``m_end_block``
``TW base pointer`` = value of ``bw`` passed in ``GSTextureCache::Target::Inside()``
``TW end block`` = *[value of block](https://github.com/PCSX2/pcsx2/pull/1434/files#diff-7436adf7406199c56fd673a16e6086b2R1847) in* **#1434**

Basically the issue is caused due to pushing back a dirty rect when we detect a write in the middle of the target buffer.

**[Line 837 :](https://github.com/PCSX2/pcsx2/blob/0a4938e6cf5e0fa22463b4145db41b5d06f3ff13/plugins/GSdx/GSTextureCache.cpp#L837)**
```
t->m_dirty.push_back(GSDirtyRect(GSVector4i(r.left, r.top + y, r.right, r.bottom + y), psm));
``` 

So the solution would be to not push back the dirty rect at certain scenarios to resolve the following issue.

_**Test Case**:_

The following patch resolves the issue as this allows the dirty rect push only for a type of ``DepthStencil``. (However, not the right solution)
```
C:\Users\user\Documents\GitHub\pcsx2 [Ben10_TC]> git diff HEAD~1..HEAD
diff --git a/plugins/GSdx/GSTextureCache.cpp b/plugins/GSdx/GSTextureCache.cpp
index 3c499dc..bd172f3 100644
--- a/plugins/GSdx/GSTextureCache.cpp
+++ b/plugins/GSdx/GSTextureCache.cpp
@@ -827,15 +827,12 @@ void GSTextureCache::InvalidateVideoMem(GSOffset* off, const GSVector4i& rect, b
                                        uint32 rowsize = bw * 8192u;
                                        uint32 offset = (uint32)((bp - t->m_TEX0.TBP0) * 256);

-                                       if(rowsize > 0 && offset % rowsize == 0) {
+                                       if(rowsize > 0 && offset % rowsize == 0 && type != RenderTarget ) {
                                                GL_CACHE("TC: Dirty in the middle of Target(%s) %d (0x%x)", to_string(type),
                                                                t->m_texture ? t->m_texture->GetID() : 0,
                                                                t->m_TEX0.TBP0);
```

I hope the summary helps, it took me two hours to properly analyze the source of the issue :P

**Comment by gregory38** [comment] 2016-07-08 10:31
Sorry, I could have tell you this explanation (without number). You need to debug it further ;)

Potentially it could be an issue with limit `<` vs `<=`

Where are the valid data of the target ? So what is the base block address of the target, the real end block address of target (you might need to dump the image to see the real size).

Then, is the write really a write in the middle of the target ?

Some explanations (check gsdx doc directory too):
* render targets (aka framebuffer) are stored (and written) by the GPU. However in the real GS, the real info ought to be in the GS memory.
* In the HW renderer, we don't compute the correct value of the GS mem, data are only on the GPU. So `input texture (not previous target/depth)` are in both the GS mem and GPU mem. Target/Depth only GPU. 

So when EE write in the GS memory block. You need to dirty the data on the GPU and write the value in GS mem. Later if you want to reuse the GPU data, you need to upload the new value from the GS memory.

**Comment by ssakash** [comment] 2016-07-22 10:49
> Where are the valid data of the target ? So what is the base block address of the target, the real end block address of target (you might need to dump the image to see the real size).

Here's a dump of the texture **(64x32)**
![TextureCache.png](http://ultraimg.com/images/2016/07/22/TextureCache.png)

**Information**:

``Texture Buffer pointer : 15488``
``Texture Buffer end block : 16000``
``Start address of the texture write: 15904``
``End address of the texture write: 15968``

> Then, is the write really a write in the middle of the target ?

Yes, according to the information we could conclude that it's on the middle of the texture buffer. Assuming the code for ``GSTextureCache::Target::Inside()`` is correct. so the question is, why does dirtying it cause the issue ?

Also thanks for the other information ;)

**Comment by gregory38** [comment] 2016-07-24 19:01
Do you have the id number of the bad draw call ? This way I can look in your gs dump.
You can see the id of the openGL log (FYI, the id is incremented 3 times by GS draw)

**Comment by gregory38** [comment] 2016-08-17 18:24
I gave a look. And potentially I didn't trace the same issue. Anyway something is strange. Previous rendering is 64,64 (or maybe 65?) pixels. End block seeems to imply 4 pages instead of 2. Maybe end block info is wrong.

```
T:Oth	ID:2153	S:Info	=> TC: Lookup Target(Color) 1280x1024, hit: 267 (0x3a40, C_32)
T:Oth	ID:2153	S:Info	=> TC: src hit: 249 (0x3a80, P_4)
T:Oth	ID:2156	S:Info	=> Write! ...  => 0x3a9c W:1 F:C_32 (DIR 00), dPos(0 0) size(16 16)
T:Oth	ID:2156	S:Info	=> Write! ...  => 0x3a80 W:1 F:C_32 (DIR 00), dPos(0 0) size(32 32)
T:Oth	ID:2156	S:Info	=> TC: Dirty in the middle of Target(Color) 267 (0x3a40->0x3ac0)
T:Oth	ID:2156	S:Info	=> TC: Dirty in the middle of Target(Color) 289 (0x3a60->0x3b60)
```

Here a bad texture. It was removed above.
```
T:Oth	ID:2201	S:Info	=> TC: src miss (0x3a40, C_32)
```

**Comment by gregory38** [comment] 2016-08-17 19:12
I think I begin to understand. The game will do
* render 128x128 texture
* use it for a first effect
* render 64x64 texture in same target
* upload a new content in the last part of the target which delete previous rendering.
* use it for a 2nd effect

Clever idea are welcome

**Comment by gregory38** [comment] 2016-08-17 19:33
Hum, so far I have 2 ideas
* skip the dirty in the middle if bw (buffer width is 1) i.e. RT is quite small
* reset m_valid to 0 when we hit the RT with another bw. Typically here, the game will first use 2 for the first effect and then 1 for the next. Hum, it seems risky due to postprocessing effect that could use a size of 1 too.

**Comment by gregory38** [comment] 2016-08-28 14:51
I pushed the fix to master. It must be good now.

**Closed by gregory38** 2016-08-28 14:51 UTC
Labels: Bug, GSdx: Hardware, GSdx: Texture Cache, Plugin: GSdx, Regression
