### ISSUE TITLE
[Feature Request]: TopazTK´s texture dump/replacer

### ISSUE THREAD

**Issue by PipoCrazy** [PCSX2/pcsx2#5305] opened 2022-01-10 04:00 UTC
### Description

I´ve been following the project for a while, but now I can´t find the option to export or import textures...

What happened to this plugin?

I have just read some drama about it going to "PCSX2-EX" since there was some random problem, but, again, I have no idea about PCSX2-EX, nor if it is still in development.

Where and how could I get the plugin? Is it being developed at all? Will it ever be put into the original PCSX2 emulator?

Thank you in advance.

### Reason

I want to make PS2 games more HD, if you know what I mean... Dolphin GC emulator also has this feature already in it.

### Examples

https://www.youtube.com/watch?v=1_ad_NnMv4c&t=46s

**Comment by MrCK1** [comment] 2022-01-10 04:06
Sorry, the developer abandoned the project some time ago. You will have to wait until somebody else decides to make one. Dupe of https://github.com/PCSX2/pcsx2/issues/5046

**Closed by MrCK1** 2022-01-10 04:06 UTC
Labels: Enhancement / Feature Request
